SC.stringsFor("zh-Hans", {
              "DG.fileMenu.menuItem.newDocument": "新建",
              "DG.fileMenu.menuItem.openDocument": "打开",
              "DG.fileMenu.menuItem.closeDocument": "关闭",
              "DG.fileMenu.menuItem.importFile": "导入",
              "DG.fileMenu.menuItem.revertTo": "恢复",
              "DG.fileMenu.menuItem.revertToOpened": "最近打开状态",
              "DG.fileMenu.menuItem.revertToShared": "共享视图",
              "DG.fileMenu.menuItem.saveDocument": "保存...",
              "DG.fileMenu.menuItem.copyDocument": "创建复制本",
              "DG.fileMenu.menuItem.share": "共享...",
              "DG.fileMenu.menuItem.shareGetLink": "获取共享视图的链接",
              "DG.fileMenu.menuItem.shareUpdate": "更新共享视图",
              "DG.fileMenu.menuItem.renameDocument": "重命名",
              "DG.main.userEntryView.title": "想要做什么？",
              "DG.main.userEntryView.openDocument": "打开文件或浏览示例",
              "DG.main.userEntryView.newDocument": "创建新文件",
              "DG.mainPage.mainPane.undoButton.title": "撤销",
              "DG.mainPage.mainPane.undoButton.toolTip": "撤销上一个操作",
              "DG.mainPage.mainPane.redoButton.title": "恢复",
              "DG.mainPage.mainPane.redoButton.toolTip": "恢复上一个未完成操作",
              "DG.mainPage.mainPane.versionString": "版本%@（%@）",
              "DG.mainPage.mainPane.messageView.value": "很遗憾，此浏览器目前不支持CODAP。Firefox 46+, Chrome 50+, Windows Edge 14+以及Safari 10+支持CODAP。目前，其他浏览器没有被激活支持CODAP。",
              "DG.mainPage.titleBar.saved": "文件已保存！",
              "DG.mainPage.mainPane.versionString.IS_BUILD": "版本%@（%@IS）",
              "DG.mainPage.mainPane.versionString.SRRI_BUILD": "版本%@（%@.srri10）",
              "DG.AppController.resetData.title": "清除数据",
              "DG.AppController.resetData.toolTip": "删除当前文件中所有数据",
              "DG.AppController.resetData.warnMessage": "确定要删除此文件中所有数据吗？",
              "DG.AppController.resetData.warnDescription": "此操作不可撤销。",
              "DG.AppController.resetData.okButtonTitle": "是，删除数据",
              "DG.AppController.resetData.cancelButtonTitle": "否，保留数据",
              "DG.AppController.closeDocument.warnMessage": "关闭当前文件且不保存？",
              "DG.AppController.closeDocument.warnDescription": "此操作不可撤销。",
              "DG.AppController.closeDocument.okButtonTitle": "关闭",
              "DG.AppController.closeDocument.cancelButtonTitle": "取消",
              "DG.AppController.beforeUnload.confirmationMessage": "此文件包含未保存更改。",
              "DG.AppController.optionMenuItems.reportProblem": "发送反馈...",
              "DG.AppController.optionMenuItems.viewWebPage": "显示网页...",
              "DG.AppController.optionMenuItems.configureGuide": "配置指南...",
              "DG.AppController.optionMenuItems.about": "有关CODAP...",
              "DG.AppController.optionMenuItems.releaseNotes": "什么是新的？",
              "DG.AppController.optionMenuItems.help": "帮助页和视频",
              "DG.AppController.optionMenuItems.toWebSite": "CODAP项目",
              "DG.AppController.exportDocument.prompt": "文件名：",
              "DG.AppController.exportCaseData.prompt": "导出案例数据从：",
              "DG.AppController.exportDocument.exportTitle": "导出",
              "DG.AppController.exportDocument.exportTooltip": "导出数据到文件",
              "DG.AppController.exportDocument.cancelTitle": "取消",
              "DG.AppController.exportDocument.cancelTooltip": "取消导出",
              "DG.AppController.feedbackDialog.dialogTitle": "提供反馈",
              "DG.AppController.feedbackDialog.subHeaderText": "您的反馈对我们很重要！",
              "DG.AppController.feedbackDialog.messageText": "请帮助我们持续改进此项目。问题、错误报告和功能需求都非常欢迎。谢谢！",
              "DG.AppController.feedbackDialog.subjectHint": "您的反馈是关于",
              "DG.AppController.feedbackDialog.feedbackHint": "细节",
              "DG.AppController.feedbackDialog.submitFeedbackButton": "提交",
              "DG.AppController.feedbackDialog.cancelFeedbackButton": "取消",
              "DG.AppController.showWebSiteTitle": "有关CODAP",
              "DG.AppController.showHelpTitle": "CODAP相关帮助",
              "DG.AppController.showAboutTitle": "有关CODAP",
              "DG.AppController.showReleaseNotesTitle": "CODAP发布说明",
              "DG.AppController.dropFile.error": "错误：%@1",
              "DG.AppController.dropFile.unknownFileType": "无法导入已删除的文件类型",
              "DG.AppController.validateDocument.missingRequiredProperty": "找不到所需性质：%@1",
              "DG.AppController.validateDocument.unexpectedProperty": "未预料顶层属性：%@1",
              "DG.AppController.validateDocument.unresolvedID": "未解决id：%@1",
              "DG.AppController.validateDocument.parseError": "文件解析错误：%@1",
              "DG.AppController.validateDocument.invalidDocument": "无效JSON文件：%@1",
              "DG.AppController.openDocument.error.general": "不能打开文件",
              "DG.AppController.openDocument.error.invalid_format": "CODAP不能读取此类型文件",
              "DG.AppController.createDataSet.initialAttribute": "变量名称",
              "DG.AppController.createDataSet.name": "新建数据集",
              "DG.AppController.createDataSet.collectionName": "个案",
              "DG.AppController.caseTableMenu.newDataSet": "--新--",
              "DG.SingleTextDialog.okButton.title": "好",
              "DG.SingleTextDialog.cancelButton.title": "取消",
              "DG.SingleTextDialog.cancelButton.toolTip": "关闭对话框并不作任何更改",
              "DG.DocumentController.calculatorTitle": "计算器",
              "DG.DocumentController.caseTableTitle": "个案表",
              "DG.DocumentController.graphTitle": "图表",
              "DG.DocumentController.sliderTitle": "滑块",
              "DG.DocumentController.textTitle": "文字",
              "DG.DocumentController.mapTitle": "地图",
              "DG.DocumentController.enterURLPrompt": "输入要显示的网页网址",
              "DG.DocumentController.enterViewWebPageOKTip": "显示给定网址的网页",
              "DG.Document.defaultDocumentName": "未命名文件",
              "DG.Document.documentName.toolTip": "点击编辑文件名",
              "DG.SliderView.thumbView.toolTip": "拖动更改滑块值",
              "DG.SliderView.startButton.toolTip": "开始/停止动画",
              "DG.ToolButtonData.tableButton.title": "表格",
              "DG.ToolButtonData.tableButton.toolTip": "为每个数据集打开个案表格（ctrl-alt-t）",
              "DG.ToolButtonData.graphButton.title": "图表",
              "DG.ToolButtonData.graphButton.toolTip": "制作图表（ctrl-alt-g）",
              "DG.ToolButtonData.sliderButton.title": "滑块",
              "DG.ToolButtonData.sliderButton.toolTip": "制作滑块（ctrl-alt-s）",
              "DG.ToolButtonData.calcButton.title": "计算器",
              "DG.ToolButtonData.calcButton.toolTip": "打开/关闭计算器（ctrl-alt-c）",
              "DG.ToolButtonData.textButton.title": "文字",
              "DG.ToolButtonData.textButton.toolTip": "制作文字对象（ctrl-alt-shift-t）",
              "DG.ToolButtonData.mapButton.title": "地图",
              "DG.ToolButtonData.mapButton.toolTip": "制作地图",
              "DG.ToolButtonData.optionMenu.title": "选项",
              "DG.ToolButtonData.optionMenu.toolTip": "显示网站，配置指南...",
              "DG.ToolButtonData.tileListMenu.title": "清单",
              "DG.ToolButtonData.tileListMenu.toolTip": "显示文件中清单列表",
              "DG.ToolButtonData.guideMenu.title": "指南",
              "DG.ToolButtonData.guideMenu.toolTip": "显示此活动指南并进行导航",
              "DG.ToolButtonData.guideMenu.showGuide": "显示指南",
              "DG.ToolButtonData.help.title": "帮助",
              "DG.ToolButtonData.help.toolTip": "为CODAP提供帮助，了解CODAP项目",
              "DG.Slider.multiples": "限制为：",
              "DG.Slider.maxPerSecond": "最大动画帧数/秒：",
              "DG.Slider.direction": "动画方向：",
              "DG.Slider.backAndForth": "往返",
              "DG.Slider.lowToHigh": "从低到高",
              "DG.Slider.highToLow": "从高到低",
              "DG.Slider.mode": "动画重复：",
              "DG.Slider.nonStop": "不停",
              "DG.Slider.onceOnly": "仅限一次",
              "DG.Undo.exceptionOccurred": "尝试撤销时发生错误。",
              "DG.Redo.exceptionOccurred": "尝试恢复时发生错误。",
              "DG.Undo.componentMove": "撤销移动组件",
              "DG.Redo.componentMove": "恢复移动组件",
              "DG.Undo.componentResize": "撤销调整组件大小",
              "DG.Redo.componentResize": "恢复调整组件大小",
              "DG.Undo.axisDilate": "撤销调整缩放轴",
              "DG.Redo.axisDilate": "恢复调整缩放轴",
              "DG.Undo.axisRescaleFromData": "撤销调整缩放轴",
              "DG.Redo.axisRescaleFromData": "恢复调整缩放轴",
              "DG.Undo.axisDrag": "撤销拖动轴",
              "DG.Redo.axisDrag": "恢复拖动轴",
              "DG.Undo.axisAttributeChange": "撤销更改轴变量",
              "DG.Redo.axisAttributeChange": "恢复更改轴变量",
              "DG.Undo.axisAttributeAdded": "撤销增加轴变量",
              "DG.Redo.axisAttributeAdded": "恢复增加轴变量",
              "DG.Undo.toggleComponent.add.calcView": "撤销显示计算器",
              "DG.Redo.toggleComponent.add.calcView": "恢复显示计算器",
              "DG.Undo.toggleComponent.delete.calcView": "撤销隐藏计算器",
              "DG.Redo.toggleComponent.delete.calcView": "恢复隐藏计算器",
              "DG.Undo.caseTable.open": "撤销显示案例表",
              "DG.Redo.caseTable.open": "恢复显示案例表",
              "DG.Undo.caseTable.editAttribute": "撤销编辑案例表格变量",
              "DG.Redo.caseTable.editAttribute": "恢复编辑案例表变量",
              "DG.Undo.caseTable.createAttribute": "撤销创建案例表格变量",
              "DG.Redo.caseTable.createAttribute": "恢复创建案例表格变量",
              "DG.Undo.caseTable.editAttributeFormula": "撤销编辑案例表格变量公式",
              "DG.Redo.caseTable.editAttributeFormula": "恢复编辑案例表格变量公式",
              "DG.Undo.caseTable.editCellValue": "撤销编辑案例表单元格值",
              "DG.Redo.caseTable.editCellValue": "恢复编辑案例表单元格值",
              "DG.Undo.caseTable.sortCases": "撤销分类案例",
              "DG.Redo.caseTable.sortCases": "恢复分类案例",
              "DG.Undo.caseTable.deleteAttribute": "撤销删除案例表格变量",
              "DG.Redo.caseTable.deleteAttribute": "恢复删除案例表格变量",
              "DG.Undo.caseTable.createCollection": "撤销创建新集合",
              "DG.Redo.caseTable.createCollection": "恢复创建新集合",
              "DG.Undo.caseTable.collectionNameChange": "撤销重新命名新集合",
              "DG.Redo.caseTable.collectionNameChange": "恢复命名新集合",
              "DG.Undo.caseTable.createNewCase": "撤销创建新案例",
              "DG.Redo.caseTable.createNewCase": "恢复创建新案例",
              "DG.Undo.caseTable.insertCases": "撤销插入案例",
              "DG.Redo.caseTable.insertCases": "恢复插入案例",
              "DG.Undo.caseTable.groupToggleExpandCollapseAll": "撤销切换展开/折叠全部",
              "DG.Redo.caseTable.groupToggleExpandCollapseAll": "恢复切换展开/折叠全部",
              "DG.Undo.caseTable.expandCollapseOneCase": "撤销组的展开或折叠",
              "DG.Redo.caseTable.expandCollapseOneCase": "恢复组的展开或折叠",
              "DG.Undo.caseTable.resizeColumns": "撤销自动调整所有列大小",
              "DG.Redo.caseTable.resizeColumns": "恢复自动调整所有列大小",
              "DG.Undo.document.share": "撤销共享文档",
              "DG.Redo.document.share": "恢复共享文档",
              "DG.Undo.document.unshare": "撤销停止共享文档",
              "DG.Redo.document.unshare": "恢复停止共享文档",
              "DG.Undo.game.add": "撤销添加游戏到文档",
              "DG.Redo.game.add": "恢复添加游戏到文档",
              "DG.Undo.graph.showCount": "撤销显示计数",
              "DG.Redo.graph.showCount": "恢复显示计数",
              "DG.Undo.graph.hideCount": "撤销隐藏计数",
              "DG.Redo.graph.hideCount": "恢复显示计数",
              "DG.Undo.graph.showPercent": "撤销显示百分比",
              "DG.Redo.graph.showPercent": "恢复显示百分比",
              "DG.Undo.graph.hidePercent": "撤销隐藏百分比",
              "DG.Redo.graph.hidePercent": "恢复显示百分比",
              "DG.Undo.graph.showMovableLine": "撤销显示可动线",
              "DG.Redo.graph.showMovableLine": "恢复显示可动线",
              "DG.Undo.graph.hideMovableLine": "撤销隐藏可动线",
              "DG.Redo.graph.hideMovableLine": "恢复隐藏可动线",
              "DG.Undo.graph.lockIntercept": "撤销锁定线截距",
              "DG.Redo.graph.lockIntercept": "恢复锁定线截距",
              "DG.Undo.graph.unlockIntercept": "撤销解锁线截距",
              "DG.Redo.graph.unlockIntercept": "恢复解锁线截距",
              "DG.Undo.graph.showPlotFunction": "撤销显示绘图函数",
              "DG.Redo.graph.showPlotFunction": "恢复显示绘图函数",
              "DG.Undo.graph.hidePlotFunction": "撤销隐藏绘图函数",
              "DG.Redo.graph.hidePlotFunction": "恢复隐藏绘图函数",
              "DG.Undo.graph.changePlotFunction": "撤销更改绘图函数",
              "DG.Redo.graph.changePlotFunction": "恢复更改绘图函数",
              "DG.Undo.graph.showPlotValue": "撤销显示标绘值",
              "DG.Redo.graph.showPlotValue": "恢复显示标绘值",
              "DG.Undo.graph.hidePlotValue": "撤销隐藏标绘值",
              "DG.Redo.graph.hidePlotValue": "恢复隐藏标绘值",
              "DG.Undo.graph.changePlotValue": "撤销更改标绘值",
              "DG.Redo.graph.changePlotValue": "恢复更改标绘值",
              "DG.Undo.graph.showConnectingLine": "撤销显示连接线",
              "DG.Redo.graph.showConnectingLine": "恢复显示连接线",
              "DG.Undo.graph.hideConnectingLine": "撤销隐藏连接线",
              "DG.Redo.graph.hideConnectingLine": "恢复隐藏连接线",
              "DG.Undo.graph.showLSRL": "撤销显示最小二乘法直线",
              "DG.Redo.graph.showLSRL": "恢复显示最小二乘法直线",
              "DG.Undo.graph.hideLSRL": "撤销隐藏最小二乘法直线",
              "DG.Redo.graph.hideLSRL": "恢复隐藏最小二乘法直线",
              "DG.Undo.graph.showSquares": "撤销显示平方值",
              "DG.Redo.graph.showSquares": "恢复显示平方值",
              "DG.Undo.graph.hideSquares": "撤销隐藏平方值",
              "DG.Redo.graph.hideSquares": "恢复隐藏平方值",
              "DG.Undo.graph.showPlottedMean": "撤销显示均值",
              "DG.Redo.graph.showPlottedMean": "恢复显示均值",
              "DG.Undo.graph.hidePlottedMean": "撤销隐藏均值",
              "DG.Redo.graph.hidePlottedMean": "恢复隐藏均值",
              "DG.Undo.graph.showPlottedMedian": "撤销显示中位数",
              "DG.Redo.graph.showPlottedMedian": "恢复显示中位数",
              "DG.Undo.graph.hidePlottedMedian": "撤销隐藏中位数",
              "DG.Redo.graph.hidePlottedMedian": "恢复隐藏中位数",
              "DG.Undo.graph.showPlottedStDev": "撤销显示标准方差",
              "DG.Redo.graph.showPlottedStDev": "恢复显示标准方差",
              "DG.Undo.graph.hidePlottedStDev": "撤销隐藏标准方差",
              "DG.Redo.graph.hidePlottedStDev": "恢复隐藏标准方差",
              "DG.Undo.graph.showPlottedIQR": "撤销显示四分位间距",
              "DG.Redo.graph.hidePlottedIQR": "恢复隐藏四分位间距",
              "DG.Undo.graph.hidePlottedIQR": "撤销隐藏四分位间距",
              "DG.Redo.graph.showPlottedIQR": "恢复显示四分位间距",
              "DG.Undo.graph.addMovableValue": "撤销添加可移动值",
              "DG.Redo.graph.addMovableValue": "恢复添加可移动值",
              "DG.Undo.graph.removeMovableValue": "撤销删除可移动值",
              "DG.Redo.graph.removeMovableValue": "恢复删除可移动值",
              "DG.Undo.graph.moveMovableValue": "撤销移动可移动值",
              "DG.Redo.graph.moveMovableValue": "恢复移动可移动值",
              "DG.Undo.graph.changePointColor": "撤销更改数据颜色",
              "DG.Redo.graph.changePointColor": "恢复更改数据颜色",
              "DG.Undo.graph.changeStrokeColor": "撤销更改笔触颜色",
              "DG.Redo.graph.changeStrokeColor": "恢复更改笔触颜色",
              "DG.Undo.graph.changePointSize": "撤销更改点的大小",
              "DG.Redo.graph.changePointSize": "恢复更改点的大小",
              "DG.Undo.graph.changeAttributeColor": "撤销更改变量颜色",
              "DG.Redo.graph.changeAttributeColor": "恢复更改变量颜色",
              "DG.Undo.graph.changeBackgroundColor": "撤销更改图形背景色",
              "DG.Redo.graph.changeBackgroundColor": "恢复更改图形背景色",
              "DG.Undo.graph.toggleTransparent": "撤销切换图的透明度",
              "DG.Redo.graph.toggleTransparent": "恢复切换图的透明度",
              "DG.Undo.guide.show": "撤销显示指南",
              "DG.Redo.guide.show": "恢复显示指南",
              "DG.Undo.guide.navigate": "撤销更改指南页",
              "DG.Redo.guide.navigate": "恢复更改指南页",
              "DG.Undo.hideSelectedCases": "撤销隐藏所选案例",
              "DG.Redo.hideSelectedCases": "恢复隐藏所选案例",
              "DG.Undo.hideUnselectedCases": "撤销隐藏未选案例",
              "DG.Redo.hideUnselectedCases": "恢复隐藏未选案例",
              "DG.Undo.enableNumberToggle": "撤销显示上层数据集可见切换",
              "DG.Redo.enableNumberToggle": "恢复显示上层数据集可见切换",
              "DG.Undo.disableNumberToggle": "撤销隐藏上层可见切换",
              "DG.Redo.disableNumberToggle": "恢复隐藏上层可见切换",
              "DG.Undo.interactiveUndoableAction": "撤销交互中操作",
              "DG.Redo.interactiveUndoableAction": "恢复交互中操作",
              "DG.Undo.showAllCases": "撤销显示所有案例",
              "DG.Redo.showAllCases": "恢复显示所有案例",
              "DG.Undo.map.create": "撤销添加地图",
              "DG.Redo.map.create": "恢复添加地图",
              "DG.Undo.map.fitBounds": "撤销调整地图大小",
              "DG.Redo.map.fitBounds": "恢复调整地图大小",
              "DG.Undo.map.pan": "撤销平移地图",
              "DG.Redo.map.pan": "恢复平移地图",
              "DG.Undo.map.zoom": "撤销缩放地图",
              "DG.Redo.map.zoom": "恢复缩放地图",
              "DG.Undo.map.showGrid": "撤销显示地图上网格",
              "DG.Redo.map.showGrid": "恢复显示地图上网格",
              "DG.Undo.map.hideGrid": "撤销隐藏地图上网格",
              "DG.Redo.map.hideGrid": "恢复隐藏地图上网格",
              "DG.Undo.map.changeGridSize": "撤销更改地图网格大小",
              "DG.Redo.map.changeGridSize": "恢复更改地图网格大小",
              "DG.Undo.map.showPoints": "撤销显示地图上的点",
              "DG.Redo.map.showPoints": "恢复显示地图上的点",
              "DG.Undo.map.hidePoints": "撤销隐藏地图上的点",
              "DG.Redo.map.hidePoints": "恢复隐藏地图上的点",
              "DG.Undo.map.showLines": "撤销显示地图上的线",
              "DG.Redo.map.showLines": "恢复显示地图上的线",
              "DG.Undo.map.hideLines": "撤销隐藏地图上的线",
              "DG.Redo.map.hideLines": "恢复隐藏地图上的线",
              "DG.Undo.map.changeBaseMap": "撤销更改地图背景",
              "DG.Redo.map.changeBaseMap": "恢复更改地图背景",
              "DG.Undo.textComponent.create": "撤销添加文本对象",
              "DG.Redo.textComponent.create": "恢复添加文本对象",
              "DG.Undo.textComponent.edit": "撤销编辑文本",
              "DG.Redo.textComponent.edit": "恢复编辑文本",
              "DG.Undo.sliderComponent.create": "撤销添加滑块",
              "DG.Redo.sliderComponent.create": "恢复添加滑块",
              "DG.Undo.slider.change": "撤销对滑块值的更改",
              "DG.Redo.slider.change": "恢复对滑块值的更改",
              "DG.Undo.slider.changeMultiples": "撤销对滑块倍数限制的更改",
              "DG.Redo.slider.changeMultiples": "恢复对滑块倍数限制的更改",
              "DG.Undo.slider.changeSpeed": "撤销对滑块最大帧数/秒的更改",
              "DG.Redo.slider.changeSpeed": "恢复对滑块最大帧数/秒的更改",
              "DG.Undo.slider.changeDirection": "撤销对滑块动画方向的更改",
              "DG.Redo.slider.changeDirection": "恢复对滑块动画方向的更改",
              "DG.Undo.slider.changeRepetition": "撤销对滑块动画重复的更改",
              "DG.Redo.slider.changeRepetition": "恢复对滑块动画重复的更改",
              "DG.Undo.graphComponent.create": "撤销添加图形",
              "DG.Redo.graphComponent.create": "恢复添加图形",
              "DG.Undo.dataContext.create": "撤销创建数据集",
              "DG.Redo.dataContext.create": "恢复创建数据集",
              "DG.Undo.data.deleteCases": "撤销删除案例",
              "DG.Redo.data.deleteCases": "恢复删除案例",
              "DG.Undo.component.close": "撤销关闭组件",
              "DG.Redo.component.close": "恢复关闭组件",
              "DG.Undo.component.minimize": "撤销最小化组件",
              "DG.Redo.component.minimize": "恢复最小化组件",
              "DG.Undo.dataContext.moveAttribute": "撤销移动案例表格变量",
              "DG.Redo.dataContext.moveAttribute": "恢复移动案例表格变量",
              "DG.DataContext.singleCaseName": "案例",
              "DG.DataContext.pluralCaseName": "案例",
              "DG.DataContext.caseCountString": "%@1 %@2",
              "DG.DataContext.setOfCasesLabel": "集合",
              "DG.DataContext.collapsedRowString": "%@1 of %@2",
              "DG.DataContext.noData": "无数据",
              "DG.DataContext.baseName": "Data_Set_%@1",
              "DG.CollectionClient.cantEditFormulaErrorMsg": "变量公式“%@”不可编辑。",
              "DG.CollectionClient.cantEditFormulaErrorDesc": "创建能够指定公式的新属性。",
              "DG.Formula.FuncCategoryArithmetic": "算数函数",
              "DG.Formula.FuncCategoryConversion": "其他函数",
              "DG.Formula.FuncCategoryDateTime": "数据/时间函数",
              "DG.Formula.FuncCategoryLookup": "查询函数",
              "DG.Formula.FuncCategoryOther": "其他函数",
              "DG.Formula.FuncCategoryRandom": "其他函数",
              "DG.Formula.FuncCategoryStatistical": "统计函数",
              "DG.Formula.FuncCategoryString": "字符串函数",
              "DG.Formula.FuncCategoryTrigonometric": "三角函数",
              "DG.Formula.DateLongMonthJanuary": "一月",
              "DG.Formula.DateLongMonthFebruary": "二月",
              "DG.Formula.DateLongMonthMarch": "三月",
              "DG.Formula.DateLongMonthApril": "四月",
              "DG.Formula.DateLongMonthMay": "五月",
              "DG.Formula.DateLongMonthJune": "六月",
              "DG.Formula.DateLongMonthJuly": "七月",
              "DG.Formula.DateLongMonthAugust": "八月",
              "DG.Formula.DateLongMonthSeptember": "九月",
              "DG.Formula.DateLongMonthOctober": "十月",
              "DG.Formula.DateLongMonthNovember": "十一月",
              "DG.Formula.DateLongMonthDecember": "十二月",
              "DG.Formula.DateShortMonthJanuary": "一月",
              "DG.Formula.DateShortMonthFebruary": "二月",
              "DG.Formula.DateShortMonthMarch": "三月",
              "DG.Formula.DateShortMonthApril": "四月",
              "DG.Formula.DateShortMonthMay": "五月",
              "DG.Formula.DateShortMonthJune": "六月",
              "DG.Formula.DateShortMonthJuly": "七月",
              "DG.Formula.DateShortMonthAugust": "八月",
              "DG.Formula.DateShortMonthSeptember": "九月",
              "DG.Formula.DateShortMonthOctober": "十月",
              "DG.Formula.DateShortMonthNovember": "十一月",
              "DG.Formula.DateShortMonthDecember": "十二月",
              "DG.Formula.DateLongDaySunday": "周日",
              "DG.Formula.DateLongDayMonday": "周一",
              "DG.Formula.DateLongDayTuesday": "周二",
              "DG.Formula.DateLongDayWednesday": "周三",
              "DG.Formula.DateLongDayThursday": "周四",
              "DG.Formula.DateLongDayFriday": "周五",
              "DG.Formula.DateLongDaySaturday": "周六",
              "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec) \\d{1,2}( |,) *\\d{4}|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
              "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
              "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
              "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
              "DG.Formula.SyntaxErrorMiddle": "语法错误： '%@'",
              "DG.Formula.SyntaxErrorEnd": "不完整表达",
              "DG.Formula.SyntaxErrorInvalidOperator": "无效操作'%@'",
              "DG.Formula.TypeError.name": "❌",
              "DG.Formula.TypeError.message": "无效键入 '%@'",
              "DG.Formula.TypeError.description": "无效键入 '%@'",
              "DG.Formula.VarReferenceError.name": "❌",
              "DG.Formula.VarReferenceError.message": "'%@'无法识别",
              "DG.Formula.VarReferenceError.description": "变量 '%@' 无法识别",
              "DG.Formula.HierReferenceError.name": "❌",
              "DG.Formula.HierReferenceError.message": "对 '%@'子属性的无效引用",
              "DG.Formula.HierReferenceError.description": "'％@'是子属性，只能在聚合函数中引用",
              "DG.Formula.FuncReferenceError.name": "❌",
              "DG.Formula.FuncReferenceError.message": "'%@()' 无法识别",
              "DG.Formula.FuncReferenceError.description": "函数'%@()' 无法识别",
              "DG.Formula.FuncArgsError.name": "❌",
              "DG.Formula.FuncArgsErrorSingle.message": "'%@()' 需要一个参数",
              "DG.Formula.FuncArgsErrorSingle.description": "'%@()'函数需要一个参数",
              "DG.Formula.FuncArgsErrorPlural.message": "'%@()'需要%@参数",
              "DG.Formula.FuncArgsErrorPlural.description": "'%@()'函数需要%@参数",
              "DG.Formula.FuncArgsErrorRange.message": "'%@()'需要%@-%@ 参数",
              "DG.Formula.FuncArgsErrorRange.description": "'%@()'函数需要%@-%@参数",
              "DG.Formula.PendingRequest.name": "⌛",
              "DG.Formula.PendingRequest.message": "请求待处理...",
              "DG.Formula.PendingRequest.description": "请求待处理...",
              "DG.Formula.FailedRequest.name": "❌",
              "DG.Formula.FailedRequest.message": "请求失败 (%@)",
              "DG.Formula.FailedRequest.description": "请求失败 (%@)",
              "DG.Formula.PendingBoundaries.name": "⌛",
              "DG.Formula.PendingBoundaries.message": "边界待定...",
              "DG.Formula.PendingBoundaries.description": "边界待定...",
              "DG.Formula.FailedBoundaries.name": "❌",
              "DG.Formula.FailedBoundaries.message": "边界失败(%@)",
              "DG.Formula.FailedBoundaries.description": "边界失败(%@)",
              "DG.Formula.LookupDataSetError.message": "'%@': 无法识别数据集",
              "DG.Formula.LookupDataSetError.description": "数据集'%@'无法识别",
              "DG.Formula.LookupAttrError.message": "'%@' 不能在数据集'%@' 中找到",
              "DG.Formula.LookupAttrError.description": "属性'%@' 不能在数据集'%@'中找到",
              "DG.TableController.headerMenuItems.editAttribute": "编辑属性性质...",
              "DG.TableController.headerMenuItems.editFormula": "编辑公式...",
              "DG.TableController.headerMenuItems.randomizeAttribute": "重新随机化",
              "DG.TableController.headerMenuItems.sortAscending": "升序排列(A→Z, 0→9)",
              "DG.TableController.headerMenuItems.sortDescending": "降序排列(9→0, Z→A)",
              "DG.TableController.headerMenuItems.deleteAttribute": "删除变量",
              "DG.TableController.newAttrDlg.defaultAttrName": "未命名变量",
              "DG.TableController.newAttrDlg.attrNameHint": "输入新属性名称",
              "DG.TableController.newAttrDlg.formulaHint": "如果需要，键入用于计算此属性值的公式",
              "DG.TableController.newAttrDlg.applyTooltip": "使用名称和（可选）公式定义新属性",
              "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "请输入新属性名称",
              "DG.TableController.newAttrDialog.AttributesCategory": "变量",
              "DG.TableController.newAttrDialog.SpecialCategory": "特别",
              "DG.TableController.newAttrDialog.GlobalsCategory": "全局值",
              "DG.TableController.newAttrDialog.ConstantsCategory": "常数",
              "DG.TableController.newAttrDialog.FunctionsCategory": "函数",
              "DG.TableController.renameAttributeInvalidMsg": "变量名称不能为空",
              "DG.TableController.renameAttributeInvalidDesc": "请输入有效变量名称",
              "DG.TableController.renameAttributeDuplicateMsg": "该变量名称已存在",
              "DG.TableController.renameAttributeDuplicateDesc": "请输入唯一变量名称",
              "DG.TableController.deleteAttribute.confirmMessage": "删除变量'%@'？",
              "DG.TableController.deleteAttribute.confirmDescription": "此操作无法撤销。",
              "DG.TableController.deleteAttribute.okButtonTitle": "删除变量",
              "DG.TableController.deleteAttribute.cancelButtonTitle": "取消",
              "DG.TableController.deleteDataSet.confirmMessage": "删除并销毁 '%@'数据集？",
              "DG.TableController.deleteDataSet.confirmDescription": "此操作无法撤销。",
              "DG.TableController.deleteDataSet.okButtonTitle": "删除数据集",
              "DG.TableController.deleteDataSet.cancelButtonTitle": "取消",
              "DG.TableController.attrEditor.unitHint": "计量单位，如果适用",
              "DG.TableController.attrEditor.descriptionHint": "描述变量",
              "DG.TableController.setScoreDlg.applyTooltip": "设置'%@'变量公式",
              "DG.TableController.setScoreDlg.formulaHint": "键入公式计算此变量值",
              "DG.TableController.newAttributeTooltip": "向该表格添加新变量",
              "DG.TableController.attributeEditor.title": "变量性质",
              "DG.CaseTableDropTarget.dropMessage": "删除变量创建新集合",
              "DG.CaseTable.defaultAttrName": "未命名变量",
              "DG.CaseTable.indexColumnName": "编号",
              "DG.CaseTable.indexColumnTooltip": "序号（案例编号）",
              "DG.CaseTable.indexMenu.insertCase": "插入案例",
              "DG.CaseTable.indexMenu.insertCases": "插入案例...",
              "DG.CaseTable.indexMenu.deleteCase": "删除案例",
              "DG.CaseTable.indexMenu.deleteCases": "删除案例",
              "DG.CaseTable.attribute.type.none": "none",
              "DG.CaseTable.attribute.type.nominal": "类别",
              "DG.CaseTable.attribute.type.categorical": "类别",
              "DG.CaseTable.attribute.type.numeric": "数字",
              "DG.CaseTable.attribute.type.date": "日期",
              "DG.CaseTable.attribute.type.qualitative": "定性",
              "DG.CaseTable.attribute.type.boundary": "边界",
              "DG.CaseTable.attributeEditor.name": "名称",
              "DG.CaseTable.attributeEditor.description": "描述",
              "DG.CaseTable.attributeEditor.type": "键入",
              "DG.CaseTable.attributeEditor.unit": "单位",
              "DG.CaseTable.attributeEditor.precision": "精确",
              "DG.CaseTable.attributeEditor.editable": "可编辑的",
              "DG.CaseTable.insertCasesDialog.title": "插入案例",
              "DG.CaseTable.insertCasesDialog.numCasesPrompt": "要插入的#个案例：",
              "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "位置：",
              "DG.CaseTable.insertCasesDialog.beforeAfter.before": "前",
              "DG.CaseTable.insertCasesDialog.beforeAfter.after": "后",
              "DG.CaseTable.insertCasesDialog.applyBtnTitle": "插入案例",
              "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "插入指定数目的案例",
              "DG.CaseTableController.allTables": "所有表格",
              "DG.AttrFormView.attrNamePrompt": "变量名称：",
              "DG.AttrFormView.formulaPrompt": "公式：",
              "DG.AttrFormView.operandMenuTitle": "---插入数值---",
              "DG.AttrFormView.functionMenuTitle": "---插入函数---",
              "DG.AttrFormView.applyBtnTitle": "应用",
              "DG.AttrFormView.cancelBtnTitle": "取消",
              "DG.AttrFormView.cancelBtnTooltip": "关闭对话框而不进行任何更改",
              "DG.GuideConfigView.titlePrompt": "指南标题",
              "DG.GuideConfigView.titleHint": "活动名称",
              "DG.GuideConfigView.itemTitleHint": "栏目名称",
              "DG.GuideConfigView.itemURLHint": "栏目网址",
              "DG.GuideConfigView.okBtnTitle": "好",
              "DG.GuideConfigView.okBtnToolTip": "接受指南菜单项",
              "DG.GuideConfigView.cancelBtnTitle": "取消",
              "DG.GuideConfigView.cancelBtnTooltip": "关闭对话框而不进行任何更改",
              "DG.GuideConfigView.httpWarning": "网址必须以http://或者https://开头",
              "DG.DataDisplayModel.rescaleToData": "重新调整到数据",
              "DG.DataDisplayModel.ShowConnectingLine": "显示连接线",
              "DG.DataDisplayModel.HideConnectingLine": "隐藏连接线",
              "DG.AxisView.emptyGraphCue": "单击此处，或此处拖动一个变量。",
              "DG.CellLinearAxisView.midPanelTooltip": "拖动以平移轴比例",
              "DG.CellLinearAxisView.lowerPanelTooltip": "拖动以更改轴下限",
              "DG.CellLinearAxisView.upperPanelTooltip": "拖动以更改轴上限",
              "DG.PlotModel.mixup": "混合此图",
              "DG.PlotModel.showCount": "显示计数",
              "DG.PlotModel.hideCount": "隐藏计数",
              "DG.ScatterPlotModel.sumSquares": "，\n平方和=%@",
              "DG.ScatterPlotModel.slopeOnly": "斜率 = %@ %@",
              "DG.ScatterPlotModel.yearsLabel": "每年",
              "DG.ScatterPlotModel.daysLabel": "每天",
              "DG.ScatterPlotModel.hoursLabel": "每小时",
              "DG.ScatterPlotModel.minutesLabel": "每分钟",
              "DG.ScatterPlotModel.secondsLabel": "每秒钟",
              "DG.LegendView.attributeTooltip": "单击更改变量图示说明",
              "DG.NumberToggleView.showAll": "显示所有—",
              "DG.NumberToggleView.hideAll": "隐藏全部—",
              "DG.NumberToggleView.lastDash": "–",
              "DG.NumberToggleView.lastUnchecked": "☐",
              "DG.NumberToggleView.lastChecked": "☒",
              "DG.NumberToggleView.lastLabel": "最后",
              "DG.NumberToggleView.showAllTooltip": "单击显示所有案例\n单击母案例标签以切换可见",
              "DG.NumberToggleView.hideAllTooltip": "单击隐藏所有案例\n单击母案例标签以切换可见",
              "DG.NumberToggleView.enableLastModeTooltip": "单击仅显示最后母案例",
              "DG.NumberToggleView.disableLastModeTooltip": "单击推出上个母案例模式",
              "DG.NumberToggleView.indexTooltip": "单击切换可见性",
              "DG.PlottedAverageAdornment.meanValueTitle": "均值=%@",
              "DG.PlottedAverageAdornment.medianValueTitle": "中位数=%@",
              "DG.PlottedAverageAdornment.stDevValueTitle": "±1 标准差, %@",
              "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@",
              "DG.PlottedAverageAdornment.boxPlotTitle": "下限=%@\nQ1=%@\n中位数=%@\nQ3=%@\n上限=%@\n四分位距=%@",
              "DG.PlottedCountAdornment.title": "%@ %@, %@%",
              "DG.DataDisplayMenu.attribute_x": "X: %@",
              "DG.DataDisplayMenu.attribute_y": "Y: %@",
              "DG.DataDisplayMenu.attribute_y2": "Y: %@",
              "DG.DataDisplayMenu.attribute_legend": "图例：%@",
              "DG.DataDisplayMenu.remove": "删除变量",
              "DG.DataDisplayMenu.removeAttribute_x": "删除X: %@",
              "DG.DataDisplayMenu.removeAttribute_y": "删除 Y: %@",
              "DG.DataDisplayMenu.removeAttribute_y2": "删除 Y: %@",
              "DG.DataDisplayMenu.removeAttribute_legend": "删除图例: %@",
              "DG.DataDisplayMenu.treatAsCategorical": "视为类别",
              "DG.DataDisplayMenu.treatAsNumeric": "视为数字",
              "DG.DataDisplayMenu.hide": "隐藏和显示",
              "DG.DataDisplayMenu.hideSelectedPlural": "隐藏所选案例",
              "DG.DataDisplayMenu.hideUnselectedPlural": "隐藏未选案例",
              "DG.DataDisplayMenu.hideSelectedSing": "隐藏所选案例",
              "DG.DataDisplayMenu.hideUnselectedSing": "隐藏未选案例",
              "DG.DataDisplayMenu.enableNumberToggle": "显示上层数据集可见切换",
              "DG.DataDisplayMenu.disableNumberToggle": "隐藏上层可见切换",
              "DG.DataDisplayMenu.showAll": "显示所有案例",
              "DG.DataDisplayMenu.snapshot": "制作快照",
              "DG.GraphView.replaceAttribute": "用%@替换%@",
              "DG.GraphView.addAttribute": "添加变量%@",
              "DG.GraphView.addToEmptyPlace": "用%@创建轴",
              "DG.GraphView.addToEmptyX": "用%@创建x轴",
              "DG.GraphView.dropInPlot": "按%@值显示色点",
              "DG.GraphView.zoomTip": "双击放大。\n按住Shift键双击缩小",
              "DG.GraphView.rescale": "重新调整到数据",
              "DG.AxisView.labelTooltip": "—单击以更改%@轴变量",
              "DG.AxisView.vertical": "垂直",
              "DG.AxisView.horizontal": "水平",
              "DG.DataTip.connectingLine": "%@: %@\n与 %@ %@",
              "DG.MovableMonthYear": "%@, %@",
              "DG.MovableMonthDayHour": "%@ %@ %@:00",
              "DG.PlottedFormula.defaultNamePrompt": "公式",
              "DG.PlottedValue.namePrompt": "标绘值",
              "DG.PlottedValue.formulaPrompt": "值=",
              "DG.PlottedValue.formulaHint": "\u200b",
              "DG.PlottedFunction.namePrompt": "绘制函数",
              "DG.PlottedFunction.formulaPrompt": "f() =",
              "DG.PlottedFunction.formulaHint": "键入表达式 例如x*x/30 - 50",
              "DG.MapView.showGrid": "显示网格",
              "DG.MapView.hideGrid": "隐藏网格",
              "DG.MapView.showPoints": "显示点",
              "DG.MapView.hidePoints": "隐藏点",
              "DG.MapView.marqueeHint": "选框工具—拖动地图中的选择点",
              "DG.MapView.gridControlHint": "更改网格矩形大小",
              "DG.Inspector.values": "测量",
              "DG.Inspector.styles": "格式",
              "DG.Inspector.pointSize": "点大小：",
              "DG.Inspector.transparency": "透明度：",
              "DG.Inspector.color": "颜色：",
              "DG.Inspector.legendColor": "图例颜色：",
              "DG.Inspector.backgroundColor": "背景颜色：",
              "DG.Inspector.stroke": "笔触：",
              "DG.Inspector.rescale.toolTip": "重新调整显示所有数据",
              "DG.Inspector.mixUp.toolTip": "混合所有点",
              "DG.Inspector.hideShow.toolTip": "显示所有案例或者隐藏所选/未选案例",
              "DG.Inspector.delete.toolTip": "删除所选/未选案例",
              "DG.Inspector.sliderValues.toolTip": "设置滑块动画的方向，速度，...",
              "DG.Inspector.webViewEditURL.toolTip": "编辑所显示网页的网址",
              "DG.Inspector.selection.selectAll": "选择所有案例",
              "DG.Inspector.selection.deleteSelectedCases": "删除所选案例",
              "DG.Inspector.selection.deleteUnselectedCases": "删除未选案例",
              "DG.Inspector.deleteAll": "删除所有案例",
              "DG.Inspector.deleteDataSet": "删除和销毁数据集",
              "DG.Inspector.displayValues.toolTip": "更改与点一起显示的内容",
              "DG.Inspector.displayStyles.toolTip": "更改显示器外观",
              "DG.Inspector.makeImage.toolTip": "将图像另存为PNG文件",
              "DG.Inspector.displayShow": "显示...",
              "DG.Inspector.colorPicker.more": "更多",
              "DG.Inspector.colorPicker.less": "更少",
              "DG.Inspector.graphTransparency": "透明",
              "DG.Inspector.graphCount": "计数",
              "DG.Inspector.graphPercent": "百分比",
              "DG.Inspector.graphRow": "行",
              "DG.Inspector.graphColumn": "列",
              "DG.Inspector.graphCell": "单元格",
              "DG.Inspector.graphConnectingLine": "连接线",
              "DG.Inspector.graphMovableLine": "可动线",
              "DG.Inspector.graphInterceptLocked": "斜率锁定",
              "DG.Inspector.graphPlottedFunction": "绘制函数",
              "DG.Inspector.graphSquares": "残差平方",
              "DG.Inspector.graphLSRL": "最小平方线",
              "DG.Inspector.graphMovableValue": "可移动值",
              "DG.Inspector.graphAdd": "添加",
              "DG.Inspector.graphRemove": "删除",
              "DG.Inspector.graphPlottedMean": "均值",
              "DG.Inspector.graphPlottedMedian": "中位数",
              "DG.Inspector.graphPlottedStDev": "标准差",
              "DG.Inspector.graphPlottedIQR": "四分位间距",
              "DG.Inspector.graphPlottedBoxPlot": "箱型图",
              "DG.Inspector.graphPlottedValue": "标绘值",
              "DG.Inspector.attributes.toolTip": "设置新变量。导出案例数据。",
              "DG.Inspector.resize.toolTip": "调整所有列大小以适应数据",
              "DG.Inspector.newAttribute": "%@...中新变量",
              "DG.Inspector.randomizeAllAttributes": "重新随机化",
              "DG.Inspector.exportCaseData": "导出案例数据...",
              "DG.Inspector.mapGrid": "网格",
              "DG.Inspector.mapPoints": "点",
              "DG.Inspector.mapLines": "连接线",
              "DG.GameController.continuityError": "抱歉，在对案例表中列进行重新排序后，无法接受新数据。",
              "DG.GameView.loading": "载入中",
              "DG.GameView.loadError": "如果您可以看到此文本，则可能是上述网址加载失败。您可以在其他浏览器选项卡中检查链接或者将错误报告给http://codap.concord.org/help。",
              "DG.Component.closeComponent.confirmCloseMessage": "确定？",
              "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
              "DG.Component.closeComponent.okButtonTitle": "是，关闭它。",
              "DG.Component.closeComponent.cancelButtonTitle": "取消",
              "DG.GameController.confirmCloseDescription": "如果关闭此窗口，您将可能无法添加更多数据。",
              "DG.WebView.defaultTitle": "网页",
              "DG.mainPage.exceptionMessage": "发生错误，可能影响该程序的行为。在保存工作后，您可能希望重新加载此页面。（错误：%@）",
              "DG.fileMenu.provider.examples.displayName": "范例文件",
              "DG.ToolButtonData.pluginMenu.title": "插件",
              "DG.ToolButtonData.pluginMenu.toolTip": "打开一个插件组件",
              "DG.Undo.graph.showMovablePoint": "撤销显示可动点",
              "DG.Redo.graph.showMovablePoint": "恢复显示可动点",
              "DG.Undo.graph.hideMovablePoint": "撤销隐藏可动点",
              "DG.Redo.graph.hideMovablePoint": "恢复隐藏可动点",
              "DG.Undo.graph.moveMovablePoint": "撤销移动可动点",
              "DG.Redo.graph.moveMovablePoint": "恢复移动可动点",
              "DG.DataDisplayMenu.copyAsImage": "在绘图工具中打开",
              "DG.DataDisplayMenu.exportImage": "导出图片...",
              "DG.DataDisplayMenu.imageOfTitle": "%@图片",
              "DG.Inspector.graphMovablePoint": "可动点",
              "DG.AppController.caseTableMenu.openCaseTableToolTip": "打开此数据集的案例表",
              "DG.AppController.caseTableMenu.newDataSetToolTip": "创建新数据集",
              "DG.AppController.caseTableMenu.deleteDataSetToolTip": "删除并销毁此数据集",
              "DG.Undo.graph.showAsBarChart": "撤销将散点图到条形图",
              "DG.Redo.graph.showAsBarChart": "恢复将散点图到条形图",
              "DG.Undo.graph.showAsDotChart": "撤销分散条形图成散点图",
              "DG.Redo.graph.showAsDotChart": "恢复分散条形图成散点图",
              "DG.CountAxisView.countLabel": "计数",
              "DG.CountAxisView.countLabelDescription": "沿该轴的条中案例数",
              "DG.CountAxisView.percentLabel": "百分比",
              "DG.CountAxisView.percentLabelDescription": "沿该轴的条中案例百分比",
              "DG.BarChartModel.cellTipPlural": "%@ %@ (%@%)的%@是%@",
              "DG.BarChartModel.cellTipSingular": "%@ %@ (%@%)的%@是%@",
              "DG.Inspector.configuration": "组态",
              "DG.Inspector.displayConfiguration.toolTip": "不同地配置显示",
              "DG.Inspector.displayScale": "比例...",
              "DG.Inspector.graphBarChart": "将点转化成条形图",
              "DG.Locale.name.de": "德语",
              "DG.Locale.name.en": "英语",
              "DG.Locale.name.es": "西班牙语",
              "DG.Locale.name.he": "希伯来语",
              "DG.Locale.name.tr": "土耳其语",
              "DG.Locale.name.zh": "汉语",
              "DG.Undo.graph.swapCategories": "撤销重新排序类别",
              "DG.Redo.graph.swapCategories": "重新排序类别",
              "DG.TableController.collectionTitleText": "%@1 (%@2 案例)",
              "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 案例, %@3 保留)",
              "DG.Inspector.setaside.setAsideSelectedCases": "保留所选案例",
              "DG.Inspector.setaside.setAsideUnselectedCases": "保留未选案例",
              "DG.Inspector.setaside.restoreSetAsideCases": "恢复%@保留案例",
              "DG.DocumentController.caseCardTitle": "案例卡",
              "DG.DocumentController.toggleToCaseCard": "切换到案例卡数据视图",
              "DG.DocumentController.toggleToCaseTable": "切换到案例表数据视图",
              "DG.CaseCard.indexString": "%@%@中的1",
              "DG.CaseCard.namePlusCaseCount": "%@ %@",
              "DG.CaseCard.namePlusSelectionCount": "%@ %@中所选%@",
              "DG.CaseCard.summaryValues": "%@值",
              "DG.CaseCard.summaryRange": "%@–%@ %@",
              "DG.CaseCard.navNextCase": "选择并显示下个案例",
              "DG.CaseCard.navPrevCase": "选择并显示上个案例",
              "DG.CaseCard.navFirstCase": "选择并显示第一个案例",
              "DG.CaseCard.navLastCase": "选择并显示最后一个案例",
              "DG.Undo.component.toggleTableToCard": "撤销更改案例表为案例卡",
              "DG.Redo.component.toggleTableToCard": "恢复更改案例表为案例卡",
              "DG.Undo.component.toggleCardToTable": "撤销更改案例卡为案例表",
              "DG.Redo.component.toggleCardToTable": "恢复更改案例卡为案例表",
              "DG.Undo.graph.addBackgroundImage": "撤销添加图表背景图片",
              "DG.Redo.graph.addBackgroundImage": "恢复添加图表背景图片",
              "DG.Undo.graph.removeBackgroundImage": "撤销删除图表背景图片",
              "DG.Redo.graph.removeBackgroundImage": "恢复删除图表背景图片",
              "DG.Undo.graph.lockBackgroundImage": "撤销将背景图片锁定到轴",
              "DG.Redo.graph.lockBackgroundImage": "恢复将背景图片锁定到轴",
              "DG.Undo.graph.unlockBackgroundImage": "撤销从轴解锁背景图片",
              "DG.Redo.graph.unlockBackgroundImage": "恢复从轴解锁背景图片",
              "DG.Undo.enableMeasuresForSelection": "撤销显示对所选的测量",
              "DG.Redo.enableMeasuresForSelection": "恢复显示对所选的测量",
              "DG.Undo.disableMeasuresForSelection": "撤销隐藏对所选的测量",
              "DG.Redo.disableMeasuresForSelection": "恢复隐藏对所选的测量",
              "DG.DataDisplayMenu.enableMeasuresForSelection": "显示所选案例的测量值",
              "DG.DataDisplayMenu.disableMeasuresForSelection": "隐藏所选的测量",
              "DG.DataDisplayMenu.addBackgroundImage": "添加背景图片",
              "DG.DataDisplayMenu.lockImageToAxes": "锁定背景图片到轴",
              "DG.DataDisplayMenu.unlockImageFromAxes": "从轴解锁背景图片",
              "DG.DataDisplayMenu.removeBackgroundImage": "删除背景图片",
              "DG.main.page.title": "%@1 - %@2",
              "DG.TableController.headerMenuItems.deleteFormula": "删除公式（保留值）",
              "DG.TableController.headerMenuItems.recoverFormula": "恢复已删除公式",
              "DG.Inspector.displayLayers.toolTip": "更改地图图层外观",
              "DG.Inspector.layers": "层数",
              "DG.Undo.graph.repositionEquation": "撤销重新定位方程",
              "DG.Redo.graph.repositionEquation": "恢复定位方程",
              "DG.TableController.attrEditor.precisionNumericHint": "小数点后的位数",
              "DG.TableController.attrEditor.precisionDateHint": "确定显示多少日期",
              "DG.TableController.attrEditor.typeHint": "设置为强制将变量视为某种类型",
              "DG.TableController.attrEditor.nameHint": "变量名称显示在案例表，案例卡和图形轴上",
              "DG.TableController.attrEditor.editableHint": "若变量不可编辑，则不能更改其值和/或公式",
              "DG.CaseTable.attributeEditor.datePrecisionOptions": "年 月 日 时 分 秒",
              "DG.AttributeFormat.DatePrecision.year": "年",
              "DG.AttributeFormat.DatePrecision.month": "月 年",
              "DG.AttributeFormat.DatePrecision.day": "月 日，年",
              "DG.AttributeFormat.DatePrecision.hour": "月 日，年 时：00",
              "DG.AttributeFormat.DatePrecision.minute": "月 日，年 时：分",
              "DG.AttributeFormat.DatePrecision.second": "月 日，年 时：分：秒",
              "DG.CaseCard.attrHintPlain": "%@",
              "DG.CaseCard.attrHintUnitsOnly": "%@中的%@",
              "DG.CaseCard.attrHintDescription": "%@: %@",
              "DG.CaseCard.attrHintFormula": "%@\n%@",
              "DG.AppController.optionMenuItems.help-forum": "求助论坛...",
              "DG.AppController.showHelpForumTitle": "求助论坛",
              "DG.Locale.name.el": "希腊语",
              "DG.BarChartModel.cellTipNoLegendSingular": "%@ (%@%)中的%@是%@",
              "DG.BarChartModel.cellTipNoLegendPlural": "%@ (%@%)中的%@是%@",
              "DG.DataDisplayMenu.removeAttribute_top": "按%@删除并排布局",
              "DG.DataDisplayMenu.removeAttribute_right": "按%@删除垂直布局",
              "DG.GraphView.layoutPlotsSideBySide": "按%@进行并排布局",
              "DG.GraphView.layoutPlotsVertically": "按%@进行垂直布局",
              "DG.Undo.graph.makeStrokeSameAsFill": "撤销使笔触与填充一样",
              "DG.Redo.graph.makeStrokeSameAsFill": "恢复使笔触与填充一样",
              "DG.Undo.graph.makeStrokeIndependent": "撤销使笔触从填充中独立",
              "DG.Redo.graph.makeStrokeIndependent": "恢复使笔触从填充中独立",
              "DG.Inspector.strokeSameAsFill": "笔触颜色与填充一样",
              "DG.Formula.DateShortDaySunday": "周日",
              "DG.Formula.DateShortDayMonday": "周一",
              "DG.Formula.DateShortDayTuesday": "周二",
              "DG.Formula.DateShortDayWednesday": "周三",
              "DG.Formula.DateShortDayThursday": "周四",
              "DG.Formula.DateShortDayFriday": "周五",
              "DG.Formula.DateShortDaySaturday": "周六",
              "DG.AttributeFormat.DatePrecision.millisecond": "月 日，年 时：分：秒。SSS",
              "DG.CellAxis.other": "其他",
              "DG.PlottedAverageAdornment.madValueTitle": "±1 平均绝对偏差, %@",
              "DG.Inspector.graphPlottedMeanAbsDev": "平均绝对偏差",
              "DG.Undo.graph.showPlottedBoxPlot": "撤销显示箱线图",
              "DG.Redo.graph.hidePlottedBoxPlot": "恢复隐藏箱线图",
              "DG.Undo.graph.hidePlottedBoxPlot": "撤销隐藏箱线图",
              "DG.Redo.graph.showPlottedBoxPlot": "撤销显示箱线图",
              "DG.Undo.graph.showOutliers": "撤销显示异常值",
              "DG.Redo.graph.hideOutliers": "恢复隐藏异常值",
              "DG.Undo.graph.hideOutliers": "撤销隐藏异常值",
              "DG.Redo.graph.showOutliers": "恢复显示异常值",
              "DG.Inspector.graphBoxPlotShowOutliers": "显示异常值",
              "DG.Locale.name.nb": "挪威语",
              "DG.Locale.name.nn": "新挪威语",
              "DG.CaseCard.newCaseToolTip": "向此集合中添加一个空案例",
              "DG.TableController.headerMenuItems.renameAttribute": "重命名",
              "DG.Undo.graph.fuseDotsToRectangles": "撤销将散点图到矩形图",
              "DG.Redo.graph.fuseDotsToRectangles": "恢复将散点图到矩形图",
              "DG.Undo.graph.dissolveRectanglesToDots": "撤销将矩形图到散点图",
              "DG.Redo.graph.dissolveRectanglesToDots": "恢复将矩形图到散点图",
              "DG.Undo.graph.changeBreakdownType": "撤销更改量度类型",
              "DG.Redo.graph.changeBreakdownType": "恢复更改量度类型",
              "DG.Undo.graph.showAsBinnedPlot": "撤销组合散点图到直方图",
              "DG.Redo.graph.showAsBinnedPlot": "恢复组合散点图到直方图",
              "DG.Undo.graph.showAsDotPlot": "撤销直方图分组到散点图",
              "DG.Redo.graph.showAsDotPlot": "恢复直方图分组到散点图",
              "DG.Undo.graph.dragBinBoundary": "撤销拖动直方图边界",
              "DG.Redo.graph.dragBinBoundary": "恢复拖动直方图边界",
              "DG.Undo.graph.changeBinWidth": "撤销更改直方图宽度",
              "DG.Redo.graph.changeBinWidth": "恢复更改直方图宽度",
              "DG.Undo.graph.changeBinAlignment": "撤销更改直方图对齐",
              "DG.Redo.graph.changeBinAlignment": "恢复更改直方图对齐",
              "DG.BinnedPlotModel.dragBinTip": "拖动更改直方图宽度",
              "DG.HistogramView.barTipPlural": "%@ of %@ %@ (%@%) are ≥ %@ and < %@",
              "DG.HistogramView.barTipSingular": "%@ of %@ %@ (%@%) is ≥ %@ and < %@",
              "DG.HistogramView.barTipNoLegendSingular": "%@ of %@ (%@%) is ≥ %@ and < %@",
              "DG.HistogramView.barTipNoLegendPlural": "%@ of %@ (%@%) are ≥ %@ and < %@",
              "DG.Inspector.graphGroupIntoBins": "组合成直方图",
              "DG.Inspector.graphBinWidth": "直方图宽度",
              "DG.Inspector.graphAlignment": "直方图对齐",
              "DG.CaseTable.dividerView.expandAllTooltip": "展开所有组",
              "DG.CaseTable.dividerView.expandGroupTooltip": "展开组",
              "DG.CaseTable.dividerView.collapseAllTooltip": "折叠所有组",
              "DG.CaseTable.dividerView.collapseGroupTooltip": "折叠组",
              "DG.BinnedPlotModel.binLabelTip": "直方图数值是%@ 和%@",
              "DG.Component.closeComponent.toolTip": "关闭该组分",
              "DG.Component.minimizeComponent.toolTip": "最小化或展开该组分",
              "DG.Locale.name.ja": "Japanese",
              "DG.CaseCard.attrHintDescriptionAndFormula": "%@1: %@2\n%@1 = %@3",
              "DG.Locale.name.zh-Hans": "Simplified Chinese",
              "DG.PlottedCount.withoutSelection": "%@",
              "DG.PlottedCount.withSelection": "%@ selected",
              "DG.PlottedPercent.withoutSelection": "%@%",
              "DG.PlottedPercent.withSelection": "%@% selected",
              "DG.PlottedCountPercent.withoutSelection": "%@ (%@%)",
              "DG.PlottedCountPercent.withSelection": "%@ of %@ (%@%) selected",
              "DG.Undo.caseTable.resizeColumn": "Undo fit width to content",
              "DG.Redo.caseTable.resizeColumn": "Redo fit width to content",
              "DG.TableController.headerMenuItems.resizeColumn": "Fit Width To Content",
              "DG.SelectedInfoView.infoPlural": "Showing measures for %@ selected cases",
              "DG.SelectedInfoView.infoSing": "Showing measures for %@ selected case",
              "DG.Inspector.copyCaseDataToClipboard": "Copy to Clipboard...",
              "DG.Inspector.caseTable.exportCaseDialog.copyFrom": "Copy case data from:",
              "DG.Inspector.caseTable.exportCaseDialog.copy": "Copy",
              "DG.Inspector.caseTable.exportCaseDialog.copyTooltip": "Copy data to clipboard",
              "DG.Inspector.caseTable.exportCaseDialog.copiedData": "Copied %@ to the clipboard",
              "DG.Undo.caseTable.hideAttribute": "Undo hiding attribute",
              "DG.Redo.caseTable.hideAttribute": "Redo hiding attribute",
              "DG.Undo.caseTable.showAllHiddenAttributes": "Undo show all hidden attributes",
              "DG.Redo.caseTable.showAllHiddenAttributes": "Redo show all hidden attributes",
              "DG.TableController.headerMenuItems.hideAttribute": "Hide Attribute",
              "DG.Inspector.attributes.showAllHiddenAttributesSing": "Show %@ Hidden Attribute",
              "DG.Inspector.attributes.showAllHiddenAttributesPlural": "Show %@ Hidden Attributes",
              "DG.Inspector.attributes.showAllHiddenAttributesDisabled": "Show Hidden Attributes",
              "DG.Inspector.getCaseDataFromClipboard": "Import Case Data from Clipboard...",
              "DG.CaseCard.addCaseButton": "add case",
              "DG.Undo.DataContext.join": "Undo join of %@ to %@",
              "DG.Redo.DataContext.join": "Redo join of %@ to %@",
              "DG.Collection.joinTip": "Join %@ in %@ to %@ in %@ by matching %@ with %@",
              "DG.Inspector.graphPlotPoints": "Points",
              "DG.Inspector.graphBarForEachPoint": "Bar for Each Point",
              "DG.Undo.graph.changeBarChartFunction": "Undo change bar chart formula",
              "DG.Redo.graph.changeBarChartFunction": "Redo change bar chart formula",
              "DG.Undo.graph.showAsLinePlot": "Undo bar for each point",
              "DG.Redo.graph.showAsLinePlot": "Redo bar for each point",
              "DG.Undo.graph.showAsStandardBarChart": "Undo using count or percent for bar chart scale",
              "DG.Redo.graph.showAsStandardBarChart": "Redo using count or percent for bar chart scale",
              "DG.Undo.graph.showAsComputedBarChart": "Undo computing bar length with formula",
              "DG.Redo.graph.showAsComputedBarChart": "Redo computing bar length with formula",
              "DG.FormulaAxisView.labelDescription": "The expression that determines the length of the bars. Click to edit.",
              "DG.ComputedBarChartModel.cellTip": "For group %@ the value is %@",
              "DG.BarChartFunction.namePrompt": "Bar Chart",
              "DG.BarChartFunction.formulaPrompt": "bar length =",
              "DG.BarChartFunction.formulaHint": "Type a formula to compute bar length",
              "DG.BarChartFunction.emptyExpressionAxisPrompt": "Click here to provide a formula",
              "DG.Inspector.graphFormula": "Formula",
              "DG.Undo.displayOnlySelected": "Undo displaying only selected cases",
              "DG.Redo.displayOnlySelected": "Redo displaying only selected cases",
              "DG.Undo.webView.show": "Undo adding webView component",
              "DG.Redo.webView.show": "Redo adding webView component",
              "DG.Undo.imageComponent.show": "Undo adding image component",
              "DG.Redo.imageComponent.show": "Redo adding image component",
              "DG.DataDisplayMenu.displayOnlySelected": "Display Only Selected Cases",
              "DG.DataDisplayMenu.displayingOnlySelected": "Displaying Only Selected Cases",
              "DG.PlotBackgroundView.msg0": "This graph is set to display",
              "DG.PlotBackgroundView.msg1": "only selected cases.",
              "DG.PlotBackgroundView.msg2": "No cases are selected",
              "DG.PlotBackgroundView.msg3": "so nothing is being displayed.",
              "DG.PlotBackgroundView.msg4": "You can select cases in a",
              "DG.PlotBackgroundView.msg5": "case table or another graph.",
              "DG.ImageComponent.defaultTitle": "Image",
              "DG.TableController.datasetMetadata.title": "Dataset Information",
              "DG.CaseTable.datasetMetadata.url": "source",
              "DG.CaseTable.datasetMetadata.creationDate": "import date",
              "DG.TableController.datasetMetadata.descriptionHint": "Describe the dataset",
              "DG.Inspector.datasetInfo.toolTip": "Display information about dataset",
              "DG.CaseTable.indexMenu.moveEntryRow": "Move Data Entry Row Here",
              "DG.CaseCard.deselect": "Deselect all cases",
              "DG.CaseCard.noDeselect": "No cases are selected",
              "DG.CaseTable.indexProto.tooltip": "Drag to place data entry row within this table",
              "DG.AttributeFormat.DatePrecisionShort.year": "YYYY",
              "DG.AttributeFormat.DatePrecisionShort.month": "M/YY",
              "DG.AttributeFormat.DatePrecisionShort.day": "M/D/YY",
              "DG.AttributeFormat.DatePrecisionShort.hour": "M/D/YY HH:00",
              "DG.AttributeFormat.DatePrecisionShort.minute": "M/D/YY HH:mm",
              "DG.AttributeFormat.DatePrecisionShort.second": "M/D/YY HH:mm:ss",
              "DG.AttributeFormat.DatePrecisionShort.millisecond": "M/D/YY HH:mm:ss.SSS",
              "DG.Formula.FuncCategoryLogic": "Logic Functions",
              "DG.Undo.graph.showMeasureLabels": "Undo showing measure labels",
              "DG.Redo.graph.showMeasureLabels": "Redo showing measure labels",
              "DG.Undo.graph.hideMeasureLabels": "Undo hiding measure labels",
              "DG.Redo.graph.hideMeasureLabels": "Redo hiding measure labels",
              "DG.Inspector.showLabels": "Show Measure Labels",
              "DG.Undo.caseTable.resizeOneColumn": "Undo resize column",
              "DG.Redo.caseTable.resizeOneColumn": "Redo resize column",
              "DG.CaseTable.attribute.type.checkbox": "checkbox",
              "DG.AppController.caseTableMenu.clipboardDataset": "Νew from clipboard",
              "DG.AppController.caseTableMenu.clipboardDatasetToolTip": "Paste data set from clipboard",
              "DG.AppController.optionMenuItems.toPrivacyPage": "Privacy Page...",
              "DG.plugin.Importer.title": "Import CSV to CODAP",
              "DG.plugin.Importer.enter-url": "Enter url: ",
              "DG.plugin.Importer.or": "or",
              "DG.plugin.Importer.downsample-section": "Downsample Options...",
              "DG.plugin.Importer.downsample-random-p1": "Randomly select",
              "DG.plugin.Importer.downsample-random-p2": "rows",
              "DG.plugin.Importer.downsample-every-nth-p1": "Select every",
              "DG.plugin.Importer.downsample-every-nth-p2": "th row",
              "DG.plugin.Importer.downsample-import-all": "Import all rows",
              "DG.plugin.Importer.target-options-title": "Target Options...",
              "DG.plugin.Importer.target-options-replace": "Replace existing dataset with this one",
              "DG.plugin.Importer.target-options-append": "Append this dataset to the existing one",
              "DG.plugin.Importer.target-options-create-new": "Create a new data set",
              "DG.plugin.Importer.button-cancel": "Cancel",
              "DG.plugin.Importer.button-submit": "OK",
              "DG.plugin.Importer.button-dismiss": "Dismiss",
              "DG.plugin.Importer.load-error": "There was an error loading this resource: \"%@\" reason: \"%@\"",
              "DG.plugin.Importer.no-table-error": "Could not find tabular data in a format that can be imported into CODAP",
              "DG.plugin.Importer.duplicate-dataset-msg": "There already exists a dataset like this one. It is named \"%@\".",
              "DG.plugin.Importer.upload-time-msg": "It was uploaded %@",
              "DG.plugin.Importer.large-file-msg": "The imported file, \"%@\" has %@ rows. With more than %@ rows CODAP performance may be sluggish. You can work with a sample of the data at least at first, replacing it with the full dataset later.",
              "DG.plugin.Importer.error-codap-connection": "Error sending data to CODAP",
              "DG.plugin.Importer.error-upload": "Could not import this file -- %@",
              "DG.plugin.Importer.import-message": "Preparing to import %@ rows into \"%@\" from a table with %@ attributes: %@%@",
              "DG.Undo.component.componentTitleChange": "Undo changing the component title",
              "DG.Redo.component.componentTitleChange": "Redo changing the component title",
              "DG.TableController.collectionTitleText-nonempty": "%@1 (%@2 nonempty cases)",
              "DG.TableController.collectionTitleTextWithSetAside-nonempty": "%@1 (%@2 nonempty cases, %@3 set aside)",
              "DG.CaseTable.closedGroup.summary": "%@1 %@2",
              "DG.CaseTable.closedGroup.summary-nonempty": "%@1 nonempty %@2",
              "DG.DataDisplayMenu.exportPngImage": "Export PNG Image...",
              "DG.DataDisplayMenu.exportSvgImage": "Export SVG Image...",
              "DG.plugin.StoryBuilder.pluginName": "Story Builder",
              "DG.plugin.StoryBuilder.description": "Create a narrative of your investigation.",
              "DG.plugin.StoryBuilder.controlArea.discardAlt": "Discard changes",
              "DG.plugin.StoryBuilder.controlArea.discardTooltip": "Discard changes to this moment",
              "DG.plugin.StoryBuilder.controlArea.saveAlt": "Save",
              "DG.plugin.StoryBuilder.controlArea.saveTooltip": "Save this moment",
              "DG.plugin.StoryBuilder.controlArea.newAlt": "Make a new moment",
              "DG.plugin.StoryBuilder.controlArea.newTooltip": "Add a new moment to the right",
              "DG.plugin.StoryBuilder.dialog.optOutCheckbox": "Don't ask me again (always save)",
              "DG.plugin.StoryBuilder.emptyMoment.createAlt": "make new moment",
              "DG.plugin.StoryBuilder.emptyMoment.createTitle": "Click to make a new moment",
              "DG.plugin.StoryBuilder.buttons.helpAlt": "get help",
              "DG.plugin.StoryBuilder.buttons.helpTitle": "Get some help about how to use Story Builder",
              "DG.plugin.StoryBuilder.buttons.autoSaveTitleAuto": "Currently will automatically save changes to moments. Click to be asked whether to save or discard.",
              "DG.plugin.StoryBuilder.buttons.autoSaveTitleManual": "Currently will ask to save or discard changes to moments. Click to automatically save changes without asking.",
              "DG.plugin.StoryBuilder.momentComponent.deleteAlt": "Delete this moment",
              "DG.plugin.StoryBuilder.momentComponent.deleteTitle": "Delete this moment",
              "DG.plugin.StoryBuilder.momentTextboxContent": "What did you do? Why did you do it?",
              "DG.plugin.StoryBuilder.momentTextboxFirstContent": "This is the beginning of your data story.",
              "DG.plugin.StoryBuilder.momentManager.firstTitle": "start ...",
              "DG.plugin.StoryBuilder.momentManager.nextTitle": "moment title",
              "DG.plugin.StoryBuilder.storyArea.dialog.cancel": "Cancel",
              "DG.plugin.StoryBuilder.storyArea.dialog.discard": "Discard",
              "DG.plugin.StoryBuilder.storyArea.dialog.save": "Save",
              "DG.plugin.StoryBuilder.storyArea.qClickAnotherMomentPrompt": "Save or discard changes?",
              "DG.plugin.StoryBuilder.storyArea.qClickAnotherMomentExplanation": "You have made changes to Moment %@. Would you like to save or discard these changes?",
              "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentPrompt": "Save changes before creating Moment %@?",
              "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentExplanation": "You have made changes to Moment %@. Would you like to save those changes to both Moments %@ and %@ or only to the new Moment %@?",
              "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentTwoMoments": "Moments %@ and %@",
              "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentOneMoment": "Only Moment %@",
              "DG.plugin.StoryBuilder.storyArea.qRevertPrompt": "Discard changes?",
              "DG.plugin.StoryBuilder.storyArea.qRevertExplanation": "Would you like to discard the changes you made to Moment %@ (and revert to the state it was in before you made changes)?",
              "DG.plugin.StoryBuilder.storyArea.qClickLockPrompt": "Save or discard changes?",
              "DG.plugin.StoryBuilder.storyArea.qClickLockExplanation": "You have made changes to Moment %@. Would you like to save or discard these changes?",
              "DG.plugin.Scrambler.name": "scrambler",
              "DG.plugin.Scrambler.description": "Test hypotheses by randomly varying an attribute.",
              "DG.plugin.Scrambler.language": "English",
              "DG.plugin.Scrambler.static.scramblerTitle": "Scrambler",
              "DG.plugin.Scrambler.static.cantScrambleStripe": "Fix that to proceed.",
              "DG.plugin.Scrambler.static.howManyLabel": "how many?",
              "DG.plugin.Scrambler.static.scrambledDataButtonName": "show scrambled",
              "DG.plugin.Scrambler.sScramble": "scramble",
              "DG.plugin.Scrambler.sNoAttribute": "no attribute 😕",
              "DG.plugin.Scrambler.sIterationAttName": "batch",
              "DG.plugin.Scrambler.sIterationAttDescription": "Which \"batch\" of data. Increases every time you scramble.",
              "DG.plugin.Scrambler.sScrambledAttName": "scrambled att",
              "DG.plugin.Scrambler.sScrambledAttDescription": "Which attribute was scrambled.",
              "DG.plugin.Scrambler.sNoDataset": "Find a dataset and drag the attribute here that you want to scramble!",
              "DG.plugin.Scrambler.sNoScrambleAttribute": "What attribute do you want to scramble? Drag it in here.",
              "DG.plugin.Scrambler.shShowScrambledButtonHelpText": "Show one scrambled dataset",
              "DG.plugin.Scrambler.sfScrambledAttribute": "<span>scramble <code>%@1</code></span>",
              "DG.plugin.Scrambler.sfOKtoScramble": "<span>OK to scramble <code>%@1</code> in dataset <code>%@2</code></span>",
              "DG.plugin.Scrambler.sfNoMeasure": "<span>Your dataset, <code>%@1</code>, needs a measure, which is probably an attribute with a formula. Drag that attribute to the left so you have something to collect!</span>",
              "DG.plugin.Scrambler.sfFormulaProblem": "<span>Scrambling <code>%@1</code> won't work because it has a formula. Drag in a different attribute from the last collection (%@2), such as <code>%@3</code>.</span>",
              "DG.plugin.Scrambler.sfNotALeafProblem": "<span>Scrambling <code>%@1</code> won't work because it's not in the last collection (<code>%@2</code>). Drop an attribute here from <code>%@2</code>, such as <code>%@3</code>.</span>",
              "DG.plugin.Scrambler.sOr": "or",
              "DG.plugin.Scrambler.sScrambledDatasetPrefix": "scrambled_",
              "DG.plugin.Scrambler.sMeasureDatasetPrefix": "measures_from_",
              "DG.plugin.Sampler.title": "Sampler",
              "DG.plugin.Sampler.description": "Create random datasets from scratch or existing datasets.",
              "DG.plugin.Sampler.tab.sampler": "Sampler",
              "DG.plugin.Sampler.tab.options": "Options",
              "DG.plugin.Sampler.tab.about": "About",
              "DG.plugin.Sampler.top-bar.run": "START",
              "DG.plugin.Sampler.top-bar.stop": "STOP",
              "DG.plugin.Sampler.top-bar.pause": "PAUSE",
              "DG.plugin.Sampler.top-bar.medium-speed": "Medium",
              "DG.plugin.Sampler.draw-settings.select-items-p1": "Select",
              "DG.plugin.Sampler.draw-settings.select-items-p2": "items",
              "DG.plugin.Sampler.draw-settings.collect-samples-p1": "Collect",
              "DG.plugin.Sampler.draw-settings.collect-samples-p2": "samples",
              "DG.plugin.Sampler.model-controls.add-variable-title": "Add the next item to the mixer",
              "DG.plugin.Sampler.model-controls.remove-variable-title": "Remove the last item from the mixer",
              "DG.plugin.Sampler.model-controls.add-series-title": "Specify a series of labels for items",
              "DG.plugin.Sampler.model-controls.select-collection-loading": "Loading collections...",
              "DG.plugin.Sampler.reset-title": "Delete all data and extra item-level attributes",
              "DG.plugin.Sampler.reset-text": "CLEAR DATA",
              "DG.plugin.Sampler.device-selection.mixer": "Mixer",
              "DG.plugin.Sampler.device-selection.spinner": "Spinner",
              "DG.plugin.Sampler.device-selection.collector": "Collector",
              "DG.plugin.Sampler.spinner-cover-alt": "transparent cover",
              "DG.plugin.sampler.speed.slow": "Slow",
              "DG.plugin.sampler.speed.medium": "Medium",
              "DG.plugin.sampler.speed.fast": "Fast",
              "DG.plugin.sampler.speed.Fastest": "Fastest",
              "DG.plugin.sampler.collector.noDatasets": "No data sets",
              "DG.plugin.Sampler.selection-options.select-cases": "Select cases",
              "DG.plugin.Sampler.selection-options.with-replacement": "with replacement",
              "DG.plugin.Sampler.selection-options.without-replacement": "without replacement",
              "DG.plugin.Sampler.hide-options.hide": "Hide model",
              "DG.plugin.Sampler.password-options.lock-title": "Lock settings with password:",
              "DG.plugin.Sampler.password-options.lock": "Lock",
              "DG.plugin.Sampler.password-options.unlock-title": "Unlock settings with password:",
              "DG.plugin.Sampler.password-options.unlock": "Unlock",
              "DG.plugin.Sampler.password-options.password-failed": "Password is incorrect.",
              "DG.plugin.Sampler.options.reload": "Reload default settings",
              "DG.plugin.Sampler.about.paragraph1": "The CODAP Sampler plugin can randomly choose items placed in a mixer, choose items based on sector sizes of a spinner, or choose cases from a collection of data.",
              "DG.plugin.Sampler.about.item1": "<b>Select &lt;n&gt; items</b> determines the sample size,",
              "DG.plugin.Sampler.about.item2": "<b>Collect &lt;n&gt; samples</b> controls how many samples to repeat in a given experiment.",
              "DG.plugin.Sampler.about.paragraph2.1": "The speed of sampling can be controlled, as well as whether to sample with or without replacement (in Options tab). The data generated from the Sampler will appear in a hierarchical table. The top level represents the experiment (one complete run of a simulation) and allows you to compute statistics about an entire experiment. The next level contains information about each sample and allows one to compute statistics about each sample. The items level shows each individual value drawn from the Sampler. This ",
              "DG.plugin.Sampler.about.paragraph2.2": " explains Sampler basics.",
              "DG.plugin.Sampler.about.tutorial-link-text": "video tutorial",
              "DG.plugin.Sampler.about.paragraph3.1": "The Sampler in CODAP was inspired by the Sampler in",
              "DG.plugin.Sampler.about.paragraph3.2": ". It was developed by ",
              "DG.plugin.Sampler.about.paragraph3.3": " a part of the ",
              "DG.plugin.Sampler.about.paragraph3.4": "with support by the National Science Foundation under Grant No. DUE <span style=\"color:red;\">1625713</span> awarded to North Carolina State University.",
              "DG.plugin.Sampler.about.paragraph3.6": " Any opinions, findings, and conclusions or recommendations in this material are those of the principal investigators and do not necessarily reflect the views of the National Science Foundation.",
              "DG.plugin.Sampler.about.tinkerPlots-link-text": "TinkerPlots",
              "DG.plugin.Sampler.about.concord-link-text": "Concord Consortium",
              "DG.plugin.Sampler.about.esteem-link-text": "ESTEEM project",
              "DG.plugin.Sampler.about.esteem-logo-text": "Esteem logo",
              "DG.plugin.Sampler.sample-list.parse-error": "Sorry. Unable to parse that. Here are some valid list and range expressions: 'a,b,b,b', 'cat,cat,dog', '1-50', '-5 to 5', '1.0 to 5.0', or 'A-Z'",
              "DG.plugin.Sampler.sample-list.prompt": "Enter a list (e.g. 'cat, cat, dog') or a range (e.g. '1-50', '-5 %@1 5', '1.0 %@1 5.0', 'A-Z')",
              "DG.plugin.Sampler.sample-list.initial-value": "a %@1 c",
              "DG.plugin.Sampler.range-word": "to",
              "DG.plugin.Sampler.dataset.name": "Sampler",
              "DG.plugin.Sampler.dataset.experiment-collection-name": "experiments",
              "DG.plugin.Sampler.dataset.sample-collection-name": "samples",
              "DG.plugin.Sampler.dataset.item-collection-name": "items",
              "DG.plugin.Sampler.dataset.attr-experiment": "experiment",
              "DG.plugin.Sampler.dataset.attr-description": "description",
              "DG.plugin.Sampler.dataset.attr-sample_size": "sample_size",
              "DG.plugin.Sampler.dataset.attr-sample": "sample",
              "DG.plugin.Sampler.dataset.attr-value": "output",
              "DG.plugin.Sampler.dataset.col-experiments": "experiments",
              "DG.plugin.Sampler.dataset.col-samples": "samples",
              "DG.plugin.Sampler.dataset.col-items": "items",
              "DG.plugin.sampler.experiment.description": "%@1 containing %@2 %@3%@4(%@5)",
              "DG.plugin.sampler.experiment.no-description": "hidden!",
              "DG.plugin.sampler.experiment.description-mixer-item-kind": "items",
              "DG.plugin.sampler.experiment.description-spinner-item-kind": "sections",
              "DG.plugin.sampler.experiment.description-collector-item-kind": "cases",
              "DG.plugin.sampler.experiment.description-collector-phrase": " from %@1 ",
              "DG.plugin.sampler.experiment.description-replacement-phrase": "with replacement",
              "DG.plugin.sampler.experiment.description-no-replacement-phrase": "without replacement",
              "DG.plugin.DrawTool.title": "Draw Tool",
              "DG.plugin.DrawTool.description": "Annotate an image.",
              "DG.plugin.MicrodataPortal.title": "Microdata Portal",
              "DG.plugin.MicrodataPortal.description": "Investigate populations from the US census at the individual level.",
              "DG.plugin.NOAA-weather.title": "NOAA Weather",
              "DG.plugin.NOAA-weather.description": "Investigate historical weather patterns.",
              "DG.plugin.Choosy.title": "Choosy",
              "DG.plugin.Choosy.description": "Organize and simplify datasets with many attributes.",
              "DG.plugin.Transformers.title": "Transformers",
              "DG.plugin.Transformers.description": "Transform datasets with a collection of powerful tools.",
              "DG.Locale.name.ko": "Korean",
              "DG.Locale.name.pl": "Polski",
              "DG.Undo.graph.showICI": "Undo showing informal confidence interval",
              "DG.Redo.graph.hideICI": "Redo hiding informal confidence interval",
              "DG.Undo.graph.hideICI": "Undo hiding informal confidence interval",
              "DG.Redo.graph.showICI": "Redo showing informal confidence interval",
              "DG.Undo.graph.showPlottedStErr": "Undo showing standard error",
              "DG.Redo.graph.showPlottedStErr": "Redo showing standard error",
              "DG.Undo.graph.hidePlottedStErr": "Undo hiding standard error",
              "DG.Redo.graph.hidePlottedStErr": "Redo hiding standard error",
              "DG.Undo.graph.setNumStErrs": "Undo setting the number of standard errors",
              "DG.Redo.graph.setNumStErrs": "Redo setting the number of standard errors",
              "DG.Undo.graph.showPlottedNormal": "Undo showing normal curve",
              "DG.Redo.graph.hidePlottedNormal": "Redo hiding normal curve",
              "DG.Undo.graph.hidePlottedNormal": "Undo hiding normal curve",
              "DG.Redo.graph.showPlottedNormal": "Redo showing normal curve",
              "DG.ScatterPlotModel.LSRLCIBandInfo": "Shaded regions shows the range\n in which the true regression line\n lies at 95% confidence level.",
              "DG.PlottedAverageAdornment.stErrValueTitle": "%@ SE%@mean%@=%@",
              "DG.Inspector.graphLSRLSlopeCI": "Show Fit Uncertainty",
              "DG.Inspector.graphSpreadOptions": "Measures of Spread",
              "DG.Inspector.graphPlottedStErr": "Standard Error",
              "DG.Inspector.graphPlottedNormal": "Normal Curve",
              "DG.Inspector.graphPlottedGaussianFit": "Gaussian Fit",
              "DG.Undo.legend.lockQuantiles": "Undo locking legend color bins",
              "DG.Redo.legend.lockQuantiles": "Redo locking legend color bins",
              "DG.Undo.legend.unlockQuantiles": "Undo unlocking legend color bins",
              "DG.Redo.legend.unlockQuantiles": "Redo unlocking legend color bins",
              "DG.Inspector.lockLegendQuantiles": "Lock legend color bins",
              "DG.Inspector.lockLegendQuantilesTooltip": "When checked, the color bins will not change when the values change.",
              "DG.Inspector.graphBoxPlotShowICI": "Show Informal CI",
              "DG.plugin.Sampler.tab.devices": "Model",
              "DG.plugin.Sampler.tab.measures": "Measures",
              "DG.Inspector.graphCenterOptions": "Measures of Center",
              "DG.Inspector.graphBoxPlotNormalCurveOptions": "Box Plot and Normal Curve",
              "DG.Inspector.graphBoxPlotGaussianFitOptions": "Box Plot and Gaussian Fit",
              "DG.Inspector.graphOtherValuesOptions": "Plotted and Movable Values",
              "DG.plugin.Sampler.measures.instructions": "Compute common measures for each sample using the template below.",
              "DG.plugin.Sampler.measures.select-measure": "Select a measure: ",
              "DG.plugin.Sampler.measures.add-measure": "Add Measure",
              "DG.plugin.Sampler.measures.mean": "Mean",
              "DG.plugin.Sampler.measures.mean-formula": "mean",
              "DG.plugin.Sampler.measures.conditional_mean": "Conditional mean",
              "DG.plugin.Sampler.measures.conditional_mean-formula": "mean",
              "DG.plugin.Sampler.measures.difference_of_means": "Difference of means",
              "DG.plugin.Sampler.measures.difference_of_means-formula-pt-1": "mean",
              "DG.plugin.Sampler.measures.difference_of_means-formula-pt-2": "– mean",
              "DG.plugin.Sampler.measures.sum": "Sum",
              "DG.plugin.Sampler.measures.sum-formula": "sum",
              "DG.plugin.Sampler.measures.median": "Median",
              "DG.plugin.Sampler.measures.median-formula": "median",
              "DG.plugin.Sampler.measures.conditional_median": "Conditional median",
              "DG.plugin.Sampler.measures.conditional_median-formula": "median",
              "DG.plugin.Sampler.measures.difference_of_medians": "Difference of medians",
              "DG.plugin.Sampler.measures.difference_of_medians-formula-pt-1": "median",
              "DG.plugin.Sampler.measures.difference_of_medians-formula-pt-2": " - median",
              "DG.plugin.Sampler.measures.conditional_sum": "Conditional sum",
              "DG.plugin.Sampler.measures.conditional_sum-formula": "sum",
              "DG.plugin.Sampler.measures.select-formula": "Select a formula: ",
              "DG.plugin.Sampler.measures.count": "Count",
              "DG.plugin.Sampler.measures.count-formula": "count",
              "DG.plugin.Sampler.measures.percent": "Percent",
              "DG.plugin.Sampler.measures.percent-formula-pt-1": "100 * count",
              "DG.plugin.Sampler.measures.percent-formula-pt-2": " / count( )",
              "DG.plugin.Sampler.measures.name-label": "Name the measure: ",
              "DG.plugin.Testimate.name": "Testimate",
              "DG.plugin.Testimate.description": "Test hypotheses using classical inferential methods.",
              "DG.plugin.PurpleAir.title": "Purple Air",
              "DG.plugin.Sonify.title": "Sonify",
              "DG.plugin.Sonify.description": "Listen to your data",
              "DG.plugin.NHANES.title": "NHANES Portal",
              "DG.plugin.NHANES.description": "Get data from the National Health and Nutrition Examination Survey.",
              "DG.plugin.NASA-data.title": "NASA: Earth, Air, and Water",
              "DG.plugin.NASA-data.description": "Get global data from NASA",
              "DG.plugin.DayLength.title": "Day Length",
              "DG.plugin.DayLength.description": "Get day lengths for any location on Earth plus an astronomical simulation",
              "DG.plugin.Simmer.name": "Simmer",
              "DG.plugin.Simmer.description": "Create block programmed simulations that generate data.",
              "DG.Undo.caseCard.columnWidthChange": "Undo resize case card column",
              "DG.Redo.caseCard.columnWidthChange": "Redo resize case card column",
              "DG.CaseTable.attribute.type.color": "color",
              "V3.general.yes": "Yes",
              "V3.general.no": "No",
              "V3.general.unsavedChangesWarning": "Changes you made may not be saved.",
              "V3.fileMenu.fileMenuName": "File",
              "V3.app.errorDialog.title": "Error",
              "V3.app.errorDialog.description": "An error has occurred that may affect how this program behaves.",
              "V3.app.errorDialog.suggestionWithSave": "You may wish to reload this page after you save a copy of your work.",
              "V3.app.errorDialog.suggestion": "You may wish to reload this page.",
              "V3.app.errorDialog.errorDetails": "(Error: %@)",
              "V3.app.documentDisplayError.title": "Display Error",
              "V3.app.documentDisplayError.suggestion": "Try reloading the page.",
              "V3.app.documentDisplayError.suggestionWithSave": "Try saving a copy of the document and reloading the page.",
              "V3.app.documentDisplayError.reason": "An error is preventing CODAP from displaying the document.",
              "V3.app.documentDisplayError.detailsTitle": "Details",
              "V3.CellAxis.dragCategory": "Click and drag to reorder categories",
              "V3.graph.Inspector.Rescale": "Rescale",
              "V3.graph.Inspector.View": "View",
              "V3.graph.Inspector.Measure": "Measure",
              "V3.graph.Inspector.Config": "Config",
              "V3.graph.Inspector.Format": "Format",
              "V3.graph.Inspector.Image": "Image",
              "V3.Inspector.graph.legendBins": "Legend bins:",
              "V3.Inspector.graph.legendBins.quantize": "Linear",
              "V3.Inspector.graph.legendBins.quantile": "Quantile",
              "V3.Undo.graph.toggleParentVisibility": "Undo toggling visibility",
              "V3.Redo.graph.toggleParentVisibility": "Redo toggling visibility",
              "V3.Undo.graph.hideAllCases": "Undo hiding all cases",
              "V3.Redo.graph.hideAllCases": "Redo hiding all cases",
              "V3.Undo.graph.showAllCases": "Undo showing all cases",
              "V3.Redo.graph.showAllCases": "Redo showing all cases",
              "V3.Undo.graph.adjustMovableLine": "Undo adjusting movable line",
              "V3.Redo.graph.adjustMovableLine": "Redo adjusting movable line",
              "V3.Undo.graph.showLastParentOnly": "Undo showing only last parent case",
              "V3.Redo.graph.showLastParentOnly": "Redo showing only last parent case",
              "V3.Undo.graph.uncheckLastParentOnly": "Undo unchecking \"Last\" checkbox",
              "V3.Redo.graph.uncheckLastParentOnly": "Redo unchecking \"Last\" checkbox",
              "V3.Undo.graph.changeAttributeBinningType": "Undo changing attribute binning type",
              "V3.Redo.graph.changeAttributeBinningType": "Redo changing attribute binning type",
              "V3.map.Inspector.Rescale": "Rescale",
              "V3.map.Inspector.View": "View",
              "V3.map.Inspector.Data": "Data",
              "V3.map.Inspector.Layers": "Layers",
              "V3.map.Inspector.Image": "Image",
              "V3.map.inspector.base": "Base",
              "V3.map.inspector.oceans": "Oceans",
              "V3.map.inspector.topo": "Topo",
              "V3.map.inspector.streets": "Streets",
              "V3.map.inspector.displayAsPoints": "Display as points",
              "V3.map.inspector.displayAsHeatmap": "Display as heatmap",
              "V3.map.inspector.pins": "Pins",
              "V3.Undo.map.showPins": "Undo showing pins on map",
              "V3.Redo.map.showPins": "Redo showing pins on map",
              "V3.Undo.map.hidePins": "Undo hiding pins on map",
              "V3.Redo.map.hidePins": "Redo hiding pins on map",
              "V3.Undo.map.inspector.hideMapLayer": "Undo hiding map layer",
              "V3.Redo.map.inspector.hideMapLayer": "Redo hiding map layer",
              "V3.Undo.map.inspector.showMapLayer": "Undo showing map layer",
              "V3.Redo.map.inspector.showMapLayer": "Redo showing map layer",
              "V3.Undo.map.inspector.changeMapBaseLayer": "Undo changing base map",
              "V3.Redo.map.inspector.changeMapBaseLayer": "Redo changing base map",
              "V3.Undo.map.inspector.changePointType": "Undo changing point type",
              "V3.Redo.map.inspector.changePointType": "Redo changing point type",
              "V3.Undo.map.showLayer": "Undo showing map layer",
              "V3.Redo.map.showLayer": "Redo showing map layer",
              "V3.Undo.map.hideLayer": "Undo hiding map layer",
              "V3.Redo.map.hideLayer": "Redo hiding map layer",
              "V3.Undo.calculator.calculate": "Undo calculation",
              "V3.Redo.calculator.calculate": "Redo calculation",
              "V3.Undo.calculator.clear": "Undo clearing calculator",
              "V3.Redo.calculator.clear": "Redo clearing calculator",
              "V3.CaseCardTable.Inspector.Info": "Info",
              "V3.CaseCardTable.Inspector.Resize": "Resize",
              "V3.CaseCardTable.Inspector.View": "View",
              "V3.CaseCardTable.Inspector.Data": "Data",
              "V3.CaseCardTable.Inspector.Delete": "Delete",
              "V3.CaseTable.collectionTitleText": "%@1 (%@2 cases)",
              "V3.CaseTable.collectionTitleTextWithHidden": "%@1 (%@2 cases, %@3 hidden)",
              "V3.CaseTable.collectionTitleTextWithEmpty": "%@1 (%@2 nonempty cases)",
              "V3.CaseTable.collectionTitleTextWithEmptyAndHidden": "%@1 (%@2 nonempty cases, %@3 hidden)",
              "V3.CaseTable.colorPalette.setColor": "Set Color",
              "V3.CaseTable.colorPalette.cancel": "Cancel",
              "V3.CaseTable.formulaFilterBar.label": "Show cases only if",
              "V3.Undo.caseTable.create": "Undo adding case table",
              "V3.Redo.caseTable.create": "Redo adding case table",
              "V3.Undo.caseTable.delete": "Undo deleting case table",
              "V3.Redo.caseTable.delete": "Redo deleting case table",
              "V3.Undo.caseTable.changeRowHeight": "Undo changing row height",
              "V3.Redo.caseTable.changeRowHeight": "Redo changing row height",
              "V3.Undo.import.data": "Undo import of data",
              "V3.Redo.import.data": "Redo import of data",
              "V3.caseCard.summaryButton.showIndividualCases": "Browse Individual Cases",
              "V3.caseCard.summaryButton.showSummary": "Summarize Dataset",
              "V3.caseCard.addCaseDisabledBecauseFilter": "Cases cannot be added when there is a filter formula",
              "V3.caseCard.addAttributeTooltip": "Add a new attribute to this collection",
              "V3.Undo.hideShowMenu.setAsideCases": "Undo setting aside cases",
              "V3.Redo.hideShowMenu.setAsideCases": "Redo setting aside cases",
              "V3.Undo.hideShowMenu.restoreSetAsideCases": "Undo restoring set aside cases",
              "V3.Redo.hideShowMenu.restoreSetAsideCases": "Redo restoring set aside cases",
              "V3.hideShowMenu.addFilterFormula": "Add Filter Formula...",
              "V3.hideShowMenu.editFilterFormula": "Edit Filter Formula...",
              "V3.hideShowMenu.filterFormulaPrompt": "Filter Formula",
              "V3.Undo.hideShowMenu.changeFilterFormula": "Undo changing filter formula",
              "V3.Redo.hideShowMenu.changeFilterFormula": "Redo changing filter formula",
              "V3.AttrFormView.attrPlaceholder": "attribute",
              "V3.Inspector.rescale.noRescale.toolTip": "All the data are already visible",
              "V3.Inspector.rescale.casePlot.toolTip": "Move the points to new random positions",
              "V3.Slider.Inspector.Playback": "Playback",
              "V3.Slider.Inspector.Scale": "Scale",
              "V3.Inspector.sliderScales.toolTip": "Set slider scale to numeric or date-time",
              "V3.Inspector.animation": "Animation",
              "V3.Inspector.scale": "Scale",
              "V3.Slider.scaleType": "Scale Type:",
              "V3.Slider.scaleType.numeric": "Numeric",
              "V3.Slider.scaleType.date": "Date-Time",
              "V3.Undo.slider.changeScaleType": "Undo change to slider scale type",
              "V3.Redo.slider.changeScaleType": "Redo change to slider scale type",
              "V3.Slider.minimum": "Minimum:",
              "V3.Slider.maximum": "Maximum:",
              "V3.Undo.slider.changeMinimum": "Undo change of slider minimum",
              "V3.Redo.slider.changeMinimum": "Redo change of slider minimum",
              "V3.Undo.slider.changeMaximum": "Undo change of slider maximum",
              "V3.Redo.slider.changeMaximum": "Redo change of slider maximum",
              "V3.WebView.Inspector.URL": "URL",
              "V3.WebView.Modal.PlaceholderText": "URL",
              "V3.WebView.Modal.okBtnTitle": "OK",
              "V3.Undo.webView.show": "Undo adding web page component",
              "V3.Redo.webView.show": "Redo adding web page component",
              "V3.Undo.webView.changeUrl": "Undo changing web page url",
              "V3.Redo.webView.changeUrl": "Redo changing web page url",
              "V3.Undo.tile.show": "Undo showing tile",
              "V3.Redo.tile.show": "Redo showing tile",
              "V3.Undo.plugin.create": "Undo adding %@ plugin",
              "V3.Redo.plugin.create": "Redo adding %@ plugin",
              "V3.formula.error.invalidParentAttrRef": "invalid reference to parent attribute '%@' within aggregate function",
              "V3.formula.error.cycle": "Circular reference: formula refers to its own attribute either directly or indirectly",
              "V3.formula.error.stringConstantArg": "The '%@()' function expects %@ argument to be a string constant",
              "V3.formula.error.caseDependentNotSupported": "This formula scope does not support case-dependent formulas",
              "V3.Undo.mapLegendAttributeChange": "Undo changing map legend attribute",
              "V3.Redo.mapLegendAttributeChange": "Redo changing map legend attribute",
              "V3.Undo.legendAttributeRemove": "Undo removing map legend attribute",
              "V3.Redo.legendAttributeRemove": "Redo removing map legend attribute",
              "V3.Undo.attributeTreatAs": "Undo changing attribute treatment",
              "V3.Redo.attributeTreatAs": "Redo changing attribute treatment",
              "V3.map.legendDrop": "Color regions by values of %@",
              "V3.DataDisplayMenu.treatAsDate": "Treat as Date",
              "V3.DI.Error.noAction": "No action to process.",
              "V3.DI.Error.unsupportedAction": "Unsupported action: %@/%@",
              "V3.DI.Error.undefinedResponse": "Action handler returned undefined.",
              "V3.DI.Error.attributeNotFound": "Attribute not found",
              "V3.DI.Error.fieldRequired": "%@1 %@2: %@3 required",
              "V3.DI.Error.dataContextNotFound": "DataContext not found",
              "V3.DI.Error.dataDisplayNotFound": "DataDisplay not found",
              "V3.DI.Error.dataSetMetadataNotFound": "DataSetMetadata not found for %@",
              "V3.DI.Error.caseNotFound": "Case not found",
              "V3.DI.Error.collectionNotFound": "Collection not found",
              "V3.DI.Error.componentNotCreated": "Could not create component",
              "V3.DI.Error.downloadCSV": "Failed to download and import CSV: %{url}",
              "V3.DI.Error.illegalAttributeAssignment": "Cannot assign %@1 to %@2",
              "V3.DI.Error.cannotFusePointsIntoBars": "Current plot type does not support fusing points into bars",
              "V3.DI.Error.invalidBarChartScale": "Invalid bar chart scale: %@",
              "V3.DI.Error.componentNotFound": "Component not found",
              "V3.DI.Error.unsupportedComponent": "Unsupported component type %@",
              "V3.DI.Error.globalCreation": "error creating global value",
              "V3.DI.Error.globalDuplicateName": "globals must have unique names",
              "V3.DI.Error.globalIllegalValue": "global values must be numbers",
              "V3.DI.Error.globalNotFound": "Global not found: %@",
              "V3.DI.Error.noMultipleSliders": "Cannot create multiple sliders for %@",
              "V3.DI.Error.unsupportedScaleType": "Unsupported scaleType %@",
              "V3.DI.Error.unsupportedDateUnit": "Unsupported dateUnit %@",
              "V3.DI.Error.unsupportedAnimationDirection": "Unsupported animationDirection %@",
              "V3.DI.Error.unsupportedAnimationMode": "Unsupported animationMode %@",
              "V3.DI.Error.missingGlobalOrValue": "missing global or value",
              "V3.DI.Error.interactiveFrameNotFound": "Interactive Frame not found",
              "V3.DI.Error.itemNotFound": "Item not found",
              "V3.DI.Error.notFound": "Not found",
              "V3.DI.Error.colorMapAccess": "Internal error prevented color map access",
              "V3.DI.Error.selectionListIllegalValues": "%@1 selectionList requires a list of case IDs.",
              "V3.DI.Error.valuesRequired": "A values object is required for this request.",
              "V3.DI.Error.invalidValuesProvided": "Invalid values provided for update.",
              "V3.DI.Error.invalidEvaluationRecord": "Invalid record for evaluation",
              "V3.DI.Error.couldNotParseQuery": "Unable to parse query.",
              "V3.DI.Error.unknownRequest": "unknown request: %@",
              "V3.DI.Error.adornmentNotFound": "Adornment not found.",
              "V3.DI.Error.adornmentNotSupported": "Unsupported adornment type",
              "V3.DI.Error.adornmentListNotFound": "Adornment list not found.",
              "V3.DI.Error.adornmentMismatch": "Not a(n) %@1 adornment.",
              "V3.DI.Error.adornmentNotSupportedByPlotType": "Adornment not supported by plot type.",
              "V3.DI.Error.adornmentRequestNotSupported": "The %@1 adornment does not currently support %@2 requests.",
              "V3.DI.Error.countAdornmentPercentNotSupported": "The current plot type does not support Percent.",
              "V3.DI.Error.invalidCellKey": "%@1 contains an invalid attribute name or ID.",
              "V3.DI.Error.componentDoesNotSupportRescale": "Component does not support rescale",
              "V3.PlottedValue.valueTitle": "value=%@",
              "V3.Inspector.graphLSRLShowConfidenceBands": "Show Confidence Bands",
              "V3.Inspector.graphRegionOfInterest": "Region of Interest",
              "V3.Undo.graph.addRegionOfInterest": "Undo showing region of interest",
              "V3.Redo.graph.addRegionOfInterest": "Redo showing region of interest",
              "V3.Undo.graph.removeRegionOfInterest": "Undo hiding region of interest",
              "V3.Redo.graph.removeRegionOfInterest": "Redo hiding region of interest",
              "V3.Undo.graph.showConfidenceBands": "Undo show confidence bands",
              "V3.Redo.graph.showConfidenceBands": "Redo show confidence bands",
              "V3.Undo.graph.hideConfidenceBands": "Undo hide confidence bands",
              "V3.Redo.graph.hideConfidenceBands": "Redo hide confidence bands",
              "V3.Undo.graph.showR": "Undo show r",
              "V3.Redo.graph.showR": "Redo show r",
              "V3.Undo.graph.hideR": "Undo hide r",
              "V3.Redo.graph.hideR": "Redo hide r",
              "V3.Undo.graph.showRSquared": "Undo show r²",
              "V3.Redo.graph.showRSquared": "Redo show r²",
              "V3.Undo.graph.hideRSquared": "Undo hide r²",
              "V3.Redo.graph.hideRSquared": "Redo hide r²",
              "V3.graphLSRL.showR": "Show r",
              "V3.graphLSRL.showRSquared": "Show r²",
              "V3.ToolButtonData.webPageButton.title": "Web Page",
              "V3.ToolButtonData.webPageButton.toolTip": "Open a web page",
              "V3.Undo.webPage.create": "Undo opening a web page",
              "V3.Redo.webPage.create": "Redo opening a web page",
              "V3.ToolButtonData.errorTesterButton.title": "ErrTest",
              "V3.ToolButtonData.errorTesterButton.toolTip": "Make an error tester",
              "V3.Undo.errorTester.create": "Undo adding error tester",
              "V3.Redo.errorTester.create": "Redo adding error tester",
              "V3.AppController.optionMenuItems.positionToolShelfLeft": "Toolbar Position: Top",
              "V3.AppController.optionMenuItems.positionToolShelfTop": "Toolbar Position: Left"
});