SC.stringsFor("de", {
    "DG.fileMenu.menuItem.newDocument": "Neu",
    "DG.fileMenu.menuItem.openDocument": "Öffnen...",
    "DG.fileMenu.menuItem.closeDocument": "Schließen",
    "DG.fileMenu.menuItem.importFile": "Importieren ...",
    "DG.fileMenu.menuItem.revertTo": "Zurückkehren...",
    "DG.fileMenu.menuItem.revertToOpened": "Kürzlich geöffnete Fassung",
    "DG.fileMenu.menuItem.revertToShared": "Geteilte Ansicht",
    "DG.fileMenu.menuItem.saveDocument": "Speichern ...",
    "DG.fileMenu.menuItem.copyDocument": "Kopie erstellen",
    "DG.fileMenu.menuItem.share": "Teilen ...",
    "DG.fileMenu.menuItem.shareGetLink": "Link erhalten für geteilte Ansicht",
    "DG.fileMenu.menuItem.shareUpdate": "Geteilte Ansicht aktualisieren",
    "DG.fileMenu.menuItem.renameDocument": "Umbennen",
    "DG.main.userEntryView.title": "Was soll getan werden?",
    "DG.main.userEntryView.openDocument": "Dokument öffnen oder Beispiele ansehen",
    "DG.main.userEntryView.newDocument": "Neues Dokument erstellen",
    "DG.mainPage.mainPane.undoButton.title": "Rückgängig",
    "DG.mainPage.mainPane.undoButton.toolTip": "Die letzte Aktion rückgängig machen",
    "DG.mainPage.mainPane.redoButton.title": "Wiederholen",
    "DG.mainPage.mainPane.redoButton.toolTip": "Letzte Aktion wiederholen",
    "DG.mainPage.mainPane.versionString": "Version %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Leider wird CODAP aktuell nicht vom verwendeten Browser unterstützt. CODAP wird unterstützt von Firefox 46+, Chrome 50+, Windows Edge 14+ und Safari 10+. CODAP wird zur Zeit nicht von anderen Browsern unterstützt.",
    "DG.mainPage.titleBar.saved": "Dokument gespeichert!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Version %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Version %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Clear Data...",
    "DG.AppController.resetData.toolTip": "Alle Daten des aktuellen Dokuments löschen",
    "DG.AppController.resetData.warnMessage": "Sollen wirklich alle Daten in diesem Dokument gelöscht werden?",
    "DG.AppController.resetData.warnDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.AppController.resetData.okButtonTitle": "Ja, Daten löschen",
    "DG.AppController.resetData.cancelButtonTitle": "Nein, Daten behalten",
    "DG.AppController.closeDocument.warnMessage": "Ohne Speichern schließen?",
    "DG.AppController.closeDocument.warnDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.AppController.closeDocument.okButtonTitle": "Schließen",
    "DG.AppController.closeDocument.cancelButtonTitle": "Abbrechen",
    "DG.AppController.beforeUnload.confirmationMessage": "Das Dokument enthält ungespeicherte Änderungen.",
    "DG.AppController.optionMenuItems.reportProblem": "Feedback senden...",
    "DG.AppController.optionMenuItems.viewWebPage": "Webseite anzeigen...",
    "DG.AppController.optionMenuItems.configureGuide": "Configure Guide...",
    "DG.AppController.optionMenuItems.about": "Über CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "Neuigkeiten",
    "DG.AppController.optionMenuItems.help": "Hilfe...",
    "DG.AppController.optionMenuItems.toWebSite": "CODAP Webseite",
    "DG.AppController.exportDocument.prompt": "Dateiname:",
    "DG.AppController.exportCaseData.prompt": "Export the case data, from:",
    "DG.AppController.exportDocument.exportTitle": "Exportieren",
    "DG.AppController.exportDocument.exportTooltip": "Export data to a file",
    "DG.AppController.exportDocument.cancelTitle": "Abbrechen",
    "DG.AppController.exportDocument.cancelTooltip": "Cancel the export",
    "DG.AppController.feedbackDialog.dialogTitle": "Provide Feedback",
    "DG.AppController.feedbackDialog.subHeaderText": "Your feedback is important to us!",
    "DG.AppController.feedbackDialog.messageText": "Please help us continue to improve our product. Questions, bug reports and feature requests are all welcome. Thank you!",
    "DG.AppController.feedbackDialog.subjectHint": "What is your feedback about",
    "DG.AppController.feedbackDialog.feedbackHint": "Details",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Submit",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Abbrechen",
    "DG.AppController.showWebSiteTitle": "Über CODAP",
    "DG.AppController.showHelpTitle": "Hilfe zu CODAP",
    "DG.AppController.showAboutTitle": "Über CODAP",
    "DG.AppController.showReleaseNotesTitle": "CODAP Release Notes",
    "DG.AppController.dropFile.error": "Error: %@1",
    "DG.AppController.dropFile.unknownFileType": "You cannot import the type of file dropped",
    "DG.AppController.validateDocument.missingRequiredProperty": "Required property not found: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Unexpected top-level property: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Unresolved id: %@1",
    "DG.AppController.validateDocument.parseError": "Parse error in document: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Invalid JSON Document: %@1",
    "DG.AppController.openDocument.error.general": "Das Dokument konnte nicht geöffnet werden.",
    "DG.AppController.openDocument.error.invalid_format": "CODAP can not read this type of document",
    "DG.AppController.createDataSet.initialAttribute": "Merkmal",
    "DG.AppController.createDataSet.name": "New Dataset",
    "DG.AppController.createDataSet.collectionName": "Fälle",
    "DG.AppController.caseTableMenu.newDataSet": "-- new --",
    "DG.SingleTextDialog.okButton.title": "OK",
    "DG.SingleTextDialog.cancelButton.title": "Abbrechen",
    "DG.SingleTextDialog.cancelButton.toolTip": "Dismiss the dialog without making any changes",
    "DG.DocumentController.calculatorTitle": "Taschenrechner",
    "DG.DocumentController.caseTableTitle": "Case Table",
    "DG.DocumentController.graphTitle": "Graph",
    "DG.DocumentController.sliderTitle": "Regler",
    "DG.DocumentController.textTitle": "Textfeld",
    "DG.DocumentController.mapTitle": "Karte",
    "DG.DocumentController.enterURLPrompt": "Enter the URL of a web page to display",
    "DG.DocumentController.enterViewWebPageOKTip": "Displays the web page given by the URL",
    "DG.Document.defaultDocumentName": "Unbenanntes Dokument",
    "DG.Document.documentName.toolTip": "Click to edit document name",
    "DG.SliderView.thumbView.toolTip": "Drag to change the slider's value",
    "DG.SliderView.startButton.toolTip": "Animation starten/anhalten",
    "DG.ToolButtonData.tableButton.title": "Tabellen",
    "DG.ToolButtonData.tableButton.toolTip": "Open a case table for each data set(ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Graph",
    "DG.ToolButtonData.graphButton.toolTip": "Make a graph (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Regler",
    "DG.ToolButtonData.sliderButton.toolTip": "Make a slider (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "Rechner",
    "DG.ToolButtonData.calcButton.toolTip": "Open/close the calculator (ctrl-alt-c)",
    "DG.ToolButtonData.textButton.title": "Text",
    "DG.ToolButtonData.textButton.toolTip": "Make a text object (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "Karte",
    "DG.ToolButtonData.mapButton.toolTip": "Eine Karte erstellen",
    "DG.ToolButtonData.optionMenu.title": "Einstellungen",
    "DG.ToolButtonData.optionMenu.toolTip": "Display a website, configure guide...",
    "DG.ToolButtonData.tileListMenu.title": "Tiles",
    "DG.ToolButtonData.tileListMenu.toolTip": "Show the list of tiles in the document",
    "DG.ToolButtonData.guideMenu.title": "Guide",
    "DG.ToolButtonData.guideMenu.toolTip": "Show the guide for this activity and navigate within it",
    "DG.ToolButtonData.guideMenu.showGuide": "Show Guide",
    "DG.ToolButtonData.help.title": "Hilfe",
    "DG.ToolButtonData.help.toolTip": "Hilfe zu CODAP, das Projekt kennenlernen",
    "DG.Slider.multiples": "Begrenzen auf Vielfache von:",
    "DG.Slider.maxPerSecond": "Maximum Animation Frames/sec",
    "DG.Slider.direction": "Animation Direction:",
    "DG.Slider.backAndForth": "Vor und Zurück",
    "DG.Slider.lowToHigh": "Niedrig zu Hoch",
    "DG.Slider.highToLow": "Hoch zu Niedrig",
    "DG.Slider.mode": "Animation Repetition:",
    "DG.Slider.nonStop": "pausenlos",
    "DG.Slider.onceOnly": "Nur einmal",
    "DG.Undo.exceptionOccurred": "Ein Fehler trat auf beim Rückgängig Machen.",
    "DG.Redo.exceptionOccurred": "Ein Fehler trat auf beim Wiederholen.",
    "DG.Undo.componentMove": "Rückgängig: Das Objekt verschieben",
    "DG.Redo.componentMove": "Wiederholen: Das Objekt verschieben",
    "DG.Undo.componentResize": "Rückgängig: Größenänderung des Objekts",
    "DG.Redo.componentResize": "Wiederholen: Größenänderung des Objekts",
    "DG.Undo.axisDilate": "Rückgängig: Die Achse verändern",
    "DG.Redo.axisDilate": "Wiederholen: Die Achse verändern",
    "DG.Undo.axisRescaleFromData": "Rückgängig: Die Achse verändern",
    "DG.Redo.axisRescaleFromData": "Wiederholen: Die Achse verändern",
    "DG.Undo.axisDrag": "Undo dragging the axis",
    "DG.Redo.axisDrag": "Redo dragging the axis",
    "DG.Undo.axisAttributeChange": "Rückgängig: Das Merkmal der Achse verändern",
    "DG.Redo.axisAttributeChange": "Wiederholen: Das Merkmal der Achse verändern",
    "DG.Undo.axisAttributeAdded": "Rückgängig: Der Achse ein Merkmal hinzufügen",
    "DG.Redo.axisAttributeAdded": "Wiederholen: Der Achse ein Merkmal hinzufügen",
    "DG.Undo.toggleComponent.add.calcView": "Rückgängig: Den Taschenrechner einblenden",
    "DG.Redo.toggleComponent.add.calcView": "Wiederholen: Den Taschenrechner einblenden",
    "DG.Undo.toggleComponent.delete.calcView": "Rückgängig: Den Taschenrechner verbergen",
    "DG.Redo.toggleComponent.delete.calcView": "Wiederholen: Den Taschenrechner verbergen",
    "DG.Undo.caseTable.open": "Rückgängig: Die Tabelle einblenden",
    "DG.Redo.caseTable.open": "Wiederholen: Die Tabelle einblenden",
    "DG.Undo.caseTable.editAttribute": "Undo editing case table attribute",
    "DG.Redo.caseTable.editAttribute": "Redo editing case table attribute",
    "DG.Undo.caseTable.createAttribute": "Undo creating case table attribute",
    "DG.Redo.caseTable.createAttribute": "Redo creating case table attribute",
    "DG.Undo.caseTable.editAttributeFormula": "Undo editing case table attribute formula",
    "DG.Redo.caseTable.editAttributeFormula": "Redo editing case table attribute formula",
    "DG.Undo.caseTable.editCellValue": "Undo editing case table cell value",
    "DG.Redo.caseTable.editCellValue": "Redo editing case table cell value",
    "DG.Undo.caseTable.sortCases": "Undo sorting cases",
    "DG.Redo.caseTable.sortCases": "Redo sorting cases",
    "DG.Undo.caseTable.deleteAttribute": "Undo deleting case table attribute",
    "DG.Redo.caseTable.deleteAttribute": "Redo deleting case table attribute",
    "DG.Undo.caseTable.createCollection": "Undo create new collection",
    "DG.Redo.caseTable.createCollection": "Redo create new collection",
    "DG.Undo.caseTable.collectionNameChange": "Undo rename collection",
    "DG.Redo.caseTable.collectionNameChange": "Redo rename collection",
    "DG.Undo.caseTable.createNewCase": "Undo create new case",
    "DG.Redo.caseTable.createNewCase": "Redo create new case",
    "DG.Undo.caseTable.insertCases": "Undo insert cases",
    "DG.Redo.caseTable.insertCases": "Redo insert cases",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Undo toggle expand/collapse all",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Redo toggle expand/collapse all",
    "DG.Undo.caseTable.expandCollapseOneCase": "Undo expand or collapse of a group",
    "DG.Redo.caseTable.expandCollapseOneCase": "Redo expand or collapse of a group",
    "DG.Undo.caseTable.resizeColumns": "Undo auto-resize all columns",
    "DG.Redo.caseTable.resizeColumns": "Redo auto-resize all columns",
    "DG.Undo.document.share": "Undo sharing the document",
    "DG.Redo.document.share": "Redo sharing the document",
    "DG.Undo.document.unshare": "Undo stop sharing the document",
    "DG.Redo.document.unshare": "Redo stop sharing the document",
    "DG.Undo.game.add": "Undo adding a game to the document",
    "DG.Redo.game.add": "Redo adding a game to the document",
    "DG.Undo.graph.showCount": "Undo showing count",
    "DG.Redo.graph.showCount": "Redo showing count",
    "DG.Undo.graph.hideCount": "Undo hiding count",
    "DG.Redo.graph.hideCount": "Redo hiding count",
    "DG.Undo.graph.showPercent": "Undo showing percent",
    "DG.Redo.graph.showPercent": "Redo showing percent",
    "DG.Undo.graph.hidePercent": "Undo hiding percent",
    "DG.Redo.graph.hidePercent": "Redo hiding percent",
    "DG.Undo.graph.showMovableLine": "Undo showing movable line",
    "DG.Redo.graph.showMovableLine": "Redo showing movable line",
    "DG.Undo.graph.hideMovableLine": "Undo hiding movable line",
    "DG.Redo.graph.hideMovableLine": "Redo hiding movable line",
    "DG.Undo.graph.lockIntercept": "Undo locking line intercept",
    "DG.Redo.graph.lockIntercept": "Redo locking line intercept",
    "DG.Undo.graph.unlockIntercept": "Undo unlocking line intercept",
    "DG.Redo.graph.unlockIntercept": "Redo unlocking line intercept",
    "DG.Undo.graph.showPlotFunction": "Undo showing plotted function",
    "DG.Redo.graph.showPlotFunction": "Redo showing plotted function",
    "DG.Undo.graph.hidePlotFunction": "Undo hiding plotted function",
    "DG.Redo.graph.hidePlotFunction": "Redo hiding plotted function",
    "DG.Undo.graph.changePlotFunction": "Undo change plotted function",
    "DG.Redo.graph.changePlotFunction": "Redo change plotted function",
    "DG.Undo.graph.showPlotValue": "Undo showing plotted value",
    "DG.Redo.graph.showPlotValue": "Redo showing plotted value",
    "DG.Undo.graph.hidePlotValue": "Undo hiding plotted value",
    "DG.Redo.graph.hidePlotValue": "Redo hiding plotted value",
    "DG.Undo.graph.changePlotValue": "Undo change plotted value",
    "DG.Redo.graph.changePlotValue": "Redo change plotted value",
    "DG.Undo.graph.showConnectingLine": "Undo showing connecting line",
    "DG.Redo.graph.showConnectingLine": "Redo showing connecting line",
    "DG.Undo.graph.hideConnectingLine": "Undo hiding connecting line",
    "DG.Redo.graph.hideConnectingLine": "Redo hiding connecting line",
    "DG.Undo.graph.showLSRL": "Undo showing least squares line",
    "DG.Redo.graph.showLSRL": "Redo showing least squares line",
    "DG.Undo.graph.hideLSRL": "Undo hiding least squares line",
    "DG.Redo.graph.hideLSRL": "Redo hiding least squares line",
    "DG.Undo.graph.showSquares": "Undo showing squares",
    "DG.Redo.graph.showSquares": "Redo showing squares",
    "DG.Undo.graph.hideSquares": "Undo hiding squares",
    "DG.Redo.graph.hideSquares": "Redo hiding squares",
    "DG.Undo.graph.showPlottedMean": "Undo showing mean",
    "DG.Redo.graph.showPlottedMean": "Redo showing mean",
    "DG.Undo.graph.hidePlottedMean": "Undo hiding mean",
    "DG.Redo.graph.hidePlottedMean": "Redo hiding mean",
    "DG.Undo.graph.showPlottedMedian": "Undo showing median",
    "DG.Redo.graph.showPlottedMedian": "Redo showing median",
    "DG.Undo.graph.hidePlottedMedian": "Undo hiding median",
    "DG.Redo.graph.hidePlottedMedian": "Redo hiding median",
    "DG.Undo.graph.showPlottedStDev": "Undo showing standard deviation",
    "DG.Redo.graph.showPlottedStDev": "Redo showing standard deviation",
    "DG.Undo.graph.hidePlottedStDev": "Undo hiding standard deviation",
    "DG.Redo.graph.hidePlottedStDev": "Redo hiding standard deviation",
    "DG.Undo.graph.showPlottedIQR": "Undo showing inter-quartile range",
    "DG.Redo.graph.hidePlottedIQR": "Redo hiding inter-quartile range",
    "DG.Undo.graph.hidePlottedIQR": "Undo hiding inter-quartile range",
    "DG.Redo.graph.showPlottedIQR": "Redo showing inter-quartile range",
    "DG.Undo.graph.addMovableValue": "Undo adding movable value",
    "DG.Redo.graph.addMovableValue": "Redo adding movable value",
    "DG.Undo.graph.removeMovableValue": "Undo removing movable value",
    "DG.Redo.graph.removeMovableValue": "Redo removing movable value",
    "DG.Undo.graph.moveMovableValue": "Undo moving movable value",
    "DG.Redo.graph.moveMovableValue": "Redo moving movable value",
    "DG.Undo.graph.changePointColor": "Undo changing data color",
    "DG.Redo.graph.changePointColor": "Redo changing data color",
    "DG.Undo.graph.changeStrokeColor": "Undo changing stroke color",
    "DG.Redo.graph.changeStrokeColor": "Redo changing stroke color",
    "DG.Undo.graph.changePointSize": "Undo changing point size",
    "DG.Redo.graph.changePointSize": "Redo changing point size",
    "DG.Undo.graph.changeAttributeColor": "Undo changing attribute color",
    "DG.Redo.graph.changeAttributeColor": "Redo changing attribute color",
    "DG.Undo.graph.changeBackgroundColor": "Undo changing graph background color",
    "DG.Redo.graph.changeBackgroundColor": "Redo changing graph background color",
    "DG.Undo.graph.toggleTransparent": "Undo toggling plot transparency",
    "DG.Redo.graph.toggleTransparent": "Redo toggling plot transparency",
    "DG.Undo.guide.show": "Undo showing the guide",
    "DG.Redo.guide.show": "Redo showing the guide",
    "DG.Undo.guide.navigate": "Undo changing the guide page",
    "DG.Redo.guide.navigate": "Redo changing the guide page",
    "DG.Undo.hideSelectedCases": "Undo hiding selected cases",
    "DG.Redo.hideSelectedCases": "Redo hiding selected cases",
    "DG.Undo.hideUnselectedCases": "Undo hiding unselected cases",
    "DG.Redo.hideUnselectedCases": "Redo hiding unselected cases",
    "DG.Undo.enableNumberToggle": "Undo Show Parent Visibility Toggles",
    "DG.Redo.enableNumberToggle": "Redo Show Parent Visibility Toggles",
    "DG.Undo.disableNumberToggle": "Undo Hide Parent Visibility Toggles",
    "DG.Redo.disableNumberToggle": "Redo Hide Parent Visibility Toggles",
    "DG.Undo.interactiveUndoableAction": "Undo an action in the interactive",
    "DG.Redo.interactiveUndoableAction": "Redo an action in the interactive",
    "DG.Undo.showAllCases": "Undo showing all cases",
    "DG.Redo.showAllCases": "Redo showing all cases",
    "DG.Undo.map.create": "Undo adding map",
    "DG.Redo.map.create": "Redo adding map",
    "DG.Undo.map.fitBounds": "Undo resizing map",
    "DG.Redo.map.fitBounds": "Redo resizing map",
    "DG.Undo.map.pan": "Undo panning map",
    "DG.Redo.map.pan": "Redo panning map",
    "DG.Undo.map.zoom": "Undo zooming map",
    "DG.Redo.map.zoom": "Redo zooming map",
    "DG.Undo.map.showGrid": "Undo showing grid on map",
    "DG.Redo.map.showGrid": "Redo showing grid on map",
    "DG.Undo.map.hideGrid": "Undo hiding grid on map",
    "DG.Redo.map.hideGrid": "Redo hiding grid on map",
    "DG.Undo.map.changeGridSize": "Undo changing map grid size",
    "DG.Redo.map.changeGridSize": "Redo changing map grid size",
    "DG.Undo.map.showPoints": "Undo showing points on map",
    "DG.Redo.map.showPoints": "Redo showing points on map",
    "DG.Undo.map.hidePoints": "Undo hiding points on map",
    "DG.Redo.map.hidePoints": "Redo hiding points on map",
    "DG.Undo.map.showLines": "Undo showing lines on map",
    "DG.Redo.map.showLines": "Redo showing lines on map",
    "DG.Undo.map.hideLines": "Undo hiding lines on map",
    "DG.Redo.map.hideLines": "Redo hiding lines on map",
    "DG.Undo.map.changeBaseMap": "Undo changing map background",
    "DG.Redo.map.changeBaseMap": "Redo changing map background",
    "DG.Undo.textComponent.create": "Undo adding text object",
    "DG.Redo.textComponent.create": "Redo adding text object",
    "DG.Undo.textComponent.edit": "Undo editing text",
    "DG.Redo.textComponent.edit": "Redo editing text",
    "DG.Undo.sliderComponent.create": "Undo adding a slider",
    "DG.Redo.sliderComponent.create": "Redo adding a slider",
    "DG.Undo.slider.change": "Undo slider value change",
    "DG.Redo.slider.change": "Redo slider value change",
    "DG.Undo.slider.changeMultiples": "Undo change to slider multiples restriction",
    "DG.Redo.slider.changeMultiples": "Redo change to slider multiples restriction",
    "DG.Undo.slider.changeSpeed": "Undo change to slider max frames/sec",
    "DG.Redo.slider.changeSpeed": "Redo change to slider max frames/sec",
    "DG.Undo.slider.changeDirection": "Undo change to slider animation direction",
    "DG.Redo.slider.changeDirection": "Redo change to slider animation direction",
    "DG.Undo.slider.changeRepetition": "Undo change to slider animation repetition",
    "DG.Redo.slider.changeRepetition": "Redo change to slider animation repetition",
    "DG.Undo.graphComponent.create": "Undo adding a graph",
    "DG.Redo.graphComponent.create": "Redo adding a graph",
    "DG.Undo.dataContext.create": "Undo creating a data set",
    "DG.Redo.dataContext.create": "Redo creating a data set",
    "DG.Undo.data.deleteCases": "Undo deleting cases",
    "DG.Redo.data.deleteCases": "Redo deleting cases",
    "DG.Undo.component.close": "Undo closing component",
    "DG.Redo.component.close": "Redo closing component",
    "DG.Undo.component.minimize": "Undo minimizing component",
    "DG.Redo.component.minimize": "Redo minimizing component",
    "DG.Undo.dataContext.moveAttribute": "Undo moving case table attribute",
    "DG.Redo.dataContext.moveAttribute": "Redo moving case table attribute",
    "DG.DataContext.singleCaseName": "Fall",
    "DG.DataContext.pluralCaseName": "Fälle",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "Eine Kollektion",
    "DG.DataContext.collapsedRowString": "%@1 of %@2",
    "DG.DataContext.noData": "Keine Daten",
    "DG.DataContext.baseName": "Data_Set_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "The formula for attribute \"%@\" is not editable.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Create a new attribute to be able to specify a formula.",
    "DG.Formula.FuncCategoryArithmetic": "Arithmetic Functions",
    "DG.Formula.FuncCategoryConversion": "Other Functions",
    "DG.Formula.FuncCategoryDateTime": "Date/Time Functions",
    "DG.Formula.FuncCategoryLookup": "Lookup Functions",
    "DG.Formula.FuncCategoryOther": "Other Functions",
    "DG.Formula.FuncCategoryRandom": "Other Functions",
    "DG.Formula.FuncCategoryStatistical": "Statistical Functions",
    "DG.Formula.FuncCategoryString": "String Functions",
    "DG.Formula.FuncCategoryTrigonometric": "Trigonometric Functions",
    "DG.Formula.DateLongMonthJanuary": "Januar",
    "DG.Formula.DateLongMonthFebruary": "Februar",
    "DG.Formula.DateLongMonthMarch": "März",
    "DG.Formula.DateLongMonthApril": "April",
    "DG.Formula.DateLongMonthMay": "Mai",
    "DG.Formula.DateLongMonthJune": "Juni",
    "DG.Formula.DateLongMonthJuly": "Juli",
    "DG.Formula.DateLongMonthAugust": "August",
    "DG.Formula.DateLongMonthSeptember": "September",
    "DG.Formula.DateLongMonthOctober": "Oktober",
    "DG.Formula.DateLongMonthNovember": "November",
    "DG.Formula.DateLongMonthDecember": "Dezember",
    "DG.Formula.DateShortMonthJanuary": "Jan",
    "DG.Formula.DateShortMonthFebruary": "Feb",
    "DG.Formula.DateShortMonthMarch": "Mär",
    "DG.Formula.DateShortMonthApril": "Apr",
    "DG.Formula.DateShortMonthMay": "Mai",
    "DG.Formula.DateShortMonthJune": "Jun",
    "DG.Formula.DateShortMonthJuly": "Jul",
    "DG.Formula.DateShortMonthAugust": "Aug",
    "DG.Formula.DateShortMonthSeptember": "Sep",
    "DG.Formula.DateShortMonthOctober": "Okt",
    "DG.Formula.DateShortMonthNovember": "Nov",
    "DG.Formula.DateShortMonthDecember": "Dez",
    "DG.Formula.DateLongDaySunday": "Sonntag",
    "DG.Formula.DateLongDayMonday": "Montag",
    "DG.Formula.DateLongDayTuesday": "Dienstag",
    "DG.Formula.DateLongDayWednesday": "Mittwoch",
    "DG.Formula.DateLongDayThursday": "Donnerstag",
    "DG.Formula.DateLongDayFriday": "Freitag",
    "DG.Formula.DateLongDaySaturday": "Samstag",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mär|apr|mai|jun|jul|aug|sep|okt|nov|dez)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Syntax error: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Incomplete expression",
    "DG.Formula.SyntaxErrorInvalidOperator": "invalid operator '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "invalid type(s) for '%@'",
    "DG.Formula.TypeError.description": "invalid type(s) for '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' is unrecognized",
    "DG.Formula.VarReferenceError.description": "variable '%@' is unrecognized",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "invalid reference to child attribute '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' is a child attribute that can only be referenced in an aggregate function",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' is unrecognized",
    "DG.Formula.FuncReferenceError.description": "function '%@()' is unrecognized",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' expects 1 argument",
    "DG.Formula.FuncArgsErrorSingle.description": "The '%@()' function expects 1 argument",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' expects %@ arguments",
    "DG.Formula.FuncArgsErrorPlural.description": "The '%@()' function expects %@ arguments",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' expects %@-%@ arguments",
    "DG.Formula.FuncArgsErrorRange.description": "The '%@()' function expects %@-%@ arguments",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "request pending...",
    "DG.Formula.PendingRequest.description": "request pending...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "request failed (%@)",
    "DG.Formula.FailedRequest.description": "request failed (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "boundaries pending...",
    "DG.Formula.PendingBoundaries.description": "boundaries pending...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "boundaries failed (%@)",
    "DG.Formula.FailedBoundaries.description": "boundaries failed (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': unrecognized data set",
    "DG.Formula.LookupDataSetError.description": "Data set '%@' is unrecognized",
    "DG.Formula.LookupAttrError.message": "'%@' not found in data set '%@'",
    "DG.Formula.LookupAttrError.description": "Attribute '%@' not found in data set '%@'",
    "DG.TableController.headerMenuItems.editAttribute": "Eigenschaften des Merkmals bearbeiten...",
    "DG.TableController.headerMenuItems.editFormula": "Formel bearbeiten...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Rerandomisieren",
    "DG.TableController.headerMenuItems.sortAscending": "Aufsteigend sortieren (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Absteigend sortieren (Z→A, 9→0)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Merkmal löschen",
    "DG.TableController.newAttrDlg.defaultAttrName": "neues_Merkm",
    "DG.TableController.newAttrDlg.attrNameHint": "Einen Namen eingeben für das neue Merkmal",
    "DG.TableController.newAttrDlg.formulaHint": "If desired, type a formula for computing values of this attribute",
    "DG.TableController.newAttrDlg.applyTooltip": "Define the new attribute using the name and (optional) formula",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Please enter a name for the new attribute",
    "DG.TableController.newAttrDialog.AttributesCategory": "Merkmale",
    "DG.TableController.newAttrDialog.SpecialCategory": "Special",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Globals",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Constants",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Functions",
    "DG.TableController.renameAttributeInvalidMsg": "Merkmalsnamen dürfen nicht leer sein",
    "DG.TableController.renameAttributeInvalidDesc": "Bitte einen gültigen Merkmalsnamen eingeben",
    "DG.TableController.renameAttributeDuplicateMsg": "Dieser Merkmalsname ist bereits vergeben",
    "DG.TableController.renameAttributeDuplicateDesc": "Bitte einen eindeutigen Merkmalsnamen eingeben",
    "DG.TableController.deleteAttribute.confirmMessage": "Delete the attribute '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Merkmal löschen",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Abbrechen",
    "DG.TableController.deleteDataSet.confirmMessage": "Delete and destroy this data set: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Datensatz löschen",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Abbrechen",
    "DG.TableController.attrEditor.precisionHint": "Anzahl der Stellen nach dem Komma",
    "DG.TableController.attrEditor.unitHint": "Unit of measure, if applicable",
    "DG.TableController.attrEditor.descriptionHint": "Describe the attribute",
    "DG.TableController.scoreAttrName": "score",
    "DG.TableController.setScoreDlg.applyTooltip": "Set the formula for the '%@' attribute",
    "DG.TableController.setScoreDlg.formulaHint": "Type a formula for computing values of this attribute",
    "DG.TableController.newAttributeTooltip": "Add a new attribute to this table",
    "DG.TableController.attributeEditor.title": "Attribute Properties",
    "DG.CaseTableDropTarget.dropMessage": "drop attribute to create new collection",
    "DG.CaseTable.defaultAttrName": "newAttr",
    "DG.CaseTable.indexColumnName": "index",
    "DG.CaseTable.indexColumnTooltip": "The row number (caseIndex) within the collection",
    "DG.CaseTable.indexMenu.insertCase": "Fall hinzufügen",
    "DG.CaseTable.indexMenu.insertCases": "Fälle hinzufügen",
    "DG.CaseTable.indexMenu.deleteCase": "Fall löschen",
    "DG.CaseTable.indexMenu.deleteCases": "Fälle löschen",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "kategorial",
    "DG.CaseTable.attribute.type.categorical": "kategorial",
    "DG.CaseTable.attribute.type.numeric": "numerisch",
    "DG.CaseTable.attribute.type.date": "Datum",
    "DG.CaseTable.attribute.type.qualitative": "qualitativ",
    "DG.CaseTable.attribute.type.boundary": "boundary",
    "DG.CaseTable.attributeEditor.name": "Name",
    "DG.CaseTable.attributeEditor.description": "Beschreibung",
    "DG.CaseTable.attributeEditor.type": "Typ",
    "DG.CaseTable.attributeEditor.unit": "Einheit",
    "DG.CaseTable.attributeEditor.precision": "Genauigkeit",
    "DG.CaseTable.attributeEditor.editable": "editierbar",
    "DG.CaseTable.insertCasesDialog.title": "Fälle hinzufügen",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# cases to insert:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "location:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "before",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "after",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Insert Cases",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Insert the specified number of cases",
    "DG.CaseTableController.allTables": "All tables",
    "DG.AttrFormView.attrNamePrompt": "Attribute Name:",
    "DG.AttrFormView.formulaPrompt": "Formula:",
    "DG.AttrFormView.operandMenuTitle": "--- Insert Value ---",
    "DG.AttrFormView.functionMenuTitle": "--- Insert Function ---",
    "DG.AttrFormView.applyBtnTitle": "Apply",
    "DG.AttrFormView.cancelBtnTitle": "Cancel",
    "DG.AttrFormView.cancelBtnTooltip": "Dismiss the dialog without making any changes",
    "DG.GuideConfigView.titlePrompt": "Guide Title",
    "DG.GuideConfigView.titleHint": "Activity Name",
    "DG.GuideConfigView.itemTitleHint": "Section Name",
    "DG.GuideConfigView.itemURLHint": "URL of section",
    "DG.GuideConfigView.okBtnTitle": "OK",
    "DG.GuideConfigView.okBtnToolTip": "Accept the Guide menu items",
    "DG.GuideConfigView.cancelBtnTitle": "Abbrechen",
    "DG.GuideConfigView.cancelBtnTooltip": "Dismiss the dialog without making any changes",
    "DG.GuideConfigView.httpWarning": "The URL must start with either http:// or https://",
    "DG.DataDisplayModel.rescaleToData": "Rescale to Data",
    "DG.DataDisplayModel.ShowConnectingLine": "Verbindungslinien zeigen",
    "DG.DataDisplayModel.HideConnectingLine": "Verbindungslinien verbergen",
    "DG.AxisView.emptyGraphCue": "Hier klicken oder ein Merkmal hierher ziehen",
    "DG.CellLinearAxisView.midPanelTooltip": "Drag to translate axis scale",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Drag to change axis lower bound",
    "DG.CellLinearAxisView.upperPanelTooltip": "Drag to change axis upper bound",
    "DG.PlotModel.mixup": "Mix Up the Plot",
    "DG.PlotModel.showCount": "Show Count",
    "DG.PlotModel.hideCount": "Hide Count",
    "DG.ScatterPlotModel.sumSquares": ",\nSum of squares = %@",
    "DG.ScatterPlotModel.rSquared": ",\nr^2 = %@",
    "DG.ScatterPlotModel.slopeIntercept": "%@ = %@ %@ %@ %@",
    "DG.ScatterPlotModel.infiniteSlope": "%@ = %@",
    "DG.ScatterPlotModel.slopeOnly": "slope = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "pro Jahr",
    "DG.ScatterPlotModel.daysLabel": "pro Tag",
    "DG.ScatterPlotModel.hoursLabel": "pro Stunde",
    "DG.ScatterPlotModel.minutesLabel": "pro Minute",
    "DG.ScatterPlotModel.secondsLabel": "pro Sekunde",
    "DG.LegendView.attributeTooltip": "Click to change legend attribute",
    "DG.NumberToggleView.showAll": "Show All –",
    "DG.NumberToggleView.hideAll": "Hide All –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Last",
    "DG.NumberToggleView.showAllTooltip": "Click to show all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.hideAllTooltip": "Click to hide all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.enableLastModeTooltip": "Click to show last parent case only",
    "DG.NumberToggleView.disableLastModeTooltip": "Click to exit last parent case mode",
    "DG.NumberToggleView.indexTooltip": "Click to toggle visibility",
    "DG.PlottedAverageAdornment.meanValueTitle": "mean=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "median=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SD, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "lower=%@\nQ1=%@\nmedian=%@\nQ3=%@\nupper=%@\nIQR=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Legend: %@",
    "DG.DataDisplayMenu.remove": "Remove Attribute",
    "DG.DataDisplayMenu.removeAttribute_x": "Remove X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Remove Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Remove Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Remove Legend: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Treat as Categorical",
    "DG.DataDisplayMenu.treatAsNumeric": "Treat as Numeric",
    "DG.DataDisplayMenu.hide": "Hide and Show",
    "DG.DataDisplayMenu.hideSelectedPlural": "Ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Nicht ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideSelectedSing": "Ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideUnselectedSing": "Nicht ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.enableNumberToggle": "Show Parent Visibility Toggles",
    "DG.DataDisplayMenu.disableNumberToggle": "Hide Parent Visibility Toggles",
    "DG.DataDisplayMenu.showAll": "Alle Fälle anzeigen",
    "DG.DataDisplayMenu.snapshot": "Make Snapshot",
    "DG.GraphView.replaceAttribute": "Replace %@ with %@",
    "DG.GraphView.addAttribute": "Add attribute %@",
    "DG.GraphView.addToEmptyPlace": "Create axis with %@",
    "DG.GraphView.addToEmptyX": "Create x-axis with %@",
    "DG.GraphView.dropInPlot": "Color points by values of %@",
    "DG.GraphView.zoomTip": "Double-click to zoom in.\nShift-double-click to zoom out",
    "DG.GraphView.rescale": "Rescale to data",
    "DG.AxisView.labelTooltip": "—Click to change %@ axis attribute",
    "DG.AxisView.vertical": "vertical",
    "DG.AxisView.horizontal": "horizontal",
    "DG.DataTip.connectingLine": "%@: %@\nwith %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formel",
    "DG.PlottedValue.namePrompt": "Plotted Value",
    "DG.PlottedValue.formulaPrompt": "value =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Plotted Function",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Type an expression e.g. x*x/30 - 50",
    "DG.MapView.showGrid": "Show Grid",
    "DG.MapView.hideGrid": "Hide Grid",
    "DG.MapView.showPoints": "Show Points",
    "DG.MapView.hidePoints": "Hide Points",
    "DG.MapView.marqueeHint": "Marquee tool—drag select points in map",
    "DG.MapView.gridControlHint": "Change size of grid rectangles",
    "DG.Inspector.values": "Measure",
    "DG.Inspector.styles": "Format",
    "DG.Inspector.pointSize": "Point size:",
    "DG.Inspector.transparency": "Transparency:",
    "DG.Inspector.color": "Color:",
    "DG.Inspector.legendColor": "Legend color:",
    "DG.Inspector.backgroundColor": "Background\ncolor:",
    "DG.Inspector.stroke": "Stroke:",
    "DG.Inspector.rescale.toolTip": "Rescale display to show all the data",
    "DG.Inspector.mixUp.toolTip": "Mixup all the points",
    "DG.Inspector.hideShow.toolTip": "Show all cases or hide selected/unselected cases",
    "DG.Inspector.delete.toolTip": "Delete selected or unselected cases",
    "DG.Inspector.sliderValues.toolTip": "Set slider animation direction, speed, …",
    "DG.Inspector.webViewEditURL.toolTip": "Edit the URL of the displayed web page",
    "DG.Inspector.selection.selectAll": "Alle Fälle auswählen",
    "DG.Inspector.selection.deleteSelectedCases": "Ausgewählte Fälle löschen",
    "DG.Inspector.selection.deleteUnselectedCases": "Nicht ausgewählte Fälle löschen",
    "DG.Inspector.deleteAll": "Alle Fälle löschen",
    "DG.Inspector.deleteDataSet": "Datensatz löschen und zerstören",
    "DG.Inspector.displayValues.toolTip": "Change what is shown along with the points",
    "DG.Inspector.displayStyles.toolTip": "Change the appearance of the display",
    "DG.Inspector.makeImage.toolTip": "Save the image as a PNG file",
    "DG.Inspector.displayShow": "Show …",
    "DG.Inspector.colorPicker.more": "more",
    "DG.Inspector.colorPicker.less": "less",
    "DG.Inspector.graphTransparency": "Transparent",
    "DG.Inspector.graphCount": "Count",
    "DG.Inspector.graphPercent": "Percent",
    "DG.Inspector.graphRow": "Row",
    "DG.Inspector.graphColumn": "Column",
    "DG.Inspector.graphCell": "Cell",
    "DG.Inspector.graphConnectingLine": "Connecting Lines",
    "DG.Inspector.graphMovableLine": "Movable Line",
    "DG.Inspector.graphInterceptLocked": "Intercept Locked",
    "DG.Inspector.graphPlottedFunction": "Plotted Function",
    "DG.Inspector.graphSquares": "Squares of Residuals",
    "DG.Inspector.graphLSRL": "Least Squares Line",
    "DG.Inspector.graphMovableValue": "Movable Value",
    "DG.Inspector.graphAdd": "Add",
    "DG.Inspector.graphRemove": "Remove",
    "DG.Inspector.graphPlottedMean": "Mean",
    "DG.Inspector.graphPlottedMedian": "Median",
    "DG.Inspector.graphPlottedStDev": "Standard Deviation",
    "DG.Inspector.graphPlottedIQR": "Interquartile Range",
    "DG.Inspector.graphPlottedBoxPlot": "Box Plot",
    "DG.Inspector.graphPlottedValue": "Plotted Value",
    "DG.Inspector.attributes.toolTip": "Make new attributes. Export case data.",
    "DG.Inspector.resize.toolTip": "Resize all columns to fit data",
    "DG.Inspector.newAttribute": "New Attribute in %@...",
    "DG.Inspector.randomizeAllAttributes": "Rerandomize All",
    "DG.Inspector.exportCaseData": "Export Case Data...",
    "DG.Inspector.mapGrid": "Grid",
    "DG.Inspector.mapPoints": "Points",
    "DG.Inspector.mapLines": "Connecting Lines",
    "DG.GameController.continuityError": "Sorry, after columns in the case table have been reordered, new data cannot be accepted.",
    "DG.GameView.loading": "Loading",
    "DG.GameView.loadError": "If you can see this text, loading the above URL may have failed. You can check the link in another browser tab or report the error to http://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "Are you sure?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Yes, close it",
    "DG.Component.closeComponent.cancelButtonTitle": "Cancel",
    "DG.GameController.confirmCloseDescription": "If you close this, you may not be able to add more data.",
    "DG.WebView.defaultTitle": "Web Page",
    "DG.mainPage.exceptionMessage": "An error has occurred that may affect how this program behaves. You may wish to reload this page after you save your work. (Error: %@)",
    "DG.fileMenu.provider.examples.displayName": "Example Documents",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Open a plugin component",
    "DG.Undo.graph.showMovablePoint": "Undo showing movable point",
    "DG.Redo.graph.showMovablePoint": "Redo showing movable point",
    "DG.Undo.graph.hideMovablePoint": "Undo hiding movable point",
    "DG.Redo.graph.hideMovablePoint": "Redo hiding movable point",
    "DG.Undo.graph.moveMovablePoint": "Undo moving movable point",
    "DG.Redo.graph.moveMovablePoint": "Redo moving movable point",
    "DG.DataDisplayMenu.copyAsImage": "Open in Draw Tool",
    "DG.DataDisplayMenu.exportImage": "Export Image...",
    "DG.DataDisplayMenu.imageOfTitle": "Image of %@",
    "DG.Inspector.graphMovablePoint": "Movable Point",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Open case table for this data set",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Create a new data set",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Delete and destroy this data set",
    "DG.Undo.graph.showAsBarChart": "Undo fusing dots into bars",
    "DG.Redo.graph.showAsBarChart": "Redo fusing dots into bars",
    "DG.Undo.graph.showAsDotChart": "Undo dispersing bars into dots",
    "DG.Redo.graph.showAsDotChart": "Redo dispersing bars into dots",
    "DG.CountAxisView.countLabel": "Count",
    "DG.CountAxisView.countLabelDescription": "Number of cases in the bar along this axis",
    "DG.CountAxisView.percentLabel": "Percent",
    "DG.CountAxisView.percentLabelDescription": "Percent of cases in the bar along this axis",
    "DG.BarChartModel.cellTipPlural": "%@ of %@ %@ (%@%) are %@",
    "DG.BarChartModel.cellTipSingular": "%@ of %@ %@ (%@%) is %@",
    "DG.Inspector.configuration": "Configuration",
    "DG.Inspector.displayConfiguration.toolTip": "Configure the display differently",
    "DG.Inspector.displayScale": "Scale …",
    "DG.Inspector.graphBarChart": "Fuse Dots into Bars",
    "DG.Locale.name.de": "Deutsch",
    "DG.Locale.name.en": "Englisch",
    "DG.Locale.name.es": "Spanisch",
    "DG.Locale.name.he": "Hebräisch",
    "DG.Locale.name.tr": "Türkisch",
    "DG.Locale.name.zh": "Chinesisch"
});
