SC.stringsFor("de", {
    "DG.fileMenu.menuItem.newDocument": "Neu",
    "DG.fileMenu.menuItem.openDocument": "Öffnen...",
    "DG.fileMenu.menuItem.closeDocument": "Schließen",
    "DG.fileMenu.menuItem.importFile": "Importieren ...",
    "DG.fileMenu.menuItem.revertTo": "Zurückkehren...",
    "DG.fileMenu.menuItem.revertToOpened": "Kürzlich geöffnete Fassung",
    "DG.fileMenu.menuItem.revertToShared": "Geteilte Ansicht",
    "DG.fileMenu.menuItem.saveDocument": "Speichern ...",
    "DG.fileMenu.menuItem.copyDocument": "Kopie erstellen",
    "DG.fileMenu.menuItem.share": "Teilen ...",
    "DG.fileMenu.menuItem.shareGetLink": "Link erhalten für geteilte Ansicht",
    "DG.fileMenu.menuItem.shareUpdate": "Geteilte Ansicht aktualisieren",
    "DG.fileMenu.menuItem.renameDocument": "Umbennen",
    "DG.main.userEntryView.title": "Was soll getan werden?",
    "DG.main.userEntryView.openDocument": "Dokument öffnen oder Beispiele ansehen",
    "DG.main.userEntryView.newDocument": "Neues Dokument erstellen",
    "DG.mainPage.mainPane.undoButton.title": "Rückgängig",
    "DG.mainPage.mainPane.undoButton.toolTip": "Die letzte Aktion rückgängig machen",
    "DG.mainPage.mainPane.redoButton.title": "Wiederholen",
    "DG.mainPage.mainPane.redoButton.toolTip": "Letzte Aktion wiederholen",
    "DG.mainPage.mainPane.versionString": "Version %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Leider wird CODAP aktuell nicht vom verwendeten Browser unterstützt. CODAP wird unterstützt von Firefox 46+, Chrome 50+, Windows Edge 14+ und Safari 10+. CODAP wird zur Zeit nicht von anderen Browsern unterstützt.",
    "DG.mainPage.titleBar.saved": "Dokument gespeichert!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Version %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Version %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Daten löschen...",
    "DG.AppController.resetData.toolTip": "Alle Daten des aktuellen Dokuments löschen",
    "DG.AppController.resetData.warnMessage": "Sollen wirklich alle Daten in diesem Dokument gelöscht werden?",
    "DG.AppController.resetData.warnDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.AppController.resetData.okButtonTitle": "Ja, Daten löschen",
    "DG.AppController.resetData.cancelButtonTitle": "Nein, Daten behalten",
    "DG.AppController.closeDocument.warnMessage": "Ohne Speichern schließen?",
    "DG.AppController.closeDocument.warnDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.AppController.closeDocument.okButtonTitle": "Schließen",
    "DG.AppController.closeDocument.cancelButtonTitle": "Abbrechen",
    "DG.AppController.beforeUnload.confirmationMessage": "Das Dokument enthält ungespeicherte Änderungen.",
    "DG.AppController.optionMenuItems.reportProblem": "Feedback senden...",
    "DG.AppController.optionMenuItems.viewWebPage": "Webseite anzeigen...",
    "DG.AppController.optionMenuItems.configureGuide": "Anleitung konfigurieren",
    "DG.AppController.optionMenuItems.about": "Über CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "Neuigkeiten",
    "DG.AppController.optionMenuItems.help": "Hilfe...",
    "DG.AppController.optionMenuItems.toWebSite": "CODAP Webseite",
    "DG.AppController.exportDocument.prompt": "Dateiname:",
    "DG.AppController.exportCaseData.prompt": "Daten exportieren",
    "DG.AppController.exportDocument.exportTitle": "Exportieren",
    "DG.AppController.exportDocument.exportTooltip": "Daten exportieren in eine Datei",
    "DG.AppController.exportDocument.cancelTitle": "Abbrechen",
    "DG.AppController.exportDocument.cancelTooltip": "Exportvorgang abbrechen",
    "DG.AppController.feedbackDialog.dialogTitle": "Rückmeldung geben",
    "DG.AppController.feedbackDialog.subHeaderText": "Deine Rückmeldung ist wichtig für uns!",
    "DG.AppController.feedbackDialog.messageText": "Bitte hilf uns, unser Produkt weiter zu verbessern. Fragen, Fehlerberichte und Feature-Wünsche sind willkommen. Danke!",
    "DG.AppController.feedbackDialog.subjectHint": "Wozu gibst Du eine Rückmeldung",
    "DG.AppController.feedbackDialog.feedbackHint": "Details",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Einreichen",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Abbrechen",
    "DG.AppController.showWebSiteTitle": "Über CODAP",
    "DG.AppController.showHelpTitle": "Hilfe zu CODAP",
    "DG.AppController.showAboutTitle": "Über CODAP",
    "DG.AppController.showReleaseNotesTitle": "CODAP Versionshinweise",
    "DG.AppController.dropFile.error": "Fehler: %@1",
    "DG.AppController.dropFile.unknownFileType": "Dieser Dateityp kann nicht importiert werden",
    "DG.AppController.validateDocument.missingRequiredProperty": "Notwendige Eigenschaft nicht gefunden: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Unerwartete Top-Level Eigenschaft: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Ungeklärte Id: %@1",
    "DG.AppController.validateDocument.parseError": "Analysefehler im Dokument: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Ungültiges JSON Dokument: %@1",
    "DG.AppController.openDocument.error.general": "Das Dokument konnte nicht geöffnet werden.",
    "DG.AppController.openDocument.error.invalid_format": "Dieser Dokumenttyp kann von CODAP nicht gelesen werden",
    "DG.AppController.createDataSet.initialAttribute": "Merkmal",
    "DG.AppController.createDataSet.name": "Neuer Datensatz",
    "DG.AppController.createDataSet.collectionName": "Fälle",
    "DG.AppController.caseTableMenu.newDataSet": "-- neu --",
    "DG.SingleTextDialog.okButton.title": "OK",
    "DG.SingleTextDialog.cancelButton.title": "Abbrechen",
    "DG.SingleTextDialog.cancelButton.toolTip": "Ohne Änderungen verlassen",
    "DG.DocumentController.calculatorTitle": "Taschenrechner",
    "DG.DocumentController.caseTableTitle": "Falltabelle",
    "DG.DocumentController.graphTitle": "Graph",
    "DG.DocumentController.sliderTitle": "Regler",
    "DG.DocumentController.textTitle": "Textfeld",
    "DG.DocumentController.mapTitle": "Karte",
    "DG.DocumentController.enterURLPrompt": "URL eingeben, um eine Website anzuzeigen",
    "DG.DocumentController.enterViewWebPageOKTip": "Die Website der URL anzeigen",
    "DG.Document.defaultDocumentName": "Unbenanntes Dokument",
    "DG.Document.documentName.toolTip": "Klicken, um den Name des Dokuments zu ändern",
    "DG.SliderView.thumbView.toolTip": "Ziehen, um den Wert des Reglers zu ändern",
    "DG.SliderView.startButton.toolTip": "Animation starten/anhalten",
    "DG.ToolButtonData.tableButton.title": "Tabellen",
    "DG.ToolButtonData.tableButton.toolTip": "Öffne eine Falltabelle für jeden Datensatz (Strg+alt+t)",
    "DG.ToolButtonData.graphButton.title": "Graph",
    "DG.ToolButtonData.graphButton.toolTip": "Erstelle einen Graph (Strg+alt+g)",
    "DG.ToolButtonData.sliderButton.title": "Regler",
    "DG.ToolButtonData.sliderButton.toolTip": "Erstelle einen Regler (Strg+alt+s)",
    "DG.ToolButtonData.calcButton.title": "Rechner",
    "DG.ToolButtonData.calcButton.toolTip": "Öffne/Schließe den Taschenrechner (Strg+alt+c)",
    "DG.ToolButtonData.textButton.title": "Text",
    "DG.ToolButtonData.textButton.toolTip": "Erstelle ein Textfeld (Strg+alt+shift+t)",
    "DG.ToolButtonData.mapButton.title": "Karte",
    "DG.ToolButtonData.mapButton.toolTip": "Eine Karte erstellen",
    "DG.ToolButtonData.optionMenu.title": "Einstellungen",
    "DG.ToolButtonData.optionMenu.toolTip": "Website anzeigen, Anleitung konfigurieren",
    "DG.ToolButtonData.tileListMenu.title": "Objekte",
    "DG.ToolButtonData.tileListMenu.toolTip": "Liste der Objekte anzeigen",
    "DG.ToolButtonData.guideMenu.title": "Anleitung",
    "DG.ToolButtonData.guideMenu.toolTip": "Anleitung dieser Aktivität anzeigen und verwenden",
    "DG.ToolButtonData.guideMenu.showGuide": "Anleitung zeigen",
    "DG.ToolButtonData.help.title": "Hilfe",
    "DG.ToolButtonData.help.toolTip": "Hilfe zu CODAP, das Projekt kennenlernen",
    "DG.Slider.multiples": "Begrenzen auf Vielfache von:",
    "DG.Slider.maxPerSecond": "Maximum Animation Frames/sec",
    "DG.Slider.direction": "Richtung der Animation",
    "DG.Slider.backAndForth": "Vor und Zurück",
    "DG.Slider.lowToHigh": "Niedrig zu Hoch",
    "DG.Slider.highToLow": "Hoch zu Niedrig",
    "DG.Slider.mode": "Wiederholung der Animation",
    "DG.Slider.nonStop": "pausenlos",
    "DG.Slider.onceOnly": "Nur einmal",
    "DG.Undo.exceptionOccurred": "Ein Fehler trat auf beim Rückgängig Machen.",
    "DG.Redo.exceptionOccurred": "Ein Fehler trat auf beim Wiederholen.",
    "DG.Undo.componentMove": "Rückgängig: Das Objekt verschieben",
    "DG.Redo.componentMove": "Wiederholen: Das Objekt verschieben",
    "DG.Undo.componentResize": "Rückgängig: Größenänderung des Objekts",
    "DG.Redo.componentResize": "Wiederholen: Größenänderung des Objekts",
    "DG.Undo.axisDilate": "Rückgängig: Die Achse verändern",
    "DG.Redo.axisDilate": "Wiederholen: Die Achse verändern",
    "DG.Undo.axisRescaleFromData": "Rückgängig: Die Achse verändern",
    "DG.Redo.axisRescaleFromData": "Wiederholen: Die Achse verändern",
    "DG.Undo.axisDrag": "Rückgängig: Verschieben der Achse",
    "DG.Redo.axisDrag": "Wiederholen: Verschieben der Achse",
    "DG.Undo.axisAttributeChange": "Rückgängig: Das Merkmal der Achse verändern",
    "DG.Redo.axisAttributeChange": "Wiederholen: Das Merkmal der Achse verändern",
    "DG.Undo.axisAttributeAdded": "Rückgängig: Der Achse ein Merkmal hinzufügen",
    "DG.Redo.axisAttributeAdded": "Wiederholen: Der Achse ein Merkmal hinzufügen",
    "DG.Undo.toggleComponent.add.calcView": "Rückgängig: Den Taschenrechner einblenden",
    "DG.Redo.toggleComponent.add.calcView": "Wiederholen: Den Taschenrechner einblenden",
    "DG.Undo.toggleComponent.delete.calcView": "Rückgängig: Den Taschenrechner verbergen",
    "DG.Redo.toggleComponent.delete.calcView": "Wiederholen: Den Taschenrechner verbergen",
    "DG.Undo.caseTable.open": "Rückgängig: Die Tabelle einblenden",
    "DG.Redo.caseTable.open": "Wiederholen: Die Tabelle einblenden",
    "DG.Undo.caseTable.editAttribute": "Rückgängig: Eigenschaften der Tabelle",
    "DG.Redo.caseTable.editAttribute": "Wiederholen: Eigenschaften der Tabelle",
    "DG.Undo.caseTable.createAttribute": "Rückgängig: Eigenschaften der Tabelle erstellen",
    "DG.Redo.caseTable.createAttribute": "Wiederholen: Eigenschaften der Tabelle erstellen",
    "DG.Undo.caseTable.editAttributeFormula": "Rückgängig: Formel der Tabelle bearbeiten",
    "DG.Redo.caseTable.editAttributeFormula": "Wiederholen: Formel der Tabelle bearbeiten",
    "DG.Undo.caseTable.editCellValue": "Rückgängig: Zellwert der Tabelle bearbeiten",
    "DG.Redo.caseTable.editCellValue": "Wiederholen: Zellwert der Tabelle bearbeiten",
    "DG.Undo.caseTable.sortCases": "Rückgängig: Fälle sortieren",
    "DG.Redo.caseTable.sortCases": "Wiederholen: Fälle sortieren",
    "DG.Undo.caseTable.deleteAttribute": "Rückgängig: Eigenschaft der Tabelle löschen",
    "DG.Redo.caseTable.deleteAttribute": "Wiederholen: Eigenschaft der Tabelle löschen",
    "DG.Undo.caseTable.createCollection": "Rückgängig: Neue Kollektion erstellen",
    "DG.Redo.caseTable.createCollection": "Wiederholen: Neue Kollektion erstellen",
    "DG.Undo.caseTable.collectionNameChange": "Rückgängig: Kollektion umbenennen",
    "DG.Redo.caseTable.collectionNameChange": "Wiederholen: Kollektion umbenennen",
    "DG.Undo.caseTable.createNewCase": "Rückgängig: Neuen Fall erstellen",
    "DG.Redo.caseTable.createNewCase": "Wiederholen: Neuen Fall erstellen",
    "DG.Undo.caseTable.insertCases": "Rückgängig: Fälle einfügen",
    "DG.Redo.caseTable.insertCases": "Wiederholen: Fälle einfügen",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Rückgängig: Ein-/Ausblenden",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Wiederholen: Ein-/Ausblenden",
    "DG.Undo.caseTable.expandCollapseOneCase": "Rückgängig: Gruppe vergrößern oder verkleinern",
    "DG.Redo.caseTable.expandCollapseOneCase": "Wiederholen: Gruppe vergrößern oder verkleinern",
    "DG.Undo.caseTable.resizeColumns": "Rückgängig: Automatische Größenanpassung aller Spalten",
    "DG.Redo.caseTable.resizeColumns": "Wiederholen: Automatische Größenanpassung aller Spalten",
    "DG.Undo.document.share": "Rückgängig: Dokument teilen",
    "DG.Redo.document.share": "Wiederholen: Dokument teilen",
    "DG.Undo.document.unshare": "Rückgängig: Dokument teilen beenden",
    "DG.Redo.document.unshare": "Wiederholen: Dokument teilen beenden",
    "DG.Undo.game.add": "Rückgängig: Ein Spiel hinzufügen",
    "DG.Redo.game.add": "Wiederholen: Ein Spiel hinzufügen",
    "DG.Undo.graph.showCount": "Rückgängig: Anzahl zeigen",
    "DG.Redo.graph.showCount": "Wiederholen: Anzahl zeigen",
    "DG.Undo.graph.hideCount": "Rückgängig: Anzahl verbergen",
    "DG.Redo.graph.hideCount": "Wiederholen: Anzahl verbergen",
    "DG.Undo.graph.showPercent": "Rückgängig: Prozent zeigen",
    "DG.Redo.graph.showPercent": "Wiederholen: Prozent zeigen",
    "DG.Undo.graph.hidePercent": "Rückgängig: Prozent verbergen",
    "DG.Redo.graph.hidePercent": "Wiederholen: Prozent verbergen",
    "DG.Undo.graph.showMovableLine": "Rückgängig: Bewegliche Linie zeigen",
    "DG.Redo.graph.showMovableLine": "Wiederholen: Bewegliche Linie zeigen",
    "DG.Undo.graph.hideMovableLine": "Rückgängig: Bewegliche Linie verbergen",
    "DG.Redo.graph.hideMovableLine": "Wiederholen: Bewegliche Linie verbergen",
    "DG.Undo.graph.lockIntercept": "Rückgängig: Abschnitt sperren",
    "DG.Redo.graph.lockIntercept": "Wiederholen: Abschnitt sperren",
    "DG.Undo.graph.unlockIntercept": "Rückgängig: Abschnitt freigeben",
    "DG.Redo.graph.unlockIntercept": "Wiederholen: Abschnitt freigeben",
    "DG.Undo.graph.showPlotFunction": "Rückgängig: Funktion anzeigen",
    "DG.Redo.graph.showPlotFunction": "Wiederholen: Funktion anzeigen",
    "DG.Undo.graph.hidePlotFunction": "Rückgängig: Funktion verbergen",
    "DG.Redo.graph.hidePlotFunction": "Wiederholen: Funktion verbergen",
    "DG.Undo.graph.changePlotFunction": "Rückgängig: Funktion ändern",
    "DG.Redo.graph.changePlotFunction": "Wiederholen: Funktion ändern",
    "DG.Undo.graph.showPlotValue": "Rückgängig: Werte anzeigen",
    "DG.Redo.graph.showPlotValue": "Wiederholen: Werte anzeigen",
    "DG.Undo.graph.hidePlotValue": "Rückgängig: Werte verbergen",
    "DG.Redo.graph.hidePlotValue": "Wiederholen: Werte verbergen",
    "DG.Undo.graph.changePlotValue": "Rückgängig: Werte ändern",
    "DG.Redo.graph.changePlotValue": "Wiederholen :Werte ändern",
    "DG.Undo.graph.showConnectingLine": "Rückgängig: Verbundene Linien zeigen",
    "DG.Redo.graph.showConnectingLine": "Wiederholen: Verbundene Linien zeigen",
    "DG.Undo.graph.hideConnectingLine": "Rückgängig: Verbundene Linien verbergen",
    "DG.Redo.graph.hideConnectingLine": "Wiederholen: Verbundene Linien verbergen",
    "DG.Undo.graph.showLSRL": "Rückgängig: Ausgleichsgerade",
    "DG.Redo.graph.showLSRL": "Wiederholen: Ausgleichsgerade",
    "DG.Undo.graph.hideLSRL": "Rückgängig: Ausgleichsgerade",
    "DG.Redo.graph.hideLSRL": "Wiederholen: Ausgleichsgerade",
    "DG.Undo.graph.showSquares": "Rückgängig: Quadrate anzeigen",
    "DG.Redo.graph.showSquares": "Wiederholen: Quadrate anzeigen",
    "DG.Undo.graph.hideSquares": "Rückgängig: Quadrate verbergen",
    "DG.Redo.graph.hideSquares": "Wiederholen: Quadrate verbergen",
    "DG.Undo.graph.showPlottedMean": "Rückgängig: Arithmetisches Mittel anzeigen",
    "DG.Redo.graph.showPlottedMean": "Wiederholen: Arithmetisches Mittel anzeigen",
    "DG.Undo.graph.hidePlottedMean": "Rückgängig: Arithmetisches Mittel verbergen",
    "DG.Redo.graph.hidePlottedMean": "Wiederholen: Arithmetisches Mittel verbergen",
    "DG.Undo.graph.showPlottedMedian": "Rückgängig: Median anzeigen",
    "DG.Redo.graph.showPlottedMedian": "Wiederholen: Median anzeigen",
    "DG.Undo.graph.hidePlottedMedian": "Rückgängig: Median verbergen",
    "DG.Redo.graph.hidePlottedMedian": "Wiederholen: Median verbergen",
    "DG.Undo.graph.showPlottedStDev": "Rückgängig: Standardabweichung anzeigen",
    "DG.Redo.graph.showPlottedStDev": "Wiederholen: Standardabweichung anzeigen",
    "DG.Undo.graph.hidePlottedStDev": "Rückgängig: Standardabweichung verbergen",
    "DG.Redo.graph.hidePlottedStDev": "Wiederholen: Standardabweichung verbergen",
    "DG.Undo.graph.showPlottedIQR": "Rückgängig: Interquartilsabstand anzeigen",
    "DG.Redo.graph.hidePlottedIQR": "Wiederholen: Interquartilsabstand anzeigen",
    "DG.Undo.graph.hidePlottedIQR": "Rückgängig: Interquartilsabstand verbergen",
    "DG.Redo.graph.showPlottedIQR": "Wiederholen: Interquartilsabstand verbergen",
    "DG.Undo.graph.addMovableValue": "Rückgängig: Beweglichen Wert hinzufügen",
    "DG.Redo.graph.addMovableValue": "Wiederholen: Beweglichen Wert hinzufügen",
    "DG.Undo.graph.removeMovableValue": "Rückgängig: Beweglichen Wert entfernen",
    "DG.Redo.graph.removeMovableValue": "Wiederholen: Beweglichen Wert entfernen",
    "DG.Undo.graph.moveMovableValue": "Rückgängig: Beweglichen Wert bewegen",
    "DG.Redo.graph.moveMovableValue": "Wiederholen: Beweglichen Wert bewegen",
    "DG.Undo.graph.changePointColor": "Rückgängig: Datenfarbe ändern",
    "DG.Redo.graph.changePointColor": "Wiederholen: Datenfarbe ändern",
    "DG.Undo.graph.changeStrokeColor": "Rückgängig: Umrandungsfarbe ändern",
    "DG.Redo.graph.changeStrokeColor": "Wiederholen: Umrandungsfarbe ändern",
    "DG.Undo.graph.changePointSize": "Rückgängig: Punktgröße ändern",
    "DG.Redo.graph.changePointSize": "Wiederholen: Punktgröße ändern",
    "DG.Undo.graph.changeAttributeColor": "Rückgängig: Merkmalsfarbe ändern",
    "DG.Redo.graph.changeAttributeColor": "Wiederholen: Merkmalsfarbe ändern",
    "DG.Undo.graph.changeBackgroundColor": "Rückgängig: Hintergrundfarbe des Graphen ändern",
    "DG.Redo.graph.changeBackgroundColor": "Wiederholen: Hintergrundfarbe des Graphen ändern",
    "DG.Undo.graph.toggleTransparent": "Rückgängig: Transparenz ändern",
    "DG.Redo.graph.toggleTransparent": "Wiederholen: Transparenz ändern",
    "DG.Undo.guide.show": "Rückgängig: Einführung anzeigen",
    "DG.Redo.guide.show": "Wiederholen: Einführung anzeigen",
    "DG.Undo.guide.navigate": "Rückgängig: Einführungsseite ändern",
    "DG.Redo.guide.navigate": "Wiederholen: Einführungsseite ändern",
    "DG.Undo.hideSelectedCases": "Rückgängig: Ausgewählte Fälle verbergen",
    "DG.Redo.hideSelectedCases": "Wiederholen: Ausgewählte Fälle verbergen",
    "DG.Undo.hideUnselectedCases": "Rückgängig: Nichtausgewählte Fälle verbergen",
    "DG.Redo.hideUnselectedCases": "Wiederholen: Nichtausgewählte Fälle verbergen",
    "DG.Undo.enableNumberToggle": "Rückgängig: übergeordnete Sichtbarkeit aktivieren",
    "DG.Redo.enableNumberToggle": "Wiederholen: übergeordnete Sichtbarkeit aktivieren",
    "DG.Undo.disableNumberToggle": "Rückgängig: übergeordnete Sichtbarkeit verbergen",
    "DG.Redo.disableNumberToggle": "Wiederholen: übergeordnete Sichtbarkeit verbergen",
    "DG.Undo.interactiveUndoableAction": "Rückgängig: Aktivität",
    "DG.Redo.interactiveUndoableAction": "Wiederholen: Aktivität",
    "DG.Undo.showAllCases": "Rückgängig: Alle Fälle anzeigen",
    "DG.Redo.showAllCases": "Wiederholen: Alle Fälle anzeigen",
    "DG.Undo.map.create": "Rückgängig: Karte hinzufügen",
    "DG.Redo.map.create": "Wiederholen: Karte hinzufügen",
    "DG.Undo.map.fitBounds": "Rückgängig: Kartengröße ändern",
    "DG.Redo.map.fitBounds": "Wiederholen: Kartengröße ändern",
    "DG.Undo.map.pan": "Rückgängig: Karte verschieben",
    "DG.Redo.map.pan": "Wiederholen: Karte verschieben",
    "DG.Undo.map.zoom": "Rückgängig: Zoomen",
    "DG.Redo.map.zoom": "Wiederholen: Zoomen",
    "DG.Undo.map.showGrid": "Rückgängig: Raster in Karte zeigen",
    "DG.Redo.map.showGrid": "Wiederholen: Raster in Karte zeigen",
    "DG.Undo.map.hideGrid": "Rückgängig: Raster in Karte verbergen",
    "DG.Redo.map.hideGrid": "Wiederholen: Raster in Karte verbergen",
    "DG.Undo.map.changeGridSize": "Rückgängig: Rastergröße der Karte ändern",
    "DG.Redo.map.changeGridSize": "Wiederholen: Rastergröße der Karte ändern",
    "DG.Undo.map.showPoints": "Rückgängig: Punkte auf Karte zeigen",
    "DG.Redo.map.showPoints": "Wiederholen: Punkte auf Karte zeigen",
    "DG.Undo.map.hidePoints": "Rückgängig: Punkte auf Karte verbergen",
    "DG.Redo.map.hidePoints": "Wiederholen: Punkte auf Karte verbergen",
    "DG.Undo.map.showLines": "Rückgängig: Linien auf Karte zeigen",
    "DG.Redo.map.showLines": "Wiederholen: Linien auf Karte zeigen",
    "DG.Undo.map.hideLines": "Rückgängig: Linien auf Karte verbergen",
    "DG.Redo.map.hideLines": "Wiederholen: Linien auf Karte verbergen",
    "DG.Undo.map.changeBaseMap": "Rückgängig: Hintergrund der Karte ändern",
    "DG.Redo.map.changeBaseMap": "Wiederholen: Hintergrund der Karte ändern",
    "DG.Undo.textComponent.create": "Rückgängig: Textobjekt hinzufügen",
    "DG.Redo.textComponent.create": "Wiederholen: Textobjekt hinzufügen",
    "DG.Undo.textComponent.edit": "Rückgängig: Text editieren",
    "DG.Redo.textComponent.edit": "Wiederholen: Text editieren",
    "DG.Undo.sliderComponent.create": "Rückgängig: Regler hinzufügen",
    "DG.Redo.sliderComponent.create": "Wiederholen: Regler hinzufügen",
    "DG.Undo.slider.change": "Rückgängig: Wert des Reglers ändern",
    "DG.Redo.slider.change": "Wiederholen: Wert des Reglers ändern",
    "DG.Undo.slider.changeMultiples": "Rückgängig: Einschränkung",
    "DG.Redo.slider.changeMultiples": "Wiederholen: Einschränkung",
    "DG.Undo.slider.changeSpeed": "Rückgängig: Reglergeschwindigkeit",
    "DG.Redo.slider.changeSpeed": "Wiederholen: Reglergeschwindigkeit",
    "DG.Undo.slider.changeDirection": "Rückgängig: Regleranimation",
    "DG.Redo.slider.changeDirection": "Wiederholen: Regleranimation",
    "DG.Undo.slider.changeRepetition": "Rückgängig: Regler",
    "DG.Redo.slider.changeRepetition": "Wiederholen: Regler",
    "DG.Undo.graphComponent.create": "Rückgängig: Graph hinzufügen",
    "DG.Redo.graphComponent.create": "Wiederholen: Graph hinzufügen",
    "DG.Undo.dataContext.create": "Rückgängig: Datensatz erstellen",
    "DG.Redo.dataContext.create": "Wiederholen: Datensatz erstellen",
    "DG.Undo.data.deleteCases": "Rückgängig: Fälle löschen",
    "DG.Redo.data.deleteCases": "Wiederholen: Fälle löschen",
    "DG.Undo.component.close": "Rückgängig: Schließen",
    "DG.Redo.component.close": "Wiederholen: Schließen",
    "DG.Undo.component.minimize": "Rückgängig: Verkleinern",
    "DG.Redo.component.minimize": "Wiederholen: Verkleinern",
    "DG.Undo.dataContext.moveAttribute": "Rückgängig: Merkmal der Tabelle verschieben",
    "DG.Redo.dataContext.moveAttribute": "Wiederholen: Merkmal der Tabelle verschieben",
    "DG.DataContext.singleCaseName": "Fall",
    "DG.DataContext.pluralCaseName": "Fälle",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "Eine Kollektion",
    "DG.DataContext.collapsedRowString": "%@1 of %@2",
    "DG.DataContext.noData": "Keine Daten",
    "DG.DataContext.baseName": "Datensatz_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "Die Formel des Merkmals \"%@\" kann nicht geändert werden.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Ein neues Merkmal erstellen, um eine Formel zu verwenden",
    "DG.Formula.FuncCategoryArithmetic": "Arithmetik Funktionen",
    "DG.Formula.FuncCategoryConversion": "Andere Funktionen",
    "DG.Formula.FuncCategoryDateTime": "Datum/Zeit Funktionen",
    "DG.Formula.FuncCategoryLookup": "Such-Funktionen",
    "DG.Formula.FuncCategoryOther": "Andere Funktionen",
    "DG.Formula.FuncCategoryRandom": "Andere Funktionen",
    "DG.Formula.FuncCategoryStatistical": "Statistische Funktionen",
    "DG.Formula.FuncCategoryString": "Text Funktionen",
    "DG.Formula.FuncCategoryTrigonometric": "Trigonometrische Funktionen",
    "DG.Formula.DateLongMonthJanuary": "Januar",
    "DG.Formula.DateLongMonthFebruary": "Februar",
    "DG.Formula.DateLongMonthMarch": "März",
    "DG.Formula.DateLongMonthApril": "April",
    "DG.Formula.DateLongMonthMay": "Mai",
    "DG.Formula.DateLongMonthJune": "Juni",
    "DG.Formula.DateLongMonthJuly": "Juli",
    "DG.Formula.DateLongMonthAugust": "August",
    "DG.Formula.DateLongMonthSeptember": "September",
    "DG.Formula.DateLongMonthOctober": "Oktober",
    "DG.Formula.DateLongMonthNovember": "November",
    "DG.Formula.DateLongMonthDecember": "Dezember",
    "DG.Formula.DateShortMonthJanuary": "Jan",
    "DG.Formula.DateShortMonthFebruary": "Feb",
    "DG.Formula.DateShortMonthMarch": "Mär",
    "DG.Formula.DateShortMonthApril": "Apr",
    "DG.Formula.DateShortMonthMay": "Mai",
    "DG.Formula.DateShortMonthJune": "Jun",
    "DG.Formula.DateShortMonthJuly": "Jul",
    "DG.Formula.DateShortMonthAugust": "Aug",
    "DG.Formula.DateShortMonthSeptember": "Sep",
    "DG.Formula.DateShortMonthOctober": "Okt",
    "DG.Formula.DateShortMonthNovember": "Nov",
    "DG.Formula.DateShortMonthDecember": "Dez",
    "DG.Formula.DateLongDaySunday": "Sonntag",
    "DG.Formula.DateLongDayMonday": "Montag",
    "DG.Formula.DateLongDayTuesday": "Dienstag",
    "DG.Formula.DateLongDayWednesday": "Mittwoch",
    "DG.Formula.DateLongDayThursday": "Donnerstag",
    "DG.Formula.DateLongDayFriday": "Freitag",
    "DG.Formula.DateLongDaySaturday": "Samstag",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mär|apr|mai|jun|jul|aug|sep|okt|nov|dez)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "4\n(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Syntaxfehler: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Unvollständiger Ausdruck",
    "DG.Formula.SyntaxErrorInvalidOperator": "Ungültiger Operator '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "ungültige Typen '%@'",
    "DG.Formula.TypeError.description": "ungültige Typen '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' wurde nicht erkannt",
    "DG.Formula.VarReferenceError.description": "Die Variable '%@' wurde nicht erkannt.",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "ungültiger Bezug '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' ist ein untergeordnetes Merkmal und kann nur aggregiert werden",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' wurde nicht erkannt",
    "DG.Formula.FuncReferenceError.description": "Die Funktion '%@()' wurde nicht erkannt",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' erwartet 1 Argument",
    "DG.Formula.FuncArgsErrorSingle.description": "Die Funktion '%@()' erwartet 1 Argument",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' erwartet %@ Argumente",
    "DG.Formula.FuncArgsErrorPlural.description": "Die Funktion '%@()' erwartet %@ Argumente",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' erwartet %@-%@ Argumente",
    "DG.Formula.FuncArgsErrorRange.description": "Die Funktion '%@()' erwartet %@-%@ Argumente",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "Ausstehende Anfrage...",
    "DG.Formula.PendingRequest.description": "Ausstehende Anfrage...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "Anfrage fehlgeschlagen  (%@)",
    "DG.Formula.FailedRequest.description": "Anfrage fehlgeschlagen (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "offene Grenzen...",
    "DG.Formula.PendingBoundaries.description": "offene Grenzen...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "Grenzen gescheitert (%@)",
    "DG.Formula.FailedBoundaries.description": "Grenzen gescheitert (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': nicht erkannter Datensatz",
    "DG.Formula.LookupDataSetError.description": "Der Datensatz '%@' wurde nicht erkannt",
    "DG.Formula.LookupAttrError.message": "'%@' wurde im Datensatz '%@' nicht gefunden",
    "DG.Formula.LookupAttrError.description": "Merkmal '%@' im Datensatz '%@' nicht gefunden",
    "DG.TableController.headerMenuItems.editAttribute": "Eigenschaften des Merkmals bearbeiten...",
    "DG.TableController.headerMenuItems.editFormula": "Formel bearbeiten...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Rerandomisieren",
    "DG.TableController.headerMenuItems.sortAscending": "Aufsteigend sortieren (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Absteigend sortieren (Z→A, 9→0)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Merkmal löschen",
    "DG.TableController.newAttrDlg.defaultAttrName": "neues_Merkm",
    "DG.TableController.newAttrDlg.attrNameHint": "Einen Namen eingeben für das neue Merkmal",
    "DG.TableController.newAttrDlg.formulaHint": "Eine Formel benutzen, um Werte dieses Merkmals zu berechnen, falls gewünscht",
    "DG.TableController.newAttrDlg.applyTooltip": "Das neue Merkmal definieren mit einem Namen und einer (optionalen) Formel",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Bitte einen Namen eingeben für das neue Merkmal",
    "DG.TableController.newAttrDialog.AttributesCategory": "Merkmale",
    "DG.TableController.newAttrDialog.SpecialCategory": "Spezial",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Allgemeines",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Konstanten",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Funktionen",
    "DG.TableController.renameAttributeInvalidMsg": "Merkmalsnamen dürfen nicht leer sein",
    "DG.TableController.renameAttributeInvalidDesc": "Bitte einen gültigen Merkmalsnamen eingeben",
    "DG.TableController.renameAttributeDuplicateMsg": "Dieser Merkmalsname ist bereits vergeben",
    "DG.TableController.renameAttributeDuplicateDesc": "Bitte einen eindeutigen Merkmalsnamen eingeben",
    "DG.TableController.deleteAttribute.confirmMessage": "Das Merkmal '%@' löschen?",
    "DG.TableController.deleteAttribute.confirmDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Merkmal löschen",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Abbrechen",
    "DG.TableController.deleteDataSet.confirmMessage": "Diesen Datensatz unwiederbringlich löschen: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Datensatz löschen",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Abbrechen",
    "DG.TableController.attrEditor.unitHint": "Einheit der Messung, falls angebbar",
    "DG.TableController.attrEditor.descriptionHint": "Das Merkmal beschreiben",
    "DG.TableController.setScoreDlg.applyTooltip": "Eine Formel für das Merkmal '%@' eingeben",
    "DG.TableController.setScoreDlg.formulaHint": "Eine Formel eingeben, um Werte dieses Merkmals zu berechnen",
    "DG.TableController.newAttributeTooltip": "Der Tabelle ein neues Merkmal hinzufügen",
    "DG.TableController.attributeEditor.title": "Eigenschaften des Merkmals",
    "DG.CaseTableDropTarget.dropMessage": "Merkmal fallen lassen, um eine neue Kollektion zu erzeugen",
    "DG.CaseTable.defaultAttrName": "neuesMerkm",
    "DG.CaseTable.indexColumnName": "Index",
    "DG.CaseTable.indexColumnTooltip": "Zeilennummer (FallIndex) der Kollektion",
    "DG.CaseTable.indexMenu.insertCase": "Fall hinzufügen",
    "DG.CaseTable.indexMenu.insertCases": "Fälle hinzufügen",
    "DG.CaseTable.indexMenu.deleteCase": "Fall löschen",
    "DG.CaseTable.indexMenu.deleteCases": "Fälle löschen",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "kategorial",
    "DG.CaseTable.attribute.type.categorical": "kategorial",
    "DG.CaseTable.attribute.type.numeric": "numerisch",
    "DG.CaseTable.attribute.type.date": "Datum",
    "DG.CaseTable.attribute.type.qualitative": "qualitativ",
    "DG.CaseTable.attribute.type.boundary": "Grenzen",
    "DG.CaseTable.attributeEditor.name": "Name",
    "DG.CaseTable.attributeEditor.description": "Beschreibung",
    "DG.CaseTable.attributeEditor.type": "Typ",
    "DG.CaseTable.attributeEditor.unit": "Einheit",
    "DG.CaseTable.attributeEditor.precision": "Genauigkeit",
    "DG.CaseTable.attributeEditor.editable": "editierbar",
    "DG.CaseTable.insertCasesDialog.title": "Fälle hinzufügen",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# Fälle, die eingefügt werden sollen",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "Position:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "vor",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "nach",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Fälle einfügen",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Festgelegte Anzahl Fälle einfügen",
    "DG.CaseTableController.allTables": "Alle Tabellen",
    "DG.AttrFormView.attrNamePrompt": "Name des Merkmals:",
    "DG.AttrFormView.formulaPrompt": "Formel:",
    "DG.AttrFormView.operandMenuTitle": "--- Wert einfügen ---",
    "DG.AttrFormView.functionMenuTitle": "--- Funktion einfügen ---",
    "DG.AttrFormView.applyBtnTitle": "Bestätigen",
    "DG.AttrFormView.cancelBtnTitle": "Abbrechen",
    "DG.AttrFormView.cancelBtnTooltip": "Den Dialog ohne Änderungen verlassen",
    "DG.GuideConfigView.titlePrompt": "Einführungstitel",
    "DG.GuideConfigView.titleHint": "Name der Aktivität",
    "DG.GuideConfigView.itemTitleHint": "Abschnittsname",
    "DG.GuideConfigView.itemURLHint": "URL des Abschnitts",
    "DG.GuideConfigView.okBtnTitle": "OK",
    "DG.GuideConfigView.okBtnToolTip": "Einführungspunkte akzeptieren",
    "DG.GuideConfigView.cancelBtnTitle": "Abbrechen",
    "DG.GuideConfigView.cancelBtnTooltip": "Den Dialog verlassen ohne Änderung",
    "DG.GuideConfigView.httpWarning": "Die Adresse muss entweder mit http:// oder mit https:// starten",
    "DG.DataDisplayModel.rescaleToData": "Daten skalieren",
    "DG.DataDisplayModel.ShowConnectingLine": "Verbindungslinien zeigen",
    "DG.DataDisplayModel.HideConnectingLine": "Verbindungslinien verbergen",
    "DG.AxisView.emptyGraphCue": "Hier klicken oder ein Merkmal hierher ziehen",
    "DG.CellLinearAxisView.midPanelTooltip": "Ziehen, um die Achsenskala anzupassen",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Ziehen, um die untere Grenze der Achse zu ändern",
    "DG.CellLinearAxisView.upperPanelTooltip": "Ziehen, um die obere Grenze der Achse zu ändern",
    "DG.PlotModel.mixup": "Graph mischen",
    "DG.PlotModel.showCount": "Anzahl zeigen",
    "DG.PlotModel.hideCount": "Anzahl verbergen",
    "DG.ScatterPlotModel.sumSquares": ",\nSumme der Quadrate = %@",
    "DG.ScatterPlotModel.slopeOnly": "Steigung = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "pro Jahr",
    "DG.ScatterPlotModel.daysLabel": "pro Tag",
    "DG.ScatterPlotModel.hoursLabel": "pro Stunde",
    "DG.ScatterPlotModel.minutesLabel": "pro Minute",
    "DG.ScatterPlotModel.secondsLabel": "pro Sekunde",
    "DG.LegendView.attributeTooltip": "Klicken, um das Legendenmerkmal zuändern",
    "DG.NumberToggleView.showAll": "Alle anzeigen –",
    "DG.NumberToggleView.hideAll": "Alle verbergen –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Letzte",
    "DG.NumberToggleView.showAllTooltip": "Klicken, um alle Fälle anzuzeigen\nÜbergeordnete Etiketten anklicken, um Sichtbarkeit zu ändern",
    "DG.NumberToggleView.hideAllTooltip": "Klicken, um alle Fälle zu verbergen\nÜbergeordnete Etikellten anklicken, um Sichtbarkeit zu ändern",
    "DG.NumberToggleView.enableLastModeTooltip": "Übergeordneten Fall anzeigen",
    "DG.NumberToggleView.disableLastModeTooltip": "Übergeordneten Fall verlassen",
    "DG.NumberToggleView.indexTooltip": "Sichtbarkeit umschalten",
    "DG.PlottedAverageAdornment.meanValueTitle": "aMittel=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "Median=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SD, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "untere=%@\nQ1=%@\nMedian=%@\nQ3=%@\nobere=%@\nIQR=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Legende: %@",
    "DG.DataDisplayMenu.remove": "Merkmal entfernen",
    "DG.DataDisplayMenu.removeAttribute_x": "Entferne X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Entferne Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Entferne Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Entferne Legende: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Als kategorial behandeln",
    "DG.DataDisplayMenu.treatAsNumeric": "Als numerisch behandeln",
    "DG.DataDisplayMenu.hide": "Verbergen und Zeigen",
    "DG.DataDisplayMenu.hideSelectedPlural": "Ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Nicht ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideSelectedSing": "Ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideUnselectedSing": "Nicht ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.enableNumberToggle": "Übergeordnete Sichtbarkeit anzeigen",
    "DG.DataDisplayMenu.disableNumberToggle": "Übergeordnete Sichtbarkeit verbergen",
    "DG.DataDisplayMenu.showAll": "Alle Fälle anzeigen",
    "DG.DataDisplayMenu.snapshot": "Screenshot",
    "DG.GraphView.replaceAttribute": "Ersetze %@ durch %@",
    "DG.GraphView.addAttribute": "Merkmal %@ hinzufügen",
    "DG.GraphView.addToEmptyPlace": "Achse erstellen aus %@",
    "DG.GraphView.addToEmptyX": "X-Achse erstellen aus %@",
    "DG.GraphView.dropInPlot": "Punkte einfärben nach Werten von %@",
    "DG.GraphView.zoomTip": "Doppelklick zum Vergrößern\nUmschalt+Doppelklick zu Verkleinern",
    "DG.GraphView.rescale": "An Daten skalieren",
    "DG.AxisView.labelTooltip": "—Klicken, um %@ Achsenmerkmal zu ändern",
    "DG.AxisView.vertical": "senkrecht",
    "DG.AxisView.horizontal": "waagrecht",
    "DG.DataTip.connectingLine": "%@: %@\nmit %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formel",
    "DG.PlottedValue.namePrompt": "Wert",
    "DG.PlottedValue.formulaPrompt": "Wert =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Funktion",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Einen Ausdruck angeben, z. B. x*x/30 - 50",
    "DG.MapView.showGrid": "Gitter zeigen",
    "DG.MapView.hideGrid": "Gitter verbergen",
    "DG.MapView.showPoints": "Punkte zeigen",
    "DG.MapView.hidePoints": "Punkte verbergen",
    "DG.MapView.marqueeHint": "Markierungswerkzeug",
    "DG.MapView.gridControlHint": "Gittergröße ändern",
    "DG.Inspector.values": "Messung",
    "DG.Inspector.styles": "Format",
    "DG.Inspector.pointSize": "Punktgröße:",
    "DG.Inspector.transparency": "Transparenz:",
    "DG.Inspector.color": "Farbe:",
    "DG.Inspector.legendColor": "Legendenfarbe:",
    "DG.Inspector.backgroundColor": "Hintergrundfarbe:",
    "DG.Inspector.stroke": "Umrandung:",
    "DG.Inspector.rescale.toolTip": "Anzeige anpassen um alle Daten zu zeigen",
    "DG.Inspector.mixUp.toolTip": "Alle Punkte mischen",
    "DG.Inspector.hideShow.toolTip": "Alle Fälle zeigen oder ausgewählte/nicht ausgewählte Fälle verbergen",
    "DG.Inspector.delete.toolTip": "Ausgewählte oder nicht ausgewählte Fälle löschen",
    "DG.Inspector.sliderValues.toolTip": "Animation des Reglers",
    "DG.Inspector.webViewEditURL.toolTip": "URL editieren",
    "DG.Inspector.selection.selectAll": "Alle Fälle auswählen",
    "DG.Inspector.selection.deleteSelectedCases": "Ausgewählte Fälle löschen",
    "DG.Inspector.selection.deleteUnselectedCases": "Nicht ausgewählte Fälle löschen",
    "DG.Inspector.deleteAll": "Alle Fälle löschen",
    "DG.Inspector.deleteDataSet": "Datensatz löschen und zerstören",
    "DG.Inspector.displayValues.toolTip": "Ändern, was mit den Punkten angezeigt wird",
    "DG.Inspector.displayStyles.toolTip": "Erscheinungsbild der Anzeige ändern",
    "DG.Inspector.makeImage.toolTip": "Bild als png Datei speichern",
    "DG.Inspector.displayShow": "Zeigen...",
    "DG.Inspector.colorPicker.more": "mehr",
    "DG.Inspector.colorPicker.less": "weniger",
    "DG.Inspector.graphTransparency": "transparent",
    "DG.Inspector.graphCount": "Anzahl",
    "DG.Inspector.graphPercent": "Prozent",
    "DG.Inspector.graphRow": "Zeile",
    "DG.Inspector.graphColumn": "Spalte",
    "DG.Inspector.graphCell": "Zelle",
    "DG.Inspector.graphConnectingLine": "Linien verbinden",
    "DG.Inspector.graphMovableLine": "Bewegliche Linie",
    "DG.Inspector.graphInterceptLocked": "Abschnitt gesperrt",
    "DG.Inspector.graphPlottedFunction": "Funktion",
    "DG.Inspector.graphSquares": "Residuenquadrate",
    "DG.Inspector.graphLSRL": "Ausgleichsgerade",
    "DG.Inspector.graphMovableValue": "Beweglicher Wert",
    "DG.Inspector.graphAdd": "Hinzufügen",
    "DG.Inspector.graphRemove": "Entfernen",
    "DG.Inspector.graphPlottedMean": "arithmetisches Mittel",
    "DG.Inspector.graphPlottedMedian": "Median",
    "DG.Inspector.graphPlottedStDev": "Standardabweichung",
    "DG.Inspector.graphPlottedIQR": "Interquartilsabstand",
    "DG.Inspector.graphPlottedBoxPlot": "Boxplot",
    "DG.Inspector.graphPlottedValue": "Wert",
    "DG.Inspector.attributes.toolTip": "Neues Merkmal erstellen. Falldaten exportieren",
    "DG.Inspector.resize.toolTip": "Spaltengröße an Daten anpassen",
    "DG.Inspector.newAttribute": "Neues Merkmal als %@...",
    "DG.Inspector.randomizeAllAttributes": "Alle rerandomisieren",
    "DG.Inspector.exportCaseData": "Falldaten exportieren...",
    "DG.Inspector.mapGrid": "Gitter",
    "DG.Inspector.mapPoints": "Punkte",
    "DG.Inspector.mapLines": "Linien verbinden",
    "DG.GameController.continuityError": "Entschuldigung, nachdem die Spalten der Tabelle neu angeordnet wurden können keine neuen Daten akzeptiert werden.",
    "DG.GameView.loading": "Lädt",
    "DG.GameView.loadError": "Wenn dieser Text zu sehen ist, dann ist das Laden der URL möglicherweise fehlgeschlagen. Der Link kann in einem anderen Browser überprüft werden. Oder der Fehler kann hier berichtet werden: http://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "Sicher?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Ja, schließen",
    "DG.Component.closeComponent.cancelButtonTitle": "Abbrechen",
    "DG.GameController.confirmCloseDescription": "Wenn dies geschlossen wird, können möglicherweise keine weiteren Daten hinzugefügt werden.",
    "DG.WebView.defaultTitle": "Website",
    "DG.mainPage.exceptionMessage": "Ein Fehler ist aufgetreten. Seite neu laden (Fehler: %@)",
    "DG.fileMenu.provider.examples.displayName": "Beispieldokumente",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Plugin öffnen",
    "DG.Undo.graph.showMovablePoint": "Rückgängig: Beweglichen Punkt zeigen",
    "DG.Redo.graph.showMovablePoint": "Wiederholen: Beweglichen Punkt zeigen",
    "DG.Undo.graph.hideMovablePoint": "Rückgängig: Beweglichen Punkt verbergen",
    "DG.Redo.graph.hideMovablePoint": "Wiederholen: Beweglichen Punkt verbergen",
    "DG.Undo.graph.moveMovablePoint": "Rückgängig: Beweglichen Punkt bewegen",
    "DG.Redo.graph.moveMovablePoint": "Wiederholen: Beweglichen Punkt bewegen",
    "DG.DataDisplayMenu.copyAsImage": "Im Zeichenwerkzeug öffnen",
    "DG.DataDisplayMenu.exportImage": "Bild exportieren...",
    "DG.DataDisplayMenu.imageOfTitle": "Bild %@",
    "DG.Inspector.graphMovablePoint": "Beweglicher Punkt",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Falltabelle zu diesem Datensatz öffnen",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Neuen Datensatz erstellen",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Diesen Datensatz löschen und zerstören",
    "DG.Undo.graph.showAsBarChart": "Rückgängig: Punkte verschmelzen",
    "DG.Redo.graph.showAsBarChart": "Wiederholen: Punkte verschmelzen",
    "DG.Undo.graph.showAsDotChart": "Rückgängig: Säulen in Punkte verwandeln",
    "DG.Redo.graph.showAsDotChart": "Wiederholen: Säulen in Punkte verwandeln",
    "DG.CountAxisView.countLabel": "Anzahl",
    "DG.CountAxisView.countLabelDescription": "Anzahl Fälle der Säule dieser Achse",
    "DG.CountAxisView.percentLabel": "Prozent",
    "DG.CountAxisView.percentLabelDescription": "Prozent der Fälle in der Säule dieser Achse",
    "DG.BarChartModel.cellTipPlural": "%@ von %@ %@ (%@%) sind %@",
    "DG.BarChartModel.cellTipSingular": "%@ von %@ %@ (%@%) ist %@",
    "DG.Inspector.configuration": "Einstellung",
    "DG.Inspector.displayConfiguration.toolTip": "Einstellung zur Anzeige",
    "DG.Inspector.displayScale": "Skalieren...",
    "DG.Inspector.graphBarChart": "Punkte rechteckig verschmelzen",
    "DG.Locale.name.de": "Deutsch",
    "DG.Locale.name.en": "Englisch",
    "DG.Locale.name.es": "Spanisch",
    "DG.Locale.name.he": "Hebräisch",
    "DG.Locale.name.tr": "Türkisch",
    "DG.Locale.name.zh": "Chinesisch",
    "DG.Undo.graph.swapCategories": "Rückgängig: Kategorien anordnen",
    "DG.Redo.graph.swapCategories": "Wiederholen: Kategorien anordnen",
    "DG.TableController.collectionTitleText": "%@1 (%@2 Fälle)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 Fälle, %@3 ablegen)",
    "DG.Inspector.setaside.setAsideSelectedCases": "Ausgewählte Fälle ablegen",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Nicht ausgewählte Fälle ablegen",
    "DG.Inspector.setaside.restoreSetAsideCases": "Abglegte Fälle %@ wiederherstellen",
    "DG.DocumentController.caseCardTitle": "Datenkarte",
    "DG.DocumentController.toggleToCaseCard": "Zur Datenkartenansicht wechseln",
    "DG.DocumentController.toggleToCaseTable": "Zur Tabellenansicht wechseln",
    "DG.CaseCard.indexString": "1 von %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ von %@ %@ ausgewählt",
    "DG.CaseCard.summaryValues": "%@ Werte",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Auswählen und nächsten Fall anzeigen",
    "DG.CaseCard.navPrevCase": "Auswählen und vorherigen Fall anzeigen",
    "DG.CaseCard.navFirstCase": "Auswählen und ersten Fall anzeigen",
    "DG.CaseCard.navLastCase": "Auswählen und letzten Fall anzeigen",
    "DG.Undo.component.toggleTableToCard": "Rückgängig: Datenkartenansicht",
    "DG.Redo.component.toggleTableToCard": "Wiederholen: Datenkartenansicht",
    "DG.Undo.component.toggleCardToTable": "Rückgängig: Tabellenansicht",
    "DG.Redo.component.toggleCardToTable": "Wiederholen: Tabellenansicht",
    "DG.Undo.graph.addBackgroundImage": "Rückgängig: Hintergrundbild hinzufügen",
    "DG.Redo.graph.addBackgroundImage": "Wiederholen: Hintergrundbild hinzufügen",
    "DG.Undo.graph.removeBackgroundImage": "Rückgängig: Hintergrundbild entfernen",
    "DG.Redo.graph.removeBackgroundImage": "Wiederholen: Hintergrundbild entfernen",
    "DG.Undo.graph.lockBackgroundImage": "Rückgängig: Hintergrundbild an Achse",
    "DG.Redo.graph.lockBackgroundImage": "Wiederholen: Hintergrundbild an Achse",
    "DG.Undo.graph.unlockBackgroundImage": "Rückgängig: Hintergrundbild von Achse entfernen",
    "DG.Redo.graph.unlockBackgroundImage": "Wiederholen: Hintergrundbild von Achse entfernen",
    "DG.Undo.enableMeasuresForSelection": "Rückgängig: Messung für Auswahl anzeigen",
    "DG.Redo.enableMeasuresForSelection": "Wiederholen: Messung für Auswahl anzeigen",
    "DG.Undo.disableMeasuresForSelection": "Rückgängig: Messung für Auswahl verbergen",
    "DG.Redo.disableMeasuresForSelection": "Wiederholen: Messung für Auswahl verbergen",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Messung für Auswahl anzeigen",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Messung für Auswahl verbergen",
    "DG.DataDisplayMenu.addBackgroundImage": "Hintergrundbild hinzufügen",
    "DG.DataDisplayMenu.lockImageToAxes": "Hintergrundbild an Achsen ausrichten",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Hintergrundbild von Achse entfernen",
    "DG.DataDisplayMenu.removeBackgroundImage": "Hintergrundbild entfernen",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Formel löschen (Werte behalten)",
    "DG.TableController.headerMenuItems.recoverFormula": "Formel wiederherstellen",
    "DG.Inspector.displayLayers.toolTip": "Aussehen der Kartenebenen ändern",
    "DG.Inspector.layers": "Ebenen",
    "DG.Undo.graph.repositionEquation": "Rückgängig: Gleichung verschieben",
    "DG.Redo.graph.repositionEquation": "Wiederholen: Gleichung verschieben",
    "DG.TableController.attrEditor.precisionNumericHint": "Anzahl der Nachkommastellen",
    "DG.TableController.attrEditor.precisionDateHint": "Legt fest, wieviele der Datenpunkte angezeigt werden",
    "DG.TableController.attrEditor.typeHint": "Merkmalstyp festlegen",
    "DG.TableController.attrEditor.nameHint": "Der Merkmalsname erscheint in der Tabelle, case card und auf den Graph-Achsen",
    "DG.TableController.attrEditor.editableHint": "Wenn das Merkmal nicht editierbar ist, können seine Werte und/oder Formeln nicht geändert werden",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "Jahr Monat Tag Stunde Minute Sekunde Millisekunde",
    "DG.AttributeFormat.DatePrecision.year": "YYYY",
    "DG.AttributeFormat.DatePrecision.month": "MMM YYYY",
    "DG.AttributeFormat.DatePrecision.day": "MMM D, YYYY",
    "DG.AttributeFormat.DatePrecision.hour": "MMM D, YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "MMM D, YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "MMM D, YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@ in %@",
    "DG.CaseCard.attrHintDescription": "%@: %@",
    "DG.CaseCard.attrHintFormula": "%@\n%@",
    "DG.AppController.optionMenuItems.help-forum": "Hilfeforum...",
    "DG.AppController.showHelpForumTitle": "Hilfeforum",
    "DG.Locale.name.el": "Griechisch",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ of %@ (%@%) ist %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ von %@ (%@%) sind %@",
    "DG.DataDisplayMenu.removeAttribute_top": "Entfernen: Side-by-side Layout durch %@\n",
    "DG.DataDisplayMenu.removeAttribute_right": "Entfernen: Vertikales Layout durch %@",
    "DG.GraphView.layoutPlotsSideBySide": "Side-by-side Layout durch %@",
    "DG.GraphView.layoutPlotsVertically": "Vertikales Layout durch %@",
    "DG.Undo.graph.makeStrokeSameAsFill": "Rückgängig: Umrandung und Füllung gleich",
    "DG.Redo.graph.makeStrokeSameAsFill": "Wiederholen: Umrandung und Füllung gleich",
    "DG.Undo.graph.makeStrokeIndependent": "Rückgängig: Umrandung anders als Füllung",
    "DG.Redo.graph.makeStrokeIndependent": "Wiederholen: Umrandung anders als Füllung",
    "DG.Inspector.strokeSameAsFill": "Umrandung und Füllung gleich",
    "DG.Formula.DateShortDaySunday": "Son",
    "DG.Formula.DateShortDayMonday": "Mon",
    "DG.Formula.DateShortDayTuesday": "Die",
    "DG.Formula.DateShortDayWednesday": "Mit",
    "DG.Formula.DateShortDayThursday": "Don",
    "DG.Formula.DateShortDayFriday": "Fre",
    "DG.Formula.DateShortDaySaturday": "Sam",
    "DG.AttributeFormat.DatePrecision.millisecond": "MMM D, YYYY HH:mm:ss.SSS\n",
    "DG.CellAxis.other": "ANDERE",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 MAD, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "Durchschnittliche absolute Abweichung",
    "DG.Undo.graph.showPlottedBoxPlot": "Boxplot wieder entfernen",
    "DG.Redo.graph.hidePlottedBoxPlot": "Boxplot erneut verbergen",
    "DG.Undo.graph.hidePlottedBoxPlot": "Rückgängig: Boxplot verbergen",
    "DG.Redo.graph.showPlottedBoxPlot": "Wiederholen: Boxplot anzeigen",
    "DG.Undo.graph.showOutliers": "Rückgängig: Ausreißer anzeigen",
    "DG.Redo.graph.hideOutliers": "Wiederholen: Ausreißer verbergen",
    "DG.Undo.graph.hideOutliers": "Rückgängig: Ausreißer verbergen",
    "DG.Redo.graph.showOutliers": "Wiederholen: Ausreißer anzeigen",
    "DG.Inspector.graphBoxPlotShowOutliers": "Ausreißer anzeigen",
    "DG.Locale.name.nb": "Bokmål",
    "DG.Locale.name.nn": "Nynorsk",
    "DG.CaseCard.newCaseToolTip": "Dieser Sammlung einen leeren Fall hinzufügen",
    "DG.TableController.headerMenuItems.renameAttribute": "Umbenennen",
    "DG.Undo.graph.fuseDotsToRectangles": "Undo fusing dots into rectangles",
    "DG.Redo.graph.fuseDotsToRectangles": "Redo fusing dots into rectangles",
    "DG.Undo.graph.dissolveRectanglesToDots": "Undo dissolving rectangles into dots",
    "DG.Redo.graph.dissolveRectanglesToDots": "Redo dissolving rectangles into dots",
    "DG.Undo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Redo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Undo.graph.showAsBinnedPlot": "Undo grouping dots into bins",
    "DG.Redo.graph.showAsBinnedPlot": "Redo grouping dots into bins",
    "DG.Undo.graph.showAsDotPlot": "Undo ungrouping dots from bins",
    "DG.Redo.graph.showAsDotPlot": "Redo ungrouping dots from bins",
    "DG.Undo.graph.dragBinBoundary": "Undo dragging bin boundary",
    "DG.Redo.graph.dragBinBoundary": "Redo dragging bin boundary",
    "DG.Undo.graph.changeBinWidth": "Undo changing bin width",
    "DG.Redo.graph.changeBinWidth": "Redo changing bin width",
    "DG.Undo.graph.changeBinAlignment": "Undo changing bin alignment",
    "DG.Redo.graph.changeBinAlignment": "Redo changing bin alignment",
    "DG.BinnedPlotModel.dragBinTip": "Drag to change bin width",
    "DG.HistogramView.barTipPlural": "%@ of %@ %@ (%@%) are ≥ %@ and < %@",
    "DG.HistogramView.barTipSingular": "%@ of %@ %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendSingular": "%@ of %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendPlural": "%@ of %@ (%@%) are ≥ %@ and < %@",
    "DG.Inspector.graphGroupIntoBins": "Group into Bins",
    "DG.Inspector.graphBinWidth": "Bin width",
    "DG.Inspector.graphAlignment": "Alignment",
    "DG.CaseTable.dividerView.expandAllTooltip": "expand all groups",
    "DG.CaseTable.dividerView.expandGroupTooltip": "expand group",
    "DG.CaseTable.dividerView.collapseAllTooltip": "collapse all groups",
    "DG.CaseTable.dividerView.collapseGroupTooltip": "collapse group",
    "DG.BinnedPlotModel.binLabelTip": "Values in this bin are ≥ %@ and < %@",
    "DG.Component.closeComponent.toolTip": "Close this Component",
    "DG.Component.minimizeComponent.toolTip": "Minimize or expand this Component",
    "DG.Locale.name.ja": "Japanese",
    "DG.CaseCard.attrHintDescriptionAndFormula": "%@1: %@2\n%@1 = %@3",
    "DG.Locale.name.zh-Hans": "Simplified Chinese",
    "DG.PlottedCount.withoutSelection": "%@",
    "DG.PlottedCount.withSelection": "%@ selected",
    "DG.PlottedPercent.withoutSelection": "%@%",
    "DG.PlottedPercent.withSelection": "%@% selected",
    "DG.PlottedCountPercent.withoutSelection": "%@ (%@%)",
    "DG.PlottedCountPercent.withSelection": "%@ of %@ (%@%) selected",
    "DG.Undo.caseTable.resizeColumn": "Undo fit width to content",
    "DG.Redo.caseTable.resizeColumn": "Redo fit width to content",
    "DG.TableController.headerMenuItems.resizeColumn": "Fit width to content",
    "DG.SelectedInfoView.infoPlural": "Showing measures for %@ selected cases",
    "DG.SelectedInfoView.infoSing": "Showing measures for %@ selected case",
    "DG.Inspector.copyCaseDataToClipboard": "Copy to Clipboard...",
    "DG.Inspector.caseTable.exportCaseDialog.copyFrom": "Copy case data from:",
    "DG.Inspector.caseTable.exportCaseDialog.copy": "Copy",
    "DG.Inspector.caseTable.exportCaseDialog.copyTooltip": "Copy data to clipboard",
    "DG.Inspector.caseTable.exportCaseDialog.copiedData": "Copied %@ to the clipboard",
    "DG.Undo.caseTable.hideAttribute": "Undo hiding attribute",
    "DG.Redo.caseTable.hideAttribute": "Redo hiding attribute",
    "DG.Undo.caseTable.showAllHiddenAttributes": "Undo show all hidden attributes",
    "DG.Redo.caseTable.showAllHiddenAttributes": "Redo show all hidden attributes",
    "DG.TableController.headerMenuItems.hideAttribute": "Hide Attribute",
    "DG.Inspector.attributes.showAllHiddenAttributesSing": "Show %@ Hidden Attribute",
    "DG.Inspector.attributes.showAllHiddenAttributesPlural": "Show %@ Hidden Attributes",
    "DG.Inspector.attributes.showAllHiddenAttributesDisabled": "Show Hidden Attributes",
    "DG.Inspector.getCaseDataFromClipboard": "Import Case Data from Clipboard...",
    "DG.CaseCard.addCaseButton": "add case",
    "DG.Undo.DataContext.join": "Undo join of %@ to %@",
    "DG.Redo.DataContext.join": "Redo join of %@ to %@",
    "DG.Collection.joinTip": "Join %@ in %@ to %@ in %@ by matching %@ with %@",
    "DG.Inspector.graphPlotPoints": "Points",
    "DG.Inspector.graphBarForEachPoint": "Bar for Each Point",
    "DG.Undo.graph.changeBarChartFunction": "Undo change bar chart formula",
    "DG.Redo.graph.changeBarChartFunction": "Redo change bar chart formula",
    "DG.Undo.graph.showAsLinePlot": "Undo bar for each point",
    "DG.Redo.graph.showAsLinePlot": "Redo bar for each point",
    "DG.Undo.graph.showAsStandardBarChart": "Undo using count or percent for bar chart scale",
    "DG.Redo.graph.showAsStandardBarChart": "Redo using count or percent for bar chart scale",
    "DG.Undo.graph.showAsComputedBarChart": "Undo computing bar length with formula",
    "DG.Redo.graph.showAsComputedBarChart": "Redo computing bar length with formula",
    "DG.FormulaAxisView.labelDescription": "The expression that determines the length of the bars. Click to edit.",
    "DG.ComputedBarChartModel.cellTip": "For group %@ the value is %@",
    "DG.BarChartFunction.namePrompt": "Bar Chart",
    "DG.BarChartFunction.formulaPrompt": "bar length =",
    "DG.BarChartFunction.formulaHint": "Type a formula to compute bar length",
    "DG.BarChartFunction.emptyExpressionAxisPrompt": "Click here to provide a formula",
    "DG.Inspector.graphFormula": "Formula",
    "DG.Undo.displayOnlySelected": "Undo displaying only selected cases",
    "DG.Redo.displayOnlySelected": "Redo displaying only selected cases",
    "DG.Undo.webView.show": "Undo adding webView component",
    "DG.Redo.webView.show": "Redo adding webView component",
    "DG.Undo.imageComponent.show": "Undo adding image component",
    "DG.Redo.imageComponent.show": "Redo adding image component",
    "DG.DataDisplayMenu.displayOnlySelected": "Display Only Selected Cases",
    "DG.DataDisplayMenu.displayingOnlySelected": "Displaying Only Selected Cases",
    "DG.PlotBackgroundView.msg0": "This graph is set to display",
    "DG.PlotBackgroundView.msg1": "only selected cases.",
    "DG.PlotBackgroundView.msg2": "No cases are selected",
    "DG.PlotBackgroundView.msg3": "so nothing is being displayed.",
    "DG.PlotBackgroundView.msg4": "You can select cases in a",
    "DG.PlotBackgroundView.msg5": "case table or another graph.",
    "DG.ImageComponent.defaultTitle": "Image",
    "DG.TableController.datasetMetadata.title": "Dataset Information",
    "DG.CaseTable.datasetMetadata.url": "source",
    "DG.CaseTable.datasetMetadata.creationDate": "import date",
    "DG.TableController.datasetMetadata.descriptionHint": "Describe the dataset",
    "DG.Inspector.datasetInfo.toolTip": "Display information about dataset",
    "DG.CaseTable.indexMenu.moveEntryRow": "Move Data Entry Row Here",
    "DG.CaseCard.deselect": "Deselect all cases",
    "DG.CaseCard.noDeselect": "No cases are selected",
    "DG.CaseTable.indexProto.tooltip": "Drag to place data entry row within this table",
    "DG.AttributeFormat.DatePrecisionShort.year": "YYYY",
    "DG.AttributeFormat.DatePrecisionShort.month": "M/YY",
    "DG.AttributeFormat.DatePrecisionShort.day": "M/D/YY",
    "DG.AttributeFormat.DatePrecisionShort.hour": "M/D/YY HH:00",
    "DG.AttributeFormat.DatePrecisionShort.minute": "M/D/YY HH:mm",
    "DG.AttributeFormat.DatePrecisionShort.second": "M/D/YY HH:mm:ss",
    "DG.AttributeFormat.DatePrecisionShort.millisecond": "M/D/YY HH:mm:ss.SSS",
    "DG.Formula.FuncCategoryLogic": "Logic Functions",
    "DG.Undo.graph.showMeasureLabels": "Undo showing measure labels",
    "DG.Redo.graph.showMeasureLabels": "Redo showing measure labels",
    "DG.Undo.graph.hideMeasureLabels": "Undo hiding measure labels",
    "DG.Redo.graph.hideMeasureLabels": "Redo hiding measure labels",
    "DG.Inspector.showLabels": "Show Measure Labels",
    "DG.Undo.caseTable.resizeOneColumn": "Undo resize column",
    "DG.Redo.caseTable.resizeOneColumn": "Redo resize column",
    "DG.CaseTable.attribute.type.checkbox": "checkbox",
    "DG.AppController.caseTableMenu.clipboardDataset": "-- new from clipboard --",
    "DG.AppController.caseTableMenu.clipboardDatasetToolTip": "Paste data set from clipboard",
    "DG.AppController.optionMenuItems.toPrivacyPage": "Privacy Page...",
    "DG.plugin.Importer.title": "Import CSV to CODAP",
    "DG.plugin.Importer.enter-url": "Enter url: ",
    "DG.plugin.Importer.or": "or",
    "DG.plugin.Importer.downsample-section": "Downsample Options...",
    "DG.plugin.Importer.downsample-random-p1": "Randomly select",
    "DG.plugin.Importer.downsample-random-p2": "rows",
    "DG.plugin.Importer.downsample-every-nth-p1": "Select every",
    "DG.plugin.Importer.downsample-every-nth-p2": "th row",
    "DG.plugin.Importer.downsample-import-all": "Import all rows",
    "DG.plugin.Importer.target-options-title": "Target Options...",
    "DG.plugin.Importer.target-options-replace": "Replace existing dataset with this one",
    "DG.plugin.Importer.target-options-append": "Append this dataset to the existing one",
    "DG.plugin.Importer.target-options-create-new": "Create a new data set",
    "DG.plugin.Importer.button-cancel": "Cancel",
    "DG.plugin.Importer.button-submit": "OK",
    "DG.plugin.Importer.button-dismiss": "Dismiss",
    "DG.plugin.Importer.load-error": "There was an error loading this resource: \"%@\" reason: \"%@\"",
    "DG.plugin.Importer.no-table-error": "Could not find tabular data in a format that can be imported into CODAP",
    "DG.plugin.Importer.duplicate-dataset-msg": "There already exists a dataset like this one. It is named \"%@\".",
    "DG.plugin.Importer.upload-time-msg": "It was uploaded %@",
    "DG.plugin.Importer.large-file-msg": "The imported file, \"%@\" has %@ rows. With more than %@ rows CODAP performance may be sluggish. You can work with a sample of the data at least at first, replacing it with the full dataset later.",
    "DG.plugin.Importer.error-codap-connection": "Error sending data to CODAP",
    "DG.plugin.Importer.error-upload": "Could not import this file -- %@",
    "DG.plugin.Importer.import-message": "Preparing to import %@ rows into \"%@\" from a table with %@ attributes: %@%@",
    "DG.Undo.component.componentTitleChange": "Undo changing the component title",
    "DG.Redo.component.componentTitleChange": "Redo changing the component title"
});