SC.stringsFor("de", {
    "DG.fileMenu.menuItem.newDocument": "Neu",
    "DG.fileMenu.menuItem.openDocument": "Öffnen...",
    "DG.fileMenu.menuItem.closeDocument": "Schließen",
    "DG.fileMenu.menuItem.importFile": "Importieren ...",
    "DG.fileMenu.menuItem.revertTo": "Zurückkehren...",
    "DG.fileMenu.menuItem.revertToOpened": "Kürzlich geöffnete Fassung",
    "DG.fileMenu.menuItem.revertToShared": "Geteilte Ansicht",
    "DG.fileMenu.menuItem.saveDocument": "Speichern ...",
    "DG.fileMenu.menuItem.copyDocument": "Kopie erstellen",
    "DG.fileMenu.menuItem.share": "Teilen ...",
    "DG.fileMenu.menuItem.shareGetLink": "Link erhalten für geteilte Ansicht",
    "DG.fileMenu.menuItem.shareUpdate": "Geteilte Ansicht aktualisieren",
    "DG.fileMenu.menuItem.renameDocument": "Umbennen",
    "DG.main.userEntryView.title": "Was soll getan werden?",
    "DG.main.userEntryView.openDocument": "Dokument öffnen oder Beispiele ansehen",
    "DG.main.userEntryView.newDocument": "Neues Dokument erstellen",
    "DG.mainPage.mainPane.undoButton.title": "Rückgängig",
    "DG.mainPage.mainPane.undoButton.toolTip": "Die letzte Aktion rückgängig machen",
    "DG.mainPage.mainPane.redoButton.title": "Wiederholen",
    "DG.mainPage.mainPane.redoButton.toolTip": "Letzte Aktion wiederholen",
    "DG.mainPage.mainPane.versionString": "Version %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Leider wird CODAP aktuell nicht vom verwendeten Browser unterstützt. CODAP wird unterstützt von Firefox 46+, Chrome 50+, Windows Edge 14+ und Safari 10+. CODAP wird zur Zeit nicht von anderen Browsern unterstützt.",
    "DG.mainPage.titleBar.saved": "Dokument gespeichert!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Version %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Version %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Daten löschen...",
    "DG.AppController.resetData.toolTip": "Alle Daten des aktuellen Dokuments löschen",
    "DG.AppController.resetData.warnMessage": "Sollen wirklich alle Daten in diesem Dokument gelöscht werden?",
    "DG.AppController.resetData.warnDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.AppController.resetData.okButtonTitle": "Ja, Daten löschen",
    "DG.AppController.resetData.cancelButtonTitle": "Nein, Daten behalten",
    "DG.AppController.closeDocument.warnMessage": "Ohne Speichern schließen?",
    "DG.AppController.closeDocument.warnDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.AppController.closeDocument.okButtonTitle": "Schließen",
    "DG.AppController.closeDocument.cancelButtonTitle": "Abbrechen",
    "DG.AppController.beforeUnload.confirmationMessage": "Das Dokument enthält ungespeicherte Änderungen.",
    "DG.AppController.optionMenuItems.reportProblem": "Feedback senden...",
    "DG.AppController.optionMenuItems.viewWebPage": "Webseite anzeigen...",
    "DG.AppController.optionMenuItems.configureGuide": "Anleitung konfigurieren",
    "DG.AppController.optionMenuItems.about": "Über CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "Neuigkeiten",
    "DG.AppController.optionMenuItems.help": "Hilfe...",
    "DG.AppController.optionMenuItems.toWebSite": "CODAP Webseite",
    "DG.AppController.exportDocument.prompt": "Dateiname:",
    "DG.AppController.exportCaseData.prompt": "Daten exportieren",
    "DG.AppController.exportDocument.exportTitle": "Exportieren",
    "DG.AppController.exportDocument.exportTooltip": "Daten exportieren in eine Datei",
    "DG.AppController.exportDocument.cancelTitle": "Abbrechen",
    "DG.AppController.exportDocument.cancelTooltip": "Exportvorgang abbrechen",
    "DG.AppController.feedbackDialog.dialogTitle": "Rückmeldung geben",
    "DG.AppController.feedbackDialog.subHeaderText": "Deine Rückmeldung ist wichtig für uns!",
    "DG.AppController.feedbackDialog.messageText": "Bitte hilf uns, unser Produkt weiter zu verbessern. Fragen, Fehlerberichte und Feature-Wünsche sind willkommen. Danke!",
    "DG.AppController.feedbackDialog.subjectHint": "Wozu gibst Du eine Rückmeldung",
    "DG.AppController.feedbackDialog.feedbackHint": "Details",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Einreichen",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Abbrechen",
    "DG.AppController.showWebSiteTitle": "Über CODAP",
    "DG.AppController.showHelpTitle": "Hilfe zu CODAP",
    "DG.AppController.showAboutTitle": "Über CODAP",
    "DG.AppController.showReleaseNotesTitle": "CODAP Versionshinweise",
    "DG.AppController.dropFile.error": "Fehler: %@1",
    "DG.AppController.dropFile.unknownFileType": "Dieser Dateityp kann nicht importiert werden",
    "DG.AppController.validateDocument.missingRequiredProperty": "Notwendige Eigenschaft nicht gefunden: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Unerwartete Top-Level Eigenschaft: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Ungeklärte Id: %@1",
    "DG.AppController.validateDocument.parseError": "Analysefehler im Dokument: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Ungültiges JSON Dokument: %@1",
    "DG.AppController.openDocument.error.general": "Das Dokument konnte nicht geöffnet werden.",
    "DG.AppController.openDocument.error.invalid_format": "Dieser Dokumenttyp kann von CODAP nicht gelesen werden",
    "DG.AppController.createDataSet.initialAttribute": "Merkmal",
    "DG.AppController.createDataSet.name": "Neuer Datensatz",
    "DG.AppController.createDataSet.collectionName": "Fälle",
    "DG.AppController.caseTableMenu.newDataSet": "-- neu --",
    "DG.SingleTextDialog.okButton.title": "OK",
    "DG.SingleTextDialog.cancelButton.title": "Abbrechen",
    "DG.SingleTextDialog.cancelButton.toolTip": "Ohne Änderungen verlassen",
    "DG.DocumentController.calculatorTitle": "Taschenrechner",
    "DG.DocumentController.caseTableTitle": "Falltabelle",
    "DG.DocumentController.graphTitle": "Graph",
    "DG.DocumentController.sliderTitle": "Regler",
    "DG.DocumentController.textTitle": "Textfeld",
    "DG.DocumentController.mapTitle": "Karte",
    "DG.DocumentController.enterURLPrompt": "URL eingeben, um eine Website anzuzeigen",
    "DG.DocumentController.enterViewWebPageOKTip": "Die Website der URL anzeigen",
    "DG.Document.defaultDocumentName": "Unbenanntes Dokument",
    "DG.Document.documentName.toolTip": "Klicken, um den Name des Dokuments zu ändern",
    "DG.SliderView.thumbView.toolTip": "Ziehen, um den Wert des Reglers zu ändern",
    "DG.SliderView.startButton.toolTip": "Animation starten/anhalten",
    "DG.ToolButtonData.tableButton.title": "Tabellen",
    "DG.ToolButtonData.tableButton.toolTip": "Öffne eine Falltabelle für jeden Datensatz (Strg+alt+t)",
    "DG.ToolButtonData.graphButton.title": "Graph",
    "DG.ToolButtonData.graphButton.toolTip": "Erstelle einen Graph (Strg+alt+g)",
    "DG.ToolButtonData.sliderButton.title": "Regler",
    "DG.ToolButtonData.sliderButton.toolTip": "Erstelle einen Regler (Strg+alt+s)",
    "DG.ToolButtonData.calcButton.title": "Rechner",
    "DG.ToolButtonData.calcButton.toolTip": "Öffne/Schließe den Taschenrechner (Strg+alt+c)",
    "DG.ToolButtonData.textButton.title": "Text",
    "DG.ToolButtonData.textButton.toolTip": "Erstelle ein Textfeld (Strg+alt+shift+t)",
    "DG.ToolButtonData.mapButton.title": "Karte",
    "DG.ToolButtonData.mapButton.toolTip": "Eine Karte erstellen",
    "DG.ToolButtonData.optionMenu.title": "Einstellungen",
    "DG.ToolButtonData.optionMenu.toolTip": "Website anzeigen, Anleitung konfigurieren",
    "DG.ToolButtonData.tileListMenu.title": "Objekte",
    "DG.ToolButtonData.tileListMenu.toolTip": "Liste der Objekte anzeigen",
    "DG.ToolButtonData.guideMenu.title": "Anleitung",
    "DG.ToolButtonData.guideMenu.toolTip": "Anleitung dieser Aktivität anzeigen und verwenden",
    "DG.ToolButtonData.guideMenu.showGuide": "Anleitung zeigen",
    "DG.ToolButtonData.help.title": "Hilfe",
    "DG.ToolButtonData.help.toolTip": "Hilfe zu CODAP, das Projekt kennenlernen",
    "DG.Slider.multiples": "Begrenzen auf Vielfache von:",
    "DG.Slider.maxPerSecond": "Maximum Animation Frames/sec",
    "DG.Slider.direction": "Richtung der Animation",
    "DG.Slider.backAndForth": "Vor und Zurück",
    "DG.Slider.lowToHigh": "Niedrig zu Hoch",
    "DG.Slider.highToLow": "Hoch zu Niedrig",
    "DG.Slider.mode": "Wiederholung der Animation",
    "DG.Slider.nonStop": "pausenlos",
    "DG.Slider.onceOnly": "Nur einmal",
    "DG.Undo.exceptionOccurred": "Ein Fehler trat auf beim Rückgängig Machen.",
    "DG.Redo.exceptionOccurred": "Ein Fehler trat auf beim Wiederholen.",
    "DG.Undo.componentMove": "Rückgängig: Das Objekt verschieben",
    "DG.Redo.componentMove": "Wiederholen: Das Objekt verschieben",
    "DG.Undo.componentResize": "Rückgängig: Größenänderung des Objekts",
    "DG.Redo.componentResize": "Wiederholen: Größenänderung des Objekts",
    "DG.Undo.axisDilate": "Rückgängig: Die Achse verändern",
    "DG.Redo.axisDilate": "Wiederholen: Die Achse verändern",
    "DG.Undo.axisRescaleFromData": "Rückgängig: Die Achse verändern",
    "DG.Redo.axisRescaleFromData": "Wiederholen: Die Achse verändern",
    "DG.Undo.axisDrag": "Rückgängig: Verschieben der Achse",
    "DG.Redo.axisDrag": "Wiederholen: Verschieben der Achse",
    "DG.Undo.axisAttributeChange": "Rückgängig: Das Merkmal der Achse verändern",
    "DG.Redo.axisAttributeChange": "Wiederholen: Das Merkmal der Achse verändern",
    "DG.Undo.axisAttributeAdded": "Rückgängig: Der Achse ein Merkmal hinzufügen",
    "DG.Redo.axisAttributeAdded": "Wiederholen: Der Achse ein Merkmal hinzufügen",
    "DG.Undo.toggleComponent.add.calcView": "Rückgängig: Den Taschenrechner einblenden",
    "DG.Redo.toggleComponent.add.calcView": "Wiederholen: Den Taschenrechner einblenden",
    "DG.Undo.toggleComponent.delete.calcView": "Rückgängig: Den Taschenrechner verbergen",
    "DG.Redo.toggleComponent.delete.calcView": "Wiederholen: Den Taschenrechner verbergen",
    "DG.Undo.caseTable.open": "Rückgängig: Die Tabelle einblenden",
    "DG.Redo.caseTable.open": "Wiederholen: Die Tabelle einblenden",
    "DG.Undo.caseTable.editAttribute": "Rückgängig: Eigenschaften der Tabelle",
    "DG.Redo.caseTable.editAttribute": "Wiederholen: Eigenschaften der Tabelle",
    "DG.Undo.caseTable.createAttribute": "Rückgängig: Eigenschaften der Tabelle erstellen",
    "DG.Redo.caseTable.createAttribute": "Wiederholen: Eigenschaften der Tabelle erstellen",
    "DG.Undo.caseTable.editAttributeFormula": "Rückgängig: Formel der Tabelle bearbeiten",
    "DG.Redo.caseTable.editAttributeFormula": "Wiederholen: Formel der Tabelle bearbeiten",
    "DG.Undo.caseTable.editCellValue": "Rückgängig: Zellwert der Tabelle bearbeiten",
    "DG.Redo.caseTable.editCellValue": "Wiederholen: Zellwert der Tabelle bearbeiten",
    "DG.Undo.caseTable.sortCases": "Rückgängig: Fälle sortieren",
    "DG.Redo.caseTable.sortCases": "Wiederholen: Fälle sortieren",
    "DG.Undo.caseTable.deleteAttribute": "Rückgängig: Eigenschaft der Tabelle löschen",
    "DG.Redo.caseTable.deleteAttribute": "Wiederholen: Eigenschaft der Tabelle löschen",
    "DG.Undo.caseTable.createCollection": "Rückgängig: Neue Kollektion erstellen",
    "DG.Redo.caseTable.createCollection": "Wiederholen: Neue Kollektion erstellen",
    "DG.Undo.caseTable.collectionNameChange": "Rückgängig: Kollektion umbenennen",
    "DG.Redo.caseTable.collectionNameChange": "Wiederholen: Kollektion umbenennen",
    "DG.Undo.caseTable.createNewCase": "Rückgängig: Neuen Fall erstellen",
    "DG.Redo.caseTable.createNewCase": "Wiederholen: Neuen Fall erstellen",
    "DG.Undo.caseTable.insertCases": "Rückgängig: Fälle einfügen",
    "DG.Redo.caseTable.insertCases": "Wiederholen: Fälle einfügen",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Undo toggle expand/collapse all",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Redo toggle expand/collapse all",
    "DG.Undo.caseTable.expandCollapseOneCase": "Undo expand or collapse of a group",
    "DG.Redo.caseTable.expandCollapseOneCase": "Redo expand or collapse of a group",
    "DG.Undo.caseTable.resizeColumns": "Rückgängig: Automatische Größenanpassung aller Spalten",
    "DG.Redo.caseTable.resizeColumns": "Wiederholen: Automatische Größenanpassung aller Spalten",
    "DG.Undo.document.share": "Rückgängig: Dokument teilen",
    "DG.Redo.document.share": "Wiederholen: Dokument teilen",
    "DG.Undo.document.unshare": "Rückgängig: Dokument teilen beenden",
    "DG.Redo.document.unshare": "Wiederholen: Dokument teilen beenden",
    "DG.Undo.game.add": "Rückgängig: Ein Spiel hinzufügen",
    "DG.Redo.game.add": "Wiederholen: Ein Spiel hinzufügen",
    "DG.Undo.graph.showCount": "Rückgängig: Anzahl zeigen",
    "DG.Redo.graph.showCount": "Wiederholen: Anzahl zeigen",
    "DG.Undo.graph.hideCount": "Rückgängig: Anzahl verbergen",
    "DG.Redo.graph.hideCount": "Wiederholen: Anzahl verbergen",
    "DG.Undo.graph.showPercent": "Rückgängig: Prozent zeigen",
    "DG.Redo.graph.showPercent": "Wiederholen: Prozent zeigen",
    "DG.Undo.graph.hidePercent": "Rückgängig: Prozent verbergen",
    "DG.Redo.graph.hidePercent": "Wiederholen: Prozent verbergen",
    "DG.Undo.graph.showMovableLine": "Rückgängig: Bewegliche Linie zeigen",
    "DG.Redo.graph.showMovableLine": "Wiederholen: Bewegliche Linie zeigen",
    "DG.Undo.graph.hideMovableLine": "Rückgängig: Bewegliche Linie verbergen",
    "DG.Redo.graph.hideMovableLine": "Wiederholen: Bewegliche Linie verbergen",
    "DG.Undo.graph.lockIntercept": "Undo locking line intercept",
    "DG.Redo.graph.lockIntercept": "Redo locking line intercept",
    "DG.Undo.graph.unlockIntercept": "Undo unlocking line intercept",
    "DG.Redo.graph.unlockIntercept": "Redo unlocking line intercept",
    "DG.Undo.graph.showPlotFunction": "Undo showing plotted function",
    "DG.Redo.graph.showPlotFunction": "Redo showing plotted function",
    "DG.Undo.graph.hidePlotFunction": "Undo hiding plotted function",
    "DG.Redo.graph.hidePlotFunction": "Redo hiding plotted function",
    "DG.Undo.graph.changePlotFunction": "Undo change plotted function",
    "DG.Redo.graph.changePlotFunction": "Redo change plotted function",
    "DG.Undo.graph.showPlotValue": "Undo showing plotted value",
    "DG.Redo.graph.showPlotValue": "Redo showing plotted value",
    "DG.Undo.graph.hidePlotValue": "Undo hiding plotted value",
    "DG.Redo.graph.hidePlotValue": "Redo hiding plotted value",
    "DG.Undo.graph.changePlotValue": "Undo change plotted value",
    "DG.Redo.graph.changePlotValue": "Redo change plotted value",
    "DG.Undo.graph.showConnectingLine": "Rückgängig: Verbundene Linien zeigen",
    "DG.Redo.graph.showConnectingLine": "Wiederholen: Verbundene Linien zeigen",
    "DG.Undo.graph.hideConnectingLine": "Rückgängig: Verbundene Linien verbergen",
    "DG.Redo.graph.hideConnectingLine": "Wiederholen: Verbundene Linien verbergen",
    "DG.Undo.graph.showLSRL": "Undo showing least squares line",
    "DG.Redo.graph.showLSRL": "Redo showing least squares line",
    "DG.Undo.graph.hideLSRL": "Undo hiding least squares line",
    "DG.Redo.graph.hideLSRL": "Redo hiding least squares line",
    "DG.Undo.graph.showSquares": "Undo showing squares",
    "DG.Redo.graph.showSquares": "Redo showing squares",
    "DG.Undo.graph.hideSquares": "Undo hiding squares",
    "DG.Redo.graph.hideSquares": "Redo hiding squares",
    "DG.Undo.graph.showPlottedMean": "Rückgängig: Arithmetisches Mittel anzeigen",
    "DG.Redo.graph.showPlottedMean": "Wiederholen: Arithmetisches Mittel anzeigen",
    "DG.Undo.graph.hidePlottedMean": "Rückgängig: Arithmetisches Mittel verbergen",
    "DG.Redo.graph.hidePlottedMean": "Wiederholen: Arithmetisches Mittel verbergen",
    "DG.Undo.graph.showPlottedMedian": "Rückgängig: Median anzeigen",
    "DG.Redo.graph.showPlottedMedian": "Wiederholen: Median anzeigen",
    "DG.Undo.graph.hidePlottedMedian": "Rückgängig: Median verbergen",
    "DG.Redo.graph.hidePlottedMedian": "Wiederholen: Median verbergen",
    "DG.Undo.graph.showPlottedStDev": "Rückgängig: Standardabweichung anzeigen",
    "DG.Redo.graph.showPlottedStDev": "Wiederholen: Standardabweichung anzeigen",
    "DG.Undo.graph.hidePlottedStDev": "Rückgängig: Standardabweichung verbergen",
    "DG.Redo.graph.hidePlottedStDev": "Wiederholen: Standardabweichung verbergen",
    "DG.Undo.graph.showPlottedIQR": "Rückgängig: Interquartilsabstand anzeigen",
    "DG.Redo.graph.hidePlottedIQR": "Wiederholen: Interquartilsabstand anzeigen",
    "DG.Undo.graph.hidePlottedIQR": "Rückgängig: Interquartilsabstand verbergen",
    "DG.Redo.graph.showPlottedIQR": "Wiederholen: Interquartilsabstand verbergen",
    "DG.Undo.graph.addMovableValue": "Rückgängig: Beweglichen Wert hinzufügen",
    "DG.Redo.graph.addMovableValue": "Wiederholen: Beweglichen Wert hinzufügen",
    "DG.Undo.graph.removeMovableValue": "Rückgängig: Beweglichen Wert entfernen",
    "DG.Redo.graph.removeMovableValue": "Wiederholen: Beweglichen Wert entfernen",
    "DG.Undo.graph.moveMovableValue": "Undo moving movable value",
    "DG.Redo.graph.moveMovableValue": "Redo moving movable value",
    "DG.Undo.graph.changePointColor": "Rückgängig: Datenfarbe ändern",
    "DG.Redo.graph.changePointColor": "Wiederholen: Datenfarbe ändern",
    "DG.Undo.graph.changeStrokeColor": "Undo changing stroke color",
    "DG.Redo.graph.changeStrokeColor": "Redo changing stroke color",
    "DG.Undo.graph.changePointSize": "Undo changing point size",
    "DG.Redo.graph.changePointSize": "Redo changing point size",
    "DG.Undo.graph.changeAttributeColor": "Rückgängig: Merkmalsfarbe ändern",
    "DG.Redo.graph.changeAttributeColor": "Wiederholen: Merkmalsfarbe ändern",
    "DG.Undo.graph.changeBackgroundColor": "Rückgängig: Hintergrundfarbe des Graphen ändern",
    "DG.Redo.graph.changeBackgroundColor": "Wiederholen: Hintergrundfarbe des Graphen ändern",
    "DG.Undo.graph.toggleTransparent": "Undo toggling plot transparency",
    "DG.Redo.graph.toggleTransparent": "Redo toggling plot transparency",
    "DG.Undo.guide.show": "Undo showing the guide",
    "DG.Redo.guide.show": "Redo showing the guide",
    "DG.Undo.guide.navigate": "Undo changing the guide page",
    "DG.Redo.guide.navigate": "Redo changing the guide page",
    "DG.Undo.hideSelectedCases": "Rückgängig: Ausgewählte Fälle verbergen",
    "DG.Redo.hideSelectedCases": "Wiederholen: Ausgewählte Fälle verbergen",
    "DG.Undo.hideUnselectedCases": "Rückgängig: Nichtausgewählte Fälle verbergen",
    "DG.Redo.hideUnselectedCases": "Wiederholen: Nichtausgewählte Fälle verbergen",
    "DG.Undo.enableNumberToggle": "Undo Show Parent Visibility Toggles",
    "DG.Redo.enableNumberToggle": "Redo Show Parent Visibility Toggles",
    "DG.Undo.disableNumberToggle": "Undo Hide Parent Visibility Toggles",
    "DG.Redo.disableNumberToggle": "Redo Hide Parent Visibility Toggles",
    "DG.Undo.interactiveUndoableAction": "Undo an action in the interactive",
    "DG.Redo.interactiveUndoableAction": "Redo an action in the interactive",
    "DG.Undo.showAllCases": "Rückgängig: Alle Fälle anzeigen",
    "DG.Redo.showAllCases": "Wiederholen: Alle Fälle anzeigen",
    "DG.Undo.map.create": "Rückgängig: Karte hinzufügen",
    "DG.Redo.map.create": "Wiederholen: Karte hinzufügen",
    "DG.Undo.map.fitBounds": "Rückgängig: Kartengröße ändern",
    "DG.Redo.map.fitBounds": "Wiederholen: Kartengröße ändern",
    "DG.Undo.map.pan": "Undo panning map",
    "DG.Redo.map.pan": "Redo panning map",
    "DG.Undo.map.zoom": "Rückgängig: Zoomen",
    "DG.Redo.map.zoom": "Wiederholen: Zoomen",
    "DG.Undo.map.showGrid": "Rückgängig: Raster in Karte zeigen",
    "DG.Redo.map.showGrid": "Wiederholen: Raster in Karte zeigen",
    "DG.Undo.map.hideGrid": "Rückgängig: Raster in Karte verbergen",
    "DG.Redo.map.hideGrid": "Wiederholen: Raster in Karte verbergen",
    "DG.Undo.map.changeGridSize": "Rückgängig: Rastergröße der Karte ändern",
    "DG.Redo.map.changeGridSize": "Wiederholen: Rastergröße der Karte ändern",
    "DG.Undo.map.showPoints": "Rückgängig: Punkte auf Karte zeigen",
    "DG.Redo.map.showPoints": "Wiederholen: Punkte auf Karte zeigen",
    "DG.Undo.map.hidePoints": "Rückgängig: Punkte auf Karte verbergen",
    "DG.Redo.map.hidePoints": "Wiederholen: Punkte auf Karte verbergen",
    "DG.Undo.map.showLines": "Rückgängig: Linien auf Karte zeigen",
    "DG.Redo.map.showLines": "Wiederholen: Linien auf Karte zeigen",
    "DG.Undo.map.hideLines": "Rückgängig: Linien auf Karte verbergen",
    "DG.Redo.map.hideLines": "Wiederholen: Linien auf Karte verbergen",
    "DG.Undo.map.changeBaseMap": "Rückgängig: Hintergrund der Karte ändern",
    "DG.Redo.map.changeBaseMap": "Wiederholen: Hintergrund der Karte ändern",
    "DG.Undo.textComponent.create": "Rückgängig: Textobjekt hinzufügen",
    "DG.Redo.textComponent.create": "Wiederholen: Textobjekt hinzufügen",
    "DG.Undo.textComponent.edit": "Rückgängig: Text editieren",
    "DG.Redo.textComponent.edit": "Wiederholen: Text editieren",
    "DG.Undo.sliderComponent.create": "Rückgängig: Regler hinzufügen",
    "DG.Redo.sliderComponent.create": "Wiederholen: Regler hinzufügen",
    "DG.Undo.slider.change": "Rückgängig: Wert des Reglers ändern",
    "DG.Redo.slider.change": "Wiederholen: Wert des Reglers ändern",
    "DG.Undo.slider.changeMultiples": "Undo change to slider multiples restriction",
    "DG.Redo.slider.changeMultiples": "Redo change to slider multiples restriction",
    "DG.Undo.slider.changeSpeed": "Undo change to slider max frames/sec",
    "DG.Redo.slider.changeSpeed": "Redo change to slider max frames/sec",
    "DG.Undo.slider.changeDirection": "Undo change to slider animation direction",
    "DG.Redo.slider.changeDirection": "Redo change to slider animation direction",
    "DG.Undo.slider.changeRepetition": "Undo change to slider animation repetition",
    "DG.Redo.slider.changeRepetition": "Redo change to slider animation repetition",
    "DG.Undo.graphComponent.create": "Rückgängig: Graph hinzufügen",
    "DG.Redo.graphComponent.create": "Wiederholen: Graph hinzufügen",
    "DG.Undo.dataContext.create": "Rückgängig: Datensatz erstellen",
    "DG.Redo.dataContext.create": "Wiederholen: Datensatz erstellen",
    "DG.Undo.data.deleteCases": "Rückgängig: Fälle löschen",
    "DG.Redo.data.deleteCases": "Wiederholen: Fälle löschen",
    "DG.Undo.component.close": "Undo closing component",
    "DG.Redo.component.close": "Redo closing component",
    "DG.Undo.component.minimize": "Undo minimizing component",
    "DG.Redo.component.minimize": "Redo minimizing component",
    "DG.Undo.dataContext.moveAttribute": "Rückgängig: Merkmal der Tabelle verschieben",
    "DG.Redo.dataContext.moveAttribute": "Wiederholen: Merkmal der Tabelle verschieben",
    "DG.DataContext.singleCaseName": "Fall",
    "DG.DataContext.pluralCaseName": "Fälle",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "Eine Kollektion",
    "DG.DataContext.collapsedRowString": "%@1 of %@2",
    "DG.DataContext.noData": "Keine Daten",
    "DG.DataContext.baseName": "Data_Set_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "Die Formel des Merkmals \"%@\" kann nicht geändert werden.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Ein neues Merkmal erstellen, um eine Formel zu verwenden",
    "DG.Formula.FuncCategoryArithmetic": "Arithmetik Funktionen",
    "DG.Formula.FuncCategoryConversion": "Andere Funktionen",
    "DG.Formula.FuncCategoryDateTime": "Datum/Zeit Funktionen",
    "DG.Formula.FuncCategoryLookup": "Such-Funktionen",
    "DG.Formula.FuncCategoryOther": "Andere Funktionen",
    "DG.Formula.FuncCategoryRandom": "Andere Funktionen",
    "DG.Formula.FuncCategoryStatistical": "Statistische Funktionen",
    "DG.Formula.FuncCategoryString": "Text Funktionen",
    "DG.Formula.FuncCategoryTrigonometric": "Trigonometrische Funktionen",
    "DG.Formula.DateLongMonthJanuary": "Januar",
    "DG.Formula.DateLongMonthFebruary": "Februar",
    "DG.Formula.DateLongMonthMarch": "März",
    "DG.Formula.DateLongMonthApril": "April",
    "DG.Formula.DateLongMonthMay": "Mai",
    "DG.Formula.DateLongMonthJune": "Juni",
    "DG.Formula.DateLongMonthJuly": "Juli",
    "DG.Formula.DateLongMonthAugust": "August",
    "DG.Formula.DateLongMonthSeptember": "September",
    "DG.Formula.DateLongMonthOctober": "Oktober",
    "DG.Formula.DateLongMonthNovember": "November",
    "DG.Formula.DateLongMonthDecember": "Dezember",
    "DG.Formula.DateShortMonthJanuary": "Jan",
    "DG.Formula.DateShortMonthFebruary": "Feb",
    "DG.Formula.DateShortMonthMarch": "Mär",
    "DG.Formula.DateShortMonthApril": "Apr",
    "DG.Formula.DateShortMonthMay": "Mai",
    "DG.Formula.DateShortMonthJune": "Jun",
    "DG.Formula.DateShortMonthJuly": "Jul",
    "DG.Formula.DateShortMonthAugust": "Aug",
    "DG.Formula.DateShortMonthSeptember": "Sep",
    "DG.Formula.DateShortMonthOctober": "Okt",
    "DG.Formula.DateShortMonthNovember": "Nov",
    "DG.Formula.DateShortMonthDecember": "Dez",
    "DG.Formula.DateLongDaySunday": "Sonntag",
    "DG.Formula.DateLongDayMonday": "Montag",
    "DG.Formula.DateLongDayTuesday": "Dienstag",
    "DG.Formula.DateLongDayWednesday": "Mittwoch",
    "DG.Formula.DateLongDayThursday": "Donnerstag",
    "DG.Formula.DateLongDayFriday": "Freitag",
    "DG.Formula.DateLongDaySaturday": "Samstag",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mär|apr|mai|jun|jul|aug|sep|okt|nov|dez)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Syntax error: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Unvollständiger Ausdruck",
    "DG.Formula.SyntaxErrorInvalidOperator": "Ungültiger Operator '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "invalid type(s) for '%@'",
    "DG.Formula.TypeError.description": "invalid type(s) for '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' wurde nicht erkannt",
    "DG.Formula.VarReferenceError.description": "Die Variable '%@' wurde nicht erkannt.",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "invalid reference to child attribute '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' is a child attribute that can only be referenced in an aggregate function",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' wurde nicht erkannt",
    "DG.Formula.FuncReferenceError.description": "Die Funktion '%@()' wurde nicht erkannt",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' erwartet 1 Argument",
    "DG.Formula.FuncArgsErrorSingle.description": "Die Funktion '%@()' erwartet 1 Argument",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' erwartet %@ Argumente",
    "DG.Formula.FuncArgsErrorPlural.description": "Die Funktion '%@()' erwartet %@ Argumente",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' erwartet %@-%@ Argumente",
    "DG.Formula.FuncArgsErrorRange.description": "Die Funktion '%@()' erwartet %@-%@ Argumente",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "Ausstehende Anfrage...",
    "DG.Formula.PendingRequest.description": "Ausstehende Anfrage...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "Anfrage fehlgeschlagen  (%@)",
    "DG.Formula.FailedRequest.description": "Anfrage fehlgeschlagen (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "boundaries pending...",
    "DG.Formula.PendingBoundaries.description": "boundaries pending...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "boundaries failed (%@)",
    "DG.Formula.FailedBoundaries.description": "boundaries failed (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': nicht erkannter Datensatz",
    "DG.Formula.LookupDataSetError.description": "Der Datensatz '%@' wurde nicht erkannt",
    "DG.Formula.LookupAttrError.message": "'%@' not found in data set '%@'",
    "DG.Formula.LookupAttrError.description": "Merkmal '%@' im Datensatz '%@' nicht gefunden",
    "DG.TableController.headerMenuItems.editAttribute": "Eigenschaften des Merkmals bearbeiten...",
    "DG.TableController.headerMenuItems.editFormula": "Formel bearbeiten...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Rerandomisieren",
    "DG.TableController.headerMenuItems.sortAscending": "Aufsteigend sortieren (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Absteigend sortieren (Z→A, 9→0)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Merkmal löschen",
    "DG.TableController.newAttrDlg.defaultAttrName": "neues_Merkm",
    "DG.TableController.newAttrDlg.attrNameHint": "Einen Namen eingeben für das neue Merkmal",
    "DG.TableController.newAttrDlg.formulaHint": "Eine Formel benutzen, um Werte dieses Merkmals zu berechnen, falls gewünscht",
    "DG.TableController.newAttrDlg.applyTooltip": "Das neue Merkmal definieren mit einem Namen und einer (optionalen) Formel",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Bitte einen Namen eingeben für das neue Merkmal",
    "DG.TableController.newAttrDialog.AttributesCategory": "Merkmale",
    "DG.TableController.newAttrDialog.SpecialCategory": "Spezial",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Globals",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Konstanten",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Funktionen",
    "DG.TableController.renameAttributeInvalidMsg": "Merkmalsnamen dürfen nicht leer sein",
    "DG.TableController.renameAttributeInvalidDesc": "Bitte einen gültigen Merkmalsnamen eingeben",
    "DG.TableController.renameAttributeDuplicateMsg": "Dieser Merkmalsname ist bereits vergeben",
    "DG.TableController.renameAttributeDuplicateDesc": "Bitte einen eindeutigen Merkmalsnamen eingeben",
    "DG.TableController.deleteAttribute.confirmMessage": "Das Merkmal '%@' löschen?",
    "DG.TableController.deleteAttribute.confirmDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Merkmal löschen",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Abbrechen",
    "DG.TableController.deleteDataSet.confirmMessage": "Diesen Datensatz unwiederbringlich löschen: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Datensatz löschen",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Abbrechen",
    "DG.TableController.attrEditor.precisionHint": "Anzahl der Stellen nach dem Komma",
    "DG.TableController.attrEditor.unitHint": "Einheit der Messung, falls angebbar",
    "DG.TableController.attrEditor.descriptionHint": "Das Merkmal beschreiben",
    "DG.TableController.setScoreDlg.applyTooltip": "Eine Formel für das Merkmal '%@' eingeben",
    "DG.TableController.setScoreDlg.formulaHint": "Eine Formel eingeben, um Werte dieses Merkmals zu berechnen",
    "DG.TableController.newAttributeTooltip": "Der Tabelle ein neues Merkmal hinzufügen",
    "DG.TableController.attributeEditor.title": "Eigenschaften des Merkmals",
    "DG.CaseTableDropTarget.dropMessage": "drop attribute to create new collection",
    "DG.CaseTable.defaultAttrName": "neuesMerkm",
    "DG.CaseTable.indexColumnName": "Index",
    "DG.CaseTable.indexColumnTooltip": "Zeilennummer (FallIndex) der Kollektion",
    "DG.CaseTable.indexMenu.insertCase": "Fall hinzufügen",
    "DG.CaseTable.indexMenu.insertCases": "Fälle hinzufügen",
    "DG.CaseTable.indexMenu.deleteCase": "Fall löschen",
    "DG.CaseTable.indexMenu.deleteCases": "Fälle löschen",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "kategorial",
    "DG.CaseTable.attribute.type.categorical": "kategorial",
    "DG.CaseTable.attribute.type.numeric": "numerisch",
    "DG.CaseTable.attribute.type.date": "Datum",
    "DG.CaseTable.attribute.type.qualitative": "qualitativ",
    "DG.CaseTable.attribute.type.boundary": "boundary",
    "DG.CaseTable.attributeEditor.name": "Name",
    "DG.CaseTable.attributeEditor.description": "Beschreibung",
    "DG.CaseTable.attributeEditor.type": "Typ",
    "DG.CaseTable.attributeEditor.unit": "Einheit",
    "DG.CaseTable.attributeEditor.precision": "Genauigkeit",
    "DG.CaseTable.attributeEditor.editable": "editierbar",
    "DG.CaseTable.insertCasesDialog.title": "Fälle hinzufügen",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# cases to insert:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "location:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "before",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "after",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Fälle einfügen",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Festgelegte Anzahl Fälle einfügen",
    "DG.CaseTableController.allTables": "Alle Tabellen",
    "DG.AttrFormView.attrNamePrompt": "Name des Merkmals:",
    "DG.AttrFormView.formulaPrompt": "Formel:",
    "DG.AttrFormView.operandMenuTitle": "--- Wert einfügen ---",
    "DG.AttrFormView.functionMenuTitle": "--- Funktion einfügen ---",
    "DG.AttrFormView.applyBtnTitle": "Bestätigen",
    "DG.AttrFormView.cancelBtnTitle": "Abbrechen",
    "DG.AttrFormView.cancelBtnTooltip": "Den Dialog ohne Änderungen verlassen",
    "DG.GuideConfigView.titlePrompt": "Guide Title",
    "DG.GuideConfigView.titleHint": "Activity Name",
    "DG.GuideConfigView.itemTitleHint": "Section Name",
    "DG.GuideConfigView.itemURLHint": "URL of section",
    "DG.GuideConfigView.okBtnTitle": "OK",
    "DG.GuideConfigView.okBtnToolTip": "Accept the Guide menu items",
    "DG.GuideConfigView.cancelBtnTitle": "Abbrechen",
    "DG.GuideConfigView.cancelBtnTooltip": "Dismiss the dialog without making any changes",
    "DG.GuideConfigView.httpWarning": "Die Adresse muss entweder mit http:// oder mit https:// starten",
    "DG.DataDisplayModel.rescaleToData": "Rescale to Data",
    "DG.DataDisplayModel.ShowConnectingLine": "Verbindungslinien zeigen",
    "DG.DataDisplayModel.HideConnectingLine": "Verbindungslinien verbergen",
    "DG.AxisView.emptyGraphCue": "Hier klicken oder ein Merkmal hierher ziehen",
    "DG.CellLinearAxisView.midPanelTooltip": "Drag to translate axis scale",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Drag to change axis lower bound",
    "DG.CellLinearAxisView.upperPanelTooltip": "Drag to change axis upper bound",
    "DG.PlotModel.mixup": "Graph mischen",
    "DG.PlotModel.showCount": "Anzahl zeigen",
    "DG.PlotModel.hideCount": "Anzahl verbergen",
    "DG.ScatterPlotModel.sumSquares": ",\nSumme der Quadrate = %@",
    "DG.ScatterPlotModel.rSquared": ",\nr^2 = %@",
    "DG.ScatterPlotModel.slopeIntercept": "%@ = %@ %@ %@ %@",
    "DG.ScatterPlotModel.infiniteSlope": "%@ = %@",
    "DG.ScatterPlotModel.slopeOnly": "Steigung = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "pro Jahr",
    "DG.ScatterPlotModel.daysLabel": "pro Tag",
    "DG.ScatterPlotModel.hoursLabel": "pro Stunde",
    "DG.ScatterPlotModel.minutesLabel": "pro Minute",
    "DG.ScatterPlotModel.secondsLabel": "pro Sekunde",
    "DG.LegendView.attributeTooltip": "Klicken, um das Legendenmerkmal zuändern",
    "DG.NumberToggleView.showAll": "Alle anzeigen –",
    "DG.NumberToggleView.hideAll": "Alle verbergen –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Last",
    "DG.NumberToggleView.showAllTooltip": "Click to show all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.hideAllTooltip": "Click to hide all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.enableLastModeTooltip": "Click to show last parent case only",
    "DG.NumberToggleView.disableLastModeTooltip": "Click to exit last parent case mode",
    "DG.NumberToggleView.indexTooltip": "Click to toggle visibility",
    "DG.PlottedAverageAdornment.meanValueTitle": "aMittel=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "Median=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SD, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "untere=%@\nQ1=%@\nMedian=%@\nQ3=%@\nobere=%@\nIQR=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Legende: %@",
    "DG.DataDisplayMenu.remove": "Merkmal entfernen",
    "DG.DataDisplayMenu.removeAttribute_x": "Entferne X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Entferne Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Entferne Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Entferne Legende: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Als kategorial behandeln",
    "DG.DataDisplayMenu.treatAsNumeric": "Als numerisch behandeln",
    "DG.DataDisplayMenu.hide": "Verbergen und Zeigen",
    "DG.DataDisplayMenu.hideSelectedPlural": "Ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Nicht ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideSelectedSing": "Ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.hideUnselectedSing": "Nicht ausgewählte Fälle verbergen",
    "DG.DataDisplayMenu.enableNumberToggle": "Show Parent Visibility Toggles",
    "DG.DataDisplayMenu.disableNumberToggle": "Hide Parent Visibility Toggles",
    "DG.DataDisplayMenu.showAll": "Alle Fälle anzeigen",
    "DG.DataDisplayMenu.snapshot": "Screenshot",
    "DG.GraphView.replaceAttribute": "Ersetze %@ durch %@",
    "DG.GraphView.addAttribute": "Merkmal %@ hinzufügen",
    "DG.GraphView.addToEmptyPlace": "Achse erstellen aus %@",
    "DG.GraphView.addToEmptyX": "X-Achse erstellen aus %@",
    "DG.GraphView.dropInPlot": "Color points by values of %@",
    "DG.GraphView.zoomTip": "Double-click to zoom in.\nShift-double-click to zoom out",
    "DG.GraphView.rescale": "Rescale to data",
    "DG.AxisView.labelTooltip": "—Click to change %@ axis attribute",
    "DG.AxisView.vertical": "senkrecht",
    "DG.AxisView.horizontal": "waagrecht",
    "DG.DataTip.connectingLine": "%@: %@\nmit %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formel",
    "DG.PlottedValue.namePrompt": "Plotted Value",
    "DG.PlottedValue.formulaPrompt": "Wert =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Plotted Function",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Type an expression e.g. x*x/30 - 50",
    "DG.MapView.showGrid": "Gitter zeigen",
    "DG.MapView.hideGrid": "Gitter verbergen",
    "DG.MapView.showPoints": "Punkte zeigen",
    "DG.MapView.hidePoints": "Punkte verbergen",
    "DG.MapView.marqueeHint": "Marquee tool—drag select points in map",
    "DG.MapView.gridControlHint": "Gittergröße ändern",
    "DG.Inspector.values": "Measure",
    "DG.Inspector.styles": "Format",
    "DG.Inspector.pointSize": "Point size:",
    "DG.Inspector.transparency": "Transparenz:",
    "DG.Inspector.color": "Farbe:",
    "DG.Inspector.legendColor": "Legendenfarbe:",
    "DG.Inspector.backgroundColor": "Hintergrundfarbe:",
    "DG.Inspector.stroke": "Stroke:",
    "DG.Inspector.rescale.toolTip": "Anzeige anpassen um alle Daten zu zeigen",
    "DG.Inspector.mixUp.toolTip": "Alle Punkte mischen",
    "DG.Inspector.hideShow.toolTip": "Alle Fälle zeigen oder ausgewählte/nicht ausgewählte Fälle verbergen",
    "DG.Inspector.delete.toolTip": "Ausgewählte oder nicht ausgewählte Fälle löschen",
    "DG.Inspector.sliderValues.toolTip": "Set slider animation direction, speed, …",
    "DG.Inspector.webViewEditURL.toolTip": "Edit the URL of the displayed web page",
    "DG.Inspector.selection.selectAll": "Alle Fälle auswählen",
    "DG.Inspector.selection.deleteSelectedCases": "Ausgewählte Fälle löschen",
    "DG.Inspector.selection.deleteUnselectedCases": "Nicht ausgewählte Fälle löschen",
    "DG.Inspector.deleteAll": "Alle Fälle löschen",
    "DG.Inspector.deleteDataSet": "Datensatz löschen und zerstören",
    "DG.Inspector.displayValues.toolTip": "Change what is shown along with the points",
    "DG.Inspector.displayStyles.toolTip": "Change the appearance of the display",
    "DG.Inspector.makeImage.toolTip": "Bild als png Datei speichern",
    "DG.Inspector.displayShow": "Zeigen...",
    "DG.Inspector.colorPicker.more": "mehr",
    "DG.Inspector.colorPicker.less": "weniger",
    "DG.Inspector.graphTransparency": "transparent",
    "DG.Inspector.graphCount": "Anzahl",
    "DG.Inspector.graphPercent": "Prozent",
    "DG.Inspector.graphRow": "Zeile",
    "DG.Inspector.graphColumn": "Spalte",
    "DG.Inspector.graphCell": "Zelle",
    "DG.Inspector.graphConnectingLine": "Linien verbinden",
    "DG.Inspector.graphMovableLine": "Bewegliche Linie",
    "DG.Inspector.graphInterceptLocked": "Intercept Locked",
    "DG.Inspector.graphPlottedFunction": "Plotted Function",
    "DG.Inspector.graphSquares": "Squares of Residuals",
    "DG.Inspector.graphLSRL": "Least Squares Line",
    "DG.Inspector.graphMovableValue": "Movable Value",
    "DG.Inspector.graphAdd": "Hinzufügen",
    "DG.Inspector.graphRemove": "Entfernen",
    "DG.Inspector.graphPlottedMean": "arithmetisches Mittel",
    "DG.Inspector.graphPlottedMedian": "Median",
    "DG.Inspector.graphPlottedStDev": "Standardabweichung",
    "DG.Inspector.graphPlottedIQR": "Interquartilsabstand",
    "DG.Inspector.graphPlottedBoxPlot": "Boxplot",
    "DG.Inspector.graphPlottedValue": "Plotted Value",
    "DG.Inspector.attributes.toolTip": "Make new attributes. Export case data.",
    "DG.Inspector.resize.toolTip": "Spaltengröße an Daten anpassen",
    "DG.Inspector.newAttribute": "New Attribute in %@...",
    "DG.Inspector.randomizeAllAttributes": "Alle rerandomisieren",
    "DG.Inspector.exportCaseData": "Export Case Data...",
    "DG.Inspector.mapGrid": "Gitter",
    "DG.Inspector.mapPoints": "Punkte",
    "DG.Inspector.mapLines": "Linien verbinden",
    "DG.GameController.continuityError": "Entschuldigung, nachdem die Spalten der Tabelle neu angeordnet wurden können keine neuen Daten akzeptiert werden.",
    "DG.GameView.loading": "Lädt",
    "DG.GameView.loadError": "Wenn dieser Text zu sehen ist, dann ist das Laden der URL möglicherweise fehlgeschlagen. Der Link kann in einem anderen Browser überprüft werden. Oder der Fehler kann hier berichtet werden: http://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "Sicher?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Ja, schließen",
    "DG.Component.closeComponent.cancelButtonTitle": "Abbrechen",
    "DG.GameController.confirmCloseDescription": "Wenn dies geschlossen wird, können möglicherweise keine weiteren Daten hinzugefügt werden.",
    "DG.WebView.defaultTitle": "Website",
    "DG.mainPage.exceptionMessage": "Ein Fehler ist aufgetreten. Seite neu laden (Fehler: %@)",
    "DG.fileMenu.provider.examples.displayName": "Beispieldokumente",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Plugin öffnen",
    "DG.Undo.graph.showMovablePoint": "Rückgängig: Beweglichen Punkt zeigen",
    "DG.Redo.graph.showMovablePoint": "Wiederholen: Beweglichen Punkt zeigen",
    "DG.Undo.graph.hideMovablePoint": "Rückgängig: Beweglichen Punkt verbergen",
    "DG.Redo.graph.hideMovablePoint": "Wiederholen: Beweglichen Punkt verbergen",
    "DG.Undo.graph.moveMovablePoint": "Rückgängig: Beweglichen Punkt bewegen",
    "DG.Redo.graph.moveMovablePoint": "Wiederholen: Beweglichen Punkt bewegen",
    "DG.DataDisplayMenu.copyAsImage": "Im Zeichenwerkzeug öffnen",
    "DG.DataDisplayMenu.exportImage": "Bild exportieren...",
    "DG.DataDisplayMenu.imageOfTitle": "Bild %@",
    "DG.Inspector.graphMovablePoint": "Beweglicher Punkt",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Falltabelle zu diesem Datensatz öffnen",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Neuen Datensatz erstellen",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Diesen Datensatz löschen und zerstören",
    "DG.Undo.graph.showAsBarChart": "Rückgängig: Punkte verschmelzen",
    "DG.Redo.graph.showAsBarChart": "Wiederholen: Punkte verschmelzen",
    "DG.Undo.graph.showAsDotChart": "Rückgängig: Säulen in Punkte verwandeln",
    "DG.Redo.graph.showAsDotChart": "Wiederholen: Säulen in Punkte verwandeln",
    "DG.CountAxisView.countLabel": "Anzahl",
    "DG.CountAxisView.countLabelDescription": "Anzahl Fälle der Säule dieser Achse",
    "DG.CountAxisView.percentLabel": "Prozent",
    "DG.CountAxisView.percentLabelDescription": "Prozent der Fälle in der Säule dieser Achse",
    "DG.BarChartModel.cellTipPlural": "%@ von %@ %@ (%@%) sind %@",
    "DG.BarChartModel.cellTipSingular": "%@ von %@ %@ (%@%) ist %@",
    "DG.Inspector.configuration": "Einstellung",
    "DG.Inspector.displayConfiguration.toolTip": "Einstellung zur Anzeige",
    "DG.Inspector.displayScale": "Skalieren...",
    "DG.Inspector.graphBarChart": "Punkte rechteckig verschmelzen",
    "DG.Locale.name.de": "Deutsch",
    "DG.Locale.name.en": "Englisch",
    "DG.Locale.name.es": "Spanisch",
    "DG.Locale.name.he": "Hebräisch",
    "DG.Locale.name.tr": "Türkisch",
    "DG.Locale.name.zh": "Chinesisch",
    "DG.Undo.graph.swapCategories": "Rückgängig: Kategorien anordnen",
    "DG.Redo.graph.swapCategories": "Wiederholen: Kategorien anordnen",
    "DG.TableController.collectionTitleText": "%@1 (%@2 cases)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 cases, %@3 set aside)",
    "DG.Inspector.setaside.setAsideSelectedCases": "Set Aside Selected Cases",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Set Aside Unselected Cases",
    "DG.Inspector.setaside.restoreSetAsideCases": "Restore %@ Set Aside Cases",
    "DG.DocumentController.caseCardTitle": "Case Card",
    "DG.DocumentController.toggleToCaseCard": "Switch to case card view of the data",
    "DG.DocumentController.toggleToCaseTable": "Switch to case table view of the data",
    "DG.CaseCard.indexString": "1 of %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ selected of %@ %@",
    "DG.CaseCard.summaryValues": "%@ values",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Select and show next case",
    "DG.CaseCard.navPrevCase": "Select and show previous case",
    "DG.CaseCard.navFirstCase": "Select and show first case",
    "DG.CaseCard.navLastCase": "Select and show last case",
    "DG.Undo.component.toggleTableToCard": "Undo changing case table to case card",
    "DG.Redo.component.toggleTableToCard": "Redo changing case table to case card",
    "DG.Undo.component.toggleCardToTable": "Undo changing case card to case table",
    "DG.Redo.component.toggleCardToTable": "Redo changing case card to case table",
    "DG.Undo.graph.addBackgroundImage": "Undo adding graph background image",
    "DG.Redo.graph.addBackgroundImage": "Redo adding graph background image",
    "DG.Undo.graph.removeBackgroundImage": "Undo removing graph background image",
    "DG.Redo.graph.removeBackgroundImage": "Redo removing graph background image",
    "DG.Undo.graph.lockBackgroundImage": "Undo locking background image to axes",
    "DG.Redo.graph.lockBackgroundImage": "Redo locking background image to axes",
    "DG.Undo.graph.unlockBackgroundImage": "Undo unlocking background image from axes",
    "DG.Redo.graph.unlockBackgroundImage": "Redo unlocking background image from axes",
    "DG.Undo.enableMeasuresForSelection": "Undo Show Measures For Selection",
    "DG.Redo.enableMeasuresForSelection": "Redo Show Measures For Selection",
    "DG.Undo.disableMeasuresForSelection": "Undo Hide Measures For Selection",
    "DG.Redo.disableMeasuresForSelection": "Redo Hide Measures For Selection",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Show Measures for Selection",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Hide Measures for Selection",
    "DG.DataDisplayMenu.addBackgroundImage": "Hintergrundbild hinzufügen",
    "DG.DataDisplayMenu.lockImageToAxes": "Hintergrundbild an Achsen ausrichten",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Unlock Background Image from Axes",
    "DG.DataDisplayMenu.removeBackgroundImage": "Remove Background Image",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Delete Formula (Keeping Values)",
    "DG.TableController.headerMenuItems.recoverFormula": "Recover Deleted Formula",
    "DG.Inspector.displayLayers.toolTip": "Change the appearance of the map layers",
    "DG.Inspector.layers": "Layers"
});
