SC.stringsFor("tr", {
    "DG.fileMenu.menuItem.newDocument": "Yeni",
    "DG.fileMenu.menuItem.openDocument": "Aç...",
    "DG.fileMenu.menuItem.closeDocument": "Kapat",
    "DG.fileMenu.menuItem.importFile": "İçe aktar",
    "DG.fileMenu.menuItem.revertTo": "Dönüştür...",
    "DG.fileMenu.menuItem.revertToOpened": "Son açılan versiyon",
    "DG.fileMenu.menuItem.revertToShared": "Paylaşılan görünümler",
    "DG.fileMenu.menuItem.saveDocument": "Kaydet...",
    "DG.fileMenu.menuItem.copyDocument": "Kopya Oluştur",
    "DG.fileMenu.menuItem.share": "Paylaş",
    "DG.fileMenu.menuItem.shareGetLink": "Paylaşılan görünümler bağlantısı",
    "DG.fileMenu.menuItem.shareUpdate": "Paylaşılan görünümleri güncelle",
    "DG.fileMenu.menuItem.renameDocument": "Yeniden adlandır",
    "DG.main.userEntryView.title": "Ne yapmak istiyorsun?",
    "DG.main.userEntryView.openDocument": "Dosya Aç veya Örnekleri Görüntüle",
    "DG.main.userEntryView.newDocument": "Yeni Dosya Aç",
    "DG.mainPage.mainPane.undoButton.title": "Geri Al",
    "DG.mainPage.mainPane.undoButton.toolTip": "Son yapılanı geri al",
    "DG.mainPage.mainPane.redoButton.title": "Yinele",
    "DG.mainPage.mainPane.redoButton.toolTip": "Son geri alınanı yinele",
    "DG.mainPage.mainPane.versionString": "Versiyon %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Üzgünüz, CODAP tarayıcınız tarafından desteklenmiyor. CODAP sadece Firefox 46+, Chrome 50+, Windows Edge 14+, ve Safari 10+ tarafından desteklenmektedir. Şu anda diğer tarayıcılar tarafından desteklenmemektedir.",
    "DG.mainPage.titleBar.saved": "Dosya Kaydedildi!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Versiyon %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Versiyon %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Verileri temizle...",
    "DG.AppController.resetData.toolTip": "Bu dosyadaki tüm verileri sil",
    "DG.AppController.resetData.warnMessage": "Bu dosyadaki tüm verileri gerçekten silmek istiyor musunuz?",
    "DG.AppController.resetData.warnDescription": "Bu işlem geri alınamaz.",
    "DG.AppController.resetData.okButtonTitle": "Evet, tüm verileri sil",
    "DG.AppController.resetData.cancelButtonTitle": "Hayır, verileri sakla",
    "DG.AppController.closeDocument.warnMessage": "Dosyayı kaydetmeden kapatmak istiyor musunuz?",
    "DG.AppController.closeDocument.warnDescription": "Bu işlem geri alınamaz.",
    "DG.AppController.closeDocument.okButtonTitle": "Kapat",
    "DG.AppController.closeDocument.cancelButtonTitle": "İptal et",
    "DG.AppController.beforeUnload.confirmationMessage": "Bu dosyada kaydedilmeyen değişiklikler var.",
    "DG.AppController.optionMenuItems.reportProblem": "Yorum Gönder...",
    "DG.AppController.optionMenuItems.viewWebPage": "İnternet sayfasını görüntüle...",
    "DG.AppController.optionMenuItems.configureGuide": "Rehberi Yapılandır...\n",
    "DG.AppController.optionMenuItems.about": "CODAP Hakkında...",
    "DG.AppController.optionMenuItems.releaseNotes": "Yenilikler",
    "DG.AppController.optionMenuItems.help": "Yardım...",
    "DG.AppController.optionMenuItems.toWebSite": "CODAP internet sayfası",
    "DG.AppController.exportDocument.prompt": "Dosya adı:",
    "DG.AppController.exportCaseData.prompt": "Verileri buradan dışarı aktar:",
    "DG.AppController.exportDocument.exportTitle": "Dışa aktar",
    "DG.AppController.exportDocument.exportTooltip": "Verileri bir dosyaya aktar",
    "DG.AppController.exportDocument.cancelTitle": "İptal et",
    "DG.AppController.exportDocument.cancelTooltip": "Dışa aktarımı iptal et",
    "DG.AppController.feedbackDialog.dialogTitle": "Yorum Yap",
    "DG.AppController.feedbackDialog.subHeaderText": "Yorumlarınız bizim için önemli!",
    "DG.AppController.feedbackDialog.messageText": "Ürünümüzü geliştirmemize yardımcı olun. Sorularınızı, isteklerinizi ve sistem hatalarını bize bildirin. Teşekkür ederiz!",
    "DG.AppController.feedbackDialog.subjectHint": "Yorumunuz ne hakkında",
    "DG.AppController.feedbackDialog.feedbackHint": "Ayrıntılar",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Gönder",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "İptal et",
    "DG.AppController.showWebSiteTitle": "CODAP Hakkında",
    "DG.AppController.showHelpTitle": "CODAP için Destek",
    "DG.AppController.showAboutTitle": "CODAP Hakkında",
    "DG.AppController.showReleaseNotesTitle": "CODAP Sürüm Notları",
    "DG.AppController.dropFile.error": "Hata: %@1",
    "DG.AppController.dropFile.unknownFileType": "Bu dosya türünü aktaramazsınız",
    "DG.AppController.validateDocument.missingRequiredProperty": "Gerekli özellik bulunamadı: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Beklenmeyen üst düzey özellik: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Çözümlenmemiş kimlik: %@1",
    "DG.AppController.validateDocument.parseError": "Belgede ayrıştırma hatası: %@1\n",
    "DG.AppController.validateDocument.invalidDocument": "Geçersiz JSON Dosyası: %@1",
    "DG.AppController.openDocument.error.general": "Dosya açılamadı",
    "DG.AppController.openDocument.error.invalid_format": "CODAP bu tür dosyaları çalıştıramıyor",
    "DG.AppController.createDataSet.initialAttribute": "Özellik",
    "DG.AppController.createDataSet.name": "Yeni Veri Seti",
    "DG.AppController.createDataSet.collectionName": "Durumlar",
    "DG.AppController.caseTableMenu.newDataSet": "-- yeni --",
    "DG.SingleTextDialog.okButton.title": "TAMAM",
    "DG.SingleTextDialog.cancelButton.title": "İptal et",
    "DG.SingleTextDialog.cancelButton.toolTip": "Herhangi bir değişiklik yapmadan iletişim kutusunu kapat",
    "DG.DocumentController.calculatorTitle": "Hesap makinesi",
    "DG.DocumentController.caseTableTitle": "Durum tablosu",
    "DG.DocumentController.graphTitle": "Grafik",
    "DG.DocumentController.sliderTitle": "Kaydırıcı",
    "DG.DocumentController.textTitle": "Metin",
    "DG.DocumentController.mapTitle": "Harita",
    "DG.DocumentController.enterURLPrompt": "Görüntülenecek internet sayfasının URL'sini girin",
    "DG.DocumentController.enterViewWebPageOKTip": "URL tarafından sağlanan internet sayfasından görüntüler",
    "DG.Document.defaultDocumentName": "Başlıksız Dosya",
    "DG.Document.documentName.toolTip": "Dosya adını düzenlemek için tıklayın",
    "DG.SliderView.thumbView.toolTip": "Kaydırıcının değerini değiştirmek için sürükleyin",
    "DG.SliderView.startButton.toolTip": "Animasyonu başlat/durdur",
    "DG.ToolButtonData.tableButton.title": "Tablolar",
    "DG.ToolButtonData.tableButton.toolTip": "Her veri için bir durum tablosu aç (ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Grafik",
    "DG.ToolButtonData.graphButton.toolTip": "Grafik oluştur (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Kaydırıcı",
    "DG.ToolButtonData.sliderButton.toolTip": "Kaydırıcı oluştur (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "Hesapla",
    "DG.ToolButtonData.calcButton.toolTip": "Hesap makinesini aç/kapat (ctrl-alt-c)",
    "DG.ToolButtonData.textButton.title": "Metin",
    "DG.ToolButtonData.textButton.toolTip": "Bir metin nesnesi oluşturun (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "Harita",
    "DG.ToolButtonData.mapButton.toolTip": "Bir harita oluşturun",
    "DG.ToolButtonData.optionMenu.title": "Seçenekler",
    "DG.ToolButtonData.optionMenu.toolTip": "İnternet sayfasını görüntüle, rehberi yapılandır...",
    "DG.ToolButtonData.tileListMenu.title": "Başlıklar",
    "DG.ToolButtonData.tileListMenu.toolTip": "Dosyadaki başlıkların listesini göster",
    "DG.ToolButtonData.guideMenu.title": "Rehber",
    "DG.ToolButtonData.guideMenu.toolTip": "Rehberi bu aktivitede göster ve rehberde gezin",
    "DG.ToolButtonData.guideMenu.showGuide": "Rehberi Göster",
    "DG.ToolButtonData.help.title": "Yardım",
    "DG.ToolButtonData.help.toolTip": "CODAP Destek, CODAP Projesi Hakkında",
    "DG.Slider.multiples": "Çarpanları Sınırla:",
    "DG.Slider.maxPerSecond": "Saniyedeki Maksimum Animasyon Karesi:",
    "DG.Slider.direction": "Animasyon Yönü:",
    "DG.Slider.backAndForth": "Geri ve İleri",
    "DG.Slider.lowToHigh": "Düşükten Yükseğe",
    "DG.Slider.highToLow": "Yüksekten Düşüğe",
    "DG.Slider.mode": "Animasyon Tekrarı:",
    "DG.Slider.nonStop": "Durmadan",
    "DG.Slider.onceOnly": "Sadece bir kez",
    "DG.Undo.exceptionOccurred": "Geri almaya çalışılırken bir hata oluştu.",
    "DG.Redo.exceptionOccurred": "Yinelemeye çalışılırken bir hata oluştu.",
    "DG.Undo.componentMove": "Bileşeni hareket ettirmeyi geri al",
    "DG.Redo.componentMove": "Bileşeni hareket ettirmeyi yinele",
    "DG.Undo.componentResize": "Bileşeni yeniden boyutlandırma işlemini geri al",
    "DG.Redo.componentResize": "Bileşeni yeniden boyutlandırmayı yinele",
    "DG.Undo.axisDilate": "Ekseni yeniden ölçeklendirmeyi geri al",
    "DG.Redo.axisDilate": "Ekseni yeniden ölçeklendirmeyi yinele",
    "DG.Undo.axisRescaleFromData": "Ekseni yeniden ölçeklendirmeyi geri al",
    "DG.Redo.axisRescaleFromData": "Ekseni yeniden ölçeklendirmeyi yinele",
    "DG.Undo.axisDrag": "Ekseni sürüklemeyi geri al",
    "DG.Redo.axisDrag": "Ekseni sürüklemeyi yinele",
    "DG.Undo.axisAttributeChange": "Eksen özelliğini değiştirmeyi geri al",
    "DG.Redo.axisAttributeChange": "Eksen özelliğini değiştirmeyi yinele",
    "DG.Undo.axisAttributeAdded": "Eksen özelliği eklemeyi geri al",
    "DG.Redo.axisAttributeAdded": "Eksen özelliği eklemeyi yinele",
    "DG.Undo.toggleComponent.add.calcView": "Hesap makinesini göstermeyi geri al",
    "DG.Redo.toggleComponent.add.calcView": "Hesap makinesini göstermeyi yinele",
    "DG.Undo.toggleComponent.delete.calcView": "Hesap makinesini gizleme işlemini geri al",
    "DG.Redo.toggleComponent.delete.calcView": "Hesap makinesini gizleme işlemini yinele",
    "DG.Undo.caseTable.open": "Durum tablolarını göstermeyi geri al",
    "DG.Redo.caseTable.open": "Durum tablolarını göstermeyi yinele",
    "DG.Undo.caseTable.editAttribute": "Durum tablosu özelliğini düzenleme işlemini geri al",
    "DG.Redo.caseTable.editAttribute": "Durum tablosu özelliğini düzenleme işlemini yinele",
    "DG.Undo.caseTable.createAttribute": "Durum tablosu özelliği oluşturmayı geri al",
    "DG.Redo.caseTable.createAttribute": "Durum tablosu özelliği oluşturmayı yinele",
    "DG.Undo.caseTable.editAttributeFormula": "Durum tablosu özellik formülünü düzenleme işlemini geri al",
    "DG.Redo.caseTable.editAttributeFormula": "Durum tablosu özellik formülünü düzenleme işlemini yinele",
    "DG.Undo.caseTable.editCellValue": "Durum tablosu hücre değerini düzenleme işlemini geri al",
    "DG.Redo.caseTable.editCellValue": "Durum tablosu hücre değerini düzenleme işlemini yinele",
    "DG.Undo.caseTable.sortCases": "Durumları sıralamayı geri al",
    "DG.Redo.caseTable.sortCases": "Durumları sıralamayı yinele",
    "DG.Undo.caseTable.deleteAttribute": "Durum tablosu özelliği silmeyi geri al",
    "DG.Redo.caseTable.deleteAttribute": "Durum tablosu özelliği silmeyi yinele",
    "DG.Undo.caseTable.createCollection": "Yeni koleksiyon oluşturmayı geri al",
    "DG.Redo.caseTable.createCollection": "Yeni koleksiyon oluşturmayı yinele",
    "DG.Undo.caseTable.collectionNameChange": "Koleksiyonu yeniden adlandırmayı geri al",
    "DG.Redo.caseTable.collectionNameChange": "Koleksiyonu yeniden adlandırmayı yinele",
    "DG.Undo.caseTable.createNewCase": "Yeni durum oluşturmayı geri al",
    "DG.Redo.caseTable.createNewCase": "Yeni durum oluşturmayı yinele",
    "DG.Undo.caseTable.insertCases": "Durum eklemeyi geri al",
    "DG.Redo.caseTable.insertCases": "Durum eklemeyi yinele",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Tabloları görüntüle/gizleyi geri al",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Tabloları görüntüle/gizleyi yinele",
    "DG.Undo.caseTable.expandCollapseOneCase": "Bir grubun genişleme veya yığılmasını geri al",
    "DG.Redo.caseTable.expandCollapseOneCase": "Bir grubun genişleme veya yığılmasını yinele",
    "DG.Undo.caseTable.resizeColumns": "Tüm sütunları otomatik olarak yeniden boyutlandırmayı geri al",
    "DG.Redo.caseTable.resizeColumns": "Tüm sütunları otomatik olarak yeniden boyutlandırmayı yinele",
    "DG.Undo.document.share": "Dosyayı paylaşmayı geri al",
    "DG.Redo.document.share": "Dosyayı paylaşmayı yinele",
    "DG.Undo.document.unshare": "Dosyayı paylaşımını durdurmayı geri al",
    "DG.Redo.document.unshare": "Dosyayı paylaşımını durdurmayı yinele",
    "DG.Undo.game.add": "Dosyaya oyun eklemeyi geri al",
    "DG.Redo.game.add": "Dosyaya oyun eklemeyi yinele",
    "DG.Undo.graph.showCount": "Sayımı gösteri geri al",
    "DG.Redo.graph.showCount": "Sayımı gösteri yinele",
    "DG.Undo.graph.hideCount": "Sayımı saklayı geri al",
    "DG.Redo.graph.hideCount": "Sayımı saklayı yinele",
    "DG.Undo.graph.showPercent": "Yüzdeleri gösteri geri al",
    "DG.Redo.graph.showPercent": "Yüzdeleri gösteri yinele",
    "DG.Undo.graph.hidePercent": "Yüzdeleri saklayı geri al",
    "DG.Redo.graph.hidePercent": "Yüzdeleri saklayı yinele",
    "DG.Undo.graph.showMovableLine": "Hareketli hattın gösterilmesini geri al",
    "DG.Redo.graph.showMovableLine": "Hareketli hattın gösterilmesini yinele",
    "DG.Undo.graph.hideMovableLine": "Hareketli hattın saklanmasını geri al",
    "DG.Redo.graph.hideMovableLine": "Hareketli hattın saklanmasını yinele",
    "DG.Undo.graph.lockIntercept": "Doğruların kesişimini kilitlemeyi geri al",
    "DG.Redo.graph.lockIntercept": "Doğruların kesişimini kilitlemeyi yinele",
    "DG.Undo.graph.unlockIntercept": "Doğruların kesişimi kilidini açmayı geri al",
    "DG.Redo.graph.unlockIntercept": "Doğruların kesişimi kilidini açmayı yinele",
    "DG.Undo.graph.showPlotFunction": "Çizilen fonksiyonu göstermeyi geri al",
    "DG.Redo.graph.showPlotFunction": "Çizilen fonksiyonu göstermeyi yinele",
    "DG.Undo.graph.hidePlotFunction": "Çizilen fonksiyonu saklamayı geri al",
    "DG.Redo.graph.hidePlotFunction": "Çizilen fonksiyonu saklamayı yinele",
    "DG.Undo.graph.changePlotFunction": "Çizilen fonksiyonu değiştirmeyi geri al",
    "DG.Redo.graph.changePlotFunction": "Çizilen fonksiyonu değiştirmeyi yinele",
    "DG.Undo.graph.showPlotValue": "Çizilen değeri göstermeyi geri al",
    "DG.Redo.graph.showPlotValue": "Çizilen değeri göstermeyi yinele",
    "DG.Undo.graph.hidePlotValue": "Çizilen değeri saklamayı geri al",
    "DG.Redo.graph.hidePlotValue": "Çizilen değeri saklamayı yinele",
    "DG.Undo.graph.changePlotValue": "Çizilen değeri değiştirmeyi geri al",
    "DG.Redo.graph.changePlotValue": "Çizilen değeri değiştirmeyi yinele",
    "DG.Undo.graph.showConnectingLine": "Bağlantı doğrusunu göstermeyi geri al",
    "DG.Redo.graph.showConnectingLine": "Bağlantı doğrusunu göstermeyi yinele",
    "DG.Undo.graph.hideConnectingLine": "Bağlantı doğrusunu saklamayı geri al",
    "DG.Redo.graph.hideConnectingLine": "Bağlantı doğrusunu saklamayı yinele",
    "DG.Undo.graph.showLSRL": "En küçük kareler çizgisini göstermeyi geri al",
    "DG.Redo.graph.showLSRL": "En küçük kareler çizgisini göstermeyi yinele",
    "DG.Undo.graph.hideLSRL": "En küçük kareler çizgisini saklamayı geri al",
    "DG.Redo.graph.hideLSRL": "En küçük kareler çizgisini saklamayı yinele",
    "DG.Undo.graph.showSquares": "Kareleri göstermeyi geri al",
    "DG.Redo.graph.showSquares": "Kareleri göstermeyi yinele",
    "DG.Undo.graph.hideSquares": "Kareleri saklamayı geri al",
    "DG.Redo.graph.hideSquares": "Kareleri saklamayı yinele",
    "DG.Undo.graph.showPlottedMean": "Ortalamayı göstermeyi geri al",
    "DG.Redo.graph.showPlottedMean": "Ortalamayı göstermeyi yinele",
    "DG.Undo.graph.hidePlottedMean": "Ortalamayı saklamayı geri al",
    "DG.Redo.graph.hidePlottedMean": "Ortalamayı saklamayı yinele",
    "DG.Undo.graph.showPlottedMedian": "Ortancayı göstermeyi geri al",
    "DG.Redo.graph.showPlottedMedian": "Ortancayı göstermeyi yinele",
    "DG.Undo.graph.hidePlottedMedian": "Ortancayı saklamayı geri al",
    "DG.Redo.graph.hidePlottedMedian": "Ortancayı saklamayı yinele",
    "DG.Undo.graph.showPlottedStDev": "Standart sapmayı göstermeyi geri al",
    "DG.Redo.graph.showPlottedStDev": "Standart sapmayı göstermeyi yinele",
    "DG.Undo.graph.hidePlottedStDev": "Standart sapmayı saklamayı geri al",
    "DG.Redo.graph.hidePlottedStDev": "Standart sapmayı saklamayı yinele",
    "DG.Undo.graph.showPlottedIQR": "Çeyrekler arası aralığı göstermeyi geri al",
    "DG.Redo.graph.hidePlottedIQR": "Çeyrekler arası aralığı saklamayı yinele",
    "DG.Undo.graph.hidePlottedIQR": "Çeyrekler arası aralığı saklamayı geri al",
    "DG.Redo.graph.showPlottedIQR": "Çeyrekler arası aralığı göstermeyi yinele",
    "DG.Undo.graph.addMovableValue": "Taşınabilir değer eklemeyi geri al",
    "DG.Redo.graph.addMovableValue": "Taşınabilir değer eklemeyi yinele",
    "DG.Undo.graph.removeMovableValue": "Taşınabilir değeri kaldırmayı geri al",
    "DG.Redo.graph.removeMovableValue": "Taşınabilir değeri kaldırmayı yinele",
    "DG.Undo.graph.moveMovableValue": "Taşınabilir değeri değiştirmeyi geri al",
    "DG.Redo.graph.moveMovableValue": "Taşınabilir değeri değiştirmeyi yinele",
    "DG.Undo.graph.changePointColor": "Verilerin rengini değiştirmeyi geri al",
    "DG.Redo.graph.changePointColor": "Verilerin rengini değiştirmeyi yinele",
    "DG.Undo.graph.changeStrokeColor": "Fırça rengini değiştirmeyi geri al",
    "DG.Redo.graph.changeStrokeColor": "Fırça rengini değiştirmeyi yinele",
    "DG.Undo.graph.changePointSize": "Nokta büyüklüğünü değiştirmeyi geri al",
    "DG.Redo.graph.changePointSize": "Nokta büyüklüğünü değiştirmeyi yinele",
    "DG.Undo.graph.changeAttributeColor": "Özellik rengini değiştirmeyi geri al",
    "DG.Redo.graph.changeAttributeColor": "Özellik rengini değiştirmeyi yinele",
    "DG.Undo.graph.changeBackgroundColor": "Grafik arka plan rengini değiştirmeyi geri al",
    "DG.Redo.graph.changeBackgroundColor": "Grafik arka plan rengini değiştirmeyi yinele",
    "DG.Undo.graph.toggleTransparent": "Grafik saydamlığını değiştirmeyi geri al",
    "DG.Redo.graph.toggleTransparent": "Grafik saydamlığını değiştirmeyi yinele",
    "DG.Undo.guide.show": "Rehberi göstermeyi geri al",
    "DG.Redo.guide.show": "Rehberi göstermeyi yinele",
    "DG.Undo.guide.navigate": "Rehber sayfasını değiştirmeyi geri al",
    "DG.Redo.guide.navigate": "Rehber sayfasını değiştirmeyi yinele",
    "DG.Undo.hideSelectedCases": "Seçili durumları gizlemeyi geri al",
    "DG.Redo.hideSelectedCases": "Seçili durumları gizlemeyi yinele",
    "DG.Undo.hideUnselectedCases": "Seçili olmayan durumları gizlemeyi geri al",
    "DG.Redo.hideUnselectedCases": "Seçili olmayan durumları gizlemeyi yinele",
    "DG.Undo.enableNumberToggle": "Ana Görünüm Ayarlarını Gösteri geri al",
    "DG.Redo.enableNumberToggle": "Ana Görünüm Ayarlarını Gösteri yinele",
    "DG.Undo.disableNumberToggle": "Ana Görünüm Ayarlarını gizlemeyi geri al",
    "DG.Redo.disableNumberToggle": "Ana Görünüm Ayarlarını gizlemeyi yinele",
    "DG.Undo.interactiveUndoableAction": "Etkileşimdeki bir eylemi geri al",
    "DG.Redo.interactiveUndoableAction": "Etkileşimdeki bir eylemi yinele",
    "DG.Undo.showAllCases": "Tüm durumları gösteri geri al",
    "DG.Redo.showAllCases": "Tüm durumları gösteri yinele",
    "DG.Undo.map.create": "Harita eklemeyi geri al",
    "DG.Redo.map.create": "Harita eklemeyi yinele",
    "DG.Undo.map.fitBounds": "Harita boyutlandırmayı geri al",
    "DG.Redo.map.fitBounds": "Harita boyutlandırmayı yinele",
    "DG.Undo.map.pan": "Haritada gezinmeyi geri al",
    "DG.Redo.map.pan": "Haritada gezinmeyi yinele",
    "DG.Undo.map.zoom": "Haritaya yakınlaşmayı geri al",
    "DG.Redo.map.zoom": "Haritaya yakınlaşmayı yinele",
    "DG.Undo.map.showGrid": "Haritada kareleri göstermeyi geri al",
    "DG.Redo.map.showGrid": "Haritada kareleri göstermeyi yinele",
    "DG.Undo.map.hideGrid": "Haritada kareleri gizlemeyi geri al",
    "DG.Redo.map.hideGrid": "Haritada kareleri gizlemeyi yinele",
    "DG.Undo.map.changeGridSize": "Harita karelerinin büyüklüğünü değiştirmeyi geri al",
    "DG.Redo.map.changeGridSize": "Harita karelerinin büyüklüğünü değiştirmeyi yinele",
    "DG.Undo.map.showPoints": "Haritada noktaları göstermeyi geri al",
    "DG.Redo.map.showPoints": "Haritada noktaları göstermeyi yinele",
    "DG.Undo.map.hidePoints": "Haritada noktaları gizlemeyi geri al",
    "DG.Redo.map.hidePoints": "Haritada noktaları gizlemeyi yinele",
    "DG.Undo.map.showLines": "Harita çizgilerini göstermeyi geri al",
    "DG.Redo.map.showLines": "Harita çizgilerini göstermeyi yinele",
    "DG.Undo.map.hideLines": "Harita çizgilerini gizlemeyi geri al",
    "DG.Redo.map.hideLines": "Harita çizgilerini gizlemeyi yinele",
    "DG.Undo.map.changeBaseMap": "Harita arka planını değiştirmeyi geri al",
    "DG.Redo.map.changeBaseMap": "Harita arka planını değiştirmeyi yinele",
    "DG.Undo.textComponent.create": "Bir metin objesi eklemeyi geri al",
    "DG.Redo.textComponent.create": "Bir metin objesi eklemeyi yinele",
    "DG.Undo.textComponent.edit": "Metni değiştirmeyi geri al",
    "DG.Redo.textComponent.edit": "Metni değiştirmeyi yinele",
    "DG.Undo.sliderComponent.create": "Kaydırıcı eklemeyi geri al",
    "DG.Redo.sliderComponent.create": "Kaydırıcı eklemeyi yinele",
    "DG.Undo.slider.change": "Kaydırıcı değeri değişimini geri al",
    "DG.Redo.slider.change": "Kaydırıcı değeri değişimini yinele",
    "DG.Undo.slider.changeMultiples": "Kaydırıcı katlarını değiştirmeyi geri al",
    "DG.Redo.slider.changeMultiples": "Kaydırıcı katlarını değiştirmeyi yinele",
    "DG.Undo.slider.changeSpeed": "Saniyedeki maksimum animasyon karesini değiştirmeyi geri al",
    "DG.Redo.slider.changeSpeed": "Saniyedeki maksimum animasyon karesini değiştirmeyi yinele",
    "DG.Undo.slider.changeDirection": "Kaydırıcı animasyon yönünü değiştirmeyi geri al",
    "DG.Redo.slider.changeDirection": "Kaydırıcı animasyon yönünü değiştirmeyi yinele",
    "DG.Undo.slider.changeRepetition": "Kaydırıcı animasyon tekrarını değiştirmeyi geri al",
    "DG.Redo.slider.changeRepetition": "Kaydırıcı animasyon tekrarını değiştirmeyi yinele",
    "DG.Undo.graphComponent.create": "Grafik eklemeyi geri al",
    "DG.Redo.graphComponent.create": "Grafik eklemeyi yinele",
    "DG.Undo.dataContext.create": "Bir veri seti oluşturmayı geri al",
    "DG.Redo.dataContext.create": "Bir veri seti oluşturmayı yinele",
    "DG.Undo.data.deleteCases": "Durumları silmeyi geri al",
    "DG.Redo.data.deleteCases": "Durumları silmeyi yinele",
    "DG.Undo.component.close": "Kapatma düğmesini geri al",
    "DG.Redo.component.close": "Kapatma düğmesini yinele",
    "DG.Undo.component.minimize": "Küçültme düğmesini geri al",
    "DG.Redo.component.minimize": "Küçültme düğmesini yinele",
    "DG.Undo.dataContext.moveAttribute": "Durum tablosu özelliğini değiştirmeyi geri al",
    "DG.Redo.dataContext.moveAttribute": "Durum tablosu özelliğini değiştirmeyi yinele",
    "DG.DataContext.singleCaseName": "Durum",
    "DG.DataContext.pluralCaseName": "Durumlar",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "bir koleksiyon",
    "DG.DataContext.collapsedRowString": "%@1 arasında %@2",
    "DG.DataContext.noData": "Veri Yok",
    "DG.DataContext.baseName": "Veri_Seti_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "\"% @\" özelliği için formül düzenlenemez.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Bir formül oluşturabilmek için yeni bir özellik tanımlayın.",
    "DG.Formula.FuncCategoryArithmetic": "Aritmetik İşlemler",
    "DG.Formula.FuncCategoryConversion": "Diğer İşlemler",
    "DG.Formula.FuncCategoryDateTime": "Gün/Saat İşlemleri",
    "DG.Formula.FuncCategoryLookup": "Arama İşlemleri",
    "DG.Formula.FuncCategoryOther": "Diğer İşlemler",
    "DG.Formula.FuncCategoryRandom": "Diğer İşlemler",
    "DG.Formula.FuncCategoryStatistical": "İstatistiksel İşlemler",
    "DG.Formula.FuncCategoryString": "Dizi İşlemleri",
    "DG.Formula.FuncCategoryTrigonometric": "Trigonometrik İşlemler",
    "DG.Formula.DateLongMonthJanuary": "Ocak",
    "DG.Formula.DateLongMonthFebruary": "Şubat",
    "DG.Formula.DateLongMonthMarch": "Mart",
    "DG.Formula.DateLongMonthApril": "Nisan",
    "DG.Formula.DateLongMonthMay": "Mayıs",
    "DG.Formula.DateLongMonthJune": "Haziran",
    "DG.Formula.DateLongMonthJuly": "Temmuz",
    "DG.Formula.DateLongMonthAugust": "Ağustos",
    "DG.Formula.DateLongMonthSeptember": "Eylül",
    "DG.Formula.DateLongMonthOctober": "Ekim",
    "DG.Formula.DateLongMonthNovember": "Kasım",
    "DG.Formula.DateLongMonthDecember": "Aralık",
    "DG.Formula.DateShortMonthJanuary": "Oca",
    "DG.Formula.DateShortMonthFebruary": "Şub",
    "DG.Formula.DateShortMonthMarch": "Mar",
    "DG.Formula.DateShortMonthApril": "Nis",
    "DG.Formula.DateShortMonthMay": "May",
    "DG.Formula.DateShortMonthJune": "Haz",
    "DG.Formula.DateShortMonthJuly": "Tem",
    "DG.Formula.DateShortMonthAugust": "Ağu",
    "DG.Formula.DateShortMonthSeptember": "Eyl",
    "DG.Formula.DateShortMonthOctober": "Eki",
    "DG.Formula.DateShortMonthNovember": "Kas",
    "DG.Formula.DateShortMonthDecember": "Ara",
    "DG.Formula.DateLongDaySunday": "Pazar",
    "DG.Formula.DateLongDayMonday": "Pazartesi",
    "DG.Formula.DateLongDayTuesday": "Salı",
    "DG.Formula.DateLongDayWednesday": "Çarşamba",
    "DG.Formula.DateLongDayThursday": "Perşembe",
    "DG.Formula.DateLongDayFriday": "Cuma",
    "DG.Formula.DateLongDaySaturday": "Cumartesi",
    "DG.Utilities.date.localDatePattern": " (?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?)) ",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?) ",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ](?:[0-2]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d{3,6})?)(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Sözdizimi hatası: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Eksik ifade",
    "DG.Formula.SyntaxErrorInvalidOperator": "Geçersiz operatör '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "'%@' için geçersiz tür",
    "DG.Formula.TypeError.description": "'%@' için geçersiz tür",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' tanımlanamadı",
    "DG.Formula.VarReferenceError.description": "'%@' değişkeni tanımlanamadı",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "'%@' alt özelliği için geçersiz başvuru",
    "DG.Formula.HierReferenceError.description": "'%@' bir alt özelliktir ve sadece toplu bir işlevde kullanılabilir.",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' tanımlanamadı",
    "DG.Formula.FuncReferenceError.description": "'%@()' özelliği tanımlanamadı",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' 1 değişken gerektiriyor",
    "DG.Formula.FuncArgsErrorSingle.description": "'%@()' fonksiyonu 1 değişken gerektiriyor",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' gerektiriyor %@ değişken",
    "DG.Formula.FuncArgsErrorPlural.description": "'%@()' fonksiyonu %@ değişken gerektiriyor",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' gerektiriyor %@-%@ değişken",
    "DG.Formula.FuncArgsErrorRange.description": "'%@()' fonksiyonu %@-%@ değişken gerektiriyor",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "Bekleyen istek...",
    "DG.Formula.PendingRequest.description": "Bekleyen istek...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "İstek başarısız oldu (%@)",
    "DG.Formula.FailedRequest.description": "İstek başarısız oldu (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "Sınırlar bekliyor...",
    "DG.Formula.PendingBoundaries.description": "Sınırlar bekliyor...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "Sınırlar başarısız oldu (%@)",
    "DG.Formula.FailedBoundaries.description": "Sınırlar başarısız oldu (%@)",
    "DG.Formula.LookupDataSetError.message": "Tanınmayan veri seti: '%@'",
    "DG.Formula.LookupDataSetError.description": "'%@' veri seti tanınmadı",
    "DG.Formula.LookupAttrError.message": "'%@' bulunamadı '%@' veri setinin içinde",
    "DG.Formula.LookupAttrError.description": "'%@' özelliği '%@' veri setinin içinde bulunamadı",
    "DG.TableController.headerMenuItems.editAttribute": "Özellik Değerlerini Düzenle\n",
    "DG.TableController.headerMenuItems.editFormula": "Formülü Düzenle",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Tekrar dağıt",
    "DG.TableController.headerMenuItems.sortAscending": "Artan Şekilde Sırala (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Azalan Şekilde Sırala (9→0, Z→A)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Özelliği Sil",
    "DG.TableController.newAttrDlg.defaultAttrName": "yeni_özellik",
    "DG.TableController.newAttrDlg.attrNameHint": "Yeni özellik için bir ad girin",
    "DG.TableController.newAttrDlg.formulaHint": "Bu özelliğin değerlerini hesaplamak için gerekiyorsa bir formül yazın",
    "DG.TableController.newAttrDlg.applyTooltip": "Yeni özelliği ad ve formül (isteğe bağlı) kullanarak tanımlayın",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Lütfen yeni özellik için bir ad girin",
    "DG.TableController.newAttrDialog.AttributesCategory": "Özellikler",
    "DG.TableController.newAttrDialog.SpecialCategory": "Özel",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Değerler",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Sabitler",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Fonksiyonlar",
    "DG.TableController.renameAttributeInvalidMsg": "Özellik adları boş bırakılamaz",
    "DG.TableController.renameAttributeInvalidDesc": "Lütfen geçerli bir özellik adı girin",
    "DG.TableController.renameAttributeDuplicateMsg": "Aynı isimde bir özellik zaten var",
    "DG.TableController.renameAttributeDuplicateDesc": "Lütfen yeni bir özellik adı girin",
    "DG.TableController.deleteAttribute.confirmMessage": "Özelliği silin '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "Bu işlem geri alınamaz.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Özelliği Sil",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "İptal Et",
    "DG.TableController.deleteDataSet.confirmMessage": "Bu veri setini sil ve yok et: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Bu işlem geri alınamaz.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Veri Setini Sil",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "İptal Et",
    "DG.TableController.attrEditor.unitHint": "Varsa, ölçü birimi",
    "DG.TableController.attrEditor.descriptionHint": "Özelliği tanımla",
    "DG.TableController.setScoreDlg.applyTooltip": "'%@' özelliği için formülü ayarla",
    "DG.TableController.setScoreDlg.formulaHint": "Bu niteliğin değerlerini hesaplamak için bir formül girin",
    "DG.TableController.newAttributeTooltip": "Bu tabloya yeni bir özellik girin",
    "DG.TableController.attributeEditor.title": "Özellik Değerleri",
    "DG.CaseTableDropTarget.dropMessage": "Yeni bir koleksiyon oluşturmak için özelliği çıkarın",
    "DG.CaseTable.defaultAttrName": "yeniÖzellik",
    "DG.CaseTable.indexColumnName": "indeks",
    "DG.CaseTable.indexColumnTooltip": "Koleksiyon içindeki sıra numarası (durumİndeksi)",
    "DG.CaseTable.indexMenu.insertCase": "Durum Ekle",
    "DG.CaseTable.indexMenu.insertCases": "Durumları Ekle...",
    "DG.CaseTable.indexMenu.deleteCase": "Durumu Sil",
    "DG.CaseTable.indexMenu.deleteCases": "Durumları Sil",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "kategorik",
    "DG.CaseTable.attribute.type.categorical": "kategorik",
    "DG.CaseTable.attribute.type.numeric": "sayısal",
    "DG.CaseTable.attribute.type.date": "tarih",
    "DG.CaseTable.attribute.type.qualitative": "nitel",
    "DG.CaseTable.attribute.type.boundary": "sınır",
    "DG.CaseTable.attributeEditor.name": "isim",
    "DG.CaseTable.attributeEditor.description": "açıklama",
    "DG.CaseTable.attributeEditor.type": "tür",
    "DG.CaseTable.attributeEditor.unit": "birim",
    "DG.CaseTable.attributeEditor.precision": "kesinlik",
    "DG.CaseTable.attributeEditor.editable": "düzenlenebilir",
    "DG.CaseTable.insertCasesDialog.title": "Durum Ekle",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# tane durum ekle:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "yer:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "önce",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "sonra",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Durum Ekle",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Belirtilen sayıda durum ekle",
    "DG.CaseTableController.allTables": "Tüm tablolar",
    "DG.AttrFormView.attrNamePrompt": "Özellik adı:",
    "DG.AttrFormView.formulaPrompt": "Formül:",
    "DG.AttrFormView.operandMenuTitle": "--- Değer Ekle ---",
    "DG.AttrFormView.functionMenuTitle": "--- Formül Ekle ---",
    "DG.AttrFormView.applyBtnTitle": "Uygula",
    "DG.AttrFormView.cancelBtnTitle": "İptal Et",
    "DG.AttrFormView.cancelBtnTooltip": "Herhangi bir değişiklik yapmadan iletişim kutusunu kapat",
    "DG.GuideConfigView.titlePrompt": "Rehber Başlığı",
    "DG.GuideConfigView.titleHint": "Aktivite Adı",
    "DG.GuideConfigView.itemTitleHint": "Bölüm Adı",
    "DG.GuideConfigView.itemURLHint": "Bölümün URL'si",
    "DG.GuideConfigView.okBtnTitle": "Tamam",
    "DG.GuideConfigView.okBtnToolTip": "Rehber menü öğelerini kabul et",
    "DG.GuideConfigView.cancelBtnTitle": "İptal et",
    "DG.GuideConfigView.cancelBtnTooltip": "Herhangi bir değişiklik yapmadan iletişim kutusunu kapat",
    "DG.GuideConfigView.httpWarning": "URL http:// veya https:// ile başlamalıdır",
    "DG.DataDisplayModel.rescaleToData": "Verileri yeniden ölçeklendir",
    "DG.DataDisplayModel.ShowConnectingLine": "Bağlantı Doğrularını Göster",
    "DG.DataDisplayModel.HideConnectingLine": "Bağlantı Doğrularını Gizle",
    "DG.AxisView.emptyGraphCue": "Burayı tıklayın, veya buraya bir özellik sürükleyin.",
    "DG.CellLinearAxisView.midPanelTooltip": "Eksen ölçeğini çevirmek için sürükleyin",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Eksen alt sınırını değiştirmek için sürükleyin",
    "DG.CellLinearAxisView.upperPanelTooltip": "Eksen üst sınırını değiştirmek için sürükleyin",
    "DG.PlotModel.mixup": "Grafiği Karıştırın",
    "DG.PlotModel.showCount": "Sayımı Göster",
    "DG.PlotModel.hideCount": "Sayımı Gizle",
    "DG.ScatterPlotModel.sumSquares": ",\nKareler toplamı = %@",
    "DG.ScatterPlotModel.slopeOnly": "eğim = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "Yılda",
    "DG.ScatterPlotModel.daysLabel": "Günde",
    "DG.ScatterPlotModel.hoursLabel": "Saatte",
    "DG.ScatterPlotModel.minutesLabel": "Dakikada",
    "DG.ScatterPlotModel.secondsLabel": "Saniyede",
    "DG.LegendView.attributeTooltip": "Renklendirme özelliğini değiştirmek için tıklayın",
    "DG.NumberToggleView.showAll": "Tümünü göster –",
    "DG.NumberToggleView.hideAll": "Tümünü gizle –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Son",
    "DG.NumberToggleView.showAllTooltip": "Tüm durumları görmek için tıklayın\nGörünürlüğü değiştirmek için ana etiketlere tıklayın",
    "DG.NumberToggleView.hideAllTooltip": "Tüm durumları gizlemek için tıklayın\nGörünürlüğü değiştirmek için ana etiketlere tıklayın",
    "DG.NumberToggleView.enableLastModeTooltip": "Yalnızca son ana durumu görmek için tıklayın",
    "DG.NumberToggleView.disableLastModeTooltip": "Son ana durum modundan çıkmak için tıklayın",
    "DG.NumberToggleView.indexTooltip": "Görünürlüğü değiştirmek için tıklayın",
    "DG.PlottedAverageAdornment.meanValueTitle": "ortalama=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "ortanca=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SS, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "Çeyrekler açıklığı=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "alt=%@\nQ1=%@\nortalama=%@\nQ3=%@\nüst=%@\nçeyrekler açıklığı=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Renklendirme özelliği: %@",
    "DG.DataDisplayMenu.remove": "Özelliği Çıkar",
    "DG.DataDisplayMenu.removeAttribute_x": "X'i çıkar: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Y'yi çıkar: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Y'yi çıkar: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Renklendirme özelliğini çıkar: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Kategorik olarak değerlendir",
    "DG.DataDisplayMenu.treatAsNumeric": "Sayısal olarak değerlendir",
    "DG.DataDisplayMenu.hide": "Gizle ve Göster",
    "DG.DataDisplayMenu.hideSelectedPlural": "Seçili Durumları Gizle",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Seçilmeyen Durumları Gizle",
    "DG.DataDisplayMenu.hideSelectedSing": "Seçili Durumu Gizle",
    "DG.DataDisplayMenu.hideUnselectedSing": "Seçilmeyen Durumu Gizle",
    "DG.DataDisplayMenu.enableNumberToggle": "Ana Görünüm Ayarlarını Göster",
    "DG.DataDisplayMenu.disableNumberToggle": "Ana Görünüm Ayarlarını Gizle",
    "DG.DataDisplayMenu.showAll": "Tüm Durumları Göster",
    "DG.DataDisplayMenu.snapshot": "Anlık Görüntü Al",
    "DG.GraphView.replaceAttribute": "%@ değerini %@ ile değiştir",
    "DG.GraphView.addAttribute": "%@ değerini ekle",
    "DG.GraphView.addToEmptyPlace": "%@ ile eksen oluştur",
    "DG.GraphView.addToEmptyX": "%@ ile X eksenini oluştur",
    "DG.GraphView.dropInPlot": "Noktaları boya %@ değerleri için\n",
    "DG.GraphView.zoomTip": "Yakınlaştırmak için çift tıklayın.\nUzaklaştırmak için Shift tuşunu basılı tutup çift tıklayın",
    "DG.GraphView.rescale": "Verileri yeniden ölçeklendir",
    "DG.AxisView.labelTooltip": "—%@ ekseni özelliğini değiştirmek için tıklayın",
    "DG.AxisView.vertical": "dikey",
    "DG.AxisView.horizontal": "yatay",
    "DG.DataTip.connectingLine": "%@: %@\nile %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formül",
    "DG.PlottedValue.namePrompt": "Çizilen Değer",
    "DG.PlottedValue.formulaPrompt": "değer =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Çizilen Değer",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Bir ifade yazın, örneğin x*x/30 - 50",
    "DG.MapView.showGrid": "Kareleri Göster",
    "DG.MapView.hideGrid": "Kareleri Gizle",
    "DG.MapView.showPoints": "Puanları Göster",
    "DG.MapView.hidePoints": "Puanları Gizle",
    "DG.MapView.marqueeHint": "İşaretleme aracı—Haritadaki seçili noktaları sürükleyin",
    "DG.MapView.gridControlHint": "Karelerin ölçüsünü değiştir",
    "DG.Inspector.values": "Ölçüm",
    "DG.Inspector.styles": "Biçimlendirme",
    "DG.Inspector.pointSize": "Nokta büyüklüğü:",
    "DG.Inspector.transparency": "Şeffaflık:",
    "DG.Inspector.color": "Renk:",
    "DG.Inspector.legendColor": "Renklendirmede kullanılacak renk:",
    "DG.Inspector.backgroundColor": "Arka plan rengi:",
    "DG.Inspector.stroke": "Çizgi:",
    "DG.Inspector.rescale.toolTip": "Ekranı tüm verileri göstermek için yeniden ölçeklendirin",
    "DG.Inspector.mixUp.toolTip": "Tüm noktaları karıştır",
    "DG.Inspector.hideShow.toolTip": "Tüm durumları göster veya seçili/seçilmeyen durumları gizle",
    "DG.Inspector.delete.toolTip": "Seçili/seçilmeyen durumları sil",
    "DG.Inspector.sliderValues.toolTip": "Kaydırıcı animasyon yönünü, hızını ayarlayın ...\n",
    "DG.Inspector.webViewEditURL.toolTip": "Görüntülenen web sayfasının URL'sini düzenleyin",
    "DG.Inspector.selection.selectAll": "Tüm Durumları Seç",
    "DG.Inspector.selection.deleteSelectedCases": "Seçili Durumları Sil",
    "DG.Inspector.selection.deleteUnselectedCases": "Seçilmeyen Durumları Sil",
    "DG.Inspector.deleteAll": "Tüm Durumları Sil",
    "DG.Inspector.deleteDataSet": "Veri Setini Sil ve Yok Et",
    "DG.Inspector.displayValues.toolTip": "Noktalarla birlikte gösterilenleri değiştirin",
    "DG.Inspector.displayStyles.toolTip": "Ekran görünümünü değiştirin",
    "DG.Inspector.makeImage.toolTip": "Resmi PNG dosyası olarak kaydet",
    "DG.Inspector.displayShow": "Göster ...",
    "DG.Inspector.colorPicker.more": "daha fazla",
    "DG.Inspector.colorPicker.less": "daha az",
    "DG.Inspector.graphTransparency": "Şeffaf",
    "DG.Inspector.graphCount": "Sayı",
    "DG.Inspector.graphPercent": "Yüzde",
    "DG.Inspector.graphRow": "Satır",
    "DG.Inspector.graphColumn": "Sütun",
    "DG.Inspector.graphCell": "Hücre",
    "DG.Inspector.graphConnectingLine": "Kesişen Doğrular",
    "DG.Inspector.graphMovableLine": "Hareketli Doğru",
    "DG.Inspector.graphInterceptLocked": "0 noktası Kilitli",
    "DG.Inspector.graphPlottedFunction": "Çizilen Fonksiyon",
    "DG.Inspector.graphSquares": "Kalanların Karesi",
    "DG.Inspector.graphLSRL": "En Küçük Kareler Çizgisi",
    "DG.Inspector.graphMovableValue": "Hareketli Değer",
    "DG.Inspector.graphAdd": "Ekle",
    "DG.Inspector.graphRemove": "Çıkar",
    "DG.Inspector.graphPlottedMean": "Ortalama",
    "DG.Inspector.graphPlottedMedian": "Ortanca",
    "DG.Inspector.graphPlottedStDev": "Standart Sapma",
    "DG.Inspector.graphPlottedIQR": "Çeyrekler Arası Aralık",
    "DG.Inspector.graphPlottedBoxPlot": "Kutu Grafiği",
    "DG.Inspector.graphPlottedValue": "Çizilen Değer",
    "DG.Inspector.attributes.toolTip": "Yeni özellikler oluşturun. Durum verilerini dışa aktarın.",
    "DG.Inspector.resize.toolTip": "Verilerin sığması için tüm sütunları yeniden boyutlandır",
    "DG.Inspector.newAttribute": "Yeni Değer %@...",
    "DG.Inspector.randomizeAllAttributes": "Hepsini yeniden dağıt",
    "DG.Inspector.exportCaseData": "Durum Verilerini Dışa Aktar...",
    "DG.Inspector.mapGrid": "Kareler",
    "DG.Inspector.mapPoints": "Noktalar",
    "DG.Inspector.mapLines": "Kesişen Doğrular",
    "DG.GameController.continuityError": "Maalesef, durum tablosundaki sütunların sıralaması yapıldıktan sonra yeni veriler kabul edilemez.",
    "DG.GameView.loading": "Yükleniyor",
    "DG.GameView.loadError": "Bu metni görebiliyorsanız, yukarıdaki URL'yi yüklemek başarısız olmuş olabilir. Bağlantıyı başka bir tarayıcı sekmesinden kontrol edebilir veya hatayı http://codap.concord.org/help adresine tıklayarak bize bildirebilirsiniz.",
    "DG.Component.closeComponent.confirmCloseMessage": "Emin misiniz?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Evet, kapat",
    "DG.Component.closeComponent.cancelButtonTitle": "İptal et",
    "DG.GameController.confirmCloseDescription": "Bunu kapatırsanız, daha fazla veri ekleyemeyebilirsiniz.",
    "DG.WebView.defaultTitle": "İnternet Sayfası",
    "DG.mainPage.exceptionMessage": "An error has occurred that may affect how this program behaves. You may wish to reload this page after you save your work. (Error: %@)",
    "DG.fileMenu.provider.examples.displayName": "Example Documents",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Open a plugin component",
    "DG.Undo.graph.showMovablePoint": "Undo showing movable point",
    "DG.Redo.graph.showMovablePoint": "Redo showing movable point",
    "DG.Undo.graph.hideMovablePoint": "Undo hiding movable point",
    "DG.Redo.graph.hideMovablePoint": "Redo hiding movable point",
    "DG.Undo.graph.moveMovablePoint": "Undo moving movable point",
    "DG.Redo.graph.moveMovablePoint": "Redo moving movable point",
    "DG.DataDisplayMenu.copyAsImage": "Open in Draw Tool",
    "DG.DataDisplayMenu.exportImage": "Export Image...",
    "DG.DataDisplayMenu.imageOfTitle": "Image of %@",
    "DG.Inspector.graphMovablePoint": "Movable Point",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Open case table for this data set",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Create a new data set",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Delete and destroy this data set",
    "DG.Undo.graph.showAsBarChart": "Undo fusing dots into bars",
    "DG.Redo.graph.showAsBarChart": "Redo fusing dots into bars",
    "DG.Undo.graph.showAsDotChart": "Undo dispersing bars into dots",
    "DG.Redo.graph.showAsDotChart": "Redo dispersing bars into dots",
    "DG.CountAxisView.countLabel": "Count",
    "DG.CountAxisView.countLabelDescription": "Number of cases in the bar along this axis",
    "DG.CountAxisView.percentLabel": "Percent",
    "DG.CountAxisView.percentLabelDescription": "Percent of cases in the bar along this axis",
    "DG.BarChartModel.cellTipPlural": "%@ of %@ %@ (%@%) are %@",
    "DG.BarChartModel.cellTipSingular": "%@ of %@ %@ (%@%) is %@",
    "DG.Inspector.configuration": "Configuration",
    "DG.Inspector.displayConfiguration.toolTip": "Configure the display differently",
    "DG.Inspector.displayScale": "Scale …",
    "DG.Inspector.graphBarChart": "Fuse Dots into Bars",
    "DG.Locale.name.de": "German",
    "DG.Locale.name.en": "English",
    "DG.Locale.name.es": "Spanish",
    "DG.Locale.name.he": "Hebrew",
    "DG.Locale.name.tr": "Turkish",
    "DG.Locale.name.zh": "Traditional Chinese",
    "DG.Undo.graph.swapCategories": "Undo reordering categories",
    "DG.Redo.graph.swapCategories": "Redo reordering categories",
    "DG.TableController.collectionTitleText": "%@1 (%@2 cases)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 cases, %@3 set aside)",
    "DG.Inspector.setaside.setAsideSelectedCases": "Set Aside Selected Cases",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Set Aside Unselected Cases",
    "DG.Inspector.setaside.restoreSetAsideCases": "Restore %@ Set Aside Cases",
    "DG.DocumentController.caseCardTitle": "Case Card",
    "DG.DocumentController.toggleToCaseCard": "Switch to case card view of the data",
    "DG.DocumentController.toggleToCaseTable": "Switch to case table view of the data",
    "DG.CaseCard.indexString": "1 of %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ selected of %@ %@",
    "DG.CaseCard.summaryValues": "%@ values",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Select and show next case",
    "DG.CaseCard.navPrevCase": "Select and show previous case",
    "DG.CaseCard.navFirstCase": "Select and show first case",
    "DG.CaseCard.navLastCase": "Select and show last case",
    "DG.Undo.component.toggleTableToCard": "Undo changing case table to case card",
    "DG.Redo.component.toggleTableToCard": "Redo changing case table to case card",
    "DG.Undo.component.toggleCardToTable": "Undo changing case card to case table",
    "DG.Redo.component.toggleCardToTable": "Redo changing case card to case table",
    "DG.Undo.graph.addBackgroundImage": "Undo adding graph background image",
    "DG.Redo.graph.addBackgroundImage": "Redo adding graph background image",
    "DG.Undo.graph.removeBackgroundImage": "Undo removing graph background image",
    "DG.Redo.graph.removeBackgroundImage": "Redo removing graph background image",
    "DG.Undo.graph.lockBackgroundImage": "Undo locking background image to axes",
    "DG.Redo.graph.lockBackgroundImage": "Redo locking background image to axes",
    "DG.Undo.graph.unlockBackgroundImage": "Undo unlocking background image from axes",
    "DG.Redo.graph.unlockBackgroundImage": "Redo unlocking background image from axes",
    "DG.Undo.enableMeasuresForSelection": "Undo Show Measures For Selection",
    "DG.Redo.enableMeasuresForSelection": "Redo Show Measures For Selection",
    "DG.Undo.disableMeasuresForSelection": "Undo Hide Measures For Selection",
    "DG.Redo.disableMeasuresForSelection": "Redo Hide Measures For Selection",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Show Measures for Selection",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Hide Measures for Selection",
    "DG.DataDisplayMenu.addBackgroundImage": "Add Background Image",
    "DG.DataDisplayMenu.lockImageToAxes": "Lock Background Image to Axes",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Unlock Background Image from Axes",
    "DG.DataDisplayMenu.removeBackgroundImage": "Remove Background Image",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Delete Formula (Keeping Values)",
    "DG.TableController.headerMenuItems.recoverFormula": "Recover Deleted Formula",
    "DG.Inspector.displayLayers.toolTip": "Change the appearance of the map layers",
    "DG.Inspector.layers": "Layers",
    "DG.Undo.graph.repositionEquation": "Undo repositioning equation",
    "DG.Redo.graph.repositionEquation": "Redo repositioning equation",
    "DG.TableController.attrEditor.precisionNumericHint": "Number of digits after decimal point",
    "DG.TableController.attrEditor.precisionDateHint": "Determines how much of the date is displayed",
    "DG.TableController.attrEditor.typeHint": "Set to force the attribute to be treated as a certain type",
    "DG.TableController.attrEditor.nameHint": "The attribute name appears in the case table, case card, and on graph axes",
    "DG.TableController.attrEditor.editableHint": "If the attribute is not editable, its values and/or formula cannot be changed",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "year month day hour minute second millisecond",
    "DG.AttributeFormat.DatePrecision.year": "YYYY",
    "DG.AttributeFormat.DatePrecision.month": "MMM YYYY",
    "DG.AttributeFormat.DatePrecision.day": "MMM D, YYYY",
    "DG.AttributeFormat.DatePrecision.hour": "MMM D, YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "MMM D, YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "MMM D, YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@1 in %@2",
    "DG.CaseCard.attrHintDescription": "%@1: %@2",
    "DG.CaseCard.attrHintFormula": "%@1 = %@2",
    "DG.AppController.optionMenuItems.help-forum": "Help Forum...",
    "DG.AppController.showHelpForumTitle": "Help Forum",
    "DG.Locale.name.el": "Greek",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ of %@ (%@%) is %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ of %@ (%@%) are %@",
    "DG.DataDisplayMenu.removeAttribute_top": "Remove Side-by-side Layout by %@",
    "DG.DataDisplayMenu.removeAttribute_right": "Remove Vertical Layout by %@",
    "DG.GraphView.layoutPlotsSideBySide": "Layout side-by-side by %@",
    "DG.GraphView.layoutPlotsVertically": "Layout vertically by %@",
    "DG.Undo.graph.makeStrokeSameAsFill": "Undo making stroke same as fill",
    "DG.Redo.graph.makeStrokeSameAsFill": "Redo making stroke same as fill",
    "DG.Undo.graph.makeStrokeIndependent": "Undo making stroke independent of fill",
    "DG.Redo.graph.makeStrokeIndependent": "Redo making stroke independent of fill",
    "DG.Inspector.strokeSameAsFill": "Stroke same color as fill",
    "DG.Formula.DateShortDaySunday": "Sun",
    "DG.Formula.DateShortDayMonday": "Mon",
    "DG.Formula.DateShortDayTuesday": "Tue",
    "DG.Formula.DateShortDayWednesday": "Wed",
    "DG.Formula.DateShortDayThursday": "Thu",
    "DG.Formula.DateShortDayFriday": "Fri",
    "DG.Formula.DateShortDaySaturday": "Sat",
    "DG.AttributeFormat.DatePrecision.millisecond": "MMM D, YYYY HH:mm:ss.SSS",
    "DG.CellAxis.other": "OTHER",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 MAD, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "Mean Absolute Deviation",
    "DG.Undo.graph.showPlottedBoxPlot": "Undo showing box plot",
    "DG.Redo.graph.hidePlottedBoxPlot": "Redo hiding box plot",
    "DG.Undo.graph.hidePlottedBoxPlot": "Undo hiding box plot",
    "DG.Redo.graph.showPlottedBoxPlot": "Redo showing box plot",
    "DG.Undo.graph.showOutliers": "Undo showing outliers",
    "DG.Redo.graph.hideOutliers": "Redo hiding outliers",
    "DG.Undo.graph.hideOutliers": "Undo hiding outliers",
    "DG.Redo.graph.showOutliers": "Redo showing outliers",
    "DG.Inspector.graphBoxPlotShowOutliers": "Show Outliers",
    "DG.Locale.name.nb": "Bokmål",
    "DG.Locale.name.nn": "Nynorsk",
    "DG.CaseCard.newCaseToolTip": "Add an empty case to this collection",
    "DG.TableController.headerMenuItems.renameAttribute": "Rename",
    "DG.Undo.graph.fuseDotsToRectangles": "Undo fusing dots into rectangles",
    "DG.Redo.graph.fuseDotsToRectangles": "Redo fusing dots into rectangles",
    "DG.Undo.graph.dissolveRectanglesToDots": "Undo dissolving rectangles into dots",
    "DG.Redo.graph.dissolveRectanglesToDots": "Redo dissolving rectangles into dots",
    "DG.Undo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Redo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Undo.graph.showAsBinnedPlot": "Undo grouping dots into bins",
    "DG.Redo.graph.showAsBinnedPlot": "Redo grouping dots into bins",
    "DG.Undo.graph.showAsDotPlot": "Undo ungrouping dots from bins",
    "DG.Redo.graph.showAsDotPlot": "Redo ungrouping dots from bins",
    "DG.Undo.graph.dragBinBoundary": "Undo dragging bin boundary",
    "DG.Redo.graph.dragBinBoundary": "Redo dragging bin boundary",
    "DG.Undo.graph.changeBinWidth": "Undo changing bin width",
    "DG.Redo.graph.changeBinWidth": "Redo changing bin width",
    "DG.Undo.graph.changeBinAlignment": "Undo changing bin alignment",
    "DG.Redo.graph.changeBinAlignment": "Redo changing bin alignment",
    "DG.BinnedPlotModel.dragBinTip": "Drag to change bin width",
    "DG.HistogramView.barTipPlural": "%@ of %@ %@ (%@%) are ≥ %@ and < %@",
    "DG.HistogramView.barTipSingular": "%@ of %@ %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendSingular": "%@ of %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendPlural": "%@ of %@ (%@%) are ≥ %@ and < %@",
    "DG.Inspector.graphGroupIntoBins": "Group into Bins",
    "DG.Inspector.graphBinWidth": "Bin width",
    "DG.Inspector.graphAlignment": "Alignment",
    "DG.CaseTable.dividerView.expandAllTooltip": "expand all groups",
    "DG.CaseTable.dividerView.expandGroupTooltip": "expand group",
    "DG.CaseTable.dividerView.collapseAllTooltip": "collapse all groups",
    "DG.CaseTable.dividerView.collapseGroupTooltip": "collapse group",
    "DG.BinnedPlotModel.binLabelTip": "Values in this bin are ≥ %@ and < %@",
    "DG.Component.closeComponent.toolTip": "Close this Component",
    "DG.Component.minimizeComponent.toolTip": "Minimize or expand this Component",
    "DG.Locale.name.ja": "Japanese",
    "DG.CaseCard.attrHintDescriptionAndFormula": "%@1: %@2\n%@1 = %@3",
    "DG.Locale.name.zh-Hans": "Simplified Chinese",
    "DG.PlottedCount.withoutSelection": "%@",
    "DG.PlottedCount.withSelection": "%@ selected",
    "DG.PlottedPercent.withoutSelection": "%@%",
    "DG.PlottedPercent.withSelection": "%@% selected",
    "DG.PlottedCountPercent.withoutSelection": "%@ (%@%)",
    "DG.PlottedCountPercent.withSelection": "%@ of %@ (%@%) selected",
    "DG.Undo.caseTable.resizeColumn": "Undo fit width to content",
    "DG.Redo.caseTable.resizeColumn": "Redo fit width to content",
    "DG.TableController.headerMenuItems.resizeColumn": "Fit width to content",
    "DG.SelectedInfoView.infoPlural": "Showing measures for %@ selected cases",
    "DG.SelectedInfoView.infoSing": "Showing measures for %@ selected case",
    "DG.Inspector.copyCaseDataToClipboard": "Copy to Clipboard...",
    "DG.Inspector.caseTable.exportCaseDialog.copyFrom": "Copy case data from:",
    "DG.Inspector.caseTable.exportCaseDialog.copy": "Copy",
    "DG.Inspector.caseTable.exportCaseDialog.copyTooltip": "Copy data to clipboard",
    "DG.Inspector.caseTable.exportCaseDialog.copiedData": "Copied %@ to the clipboard",
    "DG.Undo.caseTable.hideAttribute": "Undo hiding attribute",
    "DG.Redo.caseTable.hideAttribute": "Redo hiding attribute",
    "DG.Undo.caseTable.showAllHiddenAttributes": "Undo show all hidden attributes",
    "DG.Redo.caseTable.showAllHiddenAttributes": "Redo show all hidden attributes",
    "DG.TableController.headerMenuItems.hideAttribute": "Hide Attribute",
    "DG.Inspector.attributes.showAllHiddenAttributesSing": "Show %@ Hidden Attribute",
    "DG.Inspector.attributes.showAllHiddenAttributesPlural": "Show %@ Hidden Attributes",
    "DG.Inspector.attributes.showAllHiddenAttributesDisabled": "Show Hidden Attributes",
    "DG.Inspector.getCaseDataFromClipboard": "Import Case Data from Clipboard...",
    "DG.CaseCard.addCaseButton": "add case",
    "DG.Undo.DataContext.join": "Undo join of %@ to %@",
    "DG.Redo.DataContext.join": "Redo join of %@ to %@",
    "DG.Collection.joinTip": "Join %@ in %@ to %@ in %@ by matching %@ with %@",
    "DG.Inspector.graphPlotPoints": "Points",
    "DG.Inspector.graphBarForEachPoint": "Bar for Each Point",
    "DG.Undo.graph.changeBarChartFunction": "Undo change bar chart formula",
    "DG.Redo.graph.changeBarChartFunction": "Redo change bar chart formula",
    "DG.Undo.graph.showAsLinePlot": "Undo bar for each point",
    "DG.Redo.graph.showAsLinePlot": "Redo bar for each point",
    "DG.Undo.graph.showAsStandardBarChart": "Undo using count or percent for bar chart scale",
    "DG.Redo.graph.showAsStandardBarChart": "Redo using count or percent for bar chart scale",
    "DG.Undo.graph.showAsComputedBarChart": "Undo computing bar length with formula",
    "DG.Redo.graph.showAsComputedBarChart": "Redo computing bar length with formula",
    "DG.FormulaAxisView.labelDescription": "The expression that determines the length of the bars. Click to edit.",
    "DG.ComputedBarChartModel.cellTip": "For group %@ the value is %@",
    "DG.BarChartFunction.namePrompt": "Bar Chart",
    "DG.BarChartFunction.formulaPrompt": "bar length =",
    "DG.BarChartFunction.formulaHint": "Type a formula to compute bar length",
    "DG.BarChartFunction.emptyExpressionAxisPrompt": "Click here to provide a formula",
    "DG.Inspector.graphFormula": "Formula",
    "DG.Undo.displayOnlySelected": "Undo displaying only selected cases",
    "DG.Redo.displayOnlySelected": "Redo displaying only selected cases",
    "DG.Undo.webView.show": "Undo adding webView component",
    "DG.Redo.webView.show": "Redo adding webView component",
    "DG.Undo.imageComponent.show": "Undo adding image component",
    "DG.Redo.imageComponent.show": "Redo adding image component",
    "DG.DataDisplayMenu.displayOnlySelected": "Display Only Selected Cases",
    "DG.DataDisplayMenu.displayingOnlySelected": "Displaying Only Selected Cases",
    "DG.PlotBackgroundView.msg0": "This graph is set to display",
    "DG.PlotBackgroundView.msg1": "only selected cases.",
    "DG.PlotBackgroundView.msg2": "No cases are selected",
    "DG.PlotBackgroundView.msg3": "so nothing is being displayed.",
    "DG.PlotBackgroundView.msg4": "You can select cases in a",
    "DG.PlotBackgroundView.msg5": "case table or another graph.",
    "DG.ImageComponent.defaultTitle": "Image",
    "DG.TableController.datasetMetadata.title": "Dataset Information",
    "DG.CaseTable.datasetMetadata.url": "source",
    "DG.CaseTable.datasetMetadata.creationDate": "import date",
    "DG.TableController.datasetMetadata.descriptionHint": "Describe the dataset",
    "DG.Inspector.datasetInfo.toolTip": "Display information about dataset",
    "DG.CaseTable.indexMenu.moveEntryRow": "Move Data Entry Row Here",
    "DG.CaseCard.deselect": "Deselect all cases",
    "DG.CaseCard.noDeselect": "No cases are selected",
    "DG.CaseTable.indexProto.tooltip": "Drag to place data entry row within this table",
    "DG.AttributeFormat.DatePrecisionShort.year": "YYYY",
    "DG.AttributeFormat.DatePrecisionShort.month": "M/YY",
    "DG.AttributeFormat.DatePrecisionShort.day": "M/D/YY",
    "DG.AttributeFormat.DatePrecisionShort.hour": "M/D/YY HH:00",
    "DG.AttributeFormat.DatePrecisionShort.minute": "M/D/YY HH:mm",
    "DG.AttributeFormat.DatePrecisionShort.second": "M/D/YY HH:mm:ss",
    "DG.AttributeFormat.DatePrecisionShort.millisecond": "M/D/YY HH:mm:ss.SSS",
    "DG.Formula.FuncCategoryLogic": "Logic Functions",
    "DG.Undo.graph.showMeasureLabels": "Undo showing measure labels",
    "DG.Redo.graph.showMeasureLabels": "Redo showing measure labels",
    "DG.Undo.graph.hideMeasureLabels": "Undo hiding measure labels",
    "DG.Redo.graph.hideMeasureLabels": "Redo hiding measure labels",
    "DG.Inspector.showLabels": "Show Measure Labels",
    "DG.Undo.caseTable.resizeOneColumn": "Undo resize column",
    "DG.Redo.caseTable.resizeOneColumn": "Redo resize column",
    "DG.CaseTable.attribute.type.checkbox": "checkbox",
    "DG.AppController.caseTableMenu.clipboardDataset": "-- new from clipboard --",
    "DG.AppController.caseTableMenu.clipboardDatasetToolTip": "Paste data set from clipboard",
    "DG.AppController.optionMenuItems.toPrivacyPage": "Privacy Page...",
    "DG.plugin.Importer.title": "Import CSV to CODAP",
    "DG.plugin.Importer.enter-url": "Enter url: ",
    "DG.plugin.Importer.or": "or",
    "DG.plugin.Importer.downsample-section": "Downsample Options...",
    "DG.plugin.Importer.downsample-random-p1": "Randomly select",
    "DG.plugin.Importer.downsample-random-p2": "rows",
    "DG.plugin.Importer.downsample-every-nth-p1": "Select every",
    "DG.plugin.Importer.downsample-every-nth-p2": "th row",
    "DG.plugin.Importer.downsample-import-all": "Import all rows",
    "DG.plugin.Importer.target-options-title": "Target Options...",
    "DG.plugin.Importer.target-options-replace": "Replace existing dataset with this one",
    "DG.plugin.Importer.target-options-append": "Append this dataset to the existing one",
    "DG.plugin.Importer.target-options-create-new": "Create a new data set",
    "DG.plugin.Importer.button-cancel": "Cancel",
    "DG.plugin.Importer.button-submit": "OK",
    "DG.plugin.Importer.button-dismiss": "Dismiss",
    "DG.plugin.Importer.load-error": "There was an error loading this resource: \"%@\" reason: \"%@\"",
    "DG.plugin.Importer.no-table-error": "Could not find tabular data in a format that can be imported into CODAP",
    "DG.plugin.Importer.duplicate-dataset-msg": "There already exists a dataset like this one. It is named \"%@\".",
    "DG.plugin.Importer.upload-time-msg": "It was uploaded %@",
    "DG.plugin.Importer.large-file-msg": "The imported file, \"%@\" has %@ rows. With more than %@ rows CODAP performance may be sluggish. You can work with a sample of the data at least at first, replacing it with the full dataset later.",
    "DG.plugin.Importer.error-codap-connection": "Error sending data to CODAP",
    "DG.plugin.Importer.error-upload": "Could not import this file -- %@",
    "DG.plugin.Importer.import-message": "Preparing to import %@ rows into \"%@\" from a table with %@ attributes: %@%@",
    "DG.Undo.component.componentTitleChange": "Undo changing the component title",
    "DG.Redo.component.componentTitleChange": "Redo changing the component title"
});