SC.stringsFor("tr", {
    "DG.fileMenu.menuItem.newDocument": "Yeni",
    "DG.fileMenu.menuItem.openDocument": "Aç...",
    "DG.fileMenu.menuItem.closeDocument": "Kapat",
    "DG.fileMenu.menuItem.importFile": "İçe aktar",
    "DG.fileMenu.menuItem.revertTo": "Dönüştür...",
    "DG.fileMenu.menuItem.revertToOpened": "Son açılan versiyon",
    "DG.fileMenu.menuItem.revertToShared": "Paylaşılan görünümler",
    "DG.fileMenu.menuItem.saveDocument": "Kaydet...",
    "DG.fileMenu.menuItem.copyDocument": "Kopya Oluştur",
    "DG.fileMenu.menuItem.share": "Paylaş...",
    "DG.fileMenu.menuItem.shareGetLink": "Paylaşılan görünümler bağlantısı",
    "DG.fileMenu.menuItem.shareUpdate": "Paylaşılan görünümleri güncelle",
    "DG.fileMenu.menuItem.renameDocument": "Yeniden adlandır",
    "DG.main.userEntryView.title": "Ne yapmak istiyorsunuz?",
    "DG.main.userEntryView.openDocument": "Dosya Aç veya Örnekleri Görüntüle",
    "DG.main.userEntryView.newDocument": "Yeni Dosya Aç",
    "DG.mainPage.mainPane.undoButton.title": "Geri Al",
    "DG.mainPage.mainPane.undoButton.toolTip": "Son yapılanı geri al",
    "DG.mainPage.mainPane.redoButton.title": "Yinele",
    "DG.mainPage.mainPane.redoButton.toolTip": "Son geri alınanı yinele",
    "DG.mainPage.mainPane.versionString": "Versiyon %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Üzgünüz, CODAP tarayıcınız tarafından desteklenmiyor. CODAP sadece Firefox 46+, Chrome 50+, Windows Edge 14+, ve Safari 10+ tarafından desteklenmektedir. Şu anda diğer tarayıcılar tarafından desteklenmemektedir.",
    "DG.mainPage.titleBar.saved": "Dosya Kaydedildi!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Versiyon %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Versiyon %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Verileri temizle...",
    "DG.AppController.resetData.toolTip": "Bu dosyadaki tüm verileri sil",
    "DG.AppController.resetData.warnMessage": "Bu dosyadaki tüm verileri gerçekten silmek istiyor musunuz?",
    "DG.AppController.resetData.warnDescription": "Bu işlem geri alınamaz.",
    "DG.AppController.resetData.okButtonTitle": "Evet, tüm verileri sil",
    "DG.AppController.resetData.cancelButtonTitle": "Hayır, verileri sakla",
    "DG.AppController.closeDocument.warnMessage": "Dosyayı kaydetmeden kapatmak istiyor musunuz?",
    "DG.AppController.closeDocument.warnDescription": "Bu işlem geri alınamaz.",
    "DG.AppController.closeDocument.okButtonTitle": "Kapat",
    "DG.AppController.closeDocument.cancelButtonTitle": "İptal et",
    "DG.AppController.beforeUnload.confirmationMessage": "Bu dosyada kaydedilmeyen değişiklikler var.",
    "DG.AppController.optionMenuItems.reportProblem": "Geri Bildirim Gönder...",
    "DG.AppController.optionMenuItems.viewWebPage": "İnternet sayfasını görüntüle...",
    "DG.AppController.optionMenuItems.configureGuide": "Rehberi Yapılandır...",
    "DG.AppController.optionMenuItems.about": "CODAP Hakkında...",
    "DG.AppController.optionMenuItems.releaseNotes": "Yenilikler",
    "DG.AppController.optionMenuItems.help": "Yardım Sayfaları ve Videoları...",
    "DG.AppController.optionMenuItems.toWebSite": "CODAP internet sayfası",
    "DG.AppController.exportDocument.prompt": "Dosya adı:",
    "DG.AppController.exportCaseData.prompt": "Verileri buradan dışarı aktar:",
    "DG.AppController.exportDocument.exportTitle": "Dışa aktar",
    "DG.AppController.exportDocument.exportTooltip": "Verileri bir dosyaya aktar",
    "DG.AppController.exportDocument.cancelTitle": "İptal et",
    "DG.AppController.exportDocument.cancelTooltip": "Dışa aktarımı iptal et",
    "DG.AppController.feedbackDialog.dialogTitle": "Geri Bildirim Yap",
    "DG.AppController.feedbackDialog.subHeaderText": "Geri bildirimleriniz bizim için önemli!",
    "DG.AppController.feedbackDialog.messageText": "Ürünümüzü geliştirmemize yardımcı olun. Sorularınızı, isteklerinizi ve sistem hatalarını bize bildirin. Teşekkür ederiz!",
    "DG.AppController.feedbackDialog.subjectHint": "Geri bildiriminiz nedir",
    "DG.AppController.feedbackDialog.feedbackHint": "Ayrıntılar",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Gönder",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "İptal et",
    "DG.AppController.showWebSiteTitle": "CODAP Hakkında",
    "DG.AppController.showHelpTitle": "CODAP için Destek",
    "DG.AppController.showAboutTitle": "CODAP Hakkında",
    "DG.AppController.showReleaseNotesTitle": "CODAP Sürüm Notları",
    "DG.AppController.dropFile.error": "Hata: %@1",
    "DG.AppController.dropFile.unknownFileType": "Bu dosya türünü aktaramazsınız",
    "DG.AppController.validateDocument.missingRequiredProperty": "Gerekli özellik bulunamadı: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Beklenmeyen üst düzey özellik: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Çözümlenmemiş kimlik: %@1",
    "DG.AppController.validateDocument.parseError": "Belgedeki hatayı ayrıştır: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Geçersiz JSON Dosyası: %@1",
    "DG.AppController.openDocument.error.general": "Dosya açılamadı",
    "DG.AppController.openDocument.error.invalid_format": "CODAP bu tür dosyaları çalıştıramıyor",
    "DG.AppController.createDataSet.initialAttribute": "Özellik",
    "DG.AppController.createDataSet.name": "Yeni Veri Seti",
    "DG.AppController.createDataSet.collectionName": "Durumlar",
    "DG.AppController.caseTableMenu.newDataSet": "-- yeni --",
    "DG.SingleTextDialog.okButton.title": "TAMAM",
    "DG.SingleTextDialog.cancelButton.title": "İptal et",
    "DG.SingleTextDialog.cancelButton.toolTip": "Herhangi bir değişiklik yapmadan iletişim kutusunu kapat",
    "DG.DocumentController.calculatorTitle": "Hesap makinesi",
    "DG.DocumentController.caseTableTitle": "Durum tablosu",
    "DG.DocumentController.graphTitle": "Grafik",
    "DG.DocumentController.sliderTitle": "Sürgü",
    "DG.DocumentController.textTitle": "Metin",
    "DG.DocumentController.mapTitle": "Harita",
    "DG.DocumentController.enterURLPrompt": "Görüntülenecek internet sayfasının URL'sini girin",
    "DG.DocumentController.enterViewWebPageOKTip": "URL tarafından sağlanan internet sayfasından görüntüler",
    "DG.Document.defaultDocumentName": "Başlıksız Dosya",
    "DG.Document.documentName.toolTip": "Dosya adını düzenlemek için tıklayın",
    "DG.SliderView.thumbView.toolTip": "Kaydırıcının değerini değiştirmek için sürükleyin",
    "DG.SliderView.startButton.toolTip": "Animasyonu başlat/durdur",
    "DG.ToolButtonData.tableButton.title": "Tablolar",
    "DG.ToolButtonData.tableButton.toolTip": "Her veri için bir durum tablosu aç (ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Grafik",
    "DG.ToolButtonData.graphButton.toolTip": "Grafik oluştur (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Sürgü",
    "DG.ToolButtonData.sliderButton.toolTip": "Sürgü oluştur (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "Hesapla",
    "DG.ToolButtonData.calcButton.toolTip": "Hesap makinesini aç/kapat (ctrl-alt-c)",
    "DG.ToolButtonData.textButton.title": "Metin",
    "DG.ToolButtonData.textButton.toolTip": "Bir metin nesnesi oluşturun (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "Harita",
    "DG.ToolButtonData.mapButton.toolTip": "Harita oluştur",
    "DG.ToolButtonData.optionMenu.title": "Seçenekler",
    "DG.ToolButtonData.optionMenu.toolTip": "İnternet sayfasını görüntüle, rehberi yapılandır...",
    "DG.ToolButtonData.tileListMenu.title": "Pano",
    "DG.ToolButtonData.tileListMenu.toolTip": "Dosyadaki pano listesini göster",
    "DG.ToolButtonData.guideMenu.title": "Rehber",
    "DG.ToolButtonData.guideMenu.toolTip": "Rehberi bu aktivitede göster ve rehberde gezin",
    "DG.ToolButtonData.guideMenu.showGuide": "Rehberi Göster",
    "DG.ToolButtonData.help.title": "Yardım",
    "DG.ToolButtonData.help.toolTip": "CODAP Destek, CODAP Projesi Hakkında",
    "DG.Slider.multiples": "Sürgü Hareket Katsayısı:",
    "DG.Slider.maxPerSecond": "Saniyedeki Maksimum Animasyon Karesi:",
    "DG.Slider.direction": "Animasyon Yönü:",
    "DG.Slider.backAndForth": "İleri-Geri",
    "DG.Slider.lowToHigh": "Küçükten Büyüğe",
    "DG.Slider.highToLow": "Büyükten Küçüğe",
    "DG.Slider.mode": "Animasyon Tekrarı:",
    "DG.Slider.nonStop": "Durmaksızın",
    "DG.Slider.onceOnly": "Sadece bir kez",
    "DG.Undo.exceptionOccurred": "Geri almaya çalışılırken bir hata oluştu.",
    "DG.Redo.exceptionOccurred": "Yinelemeye çalışılırken bir hata oluştu.",
    "DG.Undo.componentMove": "Bileşeni hareket ettirmeyi geri al",
    "DG.Redo.componentMove": "Bileşeni hareket ettirmeyi yinele",
    "DG.Undo.componentResize": "Bileşeni yeniden boyutlandırma işlemini geri al",
    "DG.Redo.componentResize": "Bileşeni yeniden boyutlandırmayı yinele",
    "DG.Undo.axisDilate": "Ekseni yeniden ölçeklendirmeyi geri al",
    "DG.Redo.axisDilate": "Ekseni yeniden ölçeklendirmeyi yinele",
    "DG.Undo.axisRescaleFromData": "Ekseni yeniden ölçeklendirmeyi geri al",
    "DG.Redo.axisRescaleFromData": "Ekseni yeniden ölçeklendirmeyi yinele",
    "DG.Undo.axisDrag": "Ekseni sürüklemeyi geri al",
    "DG.Redo.axisDrag": "Ekseni sürüklemeyi yinele",
    "DG.Undo.axisAttributeChange": "Eksen özelliğini değiştirmeyi geri al",
    "DG.Redo.axisAttributeChange": "Eksen özelliğini değiştirmeyi yinele",
    "DG.Undo.axisAttributeAdded": "Eksen özelliği eklemeyi geri al",
    "DG.Redo.axisAttributeAdded": "Eksen özelliği eklemeyi yinele",
    "DG.Undo.toggleComponent.add.calcView": "Hesap makinesini göstermeyi geri al",
    "DG.Redo.toggleComponent.add.calcView": "Hesap makinesini göstermeyi yinele",
    "DG.Undo.toggleComponent.delete.calcView": "Hesap makinesini gizleme işlemini geri al",
    "DG.Redo.toggleComponent.delete.calcView": "Hesap makinesini gizleme işlemini yinele",
    "DG.Undo.caseTable.open": "Durum tablolarını göstermeyi geri al",
    "DG.Redo.caseTable.open": "Durum tablolarını göstermeyi yinele",
    "DG.Undo.caseTable.editAttribute": "Durum tablosu özelliğini düzenleme işlemini geri al",
    "DG.Redo.caseTable.editAttribute": "Durum tablosu özelliğini düzenleme işlemini yinele",
    "DG.Undo.caseTable.createAttribute": "Durum tablosu özelliği oluşturmayı geri al",
    "DG.Redo.caseTable.createAttribute": "Durum tablosu özelliği oluşturmayı yinele",
    "DG.Undo.caseTable.editAttributeFormula": "Durum tablosu özellik formülünü düzenleme işlemini geri al",
    "DG.Redo.caseTable.editAttributeFormula": "Durum tablosu özellik formülünü düzenleme işlemini yinele",
    "DG.Undo.caseTable.editCellValue": "Durum tablosu hücre değerini düzenleme işlemini geri al",
    "DG.Redo.caseTable.editCellValue": "Durum tablosu hücre değerini düzenleme işlemini yinele",
    "DG.Undo.caseTable.sortCases": "Durumları sıralamayı geri al",
    "DG.Redo.caseTable.sortCases": "Durumları sıralamayı yinele",
    "DG.Undo.caseTable.deleteAttribute": "Durum tablosu özelliği silmeyi geri al",
    "DG.Redo.caseTable.deleteAttribute": "Durum tablosu özelliği silmeyi yinele",
    "DG.Undo.caseTable.createCollection": "Yeni koleksiyon oluşturmayı geri al",
    "DG.Redo.caseTable.createCollection": "Yeni koleksiyon oluşturmayı yinele",
    "DG.Undo.caseTable.collectionNameChange": "Koleksiyonu yeniden adlandırmayı geri al",
    "DG.Redo.caseTable.collectionNameChange": "Koleksiyonu yeniden adlandırmayı yinele",
    "DG.Undo.caseTable.createNewCase": "Yeni durum oluşturmayı geri al",
    "DG.Redo.caseTable.createNewCase": "Yeni durum oluşturmayı yinele",
    "DG.Undo.caseTable.insertCases": "Durum eklemeyi geri al",
    "DG.Redo.caseTable.insertCases": "Durum eklemeyi yinele",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Tabloları görüntüle/gizleyi geri al",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Tabloları görüntüle/gizleyi yinele",
    "DG.Undo.caseTable.expandCollapseOneCase": "Bir grubun genişleme veya yığılmasını geri al",
    "DG.Redo.caseTable.expandCollapseOneCase": "Bir grubun genişleme veya yığılmasını yinele",
    "DG.Undo.caseTable.resizeColumns": "Tüm sütunları otomatik olarak yeniden boyutlandırmayı geri al",
    "DG.Redo.caseTable.resizeColumns": "Tüm sütunları otomatik olarak yeniden boyutlandırmayı yinele",
    "DG.Undo.document.share": "Dosyayı paylaşmayı geri al",
    "DG.Redo.document.share": "Dosyayı paylaşmayı yinele",
    "DG.Undo.document.unshare": "Dosyayı paylaşımını durdurmayı geri al",
    "DG.Redo.document.unshare": "Dosyayı paylaşımını durdurmayı yinele",
    "DG.Undo.game.add": "Dosyaya oyun eklemeyi geri al",
    "DG.Redo.game.add": "Dosyaya oyun eklemeyi yinele",
    "DG.Undo.graph.showCount": "Sayımı gösteri geri al",
    "DG.Redo.graph.showCount": "Sayımı gösteri yinele",
    "DG.Undo.graph.hideCount": "Sayımı gizlemeyi geri al",
    "DG.Redo.graph.hideCount": "Sayımı gizlemeyi yinele",
    "DG.Undo.graph.showPercent": "Yüzdeleri gösteri geri al",
    "DG.Redo.graph.showPercent": "Yüzdeleri gösteri yinele",
    "DG.Undo.graph.hidePercent": "Yüzdeyi gizlemeyi geri al",
    "DG.Redo.graph.hidePercent": "Yüzdeyi gizlemeyi yinele",
    "DG.Undo.graph.showMovableLine": "Hareket ettirilebilen doğrunun gösterilmesini geri al",
    "DG.Redo.graph.showMovableLine": "Hareket ettirilebilen doğrunun gösterilmesini yinele",
    "DG.Undo.graph.hideMovableLine": "Hareket ettirilebilen doğrunun gizlenmesini geri al",
    "DG.Redo.graph.hideMovableLine": "Hareket ettirilebilen doğrunun gizlenmesini yinele",
    "DG.Undo.graph.lockIntercept": "Doğruların kesişimini kilitlemeyi geri al",
    "DG.Redo.graph.lockIntercept": "Doğruların kesişimini kilitlemeyi yinele",
    "DG.Undo.graph.unlockIntercept": "Doğruların kesişimi kilidini açmayı geri al",
    "DG.Redo.graph.unlockIntercept": "Doğruların kesişimi kilidini açmayı yinele",
    "DG.Undo.graph.showPlotFunction": "Çizilen fonksiyonu göstermeyi geri al",
    "DG.Redo.graph.showPlotFunction": "Çizilen fonksiyonu göstermeyi yinele",
    "DG.Undo.graph.hidePlotFunction": "Çizilen fonksiyonu gizlemeyi geri al",
    "DG.Redo.graph.hidePlotFunction": "Çizilen fonksiyonu gizlemeyi yinele",
    "DG.Undo.graph.changePlotFunction": "Çizilen fonksiyonu değiştirmeyi geri al",
    "DG.Redo.graph.changePlotFunction": "Çizilen fonksiyonu değiştirmeyi yinele",
    "DG.Undo.graph.showPlotValue": "Çizilen değeri göstermeyi geri al",
    "DG.Redo.graph.showPlotValue": "Çizilen değeri göstermeyi yinele",
    "DG.Undo.graph.hidePlotValue": "Çizilen değeri gizlemeyi geri al",
    "DG.Redo.graph.hidePlotValue": "Çizilen değeri gizlemeyi yinele",
    "DG.Undo.graph.changePlotValue": "Çizilen değeri değiştirmeyi geri al",
    "DG.Redo.graph.changePlotValue": "Çizilen değeri değiştirmeyi yinele",
    "DG.Undo.graph.showConnectingLine": "Bağlantı doğrusunu göstermeyi geri al",
    "DG.Redo.graph.showConnectingLine": "Bağlantı doğrusunu göstermeyi yinele",
    "DG.Undo.graph.hideConnectingLine": "Bağlantı doğrusunu gizlemeyi geri al",
    "DG.Redo.graph.hideConnectingLine": "Bağlantı doğrusunu gizlemeyi yinele",
    "DG.Undo.graph.showLSRL": "En küçük kareler çizgisini göstermeyi geri al",
    "DG.Redo.graph.showLSRL": "En küçük kareler çizgisini göstermeyi yinele",
    "DG.Undo.graph.hideLSRL": "En küçük kareler çizgisini gizlemeyi geri al",
    "DG.Redo.graph.hideLSRL": "En küçük kareler çizgisini gizlemeyi yinele",
    "DG.Undo.graph.showSquares": "Kareleri göstermeyi geri al",
    "DG.Redo.graph.showSquares": "Kareleri göstermeyi yinele",
    "DG.Undo.graph.hideSquares": "Kareleri gizlemeyi geri al",
    "DG.Redo.graph.hideSquares": "Kareleri gizlemeyi yinele",
    "DG.Undo.graph.showPlottedMean": "Ortalamayı göstermeyi geri al",
    "DG.Redo.graph.showPlottedMean": "Ortalamayı göstermeyi yinele",
    "DG.Undo.graph.hidePlottedMean": "Ortalamayı gizlemeyi geri al",
    "DG.Redo.graph.hidePlottedMean": "Ortalamayı gizlemeyi yinele",
    "DG.Undo.graph.showPlottedMedian": "Ortancayı göstermeyi geri al",
    "DG.Redo.graph.showPlottedMedian": "Ortancayı göstermeyi yinele",
    "DG.Undo.graph.hidePlottedMedian": "Ortancayı gizlemeyi geri al",
    "DG.Redo.graph.hidePlottedMedian": "Ortancayı gizlemeyi yinele",
    "DG.Undo.graph.showPlottedStDev": "Standart sapmayı göstermeyi geri al",
    "DG.Redo.graph.showPlottedStDev": "Standart sapmayı göstermeyi yinele",
    "DG.Undo.graph.hidePlottedStDev": "Standart sapmayı gizlemeyi geri al",
    "DG.Redo.graph.hidePlottedStDev": "Standart sapmayı gizlemeyi yinele",
    "DG.Undo.graph.showPlottedIQR": "Çeyrekler arası açıklığı göstermeyi geri al",
    "DG.Redo.graph.hidePlottedIQR": "Çeyrekler arası açıklığı gizlemeyi yinele",
    "DG.Undo.graph.hidePlottedIQR": "Çeyrekler arası açıklığı gizlemeyi geri al",
    "DG.Redo.graph.showPlottedIQR": "Çeyrekler arası açıklığı göstermeyi yinele",
    "DG.Undo.graph.addMovableValue": "Taşınabilir değer eklemeyi geri al",
    "DG.Redo.graph.addMovableValue": "Taşınabilir değer eklemeyi yinele",
    "DG.Undo.graph.removeMovableValue": "Taşınabilir değeri kaldırmayı geri al",
    "DG.Redo.graph.removeMovableValue": "Taşınabilir değeri kaldırmayı yinele",
    "DG.Undo.graph.moveMovableValue": "Taşınabilir değeri değiştirmeyi geri al",
    "DG.Redo.graph.moveMovableValue": "Taşınabilir değeri değiştirmeyi yinele",
    "DG.Undo.graph.changePointColor": "Verilerin rengini değiştirmeyi geri al",
    "DG.Redo.graph.changePointColor": "Verilerin rengini değiştirmeyi yinele",
    "DG.Undo.graph.changeStrokeColor": "Dış hat çizgi rengini değiştirmeyi geri al",
    "DG.Redo.graph.changeStrokeColor": "Dış hat çizgi rengini değiştirmeyi yinele",
    "DG.Undo.graph.changePointSize": "Nokta büyüklüğünü değiştirmeyi geri al",
    "DG.Redo.graph.changePointSize": "Nokta büyüklüğünü değiştirmeyi yinele",
    "DG.Undo.graph.changeAttributeColor": "Özellik rengini değiştirmeyi geri al",
    "DG.Redo.graph.changeAttributeColor": "Özellik rengini değiştirmeyi yinele",
    "DG.Undo.graph.changeBackgroundColor": "Grafik arka plan rengini değiştirmeyi geri al",
    "DG.Redo.graph.changeBackgroundColor": "Grafik arka plan rengini değiştirmeyi yinele",
    "DG.Undo.graph.toggleTransparent": "Grafik saydamlığını değiştirmeyi geri al",
    "DG.Redo.graph.toggleTransparent": "Grafik saydamlığını değiştirmeyi yinele",
    "DG.Undo.guide.show": "Rehberi göstermeyi geri al",
    "DG.Redo.guide.show": "Rehberi göstermeyi yinele",
    "DG.Undo.guide.navigate": "Rehber sayfasını değiştirmeyi geri al",
    "DG.Redo.guide.navigate": "Rehber sayfasını değiştirmeyi yinele",
    "DG.Undo.hideSelectedCases": "Seçili durumları gizlemeyi geri al",
    "DG.Redo.hideSelectedCases": "Seçili durumları gizlemeyi yinele",
    "DG.Undo.hideUnselectedCases": "Seçili olmayan durumları gizlemeyi geri al",
    "DG.Redo.hideUnselectedCases": "Seçili olmayan durumları gizlemeyi yinele",
    "DG.Undo.enableNumberToggle": "Birincil Değişkenin Etiketlerini Göstermeyi Geri Al",
    "DG.Redo.enableNumberToggle": "Birincil Değişkenin Etiketlerini Göstermeyi Yinele",
    "DG.Undo.disableNumberToggle": "Birincil Değişkenin Etiketlerini Gizlemeyi Geri Al",
    "DG.Redo.disableNumberToggle": "Birincil Değişkenin Etiketlerini Gizlemeyi Yinele",
    "DG.Undo.interactiveUndoableAction": "Etkileşimdeki bir eylemi geri al",
    "DG.Redo.interactiveUndoableAction": "Etkileşimdeki bir eylemi yinele",
    "DG.Undo.showAllCases": "Tüm durumları gösteri geri al",
    "DG.Redo.showAllCases": "Tüm durumları gösteri yinele",
    "DG.Undo.map.create": "Harita eklemeyi geri al",
    "DG.Redo.map.create": "Harita eklemeyi yinele",
    "DG.Undo.map.fitBounds": "Harita boyutlandırmayı geri al",
    "DG.Redo.map.fitBounds": "Harita boyutlandırmayı yinele",
    "DG.Undo.map.pan": "Haritada gezinmeyi geri al",
    "DG.Redo.map.pan": "Haritada gezinmeyi yinele",
    "DG.Undo.map.zoom": "Haritaya yakınlaşmayı geri al",
    "DG.Redo.map.zoom": "Haritaya yakınlaşmayı yinele",
    "DG.Undo.map.showGrid": "Haritada kareleri göstermeyi geri al",
    "DG.Redo.map.showGrid": "Haritada kareleri göstermeyi yinele",
    "DG.Undo.map.hideGrid": "Haritada kareleri gizlemeyi geri al",
    "DG.Redo.map.hideGrid": "Haritada kareleri gizlemeyi yinele",
    "DG.Undo.map.changeGridSize": "Harita karelerinin büyüklüğünü değiştirmeyi geri al",
    "DG.Redo.map.changeGridSize": "Harita karelerinin büyüklüğünü değiştirmeyi yinele",
    "DG.Undo.map.showPoints": "Haritada noktaları göstermeyi geri al",
    "DG.Redo.map.showPoints": "Haritada noktaları göstermeyi yinele",
    "DG.Undo.map.hidePoints": "Haritada noktaları gizlemeyi geri al",
    "DG.Redo.map.hidePoints": "Haritada noktaları gizlemeyi yinele",
    "DG.Undo.map.showLines": "Harita çizgilerini göstermeyi geri al",
    "DG.Redo.map.showLines": "Harita çizgilerini göstermeyi yinele",
    "DG.Undo.map.hideLines": "Harita çizgilerini gizlemeyi geri al",
    "DG.Redo.map.hideLines": "Harita çizgilerini gizlemeyi yinele",
    "DG.Undo.map.changeBaseMap": "Harita arka planını değiştirmeyi geri al",
    "DG.Redo.map.changeBaseMap": "Harita arka planını değiştirmeyi yinele",
    "DG.Undo.textComponent.create": "Bir metin objesi eklemeyi geri al",
    "DG.Redo.textComponent.create": "Bir metin objesi eklemeyi yinele",
    "DG.Undo.textComponent.edit": "Metni değiştirmeyi geri al",
    "DG.Redo.textComponent.edit": "Metni değiştirmeyi yinele",
    "DG.Undo.sliderComponent.create": "Sürgü eklemeyi geri al",
    "DG.Redo.sliderComponent.create": "Sürgü eklemeyi yinele",
    "DG.Undo.slider.change": "Sürgü değeri değişimini geri al",
    "DG.Redo.slider.change": "Sürgü değeri değişimini yinele",
    "DG.Undo.slider.changeMultiples": "Sürgü katlarını değiştirmeyi geri al",
    "DG.Redo.slider.changeMultiples": "Sürgü katlarını değiştirmeyi yinele",
    "DG.Undo.slider.changeSpeed": "Saniyedeki maksimum animasyon karesini değiştirmeyi geri al",
    "DG.Redo.slider.changeSpeed": "Saniyedeki maksimum animasyon karesini değiştirmeyi yinele",
    "DG.Undo.slider.changeDirection": "Sürgü animasyon yönünü değiştirmeyi geri al",
    "DG.Redo.slider.changeDirection": "Sürgü animasyon yönünü değiştirmeyi yinele",
    "DG.Undo.slider.changeRepetition": "Sürgü animasyon tekrarını değiştirmeyi geri al",
    "DG.Redo.slider.changeRepetition": "Sürgü animasyon tekrarını değiştirmeyi yinele",
    "DG.Undo.graphComponent.create": "Grafik eklemeyi geri al",
    "DG.Redo.graphComponent.create": "Grafik eklemeyi yinele",
    "DG.Undo.dataContext.create": "Bir veri seti oluşturmayı geri al",
    "DG.Redo.dataContext.create": "Bir veri seti oluşturmayı yinele",
    "DG.Undo.data.deleteCases": "Durumları silmeyi geri al",
    "DG.Redo.data.deleteCases": "Durumları silmeyi yinele",
    "DG.Undo.component.close": "Kapatma düğmesini geri al",
    "DG.Redo.component.close": "Kapatma düğmesini yinele",
    "DG.Undo.component.minimize": "Küçültme düğmesini geri al",
    "DG.Redo.component.minimize": "Küçültme düğmesini yinele",
    "DG.Undo.dataContext.moveAttribute": "Durum tablosu özelliğini değiştirmeyi geri al",
    "DG.Redo.dataContext.moveAttribute": "Durum tablosu özelliğini değiştirmeyi yinele",
    "DG.DataContext.singleCaseName": "Durum",
    "DG.DataContext.pluralCaseName": "Durumlar",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "bir koleksiyon",
    "DG.DataContext.collapsedRowString": "%@1 arasında %@2",
    "DG.DataContext.noData": "Veri Yok",
    "DG.DataContext.baseName": "Veri_Seti_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "\"% @\" özelliği için formül düzenlenemez.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Bir formül oluşturabilmek için yeni bir özellik tanımlayın.",
    "DG.Formula.FuncCategoryArithmetic": "Aritmetik İşlemler",
    "DG.Formula.FuncCategoryConversion": "Diğer İşlemler",
    "DG.Formula.FuncCategoryDateTime": "Gün/Saat İşlemleri",
    "DG.Formula.FuncCategoryLookup": "Arama İşlemleri",
    "DG.Formula.FuncCategoryOther": "Diğer İşlemler",
    "DG.Formula.FuncCategoryRandom": "Diğer İşlemler",
    "DG.Formula.FuncCategoryStatistical": "İstatistiksel İşlemler",
    "DG.Formula.FuncCategoryString": "Dizi İşlemleri",
    "DG.Formula.FuncCategoryTrigonometric": "Trigonometrik İşlemler",
    "DG.Formula.DateLongMonthJanuary": "Ocak",
    "DG.Formula.DateLongMonthFebruary": "Şubat",
    "DG.Formula.DateLongMonthMarch": "Mart",
    "DG.Formula.DateLongMonthApril": "Nisan",
    "DG.Formula.DateLongMonthMay": "Mayıs",
    "DG.Formula.DateLongMonthJune": "Haziran",
    "DG.Formula.DateLongMonthJuly": "Temmuz",
    "DG.Formula.DateLongMonthAugust": "Ağustos",
    "DG.Formula.DateLongMonthSeptember": "Eylül",
    "DG.Formula.DateLongMonthOctober": "Ekim",
    "DG.Formula.DateLongMonthNovember": "Kasım",
    "DG.Formula.DateLongMonthDecember": "Aralık",
    "DG.Formula.DateShortMonthJanuary": "Oca",
    "DG.Formula.DateShortMonthFebruary": "Şub",
    "DG.Formula.DateShortMonthMarch": "Mar",
    "DG.Formula.DateShortMonthApril": "Nis",
    "DG.Formula.DateShortMonthMay": "May",
    "DG.Formula.DateShortMonthJune": "Haz",
    "DG.Formula.DateShortMonthJuly": "Tem",
    "DG.Formula.DateShortMonthAugust": "Ağu",
    "DG.Formula.DateShortMonthSeptember": "Eyl",
    "DG.Formula.DateShortMonthOctober": "Eki",
    "DG.Formula.DateShortMonthNovember": "Kas",
    "DG.Formula.DateShortMonthDecember": "Ara",
    "DG.Formula.DateLongDaySunday": "Pazar",
    "DG.Formula.DateLongDayMonday": "Pazartesi",
    "DG.Formula.DateLongDayTuesday": "Salı",
    "DG.Formula.DateLongDayWednesday": "Çarşamba",
    "DG.Formula.DateLongDayThursday": "Perşembe",
    "DG.Formula.DateLongDayFriday": "Cuma",
    "DG.Formula.DateLongDaySaturday": "Cumartesi",
    "DG.Utilities.date.localDatePattern": " (?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?)) ",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?) ",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ](?:[0-2]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d{3,6})?)(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Sözdizimi hatası: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Eksik ifade",
    "DG.Formula.SyntaxErrorInvalidOperator": "Geçersiz operatör '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "'%@' için geçersiz tür",
    "DG.Formula.TypeError.description": "'%@' için geçersiz tür",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' tanımlanamadı",
    "DG.Formula.VarReferenceError.description": "'%@' değişkeni tanımlanamadı",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "'%@' alt özelliği için geçersiz başvuru",
    "DG.Formula.HierReferenceError.description": "'%@' bir alt özelliktir ve sadece toplu bir işlevde kullanılabilir.",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' tanımlanamadı",
    "DG.Formula.FuncReferenceError.description": "'%@()' özelliği tanımlanamadı",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' 1 değişken gerektiriyor",
    "DG.Formula.FuncArgsErrorSingle.description": "'%@()' fonksiyonu 1 değişken gerektiriyor",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' gerektiriyor %@ değişken",
    "DG.Formula.FuncArgsErrorPlural.description": "'%@()' fonksiyonu %@ değişken gerektiriyor",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' gerektiriyor %@-%@ değişken",
    "DG.Formula.FuncArgsErrorRange.description": "'%@()' fonksiyonu %@-%@ değişken gerektiriyor",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "Bekleyen istek...",
    "DG.Formula.PendingRequest.description": "Bekleyen istek...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "İstek başarısız oldu (%@)",
    "DG.Formula.FailedRequest.description": "İstek başarısız oldu (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "Sınırlar bekliyor...",
    "DG.Formula.PendingBoundaries.description": "Sınırlar bekliyor...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "Sınırlar başarısız oldu (%@)",
    "DG.Formula.FailedBoundaries.description": "Sınırlar başarısız oldu (%@)",
    "DG.Formula.LookupDataSetError.message": "Tanınmayan veri seti: '%@'",
    "DG.Formula.LookupDataSetError.description": "'%@' veri seti tanınmadı",
    "DG.Formula.LookupAttrError.message": "'%@' bulunamadı '%@' veri setinin içinde",
    "DG.Formula.LookupAttrError.description": "'%@' özelliği '%@' veri setinin içinde bulunamadı",
    "DG.TableController.headerMenuItems.editAttribute": "Özellik Değerlerini Düzenle...",
    "DG.TableController.headerMenuItems.editFormula": "Formülü Düzenle...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Tekrar dağıt",
    "DG.TableController.headerMenuItems.sortAscending": "Artan Şekilde Sırala (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Azalan Şekilde Sırala (9→0, Z→A)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Özelliği Sil",
    "DG.TableController.newAttrDlg.defaultAttrName": "yeni_özellik",
    "DG.TableController.newAttrDlg.attrNameHint": "Yeni özellik için bir ad girin",
    "DG.TableController.newAttrDlg.formulaHint": "Bu özelliğin değerlerini hesaplamak için gerekiyorsa bir formül yazın",
    "DG.TableController.newAttrDlg.applyTooltip": "Yeni özelliği ad ve formül (isteğe bağlı) kullanarak tanımlayın",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Lütfen yeni özellik için bir ad girin",
    "DG.TableController.newAttrDialog.AttributesCategory": "Özellikler",
    "DG.TableController.newAttrDialog.SpecialCategory": "Özel",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Değerler",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Sabitler",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Fonksiyonlar",
    "DG.TableController.renameAttributeInvalidMsg": "Özellik adları boş bırakılamaz",
    "DG.TableController.renameAttributeInvalidDesc": "Lütfen geçerli bir özellik adı girin",
    "DG.TableController.renameAttributeDuplicateMsg": "Aynı isimde bir özellik zaten var",
    "DG.TableController.renameAttributeDuplicateDesc": "Lütfen yeni bir özellik adı girin",
    "DG.TableController.deleteAttribute.confirmMessage": "Özelliği silin '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "Bu işlem geri alınamaz.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Özelliği Sil",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "İptal Et",
    "DG.TableController.deleteDataSet.confirmMessage": "Bu veri setini sil ve yok et: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Bu işlem geri alınamaz.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Veri Setini Sil",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "İptal Et",
    "DG.TableController.attrEditor.unitHint": "Varsa, ölçü birimi",
    "DG.TableController.attrEditor.descriptionHint": "Özelliği tanımla",
    "DG.TableController.setScoreDlg.applyTooltip": "'%@' özelliği için formülü ayarla",
    "DG.TableController.setScoreDlg.formulaHint": "Bu niteliğin değerlerini hesaplamak için bir formül girin",
    "DG.TableController.newAttributeTooltip": "Bu tabloya yeni bir özellik girin",
    "DG.TableController.attributeEditor.title": "Özellik Değerleri",
    "DG.CaseTableDropTarget.dropMessage": "Yeni bir koleksiyon oluşturmak için özelliği çıkarın",
    "DG.CaseTable.defaultAttrName": "yeniÖzellik",
    "DG.CaseTable.indexColumnName": "indeks",
    "DG.CaseTable.indexColumnTooltip": "Koleksiyon içindeki sıra numarası (durumİndeksi)",
    "DG.CaseTable.indexMenu.insertCase": "Durum Ekle",
    "DG.CaseTable.indexMenu.insertCases": "Durumları Ekle...",
    "DG.CaseTable.indexMenu.deleteCase": "Durumu Sil",
    "DG.CaseTable.indexMenu.deleteCases": "Durumları Sil",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "sınıflamalı",
    "DG.CaseTable.attribute.type.categorical": "sınıflamalı",
    "DG.CaseTable.attribute.type.numeric": "sayısal",
    "DG.CaseTable.attribute.type.date": "tarih",
    "DG.CaseTable.attribute.type.qualitative": "nitel",
    "DG.CaseTable.attribute.type.boundary": "sınır",
    "DG.CaseTable.attributeEditor.name": "isim",
    "DG.CaseTable.attributeEditor.description": "açıklama",
    "DG.CaseTable.attributeEditor.type": "tür",
    "DG.CaseTable.attributeEditor.unit": "birim",
    "DG.CaseTable.attributeEditor.precision": "kesinlik",
    "DG.CaseTable.attributeEditor.editable": "düzenlenebilir",
    "DG.CaseTable.insertCasesDialog.title": "Durum Ekle",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# tane durum ekle:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "yer:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "önce",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "sonra",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Durum Ekle",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Belirtilen sayıda durum ekle",
    "DG.CaseTableController.allTables": "Tüm tablolar",
    "DG.AttrFormView.attrNamePrompt": "Özellik adı:",
    "DG.AttrFormView.formulaPrompt": "Formül:",
    "DG.AttrFormView.operandMenuTitle": "--- Değer Ekle ---",
    "DG.AttrFormView.functionMenuTitle": "--- Formül Ekle ---",
    "DG.AttrFormView.applyBtnTitle": "Uygula",
    "DG.AttrFormView.cancelBtnTitle": "İptal Et",
    "DG.AttrFormView.cancelBtnTooltip": "Herhangi bir değişiklik yapmadan iletişim kutusunu kapat",
    "DG.GuideConfigView.titlePrompt": "Rehber Başlığı",
    "DG.GuideConfigView.titleHint": "Etkinlik Adı",
    "DG.GuideConfigView.itemTitleHint": "Bölüm Adı",
    "DG.GuideConfigView.itemURLHint": "Bölümün URL'si",
    "DG.GuideConfigView.okBtnTitle": "Tamam",
    "DG.GuideConfigView.okBtnToolTip": "Rehber menü öğelerini kabul et",
    "DG.GuideConfigView.cancelBtnTitle": "İptal et",
    "DG.GuideConfigView.cancelBtnTooltip": "Herhangi bir değişiklik yapmadan iletişim kutusunu kapat",
    "DG.GuideConfigView.httpWarning": "URL http:// veya https:// ile başlamalıdır",
    "DG.DataDisplayModel.rescaleToData": "Verileri yeniden ölçeklendir",
    "DG.DataDisplayModel.ShowConnectingLine": "Bağlantı Doğrularını Göster",
    "DG.DataDisplayModel.HideConnectingLine": "Bağlantı Doğrularını Gizle",
    "DG.AxisView.emptyGraphCue": "Burayı tıklayın, veya buraya bir özellik sürükleyin.",
    "DG.CellLinearAxisView.midPanelTooltip": "Eksen ölçeğini çevirmek için sürükleyin",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Eksen alt sınırını değiştirmek için sürükleyin",
    "DG.CellLinearAxisView.upperPanelTooltip": "Eksen üst sınırını değiştirmek için sürükleyin",
    "DG.PlotModel.mixup": "Grafiği Karıştırın",
    "DG.PlotModel.showCount": "Sayımı Göster",
    "DG.PlotModel.hideCount": "Sayımı Gizle",
    "DG.ScatterPlotModel.sumSquares": "Kareler toplamı",
    "DG.ScatterPlotModel.slopeOnly": "eğim",
    "DG.ScatterPlotModel.yearsLabel": "yılda",
    "DG.ScatterPlotModel.daysLabel": "günde",
    "DG.ScatterPlotModel.hoursLabel": "saatte",
    "DG.ScatterPlotModel.minutesLabel": "dakikada",
    "DG.ScatterPlotModel.secondsLabel": "saniyede",
    "DG.LegendView.attributeTooltip": "Renklendirme özelliğini değiştirmek için tıklayın",
    "DG.NumberToggleView.showAll": "Tümünü göster –",
    "DG.NumberToggleView.hideAll": "Tümünü gizle –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Son",
    "DG.NumberToggleView.showAllTooltip": "Tüm durumları görmek için tıklayın\nGörünürlüğü değiştirmek için ana etiketlere tıklayın",
    "DG.NumberToggleView.hideAllTooltip": "Tüm durumları gizlemek için tıklayın\nGörünürlüğü değiştirmek için ana etiketlere tıklayın",
    "DG.NumberToggleView.enableLastModeTooltip": "Yalnızca son ana durumu görmek için tıklayın",
    "DG.NumberToggleView.disableLastModeTooltip": "Son ana durum modundan çıkmak için tıklayın",
    "DG.NumberToggleView.indexTooltip": "Görünürlüğü değiştirmek için tıklayın",
    "DG.PlottedAverageAdornment.meanValueTitle": "ortalama=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "ortanca=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SS, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "Çeyrekler arası açıklık=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "alt=%@\nQ1=%@\nortalama=%@\nQ3=%@\nüst=%@\nçeyrekler arası açıklık=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Renklendirme özelliği: %@",
    "DG.DataDisplayMenu.remove": "Özelliği Çıkar",
    "DG.DataDisplayMenu.removeAttribute_x": "X'i çıkar: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Y'yi çıkar: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Y'yi çıkar: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Renklendirme özelliğini çıkar: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Sınıflamalı veri olarak değerlendir",
    "DG.DataDisplayMenu.treatAsNumeric": "Sayısal veri olarak değerlendir",
    "DG.DataDisplayMenu.hide": "Gizle ve Göster",
    "DG.DataDisplayMenu.hideSelectedPlural": "Seçili Durumları Gizle",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Seçilmeyen Durumları Gizle",
    "DG.DataDisplayMenu.hideSelectedSing": "Seçili Durumu Gizle",
    "DG.DataDisplayMenu.hideUnselectedSing": "Seçilmeyen Durumu Gizle",
    "DG.DataDisplayMenu.enableNumberToggle": "Birincil Değişkenin Etiketlerini Göster",
    "DG.DataDisplayMenu.disableNumberToggle": "Birincil Değişkenin Etiketlerini Gizle",
    "DG.DataDisplayMenu.showAll": "Tüm Durumları Göster",
    "DG.DataDisplayMenu.snapshot": "Anlık Görüntü Al",
    "DG.GraphView.replaceAttribute": "%@ değerini %@ ile değiştir",
    "DG.GraphView.addAttribute": "%@ değerini ekle",
    "DG.GraphView.addToEmptyPlace": "%@ ile eksen oluştur",
    "DG.GraphView.addToEmptyX": "%@ ile X eksenini oluştur",
    "DG.GraphView.dropInPlot": "Noktaları boya %@ değerleri için\n",
    "DG.GraphView.zoomTip": "Yakınlaştırmak için çift tıklayın.\nUzaklaştırmak için Shift tuşunu basılı tutup çift tıklayın",
    "DG.GraphView.rescale": "Verileri yeniden ölçeklendir",
    "DG.AxisView.labelTooltip": "—%@ ekseni özelliğini değiştirmek için tıklayın",
    "DG.AxisView.vertical": "dikey",
    "DG.AxisView.horizontal": "yatay",
    "DG.DataTip.connectingLine": "%@: %@\nile %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formül",
    "DG.PlottedValue.namePrompt": "Çizilen Değer",
    "DG.PlottedValue.formulaPrompt": "değer =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Çizilen Değer",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Bir ifade yazın, örneğin x*x/30 - 50",
    "DG.MapView.showGrid": "Kareleri Göster",
    "DG.MapView.hideGrid": "Kareleri Gizle",
    "DG.MapView.showPoints": "Puanları Göster",
    "DG.MapView.hidePoints": "Puanları Gizle",
    "DG.MapView.marqueeHint": "İşaretleme aracı—Haritadaki seçili noktaları sürükleyin",
    "DG.MapView.gridControlHint": "Karelerin ölçüsünü değiştir",
    "DG.Inspector.values": "Ölçüm",
    "DG.Inspector.styles": "Biçimlendirme",
    "DG.Inspector.pointSize": "Nokta büyüklüğü:",
    "DG.Inspector.transparency": "Şeffaflık:",
    "DG.Inspector.color": "Renk:",
    "DG.Inspector.legendColor": "Renklendirmede kullanılacak renk:",
    "DG.Inspector.backgroundColor": "Arka plan rengi:",
    "DG.Inspector.stroke": "Dış hat çizgi:",
    "DG.Inspector.rescale.toolTip": "Ekranı tüm verileri göstermek için yeniden ölçeklendirin",
    "DG.Inspector.mixUp.toolTip": "Tüm noktaları karıştır",
    "DG.Inspector.hideShow.toolTip": "Tüm durumları göster veya seçili/seçilmeyen durumları gizle",
    "DG.Inspector.delete.toolTip": "Seçili/seçilmeyen durumları sil",
    "DG.Inspector.sliderValues.toolTip": "Sürgü animasyon yönünü, hızını ayarlayın …",
    "DG.Inspector.webViewEditURL.toolTip": "Görüntülenen web sayfasının URL'sini düzenleyin",
    "DG.Inspector.selection.selectAll": "Tüm Durumları Seç",
    "DG.Inspector.selection.deleteSelectedCases": "Seçili Durumları Sil",
    "DG.Inspector.selection.deleteUnselectedCases": "Seçilmeyen Durumları Sil",
    "DG.Inspector.deleteAll": "Tüm Durumları Sil",
    "DG.Inspector.deleteDataSet": "Veri Setini Sil ve Yok Et",
    "DG.Inspector.displayValues.toolTip": "Noktalarla birlikte gösterilenleri değiştirin",
    "DG.Inspector.displayStyles.toolTip": "Ekran görünümünü değiştirin",
    "DG.Inspector.makeImage.toolTip": "Resmi PNG dosyası olarak kaydet",
    "DG.Inspector.displayShow": "Göster ...",
    "DG.Inspector.colorPicker.more": "daha fazla",
    "DG.Inspector.colorPicker.less": "daha az",
    "DG.Inspector.graphTransparency": "Şeffaf",
    "DG.Inspector.graphCount": "Sayı",
    "DG.Inspector.graphPercent": "Yüzde",
    "DG.Inspector.graphRow": "Satır",
    "DG.Inspector.graphColumn": "Sütun",
    "DG.Inspector.graphCell": "Hücre",
    "DG.Inspector.graphConnectingLine": "Kesişen Doğrular",
    "DG.Inspector.graphMovableLine": "Hareketli Doğru",
    "DG.Inspector.graphInterceptLocked": "0 noktası Kilitli",
    "DG.Inspector.graphPlottedFunction": "Çizilen Fonksiyon",
    "DG.Inspector.graphSquares": "Artıkların Karesi",
    "DG.Inspector.graphLSRL": "En Küçük Kareler Doğrusu",
    "DG.Inspector.graphMovableValue": "Hareketli Değer",
    "DG.Inspector.graphAdd": "Ekle",
    "DG.Inspector.graphRemove": "Çıkar",
    "DG.Inspector.graphPlottedMean": "Ortalama",
    "DG.Inspector.graphPlottedMedian": "Ortanca",
    "DG.Inspector.graphPlottedStDev": "Standart Sapma",
    "DG.Inspector.graphPlottedIQR": "Çeyrekler Arası Açıklık",
    "DG.Inspector.graphPlottedBoxPlot": "Kutu Grafiği",
    "DG.Inspector.graphPlottedValue": "Çizilen Değer",
    "DG.Inspector.attributes.toolTip": "Yeni özellikler oluşturun. Durum verilerini dışa aktarın.",
    "DG.Inspector.resize.toolTip": "Verilerin sığması için tüm sütunları yeniden boyutlandır",
    "DG.Inspector.newAttribute": "Yeni Değer %@...",
    "DG.Inspector.randomizeAllAttributes": "Hepsini yeniden dağıt",
    "DG.Inspector.exportCaseData": "Durum Verilerini Dışa Aktar...",
    "DG.Inspector.mapGrid": "Kareler",
    "DG.Inspector.mapPoints": "Noktalar",
    "DG.Inspector.mapLines": "Kesişen Doğrular",
    "DG.GameController.continuityError": "Maalesef, durum tablosundaki sütunların sıralaması yapıldıktan sonra yeni veriler kabul edilemez.",
    "DG.GameView.loading": "Yükleniyor",
    "DG.GameView.loadError": "Bu metni görebiliyorsanız, yukarıdaki URL'yi yüklemek başarısız olmuş olabilir. Bağlantıyı başka bir tarayıcı sekmesinden kontrol edebilir veya hatayı http://codap.concord.org/help adresine tıklayarak bize bildirebilirsiniz.",
    "DG.Component.closeComponent.confirmCloseMessage": "Emin misiniz?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Evet, kapat",
    "DG.Component.closeComponent.cancelButtonTitle": "İptal et",
    "DG.GameController.confirmCloseDescription": "Bunu kapatırsanız, daha fazla veri ekleyemeyebilirsiniz.",
    "DG.WebView.defaultTitle": "İnternet Sayfası",
    "DG.mainPage.exceptionMessage": "Bu programın çalışmasını etkileyecek bir hata oluştu. Çalışmanızı kaydettikten sonra bu sayfayı yeniden yüklemek isteyebilirsiniz. (Hata: %@)",
    "DG.fileMenu.provider.examples.displayName": "Örnek Dokümanlar",
    "DG.ToolButtonData.pluginMenu.title": "Eklentiler",
    "DG.ToolButtonData.pluginMenu.toolTip": "Bir eklenti aracı aç",
    "DG.Undo.graph.showMovablePoint": "Hareketli noktayı göstermeyi geri al",
    "DG.Redo.graph.showMovablePoint": "Hareketli noktayı göstermeyi tekrarla",
    "DG.Undo.graph.hideMovablePoint": "Hareketli noktayı gizlemeyi geri al",
    "DG.Redo.graph.hideMovablePoint": "Hareketli noktayı gizlemeyi tekrarla",
    "DG.Undo.graph.moveMovablePoint": "Hareketli noktayı hareketlendirmeyi geri al",
    "DG.Redo.graph.moveMovablePoint": "Hareketli noktayı hareketlendirmeyi tekrarla",
    "DG.DataDisplayMenu.copyAsImage": "Çizim aracında aç",
    "DG.DataDisplayMenu.exportImage": "Resmi dışa aktar...",
    "DG.DataDisplayMenu.imageOfTitle": "Resmin %@",
    "DG.Inspector.graphMovablePoint": "Hareketli Nokta",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Bu veri seti için veri tablosu aç",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Yeni bir veri seti oluştur",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Bu veri setini sil ve imha et",
    "DG.Undo.graph.showAsBarChart": "Noktaları sütunlara dönüştürmeyi geri al",
    "DG.Redo.graph.showAsBarChart": "Noktaları sütunlara dönüştürmeyi yinele",
    "DG.Undo.graph.showAsDotChart": "Undo dispersing bars into dots",
    "DG.Redo.graph.showAsDotChart": "Redo dispersing bars into dots",
    "DG.CountAxisView.countLabel": "Sayı",
    "DG.CountAxisView.countLabelDescription": "Number of cases in the bar along this axis",
    "DG.CountAxisView.percentLabel": "Yüzde",
    "DG.CountAxisView.percentLabelDescription": "Percent of cases in the bar along this axis",
    "DG.BarChartModel.cellTipPlural": "%@ of %@ %@ (%@%) are %@",
    "DG.BarChartModel.cellTipSingular": "%@ of %@ %@ (%@%) is %@",
    "DG.Inspector.configuration": "Ayarlar",
    "DG.Inspector.displayConfiguration.toolTip": "Görünümü farklı biçimde ayarla",
    "DG.Inspector.displayScale": "Ölçek …",
    "DG.Inspector.graphBarChart": "Noktaları sütunlara dönüştür",
    "DG.Locale.name.de": "Almanca",
    "DG.Locale.name.en": "İngilizce",
    "DG.Locale.name.es": "İspanyolca",
    "DG.Locale.name.he": "İbranice",
    "DG.Locale.name.tr": "Türkçe",
    "DG.Locale.name.zh": "Geleneksel Çince",
    "DG.Undo.graph.swapCategories": "Kategorileri yeniden sıralamayı geri al",
    "DG.Redo.graph.swapCategories": "Kategorileri yeniden sıralamayı yinele",
    "DG.TableController.collectionTitleText": "%@1 (%@2 cases)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 cases, %@3 set aside)",
    "DG.Inspector.setaside.setAsideSelectedCases": "Set Aside Selected Cases",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Set Aside Unselected Cases",
    "DG.Inspector.setaside.restoreSetAsideCases": "Restore %@ Set Aside Cases",
    "DG.DocumentController.caseCardTitle": "Veri Kartı",
    "DG.DocumentController.toggleToCaseCard": "Veri kartı görünümüne geçiş yap",
    "DG.DocumentController.toggleToCaseTable": "Veri tablosu görünümüne geçiş yap",
    "DG.CaseCard.indexString": "1 of %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ selected of %@ %@",
    "DG.CaseCard.summaryValues": "%@ values",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Bir sonraki veriyi seç ve göster",
    "DG.CaseCard.navPrevCase": "Bir önceki veriyi seç ve göster",
    "DG.CaseCard.navFirstCase": "İlk veriyi seç ve göster",
    "DG.CaseCard.navLastCase": "Son veriyi seç ve göster",
    "DG.Undo.component.toggleTableToCard": "Veri tablosunu veri kartı görünümüyle göstermeyi geri al",
    "DG.Redo.component.toggleTableToCard": "Veri tablosunu veri kartı görünümüyle göstermeyi yinele",
    "DG.Undo.component.toggleCardToTable": "Veri kartını veri tablosu görünümüyle göstermeyi geri al",
    "DG.Redo.component.toggleCardToTable": "Veri kartını veri tablosu görünümüyle göstermeyi yinele",
    "DG.Undo.graph.addBackgroundImage": "Grafik arka plan resmi eklemeyi geri al",
    "DG.Redo.graph.addBackgroundImage": "Grafik arka plan resmi eklemeyi tekrarla",
    "DG.Undo.graph.removeBackgroundImage": "Grafik arka plan resmini silme eylemini geri al",
    "DG.Redo.graph.removeBackgroundImage": "Grafik arka plan resmini silme eylemini tekrarla",
    "DG.Undo.graph.lockBackgroundImage": "Eksenlere arka plan resmi kilitlemeyi geri al",
    "DG.Redo.graph.lockBackgroundImage": "Eksenlere arka plan resmi kilitlemeyi yinele",
    "DG.Undo.graph.unlockBackgroundImage": "Eksenlerden arka plan resmi kilidini açma eylemini geri al",
    "DG.Redo.graph.unlockBackgroundImage": "Eksenlerden arka plan resmi kilidini açma eylemini yinele",
    "DG.Undo.enableMeasuresForSelection": "Undo Show Measures For Selection",
    "DG.Redo.enableMeasuresForSelection": "Redo Show Measures For Selection",
    "DG.Undo.disableMeasuresForSelection": "Undo Hide Measures For Selection",
    "DG.Redo.disableMeasuresForSelection": "Redo Hide Measures For Selection",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Show Measures for Selection",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Hide Measures for Selection",
    "DG.DataDisplayMenu.addBackgroundImage": "Add Background Image",
    "DG.DataDisplayMenu.lockImageToAxes": "Lock Background Image to Axes",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Unlock Background Image from Axes",
    "DG.DataDisplayMenu.removeBackgroundImage": "Remove Background Image",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Formülü Sil (Değerleri Koruyarak)",
    "DG.TableController.headerMenuItems.recoverFormula": "Recover Deleted Formula",
    "DG.Inspector.displayLayers.toolTip": "Change the appearance of the map layers",
    "DG.Inspector.layers": "Layers",
    "DG.Undo.graph.repositionEquation": "Eşitliğin yerini değiştirmeyi geri al",
    "DG.Redo.graph.repositionEquation": "Eşitliğin yerini değiştirmeyi yinele",
    "DG.TableController.attrEditor.precisionNumericHint": "Number of digits after decimal point",
    "DG.TableController.attrEditor.precisionDateHint": "Determines how much of the date is displayed",
    "DG.TableController.attrEditor.typeHint": "Set to force the attribute to be treated as a certain type",
    "DG.TableController.attrEditor.nameHint": "Özelliğin adı durum tablosunda, kartında ve grafik eksenlerimde görünmektedir",
    "DG.TableController.attrEditor.editableHint": "Eğer özellik düzeltilebilir değilse, özelliğin değeri ve/veya formülü değiştirilemez",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "yıl ay gün saat dakika saniye milisaniye",
    "DG.AttributeFormat.DatePrecision.year": "YYYY",
    "DG.AttributeFormat.DatePrecision.month": "AAA YYYY",
    "DG.AttributeFormat.DatePrecision.day": "AAA G, YYY",
    "DG.AttributeFormat.DatePrecision.hour": "MMM D, YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "MMM D, YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "MMM D, YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@1 in %@2",
    "DG.CaseCard.attrHintDescription": "%@1: %@2",
    "DG.CaseCard.attrHintFormula": "%@1 = %@2",
    "DG.AppController.optionMenuItems.help-forum": "Yardım Forumu...",
    "DG.AppController.showHelpForumTitle": "Yardım Forumu",
    "DG.Locale.name.el": "Yunanca",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ of %@ (%@%) is %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ of %@ (%@%) are %@",
    "DG.DataDisplayMenu.removeAttribute_top": "Remove Side-by-side Layout by %@",
    "DG.DataDisplayMenu.removeAttribute_right": "Remove Vertical Layout by %@",
    "DG.GraphView.layoutPlotsSideBySide": "Layout side-by-side by %@",
    "DG.GraphView.layoutPlotsVertically": "Layout vertically by %@",
    "DG.Undo.graph.makeStrokeSameAsFill": "Dış hat çizgiyi kullanılan renkle aynı yapmayı geri al",
    "DG.Redo.graph.makeStrokeSameAsFill": "Dış hat çizgiyi kullanılan renkle aynı yapmayı yinele",
    "DG.Undo.graph.makeStrokeIndependent": "Dış hat çizgiyi kullanılan renkten bağımsız yapmayı geri al",
    "DG.Redo.graph.makeStrokeIndependent": "Dış hat çizgiyi kullanılan renkten bağımsız yapmayı yinele",
    "DG.Inspector.strokeSameAsFill": "Dış hat çizgiyi kullanılan renkle aynı yap",
    "DG.Formula.DateShortDaySunday": "Paz",
    "DG.Formula.DateShortDayMonday": "Pzt",
    "DG.Formula.DateShortDayTuesday": "Sa",
    "DG.Formula.DateShortDayWednesday": "Çar",
    "DG.Formula.DateShortDayThursday": "Per",
    "DG.Formula.DateShortDayFriday": "Cu",
    "DG.Formula.DateShortDaySaturday": "Cts",
    "DG.AttributeFormat.DatePrecision.millisecond": "AAA G, YYY SS:mm:ss.SSS",
    "DG.CellAxis.other": "DİĞER",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 MAD, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "Mean Absolute Deviation",
    "DG.Undo.graph.showPlottedBoxPlot": "Kutu grafiğini göstermeyi geri al",
    "DG.Redo.graph.hidePlottedBoxPlot": "Kutu grafiğini göstermeyi yinele",
    "DG.Undo.graph.hidePlottedBoxPlot": "Kutu grafiğini gizlemeyi geri al",
    "DG.Redo.graph.showPlottedBoxPlot": "Kutu grafiğini gizlemeyi yinele",
    "DG.Undo.graph.showOutliers": "Aykırı değerleri göstermeyi geri al",
    "DG.Redo.graph.hideOutliers": "Aykırı değerleri gizlemeyi yinele",
    "DG.Undo.graph.hideOutliers": "Aykırı değerleri gizlemeyi geri al",
    "DG.Redo.graph.showOutliers": "Aykırı değerleri göstermeyi yinele",
    "DG.Inspector.graphBoxPlotShowOutliers": "Aykırı değerleri göster",
    "DG.Locale.name.nb": "Bokmål",
    "DG.Locale.name.nn": "Nynorsk",
    "DG.CaseCard.newCaseToolTip": "Add an empty case to this collection",
    "DG.TableController.headerMenuItems.renameAttribute": "Yeniden isimlendir",
    "DG.Undo.graph.fuseDotsToRectangles": "Undo fusing dots into rectangles",
    "DG.Redo.graph.fuseDotsToRectangles": "Redo fusing dots into rectangles",
    "DG.Undo.graph.dissolveRectanglesToDots": "Undo dissolving rectangles into dots",
    "DG.Redo.graph.dissolveRectanglesToDots": "Redo dissolving rectangles into dots",
    "DG.Undo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Redo.graph.changeBreakdownType": "Redo changing scale type",
    "DG.Undo.graph.showAsBinnedPlot": "Undo grouping dots into bins",
    "DG.Redo.graph.showAsBinnedPlot": "Redo grouping dots into bins",
    "DG.Undo.graph.showAsDotPlot": "Undo ungrouping dots from bins",
    "DG.Redo.graph.showAsDotPlot": "Redo ungrouping dots from bins",
    "DG.Undo.graph.dragBinBoundary": "Undo dragging bin boundary",
    "DG.Redo.graph.dragBinBoundary": "Redo dragging bin boundary",
    "DG.Undo.graph.changeBinWidth": "Grup genişliğini değiştirmeyi geri al",
    "DG.Redo.graph.changeBinWidth": "Grup genişliğini değiştirmeyi tekrarla",
    "DG.Undo.graph.changeBinAlignment": "Undo changing bin alignment",
    "DG.Redo.graph.changeBinAlignment": "Redo changing bin alignment",
    "DG.BinnedPlotModel.dragBinTip": "Grup genişliğini değiştirmek için sürükleyiniz",
    "DG.HistogramView.barTipPlural": "%@ / %@ %@ (%@%) oranında veri ≥ %@ ve < %@",
    "DG.HistogramView.barTipSingular": "%@ of %@ %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendSingular": "%@ of %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendPlural": "%@ of %@ (%@%) are ≥ %@ and < %@",
    "DG.Inspector.graphGroupIntoBins": "Group into Bins",
    "DG.Inspector.graphBinWidth": "Grup genişliği",
    "DG.Inspector.graphAlignment": "Alignment",
    "DG.CaseTable.dividerView.expandAllTooltip": "expand all groups",
    "DG.CaseTable.dividerView.expandGroupTooltip": "expand group",
    "DG.CaseTable.dividerView.collapseAllTooltip": "collapse all groups",
    "DG.CaseTable.dividerView.collapseGroupTooltip": "collapse group",
    "DG.BinnedPlotModel.binLabelTip": "Bu gruptaki değerler ≥ %@ ve < %@",
    "DG.Component.closeComponent.toolTip": "Close this Component",
    "DG.Component.minimizeComponent.toolTip": "Minimize or expand this Component",
    "DG.Locale.name.ja": "Japonca",
    "DG.CaseCard.attrHintDescriptionAndFormula": "%@1: %@2\n%@1 = %@3",
    "DG.Locale.name.zh-Hans": "Basitleştirilmiş Çince",
    "DG.PlottedCount.withoutSelection": "%@",
    "DG.PlottedCount.withSelection": "%@ seçili",
    "DG.PlottedPercent.withoutSelection": "%@%",
    "DG.PlottedPercent.withSelection": "%@% seçili",
    "DG.PlottedCountPercent.withoutSelection": "%@ (%@%)",
    "DG.PlottedCountPercent.withSelection": "%@ nın %@ (%@%) seçili",
    "DG.Undo.caseTable.resizeColumn": "Undo fit width to content",
    "DG.Redo.caseTable.resizeColumn": "Redo fit width to content",
    "DG.TableController.headerMenuItems.resizeColumn": "Fit width to content",
    "DG.SelectedInfoView.infoPlural": "Showing measures for %@ selected cases",
    "DG.SelectedInfoView.infoSing": "Showing measures for %@ selected case",
    "DG.Inspector.copyCaseDataToClipboard": "Panoya kopyala...",
    "DG.Inspector.caseTable.exportCaseDialog.copyFrom": "Copy case data from:",
    "DG.Inspector.caseTable.exportCaseDialog.copy": "Kopyala",
    "DG.Inspector.caseTable.exportCaseDialog.copyTooltip": "Panoya veri kopyala",
    "DG.Inspector.caseTable.exportCaseDialog.copiedData": "Panoya %@ kopyalandı",
    "DG.Undo.caseTable.hideAttribute": "Gizlenen özelliği geri al",
    "DG.Redo.caseTable.hideAttribute": "Gizlenen özelliği yinele",
    "DG.Undo.caseTable.showAllHiddenAttributes": "Tüm gizlenen özellikleri göstermeyi geri al",
    "DG.Redo.caseTable.showAllHiddenAttributes": "Tüm gizlenen özellikleri göstermeyi yinele",
    "DG.TableController.headerMenuItems.hideAttribute": "Özelliği Gizle",
    "DG.Inspector.attributes.showAllHiddenAttributesSing": "Gizlenen %@ Özelliği Göster",
    "DG.Inspector.attributes.showAllHiddenAttributesPlural": "Gizlenen %@ Özellikleri Göster",
    "DG.Inspector.attributes.showAllHiddenAttributesDisabled": "Gizlenen Özellikleri Göster",
    "DG.Inspector.getCaseDataFromClipboard": "Panodan veri içe aktar...",
    "DG.CaseCard.addCaseButton": "durum ekle",
    "DG.Undo.DataContext.join": "Undo join of %@ to %@",
    "DG.Redo.DataContext.join": "Redo join of %@ to %@",
    "DG.Collection.joinTip": "Join %@ in %@ to %@ in %@ by matching %@ with %@",
    "DG.Inspector.graphPlotPoints": "Points",
    "DG.Inspector.graphBarForEachPoint": "Her nokta için sütun oluştur",
    "DG.Undo.graph.changeBarChartFunction": "Undo change bar chart formula",
    "DG.Redo.graph.changeBarChartFunction": "Redo change bar chart formula",
    "DG.Undo.graph.showAsLinePlot": "Her nokta için sütun oluşturmayı geri al",
    "DG.Redo.graph.showAsLinePlot": "Her nokta için sütun oluşturmayı tekrarla",
    "DG.Undo.graph.showAsStandardBarChart": "Undo using count or percent for bar chart scale",
    "DG.Redo.graph.showAsStandardBarChart": "Redo using count or percent for bar chart scale",
    "DG.Undo.graph.showAsComputedBarChart": "Undo computing bar length with formula",
    "DG.Redo.graph.showAsComputedBarChart": "Redo computing bar length with formula",
    "DG.FormulaAxisView.labelDescription": "Sütunların uzunluğunu belirleyen ifade. Düzenlemek için tıklayınız.",
    "DG.ComputedBarChartModel.cellTip": "For group %@ the value is %@",
    "DG.BarChartFunction.namePrompt": "Sütun Grafiği",
    "DG.BarChartFunction.formulaPrompt": "sütun genişliği =",
    "DG.BarChartFunction.formulaHint": "Sütun genişliğini hesaplamak için bir formül giriniz",
    "DG.BarChartFunction.emptyExpressionAxisPrompt": "Bir formül girmek için buraya tıklayınız",
    "DG.Inspector.graphFormula": "Formül",
    "DG.Undo.displayOnlySelected": "Undo displaying only selected cases",
    "DG.Redo.displayOnlySelected": "Redo displaying only selected cases",
    "DG.Undo.webView.show": "Undo adding webView component",
    "DG.Redo.webView.show": "Redo adding webView component",
    "DG.Undo.imageComponent.show": "Undo adding image component",
    "DG.Redo.imageComponent.show": "Redo adding image component",
    "DG.DataDisplayMenu.displayOnlySelected": "Display Only Selected Cases",
    "DG.DataDisplayMenu.displayingOnlySelected": "Displaying Only Selected Cases",
    "DG.PlotBackgroundView.msg0": "This graph is set to display",
    "DG.PlotBackgroundView.msg1": "sadece seçili durumlar.",
    "DG.PlotBackgroundView.msg2": "Hiçbir durum seçilmedi",
    "DG.PlotBackgroundView.msg3": "so nothing is being displayed.",
    "DG.PlotBackgroundView.msg4": "You can select cases in a",
    "DG.PlotBackgroundView.msg5": "durum tablosu veya diğer grafik.",
    "DG.ImageComponent.defaultTitle": "Resim",
    "DG.TableController.datasetMetadata.title": "Veri Seti Bilgisi",
    "DG.CaseTable.datasetMetadata.url": "kaynak",
    "DG.CaseTable.datasetMetadata.creationDate": "tarih içe aktar",
    "DG.TableController.datasetMetadata.descriptionHint": "Veri setini açıkla",
    "DG.Inspector.datasetInfo.toolTip": "Veri seti hakkındaki bilgiyi göster",
    "DG.CaseTable.indexMenu.moveEntryRow": "Buraya veri giriş satırı ekle",
    "DG.CaseCard.deselect": "Tüm durumları seçmeyi kaldır",
    "DG.CaseCard.noDeselect": "Hiçbir durum seçilmedi",
    "DG.CaseTable.indexProto.tooltip": "Bu tablonun içine veri girdisi yerleştirmek için sürükleyiniz",
    "DG.AttributeFormat.DatePrecisionShort.year": "YYYY",
    "DG.AttributeFormat.DatePrecisionShort.month": "A/YY",
    "DG.AttributeFormat.DatePrecisionShort.day": "A/G/YY",
    "DG.AttributeFormat.DatePrecisionShort.hour": "A/G/YY SS:00",
    "DG.AttributeFormat.DatePrecisionShort.minute": "A/G/YY SS:dd",
    "DG.AttributeFormat.DatePrecisionShort.second": "A/G/YY SS:dd:ss",
    "DG.AttributeFormat.DatePrecisionShort.millisecond": "A/G/YY SS:dd:ss.SSS",
    "DG.Formula.FuncCategoryLogic": "Mantık Fonksiyonları",
    "DG.Undo.graph.showMeasureLabels": "Ölçüm etiketlerini göstermeyi geri al",
    "DG.Redo.graph.showMeasureLabels": "Ölçüm etiketlerini göstermeyi yinele",
    "DG.Undo.graph.hideMeasureLabels": "Ölçüm etiketlerini gizlemeyi geri al",
    "DG.Redo.graph.hideMeasureLabels": "Ölçüm etiketlerini gizlemeyi yinele",
    "DG.Inspector.showLabels": "Ölçüm etiketlerini göster",
    "DG.Undo.caseTable.resizeOneColumn": "Sütun boyutlandırmayı geri al",
    "DG.Redo.caseTable.resizeOneColumn": "Sütun boyutlandırmayı yinele",
    "DG.CaseTable.attribute.type.checkbox": "onay kutusu",
    "DG.AppController.caseTableMenu.clipboardDataset": "-- panodan yeni tablo --",
    "DG.AppController.caseTableMenu.clipboardDatasetToolTip": "Panodan veri seti yapıştır",
    "DG.AppController.optionMenuItems.toPrivacyPage": "Gizlilik Sayfası...",
    "DG.plugin.Importer.title": "CODAP'a CSV'yi içe aktar",
    "DG.plugin.Importer.enter-url": "Enter url: ",
    "DG.plugin.Importer.or": "veya",
    "DG.plugin.Importer.downsample-section": "Downsample Options...",
    "DG.plugin.Importer.downsample-random-p1": "Rastgele seç",
    "DG.plugin.Importer.downsample-random-p2": "satırlar",
    "DG.plugin.Importer.downsample-every-nth-p1": "Seç her",
    "DG.plugin.Importer.downsample-every-nth-p2": "-inci satır",
    "DG.plugin.Importer.downsample-import-all": "Tüm satırları içe aktar",
    "DG.plugin.Importer.target-options-title": "Hedef Seçenekler...",
    "DG.plugin.Importer.target-options-replace": "Var olan veri setini bununla değiştir",
    "DG.plugin.Importer.target-options-append": "Bu veri setini varolana ekle",
    "DG.plugin.Importer.target-options-create-new": "Yeni veri seti oluştur",
    "DG.plugin.Importer.button-cancel": "İptal et",
    "DG.plugin.Importer.button-submit": "Tamam",
    "DG.plugin.Importer.button-dismiss": "Göz ardı et",
    "DG.plugin.Importer.load-error": "Bu kaynağın yüklenmesinde hata oluştu: \"%@\" reason: \"%@\"",
    "DG.plugin.Importer.no-table-error": "CODAP'a yüklenebilecek bir formatta tablosal veri bulunamadı",
    "DG.plugin.Importer.duplicate-dataset-msg": "Bunun gibi zaten bir veri seti var. Veri setinin adı \"%@\".",
    "DG.plugin.Importer.upload-time-msg": "Yüklendi %@",
    "DG.plugin.Importer.large-file-msg": "The imported file, \"%@\" has %@ rows. With more than %@ rows CODAP performance may be sluggish. You can work with a sample of the data at least at first, replacing it with the full dataset later.",
    "DG.plugin.Importer.error-codap-connection": "Error sending data to CODAP",
    "DG.plugin.Importer.error-upload": "Bu dosyayı içe aktaramadı -- %@",
    "DG.plugin.Importer.import-message": "Preparing to import %@ rows into \"%@\" from a table with %@ attributes: %@%@",
    "DG.Undo.component.componentTitleChange": "Undo changing the component title",
    "DG.Redo.component.componentTitleChange": "Redo changing the component title",
    "DG.TableController.collectionTitleText-nonempty": "%@1 (%@2 nonempty cases)",
    "DG.TableController.collectionTitleTextWithSetAside-nonempty": "%@1 (%@2 nonempty cases, %@3 set aside)",
    "DG.CaseTable.closedGroup.summary": "%@1 %@2",
    "DG.CaseTable.closedGroup.summary-nonempty": "%@1 nonempty %@2",
    "DG.DataDisplayMenu.exportPngImage": "PNG resmini dışa aktar...",
    "DG.DataDisplayMenu.exportSvgImage": "SVG resmini dışa aktar...",
    "DG.plugin.StoryBuilder.pluginName": "Hikâye Oluşturucu",
    "DG.plugin.StoryBuilder.description": "Araştırmanızın anlatısını oluşturun.",
    "DG.plugin.StoryBuilder.controlArea.discardAlt": "Değişiklikleri sil",
    "DG.plugin.StoryBuilder.controlArea.discardTooltip": "Discard changes to this moment",
    "DG.plugin.StoryBuilder.controlArea.saveAlt": "Kaydet",
    "DG.plugin.StoryBuilder.controlArea.saveTooltip": "Save this moment",
    "DG.plugin.StoryBuilder.controlArea.newAlt": "Make a new moment",
    "DG.plugin.StoryBuilder.controlArea.newTooltip": "Add a new moment to the right",
    "DG.plugin.StoryBuilder.dialog.optOutCheckbox": "Don't ask me again (always save)",
    "DG.plugin.StoryBuilder.emptyMoment.createAlt": "make new moment",
    "DG.plugin.StoryBuilder.emptyMoment.createTitle": "Click to make a new moment",
    "DG.plugin.StoryBuilder.buttons.helpAlt": "yardım al",
    "DG.plugin.StoryBuilder.buttons.helpTitle": "Hikâye Oluşturucu kullanımına yönelik yardı al",
    "DG.plugin.StoryBuilder.buttons.autoSaveTitleAuto": "Currently will automatically save changes to moments. Click to be asked whether to save or discard.",
    "DG.plugin.StoryBuilder.buttons.autoSaveTitleManual": "Currently will ask to save or discard changes to moments. Click to automatically save changes without asking.",
    "DG.plugin.StoryBuilder.momentComponent.deleteAlt": "Delete this moment",
    "DG.plugin.StoryBuilder.momentComponent.deleteTitle": "Delete this moment",
    "DG.plugin.StoryBuilder.momentTextboxContent": "Ne yaptınız? Niçin yaptınız?",
    "DG.plugin.StoryBuilder.momentTextboxFirstContent": "Burası veri hikâyenizin başlangıç kısmı.",
    "DG.plugin.StoryBuilder.momentManager.firstTitle": "başlat ...",
    "DG.plugin.StoryBuilder.momentManager.nextTitle": "moment title",
    "DG.plugin.StoryBuilder.storyArea.dialog.cancel": "İptal et",
    "DG.plugin.StoryBuilder.storyArea.dialog.discard": "Göz ardı et",
    "DG.plugin.StoryBuilder.storyArea.dialog.save": "Kaydet",
    "DG.plugin.StoryBuilder.storyArea.qClickAnotherMomentPrompt": "Değişiklikleri kaydet ya da sil?",
    "DG.plugin.StoryBuilder.storyArea.qClickAnotherMomentExplanation": "You have made changes to Moment %@. Would you like to save or discard these changes?",
    "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentPrompt": "Save changes before creating Moment %@?",
    "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentExplanation": "You have made changes to Moment %@. Would you like to save those changes to both Moments %@ and %@ or only to the new Moment %@?",
    "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentTwoMoments": "Moments %@ and %@",
    "DG.plugin.StoryBuilder.storyArea.qDupNotLastMomentOneMoment": "Only Moment %@",
    "DG.plugin.StoryBuilder.storyArea.qRevertPrompt": "Değişiklikleri sil?",
    "DG.plugin.StoryBuilder.storyArea.qRevertExplanation": "Would you like to discard the changes you made to Moment %@ (and revert to the state it was in before you made changes)?",
    "DG.plugin.StoryBuilder.storyArea.qClickLockPrompt": "Değişiklikleri kaydet ya da sil?",
    "DG.plugin.StoryBuilder.storyArea.qClickLockExplanation": "You have made changes to Moment %@. Would you like to save or discard these changes?",
    "DG.plugin.Scrambler.name": "scrambler",
    "DG.plugin.Scrambler.description": "Rastgele değişen bir özellikliğe göre hipotezleri test et.",
    "DG.plugin.Scrambler.language": "İngilizce",
    "DG.plugin.Scrambler.static.scramblerTitle": "Scrambler",
    "DG.plugin.Scrambler.static.cantScrambleStripe": "İlerleyebilmek için düzeltiniz.",
    "DG.plugin.Scrambler.static.howManyLabel": "ne kadar?",
    "DG.plugin.Scrambler.static.scrambledDataButtonName": "show scrambled",
    "DG.plugin.Scrambler.sScramble": "scramble",
    "DG.plugin.Scrambler.sNoAttribute": "özellik yok 😕",
    "DG.plugin.Scrambler.sIterationAttName": "batch",
    "DG.plugin.Scrambler.sIterationAttDescription": "Which \"batch\" of data. Increases every time you scramble.",
    "DG.plugin.Scrambler.sScrambledAttName": "scrambled att",
    "DG.plugin.Scrambler.sScrambledAttDescription": "Which attribute was scrambled.",
    "DG.plugin.Scrambler.sNoDataset": "Find a dataset and drag the attribute here that you want to scramble!",
    "DG.plugin.Scrambler.sNoScrambleAttribute": "What attribute do you want to scramble? Drag it in here.",
    "DG.plugin.Scrambler.shShowScrambledButtonHelpText": "Show one scrambled dataset",
    "DG.plugin.Scrambler.sfScrambledAttribute": "<span>scramble <code>%@1</code></span>",
    "DG.plugin.Scrambler.sfOKtoScramble": "<span>OK to scramble <code>%@1</code> in dataset <code>%@2</code></span>",
    "DG.plugin.Scrambler.sfNoMeasure": "<span>Your dataset, <code>%@1</code>, needs a measure, which is probably an attribute with a formula. Drag that attribute to the left so you have something to collect!</span>",
    "DG.plugin.Scrambler.sfFormulaProblem": "<span>Scrambling <code>%@1</code> won't work because it has a formula. Drag in a different attribute from the last collection (%@2), such as <code>%@3</code>.</span>",
    "DG.plugin.Scrambler.sfNotALeafProblem": "<span>Scrambling <code>%@1</code> won't work because it's not in the last collection (<code>%@2</code>). Drop an attribute here from <code>%@2</code>, such as <code>%@3</code>.</span>",
    "DG.plugin.Scrambler.sOr": "veya",
    "DG.plugin.Scrambler.sScrambledDatasetPrefix": "scrambled_",
    "DG.plugin.Scrambler.sMeasureDatasetPrefix": "_den_ölçer_",
    "DG.plugin.Sampler.title": "Örneklemleyici",
    "DG.plugin.Sampler.description": "Sıfırdan başlayarak ya da var olan veri setinden rastgele veri seti oluştur.",
    "DG.plugin.Sampler.tab.sampler": "Örneklemleyici",
    "DG.plugin.Sampler.tab.options": "Seçenekler",
    "DG.plugin.Sampler.tab.about": "Hakkında",
    "DG.plugin.Sampler.top-bar.run": "BAŞLAT",
    "DG.plugin.Sampler.top-bar.stop": "DURDUR",
    "DG.plugin.Sampler.top-bar.pause": "DURAKLAT",
    "DG.plugin.Sampler.top-bar.medium-speed": "Orta",
    "DG.plugin.Sampler.draw-settings.select-items-p1": "Seç",
    "DG.plugin.Sampler.draw-settings.select-items-p2": "veri topla",
    "DG.plugin.Sampler.draw-settings.collect-samples-p1": "Topla",
    "DG.plugin.Sampler.draw-settings.collect-samples-p2": "örneklemler",
    "DG.plugin.Sampler.model-controls.add-variable-title": "Karıştırıcı'ya bir sonraki girdiyi ekle",
    "DG.plugin.Sampler.model-controls.remove-variable-title": "Karıştırıcı'ya eklenen en son girdiyi çıkar",
    "DG.plugin.Sampler.model-controls.add-series-title": "Specify a series of labels for items",
    "DG.plugin.Sampler.model-controls.select-collection-loading": "Toplananlar yükleniyor...",
    "DG.plugin.Sampler.reset-title": "Delete all data and extra item-level attributes",
    "DG.plugin.Sampler.reset-text": "VERİLERİ TEMİZLE",
    "DG.plugin.Sampler.device-selection.mixer": "Karıştırıcı",
    "DG.plugin.Sampler.device-selection.spinner": "Çark",
    "DG.plugin.Sampler.device-selection.collector": "Veri ünitesi",
    "DG.plugin.Sampler.spinner-cover-alt": "şeffaf yüz",
    "DG.plugin.sampler.speed.slow": "Yavaş",
    "DG.plugin.sampler.speed.medium": "Orta",
    "DG.plugin.sampler.speed.fast": "Hızlı",
    "DG.plugin.sampler.speed.Fastest": "En hızlı",
    "DG.plugin.sampler.collector.noDatasets": "Veri seti yok",
    "DG.plugin.Sampler.selection-options.select-cases": "Durumları seç",
    "DG.plugin.Sampler.selection-options.with-replacement": "tekrarlı",
    "DG.plugin.Sampler.selection-options.without-replacement": "tekrarsız",
    "DG.plugin.Sampler.hide-options.hide": "Modeli gizle",
    "DG.plugin.Sampler.password-options.lock-title": "Şifre kullanarak ayarları kilitle:",
    "DG.plugin.Sampler.password-options.lock": "Kilitle",
    "DG.plugin.Sampler.password-options.unlock-title": "Şifreyle ayarların kilidini aç:",
    "DG.plugin.Sampler.password-options.unlock": "Kilidi aç",
    "DG.plugin.Sampler.password-options.password-failed": "Şifre yanlış.",
    "DG.plugin.Sampler.options.reload": "Başlangıç ayarlarını yeniden yükle",
    "DG.plugin.Sampler.about.paragraph1": "CODAP'ın Örneklemleyici eklentisi, bir karıştırıcıya yerleştirilen girdileri rastgele seçebilir, çarkta yer alan daire dilimine göre veri toplayabilir ya da bir veri kümesinden veri seçebilir.",
    "DG.plugin.Sampler.about.item1": "<b>Seç &lt;n&gt; nesneler</b> örneklem sayısını belirler,",
    "DG.plugin.Sampler.about.item2": "<b>Collect &lt;n&gt; samples</b> controls how many samples to repeat in a given experiment.",
    "DG.plugin.Sampler.about.paragraph2.1": "Örnekleme hızının yanı sıra tekrarlı ya da tekrarsız örnekleme yapılıp yapılmayacağı (Seçenekler sekmesinde) ayarlanabilir. Örneklemleyicide oluşturulan veriler hiyerarşik bir tabloda sunulmaktadır. Tablodaki en üst düzey deneyi temsil eder (bir simülasyonun tamamen çalıştırılması) ve deneyin tamamına ilişkin istatistikleri hesaplamanıza olanak tanır. Bir sonraki seviye, her bir örneklem hakkında bilgi sunar ve örneklemlerle ilgili istatistiklerin hesaplanmasına olanak sağlar. Öğe düzeyi Örnekleyiciden alınan her bir değeri gösterir. Bu␣",
    "DG.plugin.Sampler.about.paragraph2.2": " explains Sampler basics.",
    "DG.plugin.Sampler.about.tutorial-link-text": "öğretici video",
    "DG.plugin.Sampler.about.paragraph3.1": "The Sampler in CODAP was inspired by the Sampler in",
    "DG.plugin.Sampler.about.paragraph3.2": ". It was developed by ",
    "DG.plugin.Sampler.about.paragraph3.3": " a part of the ",
    "DG.plugin.Sampler.about.paragraph3.4": "with support by the National Science Foundation under Grant No. DUE <span style=\"color:red;\">1625713</span> awarded to North Carolina State University.",
    "DG.plugin.Sampler.about.paragraph3.6": " Any opinions, findings, and conclusions or recommendations in this material are those of the principal investigators and do not necessarily reflect the views of the National Science Foundation.",
    "DG.plugin.Sampler.about.tinkerPlots-link-text": "TinkerPlots",
    "DG.plugin.Sampler.about.concord-link-text": "Concord Birliği",
    "DG.plugin.Sampler.about.esteem-link-text": "ESTEEM projesi",
    "DG.plugin.Sampler.about.esteem-logo-text": "Esteem logosu",
    "DG.plugin.Sampler.sample-list.parse-error": "Üzgünüz. Girdiğiniz ifadeyi uygulayamadık. Kullanabileceğiniz birkaç geçerli liste ve bir dizi ifade şu şekildedir: 'a,b,b,b', 'kedi,kedi,köpek', '1-50', '-5 ila 5', '1.0 ila 5.0', veya 'A-Z'",
    "DG.plugin.Sampler.sample-list.prompt": "Bir liste (örn. 'cat, cat, dog') veya bir aralık (örn. '1-50', '-5 %@1 5', '1.0 %@1 5.0', 'A-Z' ) giriniz..",
    "DG.plugin.Sampler.sample-list.initial-value": "a %@1 c",
    "DG.plugin.Sampler.range-word": "ila",
    "DG.plugin.Sampler.dataset.name": "Örneklemleyici",
    "DG.plugin.Sampler.dataset.experiment-collection-name": "deneyler",
    "DG.plugin.Sampler.dataset.sample-collection-name": "örneklemler",
    "DG.plugin.Sampler.dataset.item-collection-name": "items",
    "DG.plugin.Sampler.dataset.attr-experiment": "deney",
    "DG.plugin.Sampler.dataset.attr-description": "açıklama",
    "DG.plugin.Sampler.dataset.attr-sample_size": "örneklem_büyüklüğü",
    "DG.plugin.Sampler.dataset.attr-sample": "örneklem",
    "DG.plugin.Sampler.dataset.attr-value": "değer",
    "DG.plugin.Sampler.dataset.col-experiments": "deneyler",
    "DG.plugin.Sampler.dataset.col-samples": "örneklemler",
    "DG.plugin.Sampler.dataset.col-items": "deneyin çıktıları",
    "DG.plugin.sampler.experiment.description": "%@1'da yer alan %@2 %@3%@4(%@5)",
    "DG.plugin.sampler.experiment.no-description": "gizli!",
    "DG.plugin.sampler.experiment.description-mixer-item-kind": "girdi",
    "DG.plugin.sampler.experiment.description-spinner-item-kind": "bölümler",
    "DG.plugin.sampler.experiment.description-collector-item-kind": "durumlar",
    "DG.plugin.sampler.experiment.description-collector-phrase": " from %@1 ",
    "DG.plugin.sampler.experiment.description-replacement-phrase": "tekrarlı",
    "DG.plugin.sampler.experiment.description-no-replacement-phrase": "tekrarsız",
    "DG.plugin.DrawTool.title": "Çizim Aracı",
    "DG.plugin.DrawTool.description": "Resme açıklama ekle.",
    "DG.plugin.MicrodataPortal.title": "Mikro Veri Portalı",
    "DG.plugin.MicrodataPortal.description": "ABD nüfus sayımı popülasyonlarını bireysel düzeyde inceleyin.",
    "DG.plugin.NOAA-weather.title": "NOAA Hava Durumu",
    "DG.plugin.NOAA-weather.description": "Tarihsel hava durumu gidişatını inceleyin.",
    "DG.plugin.Choosy.title": "Seçici",
    "DG.plugin.Choosy.description": "Çok özellikli veri setlerini düzenle ve sadeleştir.",
    "DG.plugin.Transformers.title": "Dönüştürücüler",
    "DG.plugin.Transformers.description": "Güçlü araç koleksiyonuna sahip veri setlerini dönüştür.",
    "DG.Locale.name.ko": "Korece",
    "DG.Locale.name.pl": "Lehçe",
    "DG.Undo.graph.showICI": "İnformel güven aralığını göstermeyi geri al",
    "DG.Redo.graph.hideICI": "İnformel güven aralığını gizlemeyi tekrarla",
    "DG.Undo.graph.hideICI": "İnformel güven aralığını gizlemeyi geri al",
    "DG.Redo.graph.showICI": "İnformel güven aralığını göstermeyi tekrarla",
    "DG.Undo.graph.showPlottedStErr": "Undo showing standard error",
    "DG.Redo.graph.showPlottedStErr": "Redo showing standard error",
    "DG.Undo.graph.hidePlottedStErr": "Undo hiding standard error",
    "DG.Redo.graph.hidePlottedStErr": "Redo hiding standard error",
    "DG.Undo.graph.setNumStErrs": "Undo setting the number of standard errors",
    "DG.Redo.graph.setNumStErrs": "Redo setting the number of standard errors",
    "DG.Undo.graph.showPlottedNormal": "Undo showing normal curve",
    "DG.Redo.graph.hidePlottedNormal": "Redo hiding normal curve",
    "DG.Undo.graph.hidePlottedNormal": "Undo hiding normal curve",
    "DG.Redo.graph.showPlottedNormal": "Redo showing normal curve",
    "DG.ScatterPlotModel.LSRLCIBandInfo": "Shaded regions shows the range\n in which the true regression line\n lies at 95% confidence level.",
    "DG.PlottedAverageAdornment.stErrValueTitle": "±%@ SE, %@",
    "DG.Inspector.graphLSRLSlopeCI": "Show Confidence Bands",
    "DG.Inspector.graphSpreadOptions": "Measures of Spread",
    "DG.Inspector.graphPlottedStErr": "Standard Error",
    "DG.Inspector.graphPlottedNormal": "Normal Curve",
    "DG.Inspector.graphPlottedGaussianFit": "Gaussian Fit"
});