dist: trusty
sudo: false
language: node_js
node_js: lts/*
before_install:
- pyenv local 3.6
- sudo apt-get install jq
install:
- travis_retry gem install bundler
- travis_retry bundle install
- travis_retry gem install s3_website
- travis_retry pip install awscli --upgrade --user
- travis_retry npm ci
- travis_retry
script:
- git clone https://github.com/concord-consortium/codap-data.git ../codap-data
- git clone https://github.com/concord-consortium/codap-data-interactives.git ../codap-data-interactives
# ideally, the `npm install` would be handled by the script, so we wouldn't have to do this here
- cd ../codap-data-interactives/onboarding
- npm install
- cd ../../codap
- npm run build:travis
after_success: "./bin/s3_deploy.sh"
cache:
  bundler: true
  npm: true
  pip: true
  yarn: true
notifications:
  slack:
    on_pull_requests: false
    secure: ZRC3DvCAynz+Zp5sLYdaozBPRCCO08i8gaQKzEjBwllJSO+5lRfLzjPYlyMJYtmTLq+ILM0CRhoGfCE3o7F/bdtJiEhNxWTsO17JqSlnvttCee0P7zeNIOJUP7mVFjX52yH3yPrCA8WTz97ocdtb9yue4P4bRs4umeEuRFzW0kM=
