npmPublishAccess: public

packageExtensions:
  # This dependency requires the node `util` module. It is not polyfilled by modern webpack.
  # Without PnP the below modification isn't needed because aws-sdk package has a dependency on `util`,
  # so it would be in node_modules and webpack would just use it there.
  # With yarn PnP webpack won't settle for using a dependency from another package.
  # This issue could have been solved by modifying the webpack configuration to provide the util package
  # to the whole codebase, but limiting it to just this package seemed like a better approach.
  "@nedb/binary-search-tree@*":
    dependencies:
      util: "*"

  # this package is used by the CFM and doesn't list react as a peer so we have to add this
  # configuration so Yarn PnP allows it to load React
  "create-react-class@*":
    peerDependencies:
      "react": "*"

  # this package is used by the CFM and doesn't list react as a peer so we have to add this
  # configuration so Yarn PnP allows it to load React
  "react-dom-factories@*":
    peerDependencies:
      "react": "*"

  "@testing-library/jest-dom@*":
    dependencies:
      "@types/aria-query": "*"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
