packageExtensions:
  # This dependency requires the node `util` module. It is not polyfilled by modern webpack.
  # Without PnP the below modification isn't needed because aws-sdk package has a dependency on `util`,
  # so it would be in node_modules and webpack would just use it there.
  # With yarn PnP webpack won't settle for using a dependency from another package.
  # This issue could have been solved by modifying the webpack configuration to provide the util package
  # to the whole codebase, but limiting it to just this package seemed like a better approach.
  "@nedb/binary-search-tree@*":
    dependencies:
      util: "*"

  # eslint-plugin-import dynamically loads resolver plugins using eslint-module-utils, this approach
  # of dynamically loading plugins doesn't work well with PnP.
  # See some discussion about it here:
  # https://github.com/import-js/eslint-plugin-import/pull/2283
  # https://github.com/import-js/eslint-plugin-import/issues/1434
  # https://github.com/yarnpkg/berry/pull/3836
  #
  # The dependencies of eslint-module-utils should be automatically updated by yarn because it is listed
  # here:
  # https://github.com/yarnpkg/berry/blob/6b00c65e4afbfa966a6dc4f8b7c564fcd141709e/packages/yarnpkg-extensions/sources/index.ts#L746
  # However, that is not working.
  # TODO: it might work to migrate to eslint-plugin-import-x which is a fork of eslint-plugin-import and
  # sounds like it will fix the need for this.
  "eslint-module-utils@*":
    dependencies:
      "eslint-import-resolver-typescript": "*"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
