#!/bin/bash
#
# Installs a CODAP embeddable Zip in the release directory.
#
# Expects one argument, the CODAP instance packaged as a zip file, and having
# its top level directory named according to its build name.
# The target directory is the release directory for the codap web site.
#
# The script expects to be run with root privileges.
#
# The script changes ownership of files so the directory will be accessible
# to apache.
#
PROGNAME=`basename $0`

RELEASE_DIR=/var/www/html/releases
TMP_DIR=/tmp/${PROGNAME}.$$
CONFIG_FILE=/var/www/config/releases/codap-config.js

ZIP_FILE=$1

function usage() {
    echo usage: ${PROGNAME} codap-zip 1>&2
    exit 1
}

function error_exit() {
    echo "error: $1" 1>&2
    echo exiting... 1>&2
    exit 2
}

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   error_exit "This script must be run as root"
fi

if [ ! -f "$ZIP_FILE" ] ; then
  usage
fi

# Get build name from directory name
BUILD_NAME=`basename $ZIP_FILE .zip`

echo BUILD_NAME=$BUILD_NAME

# copy zip
cp -i $ZIP_FILE ${RELEASE_DIR}/zips/${BUILD_NAME}.zip
chgrp www-data ${RELEASE_DIR}/zips/${BUILD_NAME}.zip

# make a 'staging' link
rm -f ${RELEASE_DIR}/zips/embeddedStaging.zip
ln -s ${RELEASE_DIR}/zips/${BUILD_NAME}.zip ${RELEASE_DIR}/zips/embeddedStaging.zip

