SC.stringsFor("el", {
    "DG.fileMenu.menuItem.newDocument": "Νέο",
    "DG.fileMenu.menuItem.openDocument": "Άνοιγμα",
    "DG.fileMenu.menuItem.closeDocument": "Κλείσιμο",
    "DG.fileMenu.menuItem.importFile": "Εισαγωγή",
    "DG.fileMenu.menuItem.revertTo": "Επαναφορά",
    "DG.fileMenu.menuItem.revertToOpened": "Κατάσταση πρόσφατα ανοιγμένου",
    "DG.fileMenu.menuItem.revertToShared": "Κοινόχρηστη προβολή",
    "DG.fileMenu.menuItem.saveDocument": "Αποθήκευση...",
    "DG.fileMenu.menuItem.copyDocument": "Δημιουργία αντιγράφου",
    "DG.fileMenu.menuItem.share": "Κοινή χρήση...",
    "DG.fileMenu.menuItem.shareGetLink": "λήψη συνδέσμου κοινόχρηστης προβολής",
    "DG.fileMenu.menuItem.shareUpdate": "Ενημέρωση κοινόχρηστης προβολής",
    "DG.fileMenu.menuItem.renameDocument": "Μετονομασία",
    "DG.main.userEntryView.title": "Τι θα θέλατε να κάνετε;",
    "DG.main.userEntryView.openDocument": "Άνοιγμα Εγγράφου ή Περιήγηση σε Παραδείγματα;",
    "DG.main.userEntryView.newDocument": "Δημιουργία Νέου Εγγράφου",
    "DG.mainPage.mainPane.undoButton.title": "Αναίρεση",
    "DG.mainPage.mainPane.undoButton.toolTip": "Αναίρεση τελευταίας κίνησης",
    "DG.mainPage.mainPane.redoButton.title": "Επανάληψη",
    "DG.mainPage.mainPane.redoButton.toolTip": "Επανάληψη της τελευταίας αναίρεσης",
    "DG.mainPage.mainPane.versionString": "Έκδοση %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Δυστυχώς το CODAP δεν υποστηρίζεται από τον φυλλομετρητή σας. Το CODAP υποστηρίζεται από τους Firefox 46+, Chrome 50+, Windows Edge 14+ και Safari 10+. Το CODAP δεν υποστηρίζεται, προς το παρόν, σε άλλους φυλλομετρητές.",
    "DG.mainPage.titleBar.saved": "Το Έγγραφο Αποθηκεύτηκε!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Έκδοση %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Έκδοση %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Καθαρισμός δεδομένων...",
    "DG.AppController.resetData.toolTip": "Διαγραφή ολων των δεδομένων από αυτό το έγγραφο",
    "DG.AppController.resetData.warnMessage": "Θέλετε πράγματι να διαγράψετε όλα τα δεδομένα σε αυτό το έγγραφο;",
    "DG.AppController.resetData.warnDescription": "Η επιλογή αυτή δεν αναιρείται.",
    "DG.AppController.resetData.okButtonTitle": "Ναί, να διαγραφούν τα δεδομένα",
    "DG.AppController.resetData.cancelButtonTitle": "Όχι, να διατηρηθούν τα δεδομένα",
    "DG.AppController.closeDocument.warnMessage": "Κλείσιμο αυτού του εγγράφου χωρίς αποθήκευση;",
    "DG.AppController.closeDocument.warnDescription": "Η επιλογή αυτή δεν αναιρείται.",
    "DG.AppController.closeDocument.okButtonTitle": "Κλείσιμο",
    "DG.AppController.closeDocument.cancelButtonTitle": "Ακύρωση",
    "DG.AppController.beforeUnload.confirmationMessage": "Το έγγραφο περιέχει μη αποθηκευμένες αλλαγές",
    "DG.AppController.optionMenuItems.reportProblem": "Αποστολή Ανατροφοδότησης...",
    "DG.AppController.optionMenuItems.viewWebPage": "Προβολή Ιστοσελίδας...",
    "DG.AppController.optionMenuItems.configureGuide": "Προσαρμογή Οδηγού...",
    "DG.AppController.optionMenuItems.about": "Σχετικά με το CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "Τι νέο υπάρχει;",
    "DG.AppController.optionMenuItems.help": "Βοήθεια...",
    "DG.AppController.optionMenuItems.toWebSite": "Ιστοχώρος του CODAP",
    "DG.AppController.exportDocument.prompt": "Όνομα Αρχείου:",
    "DG.AppController.exportCaseData.prompt": "Εξαγωγή των δεδομένων από:",
    "DG.AppController.exportDocument.exportTitle": "Εξαγωγή",
    "DG.AppController.exportDocument.exportTooltip": "Εξαγωγή δεδομένων σε αρχείο",
    "DG.AppController.exportDocument.cancelTitle": "Ακύρωση",
    "DG.AppController.exportDocument.cancelTooltip": "Ακύρωση εξαγωγής",
    "DG.AppController.feedbackDialog.dialogTitle": "Αποστολή Ανατροφοδότησης",
    "DG.AppController.feedbackDialog.subHeaderText": "Η ανατροφοδότησή σας, είναι πολύ σημαντική για μας!",
    "DG.AppController.feedbackDialog.messageText": "Παρακαλούμε βοηθήστε μας να συνεχίσουμε τη βελτίωση του προϊόντος μας. Ερωτήσεις, σφάλματα και αιτήματα για τα χαρακτηριστικά του, είναι όλα καλοδεχούμενα. Σας ευχαριστούμε!",
    "DG.AppController.feedbackDialog.subjectHint": "Σχετικά με τι είναι η ανατροφοδότησή σας;",
    "DG.AppController.feedbackDialog.feedbackHint": "Λεπτομέρειες",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Υποβολή",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Ακύρωση",
    "DG.AppController.showWebSiteTitle": "Σχετικά με το CODAP",
    "DG.AppController.showHelpTitle": "Βοήθεια για το CODAP",
    "DG.AppController.showAboutTitle": "Σχετικά με το CODAP",
    "DG.AppController.showReleaseNotesTitle": "Σημειώσεις για την έκδοση του CODAP",
    "DG.AppController.dropFile.error": "Σφάλμα: %@1",
    "DG.AppController.dropFile.unknownFileType": "Δεν μπορείτε να εισάγετε το είδος του αρχείου που σύρατε",
    "DG.AppController.validateDocument.missingRequiredProperty": "Δε βρέθηκε η απαιτούμενη ιδιότητα: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Μη αναμενόμενη ιδιότητα υψηλού επιπέδου: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Απροσδιόριστη ταυτότητα: %@1",
    "DG.AppController.validateDocument.parseError": "Συντακτικό σφάλμα στο έγγραφο: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Μη έγκυρο Έγγραφο JSON: %@1",
    "DG.AppController.openDocument.error.general": "Το έγγραφο δεν είναι δυνατό να ανοιχθεί",
    "DG.AppController.openDocument.error.invalid_format": "Το CODAP δεν μπορεί να διαβάσει τέτοιου τύπου έγγραφα",
    "DG.AppController.createDataSet.initialAttribute": "AttributeName",
    "DG.AppController.createDataSet.name": "Νέο Σετ Δεδομένων",
    "DG.AppController.createDataSet.collectionName": "Περιπτώσεις",
    "DG.AppController.caseTableMenu.newDataSet": "-- νέο --",
    "DG.SingleTextDialog.okButton.title": "ΟΚ",
    "DG.SingleTextDialog.cancelButton.title": "Άκυρο",
    "DG.SingleTextDialog.cancelButton.toolTip": "Απομακρύνετε το διάλογο, χωρίς να κάνετε αλλαγές",
    "DG.DocumentController.calculatorTitle": "Αριθμομηχανή",
    "DG.DocumentController.caseTableTitle": "Πίνακας Περίπτωσης",
    "DG.DocumentController.graphTitle": "Γράφημα",
    "DG.DocumentController.sliderTitle": "Ρυθμιστής",
    "DG.DocumentController.textTitle": "Κείμενο",
    "DG.DocumentController.mapTitle": "Χάρτης",
    "DG.DocumentController.enterURLPrompt": "Εισάγετε το URL μιας ιστοσελίδας για προβολή",
    "DG.DocumentController.enterViewWebPageOKTip": "Προβάλει την ιστοσελίδα που αντιστοιχεί στο URL",
    "DG.Document.defaultDocumentName": "Ανώνυμο Έγγραφο",
    "DG.Document.documentName.toolTip": "Πατήστε για να επεξεργαστείτε το όνομα του εγγράφου",
    "DG.SliderView.thumbView.toolTip": "Σύρετε για να αλλάξετε την τιμή του ρυθμιστή",
    "DG.SliderView.startButton.toolTip": "Έναρξη/Παύση κινούμενων εικόνων",
    "DG.ToolButtonData.tableButton.title": "Πίνακες",
    "DG.ToolButtonData.tableButton.toolTip": "Ανοίξτε ένα πίνακα περίπτωσης για κάθε σετ δεδομένων (ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Γράφημα",
    "DG.ToolButtonData.graphButton.toolTip": "Δημιουργήστε λενα γράφημα (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Ρυθμιστής",
    "DG.ToolButtonData.sliderButton.toolTip": "Δημιουργήστε ένα ρυθμιστή (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "Υπολογίστε",
    "DG.ToolButtonData.calcButton.toolTip": "Ανοίξτε/κλείστε την αριθμομηχανή",
    "DG.ToolButtonData.textButton.title": "Κείμενο",
    "DG.ToolButtonData.textButton.toolTip": "Δημιουργήστε ένα αντικείμενο κειμένου (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "Χάρτης",
    "DG.ToolButtonData.mapButton.toolTip": "Δημιουργήστε ένα χάρτη",
    "DG.ToolButtonData.optionMenu.title": "Επιλογές",
    "DG.ToolButtonData.optionMenu.toolTip": "Προβολή ενός ιστοτόπου, οδηγός ρυθμίσεων...",
    "DG.ToolButtonData.tileListMenu.title": "Ψηφίδες",
    "DG.ToolButtonData.tileListMenu.toolTip": "Προβολή της λίστας των ψηφίδων στο έγγραφο",
    "DG.ToolButtonData.guideMenu.title": "Οδηγός",
    "DG.ToolButtonData.guideMenu.toolTip": "Προβολή του οδηγού για αυτή τη δραστηριότητα και πλοήγηση σε αυτή",
    "DG.ToolButtonData.guideMenu.showGuide": "Προβολή Οδηγού",
    "DG.ToolButtonData.help.title": "Βοήθεια",
    "DG.ToolButtonData.help.toolTip": "Βοήθεια για το CODAP, μάθετε για το project CODAP",
    "DG.Slider.multiples": "Περιορισμός σε Πολλαπλάσια του:",
    "DG.Slider.maxPerSecond": "Μέγιστος αριθμός Κινούμενων Εικόνων/δευτ.:",
    "DG.Slider.direction": "Κατεύθυνση Κινούμενων Εικόνων:",
    "DG.Slider.backAndForth": "Πίσω Μπρος",
    "DG.Slider.lowToHigh": "Από Χαμηλά σε Ψηλά",
    "DG.Slider.highToLow": "Από Ψηλά σε Χαμηλά",
    "DG.Slider.mode": "Επανάληψη κίνησης:",
    "DG.Slider.nonStop": "Συνεχώς",
    "DG.Slider.onceOnly": "Μια Φορά",
    "DG.Undo.exceptionOccurred": "Παρουσιάστκε σφάλμα κατά την αναίρεση.",
    "DG.Redo.exceptionOccurred": "Παρουσιάστηκε σφάλμα κατά την επανάληψη.",
    "DG.Undo.componentMove": "Αναίρεση μετακίνησης του στοιχείου",
    "DG.Redo.componentMove": "Επανάληψη μετακίνησης του στοιχείου",
    "DG.Undo.componentResize": "Αναίρεση αλλαγής μεγέθους του στοιχείου",
    "DG.Redo.componentResize": "Επανάληψη αλλαγής μεγέθους του στοιχείου",
    "DG.Undo.axisDilate": "Αναίρεση αλλαγής κλίμακας του άξονα",
    "DG.Redo.axisDilate": "Επανάληψη αλλαγής κλίμακας του άξονα",
    "DG.Undo.axisRescaleFromData": "Αναίρεση αλλαγής κλίμακας του άξονα",
    "DG.Redo.axisRescaleFromData": "Επανάληψη αλλαγής κλίμακας του άξονα",
    "DG.Undo.axisDrag": "Αναίρεση μετατόπισης του άξονα",
    "DG.Redo.axisDrag": "Επανάληψη μετατόπισης του άξονα",
    "DG.Undo.axisAttributeChange": "Αναίρεση αλλαγής της ιδιότητας του άξονα",
    "DG.Redo.axisAttributeChange": "Επανάληψη αλλαγής της ιδιότητας του άξονα",
    "DG.Undo.axisAttributeAdded": "Αναίρεση προσθήκης ιδιότητας στον άξονα",
    "DG.Redo.axisAttributeAdded": "Επανάληψη προσθήκης ιδιότητας στον άξονα",
    "DG.Undo.toggleComponent.add.calcView": "Αναίρεση προβολής της αριθμομηχανής",
    "DG.Redo.toggleComponent.add.calcView": "Επανάληψη προβολής της αριθμομηχανής",
    "DG.Undo.toggleComponent.delete.calcView": "Αναίρεση απόκρυψης της αριθμομηχανής",
    "DG.Redo.toggleComponent.delete.calcView": "Επανάληψη απόκρυψης της αριθμομηχανής",
    "DG.Undo.caseTable.open": "Αναίρεση προβολής των πινάκων περίπτωσης",
    "DG.Redo.caseTable.open": "Επανάληψη προβολής των πινάκων περίπτωσης",
    "DG.Undo.caseTable.editAttribute": "Αναίρεση επεξεργασίας της ιδιότητας των πινάκων περίπτωσης",
    "DG.Redo.caseTable.editAttribute": "Επανάληψη επεξεργασίας της ιδιότητας των πινάκων περίπτωσης",
    "DG.Undo.caseTable.createAttribute": "Αναίρεση δημιουργίας της ιδιότητας των πινάκων περίπτωσης",
    "DG.Redo.caseTable.createAttribute": "Επανάληψη δημιουργίας της ιδιότητας των πινάκων περίπτωσης",
    "DG.Undo.caseTable.editAttributeFormula": "Αναίρεση επεξεργασίας του τύπου της ιδιότητας των πινάκων περίπτωσης",
    "DG.Redo.caseTable.editAttributeFormula": "Επανάληψη επεξεργασίας του τύπου της ιδιότητας των πινάκων περίπτωσης",
    "DG.Undo.caseTable.editCellValue": "Αναίρεση επεξεργασίας της τιμής του κελιού των πινάκων περίπτωσης",
    "DG.Redo.caseTable.editCellValue": "Επανάληψη επεξεργασίας της τιμής του κελιού των πινάκων περίπτωσης",
    "DG.Undo.caseTable.sortCases": "Αναίρεση ταξινόμησης περιπτώσεων",
    "DG.Redo.caseTable.sortCases": "Επανάληψη ταξινόμησης περιπτώσεων",
    "DG.Undo.caseTable.deleteAttribute": "Αναίρεση διαγραφής της ιδιότητας του πίνακα περιπτωσης",
    "DG.Redo.caseTable.deleteAttribute": "Επανάληψη διαγραφής της ιδιότητας του πίνακα περιπτωσης",
    "DG.Undo.caseTable.createCollection": "Αναίρεση δημιουργίας νέας συλλογής",
    "DG.Redo.caseTable.createCollection": "Επανάληψη δημιουργίας νέας συλλογής",
    "DG.Undo.caseTable.collectionNameChange": "Αναίρεση μετονομασίας συλλογής",
    "DG.Redo.caseTable.collectionNameChange": "Επανάληψη μετονομασίας συλλογής",
    "DG.Undo.caseTable.createNewCase": "Αναίρεση δημιουργίας νέας περίπτωσης",
    "DG.Redo.caseTable.createNewCase": "Επανάληψη δημιουργίας νέας περίπτωσης",
    "DG.Undo.caseTable.insertCases": "Αναίρεση εισαγωγής περιπτώσεων",
    "DG.Redo.caseTable.insertCases": "Επανάληψη εισαγωγής περιπτώσεων",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Αναίρεση επιλογής ανάπτυξη/σύμπτυξη όλων",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Επανάληψη επιλογής ανάπτυξη/σύμπτυξη όλων",
    "DG.Undo.caseTable.expandCollapseOneCase": "Αναίρεση ανάπτυξης ή σύμπτυξης μιας ομάδας",
    "DG.Redo.caseTable.expandCollapseOneCase": "Επανάληψη ανάπτυξης ή σύμπτυξης μιας ομάδας",
    "DG.Undo.caseTable.resizeColumns": "Αναίρεση αυτόματης προσαρμογής μεγέθους των στηλών",
    "DG.Redo.caseTable.resizeColumns": "Επανάληψη αυτόματης προσαρμογής μεγέθους των στηλών",
    "DG.Undo.document.share": "Αναίρεση κοινοποίησης του εγγράφου",
    "DG.Redo.document.share": "Επανάληψη κοινοποίησης του εγγράφου",
    "DG.Undo.document.unshare": "Αναίρεση διακοπής κοινοποίησης του εγγράφου",
    "DG.Redo.document.unshare": "Επανάληψη διακοπής κοινοποίησης του εγγράφου",
    "DG.Undo.game.add": "Αναίρεση προσθήκης παιχνιδιού στο έγγραφο",
    "DG.Redo.game.add": "Επανάληψη προσθήκης παιχνιδιού στο έγγραφο",
    "DG.Undo.graph.showCount": "Αναίρεση προβολής μετρητή",
    "DG.Redo.graph.showCount": "Επανάληψη προβολής μετρητή",
    "DG.Undo.graph.hideCount": "Αναίρεση απόκρυψης μετρητή",
    "DG.Redo.graph.hideCount": "Επανάληψη απόκρυψης μετρητή",
    "DG.Undo.graph.showPercent": "Αναίρεση προβολής ποσοστού",
    "DG.Redo.graph.showPercent": "Επανάληψη προβολής ποσοστού",
    "DG.Undo.graph.hidePercent": "Αναίρεση απόκρυψης ποσοστού",
    "DG.Redo.graph.hidePercent": "Επανάληψη απόκρυψης ποσοστού",
    "DG.Undo.graph.showMovableLine": "Αναίρεση προβολής κινούμενης γραμμής",
    "DG.Redo.graph.showMovableLine": "Επανάληψη προβολής κινούμενης γραμμής",
    "DG.Undo.graph.hideMovableLine": "Αναίρεση απόκρυψης κινούμενης γραμμής",
    "DG.Redo.graph.hideMovableLine": "Επανάληψη απόκρυψης κινούμενης γραμμής",
    "DG.Undo.graph.lockIntercept": "Αναίρεση κλειδώματος διακοπής γραμμής",
    "DG.Redo.graph.lockIntercept": "Επανάληψη κλειδώματος διακοπής γραμμής",
    "DG.Undo.graph.unlockIntercept": "Αναίρεση ξεκλειδώματος διακοπής γραμμής",
    "DG.Redo.graph.unlockIntercept": "Επανάληψη ξεκλειδώματος διακοπής γραμμής",
    "DG.Undo.graph.showPlotFunction": "Αναίρεση προβολής σχεδιασμένης συνάρτησης",
    "DG.Redo.graph.showPlotFunction": "Επανάληψη προβολής σχεδιασμένης συνάρτησης",
    "DG.Undo.graph.hidePlotFunction": "Αναίρεση απόκρυψης σχεδιασμένης συνάρτησης",
    "DG.Redo.graph.hidePlotFunction": "Επανάληψη απόκρυψης σχεδιασμένης συνάρτησης",
    "DG.Undo.graph.changePlotFunction": "Αναίρεση αλλαγής σχεδιασμένης συνάρτησης",
    "DG.Redo.graph.changePlotFunction": "Επανάληψη αλλαγής σχεδιασμένης συνάρτησης",
    "DG.Undo.graph.showPlotValue": "Αναίρεση προβολής σχεδιασμένης τιμής",
    "DG.Redo.graph.showPlotValue": "Επανάληψη προβολής σχεδιασμένης τιμής",
    "DG.Undo.graph.hidePlotValue": "Αναίρεση απόκρυψης σχεδιασμένης τιμής",
    "DG.Redo.graph.hidePlotValue": "Επανάληψη απόκρυψης σχεδιασμένης τιμής",
    "DG.Undo.graph.changePlotValue": "Αναίρεση αλλαγής σχεδιασμένης τιμής",
    "DG.Redo.graph.changePlotValue": "Επανάληψη αλλαγής σχεδιασμένης τιμής",
    "DG.Undo.graph.showConnectingLine": "Αναίρεση προβολής συνδετικής γραμμής",
    "DG.Redo.graph.showConnectingLine": "Επανάληψη προβολής συνδετικής γραμμής",
    "DG.Undo.graph.hideConnectingLine": "Αναίρεση απόκρυψης συνδετικής γραμμής",
    "DG.Redo.graph.hideConnectingLine": "Επανάληψη απόκρυψης συνδετικής γραμμής",
    "DG.Undo.graph.showLSRL": "Αναίρεση προβολής γραμμής ελαχίστων τετραγώνων",
    "DG.Redo.graph.showLSRL": "Επανάληψη προβολής γραμμής ελαχίστων τετραγώνων",
    "DG.Undo.graph.hideLSRL": "Αναίρεση απόκρυψης γραμμής ελαχίστων τετραγώνων",
    "DG.Redo.graph.hideLSRL": "Επανάληψη απόκρυψης γραμμής ελαχίστων τετραγώνων",
    "DG.Undo.graph.showSquares": "Αναίρεση προβολής τετραγώνων",
    "DG.Redo.graph.showSquares": "Επανάληψη προβολής τετραγώνων",
    "DG.Undo.graph.hideSquares": "Αναίρεση απόκρυψης τετραγώνων",
    "DG.Redo.graph.hideSquares": "Επανάληψη απόκρυψης τετραγώνων",
    "DG.Undo.graph.showPlottedMean": "Αναίρεση προβολής μέσου όρου",
    "DG.Redo.graph.showPlottedMean": "Επανάληψη προβολής μέσου όρου",
    "DG.Undo.graph.hidePlottedMean": "Αναίρεση απόκρυψης μέσου όρου",
    "DG.Redo.graph.hidePlottedMean": "Επανάληψη απόκρυψης μέσου όρου",
    "DG.Undo.graph.showPlottedMedian": "Αναίρεση προβολής διαμέσου",
    "DG.Redo.graph.showPlottedMedian": "Επανάληψη προβολής διαμέσου",
    "DG.Undo.graph.hidePlottedMedian": "Αναίρεση απόκρυψη διαμέσου",
    "DG.Redo.graph.hidePlottedMedian": "Επανάληψη απόκρυψης διαμέσου",
    "DG.Undo.graph.showPlottedStDev": "Αναίρεση προβολής τυπικής απόκλισης",
    "DG.Redo.graph.showPlottedStDev": "Επανάληψη προβολής τυπικής απόκλισης",
    "DG.Undo.graph.hidePlottedStDev": "Αναίρεση απόκρυψης τυπικής απόκλισης",
    "DG.Redo.graph.hidePlottedStDev": "Επανάληψη απόκρυψης τυπικής απόκλισης",
    "DG.Undo.graph.showPlottedIQR": "Αναίρεση προβολής ενδοτεταρτημοριακού εύρους",
    "DG.Redo.graph.hidePlottedIQR": "Επανάληψη προβολής ενδοτεταρτημοριακού εύρους",
    "DG.Undo.graph.hidePlottedIQR": "Αναίρεση απόκρυψης ενδοτεταρτημοριακού εύρους ",
    "DG.Redo.graph.showPlottedIQR": "Επανάληψη απόκρυψης ενδοτεταρτημοριακού εύρους ",
    "DG.Undo.graph.addMovableValue": "Αναίρεση προσθήκης κινητής τιμής",
    "DG.Redo.graph.addMovableValue": "Επανάληψη προσθήκης κινητής τιμής",
    "DG.Undo.graph.removeMovableValue": "Αναίρεση αφαίρεσης κινητής τιμής",
    "DG.Redo.graph.removeMovableValue": "Επανάληψη αφαίρεσης κινητής τιμής",
    "DG.Undo.graph.moveMovableValue": "Αναίρεση μετακίνησης κινητής τιμής",
    "DG.Redo.graph.moveMovableValue": "Επανάληψη μετακίνησης κινητής τιμής",
    "DG.Undo.graph.changePointColor": "Αναίρεση αλλαγής χρώματος δεδομένων",
    "DG.Redo.graph.changePointColor": "Επανάληψη αλλαγής χρώματος δεδομένων",
    "DG.Undo.graph.changeStrokeColor": "Αναίρεση αλλαγής χρώματος περιγράμματος",
    "DG.Redo.graph.changeStrokeColor": "Επανάληψη αλλαγής χρώματος περιγράμματος",
    "DG.Undo.graph.changePointSize": "Αναίρεση αλλαγής μεγέθους σημείου",
    "DG.Redo.graph.changePointSize": "Επαναληψη αλλαγής μεγέθους σημείου",
    "DG.Undo.graph.changeAttributeColor": "Αναίρεση αλλαγής χρώματος χαρακτηριστικού",
    "DG.Redo.graph.changeAttributeColor": "Επανάληψη αλλαγής χρώματος χαρακτηριστικού",
    "DG.Undo.graph.changeBackgroundColor": "Αναίρεση αλλαγής χρώματος υποβάθρου γραφήματος",
    "DG.Redo.graph.changeBackgroundColor": "Επανάληψη αλλαγής χρώματος υποβάθρου γραφήματος",
    "DG.Undo.graph.toggleTransparent": "Αναίρεση μεταβολής διαφάνειας σχεδίου",
    "DG.Redo.graph.toggleTransparent": "Επανάληψη μεταβολής διαφάνειας σχεδίου",
    "DG.Undo.guide.show": "Αναίρεση προβολής του οδηγού",
    "DG.Redo.guide.show": "Επανάληψη προβολής του οδηγού",
    "DG.Undo.guide.navigate": "Αναίρεση προβολής σελίδας του οδηγού",
    "DG.Redo.guide.navigate": "Επανάληψη προβολής σελίδας του οδηγού",
    "DG.Undo.hideSelectedCases": "Αναίρεση απόκρυψης επιλεγμένων περιπτώσεων",
    "DG.Redo.hideSelectedCases": "Επανάληψη απόκρυψης επιλεγμένων περιπτώσεων",
    "DG.Undo.hideUnselectedCases": "Αναίρεση απόκρυψης μη επιλεγμένων περιπτώσεων",
    "DG.Redo.hideUnselectedCases": "Επανάληψη απόκρυψης μη επιλεγμένων περιπτώσεων",
    "DG.Undo.enableNumberToggle": "Αναίρεση Προβολής Ρυθμιστών Γονικής Ορατότητας",
    "DG.Redo.enableNumberToggle": "Επανάληψη Προβολής Ρυθμιστών Γονικής Ορατότητας",
    "DG.Undo.disableNumberToggle": "Αναίρεση Απόκρυψης Ρυθμιστών Γονικής Ορατότητας",
    "DG.Redo.disableNumberToggle": "Επανάληψη Απόκρυψης Ρυθμιστών Γονικής Ορατότητας",
    "DG.Undo.interactiveUndoableAction": "Αναίρεση μιας κίνησης στο διαδραστικό",
    "DG.Redo.interactiveUndoableAction": "Επανάληψη μιας κίνησης στο διαδραστικό",
    "DG.Undo.showAllCases": "Αναίρεση προβολης όλων των περιπτώσεων",
    "DG.Redo.showAllCases": "Επανάληψη προβολης όλων των περιπτώσεων",
    "DG.Undo.map.create": "Αναίρεση προσθήκης χάρτη",
    "DG.Redo.map.create": "Επανάληψη προσθήκης χάρτη",
    "DG.Undo.map.fitBounds": "Αναίρεση αλλαγής μεγέθους χάρτη",
    "DG.Redo.map.fitBounds": "Επανάληψη αλλαγής μεγέθους χάρτη",
    "DG.Undo.map.pan": "Αναίρεση μετακίνησης χάρτη",
    "DG.Redo.map.pan": "Επανάληψη μετακίνησης χάρτη",
    "DG.Undo.map.zoom": "Αναίρεση μεγέθυνσης χάρτη",
    "DG.Redo.map.zoom": "Επανάληψη μεγέθυνσης χάρτη",
    "DG.Undo.map.showGrid": "Αναίρεση προβολής πλέγματος χάρτη",
    "DG.Redo.map.showGrid": "Επανάληψη προβολής πλέγματος χάρτη",
    "DG.Undo.map.hideGrid": "Αναίρεση απόκρυψης πλέγματος χάρτη",
    "DG.Redo.map.hideGrid": "Επανάληψη απόκρυψης πλέγματος χάρτη",
    "DG.Undo.map.changeGridSize": "Αναίρεση αλλαγής μεγέθους πλέγματος χάρτη",
    "DG.Redo.map.changeGridSize": "Επανάληψη αλλαγής μεγέθους πλέγματος χάρτη",
    "DG.Undo.map.showPoints": "Αναίρεση προβολής σημείων στο χάρτη",
    "DG.Redo.map.showPoints": "Επανάληψη προβολής σημείων στο χάρτη",
    "DG.Undo.map.hidePoints": "Αναίρεση απόκρυψης σημείων στο χάρτη",
    "DG.Redo.map.hidePoints": "Επανάληψη απόκρυψης σημείων στο χάρτη",
    "DG.Undo.map.showLines": "Αναίρεση προβολής γραμμών στο χάρτη",
    "DG.Redo.map.showLines": "Επανάληψη προβολής γραμμών στο χάρτη",
    "DG.Undo.map.hideLines": "Αναίρεση απόκρυψης γραμμών στο χάρτη",
    "DG.Redo.map.hideLines": "Επανάληψη απόκρυψης γραμμών στο χάρτη",
    "DG.Undo.map.changeBaseMap": "Αναίρεση αλλαγής υποβάθρου χάρτη",
    "DG.Redo.map.changeBaseMap": "Επανάληψη αλλαγής υποβάθρου χάρτη",
    "DG.Undo.textComponent.create": "Αναίρεση προσθήκης κειμένου",
    "DG.Redo.textComponent.create": "Επανάληψη προσθήκης κειμένου",
    "DG.Undo.textComponent.edit": "Αναίρεση επεξεργασίας κειμένου",
    "DG.Redo.textComponent.edit": "Επανάληψη επεξεργασίας κειμένου",
    "DG.Undo.sliderComponent.create": "Αναίρεση προσθήκης ρυθμιστή",
    "DG.Redo.sliderComponent.create": "Επανάληψη προσθήκης ρυθμιστή",
    "DG.Undo.slider.change": "Αναίρεση αλλαγής τιμής ρυθμιστή",
    "DG.Redo.slider.change": "Επανάληψη αλλαγής τιμής ρυθμιστή",
    "DG.Undo.slider.changeMultiples": "Αναίρεση αλλαγής προεπιλεγμένων θέσεων του ρυθμιστή",
    "DG.Redo.slider.changeMultiples": "Επανάληψη αλλαγής προεπιλεγμένων θέσεων του ρυθμιστή",
    "DG.Undo.slider.changeSpeed": "Αναίρεση αλλαγής μέγιστου εικόνων/δευτ. του ρυθμιστή",
    "DG.Redo.slider.changeSpeed": "Επανάληψη αλλαγής μέγιστου εικόνων/δευτ. του ρυθμιστή",
    "DG.Undo.slider.changeDirection": "Αναίρεση αλλαγής κατεύθυνσης κινούμενων εικόνων του ρυθμιστή",
    "DG.Redo.slider.changeDirection": "Επανάληψη αλλαγής κατεύθυνσης κινούμενων εικόνων του ρυθμιστή",
    "DG.Undo.slider.changeRepetition": "Αναίρεση αλλαγής της επαναληψιμότητας κινούμενων εικόνων του ρυθμιστή",
    "DG.Redo.slider.changeRepetition": "Επανάληψη αλλαγής της επαναληψιμότητας κινούμενων εικόνων του ρυθμιστή",
    "DG.Undo.graphComponent.create": "Αναίρεση προσθήκης γραφήματος",
    "DG.Redo.graphComponent.create": "Επανάληψη προσθήκης γραφήματος",
    "DG.Undo.dataContext.create": "Αναίρεση δημιουργίας ενός συνόλου τιμών",
    "DG.Redo.dataContext.create": "Επανάληψη δημιουργίας ενός συνόλου τιμών",
    "DG.Undo.data.deleteCases": "Αναίρεση διαγραφής περιπτώσεων",
    "DG.Redo.data.deleteCases": "Επανάληψη διαγραφής περιπτώσεων",
    "DG.Undo.component.close": "Αναίρεση κλεισίματος στοιχείου",
    "DG.Redo.component.close": "Επανάληψη κλεισίματος στοιχείου",
    "DG.Undo.component.minimize": "Αναίρεση ελαχιστοποίησης στοιχείου",
    "DG.Redo.component.minimize": "Επανάληψη ελαχιστοποίησης στοιχείου",
    "DG.Undo.dataContext.moveAttribute": "Αναίρεση μετακίνησης χαρακτηριστικού πίνακα περίπτωσης",
    "DG.Redo.dataContext.moveAttribute": "Επανάληψη μετακίνησης χαρακτηριστικού πίνακα περίπτωσης",
    "DG.DataContext.singleCaseName": "περίπτωση",
    "DG.DataContext.pluralCaseName": "περιπτώσεις",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "μια συλλογή",
    "DG.DataContext.collapsedRowString": "%@1 of %@2",
    "DG.DataContext.noData": "Χωρίς Δεδομένα",
    "DG.DataContext.baseName": "Data_Set_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "Η εξίσωση για το χαρακτηριστικό \"%@\" δεν αλλάζει.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Δημιουργήστε ένα νέο χαρακτηριστικό για να μπορέσετε να ορίσετε μια εξίσωση.",
    "DG.Formula.FuncCategoryArithmetic": "Αριθμητικές Συναρτήσεις",
    "DG.Formula.FuncCategoryConversion": "Άλλες Συναρτήσεις",
    "DG.Formula.FuncCategoryDateTime": "Συναρτήσεις Ημερομηνίας/Ώρας",
    "DG.Formula.FuncCategoryLookup": "Συναρτήσεις Αναζήτησης",
    "DG.Formula.FuncCategoryOther": "Άλλες Συναρτήσεις",
    "DG.Formula.FuncCategoryRandom": "Άλλες Συναρτήσεις",
    "DG.Formula.FuncCategoryStatistical": "Στατιστικές Συναρτήσεις",
    "DG.Formula.FuncCategoryString": "Αλφαριθμητικές Συναρτήσεις",
    "DG.Formula.FuncCategoryTrigonometric": "Τριγωνομετρικές Συναρτήσεις",
    "DG.Formula.DateLongMonthJanuary": "Ιανουάριος",
    "DG.Formula.DateLongMonthFebruary": "Φεβρουάριος",
    "DG.Formula.DateLongMonthMarch": "Μάρτιος",
    "DG.Formula.DateLongMonthApril": "Απρίλιος",
    "DG.Formula.DateLongMonthMay": "Μάιος",
    "DG.Formula.DateLongMonthJune": "Ιούνιος",
    "DG.Formula.DateLongMonthJuly": "Ιούλιος",
    "DG.Formula.DateLongMonthAugust": "Αύγουστος",
    "DG.Formula.DateLongMonthSeptember": "Σεπτέμβριος",
    "DG.Formula.DateLongMonthOctober": "Οκτώβριος",
    "DG.Formula.DateLongMonthNovember": "Νοέμβριος",
    "DG.Formula.DateLongMonthDecember": "Δεκέμβριος",
    "DG.Formula.DateShortMonthJanuary": "Ιαν",
    "DG.Formula.DateShortMonthFebruary": "Φεβ",
    "DG.Formula.DateShortMonthMarch": "Μαρ",
    "DG.Formula.DateShortMonthApril": "Απρ",
    "DG.Formula.DateShortMonthMay": "Μάι",
    "DG.Formula.DateShortMonthJune": "Ιούν",
    "DG.Formula.DateShortMonthJuly": "Ιούλ",
    "DG.Formula.DateShortMonthAugust": "Αύγ",
    "DG.Formula.DateShortMonthSeptember": "Σεπ",
    "DG.Formula.DateShortMonthOctober": "Οκτ",
    "DG.Formula.DateShortMonthNovember": "Νοέ",
    "DG.Formula.DateShortMonthDecember": "Δεκ",
    "DG.Formula.DateLongDaySunday": "Κυριακή",
    "DG.Formula.DateLongDayMonday": "Δευτέρα",
    "DG.Formula.DateLongDayTuesday": "Τρίτη",
    "DG.Formula.DateLongDayWednesday": "Τετάρτη",
    "DG.Formula.DateLongDayThursday": "Πέμπτη",
    "DG.Formula.DateLongDayFriday": "Παρασκευή",
    "DG.Formula.DateLongDaySaturday": "Σάββατο",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Συντακτικό λάθος: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Ημιτελής έκφραση",
    "DG.Formula.SyntaxErrorInvalidOperator": "Μη έγκυρος τελεστής '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "Μη έγκυρος(οι) τύπος(οι) για '%@'",
    "DG.Formula.TypeError.description": "Μη έγκυρος(οι) τύπος(οι) για '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "το '%@' δεν αναγνωρίζεται",
    "DG.Formula.VarReferenceError.description": "Η μεταβλητή '%@' δεν αναγνωρίζεται",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "Μη έγκυρη αναφορά σε θυγατρικό χαρακτηριστικό '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' είναι ένα θυγατρικό χαρακτηριστικό το οποίο μπορεί να αναφερθεί μόνο σε συσσωρευμένη συνάρτηση",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "το '%@()' δεν αναγνωρίζεται",
    "DG.Formula.FuncReferenceError.description": "η συνάρτηση '%@()' δεν αναγνωρίζεται ",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "το '%@()' αναμένει 1 όρισμα",
    "DG.Formula.FuncArgsErrorSingle.description": "η συνάρτηση '%@()' αναμένει 1 όρισμα",
    "DG.Formula.FuncArgsErrorPlural.message": "το '%@()' αναμένει %@ ορίσματα",
    "DG.Formula.FuncArgsErrorPlural.description": "Η συνάρτηση '%@()' αναμένει %@ ορίσματα",
    "DG.Formula.FuncArgsErrorRange.message": "το '%@()' αναμένει %@-%@ ορίσματα",
    "DG.Formula.FuncArgsErrorRange.description": "Η συνάρτηση '%@()' αναμένει %@-%@ ορίσματα",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "αναμονή αιτήματος...",
    "DG.Formula.PendingRequest.description": "αναμονή αιτήματος...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "αποτυχία αιτήματος (%@)",
    "DG.Formula.FailedRequest.description": "αποτυχία αιτήματος (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "αναμονή για σύνορα...",
    "DG.Formula.PendingBoundaries.description": "αναμονή για σύνορα...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "αποτυχία συνόρων (%@)",
    "DG.Formula.FailedBoundaries.description": "boundaries failed (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': unrecognized data set",
    "DG.Formula.LookupDataSetError.description": "Data set '%@' is unrecognized",
    "DG.Formula.LookupAttrError.message": "'%@' not found in data set '%@'",
    "DG.Formula.LookupAttrError.description": "Attribute '%@' not found in data set '%@'",
    "DG.TableController.headerMenuItems.editAttribute": "Edit Attribute Properties...",
    "DG.TableController.headerMenuItems.editFormula": "Edit Formula...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Rerandomize",
    "DG.TableController.headerMenuItems.sortAscending": "Sort Ascending (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Sort Descending (9→0, Z→A)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Delete Attribute",
    "DG.TableController.newAttrDlg.defaultAttrName": "new_attr",
    "DG.TableController.newAttrDlg.attrNameHint": "Enter a name for the new attribute",
    "DG.TableController.newAttrDlg.formulaHint": "If desired, type a formula for computing values of this attribute",
    "DG.TableController.newAttrDlg.applyTooltip": "Define the new attribute using the name and (optional) formula",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Please enter a name for the new attribute",
    "DG.TableController.newAttrDialog.AttributesCategory": "Attributes",
    "DG.TableController.newAttrDialog.SpecialCategory": "Special",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Globals",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Constants",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Functions",
    "DG.TableController.renameAttributeInvalidMsg": "Attribute names may not be empty",
    "DG.TableController.renameAttributeInvalidDesc": "Please enter a valid attribute name",
    "DG.TableController.renameAttributeDuplicateMsg": "An attribute with that name already exists",
    "DG.TableController.renameAttributeDuplicateDesc": "Please enter a unique attribute name",
    "DG.TableController.deleteAttribute.confirmMessage": "Delete the attribute '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "This action cannot be undone.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Delete Attribute",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Cancel",
    "DG.TableController.deleteDataSet.confirmMessage": "Delete and destroy this data set: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "This action cannot be undone.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Delete Data Set",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Cancel",
    "DG.TableController.attrEditor.precisionHint": "Number of digits after decimal point",
    "DG.TableController.attrEditor.unitHint": "Unit of measure, if applicable",
    "DG.TableController.attrEditor.descriptionHint": "Describe the attribute",
    "DG.TableController.setScoreDlg.applyTooltip": "Set the formula for the '%@' attribute",
    "DG.TableController.setScoreDlg.formulaHint": "Type a formula for computing values of this attribute",
    "DG.TableController.newAttributeTooltip": "Add a new attribute to this table",
    "DG.TableController.attributeEditor.title": "Attribute Properties",
    "DG.CaseTableDropTarget.dropMessage": "drop attribute to create new collection",
    "DG.CaseTable.defaultAttrName": "newAttr",
    "DG.CaseTable.indexColumnName": "index",
    "DG.CaseTable.indexColumnTooltip": "The row number (caseIndex) within the collection",
    "DG.CaseTable.indexMenu.insertCase": "Insert Case",
    "DG.CaseTable.indexMenu.insertCases": "Insert Cases...",
    "DG.CaseTable.indexMenu.deleteCase": "Delete Case",
    "DG.CaseTable.indexMenu.deleteCases": "Delete Cases",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "categorical",
    "DG.CaseTable.attribute.type.categorical": "categorical",
    "DG.CaseTable.attribute.type.numeric": "numeric",
    "DG.CaseTable.attribute.type.date": "date",
    "DG.CaseTable.attribute.type.qualitative": "qualitative",
    "DG.CaseTable.attribute.type.boundary": "boundary",
    "DG.CaseTable.attributeEditor.name": "name",
    "DG.CaseTable.attributeEditor.description": "description",
    "DG.CaseTable.attributeEditor.type": "type",
    "DG.CaseTable.attributeEditor.unit": "unit",
    "DG.CaseTable.attributeEditor.precision": "precision",
    "DG.CaseTable.attributeEditor.editable": "editable",
    "DG.CaseTable.insertCasesDialog.title": "Insert Cases",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# cases to insert:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "location:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "before",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "after",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Insert Cases",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Insert the specified number of cases",
    "DG.CaseTableController.allTables": "All tables",
    "DG.AttrFormView.attrNamePrompt": "Attribute Name:",
    "DG.AttrFormView.formulaPrompt": "Formula:",
    "DG.AttrFormView.operandMenuTitle": "--- Insert Value ---",
    "DG.AttrFormView.functionMenuTitle": "--- Insert Function ---",
    "DG.AttrFormView.applyBtnTitle": "Apply",
    "DG.AttrFormView.cancelBtnTitle": "Cancel",
    "DG.AttrFormView.cancelBtnTooltip": "Dismiss the dialog without making any changes",
    "DG.GuideConfigView.titlePrompt": "Guide Title",
    "DG.GuideConfigView.titleHint": "Activity Name",
    "DG.GuideConfigView.itemTitleHint": "Section Name",
    "DG.GuideConfigView.itemURLHint": "URL of section",
    "DG.GuideConfigView.okBtnTitle": "OK",
    "DG.GuideConfigView.okBtnToolTip": "Accept the Guide menu items",
    "DG.GuideConfigView.cancelBtnTitle": "Cancel",
    "DG.GuideConfigView.cancelBtnTooltip": "Dismiss the dialog without making any changes",
    "DG.GuideConfigView.httpWarning": "The URL must start with either http:// or https://",
    "DG.DataDisplayModel.rescaleToData": "Rescale to Data",
    "DG.DataDisplayModel.ShowConnectingLine": "Show Connecting Lines",
    "DG.DataDisplayModel.HideConnectingLine": "Hide Connecting Lines",
    "DG.AxisView.emptyGraphCue": "Click here, or drag an attribute here.",
    "DG.CellLinearAxisView.midPanelTooltip": "Drag to translate axis scale",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Drag to change axis lower bound",
    "DG.CellLinearAxisView.upperPanelTooltip": "Drag to change axis upper bound",
    "DG.PlotModel.mixup": "Mix Up the Plot",
    "DG.PlotModel.showCount": "Show Count",
    "DG.PlotModel.hideCount": "Hide Count",
    "DG.ScatterPlotModel.sumSquares": ",\nSum of squares = %@",
    "DG.ScatterPlotModel.rSquared": ",\nr^2 = %@",
    "DG.ScatterPlotModel.slopeIntercept": "%@ = %@ %@ %@ %@",
    "DG.ScatterPlotModel.infiniteSlope": "%@ = %@",
    "DG.ScatterPlotModel.slopeOnly": "slope = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "per year",
    "DG.ScatterPlotModel.daysLabel": "per day",
    "DG.ScatterPlotModel.hoursLabel": "per hour",
    "DG.ScatterPlotModel.minutesLabel": "per minute",
    "DG.ScatterPlotModel.secondsLabel": "per seconds",
    "DG.LegendView.attributeTooltip": "Click to change legend attribute",
    "DG.NumberToggleView.showAll": "Show All –",
    "DG.NumberToggleView.hideAll": "Hide All –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Last",
    "DG.NumberToggleView.showAllTooltip": "Click to show all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.hideAllTooltip": "Click to hide all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.enableLastModeTooltip": "Click to show last parent case only",
    "DG.NumberToggleView.disableLastModeTooltip": "Click to exit last parent case mode",
    "DG.NumberToggleView.indexTooltip": "Click to toggle visibility",
    "DG.PlottedAverageAdornment.meanValueTitle": "mean=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "median=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SD, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "lower=%@\nQ1=%@\nmedian=%@\nQ3=%@\nupper=%@\nIQR=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Legend: %@",
    "DG.DataDisplayMenu.remove": "Remove Attribute",
    "DG.DataDisplayMenu.removeAttribute_x": "Remove X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Remove Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Remove Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Remove Legend: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Treat as Categorical",
    "DG.DataDisplayMenu.treatAsNumeric": "Treat as Numeric",
    "DG.DataDisplayMenu.hide": "Hide and Show",
    "DG.DataDisplayMenu.hideSelectedPlural": "Hide Selected Cases",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Hide Unselected Cases",
    "DG.DataDisplayMenu.hideSelectedSing": "Hide Selected Case",
    "DG.DataDisplayMenu.hideUnselectedSing": "Hide Unselected Case",
    "DG.DataDisplayMenu.enableNumberToggle": "Show Parent Visibility Toggles",
    "DG.DataDisplayMenu.disableNumberToggle": "Hide Parent Visibility Toggles",
    "DG.DataDisplayMenu.showAll": "Show All Cases",
    "DG.DataDisplayMenu.snapshot": "Make Snapshot",
    "DG.GraphView.replaceAttribute": "Replace %@ with %@",
    "DG.GraphView.addAttribute": "Add attribute %@",
    "DG.GraphView.addToEmptyPlace": "Create axis with %@",
    "DG.GraphView.addToEmptyX": "Create x-axis with %@",
    "DG.GraphView.dropInPlot": "Color points by values of %@",
    "DG.GraphView.zoomTip": "Double-click to zoom in.\nShift-double-click to zoom out",
    "DG.GraphView.rescale": "Rescale to data",
    "DG.AxisView.labelTooltip": "—Click to change %@ axis attribute",
    "DG.AxisView.vertical": "vertical",
    "DG.AxisView.horizontal": "horizontal",
    "DG.DataTip.connectingLine": "%@: %@\nwith %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formula",
    "DG.PlottedValue.namePrompt": "Plotted Value",
    "DG.PlottedValue.formulaPrompt": "value =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Plotted Function",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Type an expression e.g. x*x/30 - 50",
    "DG.MapView.showGrid": "Show Grid",
    "DG.MapView.hideGrid": "Hide Grid",
    "DG.MapView.showPoints": "Show Points",
    "DG.MapView.hidePoints": "Hide Points",
    "DG.MapView.marqueeHint": "Marquee tool—drag select points in map",
    "DG.MapView.gridControlHint": "Change size of grid rectangles",
    "DG.Inspector.values": "Measure",
    "DG.Inspector.styles": "Format",
    "DG.Inspector.pointSize": "Point size:",
    "DG.Inspector.transparency": "Transparency:",
    "DG.Inspector.color": "Color:",
    "DG.Inspector.legendColor": "Legend color:",
    "DG.Inspector.backgroundColor": "Background\ncolor:",
    "DG.Inspector.stroke": "Stroke:",
    "DG.Inspector.rescale.toolTip": "Rescale display to show all the data",
    "DG.Inspector.mixUp.toolTip": "Mixup all the points",
    "DG.Inspector.hideShow.toolTip": "Show all cases or hide selected/unselected cases",
    "DG.Inspector.delete.toolTip": "Delete selected or unselected cases",
    "DG.Inspector.sliderValues.toolTip": "Set slider animation direction, speed, …",
    "DG.Inspector.webViewEditURL.toolTip": "Edit the URL of the displayed web page",
    "DG.Inspector.selection.selectAll": "Select All Cases",
    "DG.Inspector.selection.deleteSelectedCases": "Delete Selected Cases",
    "DG.Inspector.selection.deleteUnselectedCases": "Delete Unselected Cases",
    "DG.Inspector.deleteAll": "Delete All Cases",
    "DG.Inspector.deleteDataSet": "Delete and Destroy Data Set",
    "DG.Inspector.displayValues.toolTip": "Change what is shown along with the points",
    "DG.Inspector.displayStyles.toolTip": "Change the appearance of the display",
    "DG.Inspector.makeImage.toolTip": "Save the image as a PNG file",
    "DG.Inspector.displayShow": "Show …",
    "DG.Inspector.colorPicker.more": "more",
    "DG.Inspector.colorPicker.less": "less",
    "DG.Inspector.graphTransparency": "Transparent",
    "DG.Inspector.graphCount": "Count",
    "DG.Inspector.graphPercent": "Percent",
    "DG.Inspector.graphRow": "Row",
    "DG.Inspector.graphColumn": "Column",
    "DG.Inspector.graphCell": "Cell",
    "DG.Inspector.graphConnectingLine": "Connecting Lines",
    "DG.Inspector.graphMovableLine": "Movable Line",
    "DG.Inspector.graphInterceptLocked": "Intercept Locked",
    "DG.Inspector.graphPlottedFunction": "Plotted Function",
    "DG.Inspector.graphSquares": "Squares of Residuals",
    "DG.Inspector.graphLSRL": "Least Squares Line",
    "DG.Inspector.graphMovableValue": "Movable Value",
    "DG.Inspector.graphAdd": "Add",
    "DG.Inspector.graphRemove": "Remove",
    "DG.Inspector.graphPlottedMean": "Mean",
    "DG.Inspector.graphPlottedMedian": "Median",
    "DG.Inspector.graphPlottedStDev": "Standard Deviation",
    "DG.Inspector.graphPlottedIQR": "Interquartile Range",
    "DG.Inspector.graphPlottedBoxPlot": "Box Plot",
    "DG.Inspector.graphPlottedValue": "Plotted Value",
    "DG.Inspector.attributes.toolTip": "Make new attributes. Export case data.",
    "DG.Inspector.resize.toolTip": "Resize all columns to fit data",
    "DG.Inspector.newAttribute": "New Attribute in %@...",
    "DG.Inspector.randomizeAllAttributes": "Rerandomize All",
    "DG.Inspector.exportCaseData": "Export Case Data...",
    "DG.Inspector.mapGrid": "Grid",
    "DG.Inspector.mapPoints": "Points",
    "DG.Inspector.mapLines": "Connecting Lines",
    "DG.GameController.continuityError": "Sorry, after columns in the case table have been reordered, new data cannot be accepted.",
    "DG.GameView.loading": "Loading",
    "DG.GameView.loadError": "If you can see this text, loading the above URL may have failed. You can check the link in another browser tab or report the error to http://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "Are you sure?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Yes, close it",
    "DG.Component.closeComponent.cancelButtonTitle": "Cancel",
    "DG.GameController.confirmCloseDescription": "If you close this, you may not be able to add more data.",
    "DG.WebView.defaultTitle": "Web Page",
    "DG.mainPage.exceptionMessage": "An error has occurred that may affect how this program behaves. You may wish to reload this page after you save your work. (Error: %@)",
    "DG.fileMenu.provider.examples.displayName": "Example Documents",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Open a plugin component",
    "DG.Undo.graph.showMovablePoint": "Undo showing movable point",
    "DG.Redo.graph.showMovablePoint": "Redo showing movable point",
    "DG.Undo.graph.hideMovablePoint": "Undo hiding movable point",
    "DG.Redo.graph.hideMovablePoint": "Redo hiding movable point",
    "DG.Undo.graph.moveMovablePoint": "Undo moving movable point",
    "DG.Redo.graph.moveMovablePoint": "Redo moving movable point",
    "DG.DataDisplayMenu.copyAsImage": "Open in Draw Tool",
    "DG.DataDisplayMenu.exportImage": "Export Image...",
    "DG.DataDisplayMenu.imageOfTitle": "Image of %@",
    "DG.Inspector.graphMovablePoint": "Movable Point",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Open case table for this data set",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Create a new data set",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Delete and destroy this data set",
    "DG.Undo.graph.showAsBarChart": "Undo fusing dots into bars",
    "DG.Redo.graph.showAsBarChart": "Redo fusing dots into bars",
    "DG.Undo.graph.showAsDotChart": "Undo dispersing bars into dots",
    "DG.Redo.graph.showAsDotChart": "Redo dispersing bars into dots",
    "DG.CountAxisView.countLabel": "Count",
    "DG.CountAxisView.countLabelDescription": "Number of cases in the bar along this axis",
    "DG.CountAxisView.percentLabel": "Percent",
    "DG.CountAxisView.percentLabelDescription": "Percent of cases in the bar along this axis",
    "DG.BarChartModel.cellTipPlural": "%@ of %@ %@ (%@%) are %@",
    "DG.BarChartModel.cellTipSingular": "%@ of %@ %@ (%@%) is %@",
    "DG.Inspector.configuration": "Configuration",
    "DG.Inspector.displayConfiguration.toolTip": "Configure the display differently",
    "DG.Inspector.displayScale": "Scale …",
    "DG.Inspector.graphBarChart": "Fuse Dots into Bars",
    "DG.Locale.name.de": "German",
    "DG.Locale.name.en": "English",
    "DG.Locale.name.es": "Spanish",
    "DG.Locale.name.he": "Hebrew",
    "DG.Locale.name.tr": "Turkish",
    "DG.Locale.name.zh": "Chinese",
    "DG.Undo.graph.swapCategories": "Undo reordering categories",
    "DG.Redo.graph.swapCategories": "Redo reordering categories",
    "DG.TableController.collectionTitleText": "%@1 (%@2 cases)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 cases, %@3 set aside)",
    "DG.Inspector.setaside.setAsideSelectedCases": "Set Aside Selected Cases",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Set Aside Unselected Cases",
    "DG.Inspector.setaside.restoreSetAsideCases": "Restore %@ Set Aside Cases",
    "DG.DocumentController.caseCardTitle": "Case Card",
    "DG.DocumentController.toggleToCaseCard": "Switch to case card view of the data",
    "DG.DocumentController.toggleToCaseTable": "Switch to case table view of the data",
    "DG.CaseCard.indexString": "1 of %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ selected of %@ %@",
    "DG.CaseCard.summaryValues": "%@ values",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Select and show next case",
    "DG.CaseCard.navPrevCase": "Select and show previous case",
    "DG.CaseCard.navFirstCase": "Select and show first case",
    "DG.CaseCard.navLastCase": "Select and show last case",
    "DG.Undo.component.toggleTableToCard": "Undo changing case table to case card",
    "DG.Redo.component.toggleTableToCard": "Redo changing case table to case card",
    "DG.Undo.component.toggleCardToTable": "Undo changing case card to case table",
    "DG.Redo.component.toggleCardToTable": "Redo changing case card to case table",
    "DG.Undo.graph.addBackgroundImage": "Undo adding graph background image",
    "DG.Redo.graph.addBackgroundImage": "Redo adding graph background image",
    "DG.Undo.graph.removeBackgroundImage": "Undo removing graph background image",
    "DG.Redo.graph.removeBackgroundImage": "Redo removing graph background image",
    "DG.Undo.graph.lockBackgroundImage": "Undo locking background image to axes",
    "DG.Redo.graph.lockBackgroundImage": "Redo locking background image to axes",
    "DG.Undo.graph.unlockBackgroundImage": "Undo unlocking background image from axes",
    "DG.Redo.graph.unlockBackgroundImage": "Redo unlocking background image from axes",
    "DG.Undo.enableMeasuresForSelection": "Undo Show Measures For Selection",
    "DG.Redo.enableMeasuresForSelection": "Redo Show Measures For Selection",
    "DG.Undo.disableMeasuresForSelection": "Undo Hide Measures For Selection",
    "DG.Redo.disableMeasuresForSelection": "Redo Hide Measures For Selection",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Show Measures for Selection",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Hide Measures for Selection",
    "DG.DataDisplayMenu.addBackgroundImage": "Add Background Image",
    "DG.DataDisplayMenu.lockImageToAxes": "Lock Background Image to Axes",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Unlock Background Image from Axes",
    "DG.DataDisplayMenu.removeBackgroundImage": "Remove Background Image",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Delete Formula (Keeping Values)",
    "DG.TableController.headerMenuItems.recoverFormula": "Recover Deleted Formula",
    "DG.Inspector.displayLayers.toolTip": "Change the appearance of the map layers",
    "DG.Inspector.layers": "Layers",
    "DG.Undo.graph.repositionEquation": "Undo repositioning equation",
    "DG.Redo.graph.repositionEquation": "Redo repositioning equation",
    "DG.Locale.name.el": "Greek"
});
