SC.stringsFor("nb", {
    "DG.fileMenu.menuItem.newDocument": "Ny",
    "DG.fileMenu.menuItem.openDocument": "Åpne...",
    "DG.fileMenu.menuItem.closeDocument": "Lukk",
    "DG.fileMenu.menuItem.importFile": "Importér...",
    "DG.fileMenu.menuItem.revertTo": "Gjør om...",
    "DG.fileMenu.menuItem.revertToOpened": "Nylig åpnet tilstand",
    "DG.fileMenu.menuItem.revertToShared": "Delt visning",
    "DG.fileMenu.menuItem.saveDocument": "Lagre...",
    "DG.fileMenu.menuItem.copyDocument": "Lag en kopi",
    "DG.fileMenu.menuItem.share": "Del...",
    "DG.fileMenu.menuItem.shareGetLink": "Lenke til delt visning",
    "DG.fileMenu.menuItem.shareUpdate": "Oppdatér delt visning",
    "DG.fileMenu.menuItem.renameDocument": "Gi nytt navn",
    "DG.main.userEntryView.title": "Hva vil du gjøre?",
    "DG.main.userEntryView.openDocument": "Åpne dokument eller ",
    "DG.main.userEntryView.newDocument": "Opprett nytt dokument",
    "DG.mainPage.mainPane.undoButton.title": "Angre",
    "DG.mainPage.mainPane.undoButton.toolTip": "Angre siste handling",
    "DG.mainPage.mainPane.redoButton.title": "Gjør om",
    "DG.mainPage.mainPane.redoButton.toolTip": "Gjør om sist angrede handling",
    "DG.mainPage.mainPane.versionString": "Versjon %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Dessverre, CODAP støttes ikke av nettleseren din. CODAP støttes av følgende nettlesere: Firefox 46+, Chrome 50+, Windows Edge 14+, og Safari 10+.",
    "DG.mainPage.titleBar.saved": "Dokument lagret!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Versjon %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Versjon %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Slett data...",
    "DG.AppController.resetData.toolTip": "Slett alle data fra gjeldende dokument",
    "DG.AppController.resetData.warnMessage": "Vil du virkelig slette alle data fra gjeldende dokument?",
    "DG.AppController.resetData.warnDescription": "Denne handlingen kan ikke angres.",
    "DG.AppController.resetData.okButtonTitle": "Ja, slett data.",
    "DG.AppController.resetData.cancelButtonTitle": "Nei, behold data.",
    "DG.AppController.closeDocument.warnMessage": "Lukke gjeldende vindu uten å lagre?",
    "DG.AppController.closeDocument.warnDescription": "Denne handlingen kan ikke angres.",
    "DG.AppController.closeDocument.okButtonTitle": "Lukk",
    "DG.AppController.closeDocument.cancelButtonTitle": "Angre",
    "DG.AppController.beforeUnload.confirmationMessage": "Dokumentet inneholder endringer som ikke er lagret.",
    "DG.AppController.optionMenuItems.reportProblem": "Gi tilbakemelding...",
    "DG.AppController.optionMenuItems.viewWebPage": "Vis nettside...",
    "DG.AppController.optionMenuItems.configureGuide": "Lag bruksanvisning...",
    "DG.AppController.optionMenuItems.about": "Om CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "Hva er nytt?",
    "DG.AppController.optionMenuItems.help": "Hjelpside og videoer",
    "DG.AppController.optionMenuItems.toWebSite": "CODAP-prosjektet",
    "DG.AppController.exportDocument.prompt": "Filnavn:",
    "DG.AppController.exportCaseData.prompt": "Eksportér observasjoner, fra:",
    "DG.AppController.exportDocument.exportTitle": "Eksportér",
    "DG.AppController.exportDocument.exportTooltip": "Eksportér data til en fil",
    "DG.AppController.exportDocument.cancelTitle": "Avbryt",
    "DG.AppController.exportDocument.cancelTooltip": "Avbryt eksport",
    "DG.AppController.feedbackDialog.dialogTitle": "Gi tilbakemelding",
    "DG.AppController.feedbackDialog.subHeaderText": "Dine tilbakemeldinger er viktige for oss!",
    "DG.AppController.feedbackDialog.messageText": "Hjelp oss med å stadig forbedre produktet vårt. Spørsmål, feil og ønsker om funksjonalitet mottas gjerne. Takk skal du ha!",
    "DG.AppController.feedbackDialog.subjectHint": "Hva vil du gi tilbakemelding om",
    "DG.AppController.feedbackDialog.feedbackHint": "Detaljer",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Send inn",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Avbryt",
    "DG.AppController.showWebSiteTitle": "Om CODAP",
    "DG.AppController.showHelpTitle": "Hjelp til CODAP",
    "DG.AppController.showAboutTitle": "Om CODAP",
    "DG.AppController.showReleaseNotesTitle": "CODAP Utgivelsesdokumentasjon",
    "DG.AppController.dropFile.error": "Feil: %@1",
    "DG.AppController.dropFile.unknownFileType": "Du kan ikke importere den filtypen du slapp",
    "DG.AppController.validateDocument.missingRequiredProperty": "Nødvendig egenskap ikke funnet: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Uventet topp-nivå-egenskap: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Uløst id: %@1",
    "DG.AppController.validateDocument.parseError": "Noe er feil i dokumentet: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Ugyldig JSON-dokument: %@1",
    "DG.AppController.openDocument.error.general": "Klarte ikke å åpne dokumentet",
    "DG.AppController.openDocument.error.invalid_format": "CODAP kan ikke lese denne typen dokument",
    "DG.AppController.createDataSet.initialAttribute": "VariabelNavn",
    "DG.AppController.createDataSet.name": "Nytt datasett",
    "DG.AppController.createDataSet.collectionName": "Observasjoner",
    "DG.AppController.caseTableMenu.newDataSet": "-- ny --",
    "DG.SingleTextDialog.okButton.title": "OK",
    "DG.SingleTextDialog.cancelButton.title": "Avbrytt",
    "DG.SingleTextDialog.cancelButton.toolTip": "Avslutt uten å gjøre endringer",
    "DG.DocumentController.calculatorTitle": "Kalkulator",
    "DG.DocumentController.caseTableTitle": "Tabell med observasjoner",
    "DG.DocumentController.graphTitle": "Graf",
    "DG.DocumentController.sliderTitle": "Glidebryter",
    "DG.DocumentController.textTitle": "Tekst",
    "DG.DocumentController.mapTitle": "Kart",
    "DG.DocumentController.enterURLPrompt": "Skriv inn URL til en nettside for å vise den",
    "DG.DocumentController.enterViewWebPageOKTip": "Viser nettside til angitt URL",
    "DG.Document.defaultDocumentName": "Dokument uten navn",
    "DG.Document.documentName.toolTip": "Klikk for å endre navnet på dokumentet",
    "DG.SliderView.thumbView.toolTip": "Dra for å endre verdien til glidebryteren",
    "DG.SliderView.startButton.toolTip": "Start/stopp animasjon",
    "DG.ToolButtonData.tableButton.title": "Tabeller",
    "DG.ToolButtonData.tableButton.toolTip": "Åpne tabell for hvert datasett (ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Graf",
    "DG.ToolButtonData.graphButton.toolTip": "Lag graf (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Glidebryter",
    "DG.ToolButtonData.sliderButton.toolTip": "Lag glidebryter (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "Kalk",
    "DG.ToolButtonData.calcButton.toolTip": "Åpne/lukke kalkulator (ctrl-alt-c)",
    "DG.ToolButtonData.textButton.title": "Tekst",
    "DG.ToolButtonData.textButton.toolTip": "Lag et tekst-objekt (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "Kart",
    "DG.ToolButtonData.mapButton.toolTip": "Lag kart",
    "DG.ToolButtonData.optionMenu.title": "Valg",
    "DG.ToolButtonData.optionMenu.toolTip": "Vis nettside, lag bruksanvisning...",
    "DG.ToolButtonData.tileListMenu.title": "Fliser",
    "DG.ToolButtonData.tileListMenu.toolTip": "Vis flisene i dokumentet",
    "DG.ToolButtonData.guideMenu.title": "Bruksanvisning",
    "DG.ToolButtonData.guideMenu.toolTip": "Vis bruksanvisning for denne aktiviteten og naviger i den",
    "DG.ToolButtonData.guideMenu.showGuide": "Vis bruksanvisning",
    "DG.ToolButtonData.help.title": "Hjelp",
    "DG.ToolButtonData.help.toolTip": "Hjelp til CODAP, lær om CODAP-prosjektet",
    "DG.Slider.multiples": "Begrens til faktorer av:",
    "DG.Slider.maxPerSecond": "Maksimalt antall animasjonsbilder/sek:",
    "DG.Slider.direction": "Animasjonsretning",
    "DG.Slider.backAndForth": "Fram og tilbake",
    "DG.Slider.lowToHigh": "Lav til høy",
    "DG.Slider.highToLow": "Høy til lav",
    "DG.Slider.mode": "Animasjon gjentas",
    "DG.Slider.nonStop": "Kontinuerlig",
    "DG.Slider.onceOnly": "Kun en gang",
    "DG.Undo.exceptionOccurred": "En feil oppstod ved omgjøring",
    "DG.Redo.exceptionOccurred": "En feil oppstod ved angring",
    "DG.Undo.componentMove": "Angre flytt element",
    "DG.Redo.componentMove": "Gjør om flytt element",
    "DG.Undo.componentResize": "Angre endre størrelse på element",
    "DG.Redo.componentResize": "Gjør om endre størrelse på element",
    "DG.Undo.axisDilate": "Angre endre skala på akse",
    "DG.Redo.axisDilate": "Gjør om endre skala på akse",
    "DG.Undo.axisRescaleFromData": "Angre endre skala på akse",
    "DG.Redo.axisRescaleFromData": "Gjør om endre skala på akse",
    "DG.Undo.axisDrag": "Angre dra aksen",
    "DG.Redo.axisDrag": "Gjør om dra aksen",
    "DG.Undo.axisAttributeChange": "Angre endre variabel på aksen",
    "DG.Redo.axisAttributeChange": "Gjør om endre variabel på aksen",
    "DG.Undo.axisAttributeAdded": "Angre legg til variabel på aksen",
    "DG.Redo.axisAttributeAdded": "Gjør om legg til variabel på aksen",
    "DG.Undo.toggleComponent.add.calcView": "Angre vis kalkulator",
    "DG.Redo.toggleComponent.add.calcView": "Gjør om vis kalkulator",
    "DG.Undo.toggleComponent.delete.calcView": "Angre skjul kalkulator",
    "DG.Redo.toggleComponent.delete.calcView": "Gjør om skjul kalkulator",
    "DG.Undo.caseTable.open": "Angre vis tabeller",
    "DG.Redo.caseTable.open": "Gjør om vis tabeller",
    "DG.Undo.caseTable.editAttribute": "Angre rediger variabel",
    "DG.Redo.caseTable.editAttribute": "Gjør om rediger variabel",
    "DG.Undo.caseTable.createAttribute": "Angre opprett variabel",
    "DG.Redo.caseTable.createAttribute": "Gjør om opprett variabel",
    "DG.Undo.caseTable.editAttributeFormula": "Angre rediger formel for variabel",
    "DG.Redo.caseTable.editAttributeFormula": "Gjør om rediger formel for variabel",
    "DG.Undo.caseTable.editCellValue": "Angre rediger celleverdi",
    "DG.Redo.caseTable.editCellValue": "Gjør om rediger celleverdi",
    "DG.Undo.caseTable.sortCases": "Angre sortér observasjoner",
    "DG.Redo.caseTable.sortCases": "Gjør om sortér observasjoner",
    "DG.Undo.caseTable.deleteAttribute": "Angre slette variabel",
    "DG.Redo.caseTable.deleteAttribute": "Gjør om slette variabel",
    "DG.Undo.caseTable.createCollection": "Angre opprett ny samling",
    "DG.Redo.caseTable.createCollection": "Gjør om opprett ny samling",
    "DG.Undo.caseTable.collectionNameChange": "Angre gi samling nytt navn",
    "DG.Redo.caseTable.collectionNameChange": "Gjør om gi samling nytt navn",
    "DG.Undo.caseTable.createNewCase": "Angre opprett ny observasjon",
    "DG.Redo.caseTable.createNewCase": "Gjør om opprett ny observasjon",
    "DG.Undo.caseTable.insertCases": "Angre sett inn observasjoner",
    "DG.Redo.caseTable.insertCases": "Gjør om sett inn observasjoner",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Angre bytt mellom utvid/minimér alle",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Gjør om bytt mellom utvid/minimér alle",
    "DG.Undo.caseTable.expandCollapseOneCase": "Angre utvid eller minimér en gruppe",
    "DG.Redo.caseTable.expandCollapseOneCase": "Gjør om utvid eller minimér en gruppe",
    "DG.Undo.caseTable.resizeColumns": "Angre auto-justér alle kolonner",
    "DG.Redo.caseTable.resizeColumns": "Gjør om auto-justér alle kolonner",
    "DG.Undo.document.share": "Angre deling av dokumentet",
    "DG.Redo.document.share": "Gjør om deling av dokumentet",
    "DG.Undo.document.unshare": "Angre opphev deling av dokumentet",
    "DG.Redo.document.unshare": "Gjør om opphev deling av dokumentet",
    "DG.Undo.game.add": "Angre legg til spill i dokumentet",
    "DG.Redo.game.add": "Gjør om legg til spill i dokumentet",
    "DG.Undo.graph.showCount": "Angre vis telling",
    "DG.Redo.graph.showCount": "Gjør om vis telling",
    "DG.Undo.graph.hideCount": "Angre skjul telling",
    "DG.Redo.graph.hideCount": "Gjør om skjul telling",
    "DG.Undo.graph.showPercent": "Angre vis prosent",
    "DG.Redo.graph.showPercent": "Gjør om vis prosent",
    "DG.Undo.graph.hidePercent": "Angre skjul prosent",
    "DG.Redo.graph.hidePercent": "Gjør om skjul prosent",
    "DG.Undo.graph.showMovableLine": "Angre vis flyttbar linje",
    "DG.Redo.graph.showMovableLine": "Gjør om vis flyttbar linje",
    "DG.Undo.graph.hideMovableLine": "Angre skjul flyttbar linje",
    "DG.Redo.graph.hideMovableLine": "Gjør om skjul flyttbar linje",
    "DG.Undo.graph.lockIntercept": "Angre lås skjæringspunkt",
    "DG.Redo.graph.lockIntercept": "Gjør om lås skjæringspunkt",
    "DG.Undo.graph.unlockIntercept": "Angre frigjør skjæringspunkt",
    "DG.Redo.graph.unlockIntercept": "Gjør om frigjør skjæringspunkt",
    "DG.Undo.graph.showPlotFunction": "Angre vis plottet funksjon",
    "DG.Redo.graph.showPlotFunction": "Gjør om plottet funksjon",
    "DG.Undo.graph.hidePlotFunction": "Angre skjul plottet funksjon",
    "DG.Redo.graph.hidePlotFunction": "Gjør om skjul plottet funksjon",
    "DG.Undo.graph.changePlotFunction": "Angre endre plottet funksjon",
    "DG.Redo.graph.changePlotFunction": "Gjør om plottet funksjon",
    "DG.Undo.graph.showPlotValue": "Angre vise plottet verdi",
    "DG.Redo.graph.showPlotValue": "Gjør om vise plottet verdi",
    "DG.Undo.graph.hidePlotValue": "Angre skjul plottet verdi",
    "DG.Redo.graph.hidePlotValue": "Gjør om skjul plottet verdi",
    "DG.Undo.graph.changePlotValue": "Angre endre plottet verdi",
    "DG.Redo.graph.changePlotValue": "Gjør om endre plottet verdi",
    "DG.Undo.graph.showConnectingLine": "Angre vis forbindelseslinje",
    "DG.Redo.graph.showConnectingLine": "Gjør om vis forbindelseslinje",
    "DG.Undo.graph.hideConnectingLine": "Angre skjul forbindelseslinje",
    "DG.Redo.graph.hideConnectingLine": "Gjør om skjul forbindelseslinje",
    "DG.Undo.graph.showLSRL": "Angre vis minste kvadraters-linje",
    "DG.Redo.graph.showLSRL": "Gjør om vis minste kvadraters-linje",
    "DG.Undo.graph.hideLSRL": "Angre skjul minste kvadraters-linje",
    "DG.Redo.graph.hideLSRL": "Gjør om skjul minste kvadraters-linje",
    "DG.Undo.graph.showSquares": "Angre vis kvadrater",
    "DG.Redo.graph.showSquares": "Gjør om vis kvadrater",
    "DG.Undo.graph.hideSquares": "Angre skjul kvadrater",
    "DG.Redo.graph.hideSquares": "Gjør om skjul kvadrater",
    "DG.Undo.graph.showPlottedMean": "Angre vis gjennomsnitt",
    "DG.Redo.graph.showPlottedMean": "Gjør om vis gjennomsnitt",
    "DG.Undo.graph.hidePlottedMean": "Angre skjul gjennomsnitt",
    "DG.Redo.graph.hidePlottedMean": "Gjør om skjul gjennomsnitt",
    "DG.Undo.graph.showPlottedMedian": "Angre vis median",
    "DG.Redo.graph.showPlottedMedian": "Gjør om vis median",
    "DG.Undo.graph.hidePlottedMedian": "Angre skjul median",
    "DG.Redo.graph.hidePlottedMedian": "Angre skjul median",
    "DG.Undo.graph.showPlottedStDev": "Angre vis standardavvik",
    "DG.Redo.graph.showPlottedStDev": "Gjør om vis standardavvik",
    "DG.Undo.graph.hidePlottedStDev": "Angre skjul standardavvik",
    "DG.Redo.graph.hidePlottedStDev": "Gjør om skjul standardavvik",
    "DG.Undo.graph.showPlottedIQR": "Angre vis variasjon i kvartilbredde",
    "DG.Redo.graph.hidePlottedIQR": "Gjør om skjul variasjon i kvartilbredde\n",
    "DG.Undo.graph.hidePlottedIQR": "Angre skjul variasjon i kvartilbredde",
    "DG.Redo.graph.showPlottedIQR": "Gjør om vis variasjon i kvartilbredde",
    "DG.Undo.graph.addMovableValue": "Angre legg til flyttbar verdi",
    "DG.Redo.graph.addMovableValue": "Gjør om legg til flyttbar verdi",
    "DG.Undo.graph.removeMovableValue": "Angre fjern flyttbar verdi",
    "DG.Redo.graph.removeMovableValue": "Gjør om fjern flyttbar verdi",
    "DG.Undo.graph.moveMovableValue": "Angre flytt flyttbar verdi",
    "DG.Redo.graph.moveMovableValue": "Gjør om flytt flyttbar verdi",
    "DG.Undo.graph.changePointColor": "Angre endre farge på data",
    "DG.Redo.graph.changePointColor": "Gjør om endre farge på data",
    "DG.Undo.graph.changeStrokeColor": "Angre endre linjefarge",
    "DG.Redo.graph.changeStrokeColor": "Gjør om endre linjefarge",
    "DG.Undo.graph.changePointSize": "Angre endre punktstørrelse",
    "DG.Redo.graph.changePointSize": "Gjør om endre punktstørrelse",
    "DG.Undo.graph.changeAttributeColor": "Angre endre farge til variabel",
    "DG.Redo.graph.changeAttributeColor": "Gjør om endre farge til variabel",
    "DG.Undo.graph.changeBackgroundColor": "Angre bytt bakgrunnsfagre på graf",
    "DG.Redo.graph.changeBackgroundColor": "Gjør om bytt bakgrunnsfarge på graf",
    "DG.Undo.graph.toggleTransparent": "Angre veksle gjennomsiktighet plot",
    "DG.Redo.graph.toggleTransparent": "Gjør om veksle gjennomsiktighet plot",
    "DG.Undo.guide.show": "Angre vis bruksanvisning",
    "DG.Redo.guide.show": "Gjør om vis bruksanvisning",
    "DG.Undo.guide.navigate": "Angre endre bruksanvisning",
    "DG.Redo.guide.navigate": "Gjør om endre bruksanvisning",
    "DG.Undo.hideSelectedCases": "Angre skjul valgte observasjoner",
    "DG.Redo.hideSelectedCases": "Gjør om skjul valgte observasjoner",
    "DG.Undo.hideUnselectedCases": "Angre skjul observasjoner som ikke er valgt",
    "DG.Redo.hideUnselectedCases": "Gjør om skjul observasjoner som ikke er valgt",
    "DG.Undo.enableNumberToggle": "Angre vis veksel for beslektede data",
    "DG.Redo.enableNumberToggle": "Gjenta vis veksel for beslektede data",
    "DG.Undo.disableNumberToggle": "Angre skjul av/på-bryter for beslektede data",
    "DG.Redo.disableNumberToggle": "Gjenta skjul av/på-bryter for beslektede data",
    "DG.Undo.interactiveUndoableAction": "Angre en handling i interaktiviteten",
    "DG.Redo.interactiveUndoableAction": "Gjenta en handling i interaktiviteten",
    "DG.Undo.showAllCases": "Angre vis alle observasjoner",
    "DG.Redo.showAllCases": "Gjør om vis alle observasjoner",
    "DG.Undo.map.create": "Angre legg til kart",
    "DG.Redo.map.create": "Gjør om legg til kart",
    "DG.Undo.map.fitBounds": "Angre endre størrelse på kart",
    "DG.Redo.map.fitBounds": "Gjør om endre størrelse på kart",
    "DG.Undo.map.pan": "Angre vis hele kartet",
    "DG.Redo.map.pan": "Gjør om vis hele kartet",
    "DG.Undo.map.zoom": "Angre zoom kart",
    "DG.Redo.map.zoom": "Gjør om zoom kart",
    "DG.Undo.map.showGrid": "Angre vis rutenett på kart",
    "DG.Redo.map.showGrid": "Gjør om vis rutenett på kart",
    "DG.Undo.map.hideGrid": "Angre skjul rutenett på kart",
    "DG.Redo.map.hideGrid": "Gjør om skjul rutenett på kart",
    "DG.Undo.map.changeGridSize": "Angre endre størrelse på rutenett på kart",
    "DG.Redo.map.changeGridSize": "Gjør om ",
    "DG.Undo.map.showPoints": "Angre vis punkter på kart",
    "DG.Redo.map.showPoints": "Gjør om vis punkter på kart",
    "DG.Undo.map.hidePoints": "Angre skjul punkter på kart",
    "DG.Redo.map.hidePoints": "Gjør om skjul punkter på kart",
    "DG.Undo.map.showLines": "Angre vis linjer på kart",
    "DG.Redo.map.showLines": "Gjør om vis linjer på kart",
    "DG.Undo.map.hideLines": "Angre skjul linjer på kart",
    "DG.Redo.map.hideLines": "Gjør om skjul linjer på kart",
    "DG.Undo.map.changeBaseMap": "Angre endre kartbakgrunn",
    "DG.Redo.map.changeBaseMap": "Gjør om endre kartbakgrunn",
    "DG.Undo.textComponent.create": "Angre legg til tekstobjekt",
    "DG.Redo.textComponent.create": "Gjør om legg til tekstobjekt",
    "DG.Undo.textComponent.edit": "Angre rediger tekst",
    "DG.Redo.textComponent.edit": "Gjør om rediger tekst",
    "DG.Undo.sliderComponent.create": "Angre legg til glidebryter",
    "DG.Redo.sliderComponent.create": "Gjør om legg til glidebryter",
    "DG.Undo.slider.change": "Angre endring av  verdi på glidebryter",
    "DG.Redo.slider.change": "Gjør om endring av verdi på glidebryter",
    "DG.Undo.slider.changeMultiples": "Angre endring av begrensning på glidebryter",
    "DG.Redo.slider.changeMultiples": "Gjør om endring glidebryter begrensning",
    "DG.Undo.slider.changeSpeed": "Angre endring maks. bilder/sek på glidebryter",
    "DG.Redo.slider.changeSpeed": "Gjør om endring maks. bilder/sek på glidebryter",
    "DG.Undo.slider.changeDirection": "Angre endring glidebryter animasjonsendring",
    "DG.Redo.slider.changeDirection": "Gjør om endring glidebryter animasjonsendring",
    "DG.Undo.slider.changeRepetition": "Angre endring glidebryter gjentakelse",
    "DG.Redo.slider.changeRepetition": "Gjør om endring glidebryter gjentakelse",
    "DG.Undo.graphComponent.create": "Angre legg til en graf",
    "DG.Redo.graphComponent.create": "Gjør om legg til en graf",
    "DG.Undo.dataContext.create": "Angre oppretting av datasett",
    "DG.Redo.dataContext.create": "Gjør om oppretting av datasett",
    "DG.Undo.data.deleteCases": "Angre slett observasjoner",
    "DG.Redo.data.deleteCases": "Gjør om slette observasjoner",
    "DG.Undo.component.close": "Angre lukk ramme",
    "DG.Redo.component.close": "Gjør om lukk ramme",
    "DG.Undo.component.minimize": "Angre minimér ramme",
    "DG.Redo.component.minimize": "Gjør om minimér ramme",
    "DG.Undo.dataContext.moveAttribute": "Angre flytt kolonne",
    "DG.Redo.dataContext.moveAttribute": "Gjør om flytt kolonne",
    "DG.DataContext.singleCaseName": "observasjon",
    "DG.DataContext.pluralCaseName": "observasjoner",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "et utvalg",
    "DG.DataContext.collapsedRowString": "%@1 av %@2",
    "DG.DataContext.noData": "Ingen data",
    "DG.DataContext.baseName": "Data_sett_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "Formelen til variabel \"%@\" kan ikke endres.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Opprett ny variabel for å kunne definere formel",
    "DG.Formula.FuncCategoryArithmetic": "Aritmetiske funksjoner",
    "DG.Formula.FuncCategoryConversion": "Andre funksjoner",
    "DG.Formula.FuncCategoryDateTime": "Dato/tid-funksjoner",
    "DG.Formula.FuncCategoryLookup": "Slå-opp-funksjoner",
    "DG.Formula.FuncCategoryOther": "Andre funksjoner",
    "DG.Formula.FuncCategoryRandom": "Andre funksjoner",
    "DG.Formula.FuncCategoryStatistical": "Statistiske funksjoner",
    "DG.Formula.FuncCategoryString": "Strengfunksjon",
    "DG.Formula.FuncCategoryTrigonometric": "Trigonometriske funksjoner",
    "DG.Formula.DateLongMonthJanuary": "januar",
    "DG.Formula.DateLongMonthFebruary": "februar",
    "DG.Formula.DateLongMonthMarch": "mars",
    "DG.Formula.DateLongMonthApril": "april",
    "DG.Formula.DateLongMonthMay": "mai",
    "DG.Formula.DateLongMonthJune": "juni",
    "DG.Formula.DateLongMonthJuly": "july",
    "DG.Formula.DateLongMonthAugust": "august",
    "DG.Formula.DateLongMonthSeptember": "september",
    "DG.Formula.DateLongMonthOctober": "oktober",
    "DG.Formula.DateLongMonthNovember": "november",
    "DG.Formula.DateLongMonthDecember": "desember",
    "DG.Formula.DateShortMonthJanuary": "jan",
    "DG.Formula.DateShortMonthFebruary": "feb",
    "DG.Formula.DateShortMonthMarch": "mar",
    "DG.Formula.DateShortMonthApril": "apr",
    "DG.Formula.DateShortMonthMay": "mai",
    "DG.Formula.DateShortMonthJune": "jun",
    "DG.Formula.DateShortMonthJuly": "jul",
    "DG.Formula.DateShortMonthAugust": "aug",
    "DG.Formula.DateShortMonthSeptember": "sep",
    "DG.Formula.DateShortMonthOctober": "okt",
    "DG.Formula.DateShortMonthNovember": "nov",
    "DG.Formula.DateShortMonthDecember": "des",
    "DG.Formula.DateLongDaySunday": "søn",
    "DG.Formula.DateLongDayMonday": "man",
    "DG.Formula.DateLongDayTuesday": "tir",
    "DG.Formula.DateLongDayWednesday": "ons",
    "DG.Formula.DateLongDayThursday": "tor",
    "DG.Formula.DateLongDayFriday": "fre",
    "DG.Formula.DateLongDaySaturday": "lør",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec) \\d{1,2}( |,) *\\d{4}|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Syntaksfeil: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Ufullstendig uttrykk",
    "DG.Formula.SyntaxErrorInvalidOperator": "ugyldig tegn '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "ugyldige type(r) for '%@'",
    "DG.Formula.TypeError.description": "ugyldige type(r) for '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": " '%@' er ikke gjenkjent",
    "DG.Formula.VarReferenceError.description": "variablen '%@' er ikke gjenkjent",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "ugyldig referanse til underliggende egenskap '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' er en underliggende egenskap som kun kan refereres til i en sammenslåingsfunksjon",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' er ukjent",
    "DG.Formula.FuncReferenceError.description": "funksjonen '%@()' er ukjent",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' forventer 1 argument",
    "DG.Formula.FuncArgsErrorSingle.description": "Funksjonen '%@()'  forventer 1 argument\n",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' forventer %@ argumenter\n",
    "DG.Formula.FuncArgsErrorPlural.description": "Funksjonen '%@()' forventer %@ argumenter\n",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' forventer %@-%@ argumenter\n",
    "DG.Formula.FuncArgsErrorRange.description": "Funksjonen '%@()' forventer %@-%@ innhold/argumenter",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "forspørsel venter...",
    "DG.Formula.PendingRequest.description": "forspørsel venter...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "forespørsel feilet (%@)\n",
    "DG.Formula.FailedRequest.description": "forspørsel feilet (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "grenser venter...",
    "DG.Formula.PendingBoundaries.description": "grenser venter...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "grenser feilet (%@)",
    "DG.Formula.FailedBoundaries.description": "grenser feilet (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': Ikke gjenkjent datasett",
    "DG.Formula.LookupDataSetError.description": "Datasettet '%@' ble ikke gjenkjent",
    "DG.Formula.LookupAttrError.message": "'%@' ikke funnet i datasett '%@'",
    "DG.Formula.LookupAttrError.description": "Variabel '%@' ikke funnet i datasett '%@'",
    "DG.TableController.headerMenuItems.editAttribute": "Rediger egenskaper til variabel...",
    "DG.TableController.headerMenuItems.editFormula": "Rediger formel",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Gjør tilfeldig på nytt",
    "DG.TableController.headerMenuItems.sortAscending": "Sortér stigende (A→Å, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Sortér synkende (Å→A, 9→0)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Slett variabel",
    "DG.TableController.newAttrDlg.defaultAttrName": "ny_var",
    "DG.TableController.newAttrDlg.attrNameHint": "Skriv inn navn for ny variabel",
    "DG.TableController.newAttrDlg.formulaHint": "Om ønskelig, skriv en formel for å regne ut verdier for denne variabelen",
    "DG.TableController.newAttrDlg.applyTooltip": "Definér den nye variabelen med navn og (valgfri) formel",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Skriv inn navn på den nye variabelen",
    "DG.TableController.newAttrDialog.AttributesCategory": "Variabler",
    "DG.TableController.newAttrDialog.SpecialCategory": "Spesiell",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Globale",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Konstanter",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Funksjoner",
    "DG.TableController.renameAttributeInvalidMsg": "Navn på variabel kan ikke være tomt ",
    "DG.TableController.renameAttributeInvalidDesc": "Skriv inn gyldig navn på variabel",
    "DG.TableController.renameAttributeDuplicateMsg": "Det finnes allerede en variabel med dette navnet",
    "DG.TableController.renameAttributeDuplicateDesc": "Skriv inn et unikt variabelnavn",
    "DG.TableController.deleteAttribute.confirmMessage": "Slette variabelen '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "Handlingen kan ikke angres.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Slett variabel",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Avbryt",
    "DG.TableController.deleteDataSet.confirmMessage": "Slett og ødelegg dette datasettet: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Denne handlingen kan ikke angres.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Slett datasett",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Avbryt",
    "DG.TableController.attrEditor.unitHint": "Måleenhet, hvis relevant",
    "DG.TableController.attrEditor.descriptionHint": "Beskriv variabelen",
    "DG.TableController.setScoreDlg.applyTooltip": "Angi formel for '%@' variabelen",
    "DG.TableController.setScoreDlg.formulaHint": "Skriv formel for å beregne verdier for denne variabelen",
    "DG.TableController.newAttributeTooltip": "Legg til ny variabel til denne tabellen",
    "DG.TableController.attributeEditor.title": "Egenskaper til variabel",
    "DG.CaseTableDropTarget.dropMessage": "slipp variabel for å opprette ny samling",
    "DG.CaseTable.defaultAttrName": "newAttr",
    "DG.CaseTable.indexColumnName": "index",
    "DG.CaseTable.indexColumnTooltip": "Radnummer (caseIndex) innenfor samlingen",
    "DG.CaseTable.indexMenu.insertCase": "Sett inn observasjon",
    "DG.CaseTable.indexMenu.insertCases": "Sett inn observasjoner...",
    "DG.CaseTable.indexMenu.deleteCase": "Slett observasjon",
    "DG.CaseTable.indexMenu.deleteCases": "Slett observasjoner",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "kategorisk",
    "DG.CaseTable.attribute.type.categorical": "kategorisk",
    "DG.CaseTable.attribute.type.numeric": "numerisk",
    "DG.CaseTable.attribute.type.date": "dato",
    "DG.CaseTable.attribute.type.qualitative": "kvalitativ",
    "DG.CaseTable.attribute.type.boundary": "grense",
    "DG.CaseTable.attributeEditor.name": "navn",
    "DG.CaseTable.attributeEditor.description": "beskrivelse",
    "DG.CaseTable.attributeEditor.type": "type",
    "DG.CaseTable.attributeEditor.unit": "enhet",
    "DG.CaseTable.attributeEditor.precision": "presisjon",
    "DG.CaseTable.attributeEditor.editable": "redigerbar",
    "DG.CaseTable.insertCasesDialog.title": "Sett inn observasjoner",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "#observasjoner som settes inn:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "plassering:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "før",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "etter",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Sett inn Observasjoner",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Sett inn antall observasjoner som angitt",
    "DG.CaseTableController.allTables": "Alle tabeller",
    "DG.AttrFormView.attrNamePrompt": "Variabel Navn",
    "DG.AttrFormView.formulaPrompt": "Formell:",
    "DG.AttrFormView.operandMenuTitle": "--- Sett inn verdi ---",
    "DG.AttrFormView.functionMenuTitle": "--- Sett inn funksjon ---",
    "DG.AttrFormView.applyBtnTitle": "Bruk",
    "DG.AttrFormView.cancelBtnTitle": "Avbryt",
    "DG.AttrFormView.cancelBtnTooltip": "Gå ut av dialogboksen uten å gjøre endringer",
    "DG.GuideConfigView.titlePrompt": "Guidetittel",
    "DG.GuideConfigView.titleHint": "Navn på aktivitet",
    "DG.GuideConfigView.itemTitleHint": "Seksjonsnavn",
    "DG.GuideConfigView.itemURLHint": "URL til seksjonen",
    "DG.GuideConfigView.okBtnTitle": "OK",
    "DG.GuideConfigView.okBtnToolTip": "Godta elementer i guidemenyen",
    "DG.GuideConfigView.cancelBtnTitle": "Avbryt",
    "DG.GuideConfigView.cancelBtnTooltip": "Gå ut av dialogboksen uten å gjøre endringer",
    "DG.GuideConfigView.httpWarning": "URL må starte med enten http:// eller https://",
    "DG.DataDisplayModel.rescaleToData": "Skalér tilbake for å vise alle observasjoner",
    "DG.DataDisplayModel.ShowConnectingLine": "Vis forbindelseslinjer",
    "DG.DataDisplayModel.HideConnectingLine": "Skjul forbindelseslinjer",
    "DG.AxisView.emptyGraphCue": "Klikk her, eller dra en variabel hit.",
    "DG.CellLinearAxisView.midPanelTooltip": "Dra for å oversette skala på akse",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Dra for å endre nedre grense på aksen",
    "DG.CellLinearAxisView.upperPanelTooltip": "Dra for å endre øver grense på aksen",
    "DG.PlotModel.mixup": "Fjern variabler fra aksene",
    "DG.PlotModel.showCount": "Vis antall observasjoner",
    "DG.PlotModel.hideCount": "Skjul antall observasjonser",
    "DG.ScatterPlotModel.sumSquares": ",\nKvadratsum = %@",
    "DG.ScatterPlotModel.slopeOnly": "stigning = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "per år",
    "DG.ScatterPlotModel.daysLabel": "per dag",
    "DG.ScatterPlotModel.hoursLabel": "per time",
    "DG.ScatterPlotModel.minutesLabel": "per minutt",
    "DG.ScatterPlotModel.secondsLabel": "per sekund",
    "DG.LegendView.attributeTooltip": "Klikk for å endre uthevet variabel",
    "DG.NumberToggleView.showAll": "Vis alle –",
    "DG.NumberToggleView.hideAll": "Skjul alle –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Siste",
    "DG.NumberToggleView.showAllTooltip": "Klikk for å vise alle observasjoner.\nKlikk merking av beslektede data for å skru synlighet av og på",
    "DG.NumberToggleView.hideAllTooltip": "Klikk for å skjule alle observasjoner.\nKlikk merking av beslektede observasjoner for å skru synlighet av og på",
    "DG.NumberToggleView.enableLastModeTooltip": "Klikk for å kun vise siste beslekta observasjoner",
    "DG.NumberToggleView.disableLastModeTooltip": "Klikk for å gå ut av siste beslekta observasjonsvisning",
    "DG.NumberToggleView.indexTooltip": "Klikk for å forandre synlighet",
    "DG.PlottedAverageAdornment.meanValueTitle": "gjennomsnitt=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "median=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 STDAV, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "Kvartilbredde=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "nedre=%@\nQ1=%@\nmedian=%@\nQ3=%@\nøvre=%@\nkvartilbredde=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Tegnforklaring: %@",
    "DG.DataDisplayMenu.remove": "Fjern variabel",
    "DG.DataDisplayMenu.removeAttribute_x": "Fjern X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Fjern Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Fjern Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Fjern tegnforklaring: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Behandle som kategori",
    "DG.DataDisplayMenu.treatAsNumeric": "Behandle som numerisk",
    "DG.DataDisplayMenu.hide": "Vis og skjul",
    "DG.DataDisplayMenu.hideSelectedPlural": "Skjul Valgte observasjoner",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Skjul Ikke-valgte observasjoner",
    "DG.DataDisplayMenu.hideSelectedSing": "Skjul Valgte observasjoner",
    "DG.DataDisplayMenu.hideUnselectedSing": "Skjul ikke-valgte observasjoner",
    "DG.DataDisplayMenu.enableNumberToggle": "Vis av/på-bryter for beslektede data",
    "DG.DataDisplayMenu.disableNumberToggle": "Skjul av/på-bryter for beslektede data",
    "DG.DataDisplayMenu.showAll": "Vis alle observasjoner",
    "DG.DataDisplayMenu.snapshot": "Ta øyeblikksbilde",
    "DG.GraphView.replaceAttribute": "Erstatt %@ med %@",
    "DG.GraphView.addAttribute": "Legg til variabel %@",
    "DG.GraphView.addToEmptyPlace": "Opprett akse med %@",
    "DG.GraphView.addToEmptyX": "Opprett x-akse med %@",
    "DG.GraphView.dropInPlot": "Fargelegg punkter med verdiene %@",
    "DG.GraphView.zoomTip": "Dobbelt-klikk for å zoome in. \nShift+dobbelt-klikk for å zoome ut.",
    "DG.GraphView.rescale": "Skalér tilbake for å vise alle observasjoner",
    "DG.AxisView.labelTooltip": "—Klikk for å endre %@ variabler til akse",
    "DG.AxisView.vertical": "loddrett",
    "DG.AxisView.horizontal": "vannrett",
    "DG.DataTip.connectingLine": "%@: %@\nmed %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formel",
    "DG.PlottedValue.namePrompt": "Plottet verdi",
    "DG.PlottedValue.formulaPrompt": "verdi=",
    "DG.PlottedValue.formulaHint": "\n \u200b",
    "DG.PlottedFunction.namePrompt": "Plottet funksjon",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Skriv et uttrykk f.eks. x*x/30 - 50",
    "DG.MapView.showGrid": "Vis rutenett",
    "DG.MapView.hideGrid": "Skjul rutenett",
    "DG.MapView.showPoints": "Vis punkter",
    "DG.MapView.hidePoints": "Skjul punkter",
    "DG.MapView.marqueeHint": "Markér punkter i kartet",
    "DG.MapView.gridControlHint": "Endre størrelse på ruter i rutenett",
    "DG.Inspector.values": "Mål",
    "DG.Inspector.styles": "Format",
    "DG.Inspector.pointSize": "Punktstørrelse:",
    "DG.Inspector.transparency": "Gjennomsiktighet:",
    "DG.Inspector.color": "Farge:",
    "DG.Inspector.legendColor": "Fargeforklaring:",
    "DG.Inspector.backgroundColor": "Bakgrunnsfarge:",
    "DG.Inspector.stroke": "Linjefarge:",
    "DG.Inspector.rescale.toolTip": "Reskalér for å vise alle observasjoner",
    "DG.Inspector.mixUp.toolTip": "Bland alle punkter",
    "DG.Inspector.hideShow.toolTip": "Vis alle observasjoner eller skjul valgte/ikke-valgte observasjoner",
    "DG.Inspector.delete.toolTip": "Slette valgte eller ikke-valgte observasjoner",
    "DG.Inspector.sliderValues.toolTip": "Still inn animasjon av glidebryter, retning, hastighet, ...",
    "DG.Inspector.webViewEditURL.toolTip": "Endre URLen til nettsida som vises",
    "DG.Inspector.selection.selectAll": "Velg alle observasjoner",
    "DG.Inspector.selection.deleteSelectedCases": "Slett valgte observasjoner",
    "DG.Inspector.selection.deleteUnselectedCases": "Slett ikke-valgte observasjoner",
    "DG.Inspector.deleteAll": "Slett alle observasjoner",
    "DG.Inspector.deleteDataSet": "Slett og ødelegg datasett",
    "DG.Inspector.displayValues.toolTip": "Endre hva som vises sammen med punktene",
    "DG.Inspector.displayStyles.toolTip": "Endre utseende til vinduet",
    "DG.Inspector.makeImage.toolTip": "Lagre bilde som PNG-fil",
    "DG.Inspector.displayShow": "Vis...",
    "DG.Inspector.colorPicker.more": "mer",
    "DG.Inspector.colorPicker.less": "færre",
    "DG.Inspector.graphTransparency": "Gjennomsiktlig",
    "DG.Inspector.graphCount": "Antall observasjoner",
    "DG.Inspector.graphPercent": "Prosent",
    "DG.Inspector.graphRow": "Rad",
    "DG.Inspector.graphColumn": "Kolonne",
    "DG.Inspector.graphCell": "Celle",
    "DG.Inspector.graphConnectingLine": "Forbindelseslinjer",
    "DG.Inspector.graphMovableLine": "Flyttbar linje",
    "DG.Inspector.graphInterceptLocked": "Skjæringspunkt låst",
    "DG.Inspector.graphPlottedFunction": "Plottet funksjon",
    "DG.Inspector.graphSquares": "Kvadratene av residualer",
    "DG.Inspector.graphLSRL": "Minste kvadraters-linje",
    "DG.Inspector.graphMovableValue": "Flyttbar verdi",
    "DG.Inspector.graphAdd": "Legg til",
    "DG.Inspector.graphRemove": "Fjern",
    "DG.Inspector.graphPlottedMean": "Gjennomsnitt",
    "DG.Inspector.graphPlottedMedian": "Median",
    "DG.Inspector.graphPlottedStDev": "Standardavvik",
    "DG.Inspector.graphPlottedIQR": "Kvartilbredde",
    "DG.Inspector.graphPlottedBoxPlot": "Boksplott",
    "DG.Inspector.graphPlottedValue": "Plottet verdi",
    "DG.Inspector.attributes.toolTip": "Opprett nye variabler. Eksporter observasjonsdata.",
    "DG.Inspector.resize.toolTip": "Tilpass kolonner til innhold",
    "DG.Inspector.newAttribute": "Ny variabel i %@...",
    "DG.Inspector.randomizeAllAttributes": "Gjør alt tilfeldig på nytt",
    "DG.Inspector.exportCaseData": "Eksportér observasjonsdata...",
    "DG.Inspector.mapGrid": "Rutenett",
    "DG.Inspector.mapPoints": "Punkter",
    "DG.Inspector.mapLines": "Forbindelseslinjer",
    "DG.GameController.continuityError": "Dessverre, etter at rekkefølgen til kolonne har blitt endret, kan ikke nye data aksepteres.",
    "DG.GameView.loading": "Laster",
    "DG.GameView.loadError": "Hvis du ser denne teksten, kan lasting av URLen over ha gått feil.\nPrøv lenken i en annen fane i nettleseren eller meld feilen til http://codap.concord. org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "Er du sikker?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Ja, lukk",
    "DG.Component.closeComponent.cancelButtonTitle": "Avbryt",
    "DG.GameController.confirmCloseDescription": "Hvis du lukker denne, kan det hende du ikke kan legge til mer data",
    "DG.WebView.defaultTitle": "Nettside",
    "DG.mainPage.exceptionMessage": "Det har oppstått en feil som kan påvirke hvordan dette programmet oppfører seg. Du kan lagre arbeidet ditt, og prøve å laste siden på nytt.",
    "DG.fileMenu.provider.examples.displayName": "Eksempeldokumenter",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Åpne en programutvidelse",
    "DG.Undo.graph.showMovablePoint": "Angre vis flyttbart punkt",
    "DG.Redo.graph.showMovablePoint": "Gjør om viser flyttbart punkt",
    "DG.Undo.graph.hideMovablePoint": "Angre skjul flyttbart punkt",
    "DG.Redo.graph.hideMovablePoint": "Gjør om skjul flyttbart punkt",
    "DG.Undo.graph.moveMovablePoint": "Angre flytte punkt",
    "DG.Redo.graph.moveMovablePoint": "Gjør om flytte punkt",
    "DG.DataDisplayMenu.copyAsImage": "Åpne i tegneverktøy",
    "DG.DataDisplayMenu.exportImage": "Eksportér bilde...",
    "DG.DataDisplayMenu.imageOfTitle": "Bilde av%@",
    "DG.Inspector.graphMovablePoint": "Flyttbart punkt",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Åpne tabell for dette datasettet",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Opprett nytt datasett",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Slett og ødelegg datasettet",
    "DG.Undo.graph.showAsBarChart": "Angre slå sammen prikker til søyler",
    "DG.Redo.graph.showAsBarChart": "Gjenta slå sammen prikker til søyler",
    "DG.Undo.graph.showAsDotChart": "Angre løse opp søyler til prikker",
    "DG.Redo.graph.showAsDotChart": "Gjenta løse opp søyler til prikker",
    "DG.CountAxisView.countLabel": "Antall observasjoner",
    "DG.CountAxisView.countLabelDescription": "Antall observasjoner i søylen langs denne aksen",
    "DG.CountAxisView.percentLabel": "Prosent",
    "DG.CountAxisView.percentLabelDescription": "Prosent observasjoner i søylen langs denne aksen",
    "DG.BarChartModel.cellTipPlural": "%@ av %@ %@ (%@%) er %@",
    "DG.BarChartModel.cellTipSingular": "%@ av %@ %@ (%@%) er %@",
    "DG.Inspector.configuration": "Konfigurering",
    "DG.Inspector.displayConfiguration.toolTip": "Still inn visngen på anne måte",
    "DG.Inspector.displayScale": "Målestokk...",
    "DG.Inspector.graphBarChart": "Slå sammen punkter til søyler",
    "DG.Locale.name.de": "Tysk",
    "DG.Locale.name.en": "Engelsk",
    "DG.Locale.name.es": "Spansk",
    "DG.Locale.name.he": "Hebraisk",
    "DG.Locale.name.tr": "Tyrkisk",
    "DG.Locale.name.zh": "Kinesisk",
    "DG.Undo.graph.swapCategories": "Angre endring av rekkefølge på kategorier",
    "DG.Redo.graph.swapCategories": "Gjør om endring av rekkefølge på kategorier",
    "DG.TableController.collectionTitleText": "%@1 (%@2 observasjoner)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 observasjoner, %@3 satt til side)\n",
    "DG.Inspector.setaside.setAsideSelectedCases": "Ta ut valgte observasjoner ",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Ta ut ikke-valgte observasjoner",
    "DG.Inspector.setaside.restoreSetAsideCases": "Gjenopprett %@ observasjoner som er tatt ut",
    "DG.DocumentController.caseCardTitle": "Observasjonskort",
    "DG.DocumentController.toggleToCaseCard": "Bytt til kortvisning av observasjonene",
    "DG.DocumentController.toggleToCaseTable": "Bytt til tabellvisning av observasjonene",
    "DG.CaseCard.indexString": "1 av %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ valgt av %@ %@",
    "DG.CaseCard.summaryValues": "%@ verdier",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Velg og vis neste observasjon",
    "DG.CaseCard.navPrevCase": "Velg og vis forrige observasjon",
    "DG.CaseCard.navFirstCase": "Velg og vis første observasjon",
    "DG.CaseCard.navLastCase": "Velg og vis siste observasjon",
    "DG.Undo.component.toggleTableToCard": "Angre endre fra tabell til kort",
    "DG.Redo.component.toggleTableToCard": "Gjør om endre fra tabell til kort",
    "DG.Undo.component.toggleCardToTable": "Angre endre fra kort til tabell",
    "DG.Redo.component.toggleCardToTable": "Gjør om endre fra kort til tabell",
    "DG.Undo.graph.addBackgroundImage": "Angre legg til bakgrunnsbilde på graf",
    "DG.Redo.graph.addBackgroundImage": "Gjør om legg til bakgrunnsbilde på graf",
    "DG.Undo.graph.removeBackgroundImage": "Angre fjern bakgrunnsbilde på graf",
    "DG.Redo.graph.removeBackgroundImage": "Gjør om fjern bakgrunnsbilde på graf",
    "DG.Undo.graph.lockBackgroundImage": "Angre lås bakgrunnsbilde til akser",
    "DG.Redo.graph.lockBackgroundImage": "Gjør om lås bakgrunnsbilde til akser",
    "DG.Undo.graph.unlockBackgroundImage": "Angre løsne bakgrunnsbilde fra akser",
    "DG.Redo.graph.unlockBackgroundImage": "Gjør om løsne bakgrunnsbilde fra akser",
    "DG.Undo.enableMeasuresForSelection": "Angre Vis målinger for utvalg",
    "DG.Redo.enableMeasuresForSelection": "Gjør om Vis målinger for utvalg",
    "DG.Undo.disableMeasuresForSelection": "Angre Skjul målinger for utvalg",
    "DG.Redo.disableMeasuresForSelection": "Gjør om Skjul målinger for utvalg",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Vis Måling for utvalg",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Skjul Målinger for utvalg",
    "DG.DataDisplayMenu.addBackgroundImage": "Legg til bakgrunnsbilde",
    "DG.DataDisplayMenu.lockImageToAxes": "Lås bakgrunnsbilde til akser",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Løsne bakgrunnsbilde fra akser",
    "DG.DataDisplayMenu.removeBackgroundImage": "Fjern bakgrunnsbilde",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Slett formel (behold verdier)",
    "DG.TableController.headerMenuItems.recoverFormula": "Gjenopprett slettet formel",
    "DG.Inspector.displayLayers.toolTip": "Endre utseende til kartlag",
    "DG.Inspector.layers": "Lag",
    "DG.Undo.graph.repositionEquation": "Angre omplassering av likning",
    "DG.Redo.graph.repositionEquation": "Gjør om flytt likning",
    "DG.TableController.attrEditor.precisionNumericHint": "Antall siffer etter desimalkomma",
    "DG.TableController.attrEditor.precisionDateHint": "Avgjør hvor mye av datoen som vises",
    "DG.TableController.attrEditor.typeHint": "Velg for å tvinge variabler til å bli behandlet som en spesiell type",
    "DG.TableController.attrEditor.nameHint": "Navnet på variabelen vises i tabell, på kort og på aksene til grafen",
    "DG.TableController.attrEditor.editableHint": "Hvis variabelen ikke kan redigeres, så kan ikke verdiene og/eller formelen endres.",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "år måned dag time minutt sekund",
    "DG.AttributeFormat.DatePrecision.year": "ÅÅÅÅ",
    "DG.AttributeFormat.DatePrecision.month": "MMM YYYY",
    "DG.AttributeFormat.DatePrecision.day": "D. MMM YYYY",
    "DG.AttributeFormat.DatePrecision.hour": "D. MMM YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "D. MMM YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "D. MMM YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@ av %@",
    "DG.CaseCard.attrHintDescription": "%@: %@",
    "DG.CaseCard.attrHintFormula": "%@\n%@",
    "DG.AppController.optionMenuItems.help-forum": "Hjelp...",
    "DG.AppController.showHelpForumTitle": "Hjelp",
    "DG.Locale.name.el": "Gresk",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ av %@ (%@%) er %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ av %@ (%@%) er %@",
    "DG.DataDisplayMenu.removeAttribute_top": "Fjern side-ved-side layout med %@",
    "DG.DataDisplayMenu.removeAttribute_right": "Fjern virtuell layout med %@",
    "DG.GraphView.layoutPlotsSideBySide": "Layout side-ved-side med %@",
    "DG.GraphView.layoutPlotsVertically": "Vertikal visning med %@",
    "DG.Undo.graph.makeStrokeSameAsFill": "Angre gjør linjefarge og fyllfarge lik",
    "DG.Redo.graph.makeStrokeSameAsFill": "Gjør om gjør linjefarge og fyllfarge lik",
    "DG.Undo.graph.makeStrokeIndependent": "Angre gjør linjefarge og fyllfarge uavhengige",
    "DG.Redo.graph.makeStrokeIndependent": "Gjør om gjør linjefarge og fyllfarge uavhengige",
    "DG.Inspector.strokeSameAsFill": "Linjefarge lik fyllfarge",
    "DG.Formula.DateShortDaySunday": "Søn",
    "DG.Formula.DateShortDayMonday": "Man",
    "DG.Formula.DateShortDayTuesday": "Tir",
    "DG.Formula.DateShortDayWednesday": "Ons",
    "DG.Formula.DateShortDayThursday": "Tor",
    "DG.Formula.DateShortDayFriday": "Fre",
    "DG.Formula.DateShortDaySaturday": "Lør",
    "DG.AttributeFormat.DatePrecision.millisecond": "D. MMM YYYY HH:mm:ss.SSS",
    "DG.CellAxis.other": "ANDRE",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 GAA, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "Gjennomsnittlig absolutt avvik",
    "DG.Undo.graph.showPlottedBoxPlot": "Angre vis boxplot",
    "DG.Redo.graph.hidePlottedBoxPlot": "Gjør om skjul boxplot",
    "DG.Undo.graph.hidePlottedBoxPlot": "Angre skjul boxplot",
    "DG.Redo.graph.showPlottedBoxPlot": "Gjør om visning av box plot",
    "DG.Undo.graph.showOutliers": "Angre visning av \"uteliggere\"",
    "DG.Redo.graph.hideOutliers": "Gjør om visning av \"uteliggere\"",
    "DG.Undo.graph.hideOutliers": "Angre skjuling av \"uteliggere\"",
    "DG.Redo.graph.showOutliers": "Gjør om skjuling av \"uteliggere\"",
    "DG.Inspector.graphBoxPlotShowOutliers": "Vis \"uteliggere\"",
    "DG.Locale.name.nb": "Norsk (bokmål)",
    "DG.Locale.name.nn": "Norsk (nynorsk)",
    "DG.CaseCard.newCaseToolTip": "Legg til tom observasjon til denne samlingen",
    "DG.TableController.headerMenuItems.renameAttribute": "Gi nytt navn",
    "DG.Undo.graph.fuseDotsToRectangles": "Undo fusing dots into rectangles",
    "DG.Redo.graph.fuseDotsToRectangles": "Redo fusing dots into rectangles",
    "DG.Undo.graph.dissolveRectanglesToDots": "Undo dissolving rectangles into dots",
    "DG.Redo.graph.dissolveRectanglesToDots": "Redo dissolving rectangles into dots",
    "DG.Undo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Redo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Undo.graph.showAsBinnedPlot": "Undo grouping dots into bins",
    "DG.Redo.graph.showAsBinnedPlot": "Redo grouping dots into bins",
    "DG.Undo.graph.showAsDotPlot": "Undo ungrouping dots from bins",
    "DG.Redo.graph.showAsDotPlot": "Redo ungrouping dots from bins",
    "DG.Undo.graph.dragBinBoundary": "Undo dragging bin boundary",
    "DG.Redo.graph.dragBinBoundary": "Redo dragging bin boundary",
    "DG.Undo.graph.changeBinWidth": "Undo changing bin width",
    "DG.Redo.graph.changeBinWidth": "Redo changing bin width",
    "DG.Undo.graph.changeBinAlignment": "Undo changing bin alignment",
    "DG.Redo.graph.changeBinAlignment": "Redo changing bin alignment",
    "DG.BinnedPlotModel.dragBinTip": "Drag to change bin width",
    "DG.HistogramView.barTipPlural": "%@ of %@ %@ (%@%) are ≥ %@ and < %@",
    "DG.HistogramView.barTipSingular": "%@ of %@ %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendSingular": "%@ of %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendPlural": "%@ of %@ (%@%) are ≥ %@ and < %@",
    "DG.Inspector.graphGroupIntoBins": "Group into Bins",
    "DG.Inspector.graphBinWidth": "Bin width",
    "DG.Inspector.graphAlignment": "Alignment",
    "DG.CaseTable.dividerView.expandAllTooltip": "expand all groups",
    "DG.CaseTable.dividerView.expandGroupTooltip": "expand group",
    "DG.CaseTable.dividerView.collapseAllTooltip": "collapse all groups",
    "DG.CaseTable.dividerView.collapseGroupTooltip": "collapse group",
    "DG.BinnedPlotModel.binLabelTip": "Values in this bin are ≥ %@ and < %@",
    "DG.Component.closeComponent.toolTip": "Close this Component",
    "DG.Component.minimizeComponent.toolTip": "Minimize or expand this Component",
    "DG.Locale.name.ja": "Japanese",
    "DG.CaseCard.attrHintDescriptionAndFormula": "%@1: %@2\n%@1 = %@3",
    "DG.Locale.name.zh-Hans": "Simplified Chinese",
    "DG.PlottedCount.withoutSelection": "%@",
    "DG.PlottedCount.withSelection": "%@ selected",
    "DG.PlottedPercent.withoutSelection": "%@%",
    "DG.PlottedPercent.withSelection": "%@% selected",
    "DG.PlottedCountPercent.withoutSelection": "%@ (%@%)",
    "DG.PlottedCountPercent.withSelection": "%@ of %@ (%@%) selected",
    "DG.Undo.caseTable.resizeColumn": "Undo fit width to content",
    "DG.Redo.caseTable.resizeColumn": "Redo fit width to content",
    "DG.TableController.headerMenuItems.resizeColumn": "Fit width to content",
    "DG.SelectedInfoView.infoPlural": "Showing measures for %@ selected cases",
    "DG.SelectedInfoView.infoSing": "Showing measures for %@ selected case",
    "DG.Inspector.copyCaseDataToClipboard": "Copy to Clipboard...",
    "DG.Inspector.caseTable.exportCaseDialog.copyFrom": "Copy case data from:",
    "DG.Inspector.caseTable.exportCaseDialog.copy": "Copy",
    "DG.Inspector.caseTable.exportCaseDialog.copyTooltip": "Copy data to clipboard",
    "DG.Inspector.caseTable.exportCaseDialog.copiedData": "Copied %@ to the clipboard",
    "DG.Undo.caseTable.hideAttribute": "Undo hiding attribute",
    "DG.Redo.caseTable.hideAttribute": "Redo hiding attribute",
    "DG.Undo.caseTable.showAllHiddenAttributes": "Undo show all hidden attributes",
    "DG.Redo.caseTable.showAllHiddenAttributes": "Redo show all hidden attributes",
    "DG.TableController.headerMenuItems.hideAttribute": "Hide Attribute",
    "DG.Inspector.attributes.showAllHiddenAttributesSing": "Show %@ Hidden Attribute",
    "DG.Inspector.attributes.showAllHiddenAttributesPlural": "Show %@ Hidden Attributes",
    "DG.Inspector.attributes.showAllHiddenAttributesDisabled": "Show Hidden Attributes",
    "DG.Inspector.getCaseDataFromClipboard": "Import Case Data from Clipboard...",
    "DG.CaseCard.addCaseButton": "add case",
    "DG.Undo.DataContext.join": "Undo join of %@ to %@",
    "DG.Redo.DataContext.join": "Redo join of %@ to %@",
    "DG.Collection.joinTip": "Join %@ in %@ to %@ in %@ by matching %@ with %@",
    "DG.Inspector.graphPlotPoints": "Points",
    "DG.Inspector.graphBarForEachPoint": "Bar for Each Point",
    "DG.Undo.graph.changeBarChartFunction": "Undo change bar chart formula",
    "DG.Redo.graph.changeBarChartFunction": "Redo change bar chart formula",
    "DG.Undo.graph.showAsLinePlot": "Undo bar for each point",
    "DG.Redo.graph.showAsLinePlot": "Redo bar for each point",
    "DG.Undo.graph.showAsStandardBarChart": "Undo using count or percent for bar chart scale",
    "DG.Redo.graph.showAsStandardBarChart": "Redo using count or percent for bar chart scale",
    "DG.Undo.graph.showAsComputedBarChart": "Undo computing bar length with formula",
    "DG.Redo.graph.showAsComputedBarChart": "Redo computing bar length with formula",
    "DG.FormulaAxisView.labelDescription": "The expression that determines the length of the bars. Click to edit.",
    "DG.ComputedBarChartModel.cellTip": "For group %@ the value is %@",
    "DG.BarChartFunction.namePrompt": "Bar Chart",
    "DG.BarChartFunction.formulaPrompt": "bar length =",
    "DG.BarChartFunction.formulaHint": "Type a formula to compute bar length",
    "DG.BarChartFunction.emptyExpressionAxisPrompt": "Click here to provide a formula",
    "DG.Inspector.graphFormula": "Formula",
    "DG.Undo.displayOnlySelected": "Undo displaying only selected cases",
    "DG.Redo.displayOnlySelected": "Redo displaying only selected cases",
    "DG.Undo.webView.show": "Undo adding webView component",
    "DG.Redo.webView.show": "Redo adding webView component",
    "DG.Undo.imageComponent.show": "Undo adding image component",
    "DG.Redo.imageComponent.show": "Redo adding image component",
    "DG.DataDisplayMenu.displayOnlySelected": "Display Only Selected Cases",
    "DG.DataDisplayMenu.displayingOnlySelected": "Displaying Only Selected Cases",
    "DG.PlotBackgroundView.msg0": "This graph is set to display",
    "DG.PlotBackgroundView.msg1": "only selected cases.",
    "DG.PlotBackgroundView.msg2": "No cases are selected",
    "DG.PlotBackgroundView.msg3": "so nothing is being displayed.",
    "DG.PlotBackgroundView.msg4": "You can select cases in a",
    "DG.PlotBackgroundView.msg5": "case table or another graph.",
    "DG.ImageComponent.defaultTitle": "Image",
    "DG.TableController.datasetMetadata.title": "Dataset Information",
    "DG.CaseTable.datasetMetadata.url": "source",
    "DG.CaseTable.datasetMetadata.creationDate": "import date",
    "DG.TableController.datasetMetadata.descriptionHint": "Describe the dataset",
    "DG.Inspector.datasetInfo.toolTip": "Display information about dataset",
    "DG.CaseTable.indexMenu.moveEntryRow": "Move Data Entry Row Here",
    "DG.CaseCard.deselect": "Deselect all cases",
    "DG.CaseCard.noDeselect": "No cases are selected",
    "DG.CaseTable.indexProto.tooltip": "Drag to place data entry row within this table",
    "DG.AttributeFormat.DatePrecisionShort.year": "YYYY",
    "DG.AttributeFormat.DatePrecisionShort.month": "M/YY",
    "DG.AttributeFormat.DatePrecisionShort.day": "M/D/YY",
    "DG.AttributeFormat.DatePrecisionShort.hour": "M/D/YY HH:00",
    "DG.AttributeFormat.DatePrecisionShort.minute": "M/D/YY HH:mm",
    "DG.AttributeFormat.DatePrecisionShort.second": "M/D/YY HH:mm:ss",
    "DG.AttributeFormat.DatePrecisionShort.millisecond": "M/D/YY HH:mm:ss.SSS",
    "DG.Formula.FuncCategoryLogic": "Logic Functions",
    "DG.Undo.graph.showMeasureLabels": "Undo showing measure labels",
    "DG.Redo.graph.showMeasureLabels": "Redo showing measure labels",
    "DG.Undo.graph.hideMeasureLabels": "Undo hiding measure labels",
    "DG.Redo.graph.hideMeasureLabels": "Redo hiding measure labels",
    "DG.Inspector.showLabels": "Show Measure Labels",
    "DG.Undo.caseTable.resizeOneColumn": "Undo resize column",
    "DG.Redo.caseTable.resizeOneColumn": "Redo resize column",
    "DG.CaseTable.attribute.type.checkbox": "checkbox",
    "DG.AppController.caseTableMenu.clipboardDataset": "-- new from clipboard --",
    "DG.AppController.caseTableMenu.clipboardDatasetToolTip": "Paste data set from clipboard",
    "DG.AppController.optionMenuItems.toPrivacyPage": "Privacy Page...",
    "DG.plugin.Importer.title": "Import CSV to CODAP",
    "DG.plugin.Importer.enter-url": "Enter url: ",
    "DG.plugin.Importer.or": "or",
    "DG.plugin.Importer.downsample-section": "Downsample Options...",
    "DG.plugin.Importer.downsample-random-p1": "Randomly select",
    "DG.plugin.Importer.downsample-random-p2": "rows",
    "DG.plugin.Importer.downsample-every-nth-p1": "Select every",
    "DG.plugin.Importer.downsample-every-nth-p2": "th row",
    "DG.plugin.Importer.downsample-import-all": "Import all rows",
    "DG.plugin.Importer.target-options-title": "Target Options...",
    "DG.plugin.Importer.target-options-replace": "Replace existing dataset with this one",
    "DG.plugin.Importer.target-options-append": "Append this dataset to the existing one",
    "DG.plugin.Importer.target-options-create-new": "Create a new data set",
    "DG.plugin.Importer.button-cancel": "Cancel",
    "DG.plugin.Importer.button-submit": "OK",
    "DG.plugin.Importer.button-dismiss": "Dismiss",
    "DG.plugin.Importer.load-error": "There was an error loading this resource: \"%@\" reason: \"%@\"",
    "DG.plugin.Importer.no-table-error": "Could not find tabular data in a format that can be imported into CODAP",
    "DG.plugin.Importer.duplicate-dataset-msg": "There already exists a dataset like this one. It is named \"%@\".",
    "DG.plugin.Importer.upload-time-msg": "It was uploaded %@",
    "DG.plugin.Importer.large-file-msg": "The imported file, \"%@\" has %@ rows. With more than %@ rows CODAP performance may be sluggish. You can work with a sample of the data at least at first, replacing it with the full dataset later.",
    "DG.plugin.Importer.error-codap-connection": "Error sending data to CODAP",
    "DG.plugin.Importer.error-upload": "Could not import this file -- %@",
    "DG.plugin.Importer.import-message": "Preparing to import %@ rows into \"%@\" from a table with %@ attributes: %@%@",
    "DG.Undo.component.componentTitleChange": "Undo changing the component title",
    "DG.Redo.component.componentTitleChange": "Redo changing the component title"
});