import { TableTileElements as table } from "../support/elements/table-tile"
import { CardTileElements as card } from "../support/elements/card-tile"
import { ComponentElements as c } from "../support/elements/component-elements"
import { ToolbarElements as toolbar } from "../support/elements/toolbar-elements"
import { FormulaHelper as fh } from "../support/helpers/formula-helper"

context("case card", () => {
  beforeEach(() => {
    // cy.scrollTo() doesn't work as expected with `scroll-behavior: smooth`
    const queryParams =
      "?sample=mammals&mouseSensor&scrollBehavior=auto&noComponentAnimation=true&suppressUnsavedWarning"
    const url = `${Cypress.config("index")}${queryParams}`
    cy.visit(url)
    cy.wait(2000)
  })

  describe("case card", () => {
    it("can switch from case table to case card view and back with undo/redo", () => {
      // Initial checks case table->case card
      cy.get('[data-testid="codap-case-table"]').should("exist")
      cy.get('[data-testid="codap-case-card"]').should("not.exist")
      table.getToggleCardView().click()
      table.getToggleCardMessage().should("have.text", "Switch to case card view of the data").click()
      cy.wait(500)
      cy.get('[data-testid="codap-case-table"]').should("not.exist")
      cy.get('[data-testid="codap-case-card"]').should("exist")
      c.checkComponentFocused("case-card")
      table.getToggleCardView().click()
      cy.wait(500)
      table.getToggleCardMessage().should("have.text", "Switch to case table view of the data").click()
      cy.get('[data-testid="codap-case-table"]').should("exist")
      cy.get('[data-testid="codap-case-card"]').should("not.exist")

      // Perform undo actions
      toolbar.getUndoTool().click()  // Undo switch
      cy.get('[data-testid="codap-case-table"]').should("not.exist")
      cy.get('[data-testid="case-card-view"]').should("exist")

      // Perform redo actions
      toolbar.getRedoTool().click()  // Redo switch to case table
      cy.get('[data-testid="codap-case-table"]').should("exist")
      cy.get('[data-testid="case-card-view"]').should("not.exist")
    })
    it("initially displays a summary view of all cases and whenever 'Summarize Dataset' button is clicked", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getViewTitle().should("have.text", "Cases")
      card.getIndexText().should("have.text", "27 cases")
      card.getAttributeNames().eq(0).should("contain.text", "Mammal")
      card.getAttributeValues().eq(0).should("have.text", "27 values")
      card.getAttributeNames().eq(1).should("contain.text", "Order")
      card.getAttributeValues().eq(1).should("have.text", "12 values")
      card.getAttributeNames().eq(2).should("contain.text", "LifeSpan")
      card.getAttributeValues().eq(2).should("have.text", "3-80")
      card.getAttributeNames().eq(3).should("contain.text", "Height")
      card.getAttributeValues().eq(3).should("have.text", "0.1-6.5")
      card.getAttributeNames().eq(4).should("contain.text", "Mass")
      card.getAttributeValues().eq(4).should("have.text", "0.02-6400")
      card.getAttributeNames().eq(5).should("contain.text", "Sleep")
      card.getAttributeValues().eq(5).should("have.text", "2-20")
      card.getAttributeNames().eq(6).should("contain.text", "Speed")
      card.getAttributeValues().eq(6).should("have.text", "1-110")
      card.getAttributeNames().eq(7).should("contain.text", "Habitat")
      card.getAttributeValues().eq(7).should("have.text", "3 values")
      card.getAttributeNames().eq(8).should("contain.text", "Diet")
      card.getAttributeValues().eq(8).should("have.text", "3 values")
      cy.log("Switch to individual cases view.")
      card.getSummaryButton().should("have.text", "Browse Individual Cases")
      card.getSummaryButton().click()
      card.getAttributeValues().eq(0).should("have.text", "African Elephant")
      card.getAttributeValues().eq(1).should("have.text", "Proboscidae")
      card.getAttributeValues().eq(2).should("have.text", "70")
      card.getAttributeValues().eq(3).should("have.text", "4")
      card.getAttributeValues().eq(4).should("have.text", "6400")
      card.getAttributeValues().eq(5).should("have.text", "3")
      card.getAttributeValues().eq(6).should("have.text", "40")
      card.getAttributeValues().eq(7).should("have.text", "land")
      card.getAttributeValues().eq(8).should("have.text", "plants")
      card.getSummaryButton().should("have.text", "Summarize Dataset")
      cy.log("Switch back to summary view.")
      card.getSummaryButton().click()
      card.getAttributeValues().eq(0).should("have.text", "27 values")
      card.getAttributeValues().eq(1).should("have.text", "12 values")
      card.getAttributeValues().eq(2).should("have.text", "3-80")
      card.getAttributeValues().eq(3).should("have.text", "0.1-6.5")
      card.getAttributeValues().eq(4).should("have.text", "0.02-6400")
      card.getAttributeValues().eq(5).should("have.text", "2-20")
      card.getAttributeValues().eq(6).should("have.text", "1-110")
      card.getAttributeValues().eq(7).should("have.text", "3 values")
      card.getAttributeValues().eq(8).should("have.text", "3 values")
      cy.get('[data-testid="summary-view-toggle-button"]').should("have.text", "Browse Individual Cases")
    })
    it("should not initially display a summary view of all cases if there is a selection", () => {
      table.getGridCell(6, 2).should("contain", "Cheetah").click()
      table.toggleCaseView()
      cy.wait(500)
      card.getAttributeNames().eq(0).should("contain.text", "Mammal")
      card.getAttributeValues().eq(0).should("have.text", "Cheetah")
      card.getAttributeValues().eq(1).should("have.text", "Carnivora")
      card.getAttributeValues().eq(2).should("have.text", "14")
    })
    it("displays cases and allows user to scroll through them", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getCaseCardView().should("have.length", 1)
      card.getViewTitle().should("have.text", "Cases")
      card.getPreviousButton().should("not.be.disabled")
      card.getNextButton().should("not.be.disabled")
      card.getIndexText().should("have.text", "27 cases")
      card.getAttributeNames().first().should("contain.text", "Mammal")
      card.getAttributeValues().first().should("have.text", "27 values")
      card.getAttributes().should("have.length", 9)
      card.getAttributeNames().should("have.length", 9)
      card.getAttributeValues().should("have.length", 9)
      // Navigating to the previous case when no cases are selected displays the last case
      card.getPreviousButton().click()
      card.getIndexText().should("have.text", "27 of 27")
      card.getAttributeValues().first().should("have.text", "Spotted Hyena")
      card.getPreviousButton().click()
      card.getAttributeValues().first().should("have.text", "Red Fox")
      card.getNextButton().should("not.be.disabled").click()
      card.getAttributeValues().first().should("have.text", "Spotted Hyena")
      card.getNextButton().should("be.disabled")
    })
    it("displays case data in a hierarchy when there is a parent collection", () => {
      // make a parent collection
      table.moveAttributeToParent("Order", "newCollection")
      cy.wait(500)
      table.toggleCaseView()
      cy.wait(500)
      card.getCaseCardView().should("have.length", 2)
      card.getCaseCardView().eq(0).should("have.class", "color-cycle-2")
      card.getCaseCardView().eq(1).should("have.class", "color-cycle-1")
      card.getViewTitle().should("have.length", 2)
      card.getViewTitle().eq(0).should("have.text", "Orders")
      card.getViewTitle().eq(1).should("have.text", "Cases")
      card.getPreviousButton().should("have.length", 2).and("not.be.disabled")
      card.getNextButton().should("have.length", 2).and("not.be.disabled")
      card.getIndexText().should("have.length", 2)
      card.getIndexText().eq(0).should("have.text", "12 cases")
      card.getIndexText().eq(1).should("have.text", "27 cases")
      card.getAttrs().should("have.length", 2)
      card.getAttrs().eq(0).find('[data-testid="case-card-attr"]').should("have.length", 1)
      card.getAttrs().eq(0).find('[data-testid="case-card-attr-name"]')
                                                 .eq(0).should("contain.text", "Order")
      card.getAttrs().eq(0).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("have.text", "12 values")
      card.getAttrs().eq(1).find('[data-testid="case-card-attr"]').should("have.length", 8)
      card.getAttrs().eq(1).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("have.text", "27 values")
      card.getNextButton().eq(0).click()
      card.getIndexText().eq(0).should("have.text", "1 of 12")
      card.getAttrs().eq(0).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("have.text", "Proboscidae")
      card.getAttrs().eq(1).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("have.text", "African Elephant, Asian Elephant")
      card.getIndexText().eq(1).should("have.text", "2 cases")
      card.getNextButton().eq(1).click()
      card.getIndexText().eq(0).should("have.text", "1 of 12")
      card.getAttrs().eq(0).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("have.text", "Proboscidae")
      card.getIndexText().eq(1).should("have.text", "1 of 2")
      card.getAttrs().eq(1).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("have.text", "African Elephant")

      // The first selected case is selected when the browse individual case button is clicked
      card.getSummaryButton().click()
      card.getNextButton().eq(0).click().click().click().click()
      card.getAttrs().eq(0).find('[data-testid="case-card-attr-value"]')
        .eq(0).should("have.text", "Carnivora")
      card.getAttrs().eq(1).find('[data-testid="case-card-attr-value"]')
        .eq(0).should("have.text", "7 values")
      card.getSummaryButton().click()
      card.getAttrs().eq(1).find('[data-testid="case-card-attr-value"]')
        .eq(0).should("have.text", "Cheetah")
    })
    it("allows the user to add, edit, and hide attributes with undo/redo", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getAttributes().should("have.length", 9)
      card.getAttributeNames().should("have.length", 9)
      card.getAttributeValues().should("have.length", 9)

      cy.log("Add new attribute with undo/redo.")
      card.getNextButton().click()
      card.getAddAttributeButton().click()
      cy.wait(500)
      card.getAttributeNameInput().should("exist").type(" Memory{enter}")
      card.getAttributeNames().eq(9).should("contain.text", "Memory")
      card.getAttributes().should("have.length", 10)
      card.getAttributeNames().should("have.length", 10)
      card.getAttributeValues().should("have.length", 10)
      card.getAttributeValues().eq(9).click()
      card.getAttributeValueEditors().should("exist").type("excellent{enter}")
      card.getAttributeValues().eq(9).should("contain.text", "excellent")

      // Undo/redo check after adding a new attribute
      toolbar.getUndoTool().click()
      toolbar.getUndoTool().click()
      toolbar.getUndoTool().click()
      card.getAttributes().should("have.length", 9)
      card.getAttributeNames().should("have.length", 9)
      toolbar.getRedoTool().click()
      toolbar.getRedoTool().click()
      toolbar.getRedoTool().click()
      card.getAttributes().should("have.length", 10)
      card.getAttributeNames().should("have.length", 10)
      card.getAttributeNames().eq(9).should("contain.text", "Memory")

      cy.log("Hide an attribute.")
      card.getAttributeNames().eq(9).click()
      cy.get('[data-testid="attribute-menu-list"]').should("be.visible")
      cy.get('[data-testid="attribute-menu-list"]').find("button").eq(9).trigger("click")
      card.getAttributes().should("have.length", 9)
      card.getAttributeNames().should("have.length", 9)
      card.getAttributeValues().should("have.length", 9)

      // Undo/redo check after hiding an attribute
      toolbar.getUndoTool().click()
      card.getAttributes().should("have.length", 10)
      toolbar.getRedoTool().click()
      card.getAttributes().should("have.length", 9)

      cy.log("Edit an attribute name with undo/redo.")
      card.getAttributeNames().eq(0).should("contain.text", "Mammal")
      card.getAttributeNames().eq(0).click()
      cy.get('[data-testid="attribute-menu-list"]').find("button").first().trigger("click")
      cy.wait(500)
      cy.get('[data-testid="column-name-input"]').type("{selectall}{backspace}Name{enter}")
      cy.get('[data-testid="column-name-input"]').should("not.exist")
      card.getAttributeNames().eq(0).should("contain.text", "Name")

      // Undo/redo check after editing an attribute name
      toolbar.getUndoTool().click()
      card.getAttributeNames().eq(0).should("contain.text", "Mammal")
      toolbar.getRedoTool().click()
      card.getAttributeNames().eq(0).should("contain.text", "Name")

      cy.log("Edit an attribute value.")
      card.getAttributeValues().eq(0).should("contain.text", "African Elephant")
      card.getAttributeValues().eq(0).click()
      card.getAttributeValueEditors().eq(0).type("Wooly Mammoth{enter}")
      card.getAttributeValues().eq(0).should("contain.text", "Wooly Mammoth")
      card.getAttributeValues().eq(0).click()
      card.getAttributeValueEditors().eq(0).type("{esc}")
      card.getAttributeValues().eq(0).should("contain.text", "Wooly Mammoth")

      // Undo/redo check after editing an attribute value
      toolbar.getUndoTool().click()
      card.getAttributeValues().eq(0).should("contain.text", "African Elephant")
      toolbar.getRedoTool().click()
      card.getAttributeValues().eq(0).should("contain.text", "Wooly Mammoth")
    })
    it("allows the user to add a new case with undo/redo", () => {
      const rootCollectionTitle = "Diets"
      table.moveAttributeToParent("Order", "newCollection")
      cy.wait(500)
      table.moveAttributeToParent("Diet", "newCollection")
      cy.wait(500)
      table.toggleCaseView()
      cy.wait(500)
      card.getCaseCardView().should("have.length", 3)
      card.getNextButton().eq(0).click()
      cy.log("Add new case to 'middle' collection.")
      card.getCaseCardView().eq(1).find('[data-testid="case-card-view-index"]')
                                                 .eq(0).should("have.text", "4 cases")
      card.getCaseCardView().eq(1).find('[data-testid="add-case-button"]')
                                                 .eq(0).click()
      card.getCaseCardView().eq(1).find('[data-testid="case-card-view-index"]')
                                                 .eq(0).should("have.text", "5 of 5")
      card.getCaseCardView().eq(1).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("exist").click()
      card.getCaseCardView().eq(1)
        .find('[data-testid="case-card-attr-value"] [data-testid="case-card-attr-value-text-editor"]')
                                                 .eq(0).should("exist").type("New Order{enter}")
      card.getCaseCardView().eq(1).find('[data-testid="case-card-attr-value"]')
                                                  .eq(0).should("contain.text", "New Order")
      cy.log("Check new case has parent and child collections' attributes and values match previously-selected case.")
      card.getCaseCardView().eq(0).find('[data-testid="case-card-view-title"]')
                                                 .eq(0).should("have.text", rootCollectionTitle)
      card.getCaseCardView().eq(2).find('[data-testid="case-card-attr-value"]')
                                                 .eq(0).should("have.text", "")

      // Check for undo/redo after editing a case attribute value
      toolbar.getUndoTool().click()
      card.getCaseCardView().eq(1).find('[data-testid="case-card-attr-value"]')
                                                  .eq(0).should("not.contain.text", "New Order")
      // Check for undo/redo after adding a new case
      toolbar.getUndoTool().click()
      card.getCaseCardView().eq(1).find('[data-testid="case-card-view-index"]')
                                                  .eq(0).should("have.text", "14 cases")

/* Note that selection is not guaranteed to be restored on undo/redo.

      toolbar.getRedoTool().click()
      toolbar.getRedoTool().click()
      cy.get('[data-testid="case-card-view"]').eq(1).find('[data-testid="case-card-view-index"]')
                                                  .eq(0).should("have.text", "5 of 5")

      // Check for undo/redo after editing a case attribute value
      toolbar.getUndoTool().click()
      cy.get('[data-testid="case-card-view"]').eq(1).find('[data-testid="case-card-attr-value"]')
                                                  .eq(0).should("not.contain.text", "New Order")
      toolbar.getRedoTool().click()
      cy.get('[data-testid="case-card-view"]').eq(1).find('[data-testid="case-card-attr-value"]')
                                                  .eq(0).should("contain.text", "New Order")
*/
    })
    it("adds a new case with the correct parent values depending on what is selected", () => {
      table.moveAttributeToParent("Order", "newCollection")
      cy.wait(500)
      table.moveAttributeToParent("Diet", "newCollection")
      cy.wait(500)
      table.toggleCaseView()
      cy.wait(500)
      card.getCaseCardView().should("have.length", 3)

      // when no cases are selected, should always add a case to the root level
      card.getCaseCardView().eq(0).find('[data-testid="case-card-view-index"]')
                                                 .eq(0).should("have.text", "3 cases")
      card.getCaseCardView().eq(2).find('[data-testid="add-case-button"]')
                                                 .eq(0).click()
      card.getCaseCardView().eq(0).find('[data-testid="case-card-view-index"]')
                                                 .eq(0).should("have.text", "4 of 4")

      // toolbar.getUndoTool().click()
      // cy.get('[data-testid="case-card-view-next-button"]').eq(0).click()
      // cy.get('[data-testid="case-card-view"]').eq(1).find('[data-testid="case-card-view-index"]')
      //                                            .eq(0).should("have.text", "4 cases")
      // cy.get('[data-testid="case-card-view"]').eq(1).find('[data-testid="add-case-button"]')
      //                                            .eq(0).click()
      // cy.get('[data-testid="case-card-view"]').eq(1).find('[data-testid="case-card-view-index"]')
      //                                            .eq(0).should("have.text", "5 of 5")
      // cy.get('[data-testid="case-card-view"]').eq(0).find('[data-testid="case-card-attr-value-text-editor"]')
      //                                            .eq(0).should("have.text", "plants")
      // cy.get('[data-testid="case-card-view"]').eq(1).find('[data-testid="case-card-attr-value-text-editor"]')
      //                                            .eq(0).should("have.text", "")
    })
    it("allows a user to drag an attribute to a new collection", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getCaseCardView().should("have.length", 1)
      cy.dragAttributeToTarget("card", "Diet", "newTopCardCollection")
      cy.wait(2000)
      card.getCaseCardView().should("have.length", 2)
      card.getViewTitle().first().should("have.text", "Diets")
    })
  })
})

context("case card inspector panel", () => {
  beforeEach(() => {
    // cy.scrollTo() doesn't work as expected with `scroll-behavior: smooth`
    const queryParams = "?sample=mammals&scrollBehavior=auto&suppressUnsavedWarning"
    const url = `${Cypress.config("index")}${queryParams}`
    cy.visit(url)
    cy.wait(2000)
  })

  describe("case card inspector panel", () => {
    it("displays inspector panel when in focus", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getInspectorPanel().should("exist")
      // click outside the card tile to remove focus
      cy.get('[data-testid="codap-app"]').click()
      card.getInspectorPanel().should("not.exist")
      cy.get('[data-testid="codap-case-card"]').click()
      card.getInspectorPanel().should("exist")
    })
    it("allows user to select and delete all cases from inspector panel", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getNextButton().click()
      card.getIndexText().should("have.text", "1 of 27")
      card.getAttributeValues().first().should("have.text", "African Elephant")
      card.getDeleteCasesButton().click()
      cy.wait(500)
      card.getTrashMenu().should("be.visible")
      card.getSelectAllCasesButton().click()
      card.getIndexText().should("have.text", "27 cases")
      card.getAttributeNames().first().should("contain.text", "Mammal")
      card.getAttributeValues().first().should("have.text", "27 values")
      card.getDeleteCasesButton().click()
      cy.wait(500)
      // resorting to {force: true} because this is failing in CI, though it passes locally
      card.getDeleteAllCasesButton().click({force: true})
      card.getIndexText().should("have.text", "0 cases")
      card.getAttributeNames().first().should("contain.text", "Mammal")
      card.getAttributeValues().first().should("have.text", "")
    })
    it("allows user to delete selected and unselected cases from inspector panel", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getNextButton().click()
      card.getIndexText().should("have.text", "1 of 27")
      card.getAttributeValues().first().should("have.text", "African Elephant")
      card.getDeleteCasesButton().click()
      cy.wait(500)
      cy.get('[data-testid="trash-menu-list"]').should("be.visible")
      card.getDeleteSelectedCasesButton().click()
      card.getIndexText().should("have.text", "26 cases")
      card.getAttributeValues().first().should("have.text", "26 values")
      card.getNextButton().click()
      card.getIndexText().should("have.text", "1 of 26")
      card.getAttributeValues().first().should("have.text", "Asian Elephant")
      card.getDeleteCasesButton().click()
      cy.wait(500)
      card.getDeleteUnselectedCasesButton().click()
      card.getIndexText().should("have.text", "1 of 1")
      card.getAttributeValues().first().should("have.text", "Asian Elephant")
    })
    it("allows user to set aside and restore cases from inspector panel", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getHideShowButton().click()
      card.getHideShowMenu().should("be.visible").should("be.visible")
      card.getSetAsideSelectedCasesButton().should("be.disabled")
      card.getNextButton().click()
      card.getIndexText().should("have.text", "1 of 27")
      card.getAttributeValues().first().should("have.text", "African Elephant")
      card.getHideShowButton().click()
      cy.wait(500)
      card.getRestoreSetAsideCasesButton().should("be.disabled").and("have.text", "Restore 0 Set Aside Cases")
      // resorting to {force: true} because this is failing in CI, though it passes locally
      card.getSetAsideSelectedCasesButton().click({force: true})
      card.getIndexText().should("have.text", "26 cases")
      card.getAttributeValues().first().should("have.text", "26 values")
      card.getHideShowButton().click()
      cy.wait(500)
      card.getRestoreSetAsideCasesButton().should("not.be.disabled").and("have.text", "Restore 1 Set Aside Cases")
      // resorting to {force: true} because this is failing in CI, though it passes locally
      card.getRestoreSetAsideCasesButton().click({force: true})
      card.getIndexText().should("have.text", "1 of 27")
      card.getAttributeValues().first().should("have.text", "African Elephant")
      card.getHideShowButton().click()
      cy.wait(500)
      card.getRestoreSetAsideCasesButton().should("be.disabled").and("have.text", "Restore 0 Set Aside Cases")
      // resorting to {force: true} because this is failing in CI, though it passes locally
      card.getSetAsideUnselectedCasesButton().click({force: true})
      card.getIndexText().should("have.text", "1 of 1")
      card.getAttributeValues().first().should("have.text", "African Elephant")
    })
    it("allows user to show hidden attributes from inspector panel", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getAttributes().should("have.length", 9)
      card.getHideShowButton().click()
      cy.wait(500)
      card.getShowAllHiddenAttributesButton().should("be.disabled")
      card.getAttributeNames().eq(8).click()
      cy.get('[data-testid="attribute-menu-list"]').should("be.visible")
      cy.get('[data-testid="attribute-menu-list"]').find("button").contains("Hide Attribute").click()
      card.getAttributes().should("have.length", 8)
      card.getHideShowButton().click()
      cy.get('[data-testid="hide-show-menu-list"]').should("be.visible")
      cy.get('[data-testid="hide-show-menu-show-all-hidden-attributes"]').should("not.be.disabled").click()
      card.getAttributes().should("have.length", 9)
    })
    it("allows user to add an attribute from inspector panel", () => {
      table.toggleCaseView()
      cy.wait(500)
      card.getAttributes().should("have.length", 9)
      card.getRulerButton().click()
      card.getRulerMenu().should("be.visible")
      card.getRulerAddAttributeButton().click()
      cy.wait(500)
      card.getAttributeNameInput().should("exist").type("Friendliness{enter}")
      card.getAttributes().should("have.length", 10)

      cy.log("add a formula to the new attribute")
      card.getAttributeNames().eq(9).click()
      cy.wait(500)
      cy.get('[data-testid="attribute-menu-list"]').should("be.visible")
      cy.get("[data-testid=attribute-menu-list] button").contains("Edit Formula...").click()
      cy.get("[data-testid=formula-editor-input] .cm-content").should("be.visible").and("have.focus")
      cy.get("[data-testid=formula-editor-input] .cm-content")
        .realType("if(LifeSpan>20, \"Friendly\", \"Unfriendly\")")
      cy.get("[data-testid=Apply-button]").click()
      cy.get('[data-testid="attr-formula-input"]').should("not.exist")
      cy.get('[data-testid="case-card-attr-value"]').eq(9).should("have.text", "Friendly, Unfriendly")
      cy.get('[data-testid="case-card-attr-value"] .formula-attr-value')
          .should("have.css", "background-color", "rgba(255, 255, 0, 0.2)")
    })
  })
  describe("case card filter formula bar", () => {
    it("displays the filter formula bar when a filter is applied", () => {
      const filterFormula = "LifeSpan > 20"
      table.toggleCaseView()
      cy.wait(500)
      card.getCaseCardView().should("have.length", 1)
      cy.get('[data-testid="filter-formula-bar"]').should("not.exist")
      card.getIndexText().should("contain", "27")
      card.getHideShowButton().click()
      card.getHideShowMenu().should("be.visible").should("be.visible")
      card.getAddFilterFormulaButton().click()
      fh.addFilterFormula(filterFormula)
      cy.get(".codap-modal-content [data-testid=Apply-button]").should("be.visible").click()
      cy.get('[data-testid="filter-formula-bar"]').should("exist")
      cy.get('[data-testid="filter-formula-bar"]').should("contain", filterFormula)
      card.getIndexText().should("contain", "11")
      cy.get('[data-testid="filter-formula-bar"]').click()

      fh.clearFormulaInput()
      cy.get(".codap-modal-content [data-testid=Apply-button]").should("be.visible").click()
      cy.get('[data-testid="filter-formula-bar"]').should("not.exist")
      card.getIndexText().should("contain", "27")
    })
  })
})
