export const kMovablePointClass = "movable-point"
export const kMovablePointType = "Movable Point"
export const kMovablePointPrefix = "ADRN"
export const kMovablePointLabel = "Movable Point"
export const kMovablePointHint = ""
