export const kMovableLineClass = "movable-line"
export const kMovableLineType = "Movable Line"
export const kMovableLinePrefix = "ADRN"
export const kMovableLineLabel = "Movable Line"
export const kMovableLineHint = ""
