#!/bin/bash
PROGNAME=`basename $0`
DIRNAME=`dirname $0`

function usage() {
  echo usage: $PROGNAME db user document-name >&2
  exit 1
}

[ $# != 3 ] && usage

DB="$1"
USER="$2"
DOC="$3"

mongoexport -d "$DB" -c documents  \
      -q "{\"_username\": \"$USER\", \"name\": \"$DOC\"}" 
