SC.stringsFor("ja", {
    "DG.fileMenu.menuItem.newDocument": "新規",
    "DG.fileMenu.menuItem.openDocument": "開く",
    "DG.fileMenu.menuItem.closeDocument": "閉じる",
    "DG.fileMenu.menuItem.importFile": "取り込む",
    "DG.fileMenu.menuItem.revertTo": "元に戻す",
    "DG.fileMenu.menuItem.revertToOpened": "最近開いた画面に戻す",
    "DG.fileMenu.menuItem.revertToShared": "共有状態に戻す",
    "DG.fileMenu.menuItem.saveDocument": "保存する",
    "DG.fileMenu.menuItem.copyDocument": "コピーする",
    "DG.fileMenu.menuItem.share": "共有する",
    "DG.fileMenu.menuItem.shareGetLink": "共有可能なリンクを取得",
    "DG.fileMenu.menuItem.shareUpdate": "共有状態を更新する",
    "DG.fileMenu.menuItem.renameDocument": "名前を変える",
    "DG.main.userEntryView.title": "どちらかを選択して下さい",
    "DG.main.userEntryView.openDocument": "過去に作成したファイル、ブラウザの例を開く",
    "DG.main.userEntryView.newDocument": "新しいファイルを作成する",
    "DG.mainPage.mainPane.undoButton.title": "戻す",
    "DG.mainPage.mainPane.undoButton.toolTip": "最後の操作を戻す",
    "DG.mainPage.mainPane.redoButton.title": "復元する",
    "DG.mainPage.mainPane.redoButton.toolTip": "最後に復元した操作をやり直す",
    "DG.mainPage.mainPane.versionString": "バージョン%@(%@)",
    "DG.mainPage.mainPane.messageView.value": "残念なことに、CODAPはあなたのブラウザでは対応しておりません。\nCODAPは Firefox 46+, Chrome 50+, Windows Edge 14+, そして Safari 10+でサポートされています。CODAPは複数のブラウザ上で同時に起動させることは推奨されておりません。",
    "DG.mainPage.titleBar.saved": "ファイルは保存されました",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "バージョン%@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "バージョン%@ (%@.srri10)",
    "DG.AppController.resetData.title": "データを修正する",
    "DG.AppController.resetData.toolTip": "現在のファイルからすべてのデータを削除する",
    "DG.AppController.resetData.warnMessage": "このファイル内にあるすべてのデータを削除しますか？",
    "DG.AppController.resetData.warnDescription": "この操作は修正ができません。",
    "DG.AppController.resetData.okButtonTitle": "はい、データを削除します",
    "DG.AppController.resetData.cancelButtonTitle": "いいえ、データを維持します。",
    "DG.AppController.closeDocument.warnMessage": "保存せずに現在のファイルを閉じますか。",
    "DG.AppController.closeDocument.warnDescription": "この操作は修正ができません。",
    "DG.AppController.closeDocument.okButtonTitle": "閉じる",
    "DG.AppController.closeDocument.cancelButtonTitle": "キャンセル",
    "DG.AppController.beforeUnload.confirmationMessage": "このファイルの変更は保存されておりません",
    "DG.AppController.optionMenuItems.reportProblem": "フィードバックを送る",
    "DG.AppController.optionMenuItems.viewWebPage": "webの表示",
    "DG.AppController.optionMenuItems.configureGuide": "ガイドを設計する",
    "DG.AppController.optionMenuItems.about": "CODAPについて",
    "DG.AppController.optionMenuItems.releaseNotes": "調子はどうですか",
    "DG.AppController.optionMenuItems.help": "マニュアル",
    "DG.AppController.optionMenuItems.toWebSite": "CODAPプロジェクト",
    "DG.AppController.exportDocument.prompt": "ファイル名",
    "DG.AppController.exportCaseData.prompt": "以下のデータを送る：",
    "DG.AppController.exportDocument.exportTitle": "送る",
    "DG.AppController.exportDocument.exportTooltip": "データをファイルに変換する",
    "DG.AppController.exportDocument.cancelTitle": "キャンセル",
    "DG.AppController.exportDocument.cancelTooltip": "送信をキャンセルする",
    "DG.AppController.feedbackDialog.dialogTitle": "フィードバックを送る",
    "DG.AppController.feedbackDialog.subHeaderText": "あなたのフィードバックは私たちにとって重要です",
    "DG.AppController.feedbackDialog.messageText": "製品を改良するために、引き続きお力を貸していただきたいです。質問、バグレポート、機能のリクエスト等全て歓迎しています。よろしくお願いします！",
    "DG.AppController.feedbackDialog.subjectHint": "あなたのフィードバックは何ですか",
    "DG.AppController.feedbackDialog.feedbackHint": "詳細",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "提出する",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "キャンセル",
    "DG.AppController.showWebSiteTitle": "CODAPについて",
    "DG.AppController.showHelpTitle": "CODAPマニュアル",
    "DG.AppController.showAboutTitle": "CODAPについて",
    "DG.AppController.showReleaseNotesTitle": "CODAPリリースノート",
    "DG.AppController.dropFile.error": "エラー: %@1",
    "DG.AppController.dropFile.unknownFileType": "取り込まれたファイルの形式が対応しておりません。",
    "DG.AppController.validateDocument.missingRequiredProperty": "お探しのファイルが見つかりません：%@1",
    "DG.AppController.validateDocument.unexpectedProperty": "重要なデータが予期せず変更されました： %@1",
    "DG.AppController.validateDocument.unresolvedID": "文書構造に問題があります： %@1",
    "DG.AppController.validateDocument.parseError": "ファイル内の文字を正しく認識できません： %@1",
    "DG.AppController.validateDocument.invalidDocument": "不正なファイルです： %@1",
    "DG.AppController.openDocument.error.general": "ファイルを開くことができません",
    "DG.AppController.openDocument.error.invalid_format": "CODAPはこの種類のファイルを読み込めません",
    "DG.AppController.createDataSet.initialAttribute": "属性名",
    "DG.AppController.createDataSet.name": "新しいデータセット",
    "DG.AppController.createDataSet.collectionName": "事例",
    "DG.AppController.caseTableMenu.newDataSet": "表を新しくつくる",
    "DG.SingleTextDialog.okButton.title": "はい",
    "DG.SingleTextDialog.cancelButton.title": "キャンセル",
    "DG.SingleTextDialog.cancelButton.toolTip": "変更を加えずに操作をやめますか",
    "DG.DocumentController.calculatorTitle": "電卓",
    "DG.DocumentController.caseTableTitle": "表",
    "DG.DocumentController.graphTitle": "グラフ",
    "DG.DocumentController.sliderTitle": "スライダー",
    "DG.DocumentController.textTitle": "テキスト",
    "DG.DocumentController.mapTitle": "地図",
    "DG.DocumentController.enterURLPrompt": "webページのURLを入力してください",
    "DG.DocumentController.enterViewWebPageOKTip": "URLのWebページを表示します",
    "DG.Document.defaultDocumentName": "名前のないファイル",
    "DG.Document.documentName.toolTip": "クリックして名前を変更する",
    "DG.SliderView.thumbView.toolTip": "ドラッグしてスライダーの値を変更します",
    "DG.SliderView.startButton.toolTip": "アニメーションの開始/停止",
    "DG.ToolButtonData.tableButton.title": "表",
    "DG.ToolButtonData.tableButton.toolTip": "表の作成(ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "グラフ",
    "DG.ToolButtonData.graphButton.toolTip": "グラフの作成",
    "DG.ToolButtonData.sliderButton.title": "スライダー",
    "DG.ToolButtonData.sliderButton.toolTip": "スライダーの作成(ctrl+alt+s)",
    "DG.ToolButtonData.calcButton.title": "電卓",
    "DG.ToolButtonData.calcButton.toolTip": "電卓の表示/消去(ctrl+alt+c)",
    "DG.ToolButtonData.textButton.title": "テキスト",
    "DG.ToolButtonData.textButton.toolTip": "テキストボックスを作成する(ctrl+alt+shift+t)",
    "DG.ToolButtonData.mapButton.title": "地図",
    "DG.ToolButtonData.mapButton.toolTip": "地図の作成",
    "DG.ToolButtonData.optionMenu.title": "オプション",
    "DG.ToolButtonData.optionMenu.toolTip": "Webサイトの表示、ガイドの設計",
    "DG.ToolButtonData.tileListMenu.title": "タイトル",
    "DG.ToolButtonData.tileListMenu.toolTip": "ファイル内のタイトルをリスト化",
    "DG.ToolButtonData.guideMenu.title": "ガイド",
    "DG.ToolButtonData.guideMenu.toolTip": "ガイドを表示、選択する",
    "DG.ToolButtonData.guideMenu.showGuide": "ガイドの表示",
    "DG.ToolButtonData.help.title": "ヘルプ",
    "DG.ToolButtonData.help.toolTip": "マニュアル、ヘルプセンター、CODAPプロジェクトについて",
    "DG.Slider.multiples": "増え方を制限する：",
    "DG.Slider.maxPerSecond": ":再生する/1秒",
    "DG.Slider.direction": "アニメーション方向",
    "DG.Slider.backAndForth": "前後する",
    "DG.Slider.lowToHigh": "増える",
    "DG.Slider.highToLow": "減る",
    "DG.Slider.mode": "アニメーションを繰り返す",
    "DG.Slider.nonStop": "繰り返す",
    "DG.Slider.onceOnly": "一度だけ",
    "DG.Undo.exceptionOccurred": "戻る操作の途中でエラーが発生しました",
    "DG.Redo.exceptionOccurred": "復元中にエラーが発生しました",
    "DG.Undo.componentMove": "パーツの移動を戻す",
    "DG.Redo.componentMove": "パーツの移動を復元する",
    "DG.Undo.componentResize": "パーツの大きさの変更を戻す",
    "DG.Redo.componentResize": "パーツの大きさを復元する\n",
    "DG.Undo.axisDilate": "軸の操作を戻す",
    "DG.Redo.axisDilate": "軸を復元する",
    "DG.Undo.axisRescaleFromData": "軸の修正を戻す",
    "DG.Redo.axisRescaleFromData": "再び軸を修正する",
    "DG.Undo.axisDrag": "軸のドラックを戻す",
    "DG.Redo.axisDrag": "軸のドラックを復元する",
    "DG.Undo.axisAttributeChange": "軸上の属性の変更を戻す",
    "DG.Redo.axisAttributeChange": "軸上の属性を復元する",
    "DG.Undo.axisAttributeAdded": "追加した軸上の属性を戻す",
    "DG.Redo.axisAttributeAdded": "追加した軸上の属性を復元する",
    "DG.Undo.toggleComponent.add.calcView": "電卓の表示を戻す",
    "DG.Redo.toggleComponent.add.calcView": "電卓の表示を復元する",
    "DG.Undo.toggleComponent.delete.calcView": "消去した電卓を戻す",
    "DG.Redo.toggleComponent.delete.calcView": "消去した電卓を復元する",
    "DG.Undo.caseTable.open": "表の作成を戻す",
    "DG.Redo.caseTable.open": "作成した表を復元する",
    "DG.Undo.caseTable.editAttribute": "表中の属性の編集を戻す",
    "DG.Redo.caseTable.editAttribute": "表中の属性を復元する",
    "DG.Undo.caseTable.createAttribute": "表中の属性の作成を戻す",
    "DG.Redo.caseTable.createAttribute": "表中の属性を復元する",
    "DG.Undo.caseTable.editAttributeFormula": "式の編集を戻す",
    "DG.Redo.caseTable.editAttributeFormula": "式の編集を復元する",
    "DG.Undo.caseTable.editCellValue": "編集した表の値を戻す",
    "DG.Redo.caseTable.editCellValue": "表の値を復元する",
    "DG.Undo.caseTable.sortCases": "事例のソートを戻す",
    "DG.Redo.caseTable.sortCases": "事例のソートを復元する",
    "DG.Undo.caseTable.deleteAttribute": "表中の属性の削除を戻す",
    "DG.Redo.caseTable.deleteAttribute": "表中の属性の削除を復元する",
    "DG.Undo.caseTable.createCollection": "データの作成を戻す",
    "DG.Redo.caseTable.createCollection": "データの作成を復元する",
    "DG.Undo.caseTable.collectionNameChange": "名前の変更を戻す",
    "DG.Redo.caseTable.collectionNameChange": "名前の変更を復元する",
    "DG.Undo.caseTable.createNewCase": "作成した新しい事例を戻す",
    "DG.Redo.caseTable.createNewCase": "作成した事例を復元する",
    "DG.Undo.caseTable.insertCases": "挿入した事例を戻す",
    "DG.Redo.caseTable.insertCases": "挿入した事例を復元する",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "全ての拡張/収納を元に戻す",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "全ての拡張/収納を復元する",
    "DG.Undo.caseTable.expandCollapseOneCase": "グループの拡張/収納を元に戻す",
    "DG.Redo.caseTable.expandCollapseOneCase": "グループの拡張/収納を復元する",
    "DG.Undo.caseTable.resizeColumns": "自動変更した列の幅を戻す",
    "DG.Redo.caseTable.resizeColumns": "自動変更した列の幅を復元する",
    "DG.Undo.document.share": "ファイルの共有を戻す",
    "DG.Redo.document.share": "ファイルの共有を復元する",
    "DG.Undo.document.unshare": "停止したファイルの共有を戻す",
    "DG.Redo.document.unshare": "停止したファイルの共有を復元する",
    "DG.Undo.game.add": "ファイルに追加するゲームを戻す",
    "DG.Redo.game.add": "ファイルに追加するゲームを復元する",
    "DG.Undo.graph.showCount": "カウントを戻す",
    "DG.Redo.graph.showCount": "カウントを復元する",
    "DG.Undo.graph.hideCount": "非表示にしたカウントを戻す",
    "DG.Redo.graph.hideCount": "再びカウントを非表示にする",
    "DG.Undo.graph.showPercent": "提示した割合を戻す",
    "DG.Redo.graph.showPercent": "提示した割合を復元する",
    "DG.Undo.graph.hidePercent": "非表示にした割合を戻す",
    "DG.Redo.graph.hidePercent": "再び割合を非表示にする",
    "DG.Undo.graph.showMovableLine": "可動線の表示を戻す",
    "DG.Redo.graph.showMovableLine": "可動線の表示を復元する",
    "DG.Undo.graph.hideMovableLine": "非表示にした可動線を戻す",
    "DG.Redo.graph.hideMovableLine": "再び可動線を非表示にする",
    "DG.Undo.graph.lockIntercept": "固定した切片を戻す",
    "DG.Redo.graph.lockIntercept": "固定した切片を復元する",
    "DG.Undo.graph.unlockIntercept": "切片の解除を戻す",
    "DG.Redo.graph.unlockIntercept": "切片の解除を復元する",
    "DG.Undo.graph.showPlotFunction": "関数の挿入を戻す",
    "DG.Redo.graph.showPlotFunction": "関数の挿入を復元する",
    "DG.Undo.graph.hidePlotFunction": "非表示にした関数を戻す",
    "DG.Redo.graph.hidePlotFunction": "再び関数を非表示にする",
    "DG.Undo.graph.changePlotFunction": "関数の変更を戻す",
    "DG.Redo.graph.changePlotFunction": "関数の変更を復元する",
    "DG.Undo.graph.showPlotValue": "値を挿入する標示を戻す",
    "DG.Redo.graph.showPlotValue": "値を挿入する標示を復元する",
    "DG.Undo.graph.hidePlotValue": "非表示にした値の挿入を戻す",
    "DG.Redo.graph.hidePlotValue": "再び値の挿入を非表示にする",
    "DG.Undo.graph.changePlotValue": "値の挿入の変更を戻す",
    "DG.Redo.graph.changePlotValue": "値の挿入の変更を復元する",
    "DG.Undo.graph.showConnectingLine": "接続線の表示を戻す",
    "DG.Redo.graph.showConnectingLine": "接続線の表示を復元する",
    "DG.Undo.graph.hideConnectingLine": "非表示にした接続線を戻す",
    "DG.Redo.graph.hideConnectingLine": "再び接続線を非表示にする",
    "DG.Undo.graph.showLSRL": "最小二乗線の表示を戻す",
    "DG.Redo.graph.showLSRL": "最小二乗線の表示を復元する",
    "DG.Undo.graph.hideLSRL": "非表示にした最小二乗線を戻す",
    "DG.Redo.graph.hideLSRL": "再び最小二乗線を非表示にする",
    "DG.Undo.graph.showSquares": "正方形の表示を消去する",
    "DG.Redo.graph.showSquares": "正方形の表示を復元する",
    "DG.Undo.graph.hideSquares": "非表示にした正方形を戻す",
    "DG.Redo.graph.hideSquares": "再び正方形を非表示にする",
    "DG.Undo.graph.showPlottedMean": "平均値の表示を戻す",
    "DG.Redo.graph.showPlottedMean": "平均値の表示を復元する",
    "DG.Undo.graph.hidePlottedMean": "非表示にした平均値を戻す",
    "DG.Redo.graph.hidePlottedMean": "再び平均値を非表示にする",
    "DG.Undo.graph.showPlottedMedian": "中央値の表示を戻す",
    "DG.Redo.graph.showPlottedMedian": "中央値の表示を復元する",
    "DG.Undo.graph.hidePlottedMedian": "中央値の非表示を戻す",
    "DG.Redo.graph.hidePlottedMedian": "再び中央値を非表示にする",
    "DG.Undo.graph.showPlottedStDev": "標準偏差の表示を戻す",
    "DG.Redo.graph.showPlottedStDev": "標準偏差の表示を復元する",
    "DG.Undo.graph.hidePlottedStDev": "標準偏差のひを非表示に戻す",
    "DG.Redo.graph.hidePlottedStDev": "再び標準偏差を非表示にする",
    "DG.Undo.graph.showPlottedIQR": "四分位範囲の表示を戻す",
    "DG.Redo.graph.hidePlottedIQR": "再び四分位範囲を非表示にする",
    "DG.Undo.graph.hidePlottedIQR": "四分位範囲の非表示を戻す",
    "DG.Redo.graph.showPlottedIQR": "四分位範囲の表示を復元する",
    "DG.Undo.graph.addMovableValue": "可動点の追加を戻す",
    "DG.Redo.graph.addMovableValue": "可動点の追加を復元する",
    "DG.Undo.graph.removeMovableValue": "可動点の消去を戻す",
    "DG.Redo.graph.removeMovableValue": "再び可動点を消去する",
    "DG.Undo.graph.moveMovableValue": "可動点の移動を戻す",
    "DG.Redo.graph.moveMovableValue": "可動点の移動を復元する",
    "DG.Undo.graph.changePointColor": "データの色の変更を戻す",
    "DG.Redo.graph.changePointColor": "データの色の変更を復元する",
    "DG.Undo.graph.changeStrokeColor": "縁の色の変更を戻す",
    "DG.Redo.graph.changeStrokeColor": "縁の色の変更を復元する",
    "DG.Undo.graph.changePointSize": "点の大きさの変更を戻す",
    "DG.Redo.graph.changePointSize": "点の大きさの変更を復元する",
    "DG.Undo.graph.changeAttributeColor": "属性の色の変更を戻す",
    "DG.Redo.graph.changeAttributeColor": "属性の色の変更を復元する",
    "DG.Undo.graph.changeBackgroundColor": "グラフ背景の色の変更を戻す",
    "DG.Redo.graph.changeBackgroundColor": "グラフ背景の色の変更を復元する",
    "DG.Undo.graph.toggleTransparent": "プロットの透明度の切り替えを戻す",
    "DG.Redo.graph.toggleTransparent": "プロットの透明度の切り替えを復元する",
    "DG.Undo.guide.show": "ガイドの表示を戻す",
    "DG.Redo.guide.show": "ガイドの表示を復元する",
    "DG.Undo.guide.navigate": "ガイドページの変更を戻す",
    "DG.Redo.guide.navigate": "ガイドページの変更を復元する",
    "DG.Undo.hideSelectedCases": "選択し、非表示にしているデータを戻す",
    "DG.Redo.hideSelectedCases": "選択し、非表示にしているデータを復元する",
    "DG.Undo.hideUnselectedCases": "選択せず、非表示にしているデータを戻す",
    "DG.Redo.hideUnselectedCases": "選択せず、非表示にしているデータを復元する",
    "DG.Undo.enableNumberToggle": "表の上位カテゴリーで分類する標示を戻す",
    "DG.Redo.enableNumberToggle": "表の上位カテゴリーで分類する標示を復元する",
    "DG.Undo.disableNumberToggle": "表の上位カテゴリーで分類する標示の非表示を戻す",
    "DG.Redo.disableNumberToggle": "再び表の上位カテゴリーで分類する標示を非表示にする",
    "DG.Undo.interactiveUndoableAction": "プラグインでの操作を戻す",
    "DG.Redo.interactiveUndoableAction": "プラグインでの操作を復元する",
    "DG.Undo.showAllCases": "全てのデータの表示を戻す",
    "DG.Redo.showAllCases": "全てのデータの表示を復元する",
    "DG.Undo.map.create": "マップの追加を戻す",
    "DG.Redo.map.create": "マップの追加を復元する",
    "DG.Undo.map.fitBounds": "マップの大きさの修正を戻す",
    "DG.Redo.map.fitBounds": "マップの大きさの修正を復元する",
    "DG.Undo.map.pan": "マップの移動を戻す",
    "DG.Redo.map.pan": "マップの移動を復元する",
    "DG.Undo.map.zoom": "マップの拡大を戻す",
    "DG.Redo.map.zoom": "マップの拡大を復元する",
    "DG.Undo.map.showGrid": "マップ上の目印を戻す",
    "DG.Redo.map.showGrid": "マップ上の目印を復元する",
    "DG.Undo.map.hideGrid": "マップ上にある目印の非表示を戻す",
    "DG.Redo.map.hideGrid": "再びマップ上にある目印を非表示にする",
    "DG.Undo.map.changeGridSize": "マップ上にある目印のサイズ変更を戻す",
    "DG.Redo.map.changeGridSize": "マップ上にある目印のサイズ変更を復元する",
    "DG.Undo.map.showPoints": "マップ上にある点の表示を戻す",
    "DG.Redo.map.showPoints": "マップ上にある点の表示を復元する",
    "DG.Undo.map.hidePoints": "マップ上にある点の非表示を戻す",
    "DG.Redo.map.hidePoints": "再びマップ上にある点を非表示にする",
    "DG.Undo.map.showLines": "マップ上にある線の表示を戻す",
    "DG.Redo.map.showLines": "マップ上にある線の表示を復元する",
    "DG.Undo.map.hideLines": "マップ上にある線の非表示を戻す",
    "DG.Redo.map.hideLines": "再びマップ上にある線を非表示にする",
    "DG.Undo.map.changeBaseMap": "マップ背景の変更を戻す",
    "DG.Redo.map.changeBaseMap": "マップ背景の変更を復元する",
    "DG.Undo.textComponent.create": "テキストの追加を戻す",
    "DG.Redo.textComponent.create": "テキストの追加を復元する",
    "DG.Undo.textComponent.edit": "テキストの編集を戻す",
    "DG.Redo.textComponent.edit": "テキストの編集を復元する",
    "DG.Undo.sliderComponent.create": "スライダーの追加を戻す",
    "DG.Redo.sliderComponent.create": "スライダーの追加を復元する",
    "DG.Undo.slider.change": "スライダーの値の変更を戻す",
    "DG.Redo.slider.change": "スライダーの値の変更を復元する",
    "DG.Undo.slider.changeMultiples": "スライダーの増え方の変更を戻す",
    "DG.Redo.slider.changeMultiples": "スライダーの増え方の変更を復元する",
    "DG.Undo.slider.changeSpeed": "スライダーの再生速度の変更を戻す",
    "DG.Redo.slider.changeSpeed": "スライダーの再生速度の変更を復元する",
    "DG.Undo.slider.changeDirection": "スライダー方向の変更を戻す",
    "DG.Redo.slider.changeDirection": "スライダー方向の変更を復元する",
    "DG.Undo.slider.changeRepetition": "スライダーの繰り返しの変更を戻す",
    "DG.Redo.slider.changeRepetition": "スライダーの繰り返しの変更を復元する",
    "DG.Undo.graphComponent.create": "グラフの追加を戻す",
    "DG.Redo.graphComponent.create": "グラフの追加を復元する",
    "DG.Undo.dataContext.create": "データの作成を戻す",
    "DG.Redo.dataContext.create": "データの作成を復元する",
    "DG.Undo.data.deleteCases": "データの削除を戻す",
    "DG.Redo.data.deleteCases": "データの削除を復元する",
    "DG.Undo.component.close": "閉じたパーツを戻す",
    "DG.Redo.component.close": "閉じたパーツを復元する",
    "DG.Undo.component.minimize": "パーツの最小化を戻す",
    "DG.Redo.component.minimize": "再びパーツを最小化する",
    "DG.Undo.dataContext.moveAttribute": "表の属性の移動を戻す",
    "DG.Redo.dataContext.moveAttribute": "表の属性の移動を復元する",
    "DG.DataContext.singleCaseName": "データ",
    "DG.DataContext.pluralCaseName": "データ",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "作成したファイル",
    "DG.DataContext.collapsedRowString": "%@2の%@1",
    "DG.DataContext.noData": "データがない",
    "DG.DataContext.baseName": "データセット%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "属性\"%@\" の式は編集不可能です",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "式を指定するために新しい属性を作成してください",
    "DG.Formula.FuncCategoryArithmetic": "数学",
    "DG.Formula.FuncCategoryConversion": "その他の関数",
    "DG.Formula.FuncCategoryDateTime": "日付/時刻",
    "DG.Formula.FuncCategoryLookup": "検索",
    "DG.Formula.FuncCategoryOther": "その他の関数",
    "DG.Formula.FuncCategoryRandom": "その他の関数",
    "DG.Formula.FuncCategoryStatistical": "統計",
    "DG.Formula.FuncCategoryString": "文字列操作",
    "DG.Formula.FuncCategoryTrigonometric": "三角関数",
    "DG.Formula.DateLongMonthJanuary": "1月",
    "DG.Formula.DateLongMonthFebruary": "2月",
    "DG.Formula.DateLongMonthMarch": "3月",
    "DG.Formula.DateLongMonthApril": "4月",
    "DG.Formula.DateLongMonthMay": "5月",
    "DG.Formula.DateLongMonthJune": "6月",
    "DG.Formula.DateLongMonthJuly": "7月",
    "DG.Formula.DateLongMonthAugust": "8月",
    "DG.Formula.DateLongMonthSeptember": "9月",
    "DG.Formula.DateLongMonthOctober": "10月",
    "DG.Formula.DateLongMonthNovember": "11月",
    "DG.Formula.DateLongMonthDecember": "12月",
    "DG.Formula.DateShortMonthJanuary": "1月",
    "DG.Formula.DateShortMonthFebruary": "2月",
    "DG.Formula.DateShortMonthMarch": "3月",
    "DG.Formula.DateShortMonthApril": "4月",
    "DG.Formula.DateShortMonthMay": "5月",
    "DG.Formula.DateShortMonthJune": "6月",
    "DG.Formula.DateShortMonthJuly": "7月",
    "DG.Formula.DateShortMonthAugust": "8月",
    "DG.Formula.DateShortMonthSeptember": "9月",
    "DG.Formula.DateShortMonthOctober": "10月",
    "DG.Formula.DateShortMonthNovember": "11月",
    "DG.Formula.DateShortMonthDecember": "12月",
    "DG.Formula.DateLongDaySunday": "日曜日",
    "DG.Formula.DateLongDayMonday": "月曜日",
    "DG.Formula.DateLongDayTuesday": "火曜日",
    "DG.Formula.DateLongDayWednesday": "水曜日",
    "DG.Formula.DateLongDayThursday": "木曜日",
    "DG.Formula.DateLongDayFriday": "金曜日",
    "DG.Formula.DateLongDaySaturday": "土曜日",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec) \\d{1,2}( |,) *\\d{4}|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "結合エラー：'%@'",
    "DG.Formula.SyntaxErrorEnd": "表現が未完成です",
    "DG.Formula.SyntaxErrorInvalidOperator": "不適切な操作 '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "不適切な種類'%@'",
    "DG.Formula.TypeError.description": "不適切な種類'%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@'は認識できません",
    "DG.Formula.VarReferenceError.description": "変数'%@'は認識できません",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "表の下位属性 '%@'からの引用が不適切です",
    "DG.Formula.HierReferenceError.description": "'%@' は統合において唯一引用できる表の下位属性です",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()'は認識できません",
    "DG.Formula.FuncReferenceError.description": "関数'%@()'は認識できません",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()'は1引数を必要とします",
    "DG.Formula.FuncArgsErrorSingle.description": " '%@()' 関数は１引数を必要とします",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' は%@ 引数を必要とします",
    "DG.Formula.FuncArgsErrorPlural.description": "'%@()'関数 は%@ 引数を必要とします",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()'は %@-%@ 引数を必要とします",
    "DG.Formula.FuncArgsErrorRange.description": "'%@()'関数は %@-%@ 引数を必要とします",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "リクエスト中です…",
    "DG.Formula.PendingRequest.description": "リクエスト中です…",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "リクエストは失敗しました (%@)",
    "DG.Formula.FailedRequest.description": "リクエストは失敗しました (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "境界を作成中です…",
    "DG.Formula.PendingBoundaries.description": "境界を作成中です…",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "境界の作成に失敗しました (%@)",
    "DG.Formula.FailedBoundaries.description": "境界の作成に失敗しました(%@)",
    "DG.Formula.LookupDataSetError.message": "'%@'：認識されないデータです",
    "DG.Formula.LookupDataSetError.description": "データ'%@' は認識されていません",
    "DG.Formula.LookupAttrError.message": "'%@' はデータ '%@'の中にありません",
    "DG.Formula.LookupAttrError.description": "属性 '%@' はデータ'%@'の中にありません",
    "DG.TableController.headerMenuItems.editAttribute": "属性の情報を編集する…",
    "DG.TableController.headerMenuItems.editFormula": "式を編集する…",
    "DG.TableController.headerMenuItems.randomizeAttribute": "再びランダムにします",
    "DG.TableController.headerMenuItems.sortAscending": "昇順に並び替える",
    "DG.TableController.headerMenuItems.sortDescending": "降順に並び替える",
    "DG.TableController.headerMenuItems.deleteAttribute": "属性を削除する",
    "DG.TableController.newAttrDlg.defaultAttrName": "新規属性",
    "DG.TableController.newAttrDlg.attrNameHint": "新しい属性に名前をつける",
    "DG.TableController.newAttrDlg.formulaHint": "属性の値を計算する式を挿入",
    "DG.TableController.newAttrDlg.applyTooltip": "名前と式（任意）を使って新しい属性を定義しましょう",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "その新しい属性に名前をつけてください",
    "DG.TableController.newAttrDialog.AttributesCategory": "属性",
    "DG.TableController.newAttrDialog.SpecialCategory": "特別な",
    "DG.TableController.newAttrDialog.GlobalsCategory": "世界基準の数値",
    "DG.TableController.newAttrDialog.ConstantsCategory": "不変",
    "DG.TableController.newAttrDialog.FunctionsCategory": "関数",
    "DG.TableController.renameAttributeInvalidMsg": "属性の名前が空白でない可能性があります",
    "DG.TableController.renameAttributeInvalidDesc": "適切な属性の名前をつけてください",
    "DG.TableController.renameAttributeDuplicateMsg": "既に存在している名前の属性",
    "DG.TableController.renameAttributeDuplicateDesc": "ユニークな属性の名前をつけてください",
    "DG.TableController.deleteAttribute.confirmMessage": "属性 '%@'を削除しますか？",
    "DG.TableController.deleteAttribute.confirmDescription": "この操作は元に戻せません",
    "DG.TableController.deleteAttribute.okButtonTitle": "属性を削除する",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "キャンセル",
    "DG.TableController.deleteDataSet.confirmMessage": "データ：'%@'を完全に削除しますか？",
    "DG.TableController.deleteDataSet.confirmDescription": "この操作は元に戻せません",
    "DG.TableController.deleteDataSet.okButtonTitle": "データを削除する",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "キャンセル",
    "DG.TableController.attrEditor.unitHint": "単位の入力(任意)",
    "DG.TableController.attrEditor.descriptionHint": "属性を記述する",
    "DG.TableController.setScoreDlg.applyTooltip": " '%@'属性に式を挿入する",
    "DG.TableController.setScoreDlg.formulaHint": "この属性の値を計算する式を入力してください",
    "DG.TableController.newAttributeTooltip": "この表に新しい属性を追加する",
    "DG.TableController.attributeEditor.title": "属性に関する情報",
    "DG.CaseTableDropTarget.dropMessage": "属性をドロップすると表がグループ分けされます",
    "DG.CaseTable.defaultAttrName": "新規属性",
    "DG.CaseTable.indexColumnName": "索引",
    "DG.CaseTable.indexColumnTooltip": "表内部の行番号（データ索引）",
    "DG.CaseTable.indexMenu.insertCase": "データを挿入する",
    "DG.CaseTable.indexMenu.insertCases": "複数のデータを挿入する",
    "DG.CaseTable.indexMenu.deleteCase": "データを削除する",
    "DG.CaseTable.indexMenu.deleteCases": "データを削除する",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "質的データ",
    "DG.CaseTable.attribute.type.categorical": "質的",
    "DG.CaseTable.attribute.type.numeric": "量的",
    "DG.CaseTable.attribute.type.date": "日付",
    "DG.CaseTable.attribute.type.qualitative": "定性的",
    "DG.CaseTable.attribute.type.boundary": "境界",
    "DG.CaseTable.attributeEditor.name": "名前",
    "DG.CaseTable.attributeEditor.description": "説明",
    "DG.CaseTable.attributeEditor.type": "種類",
    "DG.CaseTable.attributeEditor.unit": "単位",
    "DG.CaseTable.attributeEditor.precision": "精度",
    "DG.CaseTable.attributeEditor.editable": "編集可能",
    "DG.CaseTable.insertCasesDialog.title": "複数のデータを挿入する",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "挿入するデータ数：",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "位置：",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "前",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "後",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "複数のデータを挿入する",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "特定数のデータを挿入する",
    "DG.CaseTableController.allTables": "全ての表",
    "DG.AttrFormView.attrNamePrompt": "属性名：",
    "DG.AttrFormView.formulaPrompt": "式：",
    "DG.AttrFormView.operandMenuTitle": "---値の挿入---",
    "DG.AttrFormView.functionMenuTitle": "---関数の挿入---",
    "DG.AttrFormView.applyBtnTitle": "適用",
    "DG.AttrFormView.cancelBtnTitle": "キャンセル",
    "DG.AttrFormView.cancelBtnTooltip": "変更せずにやり取りを終了する",
    "DG.GuideConfigView.titlePrompt": "ガイドタイトル",
    "DG.GuideConfigView.titleHint": "活動名",
    "DG.GuideConfigView.itemTitleHint": "セクション名",
    "DG.GuideConfigView.itemURLHint": "セクションのURL",
    "DG.GuideConfigView.okBtnTitle": "実行",
    "DG.GuideConfigView.okBtnToolTip": "ガイドメニューのアイテムを得る",
    "DG.GuideConfigView.cancelBtnTitle": "キャンセル",
    "DG.GuideConfigView.cancelBtnTooltip": "変更せずにやり取りを終了する",
    "DG.GuideConfigView.httpWarning": "URLはhttp:// か https://のいずれかから始めてください",
    "DG.DataDisplayModel.rescaleToData": "データの大きさを修正する",
    "DG.DataDisplayModel.ShowConnectingLine": "結んだ線を表示する",
    "DG.DataDisplayModel.HideConnectingLine": "結んだ線を非表示にする",
    "DG.AxisView.emptyGraphCue": "ここをクリックするか、属性をドラッグします",
    "DG.CellLinearAxisView.midPanelTooltip": "ドラッグすると軸が移動します",
    "DG.CellLinearAxisView.lowerPanelTooltip": "ドラッグすると横軸が変わります",
    "DG.CellLinearAxisView.upperPanelTooltip": "ドラッグすると縦軸が変わります",
    "DG.PlotModel.mixup": "プロットをかき混ぜる",
    "DG.PlotModel.showCount": "カウントする",
    "DG.PlotModel.hideCount": "カウントを非表示する",
    "DG.ScatterPlotModel.sumSquares": ",\n平方和 = %@",
    "DG.ScatterPlotModel.slopeOnly": "傾き= %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "/ 年",
    "DG.ScatterPlotModel.daysLabel": "/ 日",
    "DG.ScatterPlotModel.hoursLabel": "/ 時",
    "DG.ScatterPlotModel.minutesLabel": "/ 分",
    "DG.ScatterPlotModel.secondsLabel": "/ 秒",
    "DG.LegendView.attributeTooltip": "クリックして凡例属性を変える",
    "DG.NumberToggleView.showAll": "全てを表示するー",
    "DG.NumberToggleView.hideAll": "全てを非表示にするー",
    "DG.NumberToggleView.lastDash": "ー",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "最後",
    "DG.NumberToggleView.showAllTooltip": "クリックして全てのデータを表示する\nクリックして表上位のデータで切り替えられるラベルを表示する",
    "DG.NumberToggleView.hideAllTooltip": "クリックして全てのデータを非表示にする\nクリックして表上位のデータで切り替えられるラベルを表示する",
    "DG.NumberToggleView.enableLastModeTooltip": "クリックして最後に可視化したデータのみを表示する",
    "DG.NumberToggleView.disableLastModeTooltip": "最後におこなったデータの可視化を終了する",
    "DG.NumberToggleView.indexTooltip": "クリックして可視化を切り替える",
    "DG.PlottedAverageAdornment.meanValueTitle": "平均値=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "中央値=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 標準偏差, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@\n",
    "DG.PlottedAverageAdornment.boxPlotTitle": "最小値=%@\nQ1=%@\n中央値=%@\nQ3=%@\n最大値=%@\n四分位範囲(IQR)=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X： %@",
    "DG.DataDisplayMenu.attribute_y": "Y： %@",
    "DG.DataDisplayMenu.attribute_y2": "Y： %@",
    "DG.DataDisplayMenu.attribute_legend": "凡例： %@",
    "DG.DataDisplayMenu.remove": "属性の削除",
    "DG.DataDisplayMenu.removeAttribute_x": "X軸の削除： %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Y軸の削除： %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Y軸の削除： %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "凡例の削除： %@",
    "DG.DataDisplayMenu.treatAsCategorical": "質的に変換する",
    "DG.DataDisplayMenu.treatAsNumeric": "量的に変換する",
    "DG.DataDisplayMenu.hide": "非表示と表示",
    "DG.DataDisplayMenu.hideSelectedPlural": "選択したデータを非表示にする",
    "DG.DataDisplayMenu.hideUnselectedPlural": "選択されていないデータを非表示にする",
    "DG.DataDisplayMenu.hideSelectedSing": "選択したデータを非表示にする",
    "DG.DataDisplayMenu.hideUnselectedSing": "選択されていないデータを非表示にする",
    "DG.DataDisplayMenu.enableNumberToggle": "表の上位データでグラフを切り替えるラベルを表示する",
    "DG.DataDisplayMenu.disableNumberToggle": "表の上位データでグラフを切り替えるラベルを非表示にする",
    "DG.DataDisplayMenu.showAll": "全てのデータを表示する",
    "DG.DataDisplayMenu.snapshot": "撮影する",
    "DG.GraphView.replaceAttribute": " %@を %@で置き換える",
    "DG.GraphView.addAttribute": "属性%@を追加する",
    "DG.GraphView.addToEmptyPlace": "%@で軸を作成する",
    "DG.GraphView.addToEmptyX": "%@でx軸を作成する",
    "DG.GraphView.dropInPlot": "%@の値でポイントに色を付ける",
    "DG.GraphView.zoomTip": "ダブルクリックするとズームインします\nシフト＋ダブルクリックするとズームアウトします",
    "DG.GraphView.rescale": "データの大きさを修正します",
    "DG.AxisView.labelTooltip": "クリックして%@を変更する",
    "DG.AxisView.vertical": "縦軸",
    "DG.AxisView.horizontal": "横軸",
    "DG.DataTip.connectingLine": "%@：%@\nと %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@：00",
    "DG.PlottedFormula.defaultNamePrompt": "式",
    "DG.PlottedValue.namePrompt": "値の挿入",
    "DG.PlottedValue.formulaPrompt": "値=",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "関数の挿入",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "表現を入力する （例えば、 x*x/30 - 50）",
    "DG.MapView.showGrid": "目印を表示する",
    "DG.MapView.hideGrid": "目印を非表示にする",
    "DG.MapView.showPoints": "点を表示する",
    "DG.MapView.hidePoints": "点を非表示にする",
    "DG.MapView.marqueeHint": "四角形選択ツールードラッグしてマップ上の点を選択します",
    "DG.MapView.gridControlHint": "目印の大きさを変更する",
    "DG.Inspector.values": "統計量",
    "DG.Inspector.styles": "フォーマット",
    "DG.Inspector.pointSize": "点の大きさ：",
    "DG.Inspector.transparency": "透明度：",
    "DG.Inspector.color": "色：",
    "DG.Inspector.legendColor": "凡例色：",
    "DG.Inspector.backgroundColor": "背景色：",
    "DG.Inspector.stroke": "縁：",
    "DG.Inspector.rescale.toolTip": "全てのデータを表示できるように画面を修正する",
    "DG.Inspector.mixUp.toolTip": "全ての点をかきまぜる",
    "DG.Inspector.hideShow.toolTip": "全てのデータを表示するか、選択された/選択されていないデータ非表示にする",
    "DG.Inspector.delete.toolTip": "選択された、もしくは選択されていないデータを削除する",
    "DG.Inspector.sliderValues.toolTip": "スライダーのアニメーション方向、速度等を編集する",
    "DG.Inspector.webViewEditURL.toolTip": "表示されたウェブページのURLを編集する",
    "DG.Inspector.selection.selectAll": "全てのデータを選択する",
    "DG.Inspector.selection.deleteSelectedCases": "選択したデータを削除する",
    "DG.Inspector.selection.deleteUnselectedCases": "選択されていないデータを削除する",
    "DG.Inspector.deleteAll": "全てのデータを削除する",
    "DG.Inspector.deleteDataSet": "データを完全に削除する",
    "DG.Inspector.displayValues.toolTip": "グラフに関数を挿入します",
    "DG.Inspector.displayStyles.toolTip": "画面表示を変更する",
    "DG.Inspector.makeImage.toolTip": "PNGファイルとして保存する",
    "DG.Inspector.displayShow": "表示する…",
    "DG.Inspector.colorPicker.more": "細かく",
    "DG.Inspector.colorPicker.less": "戻す",
    "DG.Inspector.graphTransparency": "透明度",
    "DG.Inspector.graphCount": "カウント",
    "DG.Inspector.graphPercent": "百分率（％）",
    "DG.Inspector.graphRow": "行",
    "DG.Inspector.graphColumn": "列",
    "DG.Inspector.graphCell": "セル",
    "DG.Inspector.graphConnectingLine": "線を結ぶ",
    "DG.Inspector.graphMovableLine": "可動線",
    "DG.Inspector.graphInterceptLocked": "切片の固定",
    "DG.Inspector.graphPlottedFunction": "関数の挿入",
    "DG.Inspector.graphSquares": "残差の二乗",
    "DG.Inspector.graphLSRL": "最小二乗線",
    "DG.Inspector.graphMovableValue": "可動点",
    "DG.Inspector.graphAdd": "追加",
    "DG.Inspector.graphRemove": "削除",
    "DG.Inspector.graphPlottedMean": "平均値",
    "DG.Inspector.graphPlottedMedian": "中央値",
    "DG.Inspector.graphPlottedStDev": "標準偏差",
    "DG.Inspector.graphPlottedIQR": "四分位範囲",
    "DG.Inspector.graphPlottedBoxPlot": "箱ひげ図",
    "DG.Inspector.graphPlottedValue": "値の挿入",
    "DG.Inspector.attributes.toolTip": "新しい属性を作成する。データを送る。",
    "DG.Inspector.resize.toolTip": "列の幅を変更し、隠れた文字が見えるようにします",
    "DG.Inspector.newAttribute": "%@内の新しい属性",
    "DG.Inspector.randomizeAllAttributes": "全データを再びランダムにします",
    "DG.Inspector.exportCaseData": "データを送る…",
    "DG.Inspector.mapGrid": "目印",
    "DG.Inspector.mapPoints": "点",
    "DG.Inspector.mapLines": "線を結ぶ",
    "DG.GameController.continuityError": "申し訳ありませんが、表の属性を変更した後に、新しいデータを入力することはできません。",
    "DG.GameView.loading": "読み込み中です",
    "DG.GameView.loadError": "上記のURLの読み込みに失敗しました。\n他のブラウザ上でリンクを確認するかhttp://codap.concord.org/help.までエラーの報告をしてください。",
    "DG.Component.closeComponent.confirmCloseMessage": "本当によろしいですか。",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "はい、閉じます",
    "DG.Component.closeComponent.cancelButtonTitle": "キャンセル",
    "DG.GameController.confirmCloseDescription": "もしこれを閉じたら、データが破損する可能性があります",
    "DG.WebView.defaultTitle": "ウェブページ",
    "DG.mainPage.exceptionMessage": "プログラムに影響を与えうるエラーが発生しました。\nページを保存した後に再読み込みすることをお勧めします。(エラー: %@)",
    "DG.fileMenu.provider.examples.displayName": "練習ファイル",
    "DG.ToolButtonData.pluginMenu.title": "プラグイン",
    "DG.ToolButtonData.pluginMenu.toolTip": "プラグインを開く",
    "DG.Undo.graph.showMovablePoint": "可動点の表示を戻す",
    "DG.Redo.graph.showMovablePoint": "再び可動点を表示する",
    "DG.Undo.graph.hideMovablePoint": "可動点の非表示を戻す",
    "DG.Redo.graph.hideMovablePoint": "再び可動点を非表示にする",
    "DG.Undo.graph.moveMovablePoint": "可動点の移動を戻す",
    "DG.Redo.graph.moveMovablePoint": "可動点の移動を復元する",
    "DG.DataDisplayMenu.copyAsImage": "描画ツールを開く",
    "DG.DataDisplayMenu.exportImage": "画像を送る",
    "DG.DataDisplayMenu.imageOfTitle": " %@の画像",
    "DG.Inspector.graphMovablePoint": "可動点",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "データを表にする",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "新しいデータを作成する",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "このデータを完全に削除します",
    "DG.Undo.graph.showAsBarChart": "棒グラフをドットプロットに戻します",
    "DG.Redo.graph.showAsBarChart": "棒グラフを復元します",
    "DG.Undo.graph.showAsDotChart": "ドットプロットを棒グラフに戻します",
    "DG.Redo.graph.showAsDotChart": "ドットプロットを復元します",
    "DG.CountAxisView.countLabel": "カウント",
    "DG.CountAxisView.countLabelDescription": "棒グラフのデータ数",
    "DG.CountAxisView.percentLabel": "百分率（%）",
    "DG.CountAxisView.percentLabelDescription": "棒グラフのデータ百分率（％）",
    "DG.BarChartModel.cellTipPlural": "%@ %@ (%@%) の%@ は %@",
    "DG.BarChartModel.cellTipSingular": "%@ %@ (%@%)の@% は %@",
    "DG.Inspector.configuration": "形状",
    "DG.Inspector.displayConfiguration.toolTip": "画面表示を変更する",
    "DG.Inspector.displayScale": "大きさ…",
    "DG.Inspector.graphBarChart": "ドットを融合する",
    "DG.Locale.name.de": "ドイツ語",
    "DG.Locale.name.en": "英語",
    "DG.Locale.name.es": "スペイン語",
    "DG.Locale.name.he": "ヘブライ語",
    "DG.Locale.name.tr": "トルコ語",
    "DG.Locale.name.zh": "中国語",
    "DG.Undo.graph.swapCategories": "カテゴリーの並び換えを戻す",
    "DG.Redo.graph.swapCategories": "カテゴリーの並び替えを復元する",
    "DG.TableController.collectionTitleText": "%@1 (%@2 データ)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 データ, %@3 非表示にする)",
    "DG.Inspector.setaside.setAsideSelectedCases": "選択したデータを非表示にする",
    "DG.Inspector.setaside.setAsideUnselectedCases": "選択していないデータを非表示にする",
    "DG.Inspector.setaside.restoreSetAsideCases": "非表示にした%@データを再表示する",
    "DG.DocumentController.caseCardTitle": "データカード",
    "DG.DocumentController.toggleToCaseCard": "データをカード形式に切り替える",
    "DG.DocumentController.toggleToCaseTable": "データを表形式に切り替える",
    "DG.CaseCard.indexString": "%@ %@の１",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ %@から選ばれた%@",
    "DG.CaseCard.summaryValues": "%@ 値",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "次のデータを選び、表示します",
    "DG.CaseCard.navPrevCase": "前のデータを選び、表示します",
    "DG.CaseCard.navFirstCase": "最初のデータを選び、表示します",
    "DG.CaseCard.navLastCase": "最後のデータを選び、表示します",
    "DG.Undo.component.toggleTableToCard": "表からカードへの変更を戻します",
    "DG.Redo.component.toggleTableToCard": "再び表からカードへ変更します",
    "DG.Undo.component.toggleCardToTable": "カードから表への変更を戻します",
    "DG.Redo.component.toggleCardToTable": "再びカードから表へ変更します",
    "DG.Undo.graph.addBackgroundImage": "グラフ背景への画像の挿入を戻します",
    "DG.Redo.graph.addBackgroundImage": "再び背景へ画像を挿入します",
    "DG.Undo.graph.removeBackgroundImage": "背景画像の削除を戻します",
    "DG.Redo.graph.removeBackgroundImage": "背景画像を復元します",
    "DG.Undo.graph.lockBackgroundImage": "軸への背景画像の固定を戻します",
    "DG.Redo.graph.lockBackgroundImage": "再び軸へ背景画像を固定します",
    "DG.Undo.graph.unlockBackgroundImage": "軸からの背景画像の移動を戻します",
    "DG.Redo.graph.unlockBackgroundImage": "軸の背景画像の解除を戻す",
    "DG.Undo.enableMeasuresForSelection": "選択したデータに関する統計量の表示を戻す",
    "DG.Redo.enableMeasuresForSelection": "再び、選択したデータに関する統計量を表示する",
    "DG.Undo.disableMeasuresForSelection": "選択したデータに関する統計量の消去を戻す",
    "DG.Redo.disableMeasuresForSelection": "再び、選択したデータに関する統計量を非表示にする",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "選択したデータに関する統計量を表示する",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "選択したデータに関する統計量を非表示にする",
    "DG.DataDisplayMenu.addBackgroundImage": "背景画像を追加する",
    "DG.DataDisplayMenu.lockImageToAxes": "軸に背景画像を固定する",
    "DG.DataDisplayMenu.unlockImageFromAxes": "軸の背景画像を解除する",
    "DG.DataDisplayMenu.removeBackgroundImage": "背景画像を削除する",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "式を削除する（値は保たれる）",
    "DG.TableController.headerMenuItems.recoverFormula": "削除した式を復元する",
    "DG.Inspector.displayLayers.toolTip": "マップ内にあるレイヤーの概観を変更する",
    "DG.Inspector.layers": "レイヤー",
    "DG.Undo.graph.repositionEquation": "方程式の位置替えを戻す",
    "DG.Redo.graph.repositionEquation": "再び方程式の位置替えをする",
    "DG.TableController.attrEditor.precisionNumericHint": "小数点以下の桁数",
    "DG.TableController.attrEditor.precisionDateHint": "どのくらいのデータが表示されるのかを決定する",
    "DG.TableController.attrEditor.typeHint": "属性を特定の種類に設定する",
    "DG.TableController.attrEditor.nameHint": "属性の名前は表、データ、グラフ軸で見れます",
    "DG.TableController.attrEditor.editableHint": "もし属性が編集可能でなければ、その値や式は変更されません",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "年月日時分秒ミリ秒",
    "DG.AttributeFormat.DatePrecision.year": "YYYY",
    "DG.AttributeFormat.DatePrecision.month": "MMM　YYYY",
    "DG.AttributeFormat.DatePrecision.day": "MMM D, YYYY",
    "DG.AttributeFormat.DatePrecision.hour": "MMM D, YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "MMM D, YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "MMM D, YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@内の%@",
    "DG.CaseCard.attrHintDescription": "%@: %@",
    "DG.CaseCard.attrHintFormula": "%@\n%@",
    "DG.AppController.optionMenuItems.help-forum": "ヘルプセンター",
    "DG.AppController.showHelpForumTitle": "ヘルプセンター",
    "DG.Locale.name.el": "ギリシャ語",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ (%@%) の%@は %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ (%@%) の%@は %@",
    "DG.DataDisplayMenu.removeAttribute_top": "並列配置（%@）を削除する",
    "DG.DataDisplayMenu.removeAttribute_right": "%@を使ったY軸レイアウトを削除する",
    "DG.GraphView.layoutPlotsSideBySide": "%@を並列配置する",
    "DG.GraphView.layoutPlotsVertically": "%@をY軸に置く",
    "DG.Undo.graph.makeStrokeSameAsFill": "ドットと同じ色に縁取りしたことを戻す",
    "DG.Redo.graph.makeStrokeSameAsFill": "再びドットと同じ色に縁取りする",
    "DG.Undo.graph.makeStrokeIndependent": "ドットと独立して縁取りしたことを戻す",
    "DG.Redo.graph.makeStrokeIndependent": "再びドットと独立して縁取りする",
    "DG.Inspector.strokeSameAsFill": "ドットと同じ色で縁取りする",
    "DG.Formula.DateShortDaySunday": "日曜日",
    "DG.Formula.DateShortDayMonday": "月曜日",
    "DG.Formula.DateShortDayTuesday": "火曜日",
    "DG.Formula.DateShortDayWednesday": "水曜日",
    "DG.Formula.DateShortDayThursday": "木曜日",
    "DG.Formula.DateShortDayFriday": "金曜日",
    "DG.Formula.DateShortDaySaturday": "土曜日",
    "DG.AttributeFormat.DatePrecision.millisecond": "MMM D, YYYY HH:mm:ss.SSS",
    "DG.CellAxis.other": "その他",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 絶対平均偏差, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "絶対平均偏差",
    "DG.Undo.graph.showPlottedBoxPlot": "箱ひげ図の表示を戻す",
    "DG.Redo.graph.hidePlottedBoxPlot": "再び箱ひげ図を非表示にする",
    "DG.Undo.graph.hidePlottedBoxPlot": "箱ひげ図の非表示を戻す",
    "DG.Redo.graph.showPlottedBoxPlot": "再び箱ひげ図を表示する",
    "DG.Undo.graph.showOutliers": "外れ値の表示を戻す",
    "DG.Redo.graph.hideOutliers": "再び外れ値を非表示にする",
    "DG.Undo.graph.hideOutliers": "外れ値の非表示を戻す",
    "DG.Redo.graph.showOutliers": "再び外れ値を表示する",
    "DG.Inspector.graphBoxPlotShowOutliers": "外れ値を表示する",
    "DG.Locale.name.nb": "ノルウェー語",
    "DG.Locale.name.nn": "新ノルウェー語",
    "DG.CaseCard.newCaseToolTip": "空白のデータを挿入する",
    "DG.TableController.headerMenuItems.renameAttribute": "名前を変更",
    "DG.Undo.graph.fuseDotsToRectangles": "融合させたドットを戻す",
    "DG.Redo.graph.fuseDotsToRectangles": "融合させたドットを復元する",
    "DG.Undo.graph.dissolveRectanglesToDots": "ドットプロットへの変換を戻す",
    "DG.Redo.graph.dissolveRectanglesToDots": "ドットプロットへの変換を復元する",
    "DG.Undo.graph.changeBreakdownType": "尺度の変更を戻す",
    "DG.Redo.graph.changeBreakdownType": "尺度の変更を戻す",
    "DG.Undo.graph.showAsBinnedPlot": "階級の作成を戻す",
    "DG.Redo.graph.showAsBinnedPlot": "作成した階級を復元する",
    "DG.Undo.graph.showAsDotPlot": "ドットプロットへの変換を戻す",
    "DG.Redo.graph.showAsDotPlot": "ドットプロットへの変換を復元する",
    "DG.Undo.graph.dragBinBoundary": "ドラッグした階級の境界を戻す",
    "DG.Redo.graph.dragBinBoundary": "ドラッグした階級の境界を復元する",
    "DG.Undo.graph.changeBinWidth": "階級幅の変更を戻す",
    "DG.Redo.graph.changeBinWidth": "変更した階級の境界を復元する",
    "DG.Undo.graph.changeBinAlignment": "最小階級の境界の変更を戻す",
    "DG.Redo.graph.changeBinAlignment": "最小階級の境界の変更を復元する",
    "DG.BinnedPlotModel.dragBinTip": "ドラッグして階級幅を変更します",
    "DG.HistogramView.barTipPlural": "%@ / %@ %@ (%@%) は %@≦X< %@です",
    "DG.HistogramView.barTipSingular": "%@ / %@ %@ (%@%) は %@ ≦X<%@です",
    "DG.HistogramView.barTipNoLegendSingular": "%@ / %@ (%@%) は %@ ≦X<%@です",
    "DG.HistogramView.barTipNoLegendPlural": "%@ / %@ (%@%)は  %@ ≦X<%@です",
    "DG.Inspector.graphGroupIntoBins": "階級に分類する",
    "DG.Inspector.graphBinWidth": "階級幅",
    "DG.Inspector.graphAlignment": "最小階級の境界",
    "DG.CaseTable.dividerView.expandAllTooltip": "全てのグループを拡張する",
    "DG.CaseTable.dividerView.expandGroupTooltip": "グループを拡張する",
    "DG.CaseTable.dividerView.collapseAllTooltip": "全てのグループを収納する",
    "DG.CaseTable.dividerView.collapseGroupTooltip": "グループを収納する",
    "DG.BinnedPlotModel.binLabelTip": "この階級の値は%@≦X< %@です",
    "DG.Component.closeComponent.toolTip": "このパーツを閉じます",
    "DG.Component.minimizeComponent.toolTip": "このパーツを最小化、もしくは拡張します",
    "DG.Locale.name.ja": "日本語",
    "DG.CaseCard.attrHintDescriptionAndFormula": "%@1: %@2\n%@1 = %@3",
    "DG.Locale.name.zh-Hans": "Simplified Chinese",
    "DG.PlottedCount.withoutSelection": "%@",
    "DG.PlottedCount.withSelection": "%@ selected",
    "DG.PlottedPercent.withoutSelection": "%@%",
    "DG.PlottedPercent.withSelection": "%@% selected",
    "DG.PlottedCountPercent.withoutSelection": "%@ (%@%)",
    "DG.PlottedCountPercent.withSelection": "%@ of %@ (%@%) selected",
    "DG.Undo.caseTable.resizeColumn": "Undo fit width to content",
    "DG.Redo.caseTable.resizeColumn": "Redo fit width to content",
    "DG.TableController.headerMenuItems.resizeColumn": "Fit width to content",
    "DG.SelectedInfoView.infoPlural": "Showing measures for %@ selected cases",
    "DG.SelectedInfoView.infoSing": "Showing measures for %@ selected case",
    "DG.Inspector.copyCaseDataToClipboard": "クリップボードへコピー",
    "DG.Inspector.caseTable.exportCaseDialog.copyFrom": "Copy case data from:",
    "DG.Inspector.caseTable.exportCaseDialog.copy": "コピー",
    "DG.Inspector.caseTable.exportCaseDialog.copyTooltip": "クリップボードへコピー",
    "DG.Inspector.caseTable.exportCaseDialog.copiedData": "Copied %@ to the clipboard",
    "DG.Undo.caseTable.hideAttribute": "Undo hiding attribute",
    "DG.Redo.caseTable.hideAttribute": "Redo hiding attribute",
    "DG.Undo.caseTable.showAllHiddenAttributes": "Undo show all hidden attributes",
    "DG.Redo.caseTable.showAllHiddenAttributes": "Redo show all hidden attributes",
    "DG.TableController.headerMenuItems.hideAttribute": "属性を非表示にする",
    "DG.Inspector.attributes.showAllHiddenAttributesSing": "Show %@ Hidden Attribute",
    "DG.Inspector.attributes.showAllHiddenAttributesPlural": "非表示にした%@個の属性を表示する",
    "DG.Inspector.attributes.showAllHiddenAttributesDisabled": "非表示にした属性を表示する",
    "DG.Inspector.getCaseDataFromClipboard": "クリップボードから事例データを入力する...",
    "DG.CaseCard.addCaseButton": "add case",
    "DG.Undo.DataContext.join": "Undo join of %@ to %@",
    "DG.Redo.DataContext.join": "Redo join of %@ to %@",
    "DG.Collection.joinTip": "Join %@ in %@ to %@ in %@ by matching %@ with %@",
    "DG.Inspector.graphPlotPoints": "点",
    "DG.Inspector.graphBarForEachPoint": "Bar for Each Point",
    "DG.Undo.graph.changeBarChartFunction": "Undo change bar chart formula",
    "DG.Redo.graph.changeBarChartFunction": "Redo change bar chart formula",
    "DG.Undo.graph.showAsLinePlot": "Undo bar for each point",
    "DG.Redo.graph.showAsLinePlot": "Redo bar for each point",
    "DG.Undo.graph.showAsStandardBarChart": "Undo using count or percent for bar chart scale",
    "DG.Redo.graph.showAsStandardBarChart": "Redo using count or percent for bar chart scale",
    "DG.Undo.graph.showAsComputedBarChart": "Undo computing bar length with formula",
    "DG.Redo.graph.showAsComputedBarChart": "Redo computing bar length with formula",
    "DG.FormulaAxisView.labelDescription": "The expression that determines the length of the bars. Click to edit.",
    "DG.ComputedBarChartModel.cellTip": "For group %@ the value is %@",
    "DG.BarChartFunction.namePrompt": "棒グラフ",
    "DG.BarChartFunction.formulaPrompt": "bar length =",
    "DG.BarChartFunction.formulaHint": "Type a formula to compute bar length",
    "DG.BarChartFunction.emptyExpressionAxisPrompt": "Click here to provide a formula",
    "DG.Inspector.graphFormula": "Formula",
    "DG.Undo.displayOnlySelected": "Undo displaying only selected cases",
    "DG.Redo.displayOnlySelected": "Redo displaying only selected cases",
    "DG.Undo.webView.show": "Undo adding webView component",
    "DG.Redo.webView.show": "Redo adding webView component",
    "DG.Undo.imageComponent.show": "Undo adding image component",
    "DG.Redo.imageComponent.show": "Redo adding image component",
    "DG.DataDisplayMenu.displayOnlySelected": "選択されたデータのみ表示する",
    "DG.DataDisplayMenu.displayingOnlySelected": "選択されたデータのみ表示する",
    "DG.PlotBackgroundView.msg0": "This graph is set to display",
    "DG.PlotBackgroundView.msg1": "only selected cases.",
    "DG.PlotBackgroundView.msg2": "No cases are selected",
    "DG.PlotBackgroundView.msg3": "so nothing is being displayed.",
    "DG.PlotBackgroundView.msg4": "You can select cases in a",
    "DG.PlotBackgroundView.msg5": "case table or another graph.",
    "DG.ImageComponent.defaultTitle": "Image",
    "DG.TableController.datasetMetadata.title": "Dataset Information",
    "DG.CaseTable.datasetMetadata.url": "source",
    "DG.CaseTable.datasetMetadata.creationDate": "日付を入力する",
    "DG.TableController.datasetMetadata.descriptionHint": "Describe the dataset",
    "DG.Inspector.datasetInfo.toolTip": "Display information about dataset",
    "DG.CaseTable.indexMenu.moveEntryRow": "Move Data Entry Row Here",
    "DG.CaseCard.deselect": "Deselect all cases",
    "DG.CaseCard.noDeselect": "No cases are selected",
    "DG.CaseTable.indexProto.tooltip": "Drag to place data entry row within this table",
    "DG.AttributeFormat.DatePrecisionShort.year": "YYYY",
    "DG.AttributeFormat.DatePrecisionShort.month": "M/YY",
    "DG.AttributeFormat.DatePrecisionShort.day": "M/D/YY",
    "DG.AttributeFormat.DatePrecisionShort.hour": "M/D/YY HH:00",
    "DG.AttributeFormat.DatePrecisionShort.minute": "M/D/YY HH:mm",
    "DG.AttributeFormat.DatePrecisionShort.second": "M/D/YY HH:mm:ss",
    "DG.AttributeFormat.DatePrecisionShort.millisecond": "M/D/YY HH:mm:ss.SSS",
    "DG.Formula.FuncCategoryLogic": "Logic Functions",
    "DG.Undo.graph.showMeasureLabels": "Undo showing measure labels",
    "DG.Redo.graph.showMeasureLabels": "Redo showing measure labels",
    "DG.Undo.graph.hideMeasureLabels": "Undo hiding measure labels",
    "DG.Redo.graph.hideMeasureLabels": "Redo hiding measure labels",
    "DG.Inspector.showLabels": "統計量を表示する",
    "DG.Undo.caseTable.resizeOneColumn": "変更した列の幅を戻す",
    "DG.Redo.caseTable.resizeOneColumn": "変更した列の幅を復元する",
    "DG.CaseTable.attribute.type.checkbox": "チェックボックス",
    "DG.AppController.caseTableMenu.clipboardDataset": "-- new from clipboard --",
    "DG.AppController.caseTableMenu.clipboardDatasetToolTip": "クリップボードからデータをペースト",
    "DG.AppController.optionMenuItems.toPrivacyPage": "プライバシー",
    "DG.plugin.Importer.title": "Import CSV to CODAP",
    "DG.plugin.Importer.enter-url": "Enter url: ",
    "DG.plugin.Importer.or": "or",
    "DG.plugin.Importer.downsample-section": "Downsample Options...",
    "DG.plugin.Importer.downsample-random-p1": "Randomly select",
    "DG.plugin.Importer.downsample-random-p2": "rows",
    "DG.plugin.Importer.downsample-every-nth-p1": "Select every",
    "DG.plugin.Importer.downsample-every-nth-p2": "th row",
    "DG.plugin.Importer.downsample-import-all": "Import all rows",
    "DG.plugin.Importer.target-options-title": "Target Options...",
    "DG.plugin.Importer.target-options-replace": "Replace existing dataset with this one",
    "DG.plugin.Importer.target-options-append": "Append this dataset to the existing one",
    "DG.plugin.Importer.target-options-create-new": "Create a new data set",
    "DG.plugin.Importer.button-cancel": "Cancel",
    "DG.plugin.Importer.button-submit": "OK",
    "DG.plugin.Importer.button-dismiss": "Dismiss",
    "DG.plugin.Importer.load-error": "There was an error loading this resource: \"%@\" reason: \"%@\"",
    "DG.plugin.Importer.no-table-error": "Could not find tabular data in a format that can be imported into CODAP",
    "DG.plugin.Importer.duplicate-dataset-msg": "There already exists a dataset like this one. It is named \"%@\".",
    "DG.plugin.Importer.upload-time-msg": "It was uploaded %@",
    "DG.plugin.Importer.large-file-msg": "The imported file, \"%@\" has %@ rows. With more than %@ rows CODAP performance may be sluggish. You can work with a sample of the data at least at first, replacing it with the full dataset later.",
    "DG.plugin.Importer.error-codap-connection": "Error sending data to CODAP",
    "DG.plugin.Importer.error-upload": "Could not import this file -- %@",
    "DG.plugin.Importer.import-message": "Preparing to import %@ rows into \"%@\" from a table with %@ attributes: %@%@",
    "DG.Undo.component.componentTitleChange": "Undo changing the component title",
    "DG.Redo.component.componentTitleChange": "Redo changing the component title"
});