import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <link href="https://fonts.googleapis.com/css?family=Lato&display=optional" rel="stylesheet" />
        {/* The following is a link generated by the Adobo Fonts website https://fonts.adobe.com/fonts/museo-sans
            To generate the link, go to the website. You will have to sign up for an account.
            Find "Add to Web Project" in the upper right. Select all the relevant font sizes and styles.
            Create or add to a web project, and save. This will generate the link to use here. */}
        <link href="https://use.typekit.net/ckm7htd.css" rel="stylesheet" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
