import "./adornments/count/count-adornment-registration"
import "./adornments/univariate-measures/mean/mean-adornment-registration"
import "./adornments/univariate-measures/median/median-adornment-registration"
import "./adornments/movable-line/movable-line-adornment-registration"
import "./adornments/movable-point/movable-point-adornment-registration"
import "./adornments/movable-value/movable-value-adornment-registration"
import "./adornments/plotted-value/plotted-value-adornment-registration"
