import "./adornments/count/count-registration"
import "./adornments/univariate-measures/mean/mean-adornment-registration"
import "./adornments/univariate-measures/median/median-adornment-registration"
import "./adornments/movable-line/movable-line-registration"
import "./adornments/movable-point/movable-point-registration"
import "./adornments/movable-value/movable-value-registration"
import "./adornments/plotted-value/plotted-value-registration"
