SC.stringsFor("es", {
    "DG.fileMenu.menuItem.newDocument": "Nuevo",
    "DG.fileMenu.menuItem.openDocument": "Abrir...",
    "DG.fileMenu.menuItem.closeDocument": "Cerrar",
    "DG.fileMenu.menuItem.importFile": "Importar...",
    "DG.fileMenu.menuItem.revertTo": "Revertir...",
    "DG.fileMenu.menuItem.revertToOpened": "Versión abierta recientemente",
    "DG.fileMenu.menuItem.revertToShared": "Vista compartida",
    "DG.fileMenu.menuItem.saveDocument": "Guardar...",
    "DG.fileMenu.menuItem.copyDocument": "Crear una copia",
    "DG.fileMenu.menuItem.share": "Compartir...",
    "DG.fileMenu.menuItem.shareGetLink": "Obtener enlace para compartir",
    "DG.fileMenu.menuItem.shareUpdate": "Actualizar vista compartida",
    "DG.fileMenu.menuItem.renameDocument": "Renombrar",
    "DG.main.userEntryView.title": "¿Que quieres hacer?",
    "DG.main.userEntryView.openDocument": "Abrir documento o Examinar ejemplos",
    "DG.main.userEntryView.newDocument": "Crear nuevo documento",
    "DG.mainPage.mainPane.undoButton.title": "Deshacer",
    "DG.mainPage.mainPane.undoButton.toolTip": "Deshacer la última acción",
    "DG.mainPage.mainPane.redoButton.title": "Rehacer",
    "DG.mainPage.mainPane.redoButton.toolTip": "Rehacer la última acción",
    "DG.mainPage.mainPane.versionString": "Versión %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Desfortunadamente, CODAP no está soportado por su navegador. CODAP funciona en Firefox 46+, Chrome 50+, Windows Edge 14+, and Safari 10+. Por el momento CODAP no está soportado en otros navegadores.",
    "DG.mainPage.titleBar.saved": "¡Documento Guardado!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Versión %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Versión %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Borrar datos...",
    "DG.AppController.resetData.toolTip": "Eliminar todos los datos del documento actual",
    "DG.AppController.resetData.warnMessage": "¿Realmente desea eliminar todos los datos de este documento?",
    "DG.AppController.resetData.warnDescription": "Esta acción no puede deshacerse.",
    "DG.AppController.resetData.okButtonTitle": "Sí, eliminar los datos",
    "DG.AppController.resetData.cancelButtonTitle": "No, mantener los datos",
    "DG.AppController.closeDocument.warnMessage": "¿Cerrar el documento actual sin guardarlo?",
    "DG.AppController.closeDocument.warnDescription": "Esta acción no puede deshacerse.",
    "DG.AppController.closeDocument.okButtonTitle": "Cerrar",
    "DG.AppController.closeDocument.cancelButtonTitle": "Cancelar",
    "DG.AppController.beforeUnload.confirmationMessage": "Este documento contiene cambios no guardados.",
    "DG.AppController.optionMenuItems.reportProblem": "Enviar comentarios...",
    "DG.AppController.optionMenuItems.viewWebPage": "Mostrar página web...",
    "DG.AppController.optionMenuItems.configureGuide": "Configurar la guía...",
    "DG.AppController.optionMenuItems.about": "Acerca de CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "¿Qué hay de nuevo?",
    "DG.AppController.optionMenuItems.help": "Ayuda...",
    "DG.AppController.optionMenuItems.toWebSite": "Sitio web CODAP",
    "DG.AppController.exportDocument.prompt": "Archivo:",
    "DG.AppController.exportCaseData.prompt": "Exportar los datos de:",
    "DG.AppController.exportDocument.exportTitle": "Exportar",
    "DG.AppController.exportDocument.exportTooltip": "Exportar datos a un archivo",
    "DG.AppController.exportDocument.cancelTitle": "Cancelar",
    "DG.AppController.exportDocument.cancelTooltip": "Cancelar exportación",
    "DG.AppController.feedbackDialog.dialogTitle": "Dar su opinión",
    "DG.AppController.feedbackDialog.subHeaderText": "¡Tu opinión es importante para nosotros!",
    "DG.AppController.feedbackDialog.messageText": "Por favor, ayúdenos a continuar mejorando nuestro producto. Preguntas, errores y solicitud de nuevas funciones son bienvenidas. ¡Gracias!",
    "DG.AppController.feedbackDialog.subjectHint": "¿Cuál es tu opinión?",
    "DG.AppController.feedbackDialog.feedbackHint": "Detalles",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Enviar",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Cancelar",
    "DG.AppController.showWebSiteTitle": "Acerca de CODAP",
    "DG.AppController.showHelpTitle": "Ayuda",
    "DG.AppController.showAboutTitle": "Acerca de CODAP",
    "DG.AppController.showReleaseNotesTitle": "Notas de la versión de CODAP",
    "DG.AppController.dropFile.error": "Error: %@1",
    "DG.AppController.dropFile.unknownFileType": "No se puede importar el tipo de archivo",
    "DG.AppController.validateDocument.missingRequiredProperty": "No se encontró propiedad requerida: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Propiedad inesperada de nivel superior: %@1",
    "DG.AppController.validateDocument.unresolvedID": "ID no resuelto: %@1",
    "DG.AppController.validateDocument.parseError": "Error de análisis en el documento: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Documento JSON no válido: %@1",
    "DG.AppController.openDocument.error.general": "No se puede abrir el documento",
    "DG.AppController.openDocument.error.invalid_format": "CODAP no puede abrir este tipo de documento",
    "DG.AppController.createDataSet.initialAttribute": "Atributo",
    "DG.AppController.createDataSet.name": "Nuevo Conjunto de Datos",
    "DG.AppController.createDataSet.collectionName": "Casos",
    "DG.AppController.caseTableMenu.newDataSet": "-- nuevo --",
    "DG.SingleTextDialog.okButton.title": "OK",
    "DG.SingleTextDialog.cancelButton.title": "Cancelar",
    "DG.SingleTextDialog.cancelButton.toolTip": "Descartar el cuadro de diálogo sin realizar ningún cambio",
    "DG.DocumentController.calculatorTitle": "Calculadora",
    "DG.DocumentController.caseTableTitle": "Tabla de Casos",
    "DG.DocumentController.graphTitle": "Gráfico",
    "DG.DocumentController.sliderTitle": "Deslizador",
    "DG.DocumentController.textTitle": "Texto",
    "DG.DocumentController.mapTitle": "Mapa",
    "DG.DocumentController.enterURLPrompt": "Escriba la URL de una página web para mostrar",
    "DG.DocumentController.enterViewWebPageOKTip": "Muestra la página web dada por la URL",
    "DG.Document.defaultDocumentName": "Documento sin título",
    "DG.Document.documentName.toolTip": "Clic para renombrar el documento",
    "DG.SliderView.thumbView.toolTip": "Arrastrar para cambiar valor del deslizador",
    "DG.SliderView.startButton.toolTip": "Iniciar/detener animación",
    "DG.ToolButtonData.tableButton.title": "Tablas",
    "DG.ToolButtonData.tableButton.toolTip": "Abrir una tabla de casos para cada conjunto de datos(ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Gráfico",
    "DG.ToolButtonData.graphButton.toolTip": "Crear un gráfico (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Deslizador",
    "DG.ToolButtonData.sliderButton.toolTip": "Crear un deslizador (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "Calculadora",
    "DG.ToolButtonData.calcButton.toolTip": "Abrir/Cerrar calculadora (ctrl-alt-c)",
    "DG.ToolButtonData.textButton.title": "Texto",
    "DG.ToolButtonData.textButton.toolTip": "Crear un objeto de texto (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "Mapa",
    "DG.ToolButtonData.mapButton.toolTip": "Crear un mapa",
    "DG.ToolButtonData.optionMenu.title": "Opciones",
    "DG.ToolButtonData.optionMenu.toolTip": "Mostrar un sitio web, Configurar guía...",
    "DG.ToolButtonData.tileListMenu.title": "Elementos",
    "DG.ToolButtonData.tileListMenu.toolTip": "Mostrar la lista de elementos en el documento",
    "DG.ToolButtonData.guideMenu.title": "Guía",
    "DG.ToolButtonData.guideMenu.toolTip": "Mostrar la guía para esta actividad y navegar dentro",
    "DG.ToolButtonData.guideMenu.showGuide": "Mostrar Guía",
    "DG.ToolButtonData.help.title": "Ayuda",
    "DG.ToolButtonData.help.toolTip": "Ayuda para CODAP, aprender sobre CODAP",
    "DG.Slider.multiples": "Restringir a Múltiplos de:",
    "DG.Slider.maxPerSecond": "Máx. cuadros/seg de Animación:",
    "DG.Slider.direction": "Dirección de la Animación:",
    "DG.Slider.backAndForth": "Hacia atrás y adelante",
    "DG.Slider.lowToHigh": "De menor a mayor",
    "DG.Slider.highToLow": "De mayor a menor ",
    "DG.Slider.mode": "Repetir animación:",
    "DG.Slider.nonStop": "Continuo",
    "DG.Slider.onceOnly": "Sólo Una Vez",
    "DG.Undo.exceptionOccurred": "Se ha producido un error al intentar deshacer.",
    "DG.Redo.exceptionOccurred": "Se ha producido un error al intentar rehacer.",
    "DG.Undo.componentMove": "Deshacer mover componente",
    "DG.Redo.componentMove": "Rehacer mover componente",
    "DG.Undo.componentResize": "Deshacer cambiar tamaño componente",
    "DG.Redo.componentResize": "Rehacer cambiar tamaño componente",
    "DG.Undo.axisDilate": "Deshacer reescalar ejes",
    "DG.Redo.axisDilate": "Rehacer reescalar ejes",
    "DG.Undo.axisRescaleFromData": "Deshacer reescalar ejes",
    "DG.Redo.axisRescaleFromData": "Rehacer reescalar ejes",
    "DG.Undo.axisDrag": "Deshacer arrastrar ejes",
    "DG.Redo.axisDrag": "Rehacer arrastrar ejes",
    "DG.Undo.axisAttributeChange": "Deshacer cambiar atributo eje",
    "DG.Redo.axisAttributeChange": "Rehacer cambiar atributo eje",
    "DG.Undo.axisAttributeAdded": "Deshacer agregar atributo eje",
    "DG.Redo.axisAttributeAdded": "Rehacer agregar atributo eje",
    "DG.Undo.toggleComponent.add.calcView": "Deshacer abrir la calculadora",
    "DG.Redo.toggleComponent.add.calcView": "Rehacer abrir la calculadora",
    "DG.Undo.toggleComponent.delete.calcView": "Deshacer cerrar la calculadora",
    "DG.Redo.toggleComponent.delete.calcView": "Rehacer cerrar la calculadora",
    "DG.Undo.caseTable.open": "Deshacer abrir la tabla de casos",
    "DG.Redo.caseTable.open": "Rehacer abrir la tabla de casos",
    "DG.Undo.caseTable.editAttribute": "Deshacer edición atributo tabla de caso",
    "DG.Redo.caseTable.editAttribute": "Rehacer edición atributo tabla de caso",
    "DG.Undo.caseTable.createAttribute": "Deshacer creación atributo tabla de caso",
    "DG.Redo.caseTable.createAttribute": "Rehacer creación atributo de tabla de caso",
    "DG.Undo.caseTable.editAttributeFormula": "Deshacer editar fórmula atributo tabla de caso",
    "DG.Redo.caseTable.editAttributeFormula": "Rehacer editar fórmula atributo tabla de caso",
    "DG.Undo.caseTable.editCellValue": "Deshacer edición valor de celda de la tabla de caso",
    "DG.Redo.caseTable.editCellValue": "Rehacer edición valor de celda de la tabla de caso",
    "DG.Undo.caseTable.sortCases": "Deshacer ordenar casos",
    "DG.Redo.caseTable.sortCases": "Rehacer ordenar casos",
    "DG.Undo.caseTable.deleteAttribute": "Deshacer eliminar atributo de tabla de caso",
    "DG.Redo.caseTable.deleteAttribute": "Rehacer eliminar atributo de tabla de caso",
    "DG.Undo.caseTable.createCollection": "Deshacer crear nueva colección",
    "DG.Redo.caseTable.createCollection": "Rehacer crear nueva colección",
    "DG.Undo.caseTable.collectionNameChange": "Deshacer renombrar colección",
    "DG.Redo.caseTable.collectionNameChange": "Rehacer renombrar colección",
    "DG.Undo.caseTable.createNewCase": "Deshacer crear nuevo caso",
    "DG.Redo.caseTable.createNewCase": "Rehacer crear nuevo caso",
    "DG.Undo.caseTable.insertCases": "Deshacer insertar casos",
    "DG.Redo.caseTable.insertCases": "Rehacer insertar casos",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Deshacer expandir/colapsar todos",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Rehacer expandir/colapsar todos",
    "DG.Undo.caseTable.expandCollapseOneCase": "Deshacer expandir o colapsar un grupo",
    "DG.Redo.caseTable.expandCollapseOneCase": "Rehacer expandir o colapsar un grupo",
    "DG.Undo.caseTable.resizeColumns": "Deshacer cambio automático tamaño de columnas",
    "DG.Redo.caseTable.resizeColumns": "Rehacer cambio automático tamaño de columnas",
    "DG.Undo.document.share": "Deshacer compartir documento",
    "DG.Redo.document.share": "Rehacer compartir documento",
    "DG.Undo.document.unshare": "Deshacer dejar de compartir documento",
    "DG.Redo.document.unshare": "Rehacer dejar de compartir documento",
    "DG.Undo.game.add": "Deshacer agregar juego a documento",
    "DG.Redo.game.add": "Rehacer agregar juego a documento",
    "DG.Undo.graph.showCount": "Deshacer mostrar recuento",
    "DG.Redo.graph.showCount": "Rehacer mostrar recuento",
    "DG.Undo.graph.hideCount": "Deshacer ocultar recuento",
    "DG.Redo.graph.hideCount": "Rehacer ocultar recuento",
    "DG.Undo.graph.showPercent": "Deshacer mostrar porcentaje",
    "DG.Redo.graph.showPercent": "Rehacer mostrar porcentaje",
    "DG.Undo.graph.hidePercent": "Deshacer ocultar porcentaje",
    "DG.Redo.graph.hidePercent": "Rehacer ocultar porcentaje",
    "DG.Undo.graph.showMovableLine": "Deshacer mostrar línea de valor movible",
    "DG.Redo.graph.showMovableLine": "Rehacer mostrar línea de valor movible",
    "DG.Undo.graph.hideMovableLine": "Deshacer ocultar línea de valor movible",
    "DG.Redo.graph.hideMovableLine": "Rehacer ocultar línea de valor movible",
    "DG.Undo.graph.lockIntercept": "Deshacer bloqueo de línea de intercepción",
    "DG.Redo.graph.lockIntercept": "Rehacer bloqueo de línea de intercepción",
    "DG.Undo.graph.unlockIntercept": "Deshacer desbloquear intersección línea",
    "DG.Redo.graph.unlockIntercept": "Rehacer desbloquear intersección línea",
    "DG.Undo.graph.showPlotFunction": "Deshacer mostrar función graficada",
    "DG.Redo.graph.showPlotFunction": "Rehacer mostrar función graficada",
    "DG.Undo.graph.hidePlotFunction": "Deshacer ocultar función graficada",
    "DG.Redo.graph.hidePlotFunction": "Rehacer ocultar función graficada",
    "DG.Undo.graph.changePlotFunction": "Deshacer cambiar función graficada",
    "DG.Redo.graph.changePlotFunction": "Rehacer cambiar función graficada",
    "DG.Undo.graph.showPlotValue": "Deshacer mostrar valor graficado",
    "DG.Redo.graph.showPlotValue": "Rehacer mostrar valor graficado",
    "DG.Undo.graph.hidePlotValue": "Deshacer ocultar valor graficado",
    "DG.Redo.graph.hidePlotValue": "Rehacer ocultar valor graficado",
    "DG.Undo.graph.changePlotValue": "Deshacer cambiar valor graficado",
    "DG.Redo.graph.changePlotValue": "Rehacer cambiar valor graficado",
    "DG.Undo.graph.showConnectingLine": "Deshacer mostrar línea de conexión",
    "DG.Redo.graph.showConnectingLine": "Rehacer mostrar línea de conexión",
    "DG.Undo.graph.hideConnectingLine": "Deshacer ocultar línea de conexión",
    "DG.Redo.graph.hideConnectingLine": "Rehacer ocultar línea de conexión",
    "DG.Undo.graph.showLSRL": "Deshacer mostrar línea de cuadrados mínimos",
    "DG.Redo.graph.showLSRL": "Rehacer mostrar  línea de cuadrados mínimos",
    "DG.Undo.graph.hideLSRL": "Deshacer ocultar  línea de cuadrados mínimos",
    "DG.Redo.graph.hideLSRL": "Rehacer ocultar  línea de cuadrados mínimos",
    "DG.Undo.graph.showSquares": "Deshacer mostrar cuadrados",
    "DG.Redo.graph.showSquares": "Rehacer mostrar cuadrados",
    "DG.Undo.graph.hideSquares": "Deshacer ocultar cuadrados",
    "DG.Redo.graph.hideSquares": "Rehacer ocultar cuadrados",
    "DG.Undo.graph.showPlottedMean": "Deshacer mostrar promedio",
    "DG.Redo.graph.showPlottedMean": "Rehacer mostrar promedio",
    "DG.Undo.graph.hidePlottedMean": "Deshacer ocultar promedio",
    "DG.Redo.graph.hidePlottedMean": "Rehacer ocultar promedio",
    "DG.Undo.graph.showPlottedMedian": "Deshacer mostrar mediana",
    "DG.Redo.graph.showPlottedMedian": "Rehacer mostrar mediana",
    "DG.Undo.graph.hidePlottedMedian": "Deshacer ocultar mediana",
    "DG.Redo.graph.hidePlottedMedian": "Rehacer ocultar mediana",
    "DG.Undo.graph.showPlottedStDev": "Deshacer mostrar desvío estándar",
    "DG.Redo.graph.showPlottedStDev": "Rehacer mostrar desvío estándar",
    "DG.Undo.graph.hidePlottedStDev": "Deshacer ocultar desvío estándar",
    "DG.Redo.graph.hidePlottedStDev": "Rehacer ocultar desvío estándar",
    "DG.Undo.graph.showPlottedIQR": "Deshacer mostrar rango inter-cuartil",
    "DG.Redo.graph.hidePlottedIQR": "Rehacer ocultar rango inter-cuartil",
    "DG.Undo.graph.hidePlottedIQR": "Deshacer ocultar rango inter-cuartil",
    "DG.Redo.graph.showPlottedIQR": "Rehacer mostrar rango inter-cuartil",
    "DG.Undo.graph.addMovableValue": "Deshacer agregar valor movible",
    "DG.Redo.graph.addMovableValue": "Rehacer agregar valor movible",
    "DG.Undo.graph.removeMovableValue": "Deshacer quitar valor movible",
    "DG.Redo.graph.removeMovableValue": "Rehacer quitar valor movible",
    "DG.Undo.graph.moveMovableValue": "Deshacer mover valor movible",
    "DG.Redo.graph.moveMovableValue": "Rehacer mover valor movible",
    "DG.Undo.graph.changePointColor": "Deshacer cambiar color datos",
    "DG.Redo.graph.changePointColor": "Rehacer cambiar color datos",
    "DG.Undo.graph.changeStrokeColor": "Deshacer cambiar color borde",
    "DG.Redo.graph.changeStrokeColor": "Rehacer cambiar color borde",
    "DG.Undo.graph.changePointSize": "Deshacer cambiar tamaño punto",
    "DG.Redo.graph.changePointSize": "Rehacer  cambiar tamaño punto",
    "DG.Undo.graph.changeAttributeColor": "Deshacer cambiar color de atributo",
    "DG.Redo.graph.changeAttributeColor": "Rehacer cambiar color de atributo",
    "DG.Undo.graph.changeBackgroundColor": "Deshacer cambiar color fondo gráfico",
    "DG.Redo.graph.changeBackgroundColor": "Rehacer cambiar color fondo gráfico",
    "DG.Undo.graph.toggleTransparent": "Deshacer activar transparencia de gráfico",
    "DG.Redo.graph.toggleTransparent": "Rehacer activar transparencia de gráfico",
    "DG.Undo.guide.show": "Deshacer mostrar guía",
    "DG.Redo.guide.show": "Rehacer mostrar guía",
    "DG.Undo.guide.navigate": "Deshacer cambiar página de guía",
    "DG.Redo.guide.navigate": "Rehacer cambiar página de guía",
    "DG.Undo.hideSelectedCases": "Deshacer ocultar casos seleccionados",
    "DG.Redo.hideSelectedCases": "Rehacer ocultar casos seleccionados",
    "DG.Undo.hideUnselectedCases": "Deshacer ocultar casos no seleccionados",
    "DG.Redo.hideUnselectedCases": "Rehacer ocultar casos no seleccionados",
    "DG.Undo.enableNumberToggle": "Deshacer Mostrar Activación de Visibilidad de Padres",
    "DG.Redo.enableNumberToggle": "Rehacer Mostrar Activación de Visibilidad de Padres",
    "DG.Undo.disableNumberToggle": "Deshacer Ocultar Activación de Visibilidad de Padres",
    "DG.Redo.disableNumberToggle": "Rehacer Ocultar Activación de Visibilidad de Padres",
    "DG.Undo.interactiveUndoableAction": "Deshacer una acción en el interactivo",
    "DG.Redo.interactiveUndoableAction": "Rehacer una acción en el interactivo",
    "DG.Undo.showAllCases": "Deshacer mostrar todos los casos",
    "DG.Redo.showAllCases": "Rehacer mostrar todos los casos",
    "DG.Undo.map.create": "Deshacer agregar mapa",
    "DG.Redo.map.create": "Rehacer agregar mapa",
    "DG.Undo.map.fitBounds": "Deshacer cambiar tamaño de mapa",
    "DG.Redo.map.fitBounds": "Rehacer cambiar tamaño de mapa",
    "DG.Undo.map.pan": "Deshacer paneo de mapa",
    "DG.Redo.map.pan": "Rehacer paneo de mapa",
    "DG.Undo.map.zoom": "Deshacer zoom en mapa",
    "DG.Redo.map.zoom": "Rehacer zoom en mapa",
    "DG.Undo.map.showGrid": "Deshacer mostrar grilla en mapa",
    "DG.Redo.map.showGrid": "Rehacer mostrar grilla en mapa",
    "DG.Undo.map.hideGrid": "Deshacer ocultar grilla en mapa",
    "DG.Redo.map.hideGrid": " Rehacer ocultar grilla en mapa",
    "DG.Undo.map.changeGridSize": "Deshacer cambiar tamaño grilla de mapa",
    "DG.Redo.map.changeGridSize": "Rehacer cambiar tamaño grilla de mapa",
    "DG.Undo.map.showPoints": "Deshacer mostrar puntos en mapa",
    "DG.Redo.map.showPoints": "Rehacer mostrar puntos en mapa",
    "DG.Undo.map.hidePoints": "Deshacer ocultar puntos en mapa",
    "DG.Redo.map.hidePoints": "Rehacer ocultar puntos en mapa",
    "DG.Undo.map.showLines": "Deshacer mostrar líneas en mapa",
    "DG.Redo.map.showLines": "Rehacer mostrar líneas en mapa",
    "DG.Undo.map.hideLines": "Deshacer ocultar líneas en mapa",
    "DG.Redo.map.hideLines": "Rehacer ocultar líneas en mapa",
    "DG.Undo.map.changeBaseMap": "Deshacer cambiar fondo de mapa",
    "DG.Redo.map.changeBaseMap": "Rehacer cambiar fondo de mapa",
    "DG.Undo.textComponent.create": "Deshacer agregar objeto texto",
    "DG.Redo.textComponent.create": "Rehacer agregar objeto texto",
    "DG.Undo.textComponent.edit": "Deshacer editar texto",
    "DG.Redo.textComponent.edit": "Rehacer editar texto",
    "DG.Undo.sliderComponent.create": "Deshacer agregar deslizador",
    "DG.Redo.sliderComponent.create": "Rehacer agregar deslizador",
    "DG.Undo.slider.change": "Deshacer cambiar valor deslizador",
    "DG.Redo.slider.change": "Rehacer cambiar valor deslizador",
    "DG.Undo.slider.changeMultiples": "Deshacer cambiar restricciones múltiples de deslizador",
    "DG.Redo.slider.changeMultiples": "Rehacer cambiar restricciones múltiples de deslizador",
    "DG.Undo.slider.changeSpeed": "Deshacer cambiar máx cuadros/seg deslizador",
    "DG.Redo.slider.changeSpeed": "Rehacer cambiar máx cuadros/seg deslizador",
    "DG.Undo.slider.changeDirection": "Deshacer cambiar dirección animación deslizador",
    "DG.Redo.slider.changeDirection": "Rehacer cambiar dirección animación deslizador",
    "DG.Undo.slider.changeRepetition": "Deshacer cambiar repetición animación deslizador",
    "DG.Redo.slider.changeRepetition": "Rehacer cambiar repetición animación deslizador",
    "DG.Undo.graphComponent.create": "Deshacer agregar un gráfico",
    "DG.Redo.graphComponent.create": "Rehacer agregar un gráfico",
    "DG.Undo.dataContext.create": "Deshacer crear conjunto de datos",
    "DG.Redo.dataContext.create": "Rehacer crear conjunto de datos",
    "DG.Undo.data.deleteCases": "Deshacer eliminar casos",
    "DG.Redo.data.deleteCases": "Rehacer eliminar casos",
    "DG.Undo.component.close": "Deshacer cerrar componente",
    "DG.Redo.component.close": "Rehacer cerrar componente",
    "DG.Undo.component.minimize": "Deshacer minimizar componente",
    "DG.Redo.component.minimize": "Rehacer minimizar componente",
    "DG.Undo.dataContext.moveAttribute": "Deshacer mover atributo en tabla de caso",
    "DG.Redo.dataContext.moveAttribute": "Rehacer mover atributo en tabla de caso",
    "DG.DataContext.singleCaseName": "caso",
    "DG.DataContext.pluralCaseName": "casos",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "una colección",
    "DG.DataContext.collapsedRowString": "%@1 de %@2",
    "DG.DataContext.noData": "Sin datos",
    "DG.DataContext.baseName": "Data_Set_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "La fórmula para el atributo \"%@\" no es editable.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Crear un nuevo atributo que permita especificar una fórmula",
    "DG.Formula.FuncCategoryArithmetic": "Funciones aritméticas",
    "DG.Formula.FuncCategoryConversion": "Otras funciones",
    "DG.Formula.FuncCategoryDateTime": "Funciones de Fecha/Hora",
    "DG.Formula.FuncCategoryLookup": "Funciones de búsqueda",
    "DG.Formula.FuncCategoryOther": "Otras funciones",
    "DG.Formula.FuncCategoryRandom": "Otras funciones",
    "DG.Formula.FuncCategoryStatistical": "Funciones estadísticas",
    "DG.Formula.FuncCategoryString": "Funciones de texto",
    "DG.Formula.FuncCategoryTrigonometric": "Funciones trigonométricas",
    "DG.Formula.DateLongMonthJanuary": "Enero",
    "DG.Formula.DateLongMonthFebruary": "Febrero",
    "DG.Formula.DateLongMonthMarch": "Marzo",
    "DG.Formula.DateLongMonthApril": "Abril",
    "DG.Formula.DateLongMonthMay": "Mayo",
    "DG.Formula.DateLongMonthJune": "Junio",
    "DG.Formula.DateLongMonthJuly": "Julio",
    "DG.Formula.DateLongMonthAugust": "Agosto",
    "DG.Formula.DateLongMonthSeptember": "Septiembre",
    "DG.Formula.DateLongMonthOctober": "Octubre",
    "DG.Formula.DateLongMonthNovember": "Noviembre",
    "DG.Formula.DateLongMonthDecember": "Diciembre",
    "DG.Formula.DateShortMonthJanuary": "Ene",
    "DG.Formula.DateShortMonthFebruary": "Feb",
    "DG.Formula.DateShortMonthMarch": "Mar",
    "DG.Formula.DateShortMonthApril": "Abr",
    "DG.Formula.DateShortMonthMay": "May",
    "DG.Formula.DateShortMonthJune": "Jun",
    "DG.Formula.DateShortMonthJuly": "Jul",
    "DG.Formula.DateShortMonthAugust": "Ago",
    "DG.Formula.DateShortMonthSeptember": "Sep",
    "DG.Formula.DateShortMonthOctober": "Oct",
    "DG.Formula.DateShortMonthNovember": "Nov",
    "DG.Formula.DateShortMonthDecember": "Dic",
    "DG.Formula.DateLongDaySunday": "Domingo",
    "DG.Formula.DateLongDayMonday": "Lunes",
    "DG.Formula.DateLongDayTuesday": "Martes",
    "DG.Formula.DateLongDayWednesday": "Miércoles",
    "DG.Formula.DateLongDayThursday": "Jueves",
    "DG.Formula.DateLongDayFriday": "Viernes",
    "DG.Formula.DateLongDaySaturday": "Sábado",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec) \\d{1,2}( |,) *\\d{4}|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Error de sintaxis: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Expresión incompleta",
    "DG.Formula.SyntaxErrorInvalidOperator": "Operador inválido: '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "tipo(s) inválido(s) para '%@'",
    "DG.Formula.TypeError.description": "tipo(s) inválido(s) para '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' es irreconocible",
    "DG.Formula.VarReferenceError.description": "la variable '%@' es irreconocible",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "referencia inválida para atributo hijo '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' es un atributo hijo que sólo puede ser referenciado en una función agregada",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' es irreconocible",
    "DG.Formula.FuncReferenceError.description": "la función '%@()' es irreconocible",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' requiere 1 argumento",
    "DG.Formula.FuncArgsErrorSingle.description": "La función '%@()' requiere 1 argumento",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' requiere %@ argumentos",
    "DG.Formula.FuncArgsErrorPlural.description": "La función '%@()' requiere %@ argumentos",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' requiere %@-%@ argumentos",
    "DG.Formula.FuncArgsErrorRange.description": "La función '%@()' requiere %@-%@ argumentos",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "requerimiento pendiente...",
    "DG.Formula.PendingRequest.description": "requerimiento pendiente...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "requerimiento fallido (%@)",
    "DG.Formula.FailedRequest.description": "requerimiento fallido (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "límites de áreas geográficas pendientes...",
    "DG.Formula.PendingBoundaries.description": "límites pendientes...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "límites fallidos (%@)",
    "DG.Formula.FailedBoundaries.description": "límites fallidos (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': conjunto de datos no reconocido",
    "DG.Formula.LookupDataSetError.description": "El conjunto de datos '%@' es irreconocible",
    "DG.Formula.LookupAttrError.message": "'%@' no se encontró en el conjunto de datos '%@'",
    "DG.Formula.LookupAttrError.description": "Atributo '%@' no fue encontrado en el conjunto de datos '%@'",
    "DG.TableController.headerMenuItems.editAttribute": "Editar propiedades del atributo...",
    "DG.TableController.headerMenuItems.editFormula": "Editar fórmula...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Re-aleatorizar",
    "DG.TableController.headerMenuItems.sortAscending": "Orden ascendente (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Orden descendente (9→0, Z→A)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Eliminar atributo",
    "DG.TableController.newAttrDlg.defaultAttrName": "nue_atri",
    "DG.TableController.newAttrDlg.attrNameHint": "Nombre del nuevo atributo",
    "DG.TableController.newAttrDlg.formulaHint": "Si lo desea, tipear fórmula para computar los valores de este atributo",
    "DG.TableController.newAttrDlg.applyTooltip": "Definir el nuevo atributo usando el nombre y, (opcional) la fórmula",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Por favor colocar nombre para el nuevo atributo",
    "DG.TableController.newAttrDialog.AttributesCategory": "Atributos",
    "DG.TableController.newAttrDialog.SpecialCategory": "Especial",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Globales",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Constantes",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Funciones",
    "DG.TableController.renameAttributeInvalidMsg": "Los nombres de atributos no pueden quedar vacíos",
    "DG.TableController.renameAttributeInvalidDesc": "Por favor ingresar nombre válido para atributo",
    "DG.TableController.renameAttributeDuplicateMsg": "Ya existe un atributo con ese nombre",
    "DG.TableController.renameAttributeDuplicateDesc": "Por favor ingrese un nombre de atributo único",
    "DG.TableController.deleteAttribute.confirmMessage": "¿Eliminar el atributo '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "Esta acción no puede deshacerse",
    "DG.TableController.deleteAttribute.okButtonTitle": "Eliminar atributo",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Cancelar",
    "DG.TableController.deleteDataSet.confirmMessage": "¿Eliminar y destruir este conjunto de datos: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Esta acción no puede deshacerse",
    "DG.TableController.deleteDataSet.okButtonTitle": "Eliminar conjunto de datos",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Cancelar",
    "DG.TableController.attrEditor.unitHint": "Unidad de medida (si aplica)",
    "DG.TableController.attrEditor.descriptionHint": "Describir el atributo",
    "DG.TableController.setScoreDlg.applyTooltip": "Fórmula para el atributo '%@'",
    "DG.TableController.setScoreDlg.formulaHint": "Tipear una fórmula para computar los valores de este atributo",
    "DG.TableController.newAttributeTooltip": "Agregar un nuevo atributo a esta tabla",
    "DG.TableController.attributeEditor.title": "Propiedades del atributo",
    "DG.CaseTableDropTarget.dropMessage": "soltar atributo para crear una nueva colección",
    "DG.CaseTable.defaultAttrName": "nuevAtr",
    "DG.CaseTable.indexColumnName": "índice",
    "DG.CaseTable.indexColumnTooltip": "La fila número (caseIndex) dentro de la colección",
    "DG.CaseTable.indexMenu.insertCase": "Insertar Caso",
    "DG.CaseTable.indexMenu.insertCases": "Insertar Casos...",
    "DG.CaseTable.indexMenu.deleteCase": "Eliminar Caso",
    "DG.CaseTable.indexMenu.deleteCases": "Eliminar Casos",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "categoría",
    "DG.CaseTable.attribute.type.categorical": "categoría",
    "DG.CaseTable.attribute.type.numeric": "numérico",
    "DG.CaseTable.attribute.type.date": "fecha",
    "DG.CaseTable.attribute.type.qualitative": "cualitativo",
    "DG.CaseTable.attribute.type.boundary": "límite",
    "DG.CaseTable.attributeEditor.name": "nombre",
    "DG.CaseTable.attributeEditor.description": "descripción",
    "DG.CaseTable.attributeEditor.type": "tipo",
    "DG.CaseTable.attributeEditor.unit": "unidad",
    "DG.CaseTable.attributeEditor.precision": "precisión",
    "DG.CaseTable.attributeEditor.editable": "editable",
    "DG.CaseTable.insertCasesDialog.title": "Insertar Casos",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# de casos a insertar:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "ubicación:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "antes",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "después",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Insertar Casos",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Insertar la cantidad especificada de casos",
    "DG.CaseTableController.allTables": "Todo como tablas",
    "DG.AttrFormView.attrNamePrompt": "Nombre de atributo:",
    "DG.AttrFormView.formulaPrompt": "Fórmula:",
    "DG.AttrFormView.operandMenuTitle": "--- Insertar Valor ---",
    "DG.AttrFormView.functionMenuTitle": "--- Insertar Función ---",
    "DG.AttrFormView.applyBtnTitle": "Aplicar",
    "DG.AttrFormView.cancelBtnTitle": "Cancelar",
    "DG.AttrFormView.cancelBtnTooltip": "Descartar el diálogo sin hacer ningún cambio",
    "DG.GuideConfigView.titlePrompt": "Título de la guía",
    "DG.GuideConfigView.titleHint": "Nombre de la actividad",
    "DG.GuideConfigView.itemTitleHint": "Nombre de sección",
    "DG.GuideConfigView.itemURLHint": "URL de la sección",
    "DG.GuideConfigView.okBtnTitle": "OK",
    "DG.GuideConfigView.okBtnToolTip": "Aceptar items del menú de la Guía",
    "DG.GuideConfigView.cancelBtnTitle": "Cancelar",
    "DG.GuideConfigView.cancelBtnTooltip": "Descartar el diálogo sin hacer ningún cambio",
    "DG.GuideConfigView.httpWarning": "La URL debe comenzar con http:// ó https://",
    "DG.DataDisplayModel.rescaleToData": "Reescalar a datos",
    "DG.DataDisplayModel.ShowConnectingLine": "Mostrar líneas de conexión",
    "DG.DataDisplayModel.HideConnectingLine": "Ocultar líneas de conexión",
    "DG.AxisView.emptyGraphCue": "Clic acá, o arrastrar un atributo acá.",
    "DG.CellLinearAxisView.midPanelTooltip": "Arrastrar para traducir escala de ejes",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Arrastrar para cambiar límite inferior de ejes",
    "DG.CellLinearAxisView.upperPanelTooltip": "Arrastrar para cambiar límite superior de ejes",
    "DG.PlotModel.mixup": "Mezclar los puntos",
    "DG.PlotModel.showCount": "Mostrar Conteo",
    "DG.PlotModel.hideCount": "Ocultar Conteo",
    "DG.ScatterPlotModel.sumSquares": ",\nSuma de los cuadrados = %@",
    "DG.ScatterPlotModel.rSquared": ",\nr^2 = %@",
    "DG.ScatterPlotModel.slopeIntercept": "%@ = %@ %@ %@ %@",
    "DG.ScatterPlotModel.infiniteSlope": "%@ = %@",
    "DG.ScatterPlotModel.slopeOnly": "pendiente = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "por año",
    "DG.ScatterPlotModel.daysLabel": "por día",
    "DG.ScatterPlotModel.hoursLabel": "por hora",
    "DG.ScatterPlotModel.minutesLabel": "por minuto",
    "DG.ScatterPlotModel.secondsLabel": "por segundo",
    "DG.LegendView.attributeTooltip": "Clic para cambiar leyenda del atributo",
    "DG.NumberToggleView.showAll": "Mostrar todo –",
    "DG.NumberToggleView.hideAll": "Ocultar todo –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Último",
    "DG.NumberToggleView.showAllTooltip": "Clic para mostrar todos los casos\nClic en etiquetas de caso padre para alternar visibilidad",
    "DG.NumberToggleView.hideAllTooltip": "Clic para ocultar todos los casos\nClic en etiquetas de caso padre para alternar visibilidad",
    "DG.NumberToggleView.enableLastModeTooltip": "Clic para mostrar sólo último caso padre",
    "DG.NumberToggleView.disableLastModeTooltip": "Clic para salir del modo último caso padre",
    "DG.NumberToggleView.indexTooltip": "Clic para alternar visibiilidad",
    "DG.PlottedAverageAdornment.meanValueTitle": "promedio=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "mediana=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 DE, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "RIQ=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "inferior=%@\nQ1=%@\nmediana=%@\nQ3=%@\nsuperior=%@\nRIQ=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Leyenda: %@",
    "DG.DataDisplayMenu.remove": "Quitar atributo",
    "DG.DataDisplayMenu.removeAttribute_x": "Quitar X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Quitar Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Quitar Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Quitar Leyenda: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Tratar como Categoría",
    "DG.DataDisplayMenu.treatAsNumeric": "Tratar como Numérico",
    "DG.DataDisplayMenu.hide": "Ocultar y Mostrar",
    "DG.DataDisplayMenu.hideSelectedPlural": "Ocultar Casos Seleccionados",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Ocultar Casos No Seleccionados",
    "DG.DataDisplayMenu.hideSelectedSing": "Ocultar Caso Seleccionado",
    "DG.DataDisplayMenu.hideUnselectedSing": "Ocultar Caso No Seleccionado",
    "DG.DataDisplayMenu.enableNumberToggle": "Mostrar Alternancia Visiblidad Padres",
    "DG.DataDisplayMenu.disableNumberToggle": "Ocultar Alternancia Visiblidad Padres",
    "DG.DataDisplayMenu.showAll": "Mostrar todos los casos",
    "DG.DataDisplayMenu.snapshot": "Capturar imagen del gráfico",
    "DG.GraphView.replaceAttribute": "Reemplazar %@ con %@",
    "DG.GraphView.addAttribute": "Agregar atributo %@",
    "DG.GraphView.addToEmptyPlace": "Crear ejes con %@",
    "DG.GraphView.addToEmptyX": "Crear eje-x con %@",
    "DG.GraphView.dropInPlot": "Colorear puntos con valores de %@",
    "DG.GraphView.zoomTip": "Doble clic para acercar.\nShift-doble-clic para alejar",
    "DG.GraphView.rescale": "Reescalar a datos",
    "DG.AxisView.labelTooltip": "—Clic para cambiar atributo %@ de ejes",
    "DG.AxisView.vertical": "vertical",
    "DG.AxisView.horizontal": "horizontal",
    "DG.DataTip.connectingLine": "%@: %@\ncon %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Fórmula",
    "DG.PlottedValue.namePrompt": "Valor graficado",
    "DG.PlottedValue.formulaPrompt": "valor =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Función graficada",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Tipear una expresión, por ej: x*x/30 - 50",
    "DG.MapView.showGrid": "Mostrar grilla",
    "DG.MapView.hideGrid": "Ocultar grilla",
    "DG.MapView.showPoints": "Mostrar puntos",
    "DG.MapView.hidePoints": "Ocultar puntos",
    "DG.MapView.marqueeHint": "Herramienta de selección—arrastrar seleccionar puntos en mapa",
    "DG.MapView.gridControlHint": "Cambiar tamaño rectángulos de grilla",
    "DG.Inspector.values": "Medida",
    "DG.Inspector.styles": "Formato",
    "DG.Inspector.pointSize": "Tamaño del punto:",
    "DG.Inspector.transparency": "Transparencia:",
    "DG.Inspector.color": "Color:",
    "DG.Inspector.legendColor": "Color Leyenda:",
    "DG.Inspector.backgroundColor": "Color Fondo:",
    "DG.Inspector.stroke": "Borde:",
    "DG.Inspector.rescale.toolTip": "Reescalar vista para mostrar todos los datos",
    "DG.Inspector.mixUp.toolTip": "Mezclar todos los puntos",
    "DG.Inspector.hideShow.toolTip": "Mostrar todos los casos u ocultar casos seleccionados/no seleccionados",
    "DG.Inspector.delete.toolTip": "Eliminar casos seleccionados o no seleccionados",
    "DG.Inspector.sliderValues.toolTip": "Setear dirección de animación de deslizador, velocidad, ...",
    "DG.Inspector.webViewEditURL.toolTip": "Editar la URL de la página web mostrada",
    "DG.Inspector.selection.selectAll": "Seleccionar todos los casos",
    "DG.Inspector.selection.deleteSelectedCases": "Eliminar casos seleccionados",
    "DG.Inspector.selection.deleteUnselectedCases": "Eliminar casos no seleccionados",
    "DG.Inspector.deleteAll": "Eliminar Todos los casos",
    "DG.Inspector.deleteDataSet": "Eliminar y destruir el conjunto de datos",
    "DG.Inspector.displayValues.toolTip": "Cambiar lo que se muestra a lo largo de los puntos",
    "DG.Inspector.displayStyles.toolTip": "Cambiar la apariencia de la vista",
    "DG.Inspector.makeImage.toolTip": "Guardar la imagen como archivo PNG",
    "DG.Inspector.displayShow": "Mostrar ...",
    "DG.Inspector.colorPicker.more": "más",
    "DG.Inspector.colorPicker.less": "menos",
    "DG.Inspector.graphTransparency": "Transparente",
    "DG.Inspector.graphCount": "Conteo",
    "DG.Inspector.graphPercent": "Porcentaje",
    "DG.Inspector.graphRow": "Fila",
    "DG.Inspector.graphColumn": "Columna",
    "DG.Inspector.graphCell": "Celda",
    "DG.Inspector.graphConnectingLine": "Líneas de conexión",
    "DG.Inspector.graphMovableLine": "Línea movible",
    "DG.Inspector.graphInterceptLocked": "Intersección de ejes bloqueada",
    "DG.Inspector.graphPlottedFunction": "Función graficada",
    "DG.Inspector.graphSquares": "Cuadrados de los residuales",
    "DG.Inspector.graphLSRL": "Recta de cuadrados mínimos",
    "DG.Inspector.graphMovableValue": "Valor movible",
    "DG.Inspector.graphAdd": "Agregar",
    "DG.Inspector.graphRemove": "Quitar",
    "DG.Inspector.graphPlottedMean": "Promedio",
    "DG.Inspector.graphPlottedMedian": "Mediana",
    "DG.Inspector.graphPlottedStDev": "Desvío estándar",
    "DG.Inspector.graphPlottedIQR": "Rango intercuartil",
    "DG.Inspector.graphPlottedBoxPlot": "Puntos en caja",
    "DG.Inspector.graphPlottedValue": "Valor graficado",
    "DG.Inspector.attributes.toolTip": "Crear nuevos atributos. Exportar datos del caso.",
    "DG.Inspector.resize.toolTip": "Ajustar tamaño de columnas a los datos",
    "DG.Inspector.newAttribute": "Nuevo atributo en %@...",
    "DG.Inspector.randomizeAllAttributes": "Aleatorizar Todo",
    "DG.Inspector.exportCaseData": "Exportar datos del caso...",
    "DG.Inspector.mapGrid": "Grilla",
    "DG.Inspector.mapPoints": "Puntos",
    "DG.Inspector.mapLines": "Líneas de conexión",
    "DG.GameController.continuityError": "Lo lamento, después de reordenar las columnas de la tabla de casos no pueden aceptarse nuevos datos.",
    "DG.GameView.loading": "Cargando",
    "DG.GameView.loadError": "Si está viendo este texto es porque la carga de la URL anterior pudo haber fallado. Puede comprobar el enlace en otra pestaña del navegador o informar del error en http://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "¿Seguro?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Sí, cerrarla",
    "DG.Component.closeComponent.cancelButtonTitle": "Cancelar",
    "DG.GameController.confirmCloseDescription": "Si cierra esto, no se podrán agregar más datos.",
    "DG.WebView.defaultTitle": "Página web",
    "DG.mainPage.exceptionMessage": "Se ha producido un error que puede afectar la forma en que se comporta este programa. Quizás desee volver a cargar esta página después de guardar su trabajo. (Error: %@)",
    "DG.fileMenu.provider.examples.displayName": "Documentos de ejemplo",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Abrir un componente plugin",
    "DG.Undo.graph.showMovablePoint": "Deshacer mostrar punto movible",
    "DG.Redo.graph.showMovablePoint": "Rehacer mostrar punto movible",
    "DG.Undo.graph.hideMovablePoint": "Deshacer ocultar punto movible",
    "DG.Redo.graph.hideMovablePoint": "Rehacer ocultar punto movible",
    "DG.Undo.graph.moveMovablePoint": "Deshacer mover punto movible",
    "DG.Redo.graph.moveMovablePoint": "Rehacer mover punto movible",
    "DG.DataDisplayMenu.copyAsImage": "Abrir en herramienta Dibujar",
    "DG.DataDisplayMenu.exportImage": "Exportar imagen...",
    "DG.DataDisplayMenu.imageOfTitle": "Imagen de %@",
    "DG.Inspector.graphMovablePoint": "Punto movible",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Abrir tabla de casos para este conjunto de datos",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Crear un nuevo conjunto de datos",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Eliminar y destruir este conjunto de datos",
    "DG.Undo.graph.showAsBarChart": "Deshacer fusionar puntos en barras",
    "DG.Redo.graph.showAsBarChart": "Rehacer fusionar puntos en barras",
    "DG.Undo.graph.showAsDotChart": "Deshacer dispersar barras en puntos",
    "DG.Redo.graph.showAsDotChart": "Rehacer dispersar barras en puntos",
    "DG.CountAxisView.countLabel": "Conteo",
    "DG.CountAxisView.countLabelDescription": "Cantidad de casos en la barra a lo largo de este eje",
    "DG.CountAxisView.percentLabel": "Porcentaje",
    "DG.CountAxisView.percentLabelDescription": "Porcentaje de casos en la barra a lo largo de este eje",
    "DG.BarChartModel.cellTipPlural": "%@ de %@ %@ (%@%) son %@",
    "DG.BarChartModel.cellTipSingular": "%@ de%@ %@ (%@%) es %@",
    "DG.Inspector.configuration": "Configuración",
    "DG.Inspector.displayConfiguration.toolTip": "Configurar la vista de modo diferente",
    "DG.Inspector.displayScale": "Escala ...",
    "DG.Inspector.graphBarChart": "Fusionar puntos en barras",
    "DG.Locale.name.de": "Alemán",
    "DG.Locale.name.en": "Inglés",
    "DG.Locale.name.es": "Español",
    "DG.Locale.name.he": "Hebreo",
    "DG.Locale.name.tr": "Turco",
    "DG.Locale.name.zh": "Chino",
    "DG.Undo.graph.swapCategories": "Undo reordering categories",
    "DG.Redo.graph.swapCategories": "Redo reordering categories",
    "DG.TableController.collectionTitleText": "casos",
    "DG.TableController.collectionTitleTextWithSetAside": "casos",
    "DG.Inspector.setaside.setAsideSelectedCases": "Casos",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Casos",
    "DG.Inspector.setaside.restoreSetAsideCases": "Casos",
    "DG.DocumentController.caseCardTitle": "Case Card",
    "DG.DocumentController.toggleToCaseCard": "Switch to case card view of the data",
    "DG.DocumentController.toggleToCaseTable": "Switch to case table view of the data",
    "DG.CaseCard.indexString": "1 of %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ selected of %@ %@",
    "DG.CaseCard.summaryValues": "%@ values",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Select and show next case",
    "DG.CaseCard.navPrevCase": "Select and show previous case",
    "DG.CaseCard.navFirstCase": "Select and show first case",
    "DG.CaseCard.navLastCase": "Select and show last case",
    "DG.Undo.component.toggleTableToCard": "Undo changing case table to case card",
    "DG.Redo.component.toggleTableToCard": "Redo changing case table to case card",
    "DG.Undo.component.toggleCardToTable": "Undo changing case card to case table",
    "DG.Redo.component.toggleCardToTable": "Redo changing case card to case table",
    "DG.Undo.graph.addBackgroundImage": "Undo adding graph background image",
    "DG.Redo.graph.addBackgroundImage": "Redo adding graph background image",
    "DG.Undo.graph.removeBackgroundImage": "Undo removing graph background image",
    "DG.Redo.graph.removeBackgroundImage": "Redo removing graph background image",
    "DG.Undo.graph.lockBackgroundImage": "Undo locking background image to axes",
    "DG.Redo.graph.lockBackgroundImage": "Redo locking background image to axes",
    "DG.Undo.graph.unlockBackgroundImage": "Undo unlocking background image from axes",
    "DG.Redo.graph.unlockBackgroundImage": "Redo unlocking background image from axes",
    "DG.Undo.enableMeasuresForSelection": "Undo Show Measures For Selection",
    "DG.Redo.enableMeasuresForSelection": "Redo Show Measures For Selection",
    "DG.Undo.disableMeasuresForSelection": "Undo Hide Measures For Selection",
    "DG.Redo.disableMeasuresForSelection": "Redo Hide Measures For Selection",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Show Measures for Selection",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Hide Measures for Selection",
    "DG.DataDisplayMenu.addBackgroundImage": "Add Background Image",
    "DG.DataDisplayMenu.lockImageToAxes": "Lock Background Image to Axes",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Unlock Background Image from Axes",
    "DG.DataDisplayMenu.removeBackgroundImage": "Remove Background Image",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Delete Formula (Keeping Values)",
    "DG.TableController.headerMenuItems.recoverFormula": "Recover Deleted Formula",
    "DG.Inspector.displayLayers.toolTip": "Change the appearance of the map layers",
    "DG.Inspector.layers": "Layers",
    "DG.Undo.graph.repositionEquation": "Undo repositioning equation",
    "DG.Redo.graph.repositionEquation": "Redo repositioning equation",
    "DG.TableController.attrEditor.precisionNumericHint": "Number of digits after decimal point",
    "DG.TableController.attrEditor.precisionDateHint": "Determines how much of the date is displayed",
    "DG.TableController.attrEditor.typeHint": "Set to force the attribute to be treated as a certain type",
    "DG.TableController.attrEditor.nameHint": "The attribute name appears in the case table, case card, and on graph axes",
    "DG.TableController.attrEditor.editableHint": "If the attribute is not editable, its values and/or formula cannot be changed",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "year month day hour minute second millisecond",
    "DG.AttributeFormat.DatePrecision.year": "YYYY",
    "DG.AttributeFormat.DatePrecision.month": "MMM YYYY",
    "DG.AttributeFormat.DatePrecision.day": "MMM D, YYYY",
    "DG.AttributeFormat.DatePrecision.hour": "MMM D, YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "MMM D, YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "MMM D, YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@ in %@",
    "DG.CaseCard.attrHintDescription": "%@: %@",
    "DG.CaseCard.attrHintFormula": "%@\n%@",
    "DG.AppController.optionMenuItems.help-forum": "Help Forum...",
    "DG.AppController.showHelpForumTitle": "Help Forum",
    "DG.Locale.name.el": "Greek",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ of %@ (%@%) is %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ of %@ (%@%) are %@",
    "DG.DataDisplayMenu.removeAttribute_top": "Remove Side-by-side Layout by %@",
    "DG.DataDisplayMenu.removeAttribute_right": "Remove Vertical Layout by %@",
    "DG.GraphView.layoutPlotsSideBySide": "Layout side-by-side by %@",
    "DG.GraphView.layoutPlotsVertically": "Layout vertically by %@",
    "DG.Undo.graph.makeStrokeSameAsFill": "Undo making stroke same as fill",
    "DG.Redo.graph.makeStrokeSameAsFill": "Redo making stroke same as fill",
    "DG.Undo.graph.makeStrokeIndependent": "Undo making stroke independent of fill",
    "DG.Redo.graph.makeStrokeIndependent": "Redo making stroke independent of fill",
    "DG.Inspector.strokeSameAsFill": "Stroke same color as fill",
    "DG.Formula.DateShortDaySunday": "Sun",
    "DG.Formula.DateShortDayMonday": "Mon",
    "DG.Formula.DateShortDayTuesday": "Tue",
    "DG.Formula.DateShortDayWednesday": "Wed",
    "DG.Formula.DateShortDayThursday": "Thu",
    "DG.Formula.DateShortDayFriday": "Fri",
    "DG.Formula.DateShortDaySaturday": "Sat",
    "DG.AttributeFormat.DatePrecision.millisecond": "MMM D, YYYY HH:mm:ss.SSS",
    "DG.CellAxis.other": "OTHER",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 MAD, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "Mean Absolute Deviation",
    "DG.Undo.graph.showPlottedBoxPlot": "Undo showing box plot",
    "DG.Redo.graph.hidePlottedBoxPlot": "Redo hiding box plot",
    "DG.Undo.graph.hidePlottedBoxPlot": "Undo hiding box plot",
    "DG.Redo.graph.showPlottedBoxPlot": "Redo showing box plot",
    "DG.Undo.graph.showOutliers": "Undo showing outliers",
    "DG.Redo.graph.hideOutliers": "Redo hiding outliers",
    "DG.Undo.graph.hideOutliers": "Undo hiding outliers",
    "DG.Redo.graph.showOutliers": "Redo showing outliers",
    "DG.Inspector.graphBoxPlotShowOutliers": "Show Outliers",
    "DG.Locale.name.nb": "Bokmål",
    "DG.Locale.name.nn": "Nynorsk",
    "DG.CaseCard.newCaseToolTip": "Add an empty case to this collection",
    "DG.TableController.headerMenuItems.renameAttribute": "Rename",
    "DG.Undo.graph.fuseDotsToRectangles": "Undo fusing dots into rectangles",
    "DG.Redo.graph.fuseDotsToRectangles": "Redo fusing dots into rectangles",
    "DG.Undo.graph.dissolveRectanglesToDots": "Undo dissolving rectangles into dots",
    "DG.Redo.graph.dissolveRectanglesToDots": "Redo dissolving rectangles into dots",
    "DG.Undo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Redo.graph.changeBreakdownType": "Undo changing scale type",
    "DG.Undo.graph.showAsBinnedPlot": "Undo grouping dots into bins",
    "DG.Redo.graph.showAsBinnedPlot": "Redo grouping dots into bins",
    "DG.Undo.graph.showAsDotPlot": "Undo ungrouping dots from bins",
    "DG.Redo.graph.showAsDotPlot": "Redo ungrouping dots from bins",
    "DG.Undo.graph.dragBinBoundary": "Undo dragging bin boundary",
    "DG.Redo.graph.dragBinBoundary": "Redo dragging bin boundary",
    "DG.Undo.graph.changeBinWidth": "Undo changing bin width",
    "DG.Redo.graph.changeBinWidth": "Redo changing bin width",
    "DG.Undo.graph.changeBinAlignment": "Undo changing bin alignment",
    "DG.Redo.graph.changeBinAlignment": "Redo changing bin alignment",
    "DG.BinnedPlotModel.dragBinTip": "Drag to change bin width",
    "DG.HistogramView.barTipPlural": "%@ of %@ %@ (%@%) are ≥ %@ and < %@",
    "DG.HistogramView.barTipSingular": "%@ of %@ %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendSingular": "%@ of %@ (%@%) is ≥ %@ and < %@",
    "DG.HistogramView.barTipNoLegendPlural": "%@ of %@ (%@%) are ≥ %@ and < %@",
    "DG.Inspector.graphGroupIntoBins": "Group into Bins",
    "DG.Inspector.graphBinWidth": "Bin width",
    "DG.Inspector.graphAlignment": "Alignment",
    "DG.CaseTable.dividerView.expandAllTooltip": "expand all groups",
    "DG.CaseTable.dividerView.expandGroupTooltip": "expand group",
    "DG.CaseTable.dividerView.collapseAllTooltip": "collapse all groups",
    "DG.CaseTable.dividerView.collapseGroupTooltip": "collapse group",
    "DG.BinnedPlotModel.binLabelTip": "Values in this bin are ≥ %@ and < %@",
    "DG.Component.closeComponent.toolTip": "Close this Component",
    "DG.Component.minimizeComponent.toolTip": "Minimize or expand this Component",
    "DG.Locale.name.ja": "Japanese"
});
