SC.stringsFor("es", {
    "DG.fileMenu.menuItem.newDocument": "Nuevo",
    "DG.fileMenu.menuItem.openDocument": "Abrir...",
    "DG.fileMenu.menuItem.closeDocument": "Cerrar",
    "DG.fileMenu.menuItem.importFile": "Importar...",
    "DG.fileMenu.menuItem.revertTo": "Revertir...",
    "DG.fileMenu.menuItem.revertToOpened": "Versión abierta recientemente",
    "DG.fileMenu.menuItem.revertToShared": "Versión compartida",
    "DG.fileMenu.menuItem.saveDocument": "Guardar...",
    "DG.fileMenu.menuItem.copyDocument": "Crear una copio",
    "DG.fileMenu.menuItem.share": "Compartir...",
    "DG.fileMenu.menuItem.shareGetLink": "Obtener vinculo para compartir",
    "DG.fileMenu.menuItem.shareUpdate": "Actualizar la versión compartida",
    "DG.fileMenu.menuItem.renameDocument": "Cambiar nombre",
    "DG.main.userEntryView.title": "¿Que te gustaría hacer?",
    "DG.main.userEntryView.openDocument": "Abre documento o Examinar ejemplos",
    "DG.main.userEntryView.newDocument": "Crear nuevo documento",
    "DG.mainPage.mainPane.undoButton.title": "Deshacer",
    "DG.mainPage.mainPane.undoButton.toolTip": "Deshacer la última acción",
    "DG.mainPage.mainPane.redoButton.title": "Rehacer",
    "DG.mainPage.mainPane.redoButton.toolTip": "Rehacer la última acción",
    "DG.mainPage.mainPane.versionString": "Versión %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Desfortunadamente, CODAP no se apoya en su navegador. CODAP se apoya en Firefox 46+, Chrome 50+, Windows Edge 14+, and Safari 10+. CODAP no se apoya activamente en otros versiones o navegadores ahora.",
    "DG.mainPage.titleBar.saved": "¡Documento Guardado!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Version %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Version %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Borrar datos...",
    "DG.AppController.resetData.toolTip": "Eliminar todos los datos del documento actual",
    "DG.AppController.resetData.warnMessage": "¿Realmente desea eliminar todos los datos de este documento?",
    "DG.AppController.resetData.warnDescription": "Esta acción no es reversible.",
    "DG.AppController.resetData.okButtonTitle": "Sí, eliminar los datos",
    "DG.AppController.resetData.cancelButtonTitle": "No, mantener los datos",
    "DG.AppController.closeDocument.warnMessage": "¿Cierra el documento actual sin guardarlo?",
    "DG.AppController.closeDocument.warnDescription": "Esta acción no es reversible.",
    "DG.AppController.closeDocument.okButtonTitle": "Cerrar",
    "DG.AppController.closeDocument.cancelButtonTitle": "Cancelar",
    "DG.AppController.beforeUnload.confirmationMessage": "Este documento contiene cambios no guardados.",
    "DG.AppController.optionMenuItems.reportProblem": "Enviar comentarios...",
    "DG.AppController.optionMenuItems.viewWebPage": "Mostrar página web...",
    "DG.AppController.optionMenuItems.configureGuide": "Configurar la guía...",
    "DG.AppController.optionMenuItems.about": "Acerca de CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "¿Qué hay de nuevo?",
    "DG.AppController.optionMenuItems.help": "Ayuda...",
    "DG.AppController.optionMenuItems.toWebSite": "CODAP pagina web",
    "DG.AppController.exportDocument.prompt": "Archivo nombres:",
    "DG.AppController.exportCaseData.prompt": "Exportar los datos de:",
    "DG.AppController.exportDocument.exportTitle": "Exportar",
    "DG.AppController.exportDocument.exportTooltip": "Exportar los datos a un archivo",
    "DG.AppController.exportDocument.cancelTitle": "Cancelar",
    "DG.AppController.exportDocument.cancelTooltip": "Cancelar la exportación",
    "DG.AppController.feedbackDialog.dialogTitle": "Dar opinion",
    "DG.AppController.feedbackDialog.subHeaderText": "¡Tu opinión es importante para nosotros!",
    "DG.AppController.feedbackDialog.messageText": "Por favor, ayúdenos a continuar mejorando nuestro producto. Preguntas, errores y solicitudes de características son bienvenidas. ¡Gracias!",
    "DG.AppController.feedbackDialog.subjectHint": "¿Cuál es tu opinión?",
    "DG.AppController.feedbackDialog.feedbackHint": "Detalles",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Enviar",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Cancelar",
    "DG.AppController.showWebSiteTitle": "Acerca de CODAP",
    "DG.AppController.showHelpTitle": "Ayuda",
    "DG.AppController.showAboutTitle": "Acerca de CODAP",
    "DG.AppController.showReleaseNotesTitle": "Notas de la versión de CODAP",
    "DG.AppController.dropFile.error": "Error: %@1",
    "DG.AppController.dropFile.unknownFileType": "No se puede importar el tipo de archivo",
    "DG.AppController.validateDocument.missingRequiredProperty": "No se encontró propiedad requerida: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Propiedad inesperada de nivel superior: %@1",
    "DG.AppController.validateDocument.unresolvedID": "ID no resuelto: %@1",
    "DG.AppController.validateDocument.parseError": "Error de análisis en el documento: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Documento JSON no válido: %@1",
    "DG.AppController.openDocument.error.general": "No se puede abrir el documento",
    "DG.AppController.openDocument.error.invalid_format": "CODAP no puede abrir este tipo de documento",
    "DG.AppController.createDataSet.initialAttribute": "Variables",
    "DG.AppController.createDataSet.name": "Nuevo Conjunto de Datos",
    "DG.AppController.createDataSet.collectionName": "Datos",
    "DG.AppController.caseTableMenu.newDataSet": "-- nuevo --",
    "DG.SingleTextDialog.okButton.title": "(es)OK",
    "DG.SingleTextDialog.cancelButton.title": "(es)Cancelar",
    "DG.SingleTextDialog.cancelButton.toolTip": "Descartar el cuadro de diálogo sin realizar ningún cambio",
    "DG.DocumentController.calculatorTitle": "Calculadora",
    "DG.DocumentController.caseTableTitle": "Tabla de Datos",
    "DG.DocumentController.graphTitle": "Grafico",
    "DG.DocumentController.sliderTitle": "Deslizador",
    "DG.DocumentController.textTitle": "Texto",
    "DG.DocumentController.mapTitle": "Mapa",
    "DG.DocumentController.enterURLPrompt": "Escriba la URL de una página web para mostrar",
    "DG.DocumentController.enterViewWebPageOKTip": "Muestra la página web dada por la URL",
    "DG.Document.defaultDocumentName": "Documento sin título",
    "DG.Document.documentName.toolTip": "Haga clic para cambiar el nombre del documento",
    "DG.SliderView.thumbView.toolTip": "(es)Drag to change the slider's value",
    "DG.SliderView.startButton.toolTip": "(es)Iniciar/stop animación",
    "DG.ToolButtonData.tableButton.title": "Listas",
    "DG.ToolButtonData.tableButton.toolTip": "(es)Abrir una tabla de datos para cada conjunto de datos(ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Graphico",
    "DG.ToolButtonData.graphButton.toolTip": "(es)Abrir un grafico (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Seslizador",
    "DG.ToolButtonData.sliderButton.toolTip": "(es)Hacer un deslizador (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "Calc",
    "DG.ToolButtonData.calcButton.toolTip": "Abrir/Cerrar la calculadora (ctrl-alt-c)",
    "DG.ToolButtonData.textButton.title": "Texto",
    "DG.ToolButtonData.textButton.toolTip": "Abrir un componente de texto (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "Mapa",
    "DG.ToolButtonData.mapButton.toolTip": "Abrir una mapa",
    "DG.ToolButtonData.optionMenu.title": "Opciones",
    "DG.ToolButtonData.optionMenu.toolTip": "Mostrar página web, Configurar la guía...",
    "DG.ToolButtonData.tileListMenu.title": "Inventario",
    "DG.ToolButtonData.tileListMenu.toolTip": "Mostrar la lista de inventario en el documento",
    "DG.ToolButtonData.guideMenu.title": "Guía",
    "DG.ToolButtonData.guideMenu.toolTip": "Muestra la guía para esta actividad y navega dentro de ella",
    "DG.ToolButtonData.guideMenu.showGuide": "Mostrar Guía",
    "DG.ToolButtonData.help.title": "Ayuda",
    "DG.ToolButtonData.help.toolTip": "Ayuda para CODAP, aprende sobre el proyecto CODAP",
    "DG.Slider.multiples": "Restrict to Multiples of:",
    "DG.Slider.maxPerSecond": "Maximum Animation Frames/sec:",
    "DG.Slider.direction": "Dirección de Animación:",
    "DG.Slider.backAndForth": "Hacia atrás y adelante",
    "DG.Slider.lowToHigh": "De menor a mayor",
    "DG.Slider.highToLow": "De mayor a menor ",
    "DG.Slider.mode": "Repitación la animación:",
    "DG.Slider.nonStop": "Continuo",
    "DG.Slider.onceOnly": "Solo Una Vez",
    "DG.Undo.exceptionOccurred": "Se ha producido un error al intentar deshacer.",
    "DG.Redo.exceptionOccurred": "Se ha producido un error al intentar rehacer.",
    "DG.Undo.componentMove": "Deshacer el movimiento del componente",
    "DG.Redo.componentMove": "Rehacer el movimiento del componente",
    "DG.Undo.componentResize": "Deshacer el cambio de tamaño del componente",
    "DG.Redo.componentResize": "Rehacer el cambio de tamaño del componente",
    "DG.Undo.axisDilate": "Deshacer reescalar el eje",
    "DG.Redo.axisDilate": "Rehacer reescalar el eje",
    "DG.Undo.axisRescaleFromData": "Deshacer reescalar el eje",
    "DG.Redo.axisRescaleFromData": "Rehacer reescalar el eje",
    "DG.Undo.axisDrag": "Deshacer arrastrando el eje",
    "DG.Redo.axisDrag": "Rehacer arrastrando el eje",
    "DG.Undo.axisAttributeChange": "Deshacer cambio de variable del eje",
    "DG.Redo.axisAttributeChange": "Rehacer cambio de variable del eje",
    "DG.Undo.axisAttributeAdded": "Deshacer agregar variable del eje",
    "DG.Redo.axisAttributeAdded": "Rehacer agregar variable del eje",
    "DG.Undo.toggleComponent.add.calcView": "Deshacer abrir la calculadora",
    "DG.Redo.toggleComponent.add.calcView": "Rehacer abrir la calculadora",
    "DG.Undo.toggleComponent.delete.calcView": "Deshacer cerrar la calculadora",
    "DG.Redo.toggleComponent.delete.calcView": "Rehacer cerrar la calculadora",
    "DG.Undo.caseTable.open": "Deshacer abrir la tabla de datos",
    "DG.Redo.caseTable.open": "Rehacer abrir la tabla de datos",
    "DG.Undo.caseTable.editAttribute": "Deshacer edición de la tabla de datos variable",
    "DG.Redo.caseTable.editAttribute": "Rehacer edición de la tabla de datos variable",
    "DG.Undo.caseTable.createAttribute": "Deshacer creación de tabla de datos variable",
    "DG.Redo.caseTable.createAttribute": "Rehacer creación de tabla de datos variable",
    "DG.Undo.caseTable.editAttributeFormula": "Deshacer editar de fórmula para la variable",
    "DG.Redo.caseTable.editAttributeFormula": "Rehacer editar de fórmula para la variable",
    "DG.Undo.caseTable.editCellValue": "Deshacer edición del valor de celda de la tabla de datos",
    "DG.Redo.caseTable.editCellValue": "Rehacer edición del valor de celda de la tabla de datos",
    "DG.Undo.caseTable.sortCases": "Deshacer ordenar de datos",
    "DG.Redo.caseTable.sortCases": "Rehacer ordenar de datos",
    "DG.Undo.caseTable.deleteAttribute": "Deshacer eliminar del variable de la table de datos",
    "DG.Redo.caseTable.deleteAttribute": "Rehacer eliminar del variable de la table de datos",
    "DG.Undo.caseTable.createCollection": "Deshacer crear nueva colección",
    "DG.Redo.caseTable.createCollection": "Rehacer crear nueva colección",
    "DG.Undo.caseTable.collectionNameChange": "Deshacer cambiar el nombre de colección",
    "DG.Redo.caseTable.collectionNameChange": "Rehacer cambiar el nombre de colección",
    "DG.Undo.caseTable.createNewCase": "Deshacer crear nuevo dato",
    "DG.Redo.caseTable.createNewCase": "Rehacer crear nuevo dato",
    "DG.Undo.caseTable.insertCases": "Deshacer insertar datos",
    "DG.Redo.caseTable.insertCases": "Rehacer insertar datos",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Deshacer a todos ampliar/reducir",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Rehacer a todos ampliar/reducir",
    "DG.Undo.caseTable.expandCollapseOneCase": "Deshacer ampliar o reducir de un grupo",
    "DG.Redo.caseTable.expandCollapseOneCase": "Rehacer ampliar o reducir de un grupo",
    "DG.Undo.caseTable.resizeColumns": "(es)Deshacer automáticamente cambiar el tamaño de todas las columnas",
    "DG.Redo.caseTable.resizeColumns": "(es)Rehacer automáticamente cambiar el tamaño de todas las columnas",
    "DG.Undo.document.share": "(es)Deshacer compartir el documento",
    "DG.Redo.document.share": "(es)Rehacer compartir el documento",
    "DG.Undo.document.unshare": "(es)Deshacer dejar de compartir el documento",
    "DG.Redo.document.unshare": "(es)Rehacer dejar de compartir el documento",
    "DG.Undo.game.add": "(es)Deshacer la adición de un juego al documento",
    "DG.Redo.game.add": "(es)Rehacer la adición de un juego al documento",
    "DG.Undo.graph.showCount": "(es)Deshacer mostrar recuento",
    "DG.Redo.graph.showCount": "(es)Rehacer mostrar recuento",
    "DG.Undo.graph.hideCount": "(es)Deshacer ocultar recuento",
    "DG.Redo.graph.hideCount": "(es)Rehacer ocultar recuento",
    "DG.Undo.graph.showPercent": "(es)Deshacer mostrar por ciento",
    "DG.Redo.graph.showPercent": "(es)Rehacer mostrar por ciento",
    "DG.Undo.graph.hidePercent": "(es)Deshacer ocultar por ciento",
    "DG.Redo.graph.hidePercent": "(es)Rehacer ocultar por ciento",
    "DG.Undo.graph.showMovableLine": "(es)Deshacer mostrar línea de valor movible",
    "DG.Redo.graph.showMovableLine": "(es)Rehacer mostrar línea de valor movible",
    "DG.Undo.graph.hideMovableLine": "(es)Deshacer ocultar línea de valor movible",
    "DG.Redo.graph.hideMovableLine": "(es)Rehacer ocultar línea de valor movible",
    "DG.Undo.graph.lockIntercept": "(es)Deshacer bloqueo de línea de intercepción",
    "DG.Redo.graph.lockIntercept": "(es)Rehacer bloqueo de línea de intercepción",
    "DG.Undo.graph.unlockIntercept": "(es)Deshacer desbloquear intersección línea",
    "DG.Redo.graph.unlockIntercept": "(es)Rehacer desbloquear intersección línea",
    "DG.Undo.graph.showPlotFunction": "(es)Deshacer mostrar función de trazado",
    "DG.Redo.graph.showPlotFunction": "(es)Rehacer mostrar plotted function",
    "DG.Undo.graph.hidePlotFunction": "(es)Deshacer ocultar plotted function",
    "DG.Redo.graph.hidePlotFunction": "(es)Rehacer ocultar plotted function",
    "DG.Undo.graph.changePlotFunction": "(es)Deshacer cambiar plotted function",
    "DG.Redo.graph.changePlotFunction": "(es)Rehacer cambiar plotted function",
    "DG.Undo.graph.showPlotValue": "(es)Deshacer mostrar plotted value",
    "DG.Redo.graph.showPlotValue": "(es)Rehacer mostrar plotted value",
    "DG.Undo.graph.hidePlotValue": "(es)Deshacer ocultar plotted value",
    "DG.Redo.graph.hidePlotValue": "(es)Rehacer ocultar plotted value",
    "DG.Undo.graph.changePlotValue": "(es)Deshacer cambiar plotted value",
    "DG.Redo.graph.changePlotValue": "(es)Rehacer cambiar plotted value",
    "DG.Undo.graph.showConnectingLine": "(es)Deshacer mostrar connecting line",
    "DG.Redo.graph.showConnectingLine": "(es)Rehacer mostrar connecting line",
    "DG.Undo.graph.hideConnectingLine": "(es)Deshacer ocultar connecting line",
    "DG.Redo.graph.hideConnectingLine": "(es)Rehacer ocultar connecting line",
    "DG.Undo.graph.showLSRL": "(es)Deshacer mostrar least squares line",
    "DG.Redo.graph.showLSRL": "(es)Rehacer mostrar least squares line",
    "DG.Undo.graph.hideLSRL": "(es)Deshacer ocultar least squares line",
    "DG.Redo.graph.hideLSRL": "(es)Rehacer ocultar least squares line",
    "DG.Undo.graph.showSquares": "(es)Deshacer mostrar squares",
    "DG.Redo.graph.showSquares": "(es)Rehacer mostrar squares",
    "DG.Undo.graph.hideSquares": "(es)Deshacer hiding squares",
    "DG.Redo.graph.hideSquares": "(es)Rehacer hiding squares",
    "DG.Undo.graph.showPlottedMean": "(es)Deshacer mostrar mean",
    "DG.Redo.graph.showPlottedMean": "(es)Rehacer mostrar mean",
    "DG.Undo.graph.hidePlottedMean": "(es)Deshacer hiding mean",
    "DG.Redo.graph.hidePlottedMean": "(es)Rehacer hiding mean",
    "DG.Undo.graph.showPlottedMedian": "(es)Deshacer mostrar median",
    "DG.Redo.graph.showPlottedMedian": "(es)Rehacer mostrar median",
    "DG.Undo.graph.hidePlottedMedian": "(es)Deshacer hiding median",
    "DG.Redo.graph.hidePlottedMedian": "(es)Rehacer hiding median",
    "DG.Undo.graph.showPlottedStDev": "(es)Deshacer mostrar standard deviation",
    "DG.Redo.graph.showPlottedStDev": "(es)Rehacer mostrar standard deviation",
    "DG.Undo.graph.hidePlottedStDev": "(es)Deshacer hiding standard deviation",
    "DG.Redo.graph.hidePlottedStDev": "(es)Rehacer hiding standard deviation",
    "DG.Undo.graph.showPlottedIQR": "(es)Deshacer mostrar inter-quartile range",
    "DG.Redo.graph.hidePlottedIQR": "(es)Rehacer hiding inter-quartile range",
    "DG.Undo.graph.hidePlottedIQR": "(es)Deshacer hiding inter-quartile range",
    "DG.Redo.graph.showPlottedIQR": "(es)Rehacer mostrar inter-quartile range",
    "DG.Undo.graph.addMovableValue": "(es)Deshacer adding movable value",
    "DG.Redo.graph.addMovableValue": "(es)Rehacer adding movable value",
    "DG.Undo.graph.removeMovableValue": "(es)Deshacer removing movable value",
    "DG.Redo.graph.removeMovableValue": "(es)Rehacer removing movable value",
    "DG.Undo.graph.moveMovableValue": "(es)Deshacer moving movable value",
    "DG.Redo.graph.moveMovableValue": "(es)Rehacer moving movable value",
    "DG.Undo.graph.changePointColor": "(es)Deshacer changing data color",
    "DG.Redo.graph.changePointColor": "(es)Rehacer changing data color",
    "DG.Undo.graph.changeStrokeColor": "(es)Deshacer changing stroke color",
    "DG.Redo.graph.changeStrokeColor": "(es)Rehacer changing stroke color",
    "DG.Undo.graph.changePointSize": "(es)Deshacer changing point size",
    "DG.Redo.graph.changePointSize": "(es)Rehacer changing point size",
    "DG.Undo.graph.changeAttributeColor": "(es)Deshacer changing attribute color",
    "DG.Redo.graph.changeAttributeColor": "(es)Rehacer changing attribute color",
    "DG.Undo.graph.changeBackgroundColor": "(es)Deshacer changing graph background color",
    "DG.Redo.graph.changeBackgroundColor": "(es)Rehacer changing graph background color",
    "DG.Undo.graph.toggleTransparent": "(es)Deshacer toggling plot transparency",
    "DG.Redo.graph.toggleTransparent": "(es)Rehacer toggling plot transparency",
    "DG.Undo.guide.show": "(es)Deshacer showing the guide",
    "DG.Redo.guide.show": "(es)Rehacer showing the guide",
    "DG.Undo.guide.navigate": "(es)Deshacer changing the guide page",
    "DG.Redo.guide.navigate": "(es)Rehacer changing the guide page",
    "DG.Undo.hideSelectedCases": "(es)Deshacer hiding selected cases",
    "DG.Redo.hideSelectedCases": "(es)Rehacer hiding selected cases",
    "DG.Undo.hideUnselectedCases": "(es)Deshacer hiding unselected cases",
    "DG.Redo.hideUnselectedCases": "(es)Rehacer hiding unselected cases",
    "DG.Undo.enableNumberToggle": "(es)Deshacer Show Parent Visibility Toggles",
    "DG.Redo.enableNumberToggle": "(es)Rehacer Show Parent Visibility Toggles",
    "DG.Undo.disableNumberToggle": "(es)Deshacer Hide Parent Visibility Toggles",
    "DG.Redo.disableNumberToggle": "(es)Rehacer Hide Parent Visibility Toggles",
    "DG.Undo.interactiveUndoableAction": "(es)Deshacer an action in the interactive",
    "DG.Redo.interactiveUndoableAction": "(es)Rehacer an action in the interactive",
    "DG.Undo.showAllCases": "(es)Deshacer showing all cases",
    "DG.Redo.showAllCases": "(es)Rehacer showing all cases",
    "DG.Undo.map.create": "(es)Deshacer adding map",
    "DG.Redo.map.create": "(es)Rehacer adding map",
    "DG.Undo.map.fitBounds": "(es)Deshacer resizing map",
    "DG.Redo.map.fitBounds": "(es)Rehacer resizing map",
    "DG.Undo.map.pan": "(es)Deshacer panning map",
    "DG.Redo.map.pan": "(es)Rehacer panning map",
    "DG.Undo.map.zoom": "(es)Deshacer zooming map",
    "DG.Redo.map.zoom": "(es)Rehacer zooming map",
    "DG.Undo.map.showGrid": "(es)Deshacer showing grid on map",
    "DG.Redo.map.showGrid": "(es)Rehacer showing grid on map",
    "DG.Undo.map.hideGrid": "(es)Deshacer hiding grid on map",
    "DG.Redo.map.hideGrid": "(es)Rehacer hiding grid on map",
    "DG.Undo.map.changeGridSize": "(es)Deshacer changing map grid size",
    "DG.Redo.map.changeGridSize": "(es)Rehacer changing map grid size",
    "DG.Undo.map.showPoints": "(es)Deshacer showing points on map",
    "DG.Redo.map.showPoints": "(es)Rehacer showing points on map",
    "DG.Undo.map.hidePoints": "(es)Deshacer hiding points on map",
    "DG.Redo.map.hidePoints": "(es)Rehacer hiding points on map",
    "DG.Undo.map.showLines": "(es)Deshacer showing lines on map",
    "DG.Redo.map.showLines": "(es)Rehacer showing lines on map",
    "DG.Undo.map.hideLines": "(es)Deshacer hiding lines on map",
    "DG.Redo.map.hideLines": "(es)Rehacer hiding lines on map",
    "DG.Undo.map.changeBaseMap": "(es)Deshacer changing map background",
    "DG.Redo.map.changeBaseMap": "(es)Rehacer changing map background",
    "DG.Undo.textComponent.create": "(es)Deshacer adding text object",
    "DG.Redo.textComponent.create": "(es)Rehacer adding text object",
    "DG.Undo.textComponent.edit": "(es)Deshacer editing text",
    "DG.Redo.textComponent.edit": "(es)Rehacer editing text",
    "DG.Undo.sliderComponent.create": "(es)Deshacer adding a slider",
    "DG.Redo.sliderComponent.create": "(es)Rehacer adding a slider",
    "DG.Undo.slider.change": "(es)Deshacer slider value change",
    "DG.Redo.slider.change": "(es)Rehacer slider value change",
    "DG.Undo.slider.changeMultiples": "(es)Deshacer change to slider multiples restriction",
    "DG.Redo.slider.changeMultiples": "(es)Rehacer change to slider multiples restriction",
    "DG.Undo.slider.changeSpeed": "(es)Deshacer change to slider max frames/sec",
    "DG.Redo.slider.changeSpeed": "(es)Rehacer change to slider max frames/sec",
    "DG.Undo.slider.changeDirection": "(es)Deshacer change to slider animation direction",
    "DG.Redo.slider.changeDirection": "(es)Rehacer change to slider animation direction",
    "DG.Undo.slider.changeRepetition": "(es)Deshacer change to slider animation repetition",
    "DG.Redo.slider.changeRepetition": "(es)Rehacer change to slider animation repetition",
    "DG.Undo.graphComponent.create": "(es)Deshacer adding a graph",
    "DG.Redo.graphComponent.create": "(es)Rehacer adding a graph",
    "DG.Undo.dataContext.create": "(es)Deshacer creating a data set",
    "DG.Redo.dataContext.create": "(es)Rehacer creating a data set",
    "DG.Undo.data.deleteCases": "(es)Deshacer deleting cases",
    "DG.Redo.data.deleteCases": "(es)Rehacer deleting cases",
    "DG.Undo.component.close": "(es)Deshacer closing component",
    "DG.Redo.component.close": "(es)Rehacer closing component",
    "DG.Undo.component.minimize": "(es)Deshacer minimizing component",
    "DG.Redo.component.minimize": "(es)Rehacer minimizing component",
    "DG.Undo.dataContext.moveAttribute": "(es)Deshacer moving case table attribute",
    "DG.Redo.dataContext.moveAttribute": "(es)Rehacer moving case table attribute",
    "DG.DataContext.singleCaseName": "case",
    "DG.DataContext.pluralCaseName": "cases",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "a collection",
    "DG.DataContext.collapsedRowString": "%@1 of %@2",
    "DG.DataContext.noData": "No Data",
    "DG.DataContext.baseName": "Data_Set_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "The formula for attribute \"%@\" is not editable.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Create a new attribute to be able to specify a formula.",
    "DG.Formula.FuncCategoryArithmetic": "Arithmetic Functions",
    "DG.Formula.FuncCategoryConversion": "Other Functions",
    "DG.Formula.FuncCategoryDateTime": "Date/Time Functions",
    "DG.Formula.FuncCategoryLookup": "Lookup Functions",
    "DG.Formula.FuncCategoryOther": "Other Functions",
    "DG.Formula.FuncCategoryRandom": "Other Functions",
    "DG.Formula.FuncCategoryStatistical": "Statistical Functions",
    "DG.Formula.FuncCategoryString": "String Functions",
    "DG.Formula.FuncCategoryTrigonometric": "Trigonometric Functions",
    "DG.Formula.DateLongMonthJanuary": "enero",
    "DG.Formula.DateLongMonthFebruary": "febrero",
    "DG.Formula.DateLongMonthMarch": "marzo",
    "DG.Formula.DateLongMonthApril": "abril",
    "DG.Formula.DateLongMonthMay": "mayo",
    "DG.Formula.DateLongMonthJune": "junio",
    "DG.Formula.DateLongMonthJuly": "julio",
    "DG.Formula.DateLongMonthAugust": "agosto",
    "DG.Formula.DateLongMonthSeptember": "septiembre",
    "DG.Formula.DateLongMonthOctober": "octubre",
    "DG.Formula.DateLongMonthNovember": "noviembre",
    "DG.Formula.DateLongMonthDecember": "diciembre",
    "DG.Formula.DateShortMonthJanuary": "en",
    "DG.Formula.DateShortMonthFebruary": "feb",
    "DG.Formula.DateShortMonthMarch": "mzo",
    "DG.Formula.DateShortMonthApril": "abr",
    "DG.Formula.DateShortMonthMay": "may",
    "DG.Formula.DateShortMonthJune": "jun",
    "DG.Formula.DateShortMonthJuly": "jul",
    "DG.Formula.DateShortMonthAugust": "ago",
    "DG.Formula.DateShortMonthSeptember": "sep",
    "DG.Formula.DateShortMonthOctober": "oct",
    "DG.Formula.DateShortMonthNovember": "nov",
    "DG.Formula.DateShortMonthDecember": "dic",
    "DG.Formula.DateLongDaySunday": "domingo",
    "DG.Formula.DateLongDayMonday": "lunes",
    "DG.Formula.DateLongDayTuesday": "martes",
    "DG.Formula.DateLongDayWednesday": "miércoles",
    "DG.Formula.DateLongDayThursday": "jueves",
    "DG.Formula.DateLongDayFriday": "viernes",
    "DG.Formula.DateLongDaySaturday": "sabado",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Syntax error: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Incomplete expression",
    "DG.Formula.SyntaxErrorInvalidOperator": "invalid operator '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "invalid type(s) for '%@'",
    "DG.Formula.TypeError.description": "invalid type(s) for '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' is unrecognized",
    "DG.Formula.VarReferenceError.description": "variable '%@' is unrecognized",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "invalid reference to child attribute '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' is a child attribute that can only be referenced in an aggregate function",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' is unrecognized",
    "DG.Formula.FuncReferenceError.description": "function '%@()' is unrecognized",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' expects 1 argument",
    "DG.Formula.FuncArgsErrorSingle.description": "The '%@()' function expects 1 argument",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' expects %@ arguments",
    "DG.Formula.FuncArgsErrorPlural.description": "The '%@()' function expects %@ arguments",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' expects %@-%@ arguments",
    "DG.Formula.FuncArgsErrorRange.description": "The '%@()' function expects %@-%@ arguments",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "request pending...",
    "DG.Formula.PendingRequest.description": "request pending...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "request failed (%@)",
    "DG.Formula.FailedRequest.description": "request failed (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "boundaries pending...",
    "DG.Formula.PendingBoundaries.description": "boundaries pending...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "boundaries failed (%@)",
    "DG.Formula.FailedBoundaries.description": "boundaries failed (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': unrecognized data set",
    "DG.Formula.LookupDataSetError.description": "Data set '%@' is unrecognized",
    "DG.Formula.LookupAttrError.message": "'%@' not found in data set '%@'",
    "DG.Formula.LookupAttrError.description": "Attribute '%@' not found in data set '%@'",
    "DG.TableController.headerMenuItems.editAttribute": "Edit Attribute Properties...",
    "DG.TableController.headerMenuItems.editFormula": "Edit Formula...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Rerandomize",
    "DG.TableController.headerMenuItems.sortAscending": "Sort Ascending (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Sort Descending (9→0, Z→A)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Delete Attribute",
    "DG.TableController.newAttrDlg.defaultAttrName": "new_attr",
    "DG.TableController.newAttrDlg.attrNameHint": "Enter a name for the new attribute",
    "DG.TableController.newAttrDlg.formulaHint": "If desired, type a formula for computing values of this attribute",
    "DG.TableController.newAttrDlg.applyTooltip": "Define the new attribute using the name and (optional) formula",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Please enter a name for the new attribute",
    "DG.TableController.newAttrDialog.AttributesCategory": "Attributes",
    "DG.TableController.newAttrDialog.SpecialCategory": "Special",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Globals",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Constants",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Functions",
    "DG.TableController.renameAttributeInvalidMsg": "Attribute names may not be empty",
    "DG.TableController.renameAttributeInvalidDesc": "Please enter a valid attribute name",
    "DG.TableController.renameAttributeDuplicateMsg": "An attribute with that name already exists",
    "DG.TableController.renameAttributeDuplicateDesc": "Please enter a unique attribute name",
    "DG.TableController.deleteAttribute.confirmMessage": "Delete the attribute '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "This action cannot be undone.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Delete Attribute",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Cancel",
    "DG.TableController.deleteDataSet.confirmMessage": "Delete and destroy this data set: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "This action cannot be undone.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Delete Data Set",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Cancel",
    "DG.TableController.attrEditor.precisionHint": "Number of digits after decimal point",
    "DG.TableController.attrEditor.unitHint": "Unit of measure, if applicable",
    "DG.TableController.attrEditor.descriptionHint": "Describe the attribute",
    "DG.TableController.scoreAttrName": "score",
    "DG.TableController.setScoreDlg.applyTooltip": "Set the formula for the '%@' attribute",
    "DG.TableController.setScoreDlg.formulaHint": "Type a formula for computing values of this attribute",
    "DG.TableController.newAttributeTooltip": "Add a new attribute to this table",
    "DG.TableController.attributeEditor.title": "Attribute Properties",
    "DG.CaseTableDropTarget.dropMessage": "drop attribute to create new collection",
    "DG.CaseTable.defaultAttrName": "newAttr",
    "DG.CaseTable.indexColumnName": "index",
    "DG.CaseTable.indexColumnTooltip": "The row number (caseIndex) within the collection",
    "DG.CaseTable.indexMenu.insertCase": "Insert Case",
    "DG.CaseTable.indexMenu.insertCases": "Insert Cases...",
    "DG.CaseTable.indexMenu.deleteCase": "Delete Case",
    "DG.CaseTable.indexMenu.deleteCases": "Delete Cases",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "categorical",
    "DG.CaseTable.attribute.type.categorical": "categorical",
    "DG.CaseTable.attribute.type.numeric": "numeric",
    "DG.CaseTable.attribute.type.date": "date",
    "DG.CaseTable.attribute.type.qualitative": "qualitative",
    "DG.CaseTable.attribute.type.boundary": "boundary",
    "DG.CaseTable.attributeEditor.name": "name",
    "DG.CaseTable.attributeEditor.description": "description",
    "DG.CaseTable.attributeEditor.type": "type",
    "DG.CaseTable.attributeEditor.unit": "unit",
    "DG.CaseTable.attributeEditor.precision": "precision",
    "DG.CaseTable.attributeEditor.editable": "editable",
    "DG.CaseTable.insertCasesDialog.title": "Insert Cases",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# cases to insert:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "location:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "before",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "after",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Insert Cases",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Insert the specified number of cases",
    "DG.CaseTableController.allTables": "All tables",
    "DG.AttrFormView.attrNamePrompt": "Attribute Name:",
    "DG.AttrFormView.formulaPrompt": "Formula:",
    "DG.AttrFormView.operandMenuTitle": "--- Insert Value ---",
    "DG.AttrFormView.functionMenuTitle": "--- Insert Function ---",
    "DG.AttrFormView.applyBtnTitle": "Apply",
    "DG.AttrFormView.cancelBtnTitle": "Cancel",
    "DG.AttrFormView.cancelBtnTooltip": "Dismiss the dialog without making any changes",
    "DG.GuideConfigView.titlePrompt": "Guide Title",
    "DG.GuideConfigView.titleHint": "Activity Name",
    "DG.GuideConfigView.itemTitleHint": "Section Name",
    "DG.GuideConfigView.itemURLHint": "URL of section",
    "DG.GuideConfigView.okBtnTitle": "OK",
    "DG.GuideConfigView.okBtnToolTip": "Accept the Guide menu items",
    "DG.GuideConfigView.cancelBtnTitle": "Cancel",
    "DG.GuideConfigView.cancelBtnTooltip": "Dismiss the dialog without making any changes",
    "DG.GuideConfigView.httpWarning": "The URL must start with either http:// or https://",
    "DG.DataDisplayModel.rescaleToData": "Rescale to Data",
    "DG.DataDisplayModel.ShowConnectingLine": "Show Connecting Lines",
    "DG.DataDisplayModel.HideConnectingLine": "Hide Connecting Lines",
    "DG.AxisView.emptyGraphCue": "Haga clic aquí, o arrastrar un atributo aquí.",
    "DG.CellLinearAxisView.midPanelTooltip": "Drag to translate axis scale",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Drag to change axis lower bound",
    "DG.CellLinearAxisView.upperPanelTooltip": "Drag to change axis upper bound",
    "DG.PlotModel.mixup": "Mix Up the Plot",
    "DG.PlotModel.showCount": "Show Count",
    "DG.PlotModel.hideCount": "Hide Count",
    "DG.ScatterPlotModel.sumSquares": ",\nSum of squares = %@",
    "DG.ScatterPlotModel.rSquared": ",\nr^2 = %@",
    "DG.ScatterPlotModel.slopeIntercept": "%@ = %@ %@ %@ %@",
    "DG.ScatterPlotModel.infiniteSlope": "%@ = %@",
    "DG.ScatterPlotModel.slopeOnly": "slope = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "per year",
    "DG.ScatterPlotModel.daysLabel": "per day",
    "DG.ScatterPlotModel.hoursLabel": "per hour",
    "DG.ScatterPlotModel.minutesLabel": "per minute",
    "DG.ScatterPlotModel.secondsLabel": "per seconds",
    "DG.LegendView.attributeTooltip": "Click to change legend attribute",
    "DG.NumberToggleView.showAll": "Show All –",
    "DG.NumberToggleView.hideAll": "Hide All –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Last",
    "DG.NumberToggleView.showAllTooltip": "Click to show all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.hideAllTooltip": "Click to hide all cases\nClick parent case labels to toggle visibility",
    "DG.NumberToggleView.enableLastModeTooltip": "Click to show last parent case only",
    "DG.NumberToggleView.disableLastModeTooltip": "Click to exit last parent case mode",
    "DG.NumberToggleView.indexTooltip": "Click to toggle visibility",
    "DG.PlottedAverageAdornment.meanValueTitle": "mean=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "median=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SD, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "lower=%@\nQ1=%@\nmedian=%@\nQ3=%@\nupper=%@\nIQR=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Legend: %@",
    "DG.DataDisplayMenu.remove": "Remove Attribute",
    "DG.DataDisplayMenu.removeAttribute_x": "Remove X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Remove Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Remove Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Remove Legend: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Treat as Categorical",
    "DG.DataDisplayMenu.treatAsNumeric": "Treat as Numeric",
    "DG.DataDisplayMenu.hide": "Hide and Show",
    "DG.DataDisplayMenu.hideSelectedPlural": "Hide Selected Cases",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Hide Unselected Cases",
    "DG.DataDisplayMenu.hideSelectedSing": "Hide Selected Case",
    "DG.DataDisplayMenu.hideUnselectedSing": "Hide Unselected Case",
    "DG.DataDisplayMenu.enableNumberToggle": "Show Parent Visibility Toggles",
    "DG.DataDisplayMenu.disableNumberToggle": "Hide Parent Visibility Toggles",
    "DG.DataDisplayMenu.showAll": "Show All Cases",
    "DG.DataDisplayMenu.snapshot": "Make Snapshot",
    "DG.GraphView.replaceAttribute": "Replace %@ with %@",
    "DG.GraphView.addAttribute": "Add attribute %@",
    "DG.GraphView.addToEmptyPlace": "Create axis with %@",
    "DG.GraphView.addToEmptyX": "Create x-axis with %@",
    "DG.GraphView.dropInPlot": "Color points by values of %@",
    "DG.GraphView.zoomTip": "Double-click to zoom in.\nShift-double-click to zoom out",
    "DG.GraphView.rescale": "Rescale to data",
    "DG.AxisView.labelTooltip": "—Click to change %@ axis attribute",
    "DG.AxisView.vertical": "vertical",
    "DG.AxisView.horizontal": "horizontal",
    "DG.DataTip.connectingLine": "%@: %@\nwith %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Formula",
    "DG.PlottedValue.namePrompt": "Plotted Value",
    "DG.PlottedValue.formulaPrompt": "value =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Plotted Function",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Type an expression e.g. x*x/30 - 50",
    "DG.MapView.showGrid": "Show Grid",
    "DG.MapView.hideGrid": "Hide Grid",
    "DG.MapView.showPoints": "Show Points",
    "DG.MapView.hidePoints": "Hide Points",
    "DG.MapView.marqueeHint": "Marquee tool—drag select points in map",
    "DG.MapView.gridControlHint": "Change size of grid rectangles",
    "DG.Inspector.values": "Measure",
    "DG.Inspector.styles": "Format",
    "DG.Inspector.pointSize": "Point size:",
    "DG.Inspector.transparency": "Transparency:",
    "DG.Inspector.color": "Color:",
    "DG.Inspector.legendColor": "Legend color:",
    "DG.Inspector.backgroundColor": "Background\ncolor:",
    "DG.Inspector.stroke": "Stroke:",
    "DG.Inspector.rescale.toolTip": "Rescale display to show all the data",
    "DG.Inspector.mixUp.toolTip": "Mixup all the points",
    "DG.Inspector.hideShow.toolTip": "Show all cases or hide selected/unselected cases",
    "DG.Inspector.delete.toolTip": "Delete selected or unselected cases",
    "DG.Inspector.sliderValues.toolTip": "Set slider animation direction, speed, …",
    "DG.Inspector.webViewEditURL.toolTip": "Edit the URL of the displayed web page",
    "DG.Inspector.selection.selectAll": "Select All Cases",
    "DG.Inspector.selection.deleteSelectedCases": "Delete Selected Cases",
    "DG.Inspector.selection.deleteUnselectedCases": "Delete Unselected Cases",
    "DG.Inspector.deleteAll": "Delete All Cases",
    "DG.Inspector.deleteDataSet": "Delete and Destroy Data Set",
    "DG.Inspector.displayValues.toolTip": "Change what is shown along with the points",
    "DG.Inspector.displayStyles.toolTip": "Change the appearance of the display",
    "DG.Inspector.makeImage.toolTip": "Save the image as a PNG file",
    "DG.Inspector.displayShow": "Show …",
    "DG.Inspector.colorPicker.more": "more",
    "DG.Inspector.colorPicker.less": "less",
    "DG.Inspector.graphTransparency": "Transparent",
    "DG.Inspector.graphCount": "Count",
    "DG.Inspector.graphPercent": "Percent",
    "DG.Inspector.graphRow": "Row",
    "DG.Inspector.graphColumn": "Column",
    "DG.Inspector.graphCell": "Cell",
    "DG.Inspector.graphConnectingLine": "Connecting Lines",
    "DG.Inspector.graphMovableLine": "Movable Line",
    "DG.Inspector.graphInterceptLocked": "Intercept Locked",
    "DG.Inspector.graphPlottedFunction": "Plotted Function",
    "DG.Inspector.graphSquares": "Squares of Residuals",
    "DG.Inspector.graphLSRL": "Least Squares Line",
    "DG.Inspector.graphMovableValue": "Movable Value",
    "DG.Inspector.graphAdd": "Add",
    "DG.Inspector.graphRemove": "Remove",
    "DG.Inspector.graphPlottedMean": "Mean",
    "DG.Inspector.graphPlottedMedian": "Median",
    "DG.Inspector.graphPlottedStDev": "Standard Deviation",
    "DG.Inspector.graphPlottedIQR": "Interquartile Range",
    "DG.Inspector.graphPlottedBoxPlot": "Box Plot",
    "DG.Inspector.graphPlottedValue": "Plotted Value",
    "DG.Inspector.attributes.toolTip": "Make new attributes. Export case data.",
    "DG.Inspector.resize.toolTip": "Resize all columns to fit data",
    "DG.Inspector.newAttribute": "Nueva variable en %@...",
    "DG.Inspector.randomizeAllAttributes": "Aleatorizar todo de nuevo",
    "DG.Inspector.exportCaseData": "Exportación de datos...",
    "DG.Inspector.mapGrid": "Cuadrícula",
    "DG.Inspector.mapPoints": "Puntos",
    "DG.Inspector.mapLines": "Las líneas que conectan",
    "DG.GameController.continuityError": "En este momento, después de las columnas en la tabla de casos se han reordenado, los nuevos datos pueden no ser aceptadas.",
    "DG.GameView.loading": "Cargando",
    "DG.GameView.loadError": "Si puede ver este texto, la carga de la URL anterior puede haber fallado. Puede comprobar el enlace en otra pestaña del navegador o informar del error ahttp://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "¿Seguro?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Sí, cerrarla",
    "DG.Component.closeComponent.cancelButtonTitle": "Cancelar",
    "DG.GameController.confirmCloseDescription": "Si cierra esto, no puede ser capaz de añadir más datos",
    "DG.WebView.defaultTitle": "Web Page",
    "DG.mainPage.exceptionMessage": "An error has occurred that may affect how this program behaves. You may wish to reload this page after you save your work. (Error: %@)",
    "DG.fileMenu.provider.examples.displayName": "Example Documents",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "Open a plugin component",
    "DG.Undo.graph.showMovablePoint": "Undo showing movable point",
    "DG.Redo.graph.showMovablePoint": "Redo showing movable point",
    "DG.Undo.graph.hideMovablePoint": "Undo hiding movable point",
    "DG.Redo.graph.hideMovablePoint": "Redo hiding movable point",
    "DG.Undo.graph.moveMovablePoint": "Undo moving movable point",
    "DG.Redo.graph.moveMovablePoint": "Redo moving movable point",
    "DG.DataDisplayMenu.copyAsImage": "Open in Draw Tool",
    "DG.DataDisplayMenu.exportImage": "Export Image...",
    "DG.DataDisplayMenu.imageOfTitle": "Image of %@",
    "DG.Inspector.graphMovablePoint": "Movable Point",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Open case table for this data set",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Create a new data set",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Delete and destroy this data set",
    "DG.Undo.graph.showAsBarChart": "Undo fusing dots into bars",
    "DG.Redo.graph.showAsBarChart": "Redo fusing dots into bars",
    "DG.Undo.graph.showAsDotChart": "Undo dispersing bars into dots",
    "DG.Redo.graph.showAsDotChart": "Redo dispersing bars into dots",
    "DG.CountAxisView.countLabel": "Count",
    "DG.CountAxisView.countLabelDescription": "Number of cases in the bar along this axis",
    "DG.CountAxisView.percentLabel": "Percent",
    "DG.CountAxisView.percentLabelDescription": "Percent of cases in the bar along this axis",
    "DG.BarChartModel.cellTipPlural": "%@ of %@ %@ (%@%) are %@",
    "DG.BarChartModel.cellTipSingular": "%@ of %@ %@ (%@%) is %@",
    "DG.Inspector.configuration": "Configuration",
    "DG.Inspector.displayConfiguration.toolTip": "Configure the display differently",
    "DG.Inspector.displayScale": "Scale …",
    "DG.Inspector.graphBarChart": "Fuse Dots into Bars",
    "DG.Locale.name.de": "German",
    "DG.Locale.name.en": "English",
    "DG.Locale.name.es": "Spanish",
    "DG.Locale.name.he": "Hebrew",
    "DG.Locale.name.tr": "Turkish",
    "DG.Locale.name.zh": "Chinese"
});
