SC.stringsFor("pt-BR", {
    "DG.fileMenu.menuItem.newDocument": "Novo",
    "DG.fileMenu.menuItem.openDocument": "Abrir...",
    "DG.fileMenu.menuItem.closeDocument": "Fechar",
    "DG.fileMenu.menuItem.importFile": "Importar...",
    "DG.fileMenu.menuItem.revertTo": "Desfazer...",
    "DG.fileMenu.menuItem.revertToOpened": "Retomar a versão original",
    "DG.fileMenu.menuItem.revertToShared": "Arquivo compartilhado",
    "DG.fileMenu.menuItem.saveDocument": "Salvar...",
    "DG.fileMenu.menuItem.copyDocument": "Criar uma cópia",
    "DG.fileMenu.menuItem.share": "Compartilhar...",
    "DG.fileMenu.menuItem.shareGetLink": "Link para compartilhar o arquivo",
    "DG.fileMenu.menuItem.shareUpdate": "Atualizar o arquivo compartilhado",
    "DG.fileMenu.menuItem.renameDocument": "Renomear",
    "DG.main.userEntryView.title": "O que você gostaria de fazer?",
    "DG.main.userEntryView.openDocument": "Abrir um arquivo ou um exemplo",
    "DG.main.userEntryView.newDocument": "Novo arquivo",
    "DG.mainPage.mainPane.undoButton.title": "Desfazer",
    "DG.mainPage.mainPane.undoButton.toolTip": "Desfazer a última ação",
    "DG.mainPage.mainPane.redoButton.title": "Refazer",
    "DG.mainPage.mainPane.redoButton.toolTip": "Refazer a última ação desfeita",
    "DG.mainPage.mainPane.versionString": "Versão %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "Infelizmente, o CODAP não é compartível com o seu navegador. Abra-o exclusivamente em uma das opções: Firefox 46, Chrome 50, Microsoft Edge 14, Safaria 10, ou em versões superiores.",
    "DG.mainPage.titleBar.saved": "Documento Salvo!",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "Versão %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "Versão %@ (%@.srri10)",
    "DG.AppController.resetData.title": "Apagar os Dados...",
    "DG.AppController.resetData.toolTip": "Apagar todos os dados deste arquivo",
    "DG.AppController.resetData.warnMessage": "Você realmente quer apagar todos os dados deste arquivo?",
    "DG.AppController.resetData.warnDescription": "Esta ação não poderá ser desfeita.",
    "DG.AppController.resetData.okButtonTitle": "Sim, delete os dados",
    "DG.AppController.resetData.cancelButtonTitle": "Não, mantenha os dados",
    "DG.AppController.closeDocument.warnMessage": "Sair sem salvar?",
    "DG.AppController.closeDocument.warnDescription": "Esta ação não poderá ser desfeita.",
    "DG.AppController.closeDocument.okButtonTitle": "Fechar",
    "DG.AppController.closeDocument.cancelButtonTitle": "Cancelar",
    "DG.AppController.beforeUnload.confirmationMessage": "O arquivo contém mudanças não salvas.",
    "DG.AppController.optionMenuItems.reportProblem": "Enviar Feedback...",
    "DG.AppController.optionMenuItems.viewWebPage": "Disponibilizar página web...",
    "DG.AppController.optionMenuItems.configureGuide": "Configurar Instruções...",
    "DG.AppController.optionMenuItems.about": "Sobre o CODAP...",
    "DG.AppController.optionMenuItems.releaseNotes": "O que é novo?",
    "DG.AppController.optionMenuItems.help": "Materiais de Apoio...",
    "DG.AppController.optionMenuItems.toWebSite": "O Projeto CODAP...",
    "DG.AppController.exportDocument.prompt": "Nome do arquivo:",
    "DG.AppController.exportCaseData.prompt": "Exportar os caso dados para:",
    "DG.AppController.exportDocument.exportTitle": "Exportar",
    "DG.AppController.exportDocument.exportTooltip": "Exportar os dados para um arquivo",
    "DG.AppController.exportDocument.cancelTitle": "Cancelar",
    "DG.AppController.exportDocument.cancelTooltip": "Cancelar a exportação",
    "DG.AppController.feedbackDialog.dialogTitle": "Enviar Feedback",
    "DG.AppController.feedbackDialog.subHeaderText": "Seu feedback é importante para nós!",
    "DG.AppController.feedbackDialog.messageText": "Por favor, nos ajude a continuar melhorando o CODAP. Perguntas, comentário sobre erros e melhorias são bem-vindos. Obrigado!",
    "DG.AppController.feedbackDialog.subjectHint": "Qual o assunto do seu feedback",
    "DG.AppController.feedbackDialog.feedbackHint": "Detalhes",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "Enviar",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "Cancelar",
    "DG.AppController.showWebSiteTitle": "Sobre o CODAP",
    "DG.AppController.showHelpTitle": "Ajuda com o CODAP",
    "DG.AppController.showAboutTitle": "Sobre o CODAP",
    "DG.AppController.showReleaseNotesTitle": "Notas de Versão do CODAP",
    "DG.AppController.dropFile.error": "Erro: %@1",
    "DG.AppController.dropFile.unknownFileType": "Você não pode importar este tipo de arquivo",
    "DG.AppController.validateDocument.missingRequiredProperty": "Propriedade solicitada não foi encontrada: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "Propriedade de nível superior inesperada: %@1",
    "DG.AppController.validateDocument.unresolvedID": "Identidade não resolvida: %@1",
    "DG.AppController.validateDocument.parseError": "Erro de conversão no arquivo: %@1",
    "DG.AppController.validateDocument.invalidDocument": "Aquivo JSON inválido: %@1",
    "DG.AppController.openDocument.error.general": "Não foi possível abrir o arquivo",
    "DG.AppController.openDocument.error.invalid_format": "CODAP não pode acessar este tipo de arquivo",
    "DG.AppController.createDataSet.initialAttribute": "NomeDaAtributo",
    "DG.AppController.createDataSet.name": "Nova Base de Dados",
    "DG.AppController.createDataSet.collectionName": "Casos",
    "DG.AppController.caseTableMenu.newDataSet": "-- nova --",
    "DG.SingleTextDialog.okButton.title": "OK",
    "DG.SingleTextDialog.cancelButton.title": "Cancelar",
    "DG.SingleTextDialog.cancelButton.toolTip": "Dispensar a caixa de diálogo sem fazer alteraçōes",
    "DG.DocumentController.calculatorTitle": "Calculadora",
    "DG.DocumentController.caseTableTitle": "Tabela de Casos",
    "DG.DocumentController.graphTitle": "Gráfico",
    "DG.DocumentController.sliderTitle": "Controle Deslizante",
    "DG.DocumentController.textTitle": "Caixa de Texto",
    "DG.DocumentController.mapTitle": "Mapa",
    "DG.DocumentController.enterURLPrompt": "Insira aqui a URL da página web para exibi-la no CODAP",
    "DG.DocumentController.enterViewWebPageOKTip": "Exiba a página web dada pela URL",
    "DG.Document.defaultDocumentName": "Arquivo sem nome",
    "DG.Document.documentName.toolTip": "Clique para editar o nome do arquivo",
    "DG.SliderView.thumbView.toolTip": "Arraste para mudar o valor do controle deslizante",
    "DG.SliderView.startButton.toolTip": "Começe/Pare a animação",
    "DG.ToolButtonData.tableButton.title": "Tabelas",
    "DG.ToolButtonData.tableButton.toolTip": "Abrir uma tabela de casos para cada conjunto de dados(ctrl-alt-t)",
    "DG.ToolButtonData.graphButton.title": "Gráfico",
    "DG.ToolButtonData.graphButton.toolTip": "Faça um gráfico (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "Controle Deslizante",
    "DG.ToolButtonData.sliderButton.toolTip": "Faça um controle deslizante (Ctrl Alt S)",
    "DG.ToolButtonData.calcButton.title": "Calculadora",
    "DG.ToolButtonData.calcButton.toolTip": "Abre/Feche a calculadora (Ctrl Alt C)",
    "DG.ToolButtonData.textButton.title": "Texto",
    "DG.ToolButtonData.textButton.toolTip": "Abra uma Caixa de Texto (Ctrl Alt Shift T)",
    "DG.ToolButtonData.mapButton.title": "Mapa",
    "DG.ToolButtonData.mapButton.toolTip": "Faça um Mapa",
    "DG.ToolButtonData.optionMenu.title": "Opções",
    "DG.ToolButtonData.optionMenu.toolTip": "Mostre uma página Web, ou instruções...",
    "DG.ToolButtonData.tileListMenu.title": "Objetos",
    "DG.ToolButtonData.tileListMenu.toolTip": "Mostre a lista de objetos no arquivo",
    "DG.ToolButtonData.guideMenu.title": "Roteiro",
    "DG.ToolButtonData.guideMenu.toolTip": "Mostre as instruções para esta atividade",
    "DG.ToolButtonData.guideMenu.showGuide": "Mostrar o Roteiro",
    "DG.ToolButtonData.help.title": "Ajuda",
    "DG.ToolButtonData.help.toolTip": "Conheça e Ajude o projeto CODAP",
    "DG.Slider.multiples": "Somente múltiplos de:",
    "DG.Slider.maxPerSecond": "Máximo de Frames/s na Animação:",
    "DG.Slider.direction": "Direção da animação:",
    "DG.Slider.backAndForth": "Vai e volta",
    "DG.Slider.lowToHigh": "Do menor p/ o maior",
    "DG.Slider.highToLow": "Do maior p/ o menor",
    "DG.Slider.mode": "Repetição da Animação:",
    "DG.Slider.nonStop": "Sem parar",
    "DG.Slider.onceOnly": "Só uma vez",
    "DG.Undo.exceptionOccurred": "Um erro ocorreu ao tentar desfazer.",
    "DG.Redo.exceptionOccurred": "Um erro ocorreu ao tentar refazer.",
    "DG.Undo.componentMove": "Desfazer movendo componente",
    "DG.Redo.componentMove": "Refazer movendo componente",
    "DG.Undo.componentResize": "Desfazer redimensionando componente",
    "DG.Redo.componentResize": "Refazer redimensionando componente",
    "DG.Undo.axisDilate": "Desfazer: redimensionando o eixo",
    "DG.Redo.axisDilate": "Refazer: redimensionando o eixo",
    "DG.Undo.axisRescaleFromData": "Desfazer redimensionando o eixo",
    "DG.Redo.axisRescaleFromData": "Refazer: redimensionando o eixo",
    "DG.Undo.axisDrag": "Desfazer arrastando o eixo",
    "DG.Redo.axisDrag": "Refazer arrastando o eixo",
    "DG.Undo.axisAttributeChange": "Desfazer: alterando o atributo do eixo",
    "DG.Redo.axisAttributeChange": "Refazer: alterando o atributo do eixo",
    "DG.Undo.axisAttributeAdded": "Desfazer: adicionar uma atributo ao eixo",
    "DG.Redo.axisAttributeAdded": "Refazer: adicionar uma atributo ao eixo",
    "DG.Undo.toggleComponent.add.calcView": "Desfazer: mostrando a calculadora",
    "DG.Redo.toggleComponent.add.calcView": "Refazer mostrando a calculadora",
    "DG.Undo.toggleComponent.delete.calcView": "Desfazer: escondendo a calculatora",
    "DG.Redo.toggleComponent.delete.calcView": "Refazer: escondendo a calculadora",
    "DG.Undo.caseTable.open": "Desfazer: mostrando tabelas de casos",
    "DG.Redo.caseTable.open": "Refazer: mostrando tabelas de casos",
    "DG.Undo.caseTable.editAttribute": "Desfazer: editando atributo da tabela de casos",
    "DG.Redo.caseTable.editAttribute": "Refazer: editando atributo da tabela de casos",
    "DG.Undo.caseTable.createAttribute": "Desfazer: criando atributo da tabela de casos",
    "DG.Redo.caseTable.createAttribute": "Refazer: criando atributo da tabela de casos",
    "DG.Undo.caseTable.editAttributeFormula": "Desfazer: fórmula de atributo da tabela de casos",
    "DG.Redo.caseTable.editAttributeFormula": "Refazer: fórmula de atributo da tabela de casos",
    "DG.Undo.caseTable.editCellValue": "Desfazer: editando o valor da célula da tabela de casos",
    "DG.Redo.caseTable.editCellValue": "Refazer: editando o valor da célula da tabela de casos",
    "DG.Undo.caseTable.sortCases": "Desfazer a classificação de casos",
    "DG.Redo.caseTable.sortCases": "Refazer a classificaçāo de casos",
    "DG.Undo.caseTable.deleteAttribute": "Desfazer: excluindo o atributo da tabela de casos",
    "DG.Redo.caseTable.deleteAttribute": "Refazer: excluindo o atributo da tabela de casos",
    "DG.Undo.caseTable.createCollection": "Desfazer: criar nova coleção",
    "DG.Redo.caseTable.createCollection": "Refazer: criar nova coleção",
    "DG.Undo.caseTable.collectionNameChange": "Desfazer: renomear a coleção",
    "DG.Redo.caseTable.collectionNameChange": "Refazer: renomear a coleção",
    "DG.Undo.caseTable.createNewCase": "Desfazer: criação de um caso novo",
    "DG.Redo.caseTable.createNewCase": "Refazer: criação de um caso novo",
    "DG.Undo.caseTable.insertCases": "Desfazer: inserir casos",
    "DG.Redo.caseTable.insertCases": "Refazer: inserir casos",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "Desfazer: alternar para expandir/ recolher todos",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "Refazer: alternar para expandir/ recolher todos",
    "DG.Undo.caseTable.expandCollapseOneCase": "Desfazer: expandir ou recolher de um grupo",
    "DG.Redo.caseTable.expandCollapseOneCase": "Refazer: expandir ou derrubar um grupo",
    "DG.Undo.caseTable.resizeColumns": "Desfazer: redimensionar automaticamente todas as colunas",
    "DG.Redo.caseTable.resizeColumns": "Refazer: redimensionar automaticamente todas as colunas",
    "DG.Undo.document.share": "Desfazer o compartilhamnto do documento",
    "DG.Redo.document.share": "Refazer o compartilhamento do documento",
    "DG.Undo.document.unshare": "Desfazer: pare de compartilhar o documento",
    "DG.Redo.document.unshare": "Refazer: pare de compartilhar o documento",
    "DG.Undo.game.add": "Desfazer: adicionar um jogo ao documento",
    "DG.Redo.game.add": "Refazer: adicionar um jogo ao documento",
    "DG.Undo.graph.showCount": "Desfazer: mostrando a contagem",
    "DG.Redo.graph.showCount": "Refazer: mostrando a contagem",
    "DG.Undo.graph.hideCount": "Desfazer: escondendo a contagem",
    "DG.Redo.graph.hideCount": "Refazer: escondendo a contagem",
    "DG.Undo.graph.showPercent": "Desfazer: mostrando a porcentagem",
    "DG.Redo.graph.showPercent": "Refazer: mostrando a porcentagem",
    "DG.Undo.graph.hidePercent": "Desfazer: escondendo a porcentagem",
    "DG.Redo.graph.hidePercent": "Refazer: escondendo a porcentagem",
    "DG.Undo.graph.showMovableLine": "Desfazer: mostrando a linha móvel",
    "DG.Redo.graph.showMovableLine": "Refazer: mostrando a linha móvel",
    "DG.Undo.graph.hideMovableLine": "Desfazer: escondendo a linha móvel",
    "DG.Redo.graph.hideMovableLine": "Refazer: escondendo a linha móvel",
    "DG.Undo.graph.lockIntercept": "Desfazer o bloqueio da linha de  interceptação",
    "DG.Redo.graph.lockIntercept": "Refazer o bloqueio da linha de interceptação",
    "DG.Undo.graph.unlockIntercept": "Desfazer: desbloqueando a linha de interceptação",
    "DG.Redo.graph.unlockIntercept": "Refazer: desbloqueando a linha de interceptação",
    "DG.Undo.graph.showPlotFunction": "Desfazer: mostrando a função plotada",
    "DG.Redo.graph.showPlotFunction": "Refazer: mostrando a função plotada",
    "DG.Undo.graph.hidePlotFunction": "Desfazer: escondendo a função plotada",
    "DG.Redo.graph.hidePlotFunction": "Refazer: escondendo a função plotada",
    "DG.Undo.graph.changePlotFunction": "Desfazer: alterando a função plotada",
    "DG.Redo.graph.changePlotFunction": "Refazer: alterando a função plotada",
    "DG.Undo.graph.showPlotValue": "Desfazer: mostrando o valor plotado",
    "DG.Redo.graph.showPlotValue": "Refazer: mostrando o valor plotado",
    "DG.Undo.graph.hidePlotValue": "Desfazer: ocultando o valor plotado",
    "DG.Redo.graph.hidePlotValue": "Refazer: ocultando o valor plotado",
    "DG.Undo.graph.changePlotValue": "Desfazer: alterar o valor plotado",
    "DG.Redo.graph.changePlotValue": "Refazer: alterar o valor plotado",
    "DG.Undo.graph.showConnectingLine": "Desfazer: mostrando a linha de conexão",
    "DG.Redo.graph.showConnectingLine": "Refazer: mostrando a linha de conexão",
    "DG.Undo.graph.hideConnectingLine": "Desfazer: ocultando a linha de conexão",
    "DG.Redo.graph.hideConnectingLine": "Refazer: ocultando a linha de conexão",
    "DG.Undo.graph.showLSRL": "Desfazer: mostrando a linha dos mínimos quadrados",
    "DG.Redo.graph.showLSRL": "Refazer: mostrando a linha dos mínimos quadrados",
    "DG.Undo.graph.hideLSRL": "Desfazer: ocultar a linha dos mínimos quadrados",
    "DG.Redo.graph.hideLSRL": "Refazer: ocultar a linha dos mínimos quadrados",
    "DG.Undo.graph.showSquares": "Desfazer: mostrando quadrados",
    "DG.Redo.graph.showSquares": "Refazer: mostrando quadrados",
    "DG.Undo.graph.hideSquares": "Desfazer: escondendo quadrados",
    "DG.Redo.graph.hideSquares": "Refazer: mostrando quadrados",
    "DG.Undo.graph.showPlottedMean": "Desfazer: mostrando média",
    "DG.Redo.graph.showPlottedMean": "Refazer: mostrando média",
    "DG.Undo.graph.hidePlottedMean": "Desfazer: esconder o resultado",
    "DG.Redo.graph.hidePlottedMean": "Refazer: esconder o resultado",
    "DG.Undo.graph.showPlottedMedian": "Desfazer: mostrando a média",
    "DG.Redo.graph.showPlottedMedian": "Refazer: mostrando a média",
    "DG.Undo.graph.hidePlottedMedian": "Desfazer: ocultar a média",
    "DG.Redo.graph.hidePlottedMedian": "Refazer: ocultar a média",
    "DG.Undo.graph.showPlottedStDev": "Desefazer: mostrando o desvio padrão",
    "DG.Redo.graph.showPlottedStDev": "Refazer: mostrando o desvio padrão",
    "DG.Undo.graph.hidePlottedStDev": "Desfazer: esconderndo o desvio padrão",
    "DG.Redo.graph.hidePlottedStDev": "Refazer: escondendo o desvio padrão",
    "DG.Undo.graph.showPlottedIQR": "Desfazer: mostrando io ntervalo interquartil",
    "DG.Redo.graph.hidePlottedIQR": "Refazer: escondendo o intervalo interquartil",
    "DG.Undo.graph.hidePlottedIQR": "Desfazer: escondendo o intervalo interquartil",
    "DG.Redo.graph.showPlottedIQR": "Refazer: mostrando o intervalo interquartil",
    "DG.Undo.graph.addMovableValue": "Desfazer: adicionando o valor móvel",
    "DG.Redo.graph.addMovableValue": "Refazer: adicionando o valor móvel",
    "DG.Undo.graph.removeMovableValue": "Desfazer: removendo o valor móvel",
    "DG.Redo.graph.removeMovableValue": "Refazer: removendo o valor móvel",
    "DG.Undo.graph.moveMovableValue": "Desfazer: movendo o valor móvel",
    "DG.Redo.graph.moveMovableValue": "Refazer: movendo o valor móvel",
    "DG.Undo.graph.changePointColor": "Desfazer: mudando as cores dos dados",
    "DG.Redo.graph.changePointColor": "Refazer: mudando as cores dos dados",
    "DG.Undo.graph.changeStrokeColor": "Desefazer: alterando a cor do traço",
    "DG.Redo.graph.changeStrokeColor": "Refazer: alterando a cor do traço",
    "DG.Undo.graph.changePointSize": "Desfazer: mudando o tamanho do ponto",
    "DG.Redo.graph.changePointSize": "Refazer: mudando o tamanho do ponto",
    "DG.Undo.graph.changeAttributeColor": "Desfazer: alterando a cor do atributo",
    "DG.Redo.graph.changeAttributeColor": "Refazer: alterando a cor do atributo",
    "DG.Undo.graph.changeBackgroundColor": "Desfazer: alterando a cor de fundo do gráfico",
    "DG.Redo.graph.changeBackgroundColor": "Refazer: alterando a cor de fundo do gráfico",
    "DG.Undo.graph.toggleTransparent": "Desfazer: alternando a transparência do gráfico",
    "DG.Redo.graph.toggleTransparent": "Refazer: alternando a transparência do gráfico",
    "DG.Undo.guide.show": "Desfazer: mostrando o guia",
    "DG.Redo.guide.show": "Refazer: mostrando o guia",
    "DG.Undo.guide.navigate": "Desfazer: mudando a página do guia",
    "DG.Redo.guide.navigate": "Refazer: mudando a página do guia",
    "DG.Undo.hideSelectedCases": "Desfazer: escondendo dados selecionados",
    "DG.Redo.hideSelectedCases": "Refazer: escondendo dados selecionados",
    "DG.Undo.hideUnselectedCases": "Desfazer: ocultando os dados não selecionados",
    "DG.Redo.hideUnselectedCases": "Refazer: ocultando casos não selecionados",
    "DG.Undo.enableNumberToggle": "Desfazer: mostrar alternâncias de visibilidade dos pais",
    "DG.Redo.enableNumberToggle": "Refazer: mostrar alternâncias de visibilidade dos pais",
    "DG.Undo.disableNumberToggle": "Desfazer: ocultar alternância de visibilidade dos pais",
    "DG.Redo.disableNumberToggle": "Refazer: ocultar alternâncias de visibilidade dos pais",
    "DG.Undo.interactiveUndoableAction": "Desfazer uma ação no modo interativo",
    "DG.Redo.interactiveUndoableAction": "Refazer uma ação no modo interativo",
    "DG.Undo.showAllCases": "Desfazer: mostrando todos os dados",
    "DG.Redo.showAllCases": "Refazer: mostrando todos os dados",
    "DG.Undo.map.create": "Desfazer: adicionando o mapa",
    "DG.Redo.map.create": "Refazer: adicionando o mapa",
    "DG.Undo.map.fitBounds": "Desfazer: redimensionando o mapa",
    "DG.Redo.map.fitBounds": "Refazer: redimensionamento o mapa",
    "DG.Undo.map.pan": "Desfazer o mapa panorâmico",
    "DG.Redo.map.pan": "Refazer o mapa panorâmico",
    "DG.Undo.map.zoom": "Desfazer: ampliar o mapa",
    "DG.Redo.map.zoom": "Refazer: ampliar o mapa",
    "DG.Undo.map.showGrid": "Desfazer: mostrar rede no mapa",
    "DG.Redo.map.showGrid": "Refazer: mostrar rede no mapa",
    "DG.Undo.map.hideGrid": "Desfazer: ocultar rede no mapa",
    "DG.Redo.map.hideGrid": "Refazer: ocultar grade no mapa",
    "DG.Undo.map.changeGridSize": "Desfazer: alterando o tamanho da rede do mapa",
    "DG.Redo.map.changeGridSize": "Refazer: alterando o tamanho da rede do mapa",
    "DG.Undo.map.showPoints": "Desfazer: exibindo os pontos no mapa",
    "DG.Redo.map.showPoints": "Refazer: exibindo os pontos no mapa",
    "DG.Undo.map.hidePoints": "Desfazer: ocultando os pontos no mapa",
    "DG.Redo.map.hidePoints": "Refazer: ocultando os pontos no mapa",
    "DG.Undo.map.showLines": "Desfazer: exibindo as linhas no mapa",
    "DG.Redo.map.showLines": "Refazer: exibindo as linhas no mapa",
    "DG.Undo.map.hideLines": "Desfazer: ocultando as linhas no mapa",
    "DG.Redo.map.hideLines": "Refazer: ocultando  as linhas no mapa",
    "DG.Undo.map.changeBaseMap": "Desfazer: alterando o plano de fundo do mapa",
    "DG.Redo.map.changeBaseMap": "Refazer: alterando o plano de fundo do mapa",
    "DG.Undo.textComponent.create": "Desfazer: adicionando o bloco de texto",
    "DG.Redo.textComponent.create": "Refazer: adicionando o bloco de texto",
    "DG.Undo.textComponent.edit": "Desfazer a edição de texto",
    "DG.Redo.textComponent.edit": "Refazer: editando o texto",
    "DG.Undo.sliderComponent.create": "Desfazer: adicionando um controle deslizante",
    "DG.Redo.sliderComponent.create": "Refazer: adicionando um controle deslizante",
    "DG.Undo.slider.change": "Desfazer: alterando o valor do controle deslizante",
    "DG.Redo.slider.change": "Refazer: alterando o valor do controle deslizante",
    "DG.Undo.slider.changeMultiples": "Desfazer: alterando a restrição de múltiplos do controle deslizante",
    "DG.Redo.slider.changeMultiples": "Refazer: alterando a restrição de múltiplos do controle deslizante",
    "DG.Undo.slider.changeSpeed": "Desfazer: alterando para quadros máximos do controle deslizante/seg",
    "DG.Redo.slider.changeSpeed": "Refazer: alterando para quadros máximos do controle deslizante/seg",
    "DG.Undo.slider.changeDirection": "Desfazer: alterando a direção da animação do controle deslizante",
    "DG.Redo.slider.changeDirection": "Refazer: alterando a direção da animação do controle deslizante",
    "DG.Undo.slider.changeRepetition": "Desfazer: alterando a repetição da animação do controle deslizante",
    "DG.Redo.slider.changeRepetition": "Refazer: alteranndo a repetição da animação do controle deslizante",
    "DG.Undo.graphComponent.create": "Desfazer: adicionando um gráfico",
    "DG.Redo.graphComponent.create": "Refazer: adicionando um gráfico",
    "DG.Undo.dataContext.create": "Desfazer: criando um conjunto de dados",
    "DG.Redo.dataContext.create": "Refazer: criando um conjunto de dados",
    "DG.Undo.data.deleteCases": "Desfazer: deletando casos",
    "DG.Redo.data.deleteCases": "Refazer: deletando casos",
    "DG.Undo.component.close": "Desfazer: fechando o componente",
    "DG.Redo.component.close": "Refazer: fechando o componente",
    "DG.Undo.component.minimize": "Desfazer: minimizando o componete",
    "DG.Redo.component.minimize": "Refazer: minimizando o componente",
    "DG.Undo.dataContext.moveAttribute": "Desfazer: movendo o atributo da tabela de dados",
    "DG.Redo.dataContext.moveAttribute": "Refazer: movendo o atributo da tabela de dados",
    "DG.DataContext.singleCaseName": "caso",
    "DG.DataContext.pluralCaseName": "casos",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "uma coleção",
    "DG.DataContext.collapsedRowString": "%@1 de %@2",
    "DG.DataContext.noData": "Sem dados",
    "DG.DataContext.baseName": "Conjunto de dados_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "A fórmula para a atributo \"%@\" não é editável.",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "Criar uma nova atributo para especificar uma fórmula.",
    "DG.Formula.FuncCategoryArithmetic": "Funções Aritméticas",
    "DG.Formula.FuncCategoryConversion": "Outras Funções",
    "DG.Formula.FuncCategoryDateTime": "Funções de Data e Hora",
    "DG.Formula.FuncCategoryLookup": "Funções de Busca",
    "DG.Formula.FuncCategoryOther": "Outras Funções",
    "DG.Formula.FuncCategoryRandom": "Outras Funções",
    "DG.Formula.FuncCategoryStatistical": "Funções Estatísticas",
    "DG.Formula.FuncCategoryString": "Funções de Texto",
    "DG.Formula.FuncCategoryTrigonometric": "Funções Trigonométricas",
    "DG.Formula.DateLongMonthJanuary": "Janeiro",
    "DG.Formula.DateLongMonthFebruary": "Fevereiro",
    "DG.Formula.DateLongMonthMarch": "Março",
    "DG.Formula.DateLongMonthApril": "Abril",
    "DG.Formula.DateLongMonthMay": "Maio",
    "DG.Formula.DateLongMonthJune": "Junho",
    "DG.Formula.DateLongMonthJuly": "Julho",
    "DG.Formula.DateLongMonthAugust": "Agosto",
    "DG.Formula.DateLongMonthSeptember": "Setembro",
    "DG.Formula.DateLongMonthOctober": "Outubro",
    "DG.Formula.DateLongMonthNovember": "Novembro",
    "DG.Formula.DateLongMonthDecember": "Dezembro",
    "DG.Formula.DateShortMonthJanuary": "Jan",
    "DG.Formula.DateShortMonthFebruary": "Fev",
    "DG.Formula.DateShortMonthMarch": "Mar",
    "DG.Formula.DateShortMonthApril": "Abr",
    "DG.Formula.DateShortMonthMay": "Maio",
    "DG.Formula.DateShortMonthJune": "Jun",
    "DG.Formula.DateShortMonthJuly": "Jul",
    "DG.Formula.DateShortMonthAugust": "Ago",
    "DG.Formula.DateShortMonthSeptember": "Set",
    "DG.Formula.DateShortMonthOctober": "Out",
    "DG.Formula.DateShortMonthNovember": "Nov",
    "DG.Formula.DateShortMonthDecember": "Dez",
    "DG.Formula.DateLongDaySunday": "Domingo",
    "DG.Formula.DateLongDayMonday": "Segunda",
    "DG.Formula.DateLongDayTuesday": "Terça",
    "DG.Formula.DateLongDayWednesday": "Quarta",
    "DG.Formula.DateLongDayThursday": "Quinta",
    "DG.Formula.DateLongDayFriday": "Sexta",
    "DG.Formula.DateLongDaySaturday": "Sábado",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec) \\d{1,2}( |,) *\\d{4}|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "Erro de sintaxe: '%@'",
    "DG.Formula.SyntaxErrorEnd": "Expressão incompleta",
    "DG.Formula.SyntaxErrorInvalidOperator": "Operador inválido: '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "tipo(s) inválido(s) de '%@'",
    "DG.Formula.TypeError.description": "tipo(s) inválido(s) de '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' não definida",
    "DG.Formula.VarReferenceError.description": "Variável '%@' não definida",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "Referência não válida para um atributo filho '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' é uma atributo filho que só pode ser referenciada em uma função agregada",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' não definida",
    "DG.Formula.FuncReferenceError.description": "Função '%@()' não definida",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' precisa de 1 argumento",
    "DG.Formula.FuncArgsErrorSingle.description": "A '%@()' função precisa de 1 argumento",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' precisa de %@ argumento",
    "DG.Formula.FuncArgsErrorPlural.description": "A '%@()' função precisa de %@ argumentos",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' precisa de %@-%@ argumentos",
    "DG.Formula.FuncArgsErrorRange.description": "A '%@()' função precisa de %@-%@ argumentos",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "solicitação pendente...",
    "DG.Formula.PendingRequest.description": "solicitação pendente...",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "Solicitação falhou (%@)",
    "DG.Formula.FailedRequest.description": "Solicitação falhou (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "limites pendentes...",
    "DG.Formula.PendingBoundaries.description": "limites pendentes...",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "limites falharam (%@)",
    "DG.Formula.FailedBoundaries.description": "limites falharam (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@': Conjunto de dados não reconhecido",
    "DG.Formula.LookupDataSetError.description": "Base de Dados '%@' inválida",
    "DG.Formula.LookupAttrError.message": "'%@' não foi encontrado na base de dados '%@'",
    "DG.Formula.LookupAttrError.description": "Atributo '%@' não encontrada na base de dados '%@'",
    "DG.TableController.headerMenuItems.editAttribute": "Editar Atributo...",
    "DG.TableController.headerMenuItems.editFormula": "Editar fórmulas...",
    "DG.TableController.headerMenuItems.randomizeAttribute": "Rerandomize",
    "DG.TableController.headerMenuItems.sortAscending": "Ordenação crescente (A→Z, 0→9)",
    "DG.TableController.headerMenuItems.sortDescending": "Ordenação decrescente (9→0, Z→A)",
    "DG.TableController.headerMenuItems.deleteAttribute": "Deletar Atributo",
    "DG.TableController.newAttrDlg.defaultAttrName": "new_attr",
    "DG.TableController.newAttrDlg.attrNameHint": "Digite um nome para a nova atributo",
    "DG.TableController.newAttrDlg.formulaHint": "Caso queira, digita uma fórmula para atribuição de valores à atributo",
    "DG.TableController.newAttrDlg.applyTooltip": "Defina a nova atributo usando o nome e fórmula (opcional)",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "Por favor, insira um nome para a nova atributo",
    "DG.TableController.newAttrDialog.AttributesCategory": "Atributos",
    "DG.TableController.newAttrDialog.SpecialCategory": "Especiais",
    "DG.TableController.newAttrDialog.GlobalsCategory": "Globais",
    "DG.TableController.newAttrDialog.ConstantsCategory": "Constantes",
    "DG.TableController.newAttrDialog.FunctionsCategory": "Funções",
    "DG.TableController.renameAttributeInvalidMsg": "Nome de atributo não deve ser vazia",
    "DG.TableController.renameAttributeInvalidDesc": "Por favor, insira um nome válido para a atributo",
    "DG.TableController.renameAttributeDuplicateMsg": "Uma atributo com esse nome já existe",
    "DG.TableController.renameAttributeDuplicateDesc": "Por favor, insira um nome único para a atributo",
    "DG.TableController.deleteAttribute.confirmMessage": "Deletar a atributo '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "Esta ação não pode ser desfeita.",
    "DG.TableController.deleteAttribute.okButtonTitle": "Deletar Atributo",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "Cancelar",
    "DG.TableController.deleteDataSet.confirmMessage": "Excluir permanentemente esta base de dados: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "Esta ação não pode ser desfeita.",
    "DG.TableController.deleteDataSet.okButtonTitle": "Excluir Base de Dados",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "Cancelar",
    "DG.TableController.attrEditor.unitHint": "Unidade de medida, se houver",
    "DG.TableController.attrEditor.descriptionHint": "Descreva a atributo",
    "DG.TableController.setScoreDlg.applyTooltip": "Mudar a fórmula para a atributo '%@'",
    "DG.TableController.setScoreDlg.formulaHint": "Digite uma fórmula para atribuir valores a esta atributo",
    "DG.TableController.newAttributeTooltip": "Adicione uma nova atributo a esta tabela",
    "DG.TableController.attributeEditor.title": "Propriedades da Atributo",
    "DG.CaseTableDropTarget.dropMessage": "Solte aqui a atributo para criar uma nova coleção",
    "DG.CaseTable.defaultAttrName": "newAttr",
    "DG.CaseTable.indexColumnName": "Índice",
    "DG.CaseTable.indexColumnTooltip": "O número da linha (caseIndex) na coleção",
    "DG.CaseTable.indexMenu.insertCase": "Inserir Caso",
    "DG.CaseTable.indexMenu.insertCases": "Inserir Casos...",
    "DG.CaseTable.indexMenu.deleteCase": "Excluir Caso",
    "DG.CaseTable.indexMenu.deleteCases": "Excluir Casos",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "Categórica",
    "DG.CaseTable.attribute.type.categorical": "Categórica",
    "DG.CaseTable.attribute.type.numeric": "Quantitativa",
    "DG.CaseTable.attribute.type.date": "Data",
    "DG.CaseTable.attribute.type.qualitative": "Qualitativa",
    "DG.CaseTable.attribute.type.boundary": "Limitada",
    "DG.CaseTable.attributeEditor.name": "Nome",
    "DG.CaseTable.attributeEditor.description": "Descrição",
    "DG.CaseTable.attributeEditor.type": "Tipo",
    "DG.CaseTable.attributeEditor.unit": "Unidade",
    "DG.CaseTable.attributeEditor.precision": "Precisão",
    "DG.CaseTable.attributeEditor.editable": "Editável",
    "DG.CaseTable.insertCasesDialog.title": "Inserir Dados",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# casos para inserir:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "localização:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "antes",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "aepois",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "Inserir Casos",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "Insira a quantidade específica de casos",
    "DG.CaseTableController.allTables": "Todas as bases",
    "DG.AttrFormView.attrNamePrompt": "Nome da Atributo:",
    "DG.AttrFormView.formulaPrompt": "Fórmula:",
    "DG.AttrFormView.operandMenuTitle": "--- Insira o Valor ---",
    "DG.AttrFormView.functionMenuTitle": "--- Insira a Função ---",
    "DG.AttrFormView.applyBtnTitle": "Aplicar",
    "DG.AttrFormView.cancelBtnTitle": "Cancelar",
    "DG.AttrFormView.cancelBtnTooltip": "Dispensar a caixa de diálogo sem fazer alterações",
    "DG.GuideConfigView.titlePrompt": "Título do Guia",
    "DG.GuideConfigView.titleHint": "Nome da Atividade",
    "DG.GuideConfigView.itemTitleHint": "Nome da Seção",
    "DG.GuideConfigView.itemURLHint": "URL da seção",
    "DG.GuideConfigView.okBtnTitle": "Ok",
    "DG.GuideConfigView.okBtnToolTip": "Aceite os itens do menu do Guia",
    "DG.GuideConfigView.cancelBtnTitle": "Cancelar",
    "DG.GuideConfigView.cancelBtnTooltip": "Dispensar a caixa de diálogo sem fazer alterações",
    "DG.GuideConfigView.httpWarning": "A URL deve começar com http:// ou https://",
    "DG.DataDisplayModel.rescaleToData": "Re-escalar os dados",
    "DG.DataDisplayModel.ShowConnectingLine": "Mostrar linhas de conexão",
    "DG.DataDisplayModel.HideConnectingLine": "Ocultar linhas de conexão",
    "DG.AxisView.emptyGraphCue": "Clique aqui, ou arraste uma atributo para cá.",
    "DG.CellLinearAxisView.midPanelTooltip": "Arraste para traduzir a escala do eixo",
    "DG.CellLinearAxisView.lowerPanelTooltip": "Arraste para alterar o limite inferior do eixo",
    "DG.CellLinearAxisView.upperPanelTooltip": "Arraste para alterar o limite superior do eixo",
    "DG.PlotModel.mixup": "Embaralhar dados",
    "DG.PlotModel.showCount": "Mostrar Quantidade",
    "DG.PlotModel.hideCount": "Esconder Quantidade",
    "DG.ScatterPlotModel.sumSquares": "Soma dos quadrados",
    "DG.ScatterPlotModel.slopeOnly": "inclinação",
    "DG.ScatterPlotModel.yearsLabel": "por ano",
    "DG.ScatterPlotModel.daysLabel": "por dia",
    "DG.ScatterPlotModel.hoursLabel": "por hora",
    "DG.ScatterPlotModel.minutesLabel": "por minuto",
    "DG.ScatterPlotModel.secondsLabel": "por segundos",
    "DG.LegendView.attributeTooltip": "Clique para mudar a legenda das atributo",
    "DG.NumberToggleView.showAll": "Mostrar Tudo –",
    "DG.NumberToggleView.hideAll": "Esconder Tudo –",
    "DG.NumberToggleView.lastDash": "–",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "Último",
    "DG.NumberToggleView.showAllTooltip": "Clique para mostrar todos os casos\nClique nos rótulos para alternar a visibilidade dos casos aos pais",
    "DG.NumberToggleView.hideAllTooltip": "Clique para ocultar todos os casos\nClique nos rótulos para alternar a visibilidade dos casos aos pais",
    "DG.NumberToggleView.enableLastModeTooltip": "Clique para mostrar apenas o último caso aos pais",
    "DG.NumberToggleView.disableLastModeTooltip": "Clique para ocultar o último módulos dos pais",
    "DG.NumberToggleView.indexTooltip": "Clique para alterar a visualização",
    "DG.PlottedAverageAdornment.meanValueTitle": "média=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "mediana=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 DP, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IIQ=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "mínimo=%@\nQ1=%@\nmediana=%@\nQ3=%@\nmáximo=%@\nIIQ=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "Legenda: %@",
    "DG.DataDisplayMenu.remove": "Remover Atributo",
    "DG.DataDisplayMenu.removeAttribute_x": "Remover X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "Remover Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "Remover Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "Remover Legenda: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "Considerar como Categórica",
    "DG.DataDisplayMenu.treatAsNumeric": "Considerar como Numérica",
    "DG.DataDisplayMenu.hide": "Esconder/Mostrar",
    "DG.DataDisplayMenu.hideSelectedPlural": "Esconder Casos Selecionados",
    "DG.DataDisplayMenu.hideUnselectedPlural": "Esconder Casos Não Selecionados",
    "DG.DataDisplayMenu.hideSelectedSing": "Esconder Caso Selecionados",
    "DG.DataDisplayMenu.hideUnselectedSing": "Esconder Caso Não Selecionados",
    "DG.DataDisplayMenu.enableNumberToggle": "Mostrar os botões de visibilidade dos pais",
    "DG.DataDisplayMenu.disableNumberToggle": "Ocultar os botões de visibilidade dos pais",
    "DG.DataDisplayMenu.showAll": "Mostrar todos os Casos",
    "DG.DataDisplayMenu.snapshot": "Faça um instantâneo",
    "DG.GraphView.replaceAttribute": "Substituir %@ por %@",
    "DG.GraphView.addAttribute": "Adicionar atributo %@",
    "DG.GraphView.addToEmptyPlace": "Criar eixos com %@",
    "DG.GraphView.addToEmptyX": "Criar o eixo x com %@",
    "DG.GraphView.dropInPlot": "Colorir pontos pelos valores de %@",
    "DG.GraphView.zoomTip": "Duplo clique para aumentar o zoom \ne shift + duplo clique para diminuí-lo",
    "DG.GraphView.rescale": "Redimensionar para dados",
    "DG.AxisView.labelTooltip": "—Clique para trocar o eixo da atributo %@",
    "DG.AxisView.vertical": "vertical",
    "DG.AxisView.horizontal": "horizontal",
    "DG.DataTip.connectingLine": "%@: %@\ncom %@ pontos (%@) nesta reta",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "Fórmula",
    "DG.PlottedValue.namePrompt": "Valor traçado",
    "DG.PlottedValue.formulaPrompt": "Valor =",
    "DG.PlottedValue.formulaHint": "\u200b",
    "DG.PlottedFunction.namePrompt": "Função plotada",
    "DG.PlottedFunction.formulaPrompt": "f() =",
    "DG.PlottedFunction.formulaHint": "Digite uma função, por ex. x*x/30 - 50",
    "DG.MapView.showGrid": "Mostrar Grade",
    "DG.MapView.hideGrid": "Esconder Grade",
    "DG.MapView.showPoints": "Mostrar Pontos",
    "DG.MapView.hidePoints": "Esconder Pontos",
    "DG.MapView.marqueeHint": "Ferramenta Marquee - arraste pontos selecionados no mapa",
    "DG.MapView.gridControlHint": "Mudar o tamanho da malha retangular",
    "DG.Inspector.values": "Medida",
    "DG.Inspector.styles": "Formato",
    "DG.Inspector.pointSize": "Tamanho do ponto:",
    "DG.Inspector.transparency": "Transparência:",
    "DG.Inspector.color": "Cor:",
    "DG.Inspector.legendColor": "Legenda:",
    "DG.Inspector.backgroundColor": "Cor do \nplano de fundo:",
    "DG.Inspector.stroke": "Contorno:",
    "DG.Inspector.rescale.toolTip": "Redimensionar a tela para mostrar todos os dados",
    "DG.Inspector.mixUp.toolTip": "Embaralhar os pontos",
    "DG.Inspector.hideShow.toolTip": "Mostrar todos os casos ou ocultar os casos selecionados / não selecionados",
    "DG.Inspector.delete.toolTip": "Excluir casos selecionados ou não selecionados",
    "DG.Inspector.sliderValues.toolTip": "Editar o controle deslizante …",
    "DG.Inspector.webViewEditURL.toolTip": "Editar a URL da página web",
    "DG.Inspector.selection.selectAll": "Selecionar Todos os Casos",
    "DG.Inspector.selection.deleteSelectedCases": "Excluir Casos Selecionados",
    "DG.Inspector.selection.deleteUnselectedCases": "Excluir Casos Não Selecionados",
    "DG.Inspector.deleteAll": "Excluir Todos os Casos",
    "DG.Inspector.deleteDataSet": "Excluir a Base de Dados",
    "DG.Inspector.displayValues.toolTip": "Altere o que é mostrado junto com os pontos",
    "DG.Inspector.displayStyles.toolTip": "Mudar a aparência da tela",
    "DG.Inspector.makeImage.toolTip": "Salvar a imagem no formato PNG",
    "DG.Inspector.displayShow": "Mostrar …",
    "DG.Inspector.colorPicker.more": "mais",
    "DG.Inspector.colorPicker.less": "menos",
    "DG.Inspector.graphTransparency": "Transparente",
    "DG.Inspector.graphCount": "Quantidade",
    "DG.Inspector.graphPercent": "Porcentagem",
    "DG.Inspector.graphRow": "Linha",
    "DG.Inspector.graphColumn": "Coluna",
    "DG.Inspector.graphCell": "Célula",
    "DG.Inspector.graphConnectingLine": "Linhas de Conexão",
    "DG.Inspector.graphMovableLine": "Linha Móvel",
    "DG.Inspector.graphInterceptLocked": "Fixar Gráfico em (0,0)",
    "DG.Inspector.graphPlottedFunction": "Função plotada",
    "DG.Inspector.graphSquares": "Quadrado dos Resíduos",
    "DG.Inspector.graphLSRL": "Linha de Mínimos Quadrados",
    "DG.Inspector.graphMovableValue": "Valor Móvel",
    "DG.Inspector.graphAdd": "Adicionar",
    "DG.Inspector.graphRemove": "Remover",
    "DG.Inspector.graphPlottedMean": "Média",
    "DG.Inspector.graphPlottedMedian": "Mediana",
    "DG.Inspector.graphPlottedStDev": "Desvio Padrão",
    "DG.Inspector.graphPlottedIQR": "Intervalo Interquartil",
    "DG.Inspector.graphPlottedBoxPlot": "Gráfico de Caixa",
    "DG.Inspector.graphPlottedValue": "Valor Plotado",
    "DG.Inspector.attributes.toolTip": "Fazer novas atributos. Exporte os caso dados.",
    "DG.Inspector.resize.toolTip": "Ajustar a largura ao conteúdo em todas as colunas",
    "DG.Inspector.newAttribute": "Nova Atributo em %@...",
    "DG.Inspector.randomizeAllAttributes": "Rerandomizar Tudo",
    "DG.Inspector.exportCaseData": "Exportar Caso Dados...",
    "DG.Inspector.mapGrid": "Rede",
    "DG.Inspector.mapPoints": "Pontos",
    "DG.Inspector.mapLines": "Linhas de conexão",
    "DG.GameController.continuityError": "Depois que as colunas na tabela de casos forem reordenadas, novos dados não podem ser aceitos.",
    "DG.GameView.loading": "Carregando",
    "DG.GameView.loadError": "Se você vê este texto, o acesso a URL deve ter falhado. Você pode tentar o mesmo link em outra aba do navegador, ou reportar o erro para http://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "Você tem certeza?",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "Sim,  feche",
    "DG.Component.closeComponent.cancelButtonTitle": "Cancelar",
    "DG.GameController.confirmCloseDescription": "Se você fechar isso, você não poderá adicionar mais dados.",
    "DG.WebView.defaultTitle": "Página Web",
    "DG.mainPage.exceptionMessage": "Um erro ocorreu e pode comprometer o funcionamento do programa. Salve seu progresso, ou reccaregue a página. (Erro: %@)",
    "DG.fileMenu.provider.examples.displayName": "Arquivos de Exemplo",
    "DG.ToolButtonData.pluginMenu.title": "Extensões",
    "DG.ToolButtonData.pluginMenu.toolTip": "Abrir um componente de um plugin",
    "DG.Undo.graph.showMovablePoint": "Desfazer: mostrando o ponto móvel",
    "DG.Redo.graph.showMovablePoint": "Refazer: mostrando o ponto móvel",
    "DG.Undo.graph.hideMovablePoint": "Desfazer: escondendo o ponto móvel",
    "DG.Redo.graph.hideMovablePoint": "Refazer: escondendo o ponto móvel",
    "DG.Undo.graph.moveMovablePoint": "Desfazer: movendo o ponto móvel",
    "DG.Redo.graph.moveMovablePoint": "Refazer: movendo o ponto móvel",
    "DG.DataDisplayMenu.copyAsImage": "Abrir na ferramenta de desenho",
    "DG.DataDisplayMenu.exportImage": "Exportar Imagem...",
    "DG.DataDisplayMenu.imageOfTitle": "Imagem de %@",
    "DG.Inspector.graphMovablePoint": "Ponto Móvel",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "Abrir a tabela de casos para este conjunto de dados",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "Criar uma nova base de casos",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "Excluir permanentemente esta base de dados",
    "DG.Undo.graph.showAsBarChart": "Desfazer pontos de fusão em barras",
    "DG.Redo.graph.showAsBarChart": "Refazer pontos de fusão em barras",
    "DG.Undo.graph.showAsDotChart": "Desfazer barras de dispersão em pontos",
    "DG.Redo.graph.showAsDotChart": "Refazer as barras de dispersão em pontos",
    "DG.CountAxisView.countLabel": "Quantidade",
    "DG.CountAxisView.countLabelDescription": "Número de casos na barra ao longo deste eixo",
    "DG.CountAxisView.percentLabel": "Porcentagem",
    "DG.CountAxisView.percentLabelDescription": "Porcentagem de casos na barra ao longo deste eixo",
    "DG.BarChartModel.cellTipPlural": "%@ de %@ %@ (%@%) são %@",
    "DG.BarChartModel.cellTipSingular": "%@ de %@ %@ (%@%) é %@",
    "DG.Inspector.configuration": "Configuração",
    "DG.Inspector.displayConfiguration.toolTip": "Editar configurações de visualização",
    "DG.Inspector.displayScale": "Escala …",
    "DG.Inspector.graphBarChart": "Fundir pontos em barras",
    "DG.Locale.name.de": "Alemão",
    "DG.Locale.name.en": "Inglês",
    "DG.Locale.name.es": "Espanhol",
    "DG.Locale.name.he": "Hebraico",
    "DG.Locale.name.tr": "Turco",
    "DG.Locale.name.zh": "Chinês (Tradicional)",
    "DG.Undo.graph.swapCategories": "Desfazer reordenação de categorias",
    "DG.Redo.graph.swapCategories": "Refazer categorias de reordenamento",
    "DG.TableController.collectionTitleText": "%@1 (%@2 casos)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@ 1 (%@2 casos,%@3 reservado)",
    "DG.Inspector.setaside.setAsideSelectedCases": "Definir casos selecionados de lado",
    "DG.Inspector.setaside.setAsideUnselectedCases": "Definir casos não selecionados de lado",
    "DG.Inspector.setaside.restoreSetAsideCases": "Restaurar %@ Definir Casos Separados",
    "DG.DocumentController.caseCardTitle": "Cartão de caso",
    "DG.DocumentController.toggleToCaseCard": "Mudar para a visualização dos dados do cartão do caso",
    "DG.DocumentController.toggleToCaseTable": "Mudar para a visualização da tabela de casos dos dados",
    "DG.CaseCard.indexString": "1 de %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ selecionado de %@ %@",
    "DG.CaseCard.summaryValues": "%@ valores",
    "DG.CaseCard.summaryRange": "%@–%@ %@",
    "DG.CaseCard.navNextCase": "Selecionar e mostrar o próximo caso",
    "DG.CaseCard.navPrevCase": "Selecionar e mostrar caso anteriores",
    "DG.CaseCard.navFirstCase": "Selecionar e mostrar o primeiro caso",
    "DG.CaseCard.navLastCase": "Selecionar e mostrar o último caso",
    "DG.Undo.component.toggleTableToCard": "Desfazer a troca da tabela do casos para o cartão do caso",
    "DG.Redo.component.toggleTableToCard": "Refazer a troca da tabela do casos para o cartão do caso",
    "DG.Undo.component.toggleCardToTable": "Desfazer a mudança do cartão da caso para a mesa da caso",
    "DG.Redo.component.toggleCardToTable": "Refazer a mudança do cartão da caso para a mesa da caso",
    "DG.Undo.graph.addBackgroundImage": "Desfazer adicionando imagem de fundo do gráfico",
    "DG.Redo.graph.addBackgroundImage": "Refazer adicionando imagem de fundo do gráfico",
    "DG.Undo.graph.removeBackgroundImage": "Desfazer a remoção da imagem de fundo do gráfico",
    "DG.Redo.graph.removeBackgroundImage": "Refazer a remoção da imagem de fundo do gráfico",
    "DG.Undo.graph.lockBackgroundImage": "Desfazer fixar imagens nos eixos",
    "DG.Redo.graph.lockBackgroundImage": "Refazer fixar imagens nos eixos",
    "DG.Undo.graph.unlockBackgroundImage": "Desfazer fixar imagens dos eixos",
    "DG.Redo.graph.unlockBackgroundImage": "Refazer fixar imagens dos eixos",
    "DG.Undo.enableMeasuresForSelection": "Desfazer, mostrando as medidas para seleção",
    "DG.Redo.enableMeasuresForSelection": "Refazer: mostrando as medidas para seleção",
    "DG.Undo.disableMeasuresForSelection": "Desfazer ocultar medidas para seleção",
    "DG.Redo.disableMeasuresForSelection": "Refazer ocultar medidas para seleção",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Mostrar as medidas para seleção",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Ocultar as medidas para seleção",
    "DG.DataDisplayMenu.addBackgroundImage": "Adicionar Imagem de Plano de Fundo",
    "DG.DataDisplayMenu.lockImageToAxes": "Travar Imagem de Fundo para Eixos",
    "DG.DataDisplayMenu.unlockImageFromAxes": "Desbloquear a Imagem de Fundo de Eixos",
    "DG.DataDisplayMenu.removeBackgroundImage": "Remover Imagem de Plano de Fundo",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "Excluir a Fórmula (manter valores)",
    "DG.TableController.headerMenuItems.recoverFormula": "Recuperar a  Fórmula Excluída",
    "DG.Inspector.displayLayers.toolTip": "Alterar a aparência das camadas do mapa",
    "DG.Inspector.layers": "Camadas",
    "DG.Undo.graph.repositionEquation": "Desfazer, reposicionamento da equação",
    "DG.Redo.graph.repositionEquation": "Refazer: reposicionamento da equação",
    "DG.TableController.attrEditor.precisionNumericHint": "Número de dígitos após a vírgula decimal",
    "DG.TableController.attrEditor.precisionDateHint": "Defina quantos dados estão visualizados",
    "DG.TableController.attrEditor.typeHint": "Edite para forçar que a atributo seja considerada de outro tipo",
    "DG.TableController.attrEditor.nameHint": "O nome da atributo aparece na tabela de casos, cartão de caso e nos eixos do gráfico",
    "DG.TableController.attrEditor.editableHint": "Se a atributo é fixada, estes valores e/ou fórmulas não poder ser modificados",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "Ano, mês, dia, hora, minuto, segundo, milissegundo",
    "DG.AttributeFormat.DatePrecision.year": "YYYY",
    "DG.AttributeFormat.DatePrecision.month": "MMM YYYY",
    "DG.AttributeFormat.DatePrecision.day": "MMM D, YYYY",
    "DG.AttributeFormat.DatePrecision.hour": "MMM D, YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "MMM D, YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "MMM D, YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@1 em %@2",
    "DG.CaseCard.attrHintDescription": "%@1: %@2",
    "DG.CaseCard.attrHintFormula": "%@1 = %@2",
    "DG.AppController.optionMenuItems.help-forum": "Fórum de ajuda...",
    "DG.AppController.showHelpForumTitle": "Fórum de ajuda",
    "DG.Locale.name.el": "Grego",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ de %@ (%@%) é %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ de %@ (%@%) são %@",
    "DG.DataDisplayMenu.removeAttribute_top": "Excluir Modo Lado-a-Lado de %@",
    "DG.DataDisplayMenu.removeAttribute_right": "Excluir Modo Vertical de %@",
    "DG.GraphView.layoutPlotsSideBySide": "Modo Lado-a-Lado de %@",
    "DG.GraphView.layoutPlotsVertically": "Modo Vertical de %@",
    "DG.Undo.graph.makeStrokeSameAsFill": "Desfazer o contorno e preenchimento com as mesmas cores",
    "DG.Redo.graph.makeStrokeSameAsFill": "Refazer o contorno e preenchimento com as mesmas cores",
    "DG.Undo.graph.makeStrokeIndependent": "Desfazer o contorno e preenchimento diferentes",
    "DG.Redo.graph.makeStrokeIndependent": "Refazer  o contorno e preenchimento diferentes",
    "DG.Inspector.strokeSameAsFill": "Contorno e preenchimento com as mesmas cores",
    "DG.Formula.DateShortDaySunday": "Dom",
    "DG.Formula.DateShortDayMonday": "Seg",
    "DG.Formula.DateShortDayTuesday": "Ter",
    "DG.Formula.DateShortDayWednesday": "Qua",
    "DG.Formula.DateShortDayThursday": "Qui",
    "DG.Formula.DateShortDayFriday": "Sex",
    "DG.Formula.DateShortDaySaturday": "Sáb",
    "DG.AttributeFormat.DatePrecision.millisecond": "MMM D, YYYY HH:mm:ss.SSS",
    "DG.CellAxis.other": "OUTRO",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 DAM, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "Desvio Médio Absoluto",
    "DG.Undo.graph.showPlottedBoxPlot": "Desfazer: mostrando o gráfico de caixa",
    "DG.Redo.graph.hidePlottedBoxPlot": "Refazer: ocultando o gráfico de caixa",
    "DG.Undo.graph.hidePlottedBoxPlot": "Desfazer: escondendo o gráfico de caixa",
    "DG.Redo.graph.showPlottedBoxPlot": "Refazer: mostrando o gráfico de caixa",
    "DG.Undo.graph.showOutliers": "Desfazer: mostrando o gráfico de caixa",
    "DG.Redo.graph.hideOutliers": "Refazer: ocultando outliers",
    "DG.Undo.graph.hideOutliers": "Desfazer: ocultando outliers",
    "DG.Redo.graph.showOutliers": "Refazer: mostrando outliers",
    "DG.Inspector.graphBoxPlotShowOutliers": "Mostrar Outliers",
    "DG.Locale.name.nb": "Bokmål",
    "DG.Locale.name.nn": "Nynorsk",
    "DG.CaseCard.newCaseToolTip": "Adicionar um caso vazio para esta coleção",
    "DG.TableController.headerMenuItems.renameAttribute": "Renomear",
    "DG.Undo.graph.fuseDotsToRectangles": "Desfazer os pontos de fusão em retângulos",
    "DG.Redo.graph.fuseDotsToRectangles": "Refazer os pontos de fusão em retângulos",
    "DG.Undo.graph.dissolveRectanglesToDots": "Desfazer: difundindo os retângulos em pontos",
    "DG.Redo.graph.dissolveRectanglesToDots": "Refazer: difundindo os retângulos em pontos",
    "DG.Undo.graph.changeBreakdownType": "Desfazer: alterando o tipo de escala",
    "DG.Redo.graph.changeBreakdownType": "Desfazer: alterando o tipo de escala",
    "DG.Undo.graph.showAsBinnedPlot": "Desfazer: agrupando os pontos em caixas",
    "DG.Redo.graph.showAsBinnedPlot": "Refazer: agrupando os pontos em caixas",
    "DG.Undo.graph.showAsDotPlot": "Desfazer: desagrupando os pontos das caixas",
    "DG.Redo.graph.showAsDotPlot": "Refazer: desagrupando os pontos das caixas",
    "DG.Undo.graph.dragBinBoundary": "Desfazer: arrastando o limite da caixa",
    "DG.Redo.graph.dragBinBoundary": "Refazer: arrastando o limite da caixa",
    "DG.Undo.graph.changeBinWidth": "Desfazer: mudando a largura da caixa",
    "DG.Redo.graph.changeBinWidth": "Refazer: mudando a largura da caixa",
    "DG.Undo.graph.changeBinAlignment": "Desfazer: mudando o alinhamento da caixa",
    "DG.Redo.graph.changeBinAlignment": "Refazer: mudando o alinhamento da caixa",
    "DG.BinnedPlotModel.dragBinTip": "Arraste  e mude a largura da caixa",
    "DG.HistogramView.barTipPlural": "%@ de %@ %@ (%@%) são ≥ %@ e < %@",
    "DG.HistogramView.barTipSingular": "%@ de %@ %@ (%@%) é ≥ %@ e < %@",
    "DG.HistogramView.barTipNoLegendSingular": "%@ de %@ (%@%) é ≥ %@ e < %@",
    "DG.HistogramView.barTipNoLegendPlural": "%@ de %@ (%@%) são ≥ %@ e < %@",
    "DG.Inspector.graphGroupIntoBins": "Grupo em caixas",
    "DG.Inspector.graphBinWidth": "Largura da caixa",
    "DG.Inspector.graphAlignment": "Alinhamento",
    "DG.CaseTable.dividerView.expandAllTooltip": "Expandir todos os grupos",
    "DG.CaseTable.dividerView.expandGroupTooltip": "Expandir o grupo",
    "DG.CaseTable.dividerView.collapseAllTooltip": "Recolher todos os grupos",
    "DG.CaseTable.dividerView.collapseGroupTooltip": "Recolher o grupo",
    "DG.BinnedPlotModel.binLabelTip": "Valores nesta barra são ≥ %@ e < %@",
    "DG.Component.closeComponent.toolTip": "Fechar este Componente",
    "DG.Component.minimizeComponent.toolTip": "Minimize ou expanda este componente",
    "DG.Locale.name.ja": "Japonês",
    "DG.CaseCard.attrHintDescriptionAndFormula": "%@1: %@2\n%@1 = %@3",
    "DG.Locale.name.zh-Hans": "Chinês (Simplificado)",
    "DG.PlottedCount.withoutSelection": "%@",
    "DG.PlottedCount.withSelection": "%@ selecionado(s)",
    "DG.PlottedPercent.withoutSelection": "%@%",
    "DG.PlottedPercent.withSelection": "%@% selecionado(s)",
    "DG.PlottedCountPercent.withoutSelection": "%@ (%@%)",
    "DG.PlottedCountPercent.withSelection": "%@ de %@ (%@%) selecionado(s)",
    "DG.Undo.caseTable.resizeColumn": "Desfazer: ajustar a largura ao conteúdo",
    "DG.Redo.caseTable.resizeColumn": "Refazer: ajustar a largura ao conteúdo",
    "DG.TableController.headerMenuItems.resizeColumn": "Ajustar a largura ao conteúdo",
    "DG.SelectedInfoView.infoPlural": "Exibindo medidas para %@ casos selecionadas",
    "DG.SelectedInfoView.infoSing": "Exibindo medidas para %@ casos selecionada",
    "DG.Inspector.copyCaseDataToClipboard": "Copiar para a Área de Transferência...",
    "DG.Inspector.caseTable.exportCaseDialog.copyFrom": "Copie os casos do caso de:",
    "DG.Inspector.caseTable.exportCaseDialog.copy": "Copiar",
    "DG.Inspector.caseTable.exportCaseDialog.copyTooltip": "Copiar dados para a área de transferência",
    "DG.Inspector.caseTable.exportCaseDialog.copiedData": "%@ copiados para a área de transferência",
    "DG.Undo.caseTable.hideAttribute": "Desfazer: ocultar atributo",
    "DG.Redo.caseTable.hideAttribute": "Refazer: ocultar atributo",
    "DG.Undo.caseTable.showAllHiddenAttributes": "Desfazer mostrar todos os atributos ocultos",
    "DG.Redo.caseTable.showAllHiddenAttributes": "Refazer mostrar todos os atributos ocultos",
    "DG.TableController.headerMenuItems.hideAttribute": "Ocultar Atributo",
    "DG.Inspector.attributes.showAllHiddenAttributesSing": "Mostrar %@ Atributo Oculta",
    "DG.Inspector.attributes.showAllHiddenAttributesPlural": "Mostrar %@ Atributo Ocultas",
    "DG.Inspector.attributes.showAllHiddenAttributesDisabled": "Mostrar Atributo Ocultas",
    "DG.Inspector.getCaseDataFromClipboard": "Importar dados do caso da área de transferência...",
    "DG.CaseCard.addCaseButton": "add caso",
    "DG.Undo.DataContext.join": "Desfazer junção de %@ to %@",
    "DG.Redo.DataContext.join": "Refazer junção de %@ to %@",
    "DG.Collection.joinTip": "Junte %@ em %@ a %@ em %@ combinando %@ com %@",
    "DG.Inspector.graphPlotPoints": "Pontos",
    "DG.Inspector.graphBarForEachPoint": "Barra para cada ponto",
    "DG.Undo.graph.changeBarChartFunction": "Desfazer alteração da fórmula do gráfico de barras",
    "DG.Redo.graph.changeBarChartFunction": "Refazer alterar a fórmula do gráfico de barras",
    "DG.Undo.graph.showAsLinePlot": "Desfazer barra para cada ponto",
    "DG.Redo.graph.showAsLinePlot": "Barra de refazer para cada ponto",
    "DG.Undo.graph.showAsStandardBarChart": "Desfazer usando contagem ou porcentagem para a escala do gráfico de barras",
    "DG.Redo.graph.showAsStandardBarChart": "Refazer usando contagem ou porcentagem para a escala do gráfico de barras",
    "DG.Undo.graph.showAsComputedBarChart": "Desfazer o cálculo do comprimento da barra com a fórmula",
    "DG.Redo.graph.showAsComputedBarChart": "Refazer o cálculo do comprimento da barra com a fórmula",
    "DG.FormulaAxisView.labelDescription": "Clique para editar a expressão que determina o comprimento das barras.",
    "DG.ComputedBarChartModel.cellTip": "Para o grupo %@ o valor é %@",
    "DG.BarChartFunction.namePrompt": "Gráfico de Barra",
    "DG.BarChartFunction.formulaPrompt": "comprimento da barra =",
    "DG.BarChartFunction.formulaHint": "Digite uma fórmula para mudar o comprimento da(s) barra(s)",
    "DG.BarChartFunction.emptyExpressionAxisPrompt": "Clique aqui para inserir uma fórmula",
    "DG.Inspector.graphFormula": "Fórmula",
    "DG.Undo.displayOnlySelected": "Desfazer a exibição apenas de casos selecionados",
    "DG.Redo.displayOnlySelected": "Refazer exibindo apenas casos selecionados",
    "DG.Undo.webView.show": "Desfazer adição do componente da vizualização da web",
    "DG.Redo.webView.show": "Refazer adição do componente da vizualização da web",
    "DG.Undo.imageComponent.show": "Desfazer adição de componente de imagem",
    "DG.Redo.imageComponent.show": "Refazer adicionando componente de imagem",
    "DG.DataDisplayMenu.displayOnlySelected": "Exibir Apenas Casos Selecionados",
    "DG.DataDisplayMenu.displayingOnlySelected": "Exibindo Apenas Casos Selecionados",
    "DG.PlotBackgroundView.msg0": "Este gráfico está definido para exibir",
    "DG.PlotBackgroundView.msg1": "somente casos selecionados.",
    "DG.PlotBackgroundView.msg2": "Nenhum casos foi selecionado",
    "DG.PlotBackgroundView.msg3": "então nada está sendo exibido.",
    "DG.PlotBackgroundView.msg4": "Você pode selecionar casos em um",
    "DG.PlotBackgroundView.msg5": "Tabela de casos ou outro gráfico.",
    "DG.ImageComponent.defaultTitle": "Imagem",
    "DG.TableController.datasetMetadata.title": "Informaçōes do conjunto de dados",
    "DG.CaseTable.datasetMetadata.url": "fonte",
    "DG.CaseTable.datasetMetadata.creationDate": "data de importaçåo",
    "DG.TableController.datasetMetadata.descriptionHint": "Descreva o conjunto de dados",
    "DG.Inspector.datasetInfo.toolTip": "Exibir informações sobre o conjunto de dados",
    "DG.CaseTable.indexMenu.moveEntryRow": "Mover linha de entrada de dados aqui",
    "DG.CaseCard.deselect": "Desmarque todos os casos",
    "DG.CaseCard.noDeselect": "Nenhum casos foi selecionado",
    "DG.CaseTable.indexProto.tooltip": "Arraste para colocar a linha de entrada de dados nesta tabela",
    "DG.AttributeFormat.DatePrecisionShort.year": "YYYY",
    "DG.AttributeFormat.DatePrecisionShort.month": "M/YY",
    "DG.AttributeFormat.DatePrecisionShort.day": "M/D/YY",
    "DG.AttributeFormat.DatePrecisionShort.hour": "M/D/YY HH:00",
    "DG.AttributeFormat.DatePrecisionShort.minute": "M/D/YY HH:mm",
    "DG.AttributeFormat.DatePrecisionShort.second": "M/D/YY HH:mm:ss",
    "DG.AttributeFormat.DatePrecisionShort.millisecond": "M/D/YY HH:mm:ss.SSS",
    "DG.Formula.FuncCategoryLogic": "Funções Lógicas",
    "DG.Undo.graph.showMeasureLabels": "Desfazer: mostrando rótulos de medidas",
    "DG.Redo.graph.showMeasureLabels": "Refazer: mostrando os rótulos de medida",
    "DG.Undo.graph.hideMeasureLabels": "Desfazer: ocultando os rótulos de medida",
    "DG.Redo.graph.hideMeasureLabels": "Refazer: ocultando os rótulos de medida",
    "DG.Inspector.showLabels": "Mostrar os rótulos de medida",
    "DG.Undo.caseTable.resizeOneColumn": "Desfazer: o redimensionamento da coluna",
    "DG.Redo.caseTable.resizeOneColumn": "Refazer: o redimensionamento da coluna",
    "DG.CaseTable.attribute.type.checkbox": "Caixa de seleção",
    "DG.AppController.caseTableMenu.clipboardDataset": "-- novo da área de transferência --",
    "DG.AppController.caseTableMenu.clipboardDatasetToolTip": "Colar o conjunto de dados da área de transferência",
    "DG.AppController.optionMenuItems.toPrivacyPage": "Página Privada...",
    "DG.plugin.Importer.title": "Import CSV to CODAP",
    "DG.plugin.Importer.enter-url": "Enter url: ",
    "DG.plugin.Importer.or": "or",
    "DG.plugin.Importer.downsample-section": "Downsample Options...",
    "DG.plugin.Importer.downsample-random-p1": "Randomly select",
    "DG.plugin.Importer.downsample-random-p2": "rows",
    "DG.plugin.Importer.downsample-every-nth-p1": "Select every",
    "DG.plugin.Importer.downsample-every-nth-p2": "th row",
    "DG.plugin.Importer.downsample-import-all": "Import all rows",
    "DG.plugin.Importer.target-options-title": "Target Options...",
    "DG.plugin.Importer.target-options-replace": "Replace existing dataset with this one",
    "DG.plugin.Importer.target-options-append": "Append this dataset to the existing one",
    "DG.plugin.Importer.target-options-create-new": "Create a new data set",
    "DG.plugin.Importer.button-cancel": "Cancel",
    "DG.plugin.Importer.button-submit": "OK",
    "DG.plugin.Importer.button-dismiss": "Dismiss",
    "DG.plugin.Importer.load-error": "There was an error loading this resource: \"%@\" reason: \"%@\"",
    "DG.plugin.Importer.no-table-error": "Could not find tabular data in a format that can be imported into CODAP",
    "DG.plugin.Importer.duplicate-dataset-msg": "There already exists a dataset like this one. It is named \"%@\".",
    "DG.plugin.Importer.upload-time-msg": "It was uploaded %@",
    "DG.plugin.Importer.large-file-msg": "The imported file, \"%@\" has %@ rows. With more than %@ rows CODAP performance may be sluggish. You can work with a sample of the data at least at first, replacing it with the full dataset later.",
    "DG.plugin.Importer.error-codap-connection": "Error sending data to CODAP",
    "DG.plugin.Importer.error-upload": "Could not import this file -- %@",
    "DG.plugin.Importer.import-message": "Preparing to import %@ rows into \"%@\" from a table with %@ attributes: %@%@",
    "DG.Undo.component.componentTitleChange": "Undo changing the component title",
    "DG.Redo.component.componentTitleChange": "Redo changing the component title"
});