SC.stringsFor("he", {
    "DG.fileMenu.menuItem.newDocument": "חדש",
    "DG.fileMenu.menuItem.openDocument": "פתח",
    "DG.fileMenu.menuItem.closeDocument": "סגור",
    "DG.fileMenu.menuItem.importFile": "יבא",
    "DG.fileMenu.menuItem.revertTo": "החזר",
    "DG.fileMenu.menuItem.revertToOpened": "מצב אחרון שנפתח",
    "DG.fileMenu.menuItem.revertToShared": "צפיה שיתופית",
    "DG.fileMenu.menuItem.saveDocument": "שמור",
    "DG.fileMenu.menuItem.copyDocument": "צור עותק",
    "DG.fileMenu.menuItem.share": "שתף",
    "DG.fileMenu.menuItem.shareGetLink": "קבלת קישור לצפיה שיתופית",
    "DG.fileMenu.menuItem.shareUpdate": "עדכן צפיה שיתופית",
    "DG.fileMenu.menuItem.renameDocument": "שנה שם",
    "DG.main.userEntryView.title": "מה תרצו לעשות?",
    "DG.main.userEntryView.openDocument": "פתח מסמך או דפדף בדוגמאות",
    "DG.main.userEntryView.newDocument": "צור מסמך חדש",
    "DG.mainPage.mainPane.undoButton.title": "ביטול",
    "DG.mainPage.mainPane.undoButton.toolTip": "ביטול פעולה אחרונה",
    "DG.mainPage.mainPane.redoButton.title": "בצע שוב",
    "DG.mainPage.mainPane.redoButton.toolTip": "בצע שוב פעולה שבוטלה",
    "DG.mainPage.mainPane.versionString": "גרסא %@ (%@)",
    "DG.mainPage.mainPane.messageView.value": "לצערינו, CODAP אינו יכול לתמוך בדפדפן שלך כרגע. CODAP נתמך בדפדפנים מסוג:  Windows Edge 14+, Firefox 46+, Chrome 50+, and Safari 10+.\nCOPDAP אינו תומך באופן פעיל בדפדפנים אחרים כרגע.",
    "DG.mainPage.titleBar.saved": "מסמך נשמר",
    "DG.mainPage.mainPane.versionString.IS_BUILD": "גרסה %@ (%@ IS)",
    "DG.mainPage.mainPane.versionString.SRRI_BUILD": "גרסה %@ (%@.srri10)",
    "DG.AppController.resetData.title": "נקה נתונים",
    "DG.AppController.resetData.toolTip": "מחק את כל הנתונים מהמסמך הנוכחי",
    "DG.AppController.resetData.warnMessage": "אישור מחיקת כל הנתונים ממסמך זה",
    "DG.AppController.resetData.warnDescription": "פעולה זו אינה ניתנת לביצוע מחדש",
    "DG.AppController.resetData.okButtonTitle": "כן, מחק נתונים",
    "DG.AppController.resetData.cancelButtonTitle": "לא, שמור את הנתונים",
    "DG.AppController.closeDocument.warnMessage": "אישור סגירת מסמך נוכחי ללא שמירה",
    "DG.AppController.closeDocument.warnDescription": "פעולה זו אינה ניתנת לביצוע מחדש",
    "DG.AppController.closeDocument.okButtonTitle": "סגור",
    "DG.AppController.closeDocument.cancelButtonTitle": "בטל",
    "DG.AppController.beforeUnload.confirmationMessage": "המסמך מכיל שינויים שאינם שמורים",
    "DG.AppController.optionMenuItems.reportProblem": "שלח משוב",
    "DG.AppController.optionMenuItems.viewWebPage": "הצג עמוד אינטרנט",
    "DG.AppController.optionMenuItems.configureGuide": "התאם מדריך",
    "DG.AppController.optionMenuItems.about": "לגבי CODAP",
    "DG.AppController.optionMenuItems.releaseNotes": "עדכונים וחדשות",
    "DG.AppController.optionMenuItems.help": "עזרה",
    "DG.AppController.optionMenuItems.toWebSite": "אתר CODAP",
    "DG.AppController.exportDocument.prompt": "שם קובץ:",
    "DG.AppController.exportCaseData.prompt": "יצא נתונים מ",
    "DG.AppController.exportDocument.exportTitle": "יצא",
    "DG.AppController.exportDocument.exportTooltip": "יצא נתונים לקובץ",
    "DG.AppController.exportDocument.cancelTitle": "בטל",
    "DG.AppController.exportDocument.cancelTooltip": "בטל ייצוא נתונים",
    "DG.AppController.feedbackDialog.dialogTitle": "תן משוב",
    "DG.AppController.feedbackDialog.subHeaderText": "המשוב שלך חשוב לנו!",
    "DG.AppController.feedbackDialog.messageText": "בבקשה עזרו לנו להמשיך לשפר את המוצר שלנו. שאלות, תקלות, דיווחים ובקשות יתקבלו בברכה. תודה",
    "DG.AppController.feedbackDialog.subjectHint": "על מה המשוב שלך?",
    "DG.AppController.feedbackDialog.feedbackHint": "פרטים",
    "DG.AppController.feedbackDialog.submitFeedbackButton": "שלח",
    "DG.AppController.feedbackDialog.cancelFeedbackButton": "בטל",
    "DG.AppController.showWebSiteTitle": "לגבי CODAP",
    "DG.AppController.showHelpTitle": "עזרה עם CODAP",
    "DG.AppController.showAboutTitle": "לגבי CODAP",
    "DG.AppController.showReleaseNotesTitle": "הודעות של CODAP",
    "DG.AppController.dropFile.error": "שגיאה: %@1",
    "DG.AppController.dropFile.unknownFileType": "לא ניתן ליבא את סוג הקובץ שנבחר",
    "DG.AppController.validateDocument.missingRequiredProperty": "מאפיין דרוש אינו נמצא: %@1",
    "DG.AppController.validateDocument.unexpectedProperty": "מאפיין רמה גבוהה לא צפוי: %@1",
    "DG.AppController.validateDocument.unresolvedID": "מאפיין זיהוי לא פתיר: %@1",
    "DG.AppController.validateDocument.parseError": "מסמך מכיל טעות: %@1",
    "DG.AppController.validateDocument.invalidDocument": "מסמך JSON לא תקין: %@1",
    "DG.AppController.openDocument.error.general": "לא ניתן לפתוח את המסמך",
    "DG.AppController.openDocument.error.invalid_format": "CODAP אינו יכול לקרוא סוג מסמך זה",
    "DG.AppController.createDataSet.initialAttribute": "מאפיין",
    "DG.AppController.createDataSet.name": "מערך נתונים חדש",
    "DG.AppController.createDataSet.collectionName": "מקרים",
    "DG.AppController.caseTableMenu.newDataSet": "-- חדש --",
    "DG.SingleTextDialog.okButton.title": "אישור",
    "DG.SingleTextDialog.cancelButton.title": "בטל",
    "DG.SingleTextDialog.cancelButton.toolTip": "שחרר דיאלוג ללא ביצוע שינויים",
    "DG.DocumentController.calculatorTitle": "מחשבון",
    "DG.DocumentController.caseTableTitle": "טבלה",
    "DG.DocumentController.graphTitle": "גרף",
    "DG.DocumentController.sliderTitle": "כוון",
    "DG.DocumentController.textTitle": "טקסט",
    "DG.DocumentController.mapTitle": "מפה",
    "DG.DocumentController.enterURLPrompt": "הקלדת כתובת האתר להצגה",
    "DG.DocumentController.enterViewWebPageOKTip": "הצג את האתר בהינתן כתובת",
    "DG.Document.defaultDocumentName": "מסמך ללא שם",
    "DG.Document.documentName.toolTip": "לחצו לעריכת שם המסמך",
    "DG.SliderView.thumbView.toolTip": "גררו לשינוי ערכי הכוון",
    "DG.SliderView.startButton.toolTip": "התחל\\עצור אנימציה",
    "DG.ToolButtonData.tableButton.title": "טבלה",
    "DG.ToolButtonData.tableButton.toolTip": "פתח טבלה לכל מערך נתונים (ctrl-alt-t) ",
    "DG.ToolButtonData.graphButton.title": "גרף",
    "DG.ToolButtonData.graphButton.toolTip": "צור גרף (ctrl-alt-g)",
    "DG.ToolButtonData.sliderButton.title": "כוון",
    "DG.ToolButtonData.sliderButton.toolTip": "צור כוון (ctrl-alt-s)",
    "DG.ToolButtonData.calcButton.title": "מחשבון",
    "DG.ToolButtonData.calcButton.toolTip": "פתח\\סגור מחשבון (ctrl-alt-c)",
    "DG.ToolButtonData.textButton.title": "טקסט",
    "DG.ToolButtonData.textButton.toolTip": "צור אוביקט טקסט (ctrl-alt-shift-t)",
    "DG.ToolButtonData.mapButton.title": "מפה",
    "DG.ToolButtonData.mapButton.toolTip": "צור מפה",
    "DG.ToolButtonData.optionMenu.title": "אפשרויות",
    "DG.ToolButtonData.optionMenu.toolTip": "הצג עמוד אינטרנט, שנה מדריך",
    "DG.ToolButtonData.tileListMenu.title": "אריחים",
    "DG.ToolButtonData.tileListMenu.toolTip": "הצג רשימת אריחים במסמך",
    "DG.ToolButtonData.guideMenu.title": "מדריך",
    "DG.ToolButtonData.guideMenu.toolTip": "הצג מדריך לפעילות זו ונווט בתוכו",
    "DG.ToolButtonData.guideMenu.showGuide": "הצג מדריך",
    "DG.ToolButtonData.help.title": "עזרה",
    "DG.ToolButtonData.help.toolTip": "עזור לCODAP, למה על פרויקט CODAP",
    "DG.Slider.multiples": "הגבל למכפלות של",
    "DG.Slider.maxPerSecond": "מספר אנימציות מירבי מסגרות\\שניה",
    "DG.Slider.direction": "כיוון אנימציה",
    "DG.Slider.backAndForth": "הלוך ושוב",
    "DG.Slider.lowToHigh": "נמוך לגבוה",
    "DG.Slider.highToLow": "גבוה לנמוך",
    "DG.Slider.mode": "חזרה על אנימציה:",
    "DG.Slider.nonStop": "ללא הפסקה",
    "DG.Slider.onceOnly": "פעם אחת בלבד",
    "DG.Undo.exceptionOccurred": "שגיאה אירעה במהלך הנסיון לביצוע מחדש.",
    "DG.Redo.exceptionOccurred": "שגיאה אירעה במהלך הנסיון לעשות שוב.",
    "DG.Undo.componentMove": "בצע מחדש הזזת רכיב",
    "DG.Redo.componentMove": "הזז שוב את הרכיב",
    "DG.Undo.componentResize": "בצע מחדש שינוי גודל הרכיב",
    "DG.Redo.componentResize": "עשה שוב שינוי גודל הרכיב",
    "DG.Undo.axisDilate": "בצע מחדש שינוי ערכי הצירים",
    "DG.Redo.axisDilate": "עשה שוב שינוי ציר",
    "DG.Undo.axisRescaleFromData": "בצע שוב שינוי ערך הציר",
    "DG.Redo.axisRescaleFromData": "בצע שוב שינוי ציר",
    "DG.Undo.axisDrag": "עשה שוב גרירת ציר",
    "DG.Redo.axisDrag": "בצע שוב גרירת ציר",
    "DG.Undo.axisAttributeChange": "בצע שוב שינוי שם הציר",
    "DG.Redo.axisAttributeChange": "עשה שוב את שינוי שם הציר",
    "DG.Undo.axisAttributeAdded": "בצע שוב את שינוי שם הציר",
    "DG.Redo.axisAttributeAdded": "עשה שוב הוספת שם ציר",
    "DG.Undo.toggleComponent.add.calcView": "בצע שוב הצגת מחשבון",
    "DG.Redo.toggleComponent.add.calcView": "עשה שוב הצגת מחשבון",
    "DG.Undo.toggleComponent.delete.calcView": "בצע שוב הסתרת מחשבון",
    "DG.Redo.toggleComponent.delete.calcView": "עשה שוב הסתרת מחשבון",
    "DG.Undo.caseTable.open": "בצע שוב הצגת טבלאות",
    "DG.Redo.caseTable.open": "עשה שוב הצגת טבלאות",
    "DG.Undo.caseTable.editAttribute": "בצע שוב עריכת שם טבלה",
    "DG.Redo.caseTable.editAttribute": "עשה שוב עריכת שם טבלה",
    "DG.Undo.caseTable.createAttribute": "בצע שוב יצירת שם טבלה",
    "DG.Redo.caseTable.createAttribute": "עשה שוב יצירת שם טבלה",
    "DG.Undo.caseTable.editAttributeFormula": "בצע שוב עריכת נוסחת טבלה",
    "DG.Redo.caseTable.editAttributeFormula": "עשה שוב עריכת נוסחת טבלה",
    "DG.Undo.caseTable.editCellValue": "בצע שוב עריכת ערך טבלה",
    "DG.Redo.caseTable.editCellValue": "עשה שוב עריכת ערך טבלה",
    "DG.Undo.caseTable.sortCases": "בצע שוב מיון מקרים",
    "DG.Redo.caseTable.sortCases": "עשה שוב מיון מקרים",
    "DG.Undo.caseTable.deleteAttribute": "בצע שוב מחיקת שם משתנה בטבלה",
    "DG.Redo.caseTable.deleteAttribute": "עשה שוב מחיקת שם משתנה בטבלה",
    "DG.Undo.caseTable.createCollection": "בצע שוב יצירת אוסף חדש",
    "DG.Redo.caseTable.createCollection": "עשה שוב יצירת אוסף חדש",
    "DG.Undo.caseTable.collectionNameChange": "בצע שוב שינוי שם אוסף",
    "DG.Redo.caseTable.collectionNameChange": "עשה שוב שינוי שם אוסף",
    "DG.Undo.caseTable.createNewCase": "בצע שוב יצירת משתנה חדש",
    "DG.Redo.caseTable.createNewCase": "עשה שוב יצירת משתנה חדש",
    "DG.Undo.caseTable.insertCases": "בצע שוב הכנסת משתנה",
    "DG.Redo.caseTable.insertCases": "עשה שוב הכנסת משתנה",
    "DG.Undo.caseTable.groupToggleExpandCollapseAll": "בצע שוב גלילת הרחבה\\קריסת הכל",
    "DG.Redo.caseTable.groupToggleExpandCollapseAll": "עשה שוב גלילת הרחבה\\קריסת הכל",
    "DG.Undo.caseTable.expandCollapseOneCase": "בצע שוב הרחבת או קריסת קבוצה",
    "DG.Redo.caseTable.expandCollapseOneCase": "עשה שוב הרחבת או קריסת קבוצה",
    "DG.Undo.caseTable.resizeColumns": "בצע שוב שינוי אוטומטי של גודל כל העמודות",
    "DG.Redo.caseTable.resizeColumns": "עשה שוב שינוי אוטומטי של גודל כל העמודות",
    "DG.Undo.document.share": "בצע שוב שיתוף מסמך",
    "DG.Redo.document.share": "עשה שוב שיתוף מסמך",
    "DG.Undo.document.unshare": "בצע שוב עצירת שיתוף המסמך",
    "DG.Redo.document.unshare": "עשה שוב עצירת שיתוף המסמך",
    "DG.Undo.game.add": "בצע שוב הוספת משחק למסמך",
    "DG.Redo.game.add": "עשה שוב הוספת משחק למסמך",
    "DG.Undo.graph.showCount": "בצע שוב הצגת ספירה",
    "DG.Redo.graph.showCount": "עשה שוב הצגת ספירה",
    "DG.Undo.graph.hideCount": "בצע שוב הסתרת ספירה",
    "DG.Redo.graph.hideCount": "עשה שוב הסתרת ספירה",
    "DG.Undo.graph.showPercent": "בצע שוב הצגת אחוזים",
    "DG.Redo.graph.showPercent": "עשה שוב הצגת אחוזים",
    "DG.Undo.graph.hidePercent": "בצע שוב הסתרת אחוזים",
    "DG.Redo.graph.hidePercent": "עשה שוב הסתרת אחוזים",
    "DG.Undo.graph.showMovableLine": "Undo showing movable line",
    "DG.Redo.graph.showMovableLine": "Redo showing movable line",
    "DG.Undo.graph.hideMovableLine": "Undo hiding movable line",
    "DG.Redo.graph.hideMovableLine": "Redo hiding movable line",
    "DG.Undo.graph.lockIntercept": "Undo locking line intercept",
    "DG.Redo.graph.lockIntercept": "Redo locking line intercept",
    "DG.Undo.graph.unlockIntercept": "Undo unlocking line intercept",
    "DG.Redo.graph.unlockIntercept": "Redo unlocking line intercept",
    "DG.Undo.graph.showPlotFunction": "Undo showing plotted function",
    "DG.Redo.graph.showPlotFunction": "Redo showing plotted function",
    "DG.Undo.graph.hidePlotFunction": "Undo hiding plotted function",
    "DG.Redo.graph.hidePlotFunction": "Redo hiding plotted function",
    "DG.Undo.graph.changePlotFunction": "Undo change plotted function",
    "DG.Redo.graph.changePlotFunction": "Redo change plotted function",
    "DG.Undo.graph.showPlotValue": "Undo showing plotted value",
    "DG.Redo.graph.showPlotValue": "Redo showing plotted value",
    "DG.Undo.graph.hidePlotValue": "Undo hiding plotted value",
    "DG.Redo.graph.hidePlotValue": "Redo hiding plotted value",
    "DG.Undo.graph.changePlotValue": "Undo change plotted value",
    "DG.Redo.graph.changePlotValue": "Redo change plotted value",
    "DG.Undo.graph.showConnectingLine": "Undo showing connecting line",
    "DG.Redo.graph.showConnectingLine": "Redo showing connecting line",
    "DG.Undo.graph.hideConnectingLine": "Undo hiding connecting line",
    "DG.Redo.graph.hideConnectingLine": "Redo hiding connecting line",
    "DG.Undo.graph.showLSRL": "Undo showing least squares line",
    "DG.Redo.graph.showLSRL": "Redo showing least squares line",
    "DG.Undo.graph.hideLSRL": "Undo hiding least squares line",
    "DG.Redo.graph.hideLSRL": "Redo hiding least squares line",
    "DG.Undo.graph.showSquares": "Undo showing squares",
    "DG.Redo.graph.showSquares": "Redo showing squares",
    "DG.Undo.graph.hideSquares": "Undo hiding squares",
    "DG.Redo.graph.hideSquares": "Redo hiding squares",
    "DG.Undo.graph.showPlottedMean": "Undo showing mean",
    "DG.Redo.graph.showPlottedMean": "Redo showing mean",
    "DG.Undo.graph.hidePlottedMean": "Undo hiding mean",
    "DG.Redo.graph.hidePlottedMean": "Redo hiding mean",
    "DG.Undo.graph.showPlottedMedian": "Undo showing median",
    "DG.Redo.graph.showPlottedMedian": "Redo showing median",
    "DG.Undo.graph.hidePlottedMedian": "Undo hiding median",
    "DG.Redo.graph.hidePlottedMedian": "Redo hiding median",
    "DG.Undo.graph.showPlottedStDev": "Undo showing standard deviation",
    "DG.Redo.graph.showPlottedStDev": "Redo showing standard deviation",
    "DG.Undo.graph.hidePlottedStDev": "Undo hiding standard deviation",
    "DG.Redo.graph.hidePlottedStDev": "Redo hiding standard deviation",
    "DG.Undo.graph.showPlottedIQR": "Undo showing inter-quartile range",
    "DG.Redo.graph.hidePlottedIQR": "Redo hiding inter-quartile range",
    "DG.Undo.graph.hidePlottedIQR": "Undo hiding inter-quartile range",
    "DG.Redo.graph.showPlottedIQR": "Redo showing inter-quartile range",
    "DG.Undo.graph.addMovableValue": "Undo adding movable value",
    "DG.Redo.graph.addMovableValue": "Redo adding movable value",
    "DG.Undo.graph.removeMovableValue": "Undo removing movable value",
    "DG.Redo.graph.removeMovableValue": "Redo removing movable value",
    "DG.Undo.graph.moveMovableValue": "Undo moving movable value",
    "DG.Redo.graph.moveMovableValue": "Redo moving movable value",
    "DG.Undo.graph.changePointColor": "Undo changing data color",
    "DG.Redo.graph.changePointColor": "Redo changing data color",
    "DG.Undo.graph.changeStrokeColor": "Undo changing stroke color",
    "DG.Redo.graph.changeStrokeColor": "Redo changing stroke color",
    "DG.Undo.graph.changePointSize": "Undo changing point size",
    "DG.Redo.graph.changePointSize": "Redo changing point size",
    "DG.Undo.graph.changeAttributeColor": "Undo changing attribute color",
    "DG.Redo.graph.changeAttributeColor": "Redo changing attribute color",
    "DG.Undo.graph.changeBackgroundColor": "Undo changing graph background color",
    "DG.Redo.graph.changeBackgroundColor": "Redo changing graph background color",
    "DG.Undo.graph.toggleTransparent": "Undo toggling plot transparency",
    "DG.Redo.graph.toggleTransparent": "Redo toggling plot transparency",
    "DG.Undo.guide.show": "Undo showing the guide",
    "DG.Redo.guide.show": "Redo showing the guide",
    "DG.Undo.guide.navigate": "Undo changing the guide page",
    "DG.Redo.guide.navigate": "Redo changing the guide page",
    "DG.Undo.hideSelectedCases": "Undo hiding selected cases",
    "DG.Redo.hideSelectedCases": "Redo hiding selected cases",
    "DG.Undo.hideUnselectedCases": "Undo hiding unselected cases",
    "DG.Redo.hideUnselectedCases": "Redo hiding unselected cases",
    "DG.Undo.enableNumberToggle": "Undo Show Parent Visibility Toggles",
    "DG.Redo.enableNumberToggle": "Redo Show Parent Visibility Toggles",
    "DG.Undo.disableNumberToggle": "Undo Hide Parent Visibility Toggles",
    "DG.Redo.disableNumberToggle": "Redo Hide Parent Visibility Toggles",
    "DG.Undo.interactiveUndoableAction": "Undo an action in the interactive",
    "DG.Redo.interactiveUndoableAction": "Redo an action in the interactive",
    "DG.Undo.showAllCases": "Undo showing all cases",
    "DG.Redo.showAllCases": "Redo showing all cases",
    "DG.Undo.map.create": "Undo adding map",
    "DG.Redo.map.create": "Redo adding map",
    "DG.Undo.map.fitBounds": "Undo resizing map",
    "DG.Redo.map.fitBounds": "Redo resizing map",
    "DG.Undo.map.pan": "Undo panning map",
    "DG.Redo.map.pan": "Redo panning map",
    "DG.Undo.map.zoom": "Undo zooming map",
    "DG.Redo.map.zoom": "Redo zooming map",
    "DG.Undo.map.showGrid": "Undo showing grid on map",
    "DG.Redo.map.showGrid": "Redo showing grid on map",
    "DG.Undo.map.hideGrid": "Undo hiding grid on map",
    "DG.Redo.map.hideGrid": "Redo hiding grid on map",
    "DG.Undo.map.changeGridSize": "Undo changing map grid size",
    "DG.Redo.map.changeGridSize": "Redo changing map grid size",
    "DG.Undo.map.showPoints": "Undo showing points on map",
    "DG.Redo.map.showPoints": "Redo showing points on map",
    "DG.Undo.map.hidePoints": "Undo hiding points on map",
    "DG.Redo.map.hidePoints": "Redo hiding points on map",
    "DG.Undo.map.showLines": "Undo showing lines on map",
    "DG.Redo.map.showLines": "Redo showing lines on map",
    "DG.Undo.map.hideLines": "Undo hiding lines on map",
    "DG.Redo.map.hideLines": "Redo hiding lines on map",
    "DG.Undo.map.changeBaseMap": "Undo changing map background",
    "DG.Redo.map.changeBaseMap": "Redo changing map background",
    "DG.Undo.textComponent.create": "Undo adding text object",
    "DG.Redo.textComponent.create": "Redo adding text object",
    "DG.Undo.textComponent.edit": "Undo editing text",
    "DG.Redo.textComponent.edit": "Redo editing text",
    "DG.Undo.sliderComponent.create": "Undo adding a slider",
    "DG.Redo.sliderComponent.create": "Redo adding a slider",
    "DG.Undo.slider.change": "Undo slider value change",
    "DG.Redo.slider.change": "Redo slider value change",
    "DG.Undo.slider.changeMultiples": "Undo change to slider multiples restriction",
    "DG.Redo.slider.changeMultiples": "Redo change to slider multiples restriction",
    "DG.Undo.slider.changeSpeed": "Undo change to slider max frames/sec",
    "DG.Redo.slider.changeSpeed": "Redo change to slider max frames/sec",
    "DG.Undo.slider.changeDirection": "Undo change to slider animation direction",
    "DG.Redo.slider.changeDirection": "Redo change to slider animation direction",
    "DG.Undo.slider.changeRepetition": "Undo change to slider animation repetition",
    "DG.Redo.slider.changeRepetition": "Redo change to slider animation repetition",
    "DG.Undo.graphComponent.create": "Undo adding a graph",
    "DG.Redo.graphComponent.create": "Redo adding a graph",
    "DG.Undo.dataContext.create": "Undo creating a data set",
    "DG.Redo.dataContext.create": "Redo creating a data set",
    "DG.Undo.data.deleteCases": "Undo deleting cases",
    "DG.Redo.data.deleteCases": "Redo deleting cases",
    "DG.Undo.component.close": "Undo closing component",
    "DG.Redo.component.close": "Redo closing component",
    "DG.Undo.component.minimize": "Undo minimizing component",
    "DG.Redo.component.minimize": "Redo minimizing component",
    "DG.Undo.dataContext.moveAttribute": "Undo moving case table attribute",
    "DG.Redo.dataContext.moveAttribute": "Redo moving case table attribute",
    "DG.DataContext.singleCaseName": "מקרה",
    "DG.DataContext.pluralCaseName": "מקרים",
    "DG.DataContext.caseCountString": "%@1 %@2",
    "DG.DataContext.setOfCasesLabel": "אוסף",
    "DG.DataContext.collapsedRowString": "%@1 של %@2",
    "DG.DataContext.noData": "אין נתונים",
    "DG.DataContext.baseName": "סט_נתונים_%@1",
    "DG.CollectionClient.cantEditFormulaErrorMsg": "הנוסחה למשתנה \"%@\" אינה ניתנת לעריכה",
    "DG.CollectionClient.cantEditFormulaErrorDesc": "צור משתנה חדש על מנת להשתמש בנוסחה ספציפית",
    "DG.Formula.FuncCategoryArithmetic": "פונקציות אריתמטיות",
    "DG.Formula.FuncCategoryConversion": "פונקציות אחרות",
    "DG.Formula.FuncCategoryDateTime": "פונקציות זמן\\תאריך",
    "DG.Formula.FuncCategoryLookup": "חיפוש פונקציות",
    "DG.Formula.FuncCategoryOther": "פונקציות אחרות",
    "DG.Formula.FuncCategoryRandom": "פונקציות אחרות",
    "DG.Formula.FuncCategoryStatistical": "פונקציות סטטיסטיות",
    "DG.Formula.FuncCategoryString": "פונקציות מתמשכות",
    "DG.Formula.FuncCategoryTrigonometric": "פונקציות טריגומומטריות",
    "DG.Formula.DateLongMonthJanuary": "ינואר",
    "DG.Formula.DateLongMonthFebruary": "פברואר",
    "DG.Formula.DateLongMonthMarch": "מרץ",
    "DG.Formula.DateLongMonthApril": "אפריל",
    "DG.Formula.DateLongMonthMay": "מאי",
    "DG.Formula.DateLongMonthJune": "יוני",
    "DG.Formula.DateLongMonthJuly": "יולי",
    "DG.Formula.DateLongMonthAugust": "אוגוסט",
    "DG.Formula.DateLongMonthSeptember": "ספטמבר",
    "DG.Formula.DateLongMonthOctober": "אוקטובר",
    "DG.Formula.DateLongMonthNovember": "נובמבר",
    "DG.Formula.DateLongMonthDecember": "דצמבר",
    "DG.Formula.DateShortMonthJanuary": "ינו",
    "DG.Formula.DateShortMonthFebruary": "פבר",
    "DG.Formula.DateShortMonthMarch": "מרץ",
    "DG.Formula.DateShortMonthApril": "אפר",
    "DG.Formula.DateShortMonthMay": "מאי",
    "DG.Formula.DateShortMonthJune": "יונ",
    "DG.Formula.DateShortMonthJuly": "יול",
    "DG.Formula.DateShortMonthAugust": "אוג",
    "DG.Formula.DateShortMonthSeptember": "ספט",
    "DG.Formula.DateShortMonthOctober": "אוק",
    "DG.Formula.DateShortMonthNovember": "נוב",
    "DG.Formula.DateShortMonthDecember": "דצמ",
    "DG.Formula.DateLongDaySunday": "ראשון",
    "DG.Formula.DateLongDayMonday": "שני",
    "DG.Formula.DateLongDayTuesday": "שלישי",
    "DG.Formula.DateLongDayWednesday": "רביעי",
    "DG.Formula.DateLongDayThursday": "חמישי",
    "DG.Formula.DateLongDayFriday": "ששי",
    "DG.Formula.DateLongDaySaturday": "שבת",
    "DG.Utilities.date.localDatePattern": "(?:(?:[0-3]?\\d-(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-\\d{2}(?:\\d{2})?)|(?:[01]?\\d/[0-3]?\\d/\\d{2}(?:\\d{2})?))",
    "DG.Utilities.date.timePattern": "(?:[0-2]?\\d:[0-5]?\\d(?::[0-5]\\d(?:\\.\\d{3})?)? ?(?:[ap]m)?)\n",
    "DG.Utilities.date.iso8601Pattern": "^\\d{4}-[01]\\d-[0-3]\\d(?:[T ][0-2]\\d:[0-5]\\d(?::[0-5]\\d(?:\\.\\d{3,6})?)?(?:Z|(?:[-+]?[01]\\d:[0-5]\\d)|(?: ?[-+][0-2]\\d{3}))?)?$",
    "DG.Utilities.colorPattern": "(?:rgb\\((?:\\d{1,3},){2}\\d{1,3}\\))|(?:rgba\\((?:\\d{1,3},){3}[\\d\\.]*\\))|(?:#[\\da-f]{6})",
    "DG.Formula.SyntaxErrorMiddle": "טעות סינטקס: ,%@'",
    "DG.Formula.SyntaxErrorEnd": "ביטוי לא מושלם",
    "DG.Formula.SyntaxErrorInvalidOperator": "פעולה לא תקינה '%@'",
    "DG.Formula.TypeError.name": "❌",
    "DG.Formula.TypeError.message": "הקלדות לא תקינות עבור '%@'",
    "DG.Formula.TypeError.description": "הקלדות לא תקינות עבור '%@'",
    "DG.Formula.VarReferenceError.name": "❌",
    "DG.Formula.VarReferenceError.message": "'%@' אינו מזוהה",
    "DG.Formula.VarReferenceError.description": "המשתנה '%@' אינו מזוהה",
    "DG.Formula.HierReferenceError.name": "❌",
    "DG.Formula.HierReferenceError.message": "ערך לא תקין עבור תת הערך '%@'",
    "DG.Formula.HierReferenceError.description": "'%@' הינו תת-ערך שיכול רק לעבור לפונקציה מתטברת",
    "DG.Formula.FuncReferenceError.name": "❌",
    "DG.Formula.FuncReferenceError.message": "'%@()' אינו מוכר",
    "DG.Formula.FuncReferenceError.description": "הפונקציה '%@()' אינה מוכרת",
    "DG.Formula.FuncArgsError.name": "❌",
    "DG.Formula.FuncArgsErrorSingle.message": "'%@()' אמור לקבל טיעון 1",
    "DG.Formula.FuncArgsErrorSingle.description": "הפונקציה '%@()' אמורה לקבל טיעון 1",
    "DG.Formula.FuncArgsErrorPlural.message": "'%@()' אמור לקבל %@ טיעונים",
    "DG.Formula.FuncArgsErrorPlural.description": "הפונקציה '%@()' אמורה לקבל %@ טיעונים",
    "DG.Formula.FuncArgsErrorRange.message": "'%@()' אמור לקבל %@-%@ טיעונים",
    "DG.Formula.FuncArgsErrorRange.description": "הפונקציה '%@()' אמורה לקבל %@-%@ טיעונים",
    "DG.Formula.PendingRequest.name": "⌛",
    "DG.Formula.PendingRequest.message": "בקשה בהמתנה",
    "DG.Formula.PendingRequest.description": "בקשה בהמתנה",
    "DG.Formula.FailedRequest.name": "❌",
    "DG.Formula.FailedRequest.message": "בקשה נכשלה (%@)",
    "DG.Formula.FailedRequest.description": "בקשה נכשלה (%@)",
    "DG.Formula.PendingBoundaries.name": "⌛",
    "DG.Formula.PendingBoundaries.message": "גבולות בהמתנה",
    "DG.Formula.PendingBoundaries.description": "גבולות בהמתנה",
    "DG.Formula.FailedBoundaries.name": "❌",
    "DG.Formula.FailedBoundaries.message": "גבולות נכשלו (%@)",
    "DG.Formula.FailedBoundaries.description": "גבולות נכשלו (%@)",
    "DG.Formula.LookupDataSetError.message": "'%@' סט נתונים לא מזוהה",
    "DG.Formula.LookupDataSetError.description": "סט נתונים '%@' אינו מזוהה",
    "DG.Formula.LookupAttrError.message": "'%@' לא ניתן למצוא סט נתונים '%@'",
    "DG.Formula.LookupAttrError.description": "המשתנה '%@' אינו נמצא בסט הנתונים '%@'",
    "DG.TableController.headerMenuItems.editAttribute": "ערוך מאפייני משתנים...",
    "DG.TableController.headerMenuItems.editFormula": "ערוך נוסחה..",
    "DG.TableController.headerMenuItems.randomizeAttribute": "שנה סדר אקראי שוב",
    "DG.TableController.headerMenuItems.sortAscending": "מיין בסדר עולה",
    "DG.TableController.headerMenuItems.sortDescending": "מיין בסדר יורד",
    "DG.TableController.headerMenuItems.deleteAttribute": "מחק משתנה",
    "DG.TableController.newAttrDlg.defaultAttrName": "משתנה_חדש",
    "DG.TableController.newAttrDlg.attrNameHint": "ערוך שם משתנה חדש",
    "DG.TableController.newAttrDlg.formulaHint": "במידת הצורך, הקלד נוסחה לחישוב ערכים למשתנה זה",
    "DG.TableController.newAttrDlg.applyTooltip": "הגדר משתנה חדש בעזרת השם ונוסחה (אופציונלי)",
    "DG.TableController.newAttrDlg.mustEnterAttrNameMsg": "בבקשה הקלד שם למשתנה החדש",
    "DG.TableController.newAttrDialog.AttributesCategory": "משתנה",
    "DG.TableController.newAttrDialog.SpecialCategory": "מיוחד",
    "DG.TableController.newAttrDialog.GlobalsCategory": "גלובלים",
    "DG.TableController.newAttrDialog.ConstantsCategory": "מבנים",
    "DG.TableController.newAttrDialog.FunctionsCategory": "נוסחאות",
    "DG.TableController.renameAttributeInvalidMsg": "שם המשתנה אינו יכול להיות ריק",
    "DG.TableController.renameAttributeInvalidDesc": "בבקשה הכנס שם משתנה תקין",
    "DG.TableController.renameAttributeDuplicateMsg": "משתנה עם שם זהה כבר קיים",
    "DG.TableController.renameAttributeDuplicateDesc": "בבקשה הכנס שם משתנה ייחודי",
    "DG.TableController.deleteAttribute.confirmMessage": "מחק את המשתנה '%@'?",
    "DG.TableController.deleteAttribute.confirmDescription": "פעולה זו אינה ניתנת לביצוע מחדש",
    "DG.TableController.deleteAttribute.okButtonTitle": "מחק משתנה",
    "DG.TableController.deleteAttribute.cancelButtonTitle": "בטל",
    "DG.TableController.deleteDataSet.confirmMessage": "מחק והשמד את סט הנתונים הזה: '%@'?",
    "DG.TableController.deleteDataSet.confirmDescription": "פעולה זו אינה ניתנת לביצוע מחדש",
    "DG.TableController.deleteDataSet.okButtonTitle": "מחק סט נתונים",
    "DG.TableController.deleteDataSet.cancelButtonTitle": "בטל",
    "DG.TableController.attrEditor.unitHint": "יחידת מדידה, אם יישומי",
    "DG.TableController.attrEditor.descriptionHint": "תיאור המשתנה",
    "DG.TableController.setScoreDlg.applyTooltip": "קבע את הנוסחה למשתנה '%@'",
    "DG.TableController.setScoreDlg.formulaHint": "הקלד נוסחה לחישוב ערכים למשתנה זה",
    "DG.TableController.newAttributeTooltip": "הוסף משתנה חדש לטבלה זו",
    "DG.TableController.attributeEditor.title": "מאפייני משתנה",
    "DG.CaseTableDropTarget.dropMessage": "גרור ושחרר משתנה ליצירת אוסף חדש",
    "DG.CaseTable.defaultAttrName": "משתנה חדש",
    "DG.CaseTable.indexColumnName": "מפתח",
    "DG.CaseTable.indexColumnTooltip": "מספר שורה באוסף",
    "DG.CaseTable.indexMenu.insertCase": "הכנס מקרה",
    "DG.CaseTable.indexMenu.insertCases": "הכנס מקרה...",
    "DG.CaseTable.indexMenu.deleteCase": "מחק מקרה",
    "DG.CaseTable.indexMenu.deleteCases": "מחק מקרים",
    "DG.CaseTable.attribute.type.none": "\u200b",
    "DG.CaseTable.attribute.type.nominal": "קטגורי",
    "DG.CaseTable.attribute.type.categorical": "קטגורי",
    "DG.CaseTable.attribute.type.numeric": "מספרי",
    "DG.CaseTable.attribute.type.date": "תאריך",
    "DG.CaseTable.attribute.type.qualitative": "איכותני",
    "DG.CaseTable.attribute.type.boundary": "גבול",
    "DG.CaseTable.attributeEditor.name": "שם",
    "DG.CaseTable.attributeEditor.description": "תאור",
    "DG.CaseTable.attributeEditor.type": "סוג",
    "DG.CaseTable.attributeEditor.unit": "יחידה",
    "DG.CaseTable.attributeEditor.precision": "דיוק",
    "DG.CaseTable.attributeEditor.editable": "ניתן לעריכה",
    "DG.CaseTable.insertCasesDialog.title": "הכנס מקרים",
    "DG.CaseTable.insertCasesDialog.numCasesPrompt": "# מקרים להכנסה:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.prompt": "מיקום:",
    "DG.CaseTable.insertCasesDialog.beforeAfter.before": "לפני",
    "DG.CaseTable.insertCasesDialog.beforeAfter.after": "אחרי",
    "DG.CaseTable.insertCasesDialog.applyBtnTitle": "הכנס מקרים",
    "DG.CaseTable.insertCasesDialog.applyBtnTooltip": "הכנס מספר מקרים ספציפי",
    "DG.CaseTableController.allTables": "כל הטבלאות",
    "DG.AttrFormView.attrNamePrompt": "שם משתנה:",
    "DG.AttrFormView.formulaPrompt": "נוסחה:",
    "DG.AttrFormView.operandMenuTitle": "-- הכנס ערך --",
    "DG.AttrFormView.functionMenuTitle": "-- הכנס פונקציה --",
    "DG.AttrFormView.applyBtnTitle": "הוסף",
    "DG.AttrFormView.cancelBtnTitle": "בטל",
    "DG.AttrFormView.cancelBtnTooltip": "שחרר את הדיאלוג מבלי ליצור שינויים",
    "DG.GuideConfigView.titlePrompt": "טבלת עזר",
    "DG.GuideConfigView.titleHint": "שם פעילות",
    "DG.GuideConfigView.itemTitleHint": "שם מדור",
    "DG.GuideConfigView.itemURLHint": "תאור ה-URL",
    "DG.GuideConfigView.okBtnTitle": "אישור",
    "DG.GuideConfigView.okBtnToolTip": "קבל את חפצי תפריט המדריך",
    "DG.GuideConfigView.cancelBtnTitle": "בטל",
    "DG.GuideConfigView.cancelBtnTooltip": "שחרר את הדיאלוג מבלי ליצור שינויים",
    "DG.GuideConfigView.httpWarning": "ה-URL חייב להתחיל עם http://  או https://",
    "DG.DataDisplayModel.rescaleToData": "מקם מחדש לפי הנתונים",
    "DG.DataDisplayModel.ShowConnectingLine": "הצג קווי חיבור",
    "DG.DataDisplayModel.HideConnectingLine": "הסתר קווי חיבור",
    "DG.AxisView.emptyGraphCue": "הקלק כאן, או גרור משתנה לכאן",
    "DG.CellLinearAxisView.midPanelTooltip": "גרור לתרגום סקלת הציר",
    "DG.CellLinearAxisView.lowerPanelTooltip": "גרור לשינוי גבול תחתון של הציר",
    "DG.CellLinearAxisView.upperPanelTooltip": "גרור לשינוי גבול עליון של הציר",
    "DG.PlotModel.mixup": "ערבב את הטבלה",
    "DG.PlotModel.showCount": "הראה ספירה",
    "DG.PlotModel.hideCount": "הסתר ספירה",
    "DG.ScatterPlotModel.sumSquares": "סכום הריבועים = %@",
    "DG.ScatterPlotModel.rSquared": ",\nr^2 = %@",
    "DG.ScatterPlotModel.slopeIntercept": "%@ = %@ %@ %@ %@",
    "DG.ScatterPlotModel.infiniteSlope": "%@ = %@",
    "DG.ScatterPlotModel.slopeOnly": "זווית = %@ %@",
    "DG.ScatterPlotModel.yearsLabel": "בשנה",
    "DG.ScatterPlotModel.daysLabel": "ביום",
    "DG.ScatterPlotModel.hoursLabel": "בשעה",
    "DG.ScatterPlotModel.minutesLabel": "בדקה",
    "DG.ScatterPlotModel.secondsLabel": "בשנייה",
    "DG.LegendView.attributeTooltip": "הקלק לשינוי מקרא המשתנה",
    "DG.NumberToggleView.showAll": "הצג הכל --",
    "DG.NumberToggleView.hideAll": "הסתר הכל --",
    "DG.NumberToggleView.lastDash": "--",
    "DG.NumberToggleView.lastUnchecked": "☐",
    "DG.NumberToggleView.lastChecked": "☒",
    "DG.NumberToggleView.lastLabel": "אחרון",
    "DG.NumberToggleView.showAllTooltip": "לחץ להצגת כל המקרים\nלחץ על תגית מקרה ראשוני לשינוי המראה",
    "DG.NumberToggleView.hideAllTooltip": "לחץ להסתרת כל המקרים\nלחץ על תגית מקרה ראשוני לשינוי המראה",
    "DG.NumberToggleView.enableLastModeTooltip": "לחץ להצגת מקרה ראשוני אחרון בלבד",
    "DG.NumberToggleView.disableLastModeTooltip": "לחץ ליציאה ממצב מקרה ראשוני אחרון בלבד",
    "DG.NumberToggleView.indexTooltip": "לחץ לשינוי מראה",
    "DG.PlottedAverageAdornment.meanValueTitle": "ממוצע=%@",
    "DG.PlottedAverageAdornment.medianValueTitle": "חציון=%@",
    "DG.PlottedAverageAdornment.stDevValueTitle": "±1 SD, %@",
    "DG.PlottedAverageAdornment.iqrValueTitle": "IQR=%@",
    "DG.PlottedAverageAdornment.boxPlotTitle": "lower=%@\nQ1=%@\nmedian=%@\nQ3=%@\nupper=%@\nIQR=%@",
    "DG.PlottedCountAdornment.title": "%@ %@, %@%",
    "DG.DataDisplayMenu.attribute_x": "X: %@",
    "DG.DataDisplayMenu.attribute_y": "Y: %@",
    "DG.DataDisplayMenu.attribute_y2": "Y: %@",
    "DG.DataDisplayMenu.attribute_legend": "מקרא: %@",
    "DG.DataDisplayMenu.remove": "הסר משתנה",
    "DG.DataDisplayMenu.removeAttribute_x": "הסר X: %@",
    "DG.DataDisplayMenu.removeAttribute_y": "הסר Y: %@",
    "DG.DataDisplayMenu.removeAttribute_y2": "הסר Y: %@",
    "DG.DataDisplayMenu.removeAttribute_legend": "הסר מקרא: %@",
    "DG.DataDisplayMenu.treatAsCategorical": "התייחס כקטגורי",
    "DG.DataDisplayMenu.treatAsNumeric": "התייחס כמספרי",
    "DG.DataDisplayMenu.hide": "הסתר והצג",
    "DG.DataDisplayMenu.hideSelectedPlural": "הסתר מקרים שנבחרו",
    "DG.DataDisplayMenu.hideUnselectedPlural": "הסתר מקרים שלא נבחרו",
    "DG.DataDisplayMenu.hideSelectedSing": "הסתר מקרים שנבחרו",
    "DG.DataDisplayMenu.hideUnselectedSing": "הסתר מקרים שלא נבחרו",
    "DG.DataDisplayMenu.enableNumberToggle": "הצג ערכי מקרים ראשוניים",
    "DG.DataDisplayMenu.disableNumberToggle": "הסתר ערכי מקרים ראשוניים",
    "DG.DataDisplayMenu.showAll": "הצג את כל המקרים",
    "DG.DataDisplayMenu.snapshot": "צילום תמונת מסך",
    "DG.GraphView.replaceAttribute": "החלך %@ עם %@",
    "DG.GraphView.addAttribute": "הוסף משתנה %@",
    "DG.GraphView.addToEmptyPlace": "צור ציר עם %@",
    "DG.GraphView.addToEmptyX": "צור ציר X עם %@",
    "DG.GraphView.dropInPlot": "נקודות צבע על ידי ערכים של %@",
    "DG.GraphView.zoomTip": "לחץ פעמיים על מנת לעשות זום פנימה.\nShift-double-click על מנת לעשות זום החוצה",
    "DG.GraphView.rescale": "שנה סקאלה לפי הנתונים",
    "DG.AxisView.labelTooltip": "-- לחץ לשינוי ציר משתנה %@ ",
    "DG.AxisView.vertical": "אנכי",
    "DG.AxisView.horizontal": "אופקי",
    "DG.DataTip.connectingLine": "%@: %@\nעם %@ %@",
    "DG.MovableMonthYear": "%@, %@",
    "DG.MovableMonthDayHour": "%@ %@ %@:00",
    "DG.PlottedFormula.defaultNamePrompt": "נוסחה",
    "DG.PlottedValue.namePrompt": "ערך מנוקד",
    "DG.PlottedValue.formulaPrompt": "ערך",
    "DG.PlottedValue.formulaHint": "\n \u200b",
    "DG.PlottedFunction.namePrompt": "פונקציה ",
    "DG.PlottedFunction.formulaPrompt": "\n f() =",
    "DG.PlottedFunction.formulaHint": "הקלד ביטוי לדוגמא x*x/30 - 50",
    "DG.MapView.showGrid": "הצג גריד",
    "DG.MapView.hideGrid": "הסתר גריד",
    "DG.MapView.showPoints": "הצג נקודות",
    "DG.MapView.hidePoints": "הסתר נקודות",
    "DG.MapView.marqueeHint": "כלי מרקואי- גרור בחר נקודות במפה",
    "DG.MapView.gridControlHint": "שנה גודל ריבועי גריד",
    "DG.Inspector.values": "מדוד",
    "DG.Inspector.styles": "פורמט",
    "DG.Inspector.pointSize": "גודל נקודה",
    "DG.Inspector.transparency": "שקיפות",
    "DG.Inspector.color": "צבע",
    "DG.Inspector.legendColor": "צבע מקרא",
    "DG.Inspector.backgroundColor": "רקע",
    "DG.Inspector.stroke": "קווים",
    "DG.Inspector.rescale.toolTip": "שנה גודל תצוגה להצגת כל הנתונים",
    "DG.Inspector.mixUp.toolTip": "ערבב את כל הנקודות",
    "DG.Inspector.hideShow.toolTip": "הצג את כל המקרים או הסתר מקרים שנבחרו או לא נבחרו",
    "DG.Inspector.delete.toolTip": "מחק מקרים שנבחרו או לא נבחרו",
    "DG.Inspector.sliderValues.toolTip": "ערוך כיוון סליידר אנימציה, מהירות, ...",
    "DG.Inspector.webViewEditURL.toolTip": "ערוך את ה-URL של דפי אינטרנט מוצגים",
    "DG.Inspector.selection.selectAll": "בחר את כל המקרים",
    "DG.Inspector.selection.deleteSelectedCases": "מחק מקרים שנבחרו",
    "DG.Inspector.selection.deleteUnselectedCases": "מחק מקרים שלא נבחרו",
    "DG.Inspector.deleteAll": "מחק את כל המקרים",
    "DG.Inspector.deleteDataSet": "מחק והשמד סט נתונים",
    "DG.Inspector.displayValues.toolTip": "שנה את מה שמוצג בנקודות",
    "DG.Inspector.displayStyles.toolTip": "שנה את התצוגה",
    "DG.Inspector.makeImage.toolTip": "שמור תמונה כקובץ PNG",
    "DG.Inspector.displayShow": "הצג",
    "DG.Inspector.colorPicker.more": "יותר",
    "DG.Inspector.colorPicker.less": "פחות",
    "DG.Inspector.graphTransparency": "שקוף",
    "DG.Inspector.graphCount": "מספר",
    "DG.Inspector.graphPercent": "אחוז",
    "DG.Inspector.graphRow": "שורה",
    "DG.Inspector.graphColumn": "טור",
    "DG.Inspector.graphCell": "תא",
    "DG.Inspector.graphConnectingLine": "חיבור נקודות בקו",
    "DG.Inspector.graphMovableLine": "קו נייד",
    "DG.Inspector.graphInterceptLocked": "נקודת חיבור נעולה",
    "DG.Inspector.graphPlottedFunction": "הוספת קו פונקציה",
    "DG.Inspector.graphSquares": "ריבוע שאריות",
    "DG.Inspector.graphLSRL": "קו ריבועים פחותים",
    "DG.Inspector.graphMovableValue": "ערך נייד",
    "DG.Inspector.graphAdd": "הוסף",
    "DG.Inspector.graphRemove": "הסר",
    "DG.Inspector.graphPlottedMean": "ממוצע",
    "DG.Inspector.graphPlottedMedian": "חציון",
    "DG.Inspector.graphPlottedStDev": "סטיית תקן",
    "DG.Inspector.graphPlottedIQR": "טווח רביעוני",
    "DG.Inspector.graphPlottedBoxPlot": "תיבת ערכים",
    "DG.Inspector.graphPlottedValue": "הוספת ערך",
    "DG.Inspector.attributes.toolTip": "הוסף משתנה. יצא סט נתונים",
    "DG.Inspector.resize.toolTip": "שנה גודל כל העמודות להתאמה לנתונים",
    "DG.Inspector.newAttribute": "משתנה חדש ב%@",
    "DG.Inspector.randomizeAllAttributes": "שנה סדר אקראי להכל",
    "DG.Inspector.exportCaseData": "יצא סט נתונים",
    "DG.Inspector.mapGrid": "גריד",
    "DG.Inspector.mapPoints": "נקודות",
    "DG.Inspector.mapLines": "קווים מחברים",
    "DG.GameController.continuityError": "סליחה, לאחר שינוי סדר העמודות, נתונים חדשים לא יתקבלו",
    "DG.GameView.loading": "טוען",
    "DG.GameView.loadError": "אם אתם רואים את הטקסט הזה, טעינת ה-URL נכשלה. אתם יכולים לבדוק את הקישור בדפדפן נוסף או לדווח על השגיאה ב-http://codap.concord.org/help.",
    "DG.Component.closeComponent.confirmCloseMessage": "אישור",
    "DG.Component.closeComponent.confirmCloseDescription": "\u200b",
    "DG.Component.closeComponent.okButtonTitle": "כן, סגור",
    "DG.Component.closeComponent.cancelButtonTitle": "בטל",
    "DG.GameController.confirmCloseDescription": "סגירה לא תאפשר הוספת נתונים חדשים",
    "DG.WebView.defaultTitle": "עמוד אינטרנט",
    "DG.mainPage.exceptionMessage": "חלה שגיאה שיכולה להשפיע על התוכנה. רצוי לטעון מחדש דף זה לאחר שמירת העבודה",
    "DG.fileMenu.provider.examples.displayName": "מסמכים לדוגמא",
    "DG.ToolButtonData.pluginMenu.title": "Plugins",
    "DG.ToolButtonData.pluginMenu.toolTip": "פתח מרכיב plugin",
    "DG.Undo.graph.showMovablePoint": "בצע שוב הצגת נקודה נעה",
    "DG.Redo.graph.showMovablePoint": "עשה שוב הצגת נקודה נעה",
    "DG.Undo.graph.hideMovablePoint": "בצע שוב הסתרת נקודה נעה",
    "DG.Redo.graph.hideMovablePoint": "עשה שוב הסתרת נקודה נעה",
    "DG.Undo.graph.moveMovablePoint": "בצע שוב נקודה נעה",
    "DG.Redo.graph.moveMovablePoint": "עשה שוב הזזת נקודה נעה",
    "DG.DataDisplayMenu.copyAsImage": "פתח כלי ציור",
    "DG.DataDisplayMenu.exportImage": "יצא תמונה...",
    "DG.DataDisplayMenu.imageOfTitle": "תמונה של %@",
    "DG.Inspector.graphMovablePoint": "נקודה נעה",
    "DG.AppController.caseTableMenu.openCaseTableToolTip": "פתח טבלת מקרה עבור מערך נתונים זה",
    "DG.AppController.caseTableMenu.newDataSetToolTip": "צור מערך נתונים חדש",
    "DG.AppController.caseTableMenu.deleteDataSetToolTip": "מחק והשמד מערך נתונים זה",
    "DG.Undo.graph.showAsBarChart": "בצע שוב מיזוג נקודות לעמודות",
    "DG.Redo.graph.showAsBarChart": "עשה שוב מיזוג נקודות לעמודות",
    "DG.Undo.graph.showAsDotChart": "בצע שוב פיזור עמודות לנקודות",
    "DG.Redo.graph.showAsDotChart": "עשה שוב פיזור עמודות לנקודות",
    "DG.CountAxisView.countLabel": "ספור",
    "DG.CountAxisView.countLabelDescription": "מספר המקרים בעמודה לאורך הציר",
    "DG.CountAxisView.percentLabel": "אחוז",
    "DG.CountAxisView.percentLabelDescription": "אחוז המקרים בעמודה לאורך הציר",
    "DG.BarChartModel.cellTipPlural": "\n %@ of %@ %@ (%@%) הם %@\n",
    "DG.BarChartModel.cellTipSingular": "%@ of %@ %@ (%@%) הוא %@",
    "DG.Inspector.configuration": "תצורה",
    "DG.Inspector.displayConfiguration.toolTip": "הצג תצורה באופן שונה",
    "DG.Inspector.displayScale": "שנה סרגל...",
    "DG.Inspector.graphBarChart": "מיזוג נקודות לעמודות",
    "DG.Locale.name.de": "גרמנית",
    "DG.Locale.name.en": "אנגלית",
    "DG.Locale.name.es": "ספרדית",
    "DG.Locale.name.he": "עברית",
    "DG.Locale.name.tr": "טורקית",
    "DG.Locale.name.zh": "סינית",
    "DG.Undo.graph.swapCategories": "Undo reordering categories",
    "DG.Redo.graph.swapCategories": "Redo reordering categories",
    "DG.TableController.collectionTitleText": "%@1 (%@2 cases)",
    "DG.TableController.collectionTitleTextWithSetAside": "%@1 (%@2 cases, %@3 set aside)",
    "DG.Inspector.setaside.setAsideSelectedCases": "שמירה בצד של מקרים נבחרים",
    "DG.Inspector.setaside.setAsideUnselectedCases": "שמירה בצד של מקרים שלא נבחרו",
    "DG.Inspector.setaside.restoreSetAsideCases": "Restore %@ Set Aside Cases",
    "DG.DocumentController.caseCardTitle": "Case Card",
    "DG.DocumentController.toggleToCaseCard": "החלפה לתצוגת קלפים של המידע",
    "DG.DocumentController.toggleToCaseTable": "החלפה לתצוגת טבלה של המידע",
    "DG.CaseCard.indexString": "1 מתוך %@ %@",
    "DG.CaseCard.namePlusCaseCount": "%@ %@",
    "DG.CaseCard.namePlusSelectionCount": "%@ נבחר מ %@ %@",
    "DG.CaseCard.summaryValues": "ערכי %@ ",
    "DG.CaseCard.summaryRange": "%@-%@ %@ ",
    "DG.CaseCard.navNextCase": "בחירה והצגת המקרה הבא",
    "DG.CaseCard.navPrevCase": "בחירה והצגה של המקרה הקודם",
    "DG.CaseCard.navFirstCase": "בחירה והצגה של המקרה הראשון",
    "DG.CaseCard.navLastCase": "בחירה והצגה של המקרה האחרון",
    "DG.Undo.component.toggleTableToCard": "Undo changing case table to case card",
    "DG.Redo.component.toggleTableToCard": "Redo changing case table to case card",
    "DG.Undo.component.toggleCardToTable": "Undo changing case card to case table",
    "DG.Redo.component.toggleCardToTable": "Redo changing case card to case table",
    "DG.Undo.graph.addBackgroundImage": "Undo adding graph background image",
    "DG.Redo.graph.addBackgroundImage": "Redo adding graph background image",
    "DG.Undo.graph.removeBackgroundImage": "Undo removing graph background image",
    "DG.Redo.graph.removeBackgroundImage": "Redo removing graph background image",
    "DG.Undo.graph.lockBackgroundImage": "Undo locking background image to axes",
    "DG.Redo.graph.lockBackgroundImage": "Redo locking background image to axes",
    "DG.Undo.graph.unlockBackgroundImage": "Undo unlocking background image from axes",
    "DG.Redo.graph.unlockBackgroundImage": "Redo unlocking background image from axes",
    "DG.Undo.enableMeasuresForSelection": "Undo Show Measures For Selection",
    "DG.Redo.enableMeasuresForSelection": "Redo Show Measures For Selection",
    "DG.Undo.disableMeasuresForSelection": "Undo Hide Measures For Selection",
    "DG.Redo.disableMeasuresForSelection": "Redo Hide Measures For Selection",
    "DG.DataDisplayMenu.enableMeasuresForSelection": "Show Measures for Selection",
    "DG.DataDisplayMenu.disableMeasuresForSelection": "Hide Measures for Selection",
    "DG.DataDisplayMenu.addBackgroundImage": "Add Background Image",
    "DG.DataDisplayMenu.lockImageToAxes": "Lock Background Image to Axes",
    "DG.DataDisplayMenu.unlockImageFromAxes": "פתיחת תמונה רקע מהצירים",
    "DG.DataDisplayMenu.removeBackgroundImage": "הסרת תמונת רקע",
    "DG.main.page.title": "%@1 - %@2",
    "DG.TableController.headerMenuItems.deleteFormula": "מחיקת נוסחה (שמירת ערכים)",
    "DG.TableController.headerMenuItems.recoverFormula": "שחזור נוסחה שנמחקה",
    "DG.Inspector.displayLayers.toolTip": "שינוי תצוגת שכבות המפה",
    "DG.Inspector.layers": "שכבות",
    "DG.Undo.graph.repositionEquation": "Undo repositioning equation",
    "DG.Redo.graph.repositionEquation": "Redo repositioning equation",
    "DG.TableController.attrEditor.precisionNumericHint": "Number of digits after decimal point",
    "DG.TableController.attrEditor.precisionDateHint": "Determines how much of the date is displayed",
    "DG.TableController.attrEditor.typeHint": "Set to force the attribute to be treated as a certain type",
    "DG.TableController.attrEditor.nameHint": "The attribute name appears in the case table, case card, and on graph axes",
    "DG.TableController.attrEditor.editableHint": "If the attribute is not editable, its values and/or formula cannot be changed",
    "DG.CaseTable.attributeEditor.datePrecisionOptions": "year month day hour minute second",
    "DG.AttributeFormat.DatePrecision.year": "YYYY",
    "DG.AttributeFormat.DatePrecision.month": "MMM YYYY",
    "DG.AttributeFormat.DatePrecision.day": "MMM D, YYYY",
    "DG.AttributeFormat.DatePrecision.hour": "MMM D, YYYY HH:00",
    "DG.AttributeFormat.DatePrecision.minute": "MMM D, YYYY HH:mm",
    "DG.AttributeFormat.DatePrecision.second": "MMM D, YYYY HH:mm:ss",
    "DG.CaseCard.attrHintPlain": "%@",
    "DG.CaseCard.attrHintUnitsOnly": "%@ in %@",
    "DG.CaseCard.attrHintDescription": "%@: %@",
    "DG.CaseCard.attrHintFormula": "%@\n%@",
    "DG.AppController.optionMenuItems.help-forum": "Help Forum...",
    "DG.AppController.showHelpForumTitle": "Help Forum",
    "DG.Locale.name.el": "Greek",
    "DG.BarChartModel.cellTipNoLegendSingular": "%@ of %@ (%@%) is %@",
    "DG.BarChartModel.cellTipNoLegendPlural": "%@ of %@ (%@%) are %@",
    "DG.DataDisplayMenu.removeAttribute_top": "Remove Side-by-side Layout by %@",
    "DG.DataDisplayMenu.removeAttribute_right": "Remove Vertical Layout by %@",
    "DG.GraphView.layoutPlotsSideBySide": "Layout side-by-side by %@",
    "DG.GraphView.layoutPlotsVertically": "Layout vertically by %@",
    "DG.Undo.graph.makeStrokeSameAsFill": "Undo making stroke same as fill",
    "DG.Redo.graph.makeStrokeSameAsFill": "Redo making stroke same as fill",
    "DG.Undo.graph.makeStrokeIndependent": "Undo making stroke independent of fill",
    "DG.Redo.graph.makeStrokeIndependent": "Redo making stroke independent of fill",
    "DG.Inspector.strokeSameAsFill": "Stroke same color as fill",
    "DG.Formula.DateShortDaySunday": "Sun",
    "DG.Formula.DateShortDayMonday": "Mon",
    "DG.Formula.DateShortDayTuesday": "Tue",
    "DG.Formula.DateShortDayWednesday": "Wed",
    "DG.Formula.DateShortDayThursday": "Thu",
    "DG.Formula.DateShortDayFriday": "Fri",
    "DG.Formula.DateShortDaySaturday": "Sat",
    "DG.AttributeFormat.DatePrecision.millisecond": "MMM D, YYYY HH:mm:ss.SSS",
    "DG.CellAxis.other": "OTHER",
    "DG.PlottedAverageAdornment.madValueTitle": "±1 MAD, %@",
    "DG.Inspector.graphPlottedMeanAbsDev": "Mean Absolute Deviation",
    "DG.Undo.graph.showPlottedBoxPlot": "Undo showing box plot",
    "DG.Redo.graph.hidePlottedBoxPlot": "Redo hiding box plot",
    "DG.Undo.graph.hidePlottedBoxPlot": "Undo hiding box plot",
    "DG.Redo.graph.showPlottedBoxPlot": "Redo showing box plot",
    "DG.Undo.graph.showOutliers": "Undo showing outliers",
    "DG.Redo.graph.hideOutliers": "Redo hiding outliers",
    "DG.Undo.graph.hideOutliers": "Undo hiding outliers",
    "DG.Redo.graph.showOutliers": "Redo showing outliers",
    "DG.Inspector.graphBoxPlotShowOutliers": "Show Outliers",
    "DG.Locale.name.nb": "Bokmål",
    "DG.Locale.name.nn": "Nynorsk",
    "DG.CaseCard.newCaseToolTip": "Add an empty case to this collection"
});
