# Update codap3.concord.org/index-staging.html and codap3.cocnord.org/staging
name: Release v3 Staging
on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag for the version to use for index-staging.html
        required: true
env:
  BUCKET: models-resources
  PREFIX: codap3
  SRC_FILE: index-top.html
  workingDirectory: v3
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.V3_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.V3_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - run: >
          aws s3 cp
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/${{ env.SRC_FILE }}
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/index-staging.html
      - run: >
          aws s3 cp
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/${{ env.SRC_FILE }}
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/staging
