# This ai4vs release is separate from the beta, staging, and production releases
# so we can control the timing of the ai4vs release independently.
name: Release v3 ai4vs
on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag for the version to use for ai4vs
        required: true
env:
  BUCKET: models-resources
  PREFIX: codap3
  SRC_FILE: index-top.html
  DEST_FILE: ai4vs
  workingDirectory: v3
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: >
          aws s3 cp
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/${{ env.SRC_FILE }}
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/${{ env.DEST_FILE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.V3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.V3_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
